export type Difficulty = "Easy" | "Medium" | "Hard";
export type AiCategoryType =
  | "foundations"
  | "llms"
  | "prompt-engineering"
  | "embeddings-rag"
  | "tools-agents"
  | "evaluation"
  | "production"
  | "projects";

export type CategoryStatus = "not-started" | "in-progress" | "completed";

export interface AiTopic {
  id: string;
  slug: string;
  name: string;
  description: string;
  type: AiCategoryType;
  difficulty: Difficulty;
  estimatedMinutes: number;
  conceptCount: number;
  available: boolean;
}

export function aiFormatDuration(mins: number): string {
  if (mins < 60) return `~${mins} min`;
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return m === 0 ? `~${h} hr` : `~${h}h ${m}m`;
}

export const AI_TOPICS: AiTopic[] = [
  // ── Foundations ───────────────────────────────────────────────────────────
  {
    id: "ai-engineering-fundamentals",
    slug: "ai-engineering-fundamentals",
    name: "AI Engineering Fundamentals",
    description: "AI vs ML vs Deep Learning, generative AI, the AI application lifecycle and engineering mindset.",
    type: "foundations",
    difficulty: "Easy",
    estimatedMinutes: 60,
    conceptCount: 7,
    available: true,
  },
  {
    id: "python-for-ai",
    slug: "python-for-ai",
    name: "Python for AI Engineering",
    description: "NumPy, Pandas, virtual environments, API calls and data processing pipelines.",
    type: "foundations",
    difficulty: "Easy",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: true,
  },
  {
    id: "ml-fundamentals",
    slug: "ml-fundamentals",
    name: "Machine Learning Fundamentals",
    description: "Features, labels, training, validation, testing and inference fundamentals.",
    type: "foundations",
    difficulty: "Easy",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: true,
  },
  {
    id: "supervised-learning",
    slug: "supervised-learning",
    name: "Supervised Learning",
    description: "Classification, regression and how models learn from labeled data.",
    type: "foundations",
    difficulty: "Easy",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: true,
  },
  {
    id: "unsupervised-learning",
    slug: "unsupervised-learning",
    name: "Unsupervised Learning",
    description: "Clustering, dimensionality reduction and discovering structure in unlabeled data.",
    type: "foundations",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: true,
  },
  {
    id: "model-evaluation",
    slug: "model-evaluation",
    name: "Model Evaluation",
    description: "Accuracy, precision, recall, F1, ROC-AUC and evaluation methodology.",
    type: "foundations",
    difficulty: "Easy",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: true,
  },
  {
    id: "overfitting-underfitting",
    slug: "overfitting-underfitting",
    name: "Overfitting & Underfitting",
    description: "Bias-variance trade-off, regularization techniques and cross-validation.",
    type: "foundations",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: true,
  },
  {
    id: "feature-engineering",
    slug: "feature-engineering",
    name: "Feature Engineering",
    description: "Feature selection, normalization, encoding and transformations for ML.",
    type: "foundations",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: true,
  },
  {
    id: "neural-networks",
    slug: "neural-networks",
    name: "Neural Networks",
    description: "Layers, neurons, weights, activation functions and the forward pass.",
    type: "foundations",
    difficulty: "Medium",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: true,
  },
  {
    id: "transformer-architecture",
    slug: "transformer-architecture",
    name: "Transformer Architecture",
    description: "Self-attention, multi-head attention, positional encoding and the encoder-decoder stack.",
    type: "foundations",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: true,
  },
  {
    id: "embeddings-fundamentals",
    slug: "embeddings-fundamentals",
    name: "Embeddings",
    description: "Vector representations, semantic similarity and how text becomes numbers.",
    type: "foundations",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "model-finetuning-concepts",
    slug: "model-finetuning-concepts",
    name: "Model Fine-Tuning Concepts",
    description: "Full fine-tuning, LoRA, PEFT and when fine-tuning outperforms prompting.",
    type: "foundations",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  // ── LLMs ──────────────────────────────────────────────────────────────────
  {
    id: "large-language-models",
    slug: "large-language-models",
    name: "Large Language Models",
    description: "How LLMs work, pretraining, scale and the emergent capabilities landscape.",
    type: "llms",
    difficulty: "Medium",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "tokens-tokenization",
    slug: "tokens-tokenization",
    name: "Tokens & Tokenization",
    description: "BPE, token counts, how tokenization affects cost and context windows.",
    type: "llms",
    difficulty: "Easy",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "context-windows",
    slug: "context-windows",
    name: "Context Windows",
    description: "Context limits, how attention scales, and strategies for long-context tasks.",
    type: "llms",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "pretraining-instruction-tuning",
    slug: "pretraining-instruction-tuning",
    name: "Pretraining & Instruction Tuning",
    description: "How LLMs are trained, instruction tuning, RLHF and alignment.",
    type: "llms",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "temperature-sampling",
    slug: "temperature-sampling",
    name: "Temperature & Sampling",
    description: "Temperature, top-p, top-k sampling and how to control LLM output.",
    type: "llms",
    difficulty: "Easy",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "model-selection",
    slug: "model-selection",
    name: "Model Selection",
    description: "Comparing models by capability, cost, latency and context length for production.",
    type: "llms",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "llm-inference",
    slug: "llm-inference",
    name: "LLM Inference",
    description: "Batching, KV cache, quantization and inference optimization for production LLMs.",
    type: "llms",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  // ── Prompt Engineering ────────────────────────────────────────────────────
  {
    id: "prompt-engineering-fundamentals",
    slug: "prompt-engineering-fundamentals",
    name: "Prompt Engineering Fundamentals",
    description: "Principles of effective prompts, instruction clarity and output formatting.",
    type: "prompt-engineering",
    difficulty: "Easy",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "system-prompts",
    slug: "system-prompts",
    name: "System Prompts",
    description: "System prompt design, persona definition and behavioral constraints.",
    type: "prompt-engineering",
    difficulty: "Easy",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "few-shot-prompting",
    slug: "few-shot-prompting",
    name: "Few-Shot Prompting",
    description: "In-context learning, example selection and shot count trade-offs.",
    type: "prompt-engineering",
    difficulty: "Easy",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "chain-of-thought",
    slug: "chain-of-thought",
    name: "Chain-of-Thought Prompting",
    description: "CoT, zero-shot CoT, ReAct patterns and reasoning chain design.",
    type: "prompt-engineering",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "structured-outputs",
    slug: "structured-outputs",
    name: "Structured Outputs & JSON",
    description: "Forcing JSON output, output schemas, validation and error recovery.",
    type: "prompt-engineering",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "prompt-templates",
    slug: "prompt-templates",
    name: "Prompt Templates",
    description: "Parameterized templates, Jinja2 patterns and template management.",
    type: "prompt-engineering",
    difficulty: "Easy",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "prompt-versioning",
    slug: "prompt-versioning",
    name: "Prompt Versioning",
    description: "Prompt version control, A/B testing prompts and regression detection.",
    type: "prompt-engineering",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "prompt-security",
    slug: "prompt-security",
    name: "Prompt Security",
    description: "Prompt injection, jailbreaking, defense patterns and security evaluation.",
    type: "prompt-engineering",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  // ── Embeddings & RAG ──────────────────────────────────────────────────────
  {
    id: "semantic-search",
    slug: "semantic-search",
    name: "Semantic Search",
    description: "Embedding-based retrieval, similarity metrics and search quality.",
    type: "embeddings-rag",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "vector-databases",
    slug: "vector-databases",
    name: "Vector Databases",
    description: "Pinecone, Weaviate, pgvector — indexing, querying and managing embeddings at scale.",
    type: "embeddings-rag",
    difficulty: "Medium",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "chunking-strategies",
    slug: "chunking-strategies",
    name: "Document Chunking",
    description: "Fixed-size, recursive, semantic chunking and optimal chunk strategies.",
    type: "embeddings-rag",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "hybrid-search",
    slug: "hybrid-search",
    name: "Hybrid Search & Reranking",
    description: "Combining BM25 and vector search, cross-encoder reranking and fusion.",
    type: "embeddings-rag",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  {
    id: "rag-fundamentals",
    slug: "rag-fundamentals",
    name: "RAG Fundamentals",
    description: "Retrieval-Augmented Generation: architecture, flow and when to use RAG vs fine-tuning.",
    type: "embeddings-rag",
    difficulty: "Medium",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "document-ingestion",
    slug: "document-ingestion",
    name: "Document Ingestion Pipelines",
    description: "PDF, HTML, markdown parsing, metadata extraction and pipeline design.",
    type: "embeddings-rag",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "embedding-pipelines",
    slug: "embedding-pipelines",
    name: "Embedding Pipelines",
    description: "Batch embedding, incremental updates, embedding model selection and cost.",
    type: "embeddings-rag",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "rag-prompting",
    slug: "rag-prompting",
    name: "RAG Prompting",
    description: "Context window packing, context construction and grounding prompts.",
    type: "embeddings-rag",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "rag-evaluation",
    slug: "rag-evaluation",
    name: "RAG Evaluation",
    description: "Faithfulness, relevance, answer quality and automated RAG evaluation.",
    type: "embeddings-rag",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "advanced-rag",
    slug: "advanced-rag",
    name: "Advanced RAG",
    description: "Query rewriting, HyDE, iterative retrieval, multi-hop RAG patterns.",
    type: "embeddings-rag",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },
  {
    id: "production-rag",
    slug: "production-rag",
    name: "Production RAG",
    description: "Caching, latency optimization, monitoring and scaling RAG in production.",
    type: "embeddings-rag",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },
  // ── Tools & Agents ────────────────────────────────────────────────────────
  {
    id: "tool-calling",
    slug: "tool-calling",
    name: "Tool Calling",
    description: "Function calling APIs, tool schemas, single-tool and multi-tool invocation.",
    type: "tools-agents",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "structured-tool-schemas",
    slug: "structured-tool-schemas",
    name: "Tool Schema Design",
    description: "JSON schema for tools, parameter validation and error handling.",
    type: "tools-agents",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "api-database-tools",
    slug: "api-database-tools",
    name: "API & Database Tools",
    description: "Connecting LLMs to REST APIs, SQL databases, search engines.",
    type: "tools-agents",
    difficulty: "Medium",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  {
    id: "tool-security",
    slug: "tool-security",
    name: "Tool Security",
    description: "Authorization, sandboxing, rate limiting and preventing tool abuse.",
    type: "tools-agents",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "ai-agent-fundamentals",
    slug: "ai-agent-fundamentals",
    name: "AI Agent Fundamentals",
    description: "The agent loop: observe, think, act, observe. Agent architectures overview.",
    type: "tools-agents",
    difficulty: "Medium",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "agent-loops",
    slug: "agent-loops",
    name: "Agent Loops & Planning",
    description: "ReAct, plan-and-execute, reflection loops and stopping conditions.",
    type: "tools-agents",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "agent-memory",
    slug: "agent-memory",
    name: "Agent Memory",
    description: "Working memory, episodic memory, semantic memory and memory management.",
    type: "tools-agents",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "multi-agent-systems",
    slug: "multi-agent-systems",
    name: "Multi-Agent Systems",
    description: "Orchestrator-worker, peer agents, handoff protocols and agent coordination.",
    type: "tools-agents",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },
  {
    id: "agent-workflows",
    slug: "agent-workflows",
    name: "AI Workflows",
    description: "Deterministic vs agentic workflows, when to use each and pipeline design.",
    type: "tools-agents",
    difficulty: "Medium",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  {
    id: "human-in-the-loop",
    slug: "human-in-the-loop",
    name: "Human-in-the-Loop",
    description: "Approval gates, escalation, HITL patterns and trust boundaries for agents.",
    type: "tools-agents",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "agent-reliability",
    slug: "agent-reliability",
    name: "Agent Reliability",
    description: "Retry logic, fallbacks, verification steps and reliable agent patterns.",
    type: "tools-agents",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  // ── Evaluation ────────────────────────────────────────────────────────────
  {
    id: "ai-evaluation-fundamentals",
    slug: "ai-evaluation-fundamentals",
    name: "AI Evaluation Fundamentals",
    description: "Why evaluation is hard, online vs offline evaluation and metrics overview.",
    type: "evaluation",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "golden-datasets",
    slug: "golden-datasets",
    name: "Golden Datasets",
    description: "Creating, curating and maintaining golden test sets for LLM evaluation.",
    type: "evaluation",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "llm-as-judge",
    slug: "llm-as-judge",
    name: "LLM-as-a-Judge",
    description: "Using LLMs to evaluate LLM outputs, rubric design and bias detection.",
    type: "evaluation",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  {
    id: "hallucination-detection",
    slug: "hallucination-detection",
    name: "Hallucination Detection",
    description: "Faithfulness scoring, groundedness checks and automated hallucination detection.",
    type: "evaluation",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  {
    id: "retrieval-evaluation",
    slug: "retrieval-evaluation",
    name: "Retrieval Evaluation",
    description: "NDCG, MRR, recall@k and end-to-end RAG evaluation metrics.",
    type: "evaluation",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  {
    id: "regression-testing-ai",
    slug: "regression-testing-ai",
    name: "Regression Testing for AI",
    description: "Preventing prompt regressions, CI for AI, snapshot testing.",
    type: "evaluation",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  {
    id: "evaluation-pipelines",
    slug: "evaluation-pipelines",
    name: "Evaluation Pipelines",
    description: "Automated eval workflows, LangSmith, Phoenix, Ragas and CI integration.",
    type: "evaluation",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  // ── Production ────────────────────────────────────────────────────────────
  {
    id: "ai-application-architecture",
    slug: "ai-application-architecture",
    name: "AI Application Architecture",
    description: "Request flow, LLM gateway, caching, streaming and service boundaries.",
    type: "production",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },
  {
    id: "model-apis",
    slug: "model-apis",
    name: "Model APIs & Providers",
    description: "OpenAI, Anthropic, Google, Cohere APIs — routing, fallbacks, versioning.",
    type: "production",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "streaming-responses",
    slug: "streaming-responses",
    name: "Streaming Responses",
    description: "SSE, chunked responses, streaming UX and cancellation handling.",
    type: "production",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "conversation-memory",
    slug: "conversation-memory",
    name: "Conversation Memory",
    description: "Session management, context compression and stateful conversations.",
    type: "production",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "ai-caching",
    slug: "ai-caching",
    name: "AI Caching",
    description: "Semantic cache, exact cache, prompt caching and cost reduction strategies.",
    type: "production",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 6,
    available: false,
  },
  {
    id: "token-cost-optimization",
    slug: "token-cost-optimization",
    name: "Cost Optimization",
    description: "Token counting, batching, model routing, caching and cost monitoring.",
    type: "production",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "ai-observability",
    slug: "ai-observability",
    name: "AI Observability",
    description: "Tracing, logging, latency and quality dashboards for production AI.",
    type: "production",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "prompt-injection-security",
    slug: "prompt-injection-security",
    name: "AI Security",
    description: "Prompt injection, data leakage, PII protection, guardrails and abuse prevention.",
    type: "production",
    difficulty: "Hard",
    estimatedMinutes: 75,
    conceptCount: 7,
    available: false,
  },
  {
    id: "ai-deployment",
    slug: "ai-deployment",
    name: "AI Deployment",
    description: "Containerization, model APIs, GPU fundamentals and deployment patterns.",
    type: "production",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "production-ai-architecture",
    slug: "production-ai-architecture",
    name: "Production AI Architecture",
    description: "End-to-end production AI system: gateway, RAG, agents, eval, monitoring.",
    type: "production",
    difficulty: "Hard",
    estimatedMinutes: 120,
    conceptCount: 10,
    available: false,
  },
  // ── Projects ──────────────────────────────────────────────────────────────
  {
    id: "build-chatbot",
    slug: "build-chatbot",
    name: "Build a Chatbot",
    description: "End-to-end chatbot with conversation memory, system prompts and streaming.",
    type: "projects",
    difficulty: "Easy",
    estimatedMinutes: 120,
    conceptCount: 8,
    available: false,
  },
  {
    id: "build-rag-app",
    slug: "build-rag-app",
    name: "Build a RAG Application",
    description: "PDF ingestion, embedding, vector search, retrieval and grounded Q&A.",
    type: "projects",
    difficulty: "Medium",
    estimatedMinutes: 180,
    conceptCount: 10,
    available: false,
  },
  {
    id: "build-pdf-assistant",
    slug: "build-pdf-assistant",
    name: "Build a PDF AI Assistant",
    description: "Multi-PDF Q&A with metadata filtering, citations and answer grounding.",
    type: "projects",
    difficulty: "Medium",
    estimatedMinutes: 150,
    conceptCount: 9,
    available: false,
  },
  {
    id: "build-ai-agent",
    slug: "build-ai-agent",
    name: "Build an AI Customer Support Agent",
    description: "Tool-using support agent with escalation, memory and evaluation harness.",
    type: "projects",
    difficulty: "Hard",
    estimatedMinutes: 180,
    conceptCount: 12,
    available: false,
  },
  {
    id: "build-coding-assistant",
    slug: "build-coding-assistant",
    name: "Build a Coding Assistant",
    description: "Code-aware assistant with context retrieval, test generation and review.",
    type: "projects",
    difficulty: "Hard",
    estimatedMinutes: 180,
    conceptCount: 10,
    available: false,
  },
  {
    id: "build-ai-search",
    slug: "build-ai-search",
    name: "Build an AI Search Engine",
    description: "Semantic search with hybrid retrieval, reranking and quality evaluation.",
    type: "projects",
    difficulty: "Hard",
    estimatedMinutes: 150,
    conceptCount: 10,
    available: false,
  },
  {
    id: "build-multi-agent",
    slug: "build-multi-agent",
    name: "Build a Multi-Agent Research System",
    description: "Orchestrated agents that plan, search, synthesize and verify information.",
    type: "projects",
    difficulty: "Hard",
    estimatedMinutes: 240,
    conceptCount: 14,
    available: false,
  },
  {
    id: "build-production-ai",
    slug: "build-production-ai",
    name: "Build a Production AI Platform",
    description: "Full production system: auth, rate limiting, eval pipeline, observability.",
    type: "projects",
    difficulty: "Hard",
    estimatedMinutes: 300,
    conceptCount: 16,
    available: false,
  },
];

export const AI_CATEGORY_TABS = [
  { value: "all", label: "All" },
  { value: "foundations", label: "Foundations" },
  { value: "llms", label: "LLMs" },
  { value: "prompt-engineering", label: "Prompting" },
  { value: "embeddings-rag", label: "RAG" },
  { value: "tools-agents", label: "Agents" },
  { value: "evaluation", label: "Evaluation" },
  { value: "production", label: "Production" },
  { value: "projects", label: "Projects" },
] as const;
