export type Difficulty = "Easy" | "Medium" | "Hard";
export type JavaCategoryType =
  | "core-java"
  | "collections"
  | "generics"
  | "modern-java"
  | "concurrency"
  | "jvm"
  | "advanced-java"
  | "design-patterns"
  | "spring"
  | "testing"
  | "database";

export type CategoryStatus = "not-started" | "in-progress" | "completed";

export interface JavaTopic {
  id: string;
  slug: string;
  name: string;
  description: string;
  type: JavaCategoryType;
  difficulty: Difficulty;
  estimatedMinutes: number;
  conceptCount: number;
  available: boolean;
}

export const JAVA_TOPICS: JavaTopic[] = [
  // ── Core Java ────────────────────────────────────────────────────────────
  {
    id: "java-fundamentals",
    slug: "java-fundamentals",
    name: "Java Fundamentals",
    description: "Variables, primitive types, operators, control flow, type casting and JVM/JDK/JRE overview.",
    type: "core-java",
    difficulty: "Easy",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: true,
  },
  {
    id: "methods-program-structure",
    slug: "methods-program-structure",
    name: "Methods & Program Structure",
    description: "Methods, parameters, return values, overloading, scope and package organisation.",
    type: "core-java",
    difficulty: "Easy",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: true,
  },
  {
    id: "oop",
    slug: "oop",
    name: "Object-Oriented Programming",
    description: "Classes, objects, encapsulation, inheritance, polymorphism and abstraction.",
    type: "core-java",
    difficulty: "Easy",
    estimatedMinutes: 120,
    conceptCount: 10,
    available: true,
  },
  {
    id: "interfaces-abstract",
    slug: "interfaces-abstract",
    name: "Interfaces & Abstract Classes",
    description: "Interfaces, default methods, abstract classes and composition vs inheritance.",
    type: "core-java",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: true,
  },
  {
    id: "exception-handling",
    slug: "exception-handling",
    name: "Exception Handling",
    description: "try/catch/finally, checked vs unchecked exceptions, custom exceptions and best practices.",
    type: "core-java",
    difficulty: "Easy",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: true,
  },
  {
    id: "strings-immutability",
    slug: "strings-immutability",
    name: "Strings & Immutability",
    description: "String pool, StringBuilder, StringBuffer and the implications of immutability.",
    type: "core-java",
    difficulty: "Easy",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: true,
  },
  {
    id: "enums-records-sealed",
    slug: "enums-records-sealed",
    name: "Enums, Records & Sealed Classes",
    description: "enum, records, sealed classes and pattern matching concepts.",
    type: "core-java",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },

  // ── Collections ──────────────────────────────────────────────────────────
  {
    id: "collections-framework",
    slug: "collections-framework",
    name: "Collections Framework",
    description: "List, Set, Map, Queue and Deque — the full Java collections hierarchy.",
    type: "collections",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: true,
  },
  {
    id: "arraylist-linkedlist",
    slug: "arraylist-linkedlist",
    name: "ArrayList & LinkedList",
    description: "Internal structure, time complexity, resizing strategy and when to use each.",
    type: "collections",
    difficulty: "Easy",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "hashmap-hashset",
    slug: "hashmap-hashset",
    name: "HashMap & HashSet",
    description: "Hashing, buckets, collision resolution, equals/hashCode contract.",
    type: "collections",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "treemap-treeset",
    slug: "treemap-treeset",
    name: "TreeMap & TreeSet",
    description: "Sorted ordering, Red-Black tree internals, NavigableMap operations.",
    type: "collections",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "queues-deques-pq",
    slug: "queues-deques-pq",
    name: "Queues, Deques & PriorityQueue",
    description: "ArrayDeque, LinkedList as Deque, PriorityQueue heap semantics.",
    type: "collections",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "collections-performance",
    slug: "collections-performance",
    name: "Collections Performance Guide",
    description: "Choosing the right collection — time/space tradeoffs and real-world patterns.",
    type: "collections",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 4,
    available: false,
  },

  // ── Generics ─────────────────────────────────────────────────────────────
  {
    id: "generics-fundamentals",
    slug: "generics-fundamentals",
    name: "Generics Fundamentals",
    description: "Type parameters, generic classes and generic interfaces.",
    type: "generics",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "wildcards-bounded",
    slug: "wildcards-bounded",
    name: "Wildcards & Bounded Types",
    description: "?, extends, super — PECS principle and use-site variance.",
    type: "generics",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "generic-methods-erasure",
    slug: "generic-methods-erasure",
    name: "Generic Methods & Type Erasure",
    description: "Generic static methods, type inference and the runtime implications of erasure.",
    type: "generics",
    difficulty: "Hard",
    estimatedMinutes: 45,
    conceptCount: 4,
    available: false,
  },

  // ── Modern Java ───────────────────────────────────────────────────────────
  {
    id: "lambda-expressions",
    slug: "lambda-expressions",
    name: "Lambda Expressions",
    description: "Syntax, effectively-final variables, method references and functional style.",
    type: "modern-java",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "functional-interfaces",
    slug: "functional-interfaces",
    name: "Functional Interfaces",
    description: "Function, Predicate, Consumer, Supplier and composing behaviours.",
    type: "modern-java",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "stream-api",
    slug: "stream-api",
    name: "Stream API",
    description: "Lazy evaluation, intermediate vs terminal operations, parallel streams.",
    type: "modern-java",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },
  {
    id: "stream-operations",
    slug: "stream-operations",
    name: "Stream Operations Deep Dive",
    description: "map, filter, reduce, flatMap, collect, groupingBy and Collectors.",
    type: "modern-java",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 7,
    available: false,
  },
  {
    id: "optional",
    slug: "optional",
    name: "Optional",
    description: "Representing absent values, avoiding NullPointerException, composition patterns.",
    type: "modern-java",
    difficulty: "Easy",
    estimatedMinutes: 30,
    conceptCount: 4,
    available: false,
  },
  {
    id: "date-time-api",
    slug: "date-time-api",
    name: "Date & Time API",
    description: "LocalDate, LocalDateTime, ZonedDateTime, Duration, Period and formatting.",
    type: "modern-java",
    difficulty: "Easy",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "modern-java-features",
    slug: "modern-java-features",
    name: "Modern Java Features",
    description: "Java 8–21+: pattern matching, records, text blocks, switch expressions, virtual threads.",
    type: "modern-java",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },

  // ── Concurrency ───────────────────────────────────────────────────────────
  {
    id: "threads-fundamentals",
    slug: "threads-fundamentals",
    name: "Threads Fundamentals",
    description: "Creating threads, Runnable, Thread lifecycle and the OS scheduler.",
    type: "concurrency",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "synchronization",
    slug: "synchronization",
    name: "Synchronization",
    description: "synchronized keyword, intrinsic locks, wait/notify and volatile.",
    type: "concurrency",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "locks-atomic",
    slug: "locks-atomic",
    name: "Locks & Atomic Variables",
    description: "ReentrantLock, ReadWriteLock, AtomicInteger and lock-free algorithms.",
    type: "concurrency",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "executor-framework",
    slug: "executor-framework",
    name: "Executor Framework",
    description: "ThreadPoolExecutor, fixed/cached/scheduled pools, Future and Callable.",
    type: "concurrency",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "completable-future",
    slug: "completable-future",
    name: "CompletableFuture",
    description: "Async composition, thenApply/thenCompose, exception handling and joining.",
    type: "concurrency",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "concurrent-collections",
    slug: "concurrent-collections",
    name: "Concurrent Collections",
    description: "ConcurrentHashMap, CopyOnWriteArrayList, BlockingQueue and thread-safe patterns.",
    type: "concurrency",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "java-memory-model",
    slug: "java-memory-model",
    name: "Java Memory Model",
    description: "happens-before, visibility, atomicity and why volatile is not always enough.",
    type: "concurrency",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "race-conditions-deadlocks",
    slug: "race-conditions-deadlocks",
    name: "Race Conditions & Deadlocks",
    description: "Diagnosing deadlock, livelock, starvation and prevention strategies.",
    type: "concurrency",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "virtual-threads",
    slug: "virtual-threads",
    name: "Virtual Threads",
    description: "Project Loom, structured concurrency, carrier threads and performance implications.",
    type: "concurrency",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },

  // ── JVM ───────────────────────────────────────────────────────────────────
  {
    id: "jvm-architecture",
    slug: "jvm-architecture",
    name: "JVM Architecture",
    description: "Class loader, bytecode execution, runtime data areas and the execution engine.",
    type: "jvm",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "heap-stack",
    slug: "heap-stack",
    name: "Heap & Stack",
    description: "Young gen, old gen, metaspace, stack frames and object allocation.",
    type: "jvm",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "garbage-collection",
    slug: "garbage-collection",
    name: "Garbage Collection",
    description: "Mark-and-sweep, generational GC, GC roots, minor vs major GC.",
    type: "jvm",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "g1gc-zgc",
    slug: "g1gc-zgc",
    name: "G1GC, ZGC & Shenandoah",
    description: "Modern low-pause collectors — regions, concurrent marking and tuning flags.",
    type: "jvm",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 6,
    available: false,
  },
  {
    id: "jit-compilation",
    slug: "jit-compilation",
    name: "JIT Compilation",
    description: "C1/C2 compiler, tiered compilation, inlining, escape analysis.",
    type: "jvm",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "jvm-diagnostics",
    slug: "jvm-diagnostics",
    name: "JVM Diagnostics & Profiling",
    description: "jstack, jmap, jcmd, async-profiler, flame graphs and memory leak hunting.",
    type: "jvm",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },

  // ── Advanced Java ─────────────────────────────────────────────────────────
  {
    id: "reflection",
    slug: "reflection",
    name: "Reflection",
    description: "Inspecting and invoking classes, methods, fields at runtime.",
    type: "advanced-java",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "annotations",
    slug: "annotations",
    name: "Annotations",
    description: "Built-in annotations, custom annotation processors and retention policies.",
    type: "advanced-java",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 5,
    available: false,
  },
  {
    id: "modules",
    slug: "modules",
    name: "Java Modules (JPMS)",
    description: "module-info.java, exports, requires, strong encapsulation and migration.",
    type: "advanced-java",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "nio-networking",
    slug: "nio-networking",
    name: "NIO & Networking",
    description: "Channels, buffers, selectors, non-blocking I/O and socket programming.",
    type: "advanced-java",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 6,
    available: false,
  },
  {
    id: "serialization",
    slug: "serialization",
    name: "Serialization",
    description: "Java serialization, Externalizable, serial version UID and security risks.",
    type: "advanced-java",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 4,
    available: false,
  },

  // ── Design Patterns ───────────────────────────────────────────────────────
  {
    id: "solid-principles",
    slug: "solid-principles",
    name: "SOLID Principles",
    description: "SRP, OCP, LSP, ISP, DIP — with Java examples and real-world violations.",
    type: "design-patterns",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "creational-patterns",
    slug: "creational-patterns",
    name: "Creational Patterns",
    description: "Factory, Abstract Factory, Builder, Singleton and Prototype with Java.",
    type: "design-patterns",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "structural-patterns",
    slug: "structural-patterns",
    name: "Structural Patterns",
    description: "Adapter, Decorator, Facade, Proxy, Composite and Bridge.",
    type: "design-patterns",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "behavioral-patterns",
    slug: "behavioral-patterns",
    name: "Behavioral Patterns",
    description: "Strategy, Observer, Command, Iterator, Template Method and Chain of Responsibility.",
    type: "design-patterns",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },

  // ── Spring ────────────────────────────────────────────────────────────────
  {
    id: "spring-fundamentals",
    slug: "spring-fundamentals",
    name: "Spring Fundamentals",
    description: "IoC container, application context, bean lifecycle and scopes.",
    type: "spring",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "dependency-injection",
    slug: "dependency-injection",
    name: "Dependency Injection",
    description: "Constructor, setter and field injection — best practices and pitfalls.",
    type: "spring",
    difficulty: "Easy",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "spring-boot",
    slug: "spring-boot",
    name: "Spring Boot",
    description: "Auto-configuration, starters, application.yml, profiles and actuator.",
    type: "spring",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },
  {
    id: "spring-mvc-rest",
    slug: "spring-mvc-rest",
    name: "Spring MVC & REST APIs",
    description: "Controllers, request mapping, validation, exception handlers and content negotiation.",
    type: "spring",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 8,
    available: false,
  },
  {
    id: "spring-data-jpa",
    slug: "spring-data-jpa",
    name: "Spring Data JPA",
    description: "Repositories, JPQL, derived queries, pagination and projections.",
    type: "spring",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "spring-security",
    slug: "spring-security",
    name: "Spring Security",
    description: "Authentication, authorization, JWT, OAuth2 and security filter chain.",
    type: "spring",
    difficulty: "Hard",
    estimatedMinutes: 120,
    conceptCount: 8,
    available: false,
  },
  {
    id: "spring-transactions",
    slug: "spring-transactions",
    name: "Transactions",
    description: "@Transactional propagation, isolation levels and common rollback pitfalls.",
    type: "spring",
    difficulty: "Hard",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },

  // ── Testing ───────────────────────────────────────────────────────────────
  {
    id: "junit5",
    slug: "junit5",
    name: "JUnit 5",
    description: "@Test, assertions, parameterized tests, lifecycle hooks and extensions.",
    type: "testing",
    difficulty: "Easy",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "mockito",
    slug: "mockito",
    name: "Mockito",
    description: "Mocking, stubbing, argument captors, verification and spy objects.",
    type: "testing",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 6,
    available: false,
  },
  {
    id: "integration-testing",
    slug: "integration-testing",
    name: "Integration Testing",
    description: "@SpringBootTest, MockMvc, TestRestTemplate and sliced test contexts.",
    type: "testing",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "testcontainers",
    slug: "testcontainers",
    name: "Testcontainers",
    description: "Real database containers in tests, JUnit integration and reuse strategies.",
    type: "testing",
    difficulty: "Medium",
    estimatedMinutes: 45,
    conceptCount: 4,
    available: false,
  },
  {
    id: "testing-strategy",
    slug: "testing-strategy",
    name: "Testing Strategy",
    description: "Test pyramid, contract testing, mutation testing and coverage goals.",
    type: "testing",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },

  // ── Database ──────────────────────────────────────────────────────────────
  {
    id: "jdbc",
    slug: "jdbc",
    name: "JDBC",
    description: "Connection, PreparedStatement, ResultSet, transactions and connection pooling.",
    type: "database",
    difficulty: "Medium",
    estimatedMinutes: 60,
    conceptCount: 5,
    available: false,
  },
  {
    id: "jpa-hibernate",
    slug: "jpa-hibernate",
    name: "JPA & Hibernate",
    description: "Entities, mappings, session/entity manager, lazy vs eager loading.",
    type: "database",
    difficulty: "Hard",
    estimatedMinutes: 120,
    conceptCount: 9,
    available: false,
  },
  {
    id: "hibernate-performance",
    slug: "hibernate-performance",
    name: "Hibernate Performance",
    description: "N+1 problem, batch fetching, second-level cache and query optimisation.",
    type: "database",
    difficulty: "Hard",
    estimatedMinutes: 90,
    conceptCount: 7,
    available: false,
  },
  {
    id: "caching-logging",
    slug: "caching-logging",
    name: "Caching & Observability",
    description: "Spring Cache, Redis integration, structured logging with Logback and Micrometer metrics.",
    type: "database",
    difficulty: "Medium",
    estimatedMinutes: 90,
    conceptCount: 6,
    available: false,
  },
];

export const JAVA_CATEGORY_TABS = [
  { value: "all",             label: "All" },
  { value: "core-java",       label: "Core Java" },
  { value: "collections",     label: "Collections" },
  { value: "modern-java",     label: "Modern Java" },
  { value: "concurrency",     label: "Concurrency" },
  { value: "jvm",             label: "JVM" },
  { value: "spring",          label: "Spring" },
  { value: "advanced-java",   label: "Advanced" },
] as const;

export function javaFormatDuration(minutes: number): string {
  if (minutes < 60) return `~${minutes} mins`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m === 0 ? `~${h} hr${h > 1 ? "s" : ""}` : `~${h}.${Math.round(m / 6)} hours`;
}
