-- V114: Hindi A1 lessons 51-60
-- Hex: 51=0x33, 52=0x34, 53=0x35, 54=0x36, 55=0x37, 56=0x38, 57=0x39, 58=0x3a, 59=0x3b, 60=0x3c
-- A1 rewards: xp:100, coins:50
-- English-only metadata; Hindi script only in JSONB content fields

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('cc000000-0000-0000-0000-000000000033','hi-a1-l051','City and Village','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000034','hi-a1-l052','Traffic and Transport Rules','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000035','hi-a1-l053','Fairs and Markets','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000036','hi-a1-l054','Household Chores','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000037','hi-a1-l055','Children and Play','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000038','hi-a1-l056','Neighbourhood and Community','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000039','hi-a1-l057','Safety and Emergency','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-00000000003a','hi-a1-l058','News and Current Events','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-00000000003b','hi-a1-l059','Hobbies and Free Time','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-00000000003c','hi-a1-l060','Opinions and Preferences','language','hi','A1','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000033',1,'APPROVED','PUBLISHED',
'{"objectives":["Name city and village features in Hindi","Use X में Y है for location","Compare city and village life"],"explanation":{"intro":"City and village vocabulary covers urban and rural life, key landmarks, and how to describe where you live.","culturalNote":"India has over 640,000 villages (gaon) — the majority of Indians still live in rural areas. The shift toward cities (shahar) is one of the defining stories of modern India. Key cities: Mumbai (financial), Delhi (capital), Bengaluru (tech), Chennai (manufacturing), Kolkata (culture). Key Hindi: shahar = city, gaon/gram = village. Panchayat (gram panchayat) = village council — local self-government at village level. Key services differ: electricity (bijli), water (paani), roads (sadak), hospital (aspatal), school (vidyaalay) — urban areas have better access. Metros (metro rail) — Delhi Metro is South Asia''s largest. The distinction between shahar and gaon is deeply cultural — ''city person'' (shahri) vs ''village person'' (gaonwala) carries social meaning in Indian discourse."},"examples":[{"hindi":"मैं एक बड़े शहर में रहता हूँ।","transliteration":"Main ek bade shahar mein rehta hoon.","english":"I live in a big city."},{"hindi":"गाँव में जीवन शांत होता है।","transliteration":"Gaon mein jeevan shaant hota hai.","english":"Life in the village is peaceful."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe city and village life in Hindi."}}',
'{"items":[{"word":"शहर","translation":"city","transliteration":"shahar","pronunciation":"sha-HAR","example":"बड़ा शहर।"},{"word":"गाँव","translation":"village","transliteration":"gaon","pronunciation":"GAON","example":"मेरा गाँव।"},{"word":"सड़क","translation":"road/street","transliteration":"sadak","pronunciation":"SA-dak","example":"लंबी सड़क।"},{"word":"बाज़ार","translation":"market/bazaar","transliteration":"baazaar","pronunciation":"baa-ZAAR","example":"बड़ा बाज़ार।"},{"word":"अस्पताल","translation":"hospital","transliteration":"aspatal","pronunciation":"as-pa-TAL","example":"नज़दीक अस्पताल।"},{"word":"शांत","translation":"peaceful/quiet","transliteration":"shaant","pronunciation":"SHAANT","example":"शांत जीवन।"}]}',
'{"title":"Adjective + noun agreement — big/small with place nouns","pattern":"बड़ा (bada) = big (masculine), बड़ी (badi) = big (feminine), बड़े (bade) = big (oblique masculine). Adjectives inflect to match noun gender and case. शहर (masculine) → बड़ा शहर. सड़क (feminine) → बड़ी सड़क. Oblique: बड़े शहर में (in the big city).","explanation":"Adjective agreement: -a ending adjectives change to match noun gender. Masculine direct: बड़ा. Feminine direct: बड़ी. Masculine oblique: बड़े. Feminine oblique: बड़ी (same as direct). Examples: बड़ा घर (big house — m), बड़ी दुकान (big shop — f), बड़े घर में (in the big house — oblique). Invariant adjectives (ending in consonant or ई): do not change — शांत (shaant) stays शांत regardless.","examples":[{"sentence":"वह एक छोटे गाँव में रहती है।","transliteration":"Vah ek chhote gaon mein rehti hai.","translation":"She lives in a small village."},{"sentence":"बड़ी सड़कें शहर में हैं।","transliteration":"Badi sadken shahar mein hain.","translation":"Big roads are in the city."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"शहर means?","options":["city","village","road","market"],"correctAnswer":"city"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I live in a big city.","options":["मैं एक बड़े शहर में रहता हूँ।","मैं एक छोटे गाँव में रहता हूँ।","मैं एक बड़े गाँव में रहता हूँ।","मैं एक शहर में रहती हूँ।"],"correctAnswer":"मैं एक बड़े शहर में रहता हूँ।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"गाँव में जीवन ___ होता है।","options":["शांत","बड़ा","छोटा","लंबा"],"correctAnswer":"शांत"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She lives in a small village.","wordBankItems":["वह","एक","छोटे","गाँव","में","रहती","है","।"],"correctAnswer":"वह एक छोटे गाँव में रहती है ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"अस्पताल means?","options":["hospital","school","market","road"],"correctAnswer":"hospital"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000034',1,'APPROVED','PUBLISHED',
'{"objectives":["Name vehicles and transport in Hindi","Use X से जाना for travelling by vehicle","Follow basic traffic vocabulary"],"explanation":{"intro":"Transport vocabulary covers vehicles, roads, and how to describe getting from place to place in Hindi.","culturalNote":"India has one of the world''s largest road networks. Key transport: auto-rickshaw (auto-rikshaw — three-wheeler — ubiquitous in Indian cities), metro rail (Delhi, Mumbai, Bengaluru, Chennai, Hyderabad, Kolkata), bus (bas), train (tren/rail gadi), cycle-rickshaw, motorcycle (motorcycle/bike). Traffic rules: red light (laal batti), green light (hari batti), zebra crossing (zebra crossing/pedestrian crossing). India drives on the LEFT (inherited from British). Toll roads (toll naaka). National Highway (Rashtriya Rajmarg — NH). Key: Indian roads are famously chaotic — horn use is expected (''Please sound horn'' signs on trucks are iconic). Ola and Uber operate extensively. Auto-rickshaw fare: usually metered or negotiated."},"examples":[{"hindi":"मैं बस से काम पर जाता हूँ।","transliteration":"Main bas se kaam par jaata hoon.","english":"I go to work by bus."},{"hindi":"लाल बत्ती पर गाड़ी रोकें।","transliteration":"Laal batti par gaadi roken.","english":"Stop the vehicle at the red light."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name vehicles and describe how I travel in Hindi."}}',
'{"items":[{"word":"बस","translation":"bus","transliteration":"bas","pronunciation":"bas","example":"बस से जाना।"},{"word":"गाड़ी","translation":"car/vehicle","transliteration":"gaadi","pronunciation":"GAA-dee","example":"गाड़ी चलाना।"},{"word":"ट्रेन","translation":"train","transliteration":"tren","pronunciation":"tren","example":"ट्रेन से सफ़र।"},{"word":"सिग्नल","translation":"traffic signal","transliteration":"signal","pronunciation":"SIG-nal","example":"सिग्नल पर रुकना।"},{"word":"रोकना","translation":"to stop","transliteration":"rokna","pronunciation":"ROK-na","example":"गाड़ी रोकना।"},{"word":"चलाना","translation":"to drive/operate","transliteration":"chalaana","pronunciation":"cha-LAA-na","example":"गाड़ी चलाना।"}]}',
'{"title":"Polite imperative with -एँ/-ें — please do (verb stem + en)","pattern":"Verb stem + एँ/ें = polite imperative (please do X). रोकना → रोकें (please stop). चलना → चलें (please go/walk). आना → आएँ (please come). बैठना → बैठें (please sit). Same as the polite subjunctive — used for instructions, notices, signs.","explanation":"Polite imperative: verb stem + -ें/-एँ. Functional for public notices, instructions, and requests. लाल बत्ती पर रोकें = Stop at the red light. सीट बेल्ट लगाएँ = Put on seat belt. बाईं ओर चलें = Walk/drive on the left. Compare: informal imperative = verb stem alone (रुक, चल); very formal/literary = verb stem + इए (रुकिए, चलिए). The -ें form is standard for public notices and instructions.","examples":[{"sentence":"कृपया शांत रहें।","transliteration":"Kripaya shaant rahein.","translation":"Please remain quiet."},{"sentence":"बाईं ओर चलें।","transliteration":"Baayen or chalein.","translation":"Walk on the left side."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"गाड़ी means?","options":["car/vehicle","bus","train","bicycle"],"correctAnswer":"car/vehicle"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I go to work by bus.","options":["मैं बस से काम पर जाता हूँ।","मैं ट्रेन से काम पर जाता हूँ।","मैं गाड़ी से काम पर जाता हूँ।","मैं बस से घर जाता हूँ।"],"correctAnswer":"मैं बस से काम पर जाता हूँ।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"लाल बत्ती पर गाड़ी ___ ।","options":["रोकें","चलाएँ","जाएँ","आएँ"],"correctAnswer":"रोकें"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Please remain quiet.","wordBankItems":["कृपया","शांत","रहें","।"],"correctAnswer":"कृपया शांत रहें ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"रोकना means?","options":["to stop","to drive","to go","to park"],"correctAnswer":"to stop"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000035',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about fairs and markets in Hindi","Use X मिलता/मिलती है for availability","Describe shopping at a market"],"explanation":{"intro":"Fairs and markets are central to Indian social and commercial life — vocabulary here covers what you find and how to interact at these spaces.","culturalNote":"India''s markets are legendary. Key types: haat (हाट = weekly rural market), mela (मेला = fair/festival market), bazaar (बाज़ार = general market), sabzi mandi (vegetable market), kapda bazaar (cloth market), phool mandi (flower market). Famous fairs: Pushkar Mela (Rajasthan — one of world''s largest camel fairs), Kumbh Mela (world''s largest religious gathering — every 12 years), Surajkund Mela (Haryana — crafts). Bargaining (mol-bhav = मोल-भाव) is expected at most markets — fixed-price shops are marked ''fixed price'' (fixed price/pakka daam). Key phrases: kitne ka? (how much?), thoda kam karo (reduce a little), pakka daam hai kya? (is this the fixed price?). Street food at melas: chaat, golgappa, jalebi, kulfi."},"examples":[{"hindi":"मेले में बहुत सारी दुकानें होती हैं।","transliteration":"Mele mein bahut saari dukanen hoti hain.","english":"There are many shops at the fair."},{"hindi":"यहाँ ताज़े फल और सब्ज़ियाँ मिलती हैं।","transliteration":"Yahaan taaze phal aur sabziyaan milti hain.","english":"Fresh fruits and vegetables are available here."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about fairs and markets and describe what is available there."}}',
'{"items":[{"word":"मेला","translation":"fair/festival market","transliteration":"mela","pronunciation":"ME-la","example":"मेले में जाना।"},{"word":"दुकान","translation":"shop","transliteration":"dukaan","pronunciation":"du-KAAN","example":"दुकान खोलना।"},{"word":"ताज़ा","translation":"fresh","transliteration":"taaza","pronunciation":"TAA-za","example":"ताज़ा फल।"},{"word":"मिलना","translation":"to be available/to meet","transliteration":"milna","pronunciation":"MIL-na","example":"यहाँ मिलता है।"},{"word":"मोल-भाव","translation":"bargaining","transliteration":"mol-bhaav","pronunciation":"mol-BHAAV","example":"मोल-भाव करना।"},{"word":"सस्ता","translation":"cheap/inexpensive","transliteration":"sasta","pronunciation":"SAS-ta","example":"सस्ता सामान।"}]}',
'{"title":"X मिलता/मिलती है — X is available (milna for availability)","pattern":"X मिलता है (masculine X) / X मिलती है (feminine X) = X is available. मिलना (milna) = to meet / to be available / to be obtained. यहाँ X मिलता है = X is available here. यहाँ फल मिलते हैं = Fruits are available here (plural → मिलते हैं). Useful for shops, markets, pharmacies.","explanation":"मिलना has two key uses: (1) to meet someone (X से मिलना = to meet X) and (2) to be available/obtainable (X मिलता है = X is available). Availability use: subject is the thing available, verb agrees with it. फल (masculine plural) → मिलते हैं. सब्ज़ी (feminine) → मिलती है. दवाई (feminine) → मिलती है. यहाँ दवाई मिलती है = Medicine is available here. Compare German: es gibt (impersonal — does not agree), Hindi: मिलना (agrees with the item available).","examples":[{"sentence":"उस दुकान में अच्छे कपड़े मिलते हैं।","transliteration":"Us dukaan mein acche kapde milte hain.","translation":"Good clothes are available in that shop."},{"sentence":"यहाँ ठंडा पानी नहीं मिलता।","transliteration":"Yahaan thanda paani nahi milta.","translation":"Cold water is not available here."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"मेला means?","options":["fair/festival market","shop","street","bazaar"],"correctAnswer":"fair/festival market"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Fresh fruits and vegetables are available here.","options":["यहाँ ताज़े फल और सब्ज़ियाँ मिलती हैं।","यहाँ सस्ते फल और सब्ज़ियाँ मिलती हैं।","वहाँ ताज़े फल और सब्ज़ियाँ मिलती हैं।","यहाँ ताज़े फल और सब्ज़ियाँ होती हैं।"],"correctAnswer":"यहाँ ताज़े फल और सब्ज़ियाँ मिलती हैं।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"उस दुकान में अच्छे कपड़े ___ हैं।","options":["मिलते","मिलता","मिलती","होते"],"correctAnswer":"मिलते"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: There are many shops at the fair.","wordBankItems":["मेले","में","बहुत","सारी","दुकानें","होती","हैं","।"],"correctAnswer":"मेले में बहुत सारी दुकानें होती हैं ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"सस्ता means?","options":["cheap/inexpensive","expensive","fresh","good"],"correctAnswer":"cheap/inexpensive"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000036',1,'APPROVED','PUBLISHED',
'{"objectives":["Name household chores in Hindi","Use X साफ़ करना for cleaning","Describe a daily household routine"],"explanation":{"intro":"Household chores vocabulary covers cleaning, washing, cooking, and organising the home in Hindi.","culturalNote":"Household management in India: jhadu lagaana (झाड़ू लगाना = sweeping — with a short-handled broom, done daily), pocha lagaana (पोंछा लगाना = mopping — wet mopping), kapde dhona (कपड़े धोना = washing clothes — traditionally by hand on a washing stone, now washing machines common in cities), bartan maanjhna (बर्तन माँजना = scrubbing dishes — sand or ash historically used, now soap), kapde sukhaana (कपड़े सुखाना = drying clothes on a clothesline on roof or balcony). Domestic workers (kaamwali bai = कामवाली बाई / kaamwala = कामवाला) are very common in Indian middle-class and upper-class households — often come daily for specific tasks. Washing machine ownership is increasing rapidly. Key: गृहस्थी (grihasthi) = household/home management — a significant cultural concept, especially for married women."},"examples":[{"hindi":"रोज़ सुबह झाड़ू लगाना ज़रूरी है।","transliteration":"Roz subah jhaadu lagaana zaroori hai.","english":"It is necessary to sweep every morning."},{"hindi":"मैंने कपड़े धोए और सुखाए।","transliteration":"Maine kapde dhoe aur sukhaae.","english":"I washed and dried the clothes."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name household chores and describe a household routine in Hindi."}}',
'{"items":[{"word":"झाड़ू लगाना","translation":"to sweep","transliteration":"jhaadu lagaana","pronunciation":"JHAA-du la-GAA-na","example":"झाड़ू लगाना।"},{"word":"पोंछा लगाना","translation":"to mop","transliteration":"poncha lagaana","pronunciation":"PON-chaa la-GAA-na","example":"पोंछा लगाना।"},{"word":"कपड़े धोना","translation":"to wash clothes","transliteration":"kapde dhona","pronunciation":"KAP-de DHO-na","example":"कपड़े धोना।"},{"word":"बर्तन माँजना","translation":"to scrub dishes","transliteration":"bartan maanjhna","pronunciation":"BAR-tan MAANJ-na","example":"बर्तन माँजना।"},{"word":"सुखाना","translation":"to dry","transliteration":"sukhaana","pronunciation":"su-KHAA-na","example":"कपड़े सुखाना।"},{"word":"ज़रूरी","translation":"necessary/essential","transliteration":"zaroori","pronunciation":"za-ROO-ree","example":"ज़रूरी काम।"}]}',
'{"title":"Past tense with ने — verb agreement with object (perfective past transitive)","pattern":"Subject + ने + Object + Verb (agrees with object gender/number). मैंने कपड़े धोए = I washed clothes (धोए — masculine plural, agreeing with कपड़े). मैंने बर्तन माँजे = I scrubbed dishes (masculine plural). मैंने सब्ज़ी काटी = I cut vegetables (काटी — feminine singular, agreeing with सब्ज़ी). When no clear object: verb defaults to masculine singular.","explanation":"Perfective past transitive — ergative construction: subject takes ने. Verb agrees with OBJECT (not subject). कपड़े (masculine plural) → धोए (plural masculine past). सब्ज़ी (feminine singular) → काटी (feminine past). Compound objects: मैंने कपड़े धोए और सुखाए = I washed and dried clothes — both verbs agree with कपड़े. Key verb forms: धोना → धोया (ms), धोई (fs), धोए (mp), धोईं (fp). If no direct object or intransitive verb: ने is NOT used. मैं गया (I went — intransitive, no ने).","examples":[{"sentence":"उसने खाना बनाया और परोसा।","transliteration":"Usne khaana banaaya aur parosa.","translation":"She/he made food and served it."},{"sentence":"माँ ने घर साफ़ किया।","transliteration":"Maan ne ghar saaf kiya.","translation":"Mum cleaned the house."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"झाड़ू लगाना means?","options":["to sweep","to mop","to wash","to clean"],"correctAnswer":"to sweep"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I washed and dried the clothes.","options":["मैंने कपड़े धोए और सुखाए।","मैंने कपड़े धोए और पहने।","मैं कपड़े धोता हूँ।","मैंने बर्तन धोए।"],"correctAnswer":"मैंने कपड़े धोए और सुखाए।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"माँ ने घर साफ़ ___ ।","options":["किया","किए","की","करती"],"correctAnswer":"किया"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Mum cleaned the house.","wordBankItems":["माँ","ने","घर","साफ़","किया","।"],"correctAnswer":"माँ ने घर साफ़ किया ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"ज़रूरी means?","options":["necessary/essential","important","difficult","daily"],"correctAnswer":"necessary/essential"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000037',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about children and play in Hindi","Use X खेलना for playing","Describe playground and games vocabulary"],"explanation":{"intro":"Children and play vocabulary covers games, toys, outdoor activities, and how to describe what children do in Hindi.","culturalNote":"Children''s games in India: gilli-danda (गिल्ली-डंडा = a traditional bat-and-stick game), kho-kho (खो-खो = traditional tag game), kabaddi (कबड्डी = contact sport — now a professional league), marbles (kancha = कंचा), seven stones (pittu = पिट्टू), hide and seek (chhupa-chhupai = छुपा-छुपाई). Key: cricket (cricket) is by far the dominant children''s game in India — every street, gully (lane), field is a potential cricket ground. Gully cricket (गली क्रिकेट). IPL (Indian Premier League) — T20 franchise cricket. Ludo and carrom board (carom = कैरम) are popular indoor games. School games: badminton, kabaddi, kho-kho in physical education. Toy stores (khilone ki dukan = खिलौने की दुकान). Key verb: खेलना (khelna = to play)."},"examples":[{"hindi":"बच्चे मैदान में क्रिकेट खेल रहे हैं।","transliteration":"Bachche maidaan mein cricket khel rahe hain.","english":"Children are playing cricket in the field."},{"hindi":"मुझे बचपन में कंचे खेलना पसंद था।","transliteration":"Mujhe bachpan mein kanche khelna pasand tha.","english":"As a child I liked playing marbles."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about children''s games and play in Hindi."}}',
'{"items":[{"word":"खेलना","translation":"to play","transliteration":"khelna","pronunciation":"KHEL-na","example":"क्रिकेट खेलना।"},{"word":"मैदान","translation":"field/ground","transliteration":"maidaan","pronunciation":"mai-DAAN","example":"मैदान में खेलना।"},{"word":"खिलौना","translation":"toy","transliteration":"khilouna","pronunciation":"khi-LON-a","example":"खिलौने से खेलना।"},{"word":"बचपन","translation":"childhood","transliteration":"bachpan","pronunciation":"BACH-pan","example":"बचपन की यादें।"},{"word":"दौड़ना","translation":"to run","transliteration":"daudna","pronunciation":"DAUD-na","example":"तेज़ दौड़ना।"},{"word":"मज़ा","translation":"fun/enjoyment","transliteration":"maza","pronunciation":"ma-ZA","example":"बहुत मज़ा आया।"}]}',
'{"title":"Past continuous — X रहा/रही/रहे था/थी/थे (was/were doing)","pattern":"Verb stem + रहा/रही/रहे + था/थी/थे = was/were doing. रहा था (masculine singular past continuous), रही थी (feminine singular), रहे थे (masculine plural or respectful). बच्चे खेल रहे थे = Children were playing. वह पढ़ रही थी = She was reading.","explanation":"Past continuous: verb stem + raha/rahi/rahe (present participle, agrees with subject) + tha/thi/the (past of hona, agrees with subject). Agreement: subject gender and number. बच्चे (masculine plural) → खेल रहे थे. वह (feminine) → पढ़ रही थी. मैं (masculine) → खेल रहा था. Two-part agreement: both raha and tha agree with subject. Common in narratives and past descriptions.","examples":[{"sentence":"वह सो रही थी जब मैं आया।","transliteration":"Vah so rahi thi jab main aaya.","translation":"She was sleeping when I came."},{"sentence":"हम खाना खा रहे थे।","transliteration":"Hum khaana kha rahe the.","translation":"We were eating food."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"मैदान means?","options":["field/ground","park","playground","road"],"correctAnswer":"field/ground"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Children are playing cricket in the field.","options":["बच्चे मैदान में क्रिकेट खेल रहे हैं।","बच्चे मैदान में फ़ुटबॉल खेल रहे हैं।","बच्चा मैदान में क्रिकेट खेल रहा है।","बच्चे पार्क में क्रिकेट खेल रहे हैं।"],"correctAnswer":"बच्चे मैदान में क्रिकेट खेल रहे हैं।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"हम खाना खा रहे ___ ।","options":["थे","था","थी","हैं"],"correctAnswer":"थे"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She was sleeping when I came.","wordBankItems":["वह","सो","रही","थी","जब","मैं","आया","।"],"correctAnswer":"वह सो रही थी जब मैं आया ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"बचपन means?","options":["childhood","youth","old age","adulthood"],"correctAnswer":"childhood"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000038',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about neighbourhood and community in Hindi","Use X के पास for nearness","Describe community facilities"],"explanation":{"intro":"Neighbourhood vocabulary covers local amenities, neighbours, and how to describe your community in Hindi.","culturalNote":"Neighbourhood in India: mohalla (मोहल्ला = neighbourhood/locality — from Arabic — the basic unit of urban community in North India), colony (colony = residential area), society (housing society = apartment complex), RWA (Resident Welfare Association = residents'' association that manages a colony or apartment complex). Community spaces: chaupal (चौपाल = village gathering place, traditionally under a peepal tree), park (paark), mandir (temple), masjid (mosque). Key neighbourhood services: kiryana dukaan (किराना दुकान = grocery shop), dairy (dairy = milk shop), cable-wala (local cable TV operator), bai (domestic worker). Neighbours (padosi = पड़ोसी): Indian culture places high value on good neighbourly relations — helping with food, festivals, emergencies. Eid, Diwali, Holi: neighbours share sweets and celebrate together. Bhaichara (भाईचारा = brotherhood/community solidarity) — key social value."},"examples":[{"hindi":"मेरे घर के पास एक पार्क है।","transliteration":"Mere ghar ke paas ek paark hai.","english":"Near my house there is a park."},{"hindi":"हमारे मोहल्ले में सभी एक-दूसरे को जानते हैं।","transliteration":"Hamaare mohalle mein sabhi ek-doosre ko jaante hain.","english":"In our neighbourhood everyone knows each other."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my neighbourhood and community in Hindi."}}',
'{"items":[{"word":"मोहल्ला","translation":"neighbourhood/locality","transliteration":"mohalla","pronunciation":"mo-HAL-la","example":"हमारा मोहल्ला।"},{"word":"पड़ोसी","translation":"neighbour","transliteration":"padosi","pronunciation":"pa-DO-see","example":"अच्छा पड़ोसी।"},{"word":"के पास","translation":"near/close to","transliteration":"ke paas","pronunciation":"ke PAAS","example":"घर के पास।"},{"word":"एक-दूसरे","translation":"each other","transliteration":"ek-doosre","pronunciation":"ek-DOO-sre","example":"एक-दूसरे की मदद।"},{"word":"सुविधा","translation":"facility/convenience","transliteration":"suvidha","pronunciation":"su-VI-dha","example":"सुविधाएँ होना।"},{"word":"भाईचारा","translation":"brotherhood/community solidarity","transliteration":"bhaichara","pronunciation":"bhaa-ee-CHAA-ra","example":"भाईचारे की भावना।"}]}',
'{"title":"X के पास Y है — Near X there is Y (ke paas = near/close to)","pattern":"X के पास Y है = Near X there is Y / X has Y nearby. के पास (ke paas) = near (postposition requiring oblique). मेरे घर के पास पार्क है = Near my house there is a park. Also used for possession: मेरे पास X है = I have X (literally: near/with me there is X).","explanation":"के पास (ke paas) = near, close to, at (possession implied). Location: X के पास Y है = near X, Y exists. Possession: मेरे पास पैसे हैं = I have money (near me there is money). Note: Hindi possession is expressed with पास, not with ''have'' verb. मेरे पास = near me/I have. तुम्हारे पास = near you/you have. उसके पास = near him/her/they have. Key: X के पास requires oblique of X (मेरे = oblique of मेरा).","examples":[{"sentence":"उसके पास एक अच्छी नौकरी है।","transliteration":"Uske paas ek acchi naukri hai.","translation":"She/he has a good job."},{"sentence":"हमारे घर के पास बाज़ार है।","transliteration":"Hamaare ghar ke paas baazaar hai.","translation":"There is a market near our house."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"पड़ोसी means?","options":["neighbour","friend","community","locality"],"correctAnswer":"neighbour"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Near my house there is a park.","options":["मेरे घर के पास एक पार्क है।","मेरे घर में एक पार्क है।","हमारे घर के पास एक पार्क है।","मेरे घर के पास एक बाज़ार है।"],"correctAnswer":"मेरे घर के पास एक पार्क है।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"उसके ___ एक अच्छी नौकरी है।","options":["पास","में","पर","से"],"correctAnswer":"पास"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: In our neighbourhood everyone knows each other.","wordBankItems":["हमारे","मोहल्ले","में","सभी","एक-दूसरे","को","जानते","हैं","।"],"correctAnswer":"हमारे मोहल्ले में सभी एक-दूसरे को जानते हैं ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"के पास means?","options":["near/close to","inside","on top of","far from"],"correctAnswer":"near/close to"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000039',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about safety and emergencies in Hindi","Use X को फ़ोन करना for calling emergency services","Know key emergency phrases"],"explanation":{"intro":"Safety and emergency vocabulary covers first aid, emergency services, and what to say in urgent situations in Hindi.","culturalNote":"Emergency services in India: Police = 100, Fire brigade = 101, Ambulance = 102, Disaster management = 108, Women''s helpline = 1091, Child helpline = 1098. Unified emergency number: 112 (pan-India). NDRF (National Disaster Response Force). Key: बचाओ! (bachaao! = help!/save!) — the classic distress call. आग! (aag! = fire!). Police station (thana = थाना). Fire station (agni shaman kendra = अग्निशमन केंद्र). First aid (prathmik chikitsa = प्राथमिक चिकित्सा). Ambulance (ambulance/aambulaens). Common risks: floods (India has heavy monsoons), earthquakes (seismically active zones), fire (LPG cylinder accidents). Road accidents: India has one of the highest road fatality rates globally — helmet (helmet), seatbelt (seatbelt) campaigns. NDMA (National Disaster Management Authority)."},"examples":[{"hindi":"आग लगने पर तुरंत 101 पर फ़ोन करें।","transliteration":"Aag lagne par turant 101 par phone karen.","english":"Call 101 immediately if there is a fire."},{"hindi":"ज़रूरत पड़ने पर पुलिस को बुलाएँ।","transliteration":"Zaroorat padne par police ko bulaen.","english":"Call the police if needed."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about safety and emergency situations and know key emergency phrases in Hindi."}}',
'{"items":[{"word":"आग","translation":"fire","transliteration":"aag","pronunciation":"aag","example":"आग लगना।"},{"word":"पुलिस","translation":"police","transliteration":"police","pronunciation":"pu-LEES","example":"पुलिस बुलाना।"},{"word":"अस्पताल","translation":"hospital","transliteration":"aspatal","pronunciation":"as-pa-TAL","example":"अस्पताल जाना।"},{"word":"तुरंत","translation":"immediately/at once","transliteration":"turant","pronunciation":"tu-RANT","example":"तुरंत मदद।"},{"word":"बचाओ","translation":"help!/save!","transliteration":"bachaao","pronunciation":"ba-CHAAO","example":"बचाओ! बचाओ!"},{"word":"सुरक्षित","translation":"safe/secure","transliteration":"surakshit","pronunciation":"su-RAK-shit","example":"सुरक्षित रहना।"}]}',
'{"title":"X लगने पर Y करें — When/if X happens, do Y (conditional with par)","pattern":"X लगने पर Y करें = When X occurs, do Y. लगना (lagna) = to happen/occur/catch (for fire: आग लगना = fire breaks out). लगने पर = upon/when it occurs (oblique infinitive + पर). पर here = upon (time/condition). Pattern for conditional instructions: event + ने पर → action. आग लगने पर = when fire breaks out.","explanation":"Conditional instructions with पर: oblique infinitive + पर = upon/when (event). आग लगना → आग लगने पर = when/if fire breaks out. ज़रूरत पड़ना → ज़रूरत पड़ने पर = when need arises. बारिश होना → बारिश होने पर = when it rains. Pattern: infinitive → oblique (stem + ने) + पर. Used for: safety instructions, conditional recipes, general when-then statements. Distinct from अगर...तो (if...then — explicit conditional): अगर आग लगे तो फ़ोन करें.","examples":[{"sentence":"दुर्घटना होने पर 112 पर फ़ोन करें।","transliteration":"Durghatna hone par 112 par phone karen.","translation":"Call 112 if an accident happens."},{"sentence":"बुखार होने पर डॉक्टर के पास जाएँ।","transliteration":"Bukhar hone par doctor ke paas jaen.","translation":"Go to the doctor if you have a fever."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"तुरंत means?","options":["immediately","carefully","slowly","safely"],"correctAnswer":"immediately"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Call 101 immediately if there is a fire.","options":["आग लगने पर तुरंत 101 पर फ़ोन करें।","आग लगने पर 102 पर फ़ोन करें।","दुर्घटना होने पर 101 पर फ़ोन करें।","आग लगने पर पुलिस को बुलाएँ।"],"correctAnswer":"आग लगने पर तुरंत 101 पर फ़ोन करें।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"बुखार होने पर डॉक्टर के ___ जाएँ।","options":["पास","में","पर","से"],"correctAnswer":"पास"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Call 112 if an accident happens.","wordBankItems":["दुर्घटना","होने","पर","112","पर","फ़ोन","करें","।"],"correctAnswer":"दुर्घटना होने पर 112 पर फ़ोन करें ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"बचाओ means?","options":["help!/save!","run!","stop!","wait!"],"correctAnswer":"help!/save!"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-00000000003a',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about news and current events in Hindi","Use X हुआ/हुई for something that happened","Understand basic news vocabulary"],"explanation":{"intro":"News and current events vocabulary covers media, journalism, and how to discuss what is happening in the world in Hindi.","culturalNote":"News media in India: समाचार (samaachaar) = news. अख़बार (akhbaar) = newspaper (from Persian). टेलीविज़न (television) / TV. Hindi news channels: Aaj Tak (''Until Today'' — India''s most watched Hindi news channel), NDTV India, ABP News, Zee News. Newspapers: Dainik Jagran (दैनिक जागरण = Daily Awakening — largest circulating Hindi newspaper in the world), Dainik Bhaskar, Hindustan. Online: The Print, The Wire, Scroll.in. Press freedom: India ranks around 159/180 in the Press Freedom Index (RSF 2023). Social media has transformed news consumption — WhatsApp forwards are major news vectors (and misinformation vectors). Fact-checking organizations: AltNews, Boom Live. Key: India has the world''s largest newspaper industry by circulation. Regional language newspapers have huge readership. ''Breaking news'' (breaking news) culture is intense on Indian TV news channels."},"examples":[{"hindi":"आज अख़बार में क्या ख़बर है?","transliteration":"Aaj akhbaar mein kya khabar hai?","english":"What news is in the newspaper today?"},{"hindi":"कल एक बड़ी दुर्घटना हुई।","transliteration":"Kal ek badi durghatna hui.","english":"Yesterday a big accident happened."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about news and current events in Hindi."}}',
'{"items":[{"word":"समाचार","translation":"news","transliteration":"samaachaar","pronunciation":"sa-maa-CHAAR","example":"समाचार सुनना।"},{"word":"अख़बार","translation":"newspaper","transliteration":"akhbaar","pronunciation":"akh-BAAR","example":"अख़बार पढ़ना।"},{"word":"ख़बर","translation":"news item/piece of news","transliteration":"khabar","pronunciation":"KHA-bar","example":"अच्छी ख़बर।"},{"word":"दुर्घटना","translation":"accident/mishap","transliteration":"durghatna","pronunciation":"dur-GHAT-na","example":"बड़ी दुर्घटना।"},{"word":"हुआ/हुई","translation":"happened (m/f)","transliteration":"hua/hui","pronunciation":"hua/hui","example":"क्या हुआ?"},{"word":"रिपोर्ट","translation":"report","transliteration":"report","pronunciation":"ri-PORT","example":"रिपोर्ट आई।"}]}',
'{"title":"X हुआ/हुई — X happened (intransitive past of होना)","pattern":"X हुआ (masculine X) / X हुई (feminine X) = X happened. होना in perfective past: हुआ (ms), हुई (fs), हुए (mp), हुईं (fp). दुर्घटना हुई = an accident happened (feminine). भूकंप हुआ = an earthquake happened (masculine). क्या हुआ? = What happened? No ने — intransitive होना never takes ने.","explanation":"Intransitive past of होना: हुआ/हुई/हुए. Used for events that ''happened'': X हुआ = X occurred/took place. Agreement with the subject (the event): दुर्घटना (feminine) → हुई. भूकंप (earthquake — masculine) → हुआ. शादी (wedding — feminine) → हुई. Contrast with transitive past (ने): मैंने काम किया (I did work — transitive, ने required). Key question: क्या हुआ? = What happened? Universal question in news, stories, and everyday conversation.","examples":[{"sentence":"कल रात बहुत बारिश हुई।","transliteration":"Kal raat bahut baarish hui.","translation":"It rained heavily last night."},{"sentence":"आज सुबह भूकंप हुआ।","transliteration":"Aaj subah bhookamp hua.","translation":"An earthquake happened this morning."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"अख़बार means?","options":["newspaper","news","magazine","television"],"correctAnswer":"newspaper"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Yesterday a big accident happened.","options":["कल एक बड़ी दुर्घटना हुई।","आज एक बड़ी दुर्घटना हुई।","कल एक छोटी दुर्घटना हुई।","कल एक बड़ा भूकंप हुआ।"],"correctAnswer":"कल एक बड़ी दुर्घटना हुई।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"कल रात बहुत बारिश ___ ।","options":["हुई","हुआ","हुए","होती"],"correctAnswer":"हुई"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: What news is in the newspaper today?","wordBankItems":["आज","अख़बार","में","क्या","ख़बर","है","?"],"correctAnswer":"आज अख़बार में क्या ख़बर है ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"दुर्घटना means?","options":["accident/mishap","earthquake","flood","fire"],"correctAnswer":"accident/mishap"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-00000000003b',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about hobbies and free time in Hindi","Use X करना पसंद है for liking an activity","Describe leisure activities"],"explanation":{"intro":"Hobbies and free time vocabulary covers leisure activities, sports, arts, and how to express what you enjoy doing in Hindi.","culturalNote":"Leisure in India: cricket (cricket — national obsession), Bollywood films (Bollywood — Mumbai film industry — world''s largest by number of films), music (sangeet = संगीत), dance (naach/nritya = नाच/नृत्य — classical forms: Bharatanatyam, Kathak, Odissi, Kuchipudi; folk: Bhangra, Garba), reading (padhna), cooking (khaana banana), yoga (yog = योग — originated in India). Gaming (gaming) increasingly popular among youth. OTT platforms: Netflix, Amazon Prime, Hotstar — huge in India. Social media: Instagram, YouTube, WhatsApp dominate. Handicrafts (hastakala = हस्तकला) — pottery, weaving, embroidery. Music: Carnatic (South India), Hindustani (North India). Raga (raag = राग) — melodic framework. Key: Indians spend more time watching YouTube than any other country per capita."},"examples":[{"hindi":"मुझे संगीत सुनना बहुत पसंद है।","transliteration":"Mujhe sangeet sunna bahut pasand hai.","english":"I really like listening to music."},{"hindi":"मेरी बहन को नृत्य करना पसंद है।","transliteration":"Meri bahan ko nritya karna pasand hai.","english":"My sister likes dancing."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about hobbies and free time activities in Hindi."}}',
'{"items":[{"word":"शौक","translation":"hobby/interest","transliteration":"shauq","pronunciation":"shauq","example":"मेरा शौक।"},{"word":"फ़ुर्सत","translation":"free time/leisure","transliteration":"fursat","pronunciation":"FUR-sat","example":"फ़ुर्सत में।"},{"word":"संगीत","translation":"music","transliteration":"sangeet","pronunciation":"san-GEET","example":"संगीत सुनना।"},{"word":"नृत्य","translation":"dance","transliteration":"nritya","pronunciation":"NRIT-ya","example":"नृत्य करना।"},{"word":"पढ़ना","translation":"to read","transliteration":"padhna","pronunciation":"PADH-na","example":"किताब पढ़ना।"},{"word":"योग","translation":"yoga","transliteration":"yog","pronunciation":"yog","example":"योग करना।"}]}',
'{"title":"Mujhe/Use X karna pasand hai — I/She likes doing X (dative subject for preference)","pattern":"मुझे X करना पसंद है = I like doing X. Dative subject: मुझे (to me — dative of मैं). X करना = the infinitive (the activity liked). पसंद है = is liked. Agreement: पसंद stays invariant; है agrees with... the whole clause (singular). मेरी बहन को नृत्य करना पसंद है = My sister likes dancing. को marks dative subject for liking.","explanation":"Dative subject construction for liking/disliking: X को Y करना पसंद है = X likes doing Y. X takes को (dative). Y करना = infinitive (activity). पसंद है = lit. ''is pleasing.'' Compare: X को Y पसंद है = X likes Y (noun, not activity). Negation: X को Y करना पसंद नहीं है = X does not like doing Y. Intensify: X को Y करना बहुत पसंद है = X really likes doing Y. The construction ''dative subject + activity infinitive + pasand hai'' is a fundamental Hindi preference pattern.","examples":[{"sentence":"उसे पढ़ना पसंद नहीं है।","transliteration":"Use padhna pasand nahi hai.","translation":"He/she does not like reading."},{"sentence":"क्या तुम्हें क्रिकेट खेलना पसंद है?","transliteration":"Kya tumhein cricket khelna pasand hai?","translation":"Do you like playing cricket?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"शौक means?","options":["hobby/interest","free time","music","sport"],"correctAnswer":"hobby/interest"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I really like listening to music.","options":["मुझे संगीत सुनना बहुत पसंद है।","मुझे संगीत बजाना बहुत पसंद है।","मुझे संगीत सुनना पसंद नहीं है।","मुझे नृत्य करना बहुत पसंद है।"],"correctAnswer":"मुझे संगीत सुनना बहुत पसंद है।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"उसे पढ़ना पसंद ___ है।","options":["नहीं","बहुत","कम","ज़्यादा"],"correctAnswer":"नहीं"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Do you like playing cricket?","wordBankItems":["क्या","तुम्हें","क्रिकेट","खेलना","पसंद","है","?"],"correctAnswer":"क्या तुम्हें क्रिकेट खेलना पसंद है ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"फ़ुर्सत means?","options":["free time/leisure","hobby","rest","vacation"],"correctAnswer":"free time/leisure"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-00000000003c',1,'APPROVED','PUBLISHED',
'{"objectives":["Express opinions and preferences in Hindi","Use मेरे ख़याल से for giving opinions","Agree and disagree politely"],"explanation":{"intro":"Opinions and preferences vocabulary covers how to express your views, agree and disagree, and give reasons in Hindi.","culturalNote":"Expressing opinions in Hindi: मेरे ख़याल से (mere khyaal se = in my opinion — from Persian khyaal = thought/idea). मेरी राय में (meri raay mein = in my view — raay from Arabic). मुझे लगता है (mujhe lagta hai = I think/it seems to me). सहमत होना (sahmat hona = to agree — from Arabic). असहमत होना (asahmat = to disagree). हाँ, बिल्कुल (haan, bilkul = yes, absolutely). नहीं, मुझे नहीं लगता (nahi, mujhe nahi lagta = no, I don''t think so). Indian discourse style: direct disagreement can seem rude — softening with ''शायद'' (maybe), ''थोड़ा'' (a little), ''लेकिन'' (but) is common. Debating culture: Indian Parliament, Lok Sabha — famous for spirited debate. IIT/IIM debate clubs. MUN (Model United Nations) very popular in Indian schools. Opinionated TV debates (news anchors in India are famously combative)."},"examples":[{"hindi":"मेरे ख़याल से यह फ़िल्म बहुत अच्छी है।","transliteration":"Mere khyaal se yah film bahut acchi hai.","english":"In my opinion this film is very good."},{"hindi":"मुझे लगता है कि हमें पढ़ना चाहिए।","transliteration":"Mujhe lagta hai ki hamein padhna chahiye.","english":"I think we should study."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can express opinions and preferences in Hindi and agree or disagree politely."}}',
'{"items":[{"word":"ख़याल","translation":"opinion/thought/idea","transliteration":"khyaal","pronunciation":"khyaal","example":"मेरा ख़याल।"},{"word":"राय","translation":"view/opinion","transliteration":"raay","pronunciation":"raay","example":"मेरी राय।"},{"word":"सहमत","translation":"in agreement","transliteration":"sahmat","pronunciation":"SAH-mat","example":"मैं सहमत हूँ।"},{"word":"लगना","translation":"to seem/to feel/to think","transliteration":"lagna","pronunciation":"LAG-na","example":"मुझे लगता है।"},{"word":"शायद","translation":"maybe/perhaps","transliteration":"shayad","pronunciation":"SHAA-yad","example":"शायद हाँ।"},{"word":"बिल्कुल","translation":"absolutely/exactly","transliteration":"bilkul","pronunciation":"BIL-kul","example":"बिल्कुल सही।"}]}',
'{"title":"मुझे लगता है कि X — I think that X (lagna for expressing opinion)","pattern":"मुझे लगता है कि X = I think that X / It seems to me that X. लगना (lagna) = to seem, feel, appear. Dative subject: मुझे (to me). लगता है = seems (masculine singular — the whole clause is the implied subject). कि = that (subordinating conjunction). X = the opinion clause.","explanation":"लगना (lagna) for opinion/perception: मुझे लगता है = I think/it seems to me. Literally: ''to me it seems.'' Dative subject construction — same as पसंद है. लगना also means: to be attached (दिल लगना), to cost time (घंटा लगना), to feel (ठंड लगना = to feel cold). Opinion use: मुझे लगता है कि... = I think that... Softened opinion: मुझे लगता है शायद... = I think maybe... Agreeing: मुझे भी लगता है = I think so too (भी = also/too).","examples":[{"sentence":"मुझे लगता है यह विचार सही है।","transliteration":"Mujhe lagta hai yah vichaar sahi hai.","translation":"I think this idea is correct."},{"sentence":"क्या आपको भी लगता है कि बदलाव ज़रूरी है?","transliteration":"Kya aapko bhi lagta hai ki badlaav zaroori hai?","translation":"Do you also think that change is necessary?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"सहमत means?","options":["in agreement","in disagreement","unsure","maybe"],"correctAnswer":"in agreement"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In my opinion this film is very good.","options":["मेरे ख़याल से यह फ़िल्म बहुत अच्छी है।","मेरी राय में यह फ़िल्म बहुत अच्छी है।","मेरे ख़याल से यह फ़िल्म अच्छी नहीं है।","मुझे लगता है यह फ़िल्म बहुत अच्छी है।"],"correctAnswer":"मेरे ख़याल से यह फ़िल्म बहुत अच्छी है।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"मुझे लगता है यह विचार ___ है।","options":["सही","ग़लत","अच्छा","बुरा"],"correctAnswer":"सही"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I think we should study.","wordBankItems":["मुझे","लगता","है","कि","हमें","पढ़ना","चाहिए","।"],"correctAnswer":"मुझे लगता है कि हमें पढ़ना चाहिए ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"बिल्कुल means?","options":["absolutely/exactly","maybe","sometimes","never"],"correctAnswer":"absolutely/exactly"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('ee000000-0000-0000-0000-000000000033','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l051',51,'City and Village','City and village life','PUBLISHED'),
('ee000000-0000-0000-0000-000000000034','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l052',52,'Traffic and Transport Rules','Traffic and transport vocabulary','PUBLISHED'),
('ee000000-0000-0000-0000-000000000035','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l053',53,'Fairs and Markets','Fairs and market shopping','PUBLISHED'),
('ee000000-0000-0000-0000-000000000036','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l054',54,'Household Chores','Household chores and routine','PUBLISHED'),
('ee000000-0000-0000-0000-000000000037','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l055',55,'Children and Play','Children games and play','PUBLISHED'),
('ee000000-0000-0000-0000-000000000038','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l056',56,'Neighbourhood and Community','Neighbourhood and community life','PUBLISHED'),
('ee000000-0000-0000-0000-000000000039','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l057',57,'Safety and Emergency','Safety and emergency vocabulary','PUBLISHED'),
('ee000000-0000-0000-0000-00000000003a','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l058',58,'News and Current Events','News and media vocabulary','PUBLISHED'),
('ee000000-0000-0000-0000-00000000003b','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l059',59,'Hobbies and Free Time','Hobbies and leisure activities','PUBLISHED'),
('ee000000-0000-0000-0000-00000000003c','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l060',60,'Opinions and Preferences','Expressing opinions and preferences','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000033' WHERE stable_ref = 'hi-a1-u01-l051' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000034' WHERE stable_ref = 'hi-a1-u01-l052' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000035' WHERE stable_ref = 'hi-a1-u01-l053' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000036' WHERE stable_ref = 'hi-a1-u01-l054' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000037' WHERE stable_ref = 'hi-a1-u01-l055' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000038' WHERE stable_ref = 'hi-a1-u01-l056' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000039' WHERE stable_ref = 'hi-a1-u01-l057' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-00000000003a' WHERE stable_ref = 'hi-a1-u01-l058' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-00000000003b' WHERE stable_ref = 'hi-a1-u01-l059' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-00000000003c' WHERE stable_ref = 'hi-a1-u01-l060' AND lesson_id IS NULL;
