-- V115: Hindi A1 lessons 61-70
-- Hex: 61=0x3d, 62=0x3e, 63=0x3f, 64=0x40, 65=0x41, 66=0x42, 67=0x43, 68=0x44, 69=0x45, 70=0x46
-- A1 rewards: xp:100, coins:50

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('cc000000-0000-0000-0000-00000000003d','hi-a1-l061','Post Office and Banking','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-00000000003e','hi-a1-l062','Phone and Internet','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-00000000003f','hi-a1-l063','Restaurant and Dining Out','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000040','hi-a1-l064','Adjectives — Describing Things','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000041','hi-a1-l065','Seasons and Climate','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000042','hi-a1-l066','Asking for Help','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000043','hi-a1-l067','Greetings and Farewells Extended','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000044','hi-a1-l068','Describing People — Appearance','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000045','hi-a1-l069','Daily Routine — Morning','language','hi','A1','APPROVED','PUBLISHED',1,1),
('cc000000-0000-0000-0000-000000000046','hi-a1-l070','Daily Routine — Evening','language','hi','A1','APPROVED','PUBLISHED',1,1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-00000000003d',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about post office and banking in Hindi","Use X भेजना for sending","Describe basic banking transactions"],"explanation":{"intro":"Post office and banking vocabulary covers sending letters and parcels, banking transactions, and financial services in Hindi.","culturalNote":"Post office (daakghar = डाकघर) and banking in India: India Post (Bharat Dak = भारत डाक) — world''s largest postal network — 155,000 post offices. Speed Post (Speed Post), Registered Post (Registered Post), Money Order (Money Order = पैसे भेजना). Bank (bank = बैंक). ATM. Account (khata = खाता). Cheque (cheque). RTGS/NEFT (online transfer). UPI (Unified Payments Interface) — India''s digital payments revolution — over 10 billion transactions per month. PhonePe, Google Pay (GPay), Paytm — major UPI apps. Jan Dhan Yojana (Jan Dhan = ''people''s wealth'' — Modi 2014 — 500 million bank accounts opened for the unbanked). Post offices now offer banking (India Post Payments Bank). Key: India is rapidly going cashless — digital payments have transformed even small vendors and autorickshaw drivers."},"examples":[{"hindi":"मुझे यह पार्सल भेजना है।","transliteration":"Mujhe yah parcel bhejna hai.","english":"I need to send this parcel."},{"hindi":"बैंक में खाता खोलने के लिए क्या चाहिए?","transliteration":"Bank mein khaata kholne ke liye kya chahiye?","english":"What is needed to open an account at the bank?"}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about post office and banking services in Hindi."}}',
'{"items":[{"word":"डाकघर","translation":"post office","transliteration":"daakghar","pronunciation":"DAAK-ghar","example":"डाकघर जाना।"},{"word":"पार्सल","translation":"parcel","transliteration":"parcel","pronunciation":"PAR-sal","example":"पार्सल भेजना।"},{"word":"भेजना","translation":"to send","transliteration":"bhejna","pronunciation":"BHEJ-na","example":"पत्र भेजना।"},{"word":"खाता","translation":"account","transliteration":"khaata","pronunciation":"KHAA-ta","example":"बैंक खाता।"},{"word":"निकालना","translation":"to withdraw","transliteration":"nikaalna","pronunciation":"ni-KAAL-na","example":"पैसे निकालना।"},{"word":"जमा करना","translation":"to deposit","transliteration":"jama karna","pronunciation":"ja-MA kar-na","example":"पैसे जमा करना।"}]}',
'{"title":"X के लिए क्या चाहिए — What is needed for X (ke liye = for/in order to)","pattern":"X के लिए क्या चाहिए? = What is needed for X? के लिए = for (purpose postposition). चाहिए = is needed/required (impersonal — never inflects). X के लिए Y चाहिए = Y is needed for X. X के लिए can also express purpose: खाने के लिए = in order to eat.","explanation":"के लिए (ke liye) = for, in order to, for the purpose of. Postposition requiring oblique: X के लिए. Uses: (1) purpose: पीने के लिए पानी (water for drinking), (2) beneficiary: तुम्हारे लिए (for you), (3) goal: खाता खोलने के लिए (in order to open an account — oblique infinitive). चाहिए (chahiye) = is needed — impersonal verb, never changes form. मुझे X चाहिए = I need X. Y के लिए X चाहिए = X is needed for Y.","examples":[{"sentence":"यात्रा के लिए पासपोर्ट चाहिए।","transliteration":"Yaatra ke liye passport chahiye.","translation":"A passport is needed for travel."},{"sentence":"पढ़ाई के लिए मेहनत चाहिए।","transliteration":"Padhaai ke liye mehnat chahiye.","translation":"Hard work is needed for studies."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"डाकघर means?","options":["post office","bank","office","shop"],"correctAnswer":"post office"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I need to send this parcel.","options":["मुझे यह पार्सल भेजना है।","मुझे यह पत्र भेजना है।","मैं यह पार्सल भेजता हूँ।","मुझे यह पार्सल मिलना है।"],"correctAnswer":"मुझे यह पार्सल भेजना है।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"यात्रा ___ लिए पासपोर्ट चाहिए।","options":["के","की","को","से"],"correctAnswer":"के"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Hard work is needed for studies.","wordBankItems":["पढ़ाई","के","लिए","मेहनत","चाहिए","।"],"correctAnswer":"पढ़ाई के लिए मेहनत चाहिए ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"जमा करना means?","options":["to deposit","to withdraw","to transfer","to pay"],"correctAnswer":"to deposit"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-00000000003e',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about phone and internet in Hindi","Use X से बात करना for talking by phone","Describe digital communication"],"explanation":{"intro":"Phone and internet vocabulary covers digital communication, messaging, and how to describe using technology in Hindi.","culturalNote":"Mobile phones and internet in India: India has 1.2 billion mobile phone subscribers — second only to China. Jio (Reliance Jio — 2016 launch — free data revolution that made India the world''s largest mobile data consumer per capita). Smartphone (smartphone). Data (data/internet data). Call karna (call karna = to make a call). Message bhejna (message bhejna = to send a message). WhatsApp — India is WhatsApp''s largest market (500+ million users). Instagram Reels extremely popular. YouTube — India is YouTube''s largest market by users. Calls: missed call (missed call — a social signal in India — ''give me a missed call when you reach''), truecaller (TrueCaller — Swedish caller ID app — extremely popular in India to screen spam calls). Key: 4G/5G rollout transformed India — Jio disrupted the telecom market by offering nearly-free data, forcing incumbents to slash prices."},"examples":[{"hindi":"मैं फ़ोन से बात नहीं कर सकता, मैसेज करो।","transliteration":"Main phone se baat nahi kar sakta, message karo.","english":"I cannot talk on the phone, message me."},{"hindi":"इंटरनेट बंद है, वाई-फ़ाई काम नहीं कर रहा।","transliteration":"Internet band hai, WiFi kaam nahi kar raha.","english":"The internet is down, the WiFi is not working."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about phone and internet communication in Hindi."}}',
'{"items":[{"word":"फ़ोन करना","translation":"to call (by phone)","transliteration":"phone karna","pronunciation":"phone KAR-na","example":"फ़ोन करना।"},{"word":"मैसेज","translation":"message","transliteration":"message","pronunciation":"MES-saj","example":"मैसेज भेजना।"},{"word":"बंद","translation":"off/closed/down","transliteration":"band","pronunciation":"band","example":"इंटरनेट बंद।"},{"word":"काम करना","translation":"to work/function","transliteration":"kaam karna","pronunciation":"kaam KAR-na","example":"ठीक काम करना।"},{"word":"चार्ज करना","translation":"to charge","transliteration":"charge karna","pronunciation":"CHAARJ kar-na","example":"फ़ोन चार्ज करना।"},{"word":"नेटवर्क","translation":"network/signal","transliteration":"network","pronunciation":"NET-vark","example":"नेटवर्क नहीं है।"}]}',
'{"title":"X काम नहीं कर रहा/रही — X is not working (present continuous negative)","pattern":"X काम नहीं कर रहा (masculine X) / रही (feminine X) = X is not working. काम करना = to work/function. नहीं = not (negation before verb). Present continuous: कर रहा है / कर रही है. Negation: नहीं goes before the main verb (कर): काम नहीं कर रहा है.","explanation":"Negation in present continuous: नहीं (nahi) goes immediately before the main verb in the V+raha structure. काम कर रहा है (is working) → काम नहीं कर रहा (is not working). Note: है can be dropped in informal speech (कर रहा नहीं). Additional negation contexts: वह नहीं आ रहा (he is not coming), बारिश नहीं हो रही (it is not raining). Permanent negation (never): कभी नहीं करता (never does).","examples":[{"sentence":"लिफ़्ट काम नहीं कर रही है।","transliteration":"Lift kaam nahi kar rahi hai.","translation":"The lift is not working."},{"sentence":"मेरा फ़ोन चार्ज नहीं हो रहा।","transliteration":"Mera phone charge nahi ho raha.","translation":"My phone is not charging."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"बंद means?","options":["off/closed/down","open","broken","slow"],"correctAnswer":"off/closed/down"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The internet is down, the WiFi is not working.","options":["इंटरनेट बंद है, वाई-फ़ाई काम नहीं कर रहा।","इंटरनेट धीमा है, वाई-फ़ाई काम नहीं कर रहा।","इंटरनेट बंद है, फ़ोन काम नहीं कर रहा।","नेटवर्क बंद है, वाई-फ़ाई काम नहीं कर रहा।"],"correctAnswer":"इंटरनेट बंद है, वाई-फ़ाई काम नहीं कर रहा।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"मेरा फ़ोन चार्ज नहीं हो ___ ।","options":["रहा","रही","रहे","होता"],"correctAnswer":"रहा"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The lift is not working.","wordBankItems":["लिफ़्ट","काम","नहीं","कर","रही","है","।"],"correctAnswer":"लिफ़्ट काम नहीं कर रही है ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"फ़ोन करना means?","options":["to call (by phone)","to message","to email","to chat"],"correctAnswer":"to call (by phone)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-00000000003f',1,'APPROVED','PUBLISHED',
'{"objectives":["Order food and drinks at a restaurant in Hindi","Use X लाइए for requesting","Read a simple menu and ask the price"],"explanation":{"intro":"Restaurant vocabulary covers ordering, asking for the menu, and paying the bill in Hindi.","culturalNote":"Restaurants in India: dhaba (dhaba = roadside restaurant — often better food than fancy places), restaurant (restaurant), hotel (hotel — in much of India, ''hotel'' = restaurant, not lodging!), fast food (fast food). Key restaurant phrases: menu dikhaiye (show the menu please), kya recommendation hai? (what do you recommend?), bill laiye (bring the bill), ek aur roti (one more roti). Thali (थाली = a complete meal on a plate — often unlimited in South India — a great value). Service: tips are not compulsory but appreciated — 10% is common. Veg/Non-veg distinction is crucial — veg restaurants have a green dot, non-veg have a red dot (by law — FSSAI regulation). Jain food (no root vegetables). Hygiene certification (FSSAI). Zomato/Swiggy — India''s dominant food delivery apps. Key: Indian restaurants typically serve food quickly — the concept of a leisurely 3-hour dinner is less common than in Europe."},"examples":[{"hindi":"एक थाली और एक लस्सी लाइए।","transliteration":"Ek thaali aur ek lassi laiye.","english":"Please bring one thali and one lassi."},{"hindi":"बिल लाइए, हमें जाना है।","transliteration":"Bill laiye, hamein jaana hai.","english":"Please bring the bill, we need to go."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can order food at a restaurant and ask for the bill in Hindi."}}',
'{"items":[{"word":"थाली","translation":"platter/thali meal","transliteration":"thaali","pronunciation":"THAA-lee","example":"एक थाली।"},{"word":"मेनू","translation":"menu","transliteration":"menu","pronunciation":"ME-nu","example":"मेनू दिखाइए।"},{"word":"लाइए","translation":"please bring","transliteration":"laiye","pronunciation":"LAA-i-ye","example":"पानी लाइए।"},{"word":"लस्सी","translation":"lassi (yoghurt drink)","transliteration":"lassi","pronunciation":"LAS-see","example":"मीठी लस्सी।"},{"word":"शाकाहारी","translation":"vegetarian","transliteration":"shakaahaaree","pronunciation":"sha-kaa-HAA-ree","example":"शाकाहारी खाना।"},{"word":"माँसाहारी","translation":"non-vegetarian","transliteration":"maansaahaari","pronunciation":"maan-saa-HAA-ree","example":"माँसाहारी थाली।"}]}',
'{"title":"X लाइए / X दीजिए — Please bring X / Please give X (very formal imperative)","pattern":"Verb stem + इए = very polite imperative. लाना → लाइए (please bring). देना → दीजिए (please give). पीना → पीजिए (please drink). Used for requests to staff, elders, formal settings. More formal than करें (formal imperative) — लाइए is hotel/restaurant register.","explanation":"Imperative register in Hindi: (1) Informal: stem alone (ला, दे — very casual), (2) Semi-formal: stem + ो (लाओ, दो — to peers), (3) Formal: stem + ें (लाएँ, दें — polite plural/public), (4) Very polite: stem + इए (लाइए, दीजिए — respectful/to elders/service requests). Restaurant usage: लाइए, दीजिए, बताइए (please tell). Note: देना is irregular — दे + इए → दीजिए (not ''देइए''). Similarly: लेना → लीजिए.","examples":[{"sentence":"कृपया मेनू दिखाइए।","transliteration":"Kripaya menu dikhaiye.","translation":"Please show the menu."},{"sentence":"थोड़ा नमक लाइए।","transliteration":"Thoda namak laiye.","translation":"Please bring a little salt."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"थाली means?","options":["platter/thali meal","plate","bowl","tray"],"correctAnswer":"platter/thali meal"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Please bring one thali and one lassi.","options":["एक थाली और एक लस्सी लाइए।","एक थाली और एक लस्सी दीजिए।","दो थाली और एक लस्सी लाइए।","एक थाली और दो लस्सी लाइए।"],"correctAnswer":"एक थाली और एक लस्सी लाइए।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"कृपया मेनू ___ ।","options":["दिखाइए","लाइए","दीजिए","बताइए"],"correctAnswer":"दिखाइए"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Please bring the bill, we need to go.","wordBankItems":["बिल","लाइए",",","हमें","जाना","है","।"],"correctAnswer":"बिल लाइए , हमें जाना है ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"शाकाहारी means?","options":["vegetarian","non-vegetarian","spicy","sweet"],"correctAnswer":"vegetarian"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000040',1,'APPROVED','PUBLISHED',
'{"objectives":["Use descriptive adjectives in Hindi","Describe objects with size, shape, colour, and quality","Apply adjective agreement rules"],"explanation":{"intro":"Descriptive adjectives allow you to describe things, people, and places with precision. This lesson covers a wide range of quality and property adjectives in Hindi.","culturalNote":"Adjectives in Hindi: Hindi has rich adjectival vocabulary combining Sanskrit, Persian, and Arabic roots. Key quality adjectives: अच्छा (good), बुरा (bad), बड़ा (big), छोटा (small), लंबा (tall/long), नया (new), पुराना (old), सुंदर (beautiful), मुश्किल (difficult), आसान (easy), महँगा (expensive), सस्ता (cheap), गर्म (hot), ठंडा (cold), मीठा (sweet), तीखा (spicy). Inflecting adjectives: end in -a → change. Non-inflecting: end in consonant or -ī/ū → invariant. Poetry/literature: adjectives are crucial to Hindi shayari (poetry) — Urdu borrowings add emotion: नाज़ुक (delicate), लताफ़त (elegance). Common phrase: कुछ खास नहीं (nothing special). Complimenting: बहुत अच्छा! (very good!), वाह! (wow!), क्या बात है! (what a thing! = great!)."},"examples":[{"hindi":"यह साड़ी बहुत सुंदर और महँगी है।","transliteration":"Yah saari bahut sundar aur mahangi hai.","english":"This saree is very beautiful and expensive."},{"hindi":"वह लड़का लंबा और दुबला है।","transliteration":"Vah ladka lamba aur dubla hai.","english":"That boy is tall and thin."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe objects and people using descriptive adjectives in Hindi."}}',
'{"items":[{"word":"सुंदर","translation":"beautiful","transliteration":"sundar","pronunciation":"SUN-dar","example":"सुंदर फूल।"},{"word":"महँगा/महँगी","translation":"expensive (m/f)","transliteration":"mahanga/mahangi","pronunciation":"ma-HAN-ga","example":"महँगी घड़ी।"},{"word":"मुश्किल","translation":"difficult","transliteration":"mushkil","pronunciation":"MUSH-kil","example":"मुश्किल काम।"},{"word":"आसान","translation":"easy","transliteration":"aasaan","pronunciation":"aa-SAAN","example":"आसान सवाल।"},{"word":"दुबला/दुबली","translation":"thin/slim (m/f)","transliteration":"dubla/dubli","pronunciation":"DUB-la","example":"दुबला लड़का।"},{"word":"मीठा/मीठी","translation":"sweet (m/f)","transliteration":"meetha/meethi","pronunciation":"MEE-tha","example":"मीठा फल।"}]}',
'{"title":"Stacked adjectives — X और Y है (two adjectives with aur)","pattern":"X और Y है = is X and Y. Stacking two adjectives: both agree with the subject. सुंदर और महँगी है (beautiful and expensive — feminine subject). Both adjectives inflect independently. Invariant adjectives (सुंदर, मुश्किल) stay as-is. Inflecting adjectives (महँगा/महँगी) change with noun gender.","explanation":"Multiple adjectives in Hindi: joined with और (and). Each adjective agrees independently with the subject. Predicative: X Y है (X is Y — both adjectives follow subject). Attributive (before noun): X Y noun (both precede noun, both agree). Example: लंबी और सुंदर लड़की (tall and beautiful girl — both feminine). Key: invariant adjectives (सुंदर, मुश्किल, आसान, बेहतर) never change. Inflecting adjectives follow the -a/-i/-e pattern. In poetry/formal writing: adjectives can be stacked in threes or fours for effect.","examples":[{"sentence":"यह रास्ता लंबा और थकानेवाला है।","transliteration":"Yah raasta lamba aur thakaanevala hai.","translation":"This road is long and tiring."},{"sentence":"वह लड़की होशियार और मेहनती है।","transliteration":"Vah ladki hoshiyaar aur mehanti hai.","translation":"That girl is clever and hardworking."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"मुश्किल means?","options":["difficult","easy","possible","important"],"correctAnswer":"difficult"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"This saree is very beautiful and expensive.","options":["यह साड़ी बहुत सुंदर और महँगी है।","यह साड़ी बहुत सुंदर और सस्ती है।","वह साड़ी बहुत सुंदर और महँगी है।","यह कपड़ा बहुत सुंदर और महँगा है।"],"correctAnswer":"यह साड़ी बहुत सुंदर और महँगी है।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"वह लड़की होशियार और ___ है।","options":["मेहनती","मेहनतू","मेहनता","मेहनते"],"correctAnswer":"मेहनती"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That boy is tall and thin.","wordBankItems":["वह","लड़का","लंबा","और","दुबला","है","।"],"correctAnswer":"वह लड़का लंबा और दुबला है ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"आसान means?","options":["easy","hard","fast","slow"],"correctAnswer":"easy"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000041',1,'APPROVED','PUBLISHED',
'{"objectives":["Name seasons and describe the climate in Hindi","Use X में Y होता है for seasonal patterns","Talk about Indian weather"],"explanation":{"intro":"Seasons and climate vocabulary covers India''s distinct seasons, weather patterns, and how to describe them in Hindi.","culturalNote":"India''s seasons (ritu = ऋतु = season — Sanskrit — 6 traditional seasons): (1) Vasant (वसंत = spring — Feb-Mar), (2) Grishma (ग्रीष्म = summer — Apr-Jun), (3) Varsha (वर्षा = monsoon/rainy — Jul-Sep — the most important season for agriculture), (4) Sharad (शरद = autumn — Oct-Nov), (5) Hemant (हेमंत = pre-winter — Nov-Dec), (6) Shishir (शिशिर = winter — Dec-Jan). Modern common usage: garmiya (गर्मियाँ = summers), barsaat (बरसात = rains), sardi (सर्दी = winter). Monsoon (monsoon): India receives 80% of its rainfall in 3 months — agriculture depends on it — ''monsoon lottery'' for GDP growth. Severe heatwaves: Delhi reaches 45-48°C in May. Cold waves: North India fog and cold in December-January. Cyclones: Bay of Bengal coast. Kerala — receives monsoon first (usually June 1)."},"examples":[{"hindi":"भारत में बरसात का मौसम जुलाई में होता है।","transliteration":"Bharat mein barsaat ka mausam July mein hota hai.","english":"The rainy season in India is in July."},{"hindi":"गर्मियों में बहुत गर्मी होती है।","transliteration":"Garmiyon mein bahut garmi hoti hai.","english":"It is very hot in summer."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe India''s seasons and weather in Hindi."}}',
'{"items":[{"word":"मौसम","translation":"weather/season","transliteration":"mausam","pronunciation":"MAU-sam","example":"अच्छा मौसम।"},{"word":"बरसात","translation":"rainy season/rains","transliteration":"barsaat","pronunciation":"bar-SAAT","example":"बरसात का मौसम।"},{"word":"गर्मी","translation":"heat/summer","transliteration":"garmi","pronunciation":"GAR-mee","example":"बहुत गर्मी।"},{"word":"सर्दी","translation":"cold/winter","transliteration":"sardi","pronunciation":"SAR-dee","example":"ठंडी सर्दी।"},{"word":"बाढ़","translation":"flood","transliteration":"baadh","pronunciation":"baadh","example":"बाढ़ आना।"},{"word":"ठंड","translation":"cold (feeling)","transliteration":"thand","pronunciation":"thand","example":"बहुत ठंड है।"}]}',
'{"title":"X में Y होती/होता है — In/during X, Y occurs (seasonal patterns)","pattern":"X में Y होती है (feminine Y) / Y होता है (masculine Y) = In X, Y happens/occurs. Habitual present: होता/होती/होते है/हैं. गर्मियों में गर्मी होती है = In summer there is heat (गर्मी = feminine). जाड़ों में ठंड होती है = In winter there is cold. बरसात में बारिश होती है = In the rains there is rain.","explanation":"Habitual/general truth with होना: X में Y होता/होती है = In X, Y happens (general truth). The verb agrees with Y (the thing that occurs). बारिश (feminine) → होती है. मौसम (masculine) → होता है. Seasonal plurals: गर्मियों में (in summers — oblique plural of गर्मियाँ), सर्दियों में (in winters), बरसातों में (in rainy seasons). Note plural oblique: -याँ → -यों. Also: ठंड लगना = to feel cold (lagna for felt sensations — different construction).","examples":[{"sentence":"पहाड़ों में सर्दियों में बर्फ़ गिरती है।","transliteration":"Pahadon mein sardiyon mein barf giriti hai.","translation":"Snow falls in the mountains in winter."},{"sentence":"दिल्ली में गर्मियों में लू चलती है।","transliteration":"Delhi mein garmiyon mein loo chalti hai.","translation":"Hot winds blow in Delhi in summer."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"मौसम means?","options":["weather/season","monsoon","climate","temperature"],"correctAnswer":"weather/season"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"It is very hot in summer.","options":["गर्मियों में बहुत गर्मी होती है।","सर्दियों में बहुत गर्मी होती है।","गर्मियों में बहुत ठंड होती है।","बरसात में बहुत गर्मी होती है।"],"correctAnswer":"गर्मियों में बहुत गर्मी होती है।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"पहाड़ों में सर्दियों में बर्फ़ ___ है।","options":["गिरती","गिरता","गिरते","आती"],"correctAnswer":"गिरती"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The rainy season in India is in July.","wordBankItems":["भारत","में","बरसात","का","मौसम","जुलाई","में","होता","है","।"],"correctAnswer":"भारत में बरसात का मौसम जुलाई में होता है ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"बाढ़ means?","options":["flood","rain","storm","drought"],"correctAnswer":"flood"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000042',1,'APPROVED','PUBLISHED',
'{"objectives":["Ask for help in Hindi","Use X की मदद चाहिए for needing help","Express inability and request assistance"],"explanation":{"intro":"Asking for help vocabulary covers how to request assistance, express difficulty, and be polite about needing help in Hindi.","culturalNote":"Asking for help in Indian culture: Indians are generally very helpful to strangers — asking for directions (rasta poochhna = रास्ता पूछना) is common and people will often walk with you. Key phrases: kya aap meri madad kar sakte hain? (can you help me?), mujhe X chahiye (I need X), please / kripaya (कृपया = formal please — from Sanskrit kripa = grace). Excuse me: suniye (सुनिए = listen! — used to get attention — no direct Hindi equivalent of ''excuse me''). Sorry: maafi maangna (माफ़ी माँगना = to apologise — from Arabic maafi = forgiveness) or kshama karo (क्षमा करो = forgive me — Sanskrit). Thank you: shukriya (शुक्रिया — from Arabic/Persian), dhanyavaad (धन्यवाद = from Sanskrit). Note: saying please/thank you for every small thing is less common in Hindi than in English — it can sound overly formal between friends and family but is appropriate in formal/service contexts."},"examples":[{"hindi":"क्या आप मेरी मदद कर सकते हैं?","transliteration":"Kya aap meri madad kar sakte hain?","english":"Can you help me?"},{"hindi":"मुझे रास्ता ढूँढने में मदद चाहिए।","transliteration":"Mujhe raasta dhundhne mein madad chahiye.","english":"I need help finding the way."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can ask for help politely and express what I need in Hindi."}}',
'{"items":[{"word":"मदद","translation":"help","transliteration":"madad","pronunciation":"ma-DAD","example":"मदद माँगना।"},{"word":"ढूँढना","translation":"to find/search","transliteration":"dhundhna","pronunciation":"DHUNDH-na","example":"रास्ता ढूँढना।"},{"word":"कृपया","translation":"please (formal)","transliteration":"kripaya","pronunciation":"kri-PA-ya","example":"कृपया मदद करें।"},{"word":"माफ़ करना","translation":"to forgive/excuse","transliteration":"maaf karna","pronunciation":"MAAF kar-na","example":"माफ़ करना।"},{"word":"परेशानी","translation":"trouble/difficulty","transliteration":"pareshani","pronunciation":"pa-re-SHAA-nee","example":"कोई परेशानी नहीं।"},{"word":"धन्यवाद","translation":"thank you","transliteration":"dhanyavaad","pronunciation":"dhan-ya-VAAD","example":"धन्यवाद करना।"}]}',
'{"title":"क्या आप X कर सकते हैं — Can you X? (polite can-question with aap)","pattern":"क्या आप X कर सकते हैं? = Can you X? (formal). क्या (kya) = question marker. आप (aap) = you (formal). X कर सकते हैं = can do X (sakna modal). सकते हैं = 3rd person plural / formal 2nd person (aap takes plural verb). क्या तुम X कर सकते हो? = Can you X? (informal). क्या आप X कर सकती हैं? (if the person is feminine).","explanation":"Polite ability questions: क्या + subject + verb + सकना. Formal: आप → सकते/सकती हैं. Informal: तुम → सकते/सकती हो. Very informal: तू → सकता/सकती है. क्या marks a yes/no question (rising intonation also works without क्या). Answering: हाँ, मैं कर सकता/सकती हूँ (yes, I can). नहीं, मैं कर नहीं सकता (no, I cannot — नहीं between कर and सकता). Alternative: हाँ ज़रूर (yes certainly), मुझे माफ़ करें, मैं नहीं कर सकता (excuse me, I cannot).","examples":[{"sentence":"क्या आप हिंदी बोल सकते हैं?","transliteration":"Kya aap Hindi bol sakte hain?","translation":"Can you speak Hindi?"},{"sentence":"क्या आप मुझे समझा सकते हैं?","transliteration":"Kya aap mujhe samjha sakte hain?","translation":"Can you explain to me?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"परेशानी means?","options":["trouble/difficulty","help","problem","solution"],"correctAnswer":"trouble/difficulty"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Can you help me?","options":["क्या आप मेरी मदद कर सकते हैं?","क्या आप मेरे साथ आ सकते हैं?","क्या मैं आपकी मदद कर सकता हूँ?","क्या आप मुझे समझा सकते हैं?"],"correctAnswer":"क्या आप मेरी मदद कर सकते हैं?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"क्या आप हिंदी बोल ___ हैं?","options":["सकते","सकता","सकती","सकें"],"correctAnswer":"सकते"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I need help finding the way.","wordBankItems":["मुझे","रास्ता","ढूँढने","में","मदद","चाहिए","।"],"correctAnswer":"मुझे रास्ता ढूँढने में मदद चाहिए ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"धन्यवाद means?","options":["thank you","please","sorry","hello"],"correctAnswer":"thank you"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000043',1,'APPROVED','PUBLISHED',
'{"objectives":["Use extended greeting and farewell expressions in Hindi","Respond to greetings appropriately","Know time-based and context-based greetings"],"explanation":{"intro":"Extended greetings and farewells covers a fuller range of how to greet and bid farewell in different contexts — formal, informal, and regional.","culturalNote":"Extended Hindi greetings: Namaste (नमस्ते — universal), Namaskar (नमस्कार — more formal), Jai Shri Ram (जय श्री राम — Hindu religious greeting), Jai Hind (जय हिंद = ''Long live India'' — patriotic). Time-based: Suprabhat (सुप्रभात = good morning — formal), Shubh ratri (शुभ रात्रि = good night — formal). Informal: Kya haal hai? (क्या हाल है? = how are you? — casual), Kya chal raha hai? (क्या चल रहा है? = what''s going on?). Responses: Theek hoon (ठीक हूँ = I''m fine), Sab theek hai (सब ठीक है = all is well), Bas aise hi (बस ऐसे ही = just like this = OK I suppose). Farewells: Alvida (अलविदा = goodbye — from Persian), Phir milenge (फिर मिलेंगे = we will meet again), Namaste (used for both hello and goodbye), Chalte hain (चलते हैं = I''m leaving now — lit. ''we walk''). Regional: Kem cho (Gujarati hello), Vanakkam (Tamil hello), Namaskara (Kannada)."},"examples":[{"hindi":"क्या हाल है? — बस, ठीक हूँ।","transliteration":"Kya haal hai? — Bas, theek hoon.","english":"How are you? — I''m just fine."},{"hindi":"अच्छा, फिर मिलेंगे, नमस्ते!","transliteration":"Accha, phir milenge, namaste!","english":"OK, we will meet again, goodbye!"}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can use a wide range of greetings and farewells in Hindi appropriately."}}',
'{"items":[{"word":"सुप्रभात","translation":"good morning (formal)","transliteration":"suprabhat","pronunciation":"su-pra-BHAT","example":"सुप्रभात कहना।"},{"word":"शुभ रात्रि","translation":"good night (formal)","transliteration":"shubh raatri","pronunciation":"shubh RAAT-ri","example":"शुभ रात्रि।"},{"word":"फिर मिलेंगे","translation":"we will meet again","transliteration":"phir milenge","pronunciation":"phir mi-LEN-ge","example":"फिर मिलेंगे।"},{"word":"चलते हैं","translation":"I am leaving now","transliteration":"chalte hain","pronunciation":"CHAL-te hain","example":"चलते हैं, नमस्ते।"},{"word":"अलविदा","translation":"goodbye (formal)","transliteration":"alvida","pronunciation":"al-vi-DAA","example":"अलविदा कहना।"},{"word":"ठीक हूँ","translation":"I am fine","transliteration":"theek hoon","pronunciation":"theek HOON","example":"मैं ठीक हूँ।"}]}',
'{"title":"Future tense — मिलेंगे/जाएँगे (hum/aap form — we will/you will)","pattern":"Verb stem + एँगे/एगा/एगी = future tense. मिलेंगे = we will meet (1st person plural future). जाएँगे = we will go. हम X करेंगे = we will do X. आप X करेंगे = you will do X (formal). वह X करेगा (ms) / करेगी (fs) = he/she will do X. मैं X करूँगा (ms) / करूँगी (fs) = I will do X.","explanation":"Future tense in Hindi: verb stem + future suffix. Suffixes by person/gender: मैं → ऊँगा/ऊँगी (1sg). तू → एगा/एगी (2sg informal). तुम → ओगे/ओगी (2pl informal). आप → एँगे/एँगी (2 formal). वह/यह → एगा/एगी (3sg). हम → एँगे/एँगी (1pl). वे/ये → एँगे/एँगी (3pl). Key forms: करूँगा, करेगा, करेगी, करेंगे. Future is also used for polite requests: आप करेंगे? (will you do it? = please do it).","examples":[{"sentence":"हम कल बाज़ार जाएँगे।","transliteration":"Hum kal baazaar jaenge.","translation":"We will go to the market tomorrow."},{"sentence":"वह कब आएगा?","transliteration":"Vah kab aayega?","translation":"When will he come?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"अलविदा means?","options":["goodbye (formal)","hello","goodnight","see you soon"],"correctAnswer":"goodbye (formal)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"How are you? — I''m just fine.","options":["क्या हाल है? — बस, ठीक हूँ।","क्या हाल है? — बहुत अच्छा।","आप कैसे हैं? — बस, ठीक हूँ।","सब ठीक है? — हाँ, ठीक हूँ।"],"correctAnswer":"क्या हाल है? — बस, ठीक हूँ।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"हम कल बाज़ार ___ ।","options":["जाएँगे","जाते हैं","गए","जा रहे हैं"],"correctAnswer":"जाएँगे"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: OK, we will meet again, goodbye!","wordBankItems":["अच्छा",",","फिर","मिलेंगे",",","नमस्ते","!"],"correctAnswer":"अच्छा , फिर मिलेंगे , नमस्ते !"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"चलते हैं means?","options":["I am leaving now","let us walk","we are going","please come"],"correctAnswer":"I am leaving now"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000044',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe a person''s appearance in Hindi","Use X जैसा दिखना for looking like someone","Name physical features"],"explanation":{"intro":"Describing people vocabulary covers physical appearance, height, build, hair, and how to describe what someone looks like in Hindi.","culturalNote":"Describing appearance in Hindi: rang (रंग = colour/complexion — a sensitive topic in India — colorism is widespread, fairness products market is huge). Key appearance words: lambaa (tall), chhotaa (short), patla/dubla (thin), mota (fat — less taboo to say directly than in Western cultures), gora (fair-skinned), saanwla (dusky/dark-skinned), kala (black), sundar (beautiful), handsome (handsome), baal (बाल = hair), aankh (आँख = eye), naak (नाक = nose), munh (मुँह = mouth/face). Key: In India it is common and not considered rude to comment directly on someone''s weight or complexion — ''you''ve become fat'' (mote ho gaye) is a common observation, not an insult, between familiar people. Arranged marriage profiles often include height, complexion, and education. Fair & Lovely (now Glow & Lovely) was India''s top-selling skin cream — ''Fair and Lovely'' backlash led to rebrand in 2020."},"examples":[{"hindi":"वह लंबी और गोरी है।","transliteration":"Vah lambi aur gori hai.","english":"She is tall and fair-skinned."},{"hindi":"उसके काले और घुँघराले बाल हैं।","transliteration":"Uske kaale aur ghunghraale baal hain.","english":"She/he has black curly hair."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe a person''s physical appearance in Hindi."}}',
'{"items":[{"word":"लंबा/लंबी","translation":"tall/long (m/f)","transliteration":"lamba/lambi","pronunciation":"LAM-ba/LAM-bi","example":"लंबा आदमी।"},{"word":"बाल","translation":"hair","transliteration":"baal","pronunciation":"baal","example":"काले बाल।"},{"word":"आँख","translation":"eye","transliteration":"aankh","pronunciation":"aankh","example":"बड़ी आँखें।"},{"word":"गोरा/गोरी","translation":"fair-skinned (m/f)","transliteration":"gora/gori","pronunciation":"GO-ra/GO-ri","example":"गोरी लड़की।"},{"word":"घुँघराला","translation":"curly","transliteration":"ghunghraala","pronunciation":"ghun-GHRAA-la","example":"घुँघराले बाल।"},{"word":"मोटा/मोटी","translation":"fat/plump (m/f)","transliteration":"mota/moti","pronunciation":"MO-ta/MO-ti","example":"मोटा बच्चा।"}]}',
'{"title":"X के Y हैं — X has Y (body features — possession with ke)","pattern":"X के Y हैं = X has Y (for body features and inalienable possession). उसके काले बाल हैं = She/he has black hair. X के (oblique possessive) + Y (feature) + हैं. Contrast: X के पास Y है = X has Y (alienable — things that could be given away). Body parts/inherent features: X के + feature + है/हैं.","explanation":"Possession for body features: X के Y हैं (X has Y — inherent possession). उसके बड़ी आँखें हैं = She has big eyes. मेरे सफ़ेद बाल हैं = I have white hair. Compare alienable possession: मेरे पास पैसे हैं (I have money). The distinction: body parts, family members (X के भाई हैं = X has brothers), skills are expressed with के without पास. पास is used for possessable objects. Note: आँखें (plural of आँख — feminine) → बड़ी आँखें हैं (plural agreement).","examples":[{"sentence":"उसके हरी आँखें हैं।","transliteration":"Uske hari aankhein hain.","translation":"She/he has green eyes."},{"sentence":"मेरे पिता के सफ़ेद बाल हैं।","transliteration":"Mere pita ke safed baal hain.","translation":"My father has white hair."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"बाल means?","options":["hair","eye","nose","mouth"],"correctAnswer":"hair"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"She is tall and fair-skinned.","options":["वह लंबी और गोरी है।","वह लंबी और सुंदर है।","वह छोटी और गोरी है।","वह लंबा और गोरा है।"],"correctAnswer":"वह लंबी और गोरी है।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"उसके काले और घुँघराले ___ हैं।","options":["बाल","आँखें","बाहें","हाथ"],"correctAnswer":"बाल"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: My father has white hair.","wordBankItems":["मेरे","पिता","के","सफ़ेद","बाल","हैं","।"],"correctAnswer":"मेरे पिता के सफ़ेद बाल हैं ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"घुँघराला means?","options":["curly","straight","long","short"],"correctAnswer":"curly"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000045',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe a morning routine in Hindi","Use sequence words पहले, फिर, उसके बाद","Talk about habitual morning activities"],"explanation":{"intro":"Morning routine vocabulary covers waking up, washing, eating breakfast, and heading to work or school in Hindi using sequence words.","culturalNote":"Morning routines in India: uthna (उठना = to get up), dant saaf karna (दाँत साफ़ करना = to brush teeth — electric toothbrush increasingly common, but traditional datun/neem twigs still used in villages), muh dhona (मुँह धोना = to wash face), nahana (नहाना = to bathe — daily bathing is important in India — twice daily in hot months), puja karna (पूजा करना = to do morning prayers — very common in Hindu households — lighting incense, lighting lamp before idols). Chai (चाय = tea — the morning ritual — India is the world''s largest tea consumer). Nashta (नाश्ता = breakfast — from Persian naashta = ''not fasted''). Common breakfast: paratha (परांठा) with dahi/pickle, idli-sambar (South India), poha (flattened rice — Central India), upma. School/office hours: most Indians start early — schools at 7-8am, offices 9-10am. Morning walk (morning walk) increasingly popular for health."},"examples":[{"hindi":"सुबह पहले मैं उठता हूँ, फिर चाय पीता हूँ।","transliteration":"Subah pahle main uthta hoon, phir chai peeta hoon.","english":"In the morning I first get up, then I drink tea."},{"hindi":"नाश्ते के बाद मैं दफ़्तर जाता हूँ।","transliteration":"Nashte ke baad main daftar jaata hoon.","english":"After breakfast I go to the office."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my morning routine in Hindi using sequence words."}}',
'{"items":[{"word":"उठना","translation":"to get up","transliteration":"uthna","pronunciation":"UTH-na","example":"सुबह उठना।"},{"word":"नहाना","translation":"to bathe","transliteration":"nahaana","pronunciation":"na-HAA-na","example":"नहाना ज़रूरी है।"},{"word":"नाश्ता","translation":"breakfast","transliteration":"naashta","pronunciation":"NAASH-ta","example":"नाश्ता करना।"},{"word":"पहले","translation":"first/before","transliteration":"pahle","pronunciation":"PAH-le","example":"पहले नहाना।"},{"word":"फिर","translation":"then/afterwards","transliteration":"phir","pronunciation":"phir","example":"फिर खाना।"},{"word":"उसके बाद","translation":"after that","transliteration":"uske baad","pronunciation":"US-ke baad","example":"उसके बाद जाना।"}]}',
'{"title":"Sequence connectors — पहले, फिर, उसके बाद (first, then, after that)","pattern":"पहले X, फिर Y, उसके बाद Z = First X, then Y, after that Z. Sequence connectors join habitual routine clauses. Each clause is a complete sentence: Subject + Verb (habitual). The connectors act as adverbs at the start of clauses. Can also use: बाद में (later), अंत में (finally).","explanation":"Sequence vocabulary for routines: पहले (pahle) = first/before. फिर (phir) = then/next/again. उसके बाद (uske baad) = after that. बाद में (baad mein) = later. अंत में (ant mein) = finally. Used across both present habitual and past narrative. Example narrative chain: पहले मैंने चाय पी, फिर नहाया, उसके बाद दफ़्तर गया. Each verb in past: पी (drank), नहाया (bathed), गया (went). Transitional phrase: जब... तब (when...then) is used for conditional sequences.","examples":[{"sentence":"पहले होमवर्क करो, फिर खेलो।","transliteration":"Pahle homework karo, phir khelo.","translation":"First do homework, then play."},{"sentence":"खाना खाने के बाद थोड़ा आराम करो।","transliteration":"Khaana khaane ke baad thoda aaraam karo.","translation":"After eating, rest a little."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"नाश्ता means?","options":["breakfast","lunch","dinner","snack"],"correctAnswer":"breakfast"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In the morning I first get up, then I drink tea.","options":["सुबह पहले मैं उठता हूँ, फिर चाय पीता हूँ।","सुबह पहले मैं चाय पीता हूँ, फिर उठता हूँ।","रात को पहले मैं उठता हूँ, फिर चाय पीता हूँ।","सुबह पहले मैं उठता हूँ, फिर नाश्ता करता हूँ।"],"correctAnswer":"सुबह पहले मैं उठता हूँ, फिर चाय पीता हूँ।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"खाना खाने के ___ थोड़ा आराम करो।","options":["बाद","पहले","फिर","साथ"],"correctAnswer":"बाद"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: First do homework, then play.","wordBankItems":["पहले","होमवर्क","करो",",","फिर","खेलो","।"],"correctAnswer":"पहले होमवर्क करो , फिर खेलो ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"उसके बाद means?","options":["after that","before that","then","first"],"correctAnswer":"after that"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('cc000000-0000-0000-0000-000000000046',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe an evening routine in Hindi","Use X के बाद Y करना for post-activity sequences","Talk about relaxing and sleeping"],"explanation":{"intro":"Evening routine vocabulary covers coming home from work, evening activities, dinner, and going to sleep in Hindi.","culturalNote":"Evening routines in India: daftar se aana (दफ़्तर से आना = coming from the office), chai peena (चाय पीना = drinking tea — evening tea is another institution, often with biscuits or namkeen/snacks), khaana banana (खाना बनाना = cooking dinner — elaborate in many Indian households), samaachaar dekhna (समाचार देखना = watching news — prime-time news is widely watched), parivaar ke saath baithna (परिवार के साथ बैठना = sitting with family — important daily ritual). TV serials (TV serial/saas-bahu serials) = massive genre. Cricket matches in the evening. Online: OTT platforms — Netflix, Amazon Prime, JioCinema. Sleeping time: Indians typically sleep late — 11pm–midnight is common in cities, earlier in villages. Power cuts (bijli jana = बिजली जाना = electricity going) — still common in some areas, especially in summer."},"examples":[{"hindi":"काम के बाद मैं घर लौटता हूँ और खाना खाता हूँ।","transliteration":"Kaam ke baad main ghar lautha hoon aur khaana khaata hoon.","english":"After work I return home and eat dinner."},{"hindi":"रात को सोने से पहले मैं थोड़ा पढ़ता हूँ।","transliteration":"Raat ko sone se pahle main thoda padhta hoon.","english":"Before sleeping at night I read a little."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my evening routine in Hindi."}}',
'{"items":[{"word":"लौटना","translation":"to return/come back","transliteration":"lautna","pronunciation":"LAUT-na","example":"घर लौटना।"},{"word":"आराम करना","translation":"to rest","transliteration":"aaraam karna","pronunciation":"aa-RAAM kar-na","example":"थोड़ा आराम।"},{"word":"सोना","translation":"to sleep","transliteration":"sona","pronunciation":"SO-na","example":"जल्दी सोना।"},{"word":"रात को","translation":"at night","transliteration":"raat ko","pronunciation":"raat ko","example":"रात को खाना।"},{"word":"थोड़ा","translation":"a little/a bit","transliteration":"thoda","pronunciation":"THO-da","example":"थोड़ा पढ़ना।"},{"word":"से पहले","translation":"before (than)","transliteration":"se pahle","pronunciation":"se PAH-le","example":"सोने से पहले।"}]}',
'{"title":"X से पहले Y करना — Do Y before X (se pahle = before)","pattern":"X से पहले Y = Y before X. से पहले (se pahle) = before (comparative — more than just ''before'' in time — ''prior to X''). सोने से पहले = before sleeping (oblique infinitive + से पहले). X के बाद Y = Y after X (ke baad = after). Contrast: X से पहले (before X) vs. X के बाद (after X).","explanation":"Temporal before/after: से पहले (se pahle) = before. के बाद (ke baad) = after. Both require oblique infinitive when the reference point is an activity: सोना → सोने से पहले (before sleeping). खाना खाना → खाना खाने के बाद (after eating). Pattern: activity infinitive → oblique (stem + ने) + से पहले / के बाद. Examples: नहाने से पहले (before bathing), नाश्ते के बाद (after breakfast — noun, no infinitive needed). पहले vs से पहले: पहले alone = ''first'' (sequence), से पहले = ''before'' (comparison to a reference point).","examples":[{"sentence":"दवाई खाने से पहले डॉक्टर से पूछें।","transliteration":"Dawaai khaane se pahle doctor se poochhen.","translation":"Ask the doctor before taking medicine."},{"sentence":"सोने से पहले दाँत साफ़ करो।","transliteration":"Sone se pahle daant saaf karo.","translation":"Brush your teeth before sleeping."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"लौटना means?","options":["to return/come back","to leave","to arrive","to go"],"correctAnswer":"to return/come back"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"After work I return home and eat dinner.","options":["काम के बाद मैं घर लौटता हूँ और खाना खाता हूँ।","काम के बाद मैं घर जाता हूँ और खाना खाता हूँ।","काम से पहले मैं घर लौटता हूँ और खाना खाता हूँ।","काम के बाद मैं घर लौटता हूँ और सो जाता हूँ।"],"correctAnswer":"काम के बाद मैं घर लौटता हूँ और खाना खाता हूँ।"},{"id":"ex3","type":"FILL_IN_BLANK","question":"सोने ___ पहले दाँत साफ़ करो।","options":["से","के","में","को"],"correctAnswer":"से"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Before sleeping at night I read a little.","wordBankItems":["रात","को","सोने","से","पहले","मैं","थोड़ा","पढ़ता","हूँ","।"],"correctAnswer":"रात को सोने से पहले मैं थोड़ा पढ़ता हूँ ।"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"से पहले means?","options":["before (than)","after","during","until"],"correctAnswer":"before (than)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('ee000000-0000-0000-0000-00000000003d','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l061',61,'Post Office and Banking','Post office and banking services','PUBLISHED'),
('ee000000-0000-0000-0000-00000000003e','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l062',62,'Phone and Internet','Phone and internet communication','PUBLISHED'),
('ee000000-0000-0000-0000-00000000003f','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l063',63,'Restaurant and Dining Out','Ordering food and dining out','PUBLISHED'),
('ee000000-0000-0000-0000-000000000040','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l064',64,'Adjectives — Describing Things','Descriptive adjectives','PUBLISHED'),
('ee000000-0000-0000-0000-000000000041','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l065',65,'Seasons and Climate','Seasons and Indian climate','PUBLISHED'),
('ee000000-0000-0000-0000-000000000042','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l066',66,'Asking for Help','Asking for help and assistance','PUBLISHED'),
('ee000000-0000-0000-0000-000000000043','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l067',67,'Greetings and Farewells Extended','Extended greetings and farewells','PUBLISHED'),
('ee000000-0000-0000-0000-000000000044','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l068',68,'Describing People — Appearance','Describing physical appearance','PUBLISHED'),
('ee000000-0000-0000-0000-000000000045','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l069',69,'Daily Routine — Morning','Morning routine vocabulary','PUBLISHED'),
('ee000000-0000-0000-0000-000000000046','bb000000-0000-0000-0000-000000000001','bb100000-0000-0000-0000-000000000001',NULL,'hi-a1-u01-l070',70,'Daily Routine — Evening','Evening routine vocabulary','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-00000000003d' WHERE stable_ref = 'hi-a1-u01-l061' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-00000000003e' WHERE stable_ref = 'hi-a1-u01-l062' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-00000000003f' WHERE stable_ref = 'hi-a1-u01-l063' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000040' WHERE stable_ref = 'hi-a1-u01-l064' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000041' WHERE stable_ref = 'hi-a1-u01-l065' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000042' WHERE stable_ref = 'hi-a1-u01-l066' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000043' WHERE stable_ref = 'hi-a1-u01-l067' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000044' WHERE stable_ref = 'hi-a1-u01-l068' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000045' WHERE stable_ref = 'hi-a1-u01-l069' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'cc000000-0000-0000-0000-000000000046' WHERE stable_ref = 'hi-a1-u01-l070' AND lesson_id IS NULL;
