-- V120: Kannada curriculum setup + lessons 1-10
-- Creates curriculum, CEFR levels, then first 10 Kannada A1 lessons
-- Hex: 1=0x1, 2=0x2 ... 10=0xa
-- ALL CONTENT IN ENGLISH / ROMAN TRANSLITERATION ONLY — no Kannada script

-- Curriculum
INSERT INTO cf_curricula (id, stable_ref, title, language_code, description, status) VALUES
('ff000000-0000-0000-0000-000000000001','kannada-complete-v1','Kannada Complete','kn','Complete Kannada language curriculum A1-B2','PUBLISHED')
ON CONFLICT (stable_ref) DO NOTHING;

-- CEFR Levels
INSERT INTO cf_curriculum_levels (id, curriculum_id, cefr_level, ordinal, title, description) VALUES
('ff100000-0000-0000-0000-000000000001','ff000000-0000-0000-0000-000000000001','A1',1,'Kannada A1 — Beginner','Basic Kannada: greetings, introductions, daily essentials'),
('ff100000-0000-0000-0000-000000000002','ff000000-0000-0000-0000-000000000001','A2',2,'Kannada A2 — Elementary','Elementary Kannada: everyday topics, simple descriptions'),
('ff100000-0000-0000-0000-000000000003','ff000000-0000-0000-0000-000000000001','B1',3,'Kannada B1 — Intermediate','Intermediate Kannada: opinions, narratives, practical needs'),
('ff100000-0000-0000-0000-000000000004','ff000000-0000-0000-0000-000000000001','B2',4,'Kannada B2 — Upper Intermediate','Upper intermediate Kannada: complex topics, nuanced expression')
ON CONFLICT (id) DO NOTHING;

-- Lessons 1-10
INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('11000000-0000-0000-0000-000000000001','kn-a1-l001','Greetings and Basic Introductions','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000002','kn-a1-l002','Numbers 1-20','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000003','kn-a1-l003','Family Members','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000004','kn-a1-l004','Colors and Basic Adjectives','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000005','kn-a1-l005','Days of the Week and Months','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000006','kn-a1-l006','Food and Drinks','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000007','kn-a1-l007','Asking for Directions','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000008','kn-a1-l008','At the Market — Shopping','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000009','kn-a1-l009','Daily Routine','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-00000000000a','kn-a1-l010','Weather and Seasons','language','kn','A1','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000001',1,'APPROVED','PUBLISHED',
'{"objectives":["Greet people in Kannada at different times of day","Introduce yourself using basic Kannada phrases","Say please, thank you, and sorry"],"explanation":{"intro":"Kannada is the official language of Karnataka state in South India. It is a Dravidian language with about 40 million native speakers. Learning Kannada opens up Karnataka — Bengaluru (Bangalore), Mysuru (Mysore), Hampi, Coorg, and much more.","culturalNote":"Kannada greetings: Namaskara (the universal greeting — equivalent to Namaste in Hindi — hands pressed together). Kannada has distinct formal and informal registers. Formal (to elders/strangers): use -iru/-avaru endings. Informal (friends/younger): use -u/-o endings. Time-based greetings: shubha (auspicious) + time. Shubha prabhate (good morning — prabhate = morning), shubha saanje (good evening — saanje = evening). Most urban Karnatakans also use Good morning/evening in English. Respect: banni (come — formal welcome), neevu (you — formal), neenu (you — informal). Bengaluru culture: very cosmopolitan — IT city — mix of Kannadigas, Hindi speakers, Tamil speakers, and English speakers."},"examples":[{"sentence":"Namaskara, neevu hege iddiri?","english":"Hello, how are you? (formal)"},{"sentence":"Naanu Priya, neevu yaaru?","english":"I am Priya, who are you? (formal)"}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can greet people and introduce myself in basic Kannada."}}',
'{"items":[{"word":"Namaskara","translation":"Hello/Greetings (universal Kannada greeting)","transliteration":"Namaskara","pronunciation":"na-mas-KA-ra","example":"Namaskara, hege iddiri?"},{"word":"hege iddiri","translation":"how are you? (formal)","transliteration":"hege iddiri","pronunciation":"HE-ge id-DI-ri","example":"neevu hege iddiri?"},{"word":"chennagiddini","translation":"I am fine (formal)","transliteration":"chennagiddini","pronunciation":"chen-na-GID-di-ni","example":"naanu chennagiddini"},{"word":"dhanyavadagalu","translation":"thank you (formal)","transliteration":"dhanyavadagalu","pronunciation":"dhan-ya-VA-da-ga-lu","example":"dhanyavadagalu"},{"word":"kshamisi","translation":"sorry/excuse me (formal)","transliteration":"kshamisi","pronunciation":"ksha-MI-si","example":"kshamisi, naanu"},{"word":"yaaru","translation":"who","transliteration":"yaaru","pronunciation":"YAA-ru","example":"neevu yaaru?"}]}',
'{"title":"Naanu X — I am X (Kannada verb to be in present tense)","pattern":"Naanu X = I am X. Naanu = I (first person singular). In Kannada, the verb to be is usually implied or expressed as iddini (I am — formal) / iddeeni (I am — informal). Present tense: naanu X iddini (I am X). Simple identification: naanu Priya (I am Priya — verb implied).","explanation":"Kannada personal pronouns: naanu (I), neevu (you — formal), neenu (you — informal), avaru (he/she — formal/plural), avanu (he — informal), avalu (she — informal). To be: iddini (I am — 1st person formal), iddiri (you are — 2nd person formal), iddaare (they are — 3rd formal), iddeeni (I am — informal). For greetings: hege iddiri? (how are you? — formal, lit. how are you being/sitting?). Responses: chennagiddini (I am fine/well — chenna = good + iddini = am). Super: taambula chennagiddini (I am very well). Common: gottilla (I don''t know — got = known + tilla = not).","examples":[{"sentence":"Naanu Bengaluruinda bande.","english":"I came from Bengaluru."},{"sentence":"Neevu yaavudu college alli oduttiddiri?","english":"Which college are you studying in? (formal)"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Namaskara means?","options":["Hello/Greetings","Goodbye","Thank you","Sorry"],"correctAnswer":"Hello/Greetings"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Hello, how are you? (formal)","options":["Namaskara, neevu hege iddiri?","Namaskara, neenu hege iddiya?","Namaskara, avaru hege iddaare?","Namaskara, naanu hege iddini?"],"correctAnswer":"Namaskara, neevu hege iddiri?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Naanu ___ , dhanyavadagalu.","options":["chennagiddini","hege iddiri","yaaru","namaskara"],"correctAnswer":"chennagiddini"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I am Priya, who are you?","wordBankItems":["Naanu","Priya",",","neevu","yaaru","?"],"correctAnswer":"Naanu Priya , neevu yaaru ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"dhanyavadagalu means?","options":["thank you (formal)","sorry","hello","goodbye"],"correctAnswer":"thank you (formal)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000002',1,'APPROVED','PUBLISHED',
'{"objectives":["Count from 1 to 20 in Kannada","Use numbers in simple sentences","Ask and answer about age and quantity"],"explanation":{"intro":"Kannada numbers 1-20 follow Dravidian number patterns. Unlike Hindi which uses Sanskrit-based numbers, Kannada has its own distinct number system rooted in the Dravidian language family.","culturalNote":"Numbers in Kannada daily life: market prices (ondu kilo tomato eshtu? — how much for one kilo of tomato?), bus numbers (bus number ondu nooraipatthu = bus number 120), addresses (munnooru hatinaidu main road = 315 main road). Karnataka''s silk industry (Mysuru silk), coffee (Coorg coffee), and sandalwood (chandan) are famous. Number use: eshtu? (how much/many? — essential shopping question), eshtu aagutte? (how much will it cost?). Age: nimage eshtu varsha? (how old are you? — eshtu = how much/many, varsha = year). Phone numbers are read digit by digit in Kannada."},"examples":[{"sentence":"Ondu, eradu, mooru, naalku, aidu...","english":"One, two, three, four, five..."},{"sentence":"Nimage eshtu varsha?","english":"How old are you?"}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can count to 20 in Kannada and use numbers in basic sentences."}}',
'{"items":[{"word":"ondu","translation":"one (1)","transliteration":"ondu","pronunciation":"ON-du","example":"ondu kilo"},{"word":"eradu","translation":"two (2)","transliteration":"eradu","pronunciation":"E-ra-du","example":"eradu jana"},{"word":"mooru","translation":"three (3)","transliteration":"mooru","pronunciation":"MOO-ru","example":"mooru dina"},{"word":"naalku","translation":"four (4)","transliteration":"naalku","pronunciation":"NAAL-ku","example":"naalku rupai"},{"word":"aidu","translation":"five (5)","transliteration":"aidu","pronunciation":"AI-du","example":"aidu minute"},{"word":"eshtu","translation":"how many/how much","transliteration":"eshtu","pronunciation":"ESH-tu","example":"eshtu aagutte?"}]}',
'{"title":"Kannada numbers 1-20 — ondu through ippattu","pattern":"1-10: ondu, eradu, mooru, naalku, aidu, aaru, yelu, entu, ombattu, hattu. 11-20: hannondu (11), hanneradu (12), hadinmooru (13), hadinaalu (14), hadhinaidu (15), hadinaaru (16), hadinaelu (17), hadinentu (18), hattonombattu (19), ippattu (20). Pattern for 11-19: hadin + lower number. eshtu = how many/much (quantity question).","explanation":"Kannada number system: 1-10 are base forms. 11-19 are formed from hadin (10-) + unit number: hannondu (11 = hattu + ondu), hanneradu (12 = hattu + eradu), hadinmooru (13), etc. Note: 11 = hannondu (not hadinondu — irregular). 20 = ippattu. 30 = moovattu. 40 = nalavattu. 50 = aimpattu. 100 = nooru. Age: naanu X varshada (I am X years old — varshada = of years). Counting things: X jana (X people), X kilo (X kilos), X nooraipatthu = 120 (nootippattu).","examples":[{"sentence":"Naanu ippattu oondu varshada.","english":"I am 21 years old."},{"sentence":"Mooru kilo anguri eshtu aagutte?","english":"How much will three kilos of grapes cost?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"eradu means?","options":["two (2)","three (3)","one (1)","four (4)"],"correctAnswer":"two (2)"},{"id":"ex2","type":"MULTIPLE_CHOICE","question":"eshtu means?","options":["how many/how much","how old","how far","how long"],"correctAnswer":"how many/how much"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ondu, eradu, mooru, naalku, ___ .","options":["aidu","aaru","yelu","entu"],"correctAnswer":"aidu"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: How old are you?","wordBankItems":["Nimage","eshtu","varsha","?"],"correctAnswer":"Nimage eshtu varsha ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"hattu means?","options":["ten (10)","eight (8)","seven (7)","nine (9)"],"correctAnswer":"ten (10)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000003',1,'APPROVED','PUBLISHED',
'{"objectives":["Name family members in Kannada","Use X nanna Y for family relationships","Describe your family composition"],"explanation":{"intro":"Family vocabulary is fundamental for daily conversation. Karnataka has strong family traditions with close-knit extended family networks.","culturalNote":"Family structure in Karnataka: joint family system (ootada mane = house of the meal — describes the joint family living arrangement). Distinct terms for paternal and maternal relatives (unlike English): nanna appa (my father), nanna amma (my mother). Grandparents: ajja (grandfather — paternal or general), ajji (grandmother — paternal or general), thatha (grandfather — also used), paati (grandmother — South Indian — from Tamil paatti). Siblings: anna (elder brother — used also as respectful term for any older man), akka (elder sister — respectful for older women), tamma (younger brother), tangi (younger sister). Marriage: ganda (husband), hendu (wife). Children: magana (son), maga (son — informal), magalu (daughter). Karnataka culture: family ties extremely strong — grandparents often live with or near adult children."},"examples":[{"sentence":"Nanna appa Bengalurualli kaela maaduttaare.","english":"My father works in Bengaluru."},{"sentence":"Nanna amma maneyalli iruttaare.","english":"My mother is at home."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name family members and describe my family in Kannada."}}',
'{"items":[{"word":"appa","translation":"father","transliteration":"appa","pronunciation":"AP-pa","example":"nanna appa"},{"word":"amma","translation":"mother","transliteration":"amma","pronunciation":"AM-ma","example":"nanna amma"},{"word":"anna","translation":"elder brother (also respectful for older men)","transliteration":"anna","pronunciation":"AN-na","example":"nanna anna"},{"word":"akka","translation":"elder sister (also respectful for older women)","transliteration":"akka","pronunciation":"AK-ka","example":"nanna akka"},{"word":"ajja","translation":"grandfather","transliteration":"ajja","pronunciation":"AJ-ja","example":"nanna ajja"},{"word":"ajji","translation":"grandmother","transliteration":"ajji","pronunciation":"AJ-ji","example":"nanna ajji"}]}',
'{"title":"Nanna X — My X (possession in Kannada)","pattern":"Nanna X = My X. Nanna = my (first person possessive). Ninna X = Your X (informal). Nimma X = Your X (formal). Avara X = His/Her X (formal). Avana X = His X. Avala X = Her X. Possessives are placed before the noun: nanna appa (my father), ninna amma (your mother).","explanation":"Possessives in Kannada: nanna (my), ninna (your — informal), nimma (your — formal), avana (his), avala (her), avara (their/his-her — formal), namagenella (our). Possessive comes before the noun. Relationship questions: neevu yaavudu ooliga iddiri? (where are you from?), nimage makkalu iddaara? (do you have children? — makkalu = children, plural). Family action verbs: iruttaare (is/stays — 3rd person formal), kaela maaduttaare (works — 3rd formal).","examples":[{"sentence":"Nanna kutumba Mysuralli ide.","english":"My family is in Mysuru."},{"sentence":"Nimage tammandirigaalu iddaara?","english":"Do you have younger siblings? (formal)"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"appa means?","options":["father","mother","grandfather","uncle"],"correctAnswer":"father"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"My father works in Bengaluru.","options":["Nanna appa Bengalurualli kaela maaduttaare.","Nanna amma Bengalurualli kaela maaduttaare.","Nanna appa Mysuralli kaela maaduttaare.","Nimma appa Bengalurualli kaela maaduttaare."],"correctAnswer":"Nanna appa Bengalurualli kaela maaduttaare."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Nanna ___ maneyalli iruttaare.","options":["amma","appa","anna","akka"],"correctAnswer":"amma"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: My family is in Mysuru.","wordBankItems":["Nanna","kutumba","Mysuralli","ide","."],"correctAnswer":"Nanna kutumba Mysuralli ide ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"ajji means?","options":["grandmother","grandfather","aunt","elder sister"],"correctAnswer":"grandmother"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000004',1,'APPROVED','PUBLISHED',
'{"objectives":["Name colors in Kannada","Use X bana for color descriptions","Describe objects using basic adjectives"],"explanation":{"intro":"Colors and adjectives are essential for describing the world around you. In Kannada, color adjectives typically come before the noun and agree with context.","culturalNote":"Colors in Karnataka culture: kempu (red) — auspicious for weddings — brides wear red silk sarees (Mysuru silk famous worldwide — Mysuru Dasara procession features beautifully adorned elephants in red and gold). Hasi (green) — Karnataka''s color — the state flag is red-yellow-white but green fields of Coorg (Kodagu) and Western Ghats are iconic. Neeli (blue) — blue nile lily (Neelakurinji — blooms once every 12 years in Shola grasslands of Western Ghats). Bili (white) — white sandalwood (Mysuru sandalwood). Kanagambara (orange/saffron) — sacred flowers at temples. Hasibeeja oilseeds (groundnut/sunflower — yellow). Karuvalli (black pepper from Karnataka — Coorg is major producer)."},"examples":[{"sentence":"Aa kempu saree thumba chennagide.","english":"That red saree is very beautiful."},{"sentence":"Nanna mane bili bana ide.","english":"My house is white coloured."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name colors and describe objects using basic adjectives in Kannada."}}',
'{"items":[{"word":"kempu","translation":"red","transliteration":"kempu","pronunciation":"KEM-pu","example":"kempu saree"},{"word":"neeli","translation":"blue","transliteration":"neeli","pronunciation":"NEE-li","example":"neeli baraha"},{"word":"hasi","translation":"green","transliteration":"hasi","pronunciation":"ha-SI","example":"hasi beeja"},{"word":"bili","translation":"white","transliteration":"bili","pronunciation":"BI-li","example":"bili mane"},{"word":"karimbudu","translation":"black","transliteration":"karimbudu","pronunciation":"ka-RIM-bu-du","example":"karimbudu nayee"},{"word":"bana","translation":"colour/shade","transliteration":"bana","pronunciation":"BA-na","example":"kempu bana"}]}',
'{"title":"X bana — X colour (colour description in Kannada)","pattern":"X bana = X colour. Aa X kempu bana ide = That X is red colour. Bana = colour/shade (neuter). Describing colour: X kempu bana ide (X is red, lit. X red colour is). Adjective placement: adjective before noun — kempu saree (red saree), bili mane (white house), hasi gida (green plant).","explanation":"Color adjectives in Kannada: colors go before the noun. Kempu (red), neeli (blue), hasi/hasiru (green), bili (white), karimbudu/kariya (black), halli hasivu (yellow — halli hasivu = yellow-green, but hasivu or haladi bana is used for yellow), naringa bana (orange — naringa = orange). Bana (colour) can be added after the color for emphasis: kempu bana (red colour). Describing intensely: thumba kempu (very red). Describing lightly: konda kempu (slightly red). Basic adjectives: dodda (big), chikka (small), hosa (new), haLe (old), channa/chennagide (beautiful).","examples":[{"sentence":"Aa dodda mane nanna ajjiyadi.","english":"That big house belongs to my grandmother."},{"sentence":"Chikka hosi kitabi eshtu aagutte?","english":"How much does the small new book cost?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"kempu means?","options":["red","blue","green","white"],"correctAnswer":"red"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"That red saree is very beautiful.","options":["Aa kempu saree thumba chennagide.","Aa neeli saree thumba chennagide.","Aa kempu saree thakku chennagide.","Ee kempu saree thumba chennagide."],"correctAnswer":"Aa kempu saree thumba chennagide."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Nanna mane ___ bana ide.","options":["bili","kempu","neeli","hasi"],"correctAnswer":"bili"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: My house is white coloured.","wordBankItems":["Nanna","mane","bili","bana","ide","."],"correctAnswer":"Nanna mane bili bana ide ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"hasi means?","options":["green","yellow","blue","fresh"],"correctAnswer":"green"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000005',1,'APPROVED','PUBLISHED',
'{"objectives":["Name days of the week and months in Kannada","Ask and answer about today''s day and date","Plan activities using day names"],"explanation":{"intro":"Days of the week and months are essential for scheduling, appointments, and daily conversation. Kannada uses Sanskrit-based names for days of the week.","culturalNote":"Calendar in Karnataka: the week starts on Sunday (bhanu vaara — sun day). Sanskrit origins: bhanu = sun, soma = moon, mangala = Mars, budha = Mercury, guru = Jupiter, shukra = Venus, shani = Saturn. Kannada months (traditional): Chaitra, Vaishakha, Jyeshtha, Aashaadha, Shraavana, Bhadrapada, Aashvina, Kaartika, Maargashirsha, Pushya, Maagha, Phaalguna (lunar calendar). Modern Kannada mostly uses English month names. Festival timing: Ugaadi (Kannada New Year — around March/April — chaitra maasa shukla paksha prathama tithi). Dasara — Mysuru Dasara (October — state festival of Karnataka — grand celebration in Mysuru). Sankranti (January 14 — harvest festival). Important: soma vaara (Monday) is considered auspicious for temple visits; guru vaara (Thursday) and shukra vaara (Friday) too."},"examples":[{"sentence":"Inja yaava vaara?","english":"What day is today?"},{"sentence":"Naale soma vaara, naanu doctaralli hogutte.","english":"Tomorrow is Monday, I am going to the doctor."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name days of the week and use them in basic scheduling sentences in Kannada."}}',
'{"items":[{"word":"bhanu vaara","translation":"Sunday","transliteration":"bhanu vaara","pronunciation":"BHA-nu VAA-ra","example":"bhanu vaara school illa"},{"word":"soma vaara","translation":"Monday","transliteration":"soma vaara","pronunciation":"SO-ma VAA-ra","example":"soma vaara kaela"},{"word":"mangala vaara","translation":"Tuesday","transliteration":"mangala vaara","pronunciation":"MAN-ga-la VAA-ra","example":"mangala vaara temple"},{"word":"budha vaara","translation":"Wednesday","transliteration":"budha vaara","pronunciation":"BU-dha VAA-ra","example":"budha vaara meeting"},{"word":"guru vaara","translation":"Thursday","transliteration":"guru vaara","pronunciation":"GU-ru VAA-ra","example":"guru vaara puja"},{"word":"inja","translation":"today","transliteration":"inja","pronunciation":"IN-ja","example":"inja yaava vaara?"}]}',
'{"title":"Inja X vaara — Today is X day (day names in Kannada)","pattern":"Inja X vaara = Today is X day. Inja = today. Naale = tomorrow. Ninne = yesterday. Vaara = day/week. Inja yaava vaara? = What day is today? Inja soma vaara (Today is Monday). Days: bhanu vaara (Sunday), soma vaara (Monday), mangala vaara (Tuesday), budha vaara (Wednesday), guru vaara (Thursday), shukra vaara (Friday), shani vaara (Saturday).","explanation":"Days of the week in Kannada: all end in -vaara (day/week). Shukra vaara (Friday) and guru vaara (Thursday) are considered auspicious. Asking: inja yaava vaara? (what day is today?). Answering: inja X vaara (today is X day). Time words: inja (today), naale (tomorrow), ninne (yesterday), naaLe-naaLe (day after tomorrow), ninne-ninne (day before yesterday). Months: January through December are called by their English names in modern Kannada. Traditional Kannada months use the Sanskrit lunar calendar but these are used mainly for religious purposes.","examples":[{"sentence":"Shani vaara haagu bhanu vaara school biddi.","english":"Saturday and Sunday are school holidays."},{"sentence":"Guru vaara nanna appointment ide.","english":"I have an appointment on Thursday."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"inja means?","options":["today","tomorrow","yesterday","now"],"correctAnswer":"today"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"What day is today?","options":["Inja yaava vaara?","Naale yaava vaara?","Inja eshtu gante?","Ninne yaava vaara itu?"],"correctAnswer":"Inja yaava vaara?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Naale soma vaara, naanu doctaralli ___ .","options":["hogutte","iddini","baruttini","kaeluttini"],"correctAnswer":"hogutte"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Saturday and Sunday are school holidays.","wordBankItems":["Shani","vaara","haagu","bhanu","vaara","school","biddi","."],"correctAnswer":"Shani vaara haagu bhanu vaara school biddi ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"soma vaara means?","options":["Monday","Sunday","Saturday","Tuesday"],"correctAnswer":"Monday"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000006',1,'APPROVED','PUBLISHED',
'{"objectives":["Name common foods and drinks in Kannada","Use naanu X tinnuttini for eating/drinking","Order food at a restaurant or describe preferences"],"explanation":{"intro":"Food vocabulary is essential for daily life in Karnataka. Karnataka cuisine is rich and varied — from Udupi vegetarian food to Coorg pork dishes.","culturalNote":"Karnataka cuisine: huggi (rice and lentil porridge — pongal equivalent), akki rotti (rice flat bread), ragi mudde (finger millet ball — staple food of rural Karnataka — eaten with sambar), bisi bele bath (hot lentil rice — literally hot-lentil-cooked rice — famous Karnataka dish), saaru (rasam/sambar — thin lentil soup), palya (dry vegetable stir-fry), obbattu/holige (sweet flatbread — Ugaadi specialty), maddur vade (crispy flat vada — speciality of Maddur town). Coffee: South India, especially Coorg (Kodagu), produces 70% of India''s coffee — Coorg coffee is famous. Filter coffee (filter kaapi) is the quintessential Karnataka beverage — served in a steel tumbler-and-dabarah. Masala dosa originated in Udupi, Karnataka."},"examples":[{"sentence":"Naanu ragi mudde tinnuttini.","english":"I eat ragi mudde."},{"sentence":"Ondu filter kaapi kodi.","english":"Give me one filter coffee."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name common Karnataka foods and drinks and order at a restaurant."}}',
'{"items":[{"word":"anna","translation":"cooked rice (food)","transliteration":"anna","pronunciation":"AN-na","example":"anna tinnu"},{"word":"sambar","translation":"lentil-vegetable soup (sambar)","transliteration":"sambar","pronunciation":"SAM-bar","example":"sambar haakkondu"},{"word":"kaapi","translation":"coffee","transliteration":"kaapi","pronunciation":"KAA-pi","example":"filter kaapi"},{"word":"chai","translation":"tea","transliteration":"chai","pronunciation":"chai","example":"chai kudi"},{"word":"tinnuttini","translation":"I eat (present tense)","transliteration":"tinnuttini","pronunciation":"tin-NUT-ti-ni","example":"naanu X tinnuttini"},{"word":"kudiyuttini","translation":"I drink (present tense)","transliteration":"kudiyuttini","pronunciation":"ku-di-YUT-ti-ni","example":"naanu kaapi kudiyuttini"}]}',
'{"title":"Naanu X tinnuttini / kudiyuttini — I eat/drink X (food action in Kannada)","pattern":"Naanu X tinnuttini = I eat X (present habitual). Naanu X kudiyuttini = I drink X (present habitual). Tinnuttini = I eat (tinnu = eat, -uttini = I do habitually, 1st person). Kudiyuttini = I drink (kudiyuttini = I drink). Ordering: ondu X kodi = give me one X (kodi = give — imperative command for requesting).","explanation":"Food verbs in Kannada: tinnu (eat), kudiyu/kudiyuttini (drink), maadu (make/do), kodi (give — used for ordering). Present habitual tense: verb stem + uttini (1st person), uttaare (3rd formal), uttaane (3rd informal — male), uttaaLe (3rd informal — female). Tinnu → tinnuttini (I eat — habitual). Kudiyu → kudiyuttini (I drink). Requesting food: X kodi (give X — used in restaurants, shops). Please: dayavittu X kodi (please give X — dayavittu = please/kindly). How much: eshtu? (how much?). More: innastu (more). Enough: saakaagutte (that''s enough).","examples":[{"sentence":"Naanu pratidinaa filter kaapi kudiyuttini.","english":"I drink filter coffee every day."},{"sentence":"Dayavittu ondu masala dosa kodi.","english":"Please give me one masala dosa."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"kaapi means?","options":["coffee","tea","water","juice"],"correctAnswer":"coffee"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Give me one filter coffee.","options":["Ondu filter kaapi kodi.","Eradu filter kaapi kodi.","Ondu chai kodi.","Ondu coffee kudiyuttini."],"correctAnswer":"Ondu filter kaapi kodi."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Naanu ragi mudde ___ .","options":["tinnuttini","kudiyuttini","maaduttini","koduttini"],"correctAnswer":"tinnuttini"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Please give me one masala dosa.","wordBankItems":["Dayavittu","ondu","masala","dosa","kodi","."],"correctAnswer":"Dayavittu ondu masala dosa kodi ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"kodi means?","options":["give (imperative for ordering)","come","go","take"],"correctAnswer":"give (imperative for ordering)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000007',1,'APPROVED','PUBLISHED',
'{"objectives":["Ask for and give directions in Kannada","Use eliige hogabeku for asking where to go","Understand left, right, straight, near, far"],"explanation":{"intro":"Directions vocabulary is essential for navigating Karnataka''s cities and towns. Bengaluru''s rapid growth means landmarks change frequently — knowing how to ask and give directions is critical.","culturalNote":"Navigation in Bengaluru: Bengaluru (Bangalore) is India''s fastest-growing metropolis — IT capital — but notorious for traffic jams (jaamu — traffic jam). Metro (Namma Metro — our metro — Blue Line, Green Line). Auto-rickshaw (auto) — three-wheeler — the primary short-distance transport — negotiate fare or use Ola/Uber auto. Landmarks: MG Road (Mahatma Gandhi Road), Brigade Road, Koramangala, Indiranagar, Jayanagar, Rajajinagar — all are well-known areas. Mysuru: beautiful planned city — wide roads — easier to navigate. Giving directions: bala (right — lit. right hand side), eduru (left — lit. opposite/left), nera (straight). Distance: yaava distance? (how far?). Near: hattira (near — hattira = close/near). Far: doora (far — doora = distant)."},"examples":[{"sentence":"Bus stand eliide?","english":"Where is the bus stand?"},{"sentence":"Nera hogi, nantara bala tiriyi.","english":"Go straight, then turn right."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can ask for and follow directions in Kannada."}}',
'{"items":[{"word":"eliide","translation":"where is (informal)/where is it?","transliteration":"eliide","pronunciation":"e-LII-de","example":"hospital eliide?"},{"word":"nera","translation":"straight","transliteration":"nera","pronunciation":"NE-ra","example":"nera hogi"},{"word":"bala","translation":"right (direction)","transliteration":"bala","pronunciation":"BA-la","example":"bala tiriyi"},{"word":"eduru","translation":"left (direction) / opposite","transliteration":"eduru","pronunciation":"e-DU-ru","example":"eduru tiriyi"},{"word":"hattira","translation":"near/close","transliteration":"hattira","pronunciation":"HAT-ti-ra","example":"hattira ide"},{"word":"doora","translation":"far/distant","transliteration":"doora","pronunciation":"DOO-ra","example":"thumba doora"}]}',
'{"title":"X eliide? / eliige hogabeku? — Where is X? / Where do I need to go? (directions)","pattern":"X eliide? = Where is X? (informal). X ellidhe? = Where is X? (slightly formal). Eliige hogabeku = where do I need to go? (hogabeku = need to go). Directions: nera hogi (go straight), bala tiriyi (turn right), eduru/edurge tiriyi (turn left), X hattira ide (X is near), X doora ide (X is far). After: nantara (after/then), mundhe (front/ahead).","explanation":"Directions in Kannada: location questions use ellidhe (where is) or eliide (informal). Going: hogi (go — imperative informal), hoguvi (go — formal/plural). Turn: tiriyi (turn — imperative informal), tiriyiri (turn — formal). Distance: X hattira ide (X is near). Thumba doora (very far). Yeshtu doora? (how far?). Landmark navigation: X ge hogabeku (need to go to X — X ge = to X). Common landmarks: metro station (metro station), main road (main road), circle (circle — roundabout), signal (traffic signal/intersection). Auto reference: nimage X ge hogabeka? (do you need to go to X? — asking a passenger).","examples":[{"sentence":"Railway station hattira haagu nera hoguvante.","english":"The railway station is near and it seems you can go straight."},{"sentence":"Edurge tiri, nantara nooru meetar nera hogi.","english":"Turn left, then go 100 metres straight."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"nera means?","options":["straight","right","left","near"],"correctAnswer":"straight"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Where is the bus stand?","options":["Bus stand eliide?","Bus stand eliige?","Bus stand hattira ide?","Bus stand hogabeku?"],"correctAnswer":"Bus stand eliide?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Nera hogi, nantara ___ tiriyi.","options":["bala","eduru","nera","doora"],"correctAnswer":"bala"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Go straight, then turn right.","wordBankItems":["Nera","hogi",",","nantara","bala","tiriyi","."],"correctAnswer":"Nera hogi , nantara bala tiriyi ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"hattira means?","options":["near/close","far","straight","turn"],"correctAnswer":"near/close"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000008',1,'APPROVED','PUBLISHED',
'{"objectives":["Shop at a market in Kannada","Ask the price using eshtu?","Bargain and negotiate politely"],"explanation":{"intro":"Market shopping is a daily activity in Karnataka. Knowing how to ask prices and negotiate in Kannada makes shopping much easier and more authentic.","culturalNote":"Markets in Karnataka: KR Market (Krishna Rajendra Market in Bengaluru — one of Asia''s largest wholesale flower markets — 8000 tonnes of flowers traded weekly — spectacular). Devaraja Market in Mysuru — famous for silk, sandalwood, spices. Chickpet area (Bengaluru''s traditional wholesale market — silk sarees, cloth, utensils). Sabzi mandi (vegetable market). Street vendors (arali angadi = roadside shop). Bargaining: very common at local markets and with auto-rickshaws — less so in malls and supermarkets. Price haggling: yeshtu? (how much?), jasti aagutte (too much!), komme maadi (reduce a little), last price eshtu? (what is the final/last price?). Silk: Karnataka produces 70% of India''s mulberry silk — Mysuru silk is internationally renowned."},"examples":[{"sentence":"Ee tomato ondu kilo eshtu?","english":"How much is one kilo of these tomatoes?"},{"sentence":"Thumba jasti aagutte, komme maadi.","english":"That is too much, please reduce a little."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can shop at a market, ask prices, and bargain a little in Kannada."}}',
'{"items":[{"word":"eshtu","translation":"how much/how many","transliteration":"eshtu","pronunciation":"ESH-tu","example":"eshtu aagutte?"},{"word":"aagutte","translation":"it costs/it will be (price)","transliteration":"aagutte","pronunciation":"aa-GUT-te","example":"eshtu aagutte?"},{"word":"jasti","translation":"too much/excess","transliteration":"jasti","pronunciation":"JAS-ti","example":"jasti aagutte"},{"word":"komme maadi","translation":"reduce (please lower price)","transliteration":"komme maadi","pronunciation":"KOM-me MAA-di","example":"komme maadi"},{"word":"kodi","translation":"give (imperative)","transliteration":"kodi","pronunciation":"KO-di","example":"eradu kilo kodi"},{"word":"angadi","translation":"shop/store","transliteration":"angadi","pronunciation":"an-GA-di","example":"angadige hogi"}]}',
'{"title":"X eshtu aagutte? — How much does X cost? (shopping question)","pattern":"X eshtu aagutte? = How much does X cost? Eshtu = how much. Aagutte = it will cost/it is (price — 3rd person informal present). Ordering: X kodi (give me X). Response: Y rupai aagutte (it costs Y rupees). Negotiating: jasti aagutte (too much), komme maadi (please reduce), last price eshtu? (final price?), sari maadi (okay/fine).","explanation":"Shopping conversation in Kannada: (1) Looking: ee X eshtu? (how much is this X?). (2) Price given: X rupai (X rupees). (3) Negotiation: jasti aagutte (too much), komme maadi (please reduce). (4) Final: sari, kodi (okay, give me). Quantity: ondu kilo (one kilo), eradu (two), mooru (three). Weighing: timbarisi kodi (please weigh and give). Quality: channa ide? (is it good?). Freshness: hosa ide? (is it fresh? — hosa = new/fresh). Kannada bargaining phrases: last price eshtu? (what is your final price?), nimage loss aagutte (you will have a loss — sympathetic bargaining technique).","examples":[{"sentence":"Ee mango ondu kilo eshtu aagutte?","english":"How much will one kilo of these mangoes cost?"},{"sentence":"Sari, mooru kilo kodi — sari bedi eshtu?","english":"Okay, give me three kilos — how much without bargaining?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"eshtu means?","options":["how much/how many","how far","how old","how long"],"correctAnswer":"how much/how many"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"How much is one kilo of these tomatoes?","options":["Ee tomato ondu kilo eshtu?","Aa tomato ondu kilo eshtu?","Ee tomato eradu kilo eshtu?","Ee onion ondu kilo eshtu?"],"correctAnswer":"Ee tomato ondu kilo eshtu?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Thumba jasti aagutte, ___ maadi.","options":["komme","jasti","eshtu","kodi"],"correctAnswer":"komme"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That is too much, please reduce a little.","wordBankItems":["Thumba","jasti","aagutte",",","komme","maadi","."],"correctAnswer":"Thumba jasti aagutte , komme maadi ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"angadi means?","options":["shop/store","market","street","house"],"correctAnswer":"shop/store"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000009',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe your daily routine in Kannada","Use X gante Y maaduttini for time-based activities","Talk about morning, afternoon, evening routines"],"explanation":{"intro":"Daily routine vocabulary covers the activities of a typical day — from waking up to sleeping — using time expressions and activity verbs.","culturalNote":"Daily life in Bengaluru: traffic is a major factor — Bengaluru is consistently ranked among the world''s worst traffic cities. Many IT employees work night shifts (US/European timezones). Traditional Karnataka morning: ennune elupaata (getting up early), deva puja (morning prayer), filter kaapi, breakfast (tiffin — South Indian term for breakfast). Tiffin items: idli, dosa, upma, poha, kesari bath (sweet semolina). Lunch: saavali (noon), anna-sambar-palya-rasam (rice, sambar, dry vegetable, rasam). Evening: saanje (evening), tiffin again! (South Indians often have two tiffin meals — morning and evening). Night: raatri, anna-saaru (rice-rasam). Schools start at 9am. IT offices: flexible hours but typically 10am-7pm. Siesta (madhyaahna virama — afternoon rest) less common in urban areas now."},"examples":[{"sentence":"Naanu pratidinaa aidu gante elupaata.","english":"I get up every day at five o''clock."},{"sentence":"Raatri hattu gante malagikoLLuttini.","english":"At night I sleep at ten o''clock."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my daily routine with time expressions in Kannada."}}',
'{"items":[{"word":"elupaata","translation":"to wake up/get up","transliteration":"elupaata","pronunciation":"e-lu-PAA-ta","example":"aidu gante elupaata"},{"word":"pratidinaa","translation":"every day","transliteration":"pratidinaa","pronunciation":"pra-ti-di-NAA","example":"pratidinaa maaduttini"},{"word":"beLigge","translation":"morning","transliteration":"beLigge","pronunciation":"be-LIG-ge","example":"beLigge tiffin"},{"word":"malagikoLLuttini","translation":"I sleep","transliteration":"malagikoLLuttini","pronunciation":"ma-la-gi-KOL-lut-ti-ni","example":"raatri malagikoLLuttini"},{"word":"gante","translation":"o''clock/hour","transliteration":"gante","pronunciation":"GAN-te","example":"eshtu gante?"},{"word":"saanje","translation":"evening","transliteration":"saanje","pronunciation":"SAAN-je","example":"saanje aaruvaraige"}]}',
'{"title":"X gante Y maaduttini — At X o''clock I do Y (time + activity in Kannada)","pattern":"X gante Y maaduttini = At X o''clock I do Y (habitual). Gante = o''clock/hour (time marker). Maaduttini = I do (1st person habitual of maadu). Elupaata = wake up. Malagikoḷḷuttini = I sleep. Time words: beLigge (morning), madhyaahna (noon/afternoon), saanje (evening), raatri (night).","explanation":"Daily routine in Kannada: time expressions + habitual verb forms. Time: X gante = at X o''clock. X gante X nimisha = at X hours X minutes. Habitual verb endings: -uttini (I), -uttaare (they/formal), -uttaane (he/informal), -uttaaLe (she/informal). Elupaata (get up), snaaana maadu (take bath — snana maadu), tiffin tinnuttini (eat tiffin), school/office hoguttini (go to school/office — hoguttini = I go). Activities: Kannada uses maadu (do) for many activities — similar to Hindi karna. Yoga maaduttini (I do yoga), exercise maaduttini (I do exercise).","examples":[{"sentence":"Naanu beLigge aaru gante snaaana maaduttini.","english":"I take a bath at 6 in the morning."},{"sentence":"Saanje aidu gante office inda manege baruttini.","english":"In the evening I come home from office at five."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"gante means?","options":["o''clock/hour","minute","day","morning"],"correctAnswer":"o''clock/hour"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I get up every day at five o''clock.","options":["Naanu pratidinaa aidu gante elupaata.","Naanu pratidinaa aaru gante elupaata.","Naanu kadaakade aidu gante elupaata.","Naanu pratidinaa aidu gante malagikoLLuttini."],"correctAnswer":"Naanu pratidinaa aidu gante elupaata."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Raatri hattu gante ___ .","options":["malagikoLLuttini","elupaata","tinnuttini","hoguttini"],"correctAnswer":"malagikoLLuttini"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: In the evening I come home from office at five.","wordBankItems":["Saanje","aidu","gante","office","inda","manege","baruttini","."],"correctAnswer":"Saanje aidu gante office inda manege baruttini ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"pratidinaa means?","options":["every day","sometimes","today","morning"],"correctAnswer":"every day"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-00000000000a',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe the weather in Kannada","Use maleye baaruttide for it is raining","Name the four seasons and common weather conditions"],"explanation":{"intro":"Weather vocabulary is useful for daily conversation and planning. Karnataka has distinct weather patterns across its three main regions.","culturalNote":"Karnataka climate: three distinct zones. (1) Coastal Karnataka (Dakshina Kannada, Udupi): heavy monsoon — one of the wettest regions in India — Agumbe (Western Ghats) receives 7000mm+ rainfall annually — ''Cherrapunji of the South''. (2) Malnad (hill region — Western Ghats): coffee and pepper country — moderate climate. (3) Deccan plateau (Bengaluru, Mysuru, Hubli-Dharwad): drier — Bengaluru has a pleasant climate due to elevation (920m above sea level) — called the ''Air-conditioned City of India'' (historically — now warming due to urbanisation). Seasons: beeSa kaala (summer — April-June), maLe gaala (rainy/monsoon — June-October), sharada rutu (autumn — October-November), chaLi gaala (winter — November-February). Bengaluru famous for: unpredictable weather — ''four seasons in one day'' sometimes. Monsoon: Karnataka''s Southwest Monsoon arrives around June 1 on the coast."},"examples":[{"sentence":"Inja thumba beejave ide.","english":"Today it is very hot."},{"sentence":"Maleyge kaLLaLi.","english":"Let''s take an umbrella for the rain."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe the weather and seasons in Kannada."}}',
'{"items":[{"word":"maleye","translation":"rain","transliteration":"maleye","pronunciation":"ma-LE-ye","example":"maleye baaruttide"},{"word":"baarutte","translation":"it falls/rains (present)","transliteration":"baarutte","pronunciation":"BAA-rut-te","example":"maleye baaruttide"},{"word":"beejave","translation":"hot (weather)","transliteration":"beejave","pronunciation":"bee-JA-ve","example":"thumba beejave"},{"word":"chaLi","translation":"cold","transliteration":"chaLi","pronunciation":"CHA-li","example":"thumba chaLi"},{"word":"gaali","translation":"wind","transliteration":"gaali","pronunciation":"GAA-li","example":"gaali baaruttide"},{"word":"chaLi gaala","translation":"winter/cold season","transliteration":"chaLi gaala","pronunciation":"cha-LI GAA-la","example":"chaLi gaala bagge"}]}',
'{"title":"Maleye baaruttide — It is raining (weather description in Kannada)","pattern":"Maleye baaruttide = It is raining (lit. rain is falling). Baaruttide = it is coming/falling (3rd neuter present continuous). Weather patterns: maleye baaruttide (it is raining), beejave ide (it is hot), chaLi ide (it is cold), gaali baaruttide (wind is blowing). Today: inja X ide (today it is X). Will be: naale X irutte (tomorrow it will be X).","explanation":"Weather verbs in Kannada: baarutte/baaruttide (falls/rains — used for rain, wind, snow). Ide = is (present tense 3rd person neuter — used for states). Agi baaruttide = sun is shining (agi = fire/sun). Mattu (clouds) — mattaayt ide (it has clouded over). Fog: manju (morning mist/fog) — Coorg manju is famous. Temperature: eshtu degree? (how many degrees?). Weather forecast: naale X aagutte? (will it be X tomorrow?). Seasons: beeSa kaala (summer), maLe gaala (rainy), sharada rutu (autumn), chaLi gaala (winter). Karnataka monsoon (nairutya monsoon) is crucial for agriculture.","examples":[{"sentence":"Naale maleye baaruttada endaare.","english":"They say it will rain tomorrow."},{"sentence":"Bengalurualli beejave kam irutte, aadare mattaayt irutte.","english":"In Bengaluru it is less hot, but it remains cloudy."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"maleye means?","options":["rain","wind","cloud","thunder"],"correctAnswer":"rain"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Today it is very hot.","options":["Inja thumba beejave ide.","Inja thumba chaLi ide.","Naale thumba beejave ide.","Inja thakku beejave ide."],"correctAnswer":"Inja thumba beejave ide."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Maleye ___ , kaLLaLi beeku.","options":["baaruttide","baruttide","barutte","baaruve"],"correctAnswer":"baaruttide"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Let''s take an umbrella for the rain.","wordBankItems":["Maleyge","kaLLaLi","."],"correctAnswer":"Maleyge kaLLaLi ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"chaLi means?","options":["cold","hot","cool","warm"],"correctAnswer":"cold"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('22000000-0000-0000-0000-000000000001','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l001',1,'Greetings and Basic Introductions','Namaskara and basic introductions','PUBLISHED'),
('22000000-0000-0000-0000-000000000002','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l002',2,'Numbers 1-20','Ondu to ippattu — counting in Kannada','PUBLISHED'),
('22000000-0000-0000-0000-000000000003','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l003',3,'Family Members','Kannada family vocabulary','PUBLISHED'),
('22000000-0000-0000-0000-000000000004','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l004',4,'Colors and Basic Adjectives','Colors and descriptive adjectives','PUBLISHED'),
('22000000-0000-0000-0000-000000000005','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l005',5,'Days of the Week and Months','Vaara names and calendar expressions','PUBLISHED'),
('22000000-0000-0000-0000-000000000006','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l006',6,'Food and Drinks','Karnataka food vocabulary and ordering','PUBLISHED'),
('22000000-0000-0000-0000-000000000007','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l007',7,'Asking for Directions','Navigation vocabulary in Kannada','PUBLISHED'),
('22000000-0000-0000-0000-000000000008','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l008',8,'At the Market — Shopping','Market shopping and bargaining','PUBLISHED'),
('22000000-0000-0000-0000-000000000009','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l009',9,'Daily Routine','Daily routine with time expressions','PUBLISHED'),
('22000000-0000-0000-0000-00000000000a','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l010',10,'Weather and Seasons','Weather vocabulary and Karnataka climate','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000001' WHERE stable_ref = 'kn-a1-u01-l001' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000002' WHERE stable_ref = 'kn-a1-u01-l002' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000003' WHERE stable_ref = 'kn-a1-u01-l003' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000004' WHERE stable_ref = 'kn-a1-u01-l004' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000005' WHERE stable_ref = 'kn-a1-u01-l005' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000006' WHERE stable_ref = 'kn-a1-u01-l006' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000007' WHERE stable_ref = 'kn-a1-u01-l007' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000008' WHERE stable_ref = 'kn-a1-u01-l008' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000009' WHERE stable_ref = 'kn-a1-u01-l009' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-00000000000a' WHERE stable_ref = 'kn-a1-u01-l010' AND lesson_id IS NULL;
