-- V121: Kannada A1 lessons 11-20
-- Hex: 11=0xb, 12=0xc, 13=0xd, 14=0xe, 15=0xf, 16=0x10, 17=0x11, 18=0x12, 19=0x13, 20=0x14
-- ALL CONTENT IN ENGLISH / ROMAN TRANSLITERATION ONLY

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('11000000-0000-0000-0000-00000000000b','kn-a1-l011','Body Parts and Health','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-00000000000c','kn-a1-l012','Clothing and Appearance','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-00000000000d','kn-a1-l013','At Home — Rooms and Furniture','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-00000000000e','kn-a1-l014','Transport and Travel','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-00000000000f','kn-a1-l015','Time — Telling the Time','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000010','kn-a1-l016','Animals and Nature','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000011','kn-a1-l017','Occupations and Work','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000012','kn-a1-l018','Likes and Dislikes','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000013','kn-a1-l019','Describing Places','language','kn','A1','APPROVED','PUBLISHED',1,1),
('11000000-0000-0000-0000-000000000014','kn-a1-l020','Simple Questions and Answers','language','kn','A1','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-00000000000b',1,'APPROVED','PUBLISHED',
'{"objectives":["Name body parts in Kannada","Say maikke novu ide for describing pain","Ask about health and symptoms"],"explanation":{"intro":"Body part vocabulary is essential for talking about health, describing pain, and visiting the doctor. Knowing these words helps in medical situations and daily conversation.","culturalNote":"Health in Karnataka: major hospitals in Bengaluru include Manipal Hospital, Narayana Health, Apollo, Victoria Hospital (government — oldest in Bengaluru, 1900). Ayurvedic tradition: Karnataka has strong Ayurveda roots — the Ayurvedic college in Mysuru is one of the oldest. Traditional remedies: hasi arisina haalu (raw turmeric milk), neeru (water) with jeera (cumin seeds) for digestion. Body-related expressions: kai (hand) used in many idioms — kai kotta seva (service given by hand = personal service), kai haakodilla (won''t give a hand/help). Yoga: many famous yoga teachers from Karnataka — B.K.S. Iyengar (Bellary, Karnataka — founder of Iyengar Yoga), Pattabhi Jois (Mysuru — founder of Ashtanga Yoga)."},"examples":[{"sentence":"Nanna talaige novu ide.","english":"I have a headache (my head has pain)."},{"sentence":"Nanna kai novu ide, doctaralli hogabeku.","english":"My hand is paining, I need to go to the doctor."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name body parts and describe basic health symptoms in Kannada."}}',
'{"items":[{"word":"tala","translation":"head","transliteration":"tala","pronunciation":"TA-la","example":"nanna tala"},{"word":"kai","translation":"hand/arm","transliteration":"kai","pronunciation":"kai","example":"nanna kai"},{"word":"kaalu","translation":"leg/foot","transliteration":"kaalu","pronunciation":"KAA-lu","example":"nanna kaalu"},{"word":"kannu","translation":"eye","transliteration":"kannu","pronunciation":"KAN-nu","example":"nanna kannu"},{"word":"novu","translation":"pain/ache","transliteration":"novu","pronunciation":"NO-vu","example":"novu ide"},{"word":"maikke","translation":"body","transliteration":"maikke","pronunciation":"MAI-kke","example":"maikke novu"}]}',
'{"title":"Nanna X ge novu ide — My X is paining (body pain expression in Kannada)","pattern":"Nanna X ge novu ide = My X has pain / my X is aching. Nanna = my. X ge = to/in X (dative -ge suffix). Novu = pain. Ide = is (present 3rd neuter). Asking: nimage elli novu ide? (where do you have pain? — formal). Common: talaige novu ide (headache), haaleige novu ide (toothache — haalu = tooth), kaige novu ide (hand pain).","explanation":"Pain expression in Kannada: nanna X ge novu ide. The body part takes -ge (dative suffix — marks location of pain). Tala → talaige (to/in the head). Kai → kaige (to/in the hand). Kaalu → kaalige (to/in the leg). Kannu → kannige (to/in the eye). Asking about symptoms: yaava tinisike agutte? (what are you feeling?). Temperature: jivaradalli agutte (fever is there — jivarada = fever). Novu grade: komme novu (mild pain), thumba novu (a lot of pain), beejuve novu (burning pain).","examples":[{"sentence":"Nanna kaalige thumba novu ide.","english":"My leg has a lot of pain."},{"sentence":"Nimage elli novu ide?","english":"Where do you have pain? (formal)"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"novu means?","options":["pain/ache","fever","cold","headache"],"correctAnswer":"pain/ache"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have a headache (my head has pain).","options":["Nanna talaige novu ide.","Nanna kaige novu ide.","Nanna kaalige novu ide.","Nanna kannige novu ide."],"correctAnswer":"Nanna talaige novu ide."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Nanna kai novu ide, doctaralli ___ .","options":["hogabeku","baruttini","iddini","maaduttini"],"correctAnswer":"hogabeku"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Where do you have pain? (formal)","wordBankItems":["Nimage","elli","novu","ide","?"],"correctAnswer":"Nimage elli novu ide ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"kannu means?","options":["eye","ear","nose","mouth"],"correctAnswer":"eye"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-00000000000c',1,'APPROVED','PUBLISHED',
'{"objectives":["Name clothing items in Kannada","Use X haaki konde for wearing clothes","Describe what someone is wearing"],"explanation":{"intro":"Clothing vocabulary covers common garments and how to talk about what people are wearing in Kannada.","culturalNote":"Clothing in Karnataka: traditional dress — men: pancha (dhoti — white cotton cloth wrapped around waist and legs), kurta (loose shirt), angavastra (upper garment — shoulder cloth). Women: saree (saree — Karnataka style — typically Mysuru silk or Ilkal cotton), salwara kameez (salwar kameez), davani (half saree — for young women). Modern urban wear: jeans, t-shirt, formal shirts very common in Bengaluru''s IT sector. Festivals: people dress traditionally for Dasara, Ugaadi, Diwali. Silk: Mysuru silk sarees are Karnataka''s most famous textile — gold zari border, lightweight, lustrous. Khadi: hand-spun cotton — worn on Gandhi Jayanti (Oct 2) as tribute. Footwear: chappali (sandals/slippers — most common), shoes (shoes)."},"examples":[{"sentence":"Avaru kempu saree haaki konde iddaare.","english":"She is wearing a red saree."},{"sentence":"Naanu inja neeli shirt haaki konde iddini.","english":"I am wearing a blue shirt today."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name clothing items and describe what people are wearing in Kannada."}}',
'{"items":[{"word":"shirt","translation":"shirt","transliteration":"shirt","pronunciation":"shurt","example":"neeli shirt"},{"word":"saree","translation":"saree","transliteration":"saree","pronunciation":"SAA-ree","example":"Mysuru saree"},{"word":"chappali","translation":"sandals/slippers","transliteration":"chappali","pronunciation":"CHAP-pa-li","example":"chappali haaki"},{"word":"haaki konde","translation":"wearing (present continuous)","transliteration":"haaki konde","pronunciation":"HAA-ki KON-de","example":"saree haaki konde iddaare"},{"word":"batte","translation":"clothes/garment","transliteration":"batte","pronunciation":"BAT-te","example":"hosa batte"},{"word":"chali","translation":"cold/cool (used for clothes too)","transliteration":"chali","pronunciation":"CHA-li","example":"chali batte"}]}',
'{"title":"X haaki konde iddaare — He/she is wearing X (continuous wearing in Kannada)","pattern":"X haaki konde iddaare = He/she is wearing X (formal 3rd person). Haaki = having put on (from haaku = to put on/wear). Konde = having done. Iddaare = is/are (formal 3rd person continuous). First person: haaki konde iddini (I am wearing). Asking: neevu enu haaki konde iddiri? (what are you wearing? — formal).","explanation":"Wearing in Kannada: haaku (to wear/put on) is the verb. Present continuous wearing: haaki konde + iddini/iddaare/iddaane. Haaki = having put on (verbal noun/participle). Konde iddini = I am (staying in a state of). Together: haaki konde iddini = I am wearing (lit. having put on, I am staying). Describing: X bana Y haaki konde iddaare (he/she is wearing Y of colour X). Colors with clothes: kempu saree (red saree), neeli shirt (blue shirt), bili batte (white clothes). New clothes: hosa batte haaki (wearing new clothes). Traditional clothes: pancha haaki konde iddaare (he is wearing a dhoti).","examples":[{"sentence":"Avanu hosa neeli shirt haaki konde iddaane.","english":"He is wearing a new blue shirt."},{"sentence":"Nanna akka kempu davani haaki konde iddaaLe.","english":"My elder sister is wearing a red davani."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"chappali means?","options":["sandals/slippers","shirt","saree","shoes"],"correctAnswer":"sandals/slippers"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"She is wearing a red saree.","options":["Avaru kempu saree haaki konde iddaare.","Avaru neeli saree haaki konde iddaare.","Avalu kempu saree haaki konde iddaaLe.","Avaru kempu shirt haaki konde iddaare."],"correctAnswer":"Avaru kempu saree haaki konde iddaare."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Naanu inja neeli shirt haaki konde ___ .","options":["iddini","iddaare","iddaane","iddaaLe"],"correctAnswer":"iddini"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: He is wearing a new blue shirt.","wordBankItems":["Avanu","hosa","neeli","shirt","haaki","konde","iddaane","."],"correctAnswer":"Avanu hosa neeli shirt haaki konde iddaane ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"batte means?","options":["clothes/garment","colour","market","cloth shop"],"correctAnswer":"clothes/garment"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-00000000000d',1,'APPROVED','PUBLISHED',
'{"objectives":["Name rooms and furniture in Kannada","Use maneyalli X ide for describing home","Talk about your home and living space"],"explanation":{"intro":"Home vocabulary covers rooms, furniture, and how to describe where things are in your house in Kannada.","culturalNote":"Homes in Karnataka: traditional Karnataka home — hattikoppala mane (traditional house with central courtyard — called aangan in North India, madilu in Kannada). The central courtyard (madhya prabha) lets in light and air. Tulasi katte (elevated tulasi plant platform at entrance — every traditional Hindu home). Modern apartments: Bengaluru has exploded with high-rise apartments — BHK system (1BHK, 2BHK, 3BHK). Common rooms: ootada kode (dining room — ootada = eating), malagikoLLuva kode (bedroom — malagikoLLuva = sleeping), adugeyakode/ashana ghe (kitchen — cooking room), snaanadha mane (bathroom — bath house). Living room: hall (English word used universally). Furniture: meja (table — from Portuguese mesa via Goa), kurchi (chair — from Hindi/Urdu kursi), cot (cot/bed)."},"examples":[{"sentence":"Nanna maneya hall thumba dodda ide.","english":"The hall of my house is very big."},{"sentence":"Adugeyakodeyalli meja haagu kurchi ide.","english":"In the kitchen there is a table and chair."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name rooms and furniture and describe my home in Kannada."}}',
'{"items":[{"word":"mane","translation":"house/home","transliteration":"mane","pronunciation":"MA-ne","example":"nanna mane"},{"word":"kode","translation":"room","transliteration":"kode","pronunciation":"KO-de","example":"malagikoLLuva kode"},{"word":"meja","translation":"table","transliteration":"meja","pronunciation":"ME-ja","example":"meja meele"},{"word":"kurchi","translation":"chair","transliteration":"kurchi","pronunciation":"KUR-chi","example":"kurchi meele kuu"},{"word":"adugeyakode","translation":"kitchen","transliteration":"adugeyakode","pronunciation":"a-du-ge-ya-KO-de","example":"adugeyakodeyalli"},{"word":"meele","translation":"on/above (location)","transliteration":"meele","pronunciation":"MEE-le","example":"meja meele ide"}]}',
'{"title":"X maneyalli ide — X is in the house (location with -alli suffix)","pattern":"X maneyalli ide = X is in the house. -alli = in/at/inside (locative suffix — attaches to nouns). Mane + alli = maneyalli (in the house). Kode + alli = kodeyalli (in the room). Meele = on top of/above. KeLage = below/under. Hattira = near. Asking: X elli ide? (where is X?).","explanation":"Location in Kannada: -alli suffix marks location (in, at, inside). Mane → maneyalli (in the house). Kodeyalli (in the room). Bengalurualli (in Bengaluru — same suffix for cities). Elli = where (location question). Meele (on top), keLage (below/under), hattira (near), doora (far), akka-pakka (around/nearby). There is/are: X ide (X is — singular/informal), X idhe (X is — slightly formal). There is no: X illa (X is not). Furniture locations: meja meele books ide (books are on the table), kode alli meja ide (there is a table in the room).","examples":[{"sentence":"Nanna kodeyalli eradu meja ide.","english":"In my room there are two tables."},{"sentence":"Kitabi meja meele ide.","english":"The book is on the table."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"mane means?","options":["house/home","room","kitchen","table"],"correctAnswer":"house/home"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The hall of my house is very big.","options":["Nanna maneya hall thumba dodda ide.","Nanna maneya kode thumba dodda ide.","Nanna maneya hall thakku dodda ide.","Nimma maneya hall thumba dodda ide."],"correctAnswer":"Nanna maneya hall thumba dodda ide."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Kitabi meja ___ ide.","options":["meele","keLage","alli","hattira"],"correctAnswer":"meele"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: In my room there are two tables.","wordBankItems":["Nanna","kodeyalli","eradu","meja","ide","."],"correctAnswer":"Nanna kodeyalli eradu meja ide ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"-alli suffix means?","options":["in/at/inside","on top of","near","below"],"correctAnswer":"in/at/inside"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-00000000000e',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about transport in Kannada","Use X alli hoguttini for going by transport","Ask about buses, autos, and trains"],"explanation":{"intro":"Transport vocabulary covers the vehicles and services used to get around in Karnataka — from city buses to auto-rickshaws and long-distance trains.","culturalNote":"Transport in Karnataka: BMTC (Bengaluru Metropolitan Transport Corporation — city buses — 6000+ buses — Volvo AC buses for longer routes). KSRTC (Karnataka State Road Transport Corporation — intercity buses — connects all of Karnataka). Namma Metro (Blue Line, Green Line — rapidly expanding). Auto-rickshaw (auto — three-wheeler — metered or negotiated fare — essential for last-mile). Ola and Uber (app-based cabs). KSR Railway Station (Krantiveera Sangolli Rayanna Railway Station — Bengaluru City station — main intercity rail hub). SBC = station code for Bengaluru City. Rapido (bike taxi — popular in Bengaluru for traffic bypass). Cycle (bicycle) still used in smaller towns. Bullock cart (ettina gaaLi — ox cart) still seen in rural Karnataka."},"examples":[{"sentence":"Naanu bus alli office ge hoguttini.","english":"I go to the office by bus."},{"sentence":"Auto baruttade — namma hogona.","english":"The auto has come — let''s go."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about modes of transport and getting around in Kannada."}}',
'{"items":[{"word":"bus","translation":"bus","transliteration":"bus","pronunciation":"bus","example":"bus alli hogi"},{"word":"auto","translation":"auto-rickshaw","transliteration":"auto","pronunciation":"AW-to","example":"auto haidi"},{"word":"train","translation":"train","transliteration":"train","pronunciation":"treyn","example":"train station"},{"word":"nadale","translation":"to walk/walking","transliteration":"nadale","pronunciation":"NA-da-le","example":"nadeyuttini"},{"word":"alli","translation":"in/by (instrumental — by means of)","transliteration":"alli","pronunciation":"AL-li","example":"bus alli"},{"word":"station","translation":"station","transliteration":"station","pronunciation":"STAY-shun","example":"railway station"}]}',
'{"title":"X alli hoguttini — I go by X (instrumental alli for transport)","pattern":"X alli hoguttini = I go by X (present habitual). Alli = in/by (locative suffix also used instrumentally for transport). Bus alli (by bus), auto alli (by auto), train alli (by train), car alli (by car), metro alli (by metro). Hoguttini = I go (habitual present). Baruttini = I come. Asking: neevu haege hoguttiri? (how do you go? — formal).","explanation":"Transport in Kannada: -alli suffix serves double duty — location (in the room = kodeyalli) and instrument (by bus = bus alli). Hoguttini (I go — habitual), baruttini (I come), hogi (go — imperative), baa (come — imperative informal), baanni (come — formal). Common phrases: auto haidi (catch/hail an auto — haidi = catch), bus miss agutte (the bus will be missed — miss = miss, agutte = will happen), eshtu duration aagutte? (how long will it take?). Journey: prayaana (journey/trip), tiket (ticket), stoppu (bus stop).","examples":[{"sentence":"Metro alli hoguva aa bus alli hoguva?","english":"Shall we go by metro or by bus?"},{"sentence":"Railway station ge auto alli hogi.","english":"Go to the railway station by auto."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"alli (after transport) means?","options":["by/in (instrumental)","to","from","near"],"correctAnswer":"by/in (instrumental)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I go to the office by bus.","options":["Naanu bus alli office ge hoguttini.","Naanu auto alli office ge hoguttini.","Naanu bus alli manege hoguttini.","Naanu bus alli school ge hoguttini."],"correctAnswer":"Naanu bus alli office ge hoguttini."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Railway station ge auto ___ hogi.","options":["alli","ge","inda","keege"],"correctAnswer":"alli"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Shall we go by metro or by bus?","wordBankItems":["Metro","alli","hoguva","aa","bus","alli","hoguva","?"],"correctAnswer":"Metro alli hoguva aa bus alli hoguva ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"nadale means?","options":["to walk/walking","to run","to drive","to travel"],"correctAnswer":"to walk/walking"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-00000000000f',1,'APPROVED','PUBLISHED',
'{"objectives":["Tell the time in Kannada","Use X gante aagutte for it is X o''clock","Ask what time it is"],"explanation":{"intro":"Telling the time is essential for daily scheduling, catching buses, and making appointments. Kannada uses gante (hour/o''clock) as the time marker.","culturalNote":"Time in Karnataka: IST (Indian Standard Time — UTC+5:30 — all of India uses one time zone despite its vast size). 12-hour clock common in speech (morning/evening context makes it clear). 24-hour format used in official/transport contexts. Punctuality: business and IT meetings tend to run on time in Bengaluru. Traditional events (weddings, functions) commonly start late — muhurta time (auspicious time set by astrologer) must be observed. Karnataka government offices: 10am-5:30pm. Banks: 10am-4pm (Monday-Friday), 10am-1pm (Saturday). Schools: typically 9am-4pm. Auto-rickshaw rush hour: 8-10am and 5:30-7:30pm — fares surge and availability drops. Nimisha (minute), arda gante (half hour — arda = half), kaalu gante (quarter hour — kaalu = quarter/leg)."},"examples":[{"sentence":"Eshtu gante aagutte?","english":"What time is it? (How many hours is it becoming?)"},{"sentence":"Aidu gante aagutte.","english":"It is five o''clock."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can ask and tell the time in Kannada."}}',
'{"items":[{"word":"gante","translation":"hour/o''clock","transliteration":"gante","pronunciation":"GAN-te","example":"aidu gante"},{"word":"nimisha","translation":"minute","transliteration":"nimisha","pronunciation":"ni-MI-sha","example":"hattu nimisha"},{"word":"arda","translation":"half","transliteration":"arda","pronunciation":"AR-da","example":"arda gante"},{"word":"aagutte","translation":"it is becoming/it is (present)","transliteration":"aagutte","pronunciation":"aa-GUT-te","example":"aidu gante aagutte"},{"word":"beLigge","translation":"morning (AM)","transliteration":"beLigge","pronunciation":"be-LIG-ge","example":"beLigge aaru gante"},{"word":"raatri","translation":"night (PM)","transliteration":"raatri","pronunciation":"RAATRI","example":"raatri hattu gante"}]}',
'{"title":"X gante aagutte — It is X o''clock (telling time in Kannada)","pattern":"X gante aagutte = It is X o''clock (lit. X hours it is becoming). Eshtu gante aagutte? = What time is it? (lit. how many hours is it becoming?). Minutes: X gante Y nimisha aagutte (it is X hours Y minutes). Half hour: X gante arda aagutte (it is X thirty). Quarter: X gante kaalu aagutte (it is X fifteen).","explanation":"Time in Kannada: aagutte (it is becoming) is used for time. Gante = hour/o''clock. Eshtu = how many. Time expressions: beLigge (morning/AM), madhyaahna (noon), havaLe (afternoon), saanje (evening), raatri (night). Examples: beLigge aaru gante (6am), madhyaahna ondu gante (1pm), saanje aidu gante (5pm), raatri hattu gante (10pm). Minutes past: X gante Y nimisha (X hours Y minutes). Quarter: X gante kaalu nimisha (15 mins after X — kaalu = quarter). Half: X gante arda (half past X). Approximate: saajege hoguttini (I will go in the evening).","examples":[{"sentence":"Eshtu gante aagutte? — Ondu gante aagutte.","english":"What time is it? — It is one o''clock."},{"sentence":"Raatri aaru gante inda beLigge aaru gante tanka office bidu.","english":"The office is closed from 6pm to 6am."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"eshtu gante aagutte? means?","options":["what time is it?","what day is it?","how many hours?","when will it be?"],"correctAnswer":"what time is it?"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"It is five o''clock.","options":["Aidu gante aagutte.","Aaru gante aagutte.","Hattu gante aagutte.","Ondu gante aagutte."],"correctAnswer":"Aidu gante aagutte."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Eshtu gante ___? — Eradu gante aagutte.","options":["aagutte","aayitu","aagitta","aguve"],"correctAnswer":"aagutte"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: What time is it? (asking time in Kannada)","wordBankItems":["Eshtu","gante","aagutte","?"],"correctAnswer":"Eshtu gante aagutte ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"nimisha means?","options":["minute","second","hour","half"],"correctAnswer":"minute"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000010',1,'APPROVED','PUBLISHED',
'{"objectives":["Name common animals in Kannada","Use X naayi/bekku/hasu for pets","Describe animals with basic adjectives"],"explanation":{"intro":"Animal vocabulary covers pets, farm animals, and wildlife found in and around Karnataka — one of India''s most biodiverse states.","culturalNote":"Animals in Karnataka: Karnataka is home to extraordinary wildlife. Nagarhole and Bandipur Tiger Reserve (part of the Nilgiri Biosphere Reserve — largest protected forest in South Asia). Elephants: Karnataka has 6000+ wild elephants — the Mysuru Dasara procession features magnificently decorated temple elephants (gajavaira elephants). Wildlife: tiger (huli), leopard (chitraka), sloth bear (karadi), gaur (kaadu erumai), Indian wild dog (dhole), peacock (national bird — morilu). Coorg (Kodagu): coffee estates with wild elephants crossing roads! Birdwatching: Western Ghats = one of the world''s biodiversity hotspots. Pets: naayi (dog — very common), bekku (cat), haalu kai (cattle/cow). Sacred cow (hasu/haavu = sacred cow/cow in Kannada — gomata). Karnataka''s milk cooperative: KMF (Karnataka Milk Federation — Nandini brand)."},"examples":[{"sentence":"Nanna maneyalli ondu naayi ide.","english":"In my house there is one dog."},{"sentence":"Aa dodda huli Bandipur jungle alli ide.","english":"That big tiger is in the Bandipur jungle."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name common animals and describe them in Kannada."}}',
'{"items":[{"word":"naayi","translation":"dog","transliteration":"naayi","pronunciation":"NAA-yi","example":"naayi kore"},{"word":"bekku","translation":"cat","transliteration":"bekku","pronunciation":"BEK-ku","example":"bekku hogu"},{"word":"haasu","translation":"cow","transliteration":"haasu","pronunciation":"HAA-su","example":"haasu haalu"},{"word":"huli","translation":"tiger","transliteration":"huli","pronunciation":"HU-li","example":"huli hoppalu"},{"word":"gajavaira","translation":"elephant","transliteration":"gajavaira","pronunciation":"ga-ja-VAI-ra","example":"Dasara gajavaira"},{"word":"hakki","translation":"bird","transliteration":"hakki","pronunciation":"HAK-ki","example":"hakki haadutte"}]}',
'{"title":"X nanna maneyalli ide — X is in my house (animal location with -alli)","pattern":"Nanna maneyalli X ide = There is X in my house. X alli Y ide = There is Y in X (place). Describing animals: X thumba dodda ide (X is very big). X alli Y kaaNabahudu (Y can be seen in X). Questions: X eliide? (where is X?), X eshtu ide? (how many X are there?).","explanation":"Animals in Kannada: naayi (dog), bekku (cat), haasu/hsu (cow), kudi (calf), katte (donkey), kudure (horse), huli (tiger), simha (lion), aane/gajavaira (elephant), mela (fish — meenu also), hakki (bird), morilu (peacock), giLi (parrot). Describing animals: animal + adjective: dodda naayi (big dog), chikka bekku (small cat), kempu hakki (red bird). Actions: kore haakuttade (dog barks — kore haakuttade = barks), haadutte (sings/chirps — bird), hoLeyutte (jumps). Habitats: jungle alli (in the jungle), neeru alli (in the water), maneyalli (in the house).","examples":[{"sentence":"Nanna bekku thumba chikka haagu bili bana ide.","english":"My cat is very small and white coloured."},{"sentence":"Morilu Bandipur jungle alli kaaNabahudu.","english":"Peacocks can be seen in the Bandipur jungle."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"huli means?","options":["tiger","elephant","lion","leopard"],"correctAnswer":"tiger"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In my house there is one dog.","options":["Nanna maneyalli ondu naayi ide.","Nanna maneyalli eradu naayi ide.","Nanna maneyalli ondu bekku ide.","Nimma maneyalli ondu naayi ide."],"correctAnswer":"Nanna maneyalli ondu naayi ide."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Nanna bekku thumba chikka haagu ___ bana ide.","options":["bili","kempu","neeli","hasi"],"correctAnswer":"bili"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That big tiger is in the Bandipur jungle.","wordBankItems":["Aa","dodda","huli","Bandipur","jungle","alli","ide","."],"correctAnswer":"Aa dodda huli Bandipur jungle alli ide ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"hakki means?","options":["bird","fish","insect","animal"],"correctAnswer":"bird"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000011',1,'APPROVED','PUBLISHED',
'{"objectives":["Name occupations in Kannada","Use naanu X haagu kaela maaduttini for job descriptions","Ask what someone does for work"],"explanation":{"intro":"Occupation vocabulary covers common jobs and how to discuss work in Kannada — essential for introductions and daily conversation.","culturalNote":"Occupations in Karnataka: IT sector dominates Bengaluru — software engineer (software engineer), developer (developer), manager (manager) all used in English. Traditional occupations: kaigarike (handicraft maker), kumbhara (potter — clay pots), aachari (carpenter/craftsman — wood carving famous in Karnataka), devanga (weaver — famous Ilkal and Dharwad sarees). Agriculture: Karnataka''s major crops — ragi (finger millet), jowar (sorghum), cotton, coffee, areca nut (adike). Professions: doctaru (doctor), shikshaka/adhyaapaka (teacher — shikshaka from Sanskrit), advocate (lawyer), police (police). Government jobs (sarkari kaela) are highly valued — job security and pension. IT jobs (IT kaela) = high salaries but long hours. Farmers (raita — common and respected term in Karnataka)."},"examples":[{"sentence":"Naanu software engineer haagu Bengalurualli kaela maaduttini.","english":"I am a software engineer and work in Bengaluru."},{"sentence":"Neevu yaava kaela maaduttiri?","english":"What work do you do? (formal)"}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can name occupations and talk about work in Kannada."}}',
'{"items":[{"word":"kaela","translation":"work/job","transliteration":"kaela","pronunciation":"KAE-la","example":"kaela maadu"},{"word":"maaduttini","translation":"I do (habitual present 1st person)","transliteration":"maaduttini","pronunciation":"maa-DUT-ti-ni","example":"kaela maaduttini"},{"word":"doctaru","translation":"doctor","transliteration":"doctaru","pronunciation":"DOC-ta-ru","example":"doctaru kaela"},{"word":"shikshaka","translation":"teacher","transliteration":"shikshaka","pronunciation":"SHIK-sha-ka","example":"shikshaka iddaare"},{"word":"raita","translation":"farmer","transliteration":"raita","pronunciation":"RAI-ta","example":"raita kaela"},{"word":"yaava","translation":"which/what (pronoun)","transliteration":"yaava","pronunciation":"YAA-va","example":"yaava kaela?"}]}',
'{"title":"Naanu X, Y alli kaela maaduttini — I am X, I work at Y (job description)","pattern":"Naanu X (occupation) = I am X (occupation). Naanu Y alli kaela maaduttini = I work at Y. Combined: Naanu X, Y alli kaela maaduttini = I am X, I work at Y. Asking: neevu yaava kaela maaduttiri? (what work do you do? — formal). Yaava = which/what. Kaela = work. Maaduttiri = you do (formal 2nd person habitual).","explanation":"Work descriptions in Kannada: naanu X (I am X — occupation). Kaela maadu (to do work — maadu = to do, kaela = work). Workplace: X alli kaela maadu (work at X — company/hospital/school alli). Company name + alli: Infosys alli (at Infosys), school alli (at school), aspatale alli (at the hospital). Since when: X varsha inda (for X years). Salary: saambhavane (salary — formal), salary (English used commonly). Working hours: shift (shift — IT companies), overtime (overtime). Part-time vs full-time: ardha kaalada (part-time), poorna kaalada (full-time).","examples":[{"sentence":"Nanna appa raita, avaruige ragi bele kaela maaduttaare.","english":"My father is a farmer, he does ragi cultivation."},{"sentence":"Naanu ondu IT company alli kaela maaduttini.","english":"I work at an IT company."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"kaela means?","options":["work/job","office","company","salary"],"correctAnswer":"work/job"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"What work do you do? (formal)","options":["Neevu yaava kaela maaduttiri?","Neenu yaava kaela maaduttiya?","Neevu elli kaela maaduttiri?","Avaru yaava kaela maaduttaare?"],"correctAnswer":"Neevu yaava kaela maaduttiri?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Naanu software engineer haagu Bengalurualli kaela ___ .","options":["maaduttini","maaduttaare","maaduttaane","maaduttaaLe"],"correctAnswer":"maaduttini"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I work at an IT company.","wordBankItems":["Naanu","ondu","IT","company","alli","kaela","maaduttini","."],"correctAnswer":"Naanu ondu IT company alli kaela maaduttini ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"shikshaka means?","options":["teacher","student","principal","professor"],"correctAnswer":"teacher"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000012',1,'APPROVED','PUBLISHED',
'{"objectives":["Express likes and dislikes in Kannada","Use naakke X ishtavagutte for liking","Say what you enjoy and what you dislike"],"explanation":{"intro":"Expressing likes and dislikes is fundamental for conversation. In Kannada the key construction uses ishtavagutte (is pleasing/liked) for expressing liking.","culturalNote":"Likes and dislikes in Karnataka: passions of Kannadigas include Kannada cinema (Sandalwood — Bengaluru is the Kannada film industry hub), cricket (especially Bengaluru''s Royal Challengers Bangalore — RCB — in IPL), filter coffee, Mysuru silk, Karnataka Rajyotsava (state formation day Nov 1 — birthday of the state — celebrated with great pride). Music: Carnatic classical music (South Indian classical — Tyagaraja, Muthuswami Dikshitar); folk music (janapada sangeetha — haadu = sing, hakki haaDutte = bird sings). Dislike: beed (dislike/don''t want — ida beeda = I don''t want this). Common question: nimage yaavu kaela ishta? (what work do you like? — casual conversation)."},"examples":[{"sentence":"Naakke Kannada cinema thumba ishtavagutte.","english":"I like Kannada cinema very much."},{"sentence":"Naakke bisi bele bath thumba ishtavagutte.","english":"I like bisi bele bath very much."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can express what I like and dislike in Kannada."}}',
'{"items":[{"word":"ishtavagutte","translation":"is liked/pleasing (I like — dative construction)","transliteration":"ishtavagutte","pronunciation":"ish-ta-va-GUT-te","example":"naakke ishtavagutte"},{"word":"ishtavagolla","translation":"is not liked (I don''t like)","transliteration":"ishtavagolla","pronunciation":"ish-ta-va-GOL-la","example":"naakke ishtavagolla"},{"word":"naakke","translation":"to me (dative — I like uses naakke)","transliteration":"naakke","pronunciation":"NAAK-ke","example":"naakke ishta"},{"word":"ishta","translation":"liked/favourite (adjective)","transliteration":"ishta","pronunciation":"ISH-ta","example":"ishta kaela"},{"word":"beeda","translation":"don''t want / dislike","transliteration":"beeda","pronunciation":"BEE-da","example":"naakke beeda"},{"word":"chennagide","translation":"it is good/nice","transliteration":"chennagide","pronunciation":"chen-na-GI-de","example":"thumba chennagide"}]}',
'{"title":"Naakke X ishtavagutte — I like X (dative liking construction in Kannada)","pattern":"Naakke X ishtavagutte = I like X (lit. to me X is pleasing). Naakke = to me (dative of naanu — I). Ishtavagutte = is pleasing/liked (3rd person neuter present). Disliking: naakke X ishtavagolla (I don''t like X). More casual: naakke X ishta (X is my favourite/I like X — shorter form). Intensify: thumba ishtavagutte (I like very much).","explanation":"Liking in Kannada: dative construction — naakke (to me) + X + ishtavagutte (is pleasing). The subject of liking takes dative -kke/-ge. This is similar to Hindi mujhe X achha lagta hai. Naanu → naakke (I → to me). Neevu → nimage/neekke (you → to you). Avaru → avari ge (to them/formal). Intensifiers: thumba ishtavagutte (really like it), bahala ishtavagutte (also = very much like — bahala = very in some Karnataka dialects). Beeda (don''t want/dislike — negative imperative used for expressing dislike). Nange beeda = I don''t want it/I dislike it.","examples":[{"sentence":"Nimage yaava Kannada film ishtavagutte?","english":"Which Kannada film do you like? (formal)"},{"sentence":"Naakke coffee ishtavagutte, aadare chai ishtavagolla.","english":"I like coffee, but I don''t like tea."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"ishtavagutte means?","options":["is liked/pleasing (I like)","is good","is needed","is wanted"],"correctAnswer":"is liked/pleasing (I like)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I like Kannada cinema very much.","options":["Naakke Kannada cinema thumba ishtavagutte.","Naakke Bollywood cinema thumba ishtavagutte.","Nimage Kannada cinema thumba ishtavagutte.","Naakke Kannada cinema thakku ishtavagutte."],"correctAnswer":"Naakke Kannada cinema thumba ishtavagutte."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Naakke coffee ishtavagutte, aadare chai ___ .","options":["ishtavagolla","ishtavagutte","beeda","illa"],"correctAnswer":"ishtavagolla"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I like bisi bele bath very much.","wordBankItems":["Naakke","bisi","bele","bath","thumba","ishtavagutte","."],"correctAnswer":"Naakke bisi bele bath thumba ishtavagutte ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"naakke means?","options":["to me (dative)","my (possessive)","I (subject)","from me"],"correctAnswer":"to me (dative)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000013',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe places in Kannada","Use X thumba channa ide for describing places","Talk about cities and landmarks"],"explanation":{"intro":"Describing places covers how to talk about cities, tourist spots, and locations using adjectives and location vocabulary in Kannada.","culturalNote":"Places in Karnataka: Bengaluru (Bangalore) — IT capital, garden city (now somewhat mythological due to traffic and construction). Mysuru (Mysore) — palace city, cultural capital — Mysore Palace (Amba Vilas Palace) — one of the most visited monuments in India. Hampi — UNESCO World Heritage Site — ruins of Vijayanagara Empire (14th-16th century — one of the world''s greatest empires). Coorg (Kodagu) — Scotland of India — coffee estates, misty mountains, River Cauvery (Kaveri) origin. Udupi — temple town — Udupi cuisine (vegetarian) famous worldwide. Hassan — Hoysala temple architecture (Belur, Halebidu — intricate sculpture — 12th century). Badami, Aihole, Pattadakal — Chalukya caves and temples (6th-8th century). Gokarna — beach pilgrimage town. Jog Falls — second highest plunge waterfall in India."},"examples":[{"sentence":"Mysuru thumba channa nagaravagutte.","english":"Mysuru is a very beautiful city."},{"sentence":"Hampi UNESCO heritage jagavagutte.","english":"Hampi is a UNESCO heritage site."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can describe places and talk about Karnataka''s famous locations in Kannada."}}',
'{"items":[{"word":"nagara","translation":"city/town","transliteration":"nagara","pronunciation":"NA-ga-ra","example":"dodda nagara"},{"word":"channa","translation":"beautiful/nice","transliteration":"channa","pronunciation":"CHAN-na","example":"channa jaga"},{"word":"jaga","translation":"place/site","transliteration":"jaga","pronunciation":"JA-ga","example":"channa jaga"},{"word":"prasiddha","translation":"famous/renowned","transliteration":"prasiddha","pronunciation":"pra-SID-dha","example":"prasiddha jaga"},{"word":"doora","translation":"far/distant","transliteration":"doora","pronunciation":"DOO-ra","example":"thumba doora"},{"word":"hattira","translation":"near/close","transliteration":"hattira","pronunciation":"HAT-ti-ra","example":"hattira ide"}]}',
'{"title":"X thumba channa Y agutte — X is a very beautiful Y (describing places)","pattern":"X thumba channa Y agutte = X is a very beautiful Y. Channa = beautiful/nice. Thumba = very. Agutte = it is/becomes (present tense — used for descriptions). Also: X prasiddha jaga agutte (X is a famous place). X Y ge prasiddha agutte (X is famous for Y — ge marks the reason).","explanation":"Place description in Kannada: adjective + noun or X adjective agutte. Adjectives: channa (beautiful), dodda (big), hosa (new), haLe (old), prasiddha (famous), puNyakshetra (sacred site). Location from Bengaluru: X Bengaluruinda Y kilometre/gante doora ide (X is Y km/hours from Bengaluru). Distance: eshtu kilometre? (how many kilometres?). Famous for: X ge Y ge prasiddha agutte (X is famous for Y). Historical: X haLe jaga agutte (X is an old place). Natural: X praakrutika soundarya doora (X abounds in natural beauty).","examples":[{"sentence":"Coorg coffee ge prasiddha nagaravagutte.","english":"Coorg is a city famous for coffee."},{"sentence":"Hampi Bengaluruinda mooru nooraipatthu kilometre doora ide.","english":"Hampi is 350 kilometres far from Bengaluru."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"channa means?","options":["beautiful/nice","big","famous","old"],"correctAnswer":"beautiful/nice"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Mysuru is a very beautiful city.","options":["Mysuru thumba channa nagaravagutte.","Bengaluru thumba channa nagaravagutte.","Mysuru thakku channa nagaravagutte.","Mysuru thumba dodda nagaravagutte."],"correctAnswer":"Mysuru thumba channa nagaravagutte."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Coorg coffee ge ___ nagaravagutte.","options":["prasiddha","channa","dodda","haLe"],"correctAnswer":"prasiddha"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Hampi is a UNESCO heritage site.","wordBankItems":["Hampi","UNESCO","heritage","jagavagutte","."],"correctAnswer":"Hampi UNESCO heritage jagavagutte ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"prasiddha means?","options":["famous/renowned","beautiful","ancient","sacred"],"correctAnswer":"famous/renowned"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('11000000-0000-0000-0000-000000000014',1,'APPROVED','PUBLISHED',
'{"objectives":["Ask and answer simple questions in Kannada","Use yaaru, enu, elli, yaava, eshtu for question words","Form yes/no questions and short answers"],"explanation":{"intro":"Simple questions and answers covers the core question words and how to form basic questions and respond to them in Kannada — the foundation of all conversation.","culturalNote":"Question culture in Kannada: Kannadigas have a reputation for being reserved with strangers but very warm with those they know. Questions often begin with respectful markers in formal Kannada: nimage (to you — formal), nimma (your — formal). Casual questions among friends use neenu, ninna forms. Common small talk: elli hoguttiri? (where are you going? — a very common greeting-like question, not always expecting a full answer — similar to ''how are you?'' in English). Nodidiri? (have you seen? — common way to catch up). Yaav uru? (which place are you from? — from where? — common first question). Yantu nadyatide? (what is happening? — very colloquial — lit. what is happening here?). Yes: howdu (yes). No: illa (no). Maybe: irbahudu (may be), gottilla (I don''t know)."},"examples":[{"sentence":"Neevu elli hoguttiri?","english":"Where are you going? (formal)"},{"sentence":"Howdu, naanu Bengaluruinda.","english":"Yes, I am from Bengaluru."}],"rewards":{"xp":100,"coins":50},"metadata":{"estimatedMinutes":15,"canDo":"I can ask and answer simple questions in Kannada using the key question words."}}',
'{"items":[{"word":"yaaru","translation":"who","transliteration":"yaaru","pronunciation":"YAA-ru","example":"avaru yaaru?"},{"word":"enu","translation":"what","transliteration":"enu","pronunciation":"E-nu","example":"enu agutte?"},{"word":"elli","translation":"where","transliteration":"elli","pronunciation":"EL-li","example":"elli ide?"},{"word":"yaava","translation":"which/what (pronoun)","transliteration":"yaava","pronunciation":"YAA-va","example":"yaava bus?"},{"word":"howdu","translation":"yes","transliteration":"howdu","pronunciation":"HOW-du","example":"howdu, sari"},{"word":"illa","translation":"no/not/there isn''t","transliteration":"illa","pronunciation":"IL-la","example":"illa, gottilla"}]}',
'{"title":"Kannada question words — yaaru, enu, elli, yaava, eshtu","pattern":"Yaaru = who. Enu = what. Elli = where. Yaava = which. Eshtu = how many/much. Yaavattu = when. Haege = how. Question formation: question word + rest of sentence. Yes/no questions: add kaa at the end (optional). Yes = howdu. No = illa. I don''t know = gottilla.","explanation":"Question words in Kannada: yaaru (who), enu (what), elli (where), yaava (which — pronoun), eshtu (how much/many), yaavattu/yaavaga (when), haege (how), yaake (why). Yes/no: howdu (yes), illa (no). I don''t know: gottilla (gottilla = not known). Questions in Kannada can be formed by just adding a rising intonation, or by adding -aa at the end: neevu Bengaluruinda aa? (are you from Bengaluru?). Howdu = yes (literally ''it is so''). Illa = no/not (used both for no and ''there isn''t'': coffee illa = there is no coffee). Maybe/not sure: irbahudu (maybe), gottilla (I don''t know — lit. not known).","examples":[{"sentence":"Avaru yaaru? — Avaru nanna shikshaka.","english":"Who are they? — They are my teacher."},{"sentence":"Bus elli hoguttide? — Majestic ge hoguttide.","english":"Where is the bus going? — It is going to Majestic."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"howdu means?","options":["yes","no","maybe","okay"],"correctAnswer":"yes"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Where are you going? (formal)","options":["Neevu elli hoguttiri?","Neevu enu maaduttiri?","Neevu yaava bus hidiuttiri?","Neenu elli hoguttiya?"],"correctAnswer":"Neevu elli hoguttiri?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Avaru ___? — Avaru nanna shikshaka.","options":["yaaru","enu","elli","yaava"],"correctAnswer":"yaaru"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Yes, I am from Bengaluru.","wordBankItems":["Howdu",",","naanu","Bengaluruinda","."],"correctAnswer":"Howdu , naanu Bengaluruinda ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"gottilla means?","options":["I don''t know","I don''t have","there is none","I don''t like"],"correctAnswer":"I don''t know"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('22000000-0000-0000-0000-00000000000b','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l011',11,'Body Parts and Health','Body vocabulary and pain expressions','PUBLISHED'),
('22000000-0000-0000-0000-00000000000c','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l012',12,'Clothing and Appearance','Clothing vocabulary and wearing','PUBLISHED'),
('22000000-0000-0000-0000-00000000000d','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l013',13,'At Home — Rooms and Furniture','Home rooms and furniture vocabulary','PUBLISHED'),
('22000000-0000-0000-0000-00000000000e','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l014',14,'Transport and Travel','Transport vocabulary and getting around','PUBLISHED'),
('22000000-0000-0000-0000-00000000000f','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l015',15,'Time — Telling the Time','Gante and time expressions','PUBLISHED'),
('22000000-0000-0000-0000-000000000010','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l016',16,'Animals and Nature','Karnataka wildlife and animals','PUBLISHED'),
('22000000-0000-0000-0000-000000000011','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l017',17,'Occupations and Work','Jobs and work vocabulary','PUBLISHED'),
('22000000-0000-0000-0000-000000000012','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l018',18,'Likes and Dislikes','Ishtavagutte — liking expressions','PUBLISHED'),
('22000000-0000-0000-0000-000000000013','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l019',19,'Describing Places','Karnataka places and descriptions','PUBLISHED'),
('22000000-0000-0000-0000-000000000014','ff000000-0000-0000-0000-000000000001','ff100000-0000-0000-0000-000000000001',NULL,'kn-a1-u01-l020',20,'Simple Questions and Answers','Core Kannada question words','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-00000000000b' WHERE stable_ref = 'kn-a1-u01-l011' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-00000000000c' WHERE stable_ref = 'kn-a1-u01-l012' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-00000000000d' WHERE stable_ref = 'kn-a1-u01-l013' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-00000000000e' WHERE stable_ref = 'kn-a1-u01-l014' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-00000000000f' WHERE stable_ref = 'kn-a1-u01-l015' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000010' WHERE stable_ref = 'kn-a1-u01-l016' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000011' WHERE stable_ref = 'kn-a1-u01-l017' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000012' WHERE stable_ref = 'kn-a1-u01-l018' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000013' WHERE stable_ref = 'kn-a1-u01-l019' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = '11000000-0000-0000-0000-000000000014' WHERE stable_ref = 'kn-a1-u01-l020' AND lesson_id IS NULL;
