-- V52: German A1 lessons 6-20 (batch 2 of 4 batches planned for M3)
-- Extends German A1 from 5 → 20 lessons.
-- UUIDs: lessons aa000000-0000-0000-0000-000000000006..020
--         plans  dd000000-0000-0000-0000-000000000006..020

-- ─── cf_lessons ───────────────────────────────────────────────────────────────

INSERT INTO cf_lessons (
    id, stable_ref, title, domain_code, language_code, cefr_level,
    content_status, publication_status, current_version, active_version
) VALUES
    ('aa000000-0000-0000-0000-000000000006','de-a1-l006','Essen und Trinken - Food and Drink','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000007','de-a1-l007','Im Café - Ordering at a Café','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000008','de-a1-l008','Die Wohnung - Rooms and Home','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000009','de-a1-l009','Das Wetter - Weather Expressions','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000010','de-a1-l010','Kleidung - Clothing Vocabulary','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000011','de-a1-l011','Die Stadt - Places in the City','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000012','de-a1-l012','Verkehrsmittel - Getting Around','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000013','de-a1-l013','Zeit und Uhrzeit - Time and the Clock','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000014','de-a1-l014','Wochentage und Monate - Days and Months','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000015','de-a1-l015','Hobbys und Freizeit - Hobbies','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000016','de-a1-l016','Körper und Gesundheit - Body and Health','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000017','de-a1-l017','Einkaufen - Shopping','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000018','de-a1-l018','Im Restaurant - At the Restaurant','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000019','de-a1-l019','Reisen und Länder - Travel and Countries','language','de','A1','APPROVED','PUBLISHED',1,1),
    ('aa000000-0000-0000-0000-000000000020','de-a1-l020','Arbeit und Berufe - Work and Jobs','language','de','A1','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

-- ─── cf_lesson_versions ───────────────────────────────────────────────────────

-- LESSON 6: Essen und Trinken
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000006', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name common foods and drinks","Ask for and offer food","Use ich möchte to express wants"],"explanation":{"intro":"Food is central to German culture. In this lesson you will learn essential food vocabulary and how to politely ask for things using möchten.","culturalNote":"Germans often say Guten Appetit before eating, similar to bon appétit."},"examples":[{"german":"Ich möchte einen Kaffee, bitte.","english":"I would like a coffee, please."},{"german":"Was möchtest du essen?","english":"What would you like to eat?"}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can name common foods and drinks and ask for them politely."}}',
    '{"items":[{"word":"das Brot","translation":"bread","pronunciation":"dahs BROHT","example":"Ich esse Brot zum Frühstück."},{"word":"die Milch","translation":"milk","pronunciation":"dee MILCH","example":"Ich trinke Milch."},{"word":"der Käse","translation":"cheese","pronunciation":"dayr KAY-zeh","example":"Der Käse ist lecker."},{"word":"das Wasser","translation":"water","pronunciation":"dahs VAH-ser","example":"Ein Glas Wasser, bitte."},{"word":"der Apfel","translation":"apple","pronunciation":"dayr AHP-fel","example":"Ich möchte einen Apfel."},{"word":"das Fleisch","translation":"meat","pronunciation":"dahs FLYSH","example":"Er isst kein Fleisch."}]}',
    '{"title":"Möchten — polite wants","pattern":"ich möchte + noun","explanation":"Möchten is the polite form of wollen (to want). Use it to order food or ask for things. Ich möchte = I would like.","examples":[{"sentence":"Ich möchte einen Tee.","translation":"I would like a tea."},{"sentence":"Möchtest du Kuchen?","translation":"Would you like cake?"}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"What does ''das Brot'' mean?","options":["bread","milk","meat","water"],"correctAnswer":"bread"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I would like a water, please.","options":["Ich möchte ein Wasser, bitte.","Ich esse Brot.","Was möchtest du?","Der Käse ist gut."],"correctAnswer":"Ich möchte ein Wasser, bitte."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich ___ einen Apfel möchte.","options":["möchte","esse","trinke","bin"],"correctAnswer":"möchte"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I would like cheese please","wordBankItems":["Ich","möchte","Käse","bitte",".","ein"],"correctAnswer":"Ich möchte Käse bitte ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which article goes with ''Milch''?","options":["die","der","das","den"],"correctAnswer":"die"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 7: Im Café
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000007', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Order drinks and snacks at a café","Ask for the bill","Use bitte and danke naturally"],"explanation":{"intro":"Cafés are popular meeting spots in Germany. Knowing how to order confidently makes every visit enjoyable.","culturalNote":"Tipping is common in Germany — rounding up the bill is the norm."},"examples":[{"german":"Einen Kaffee und ein Stück Kuchen, bitte.","english":"A coffee and a piece of cake, please."},{"german":"Die Rechnung, bitte.","english":"The bill, please."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can order food and drinks at a café and ask for the bill."}}',
    '{"items":[{"word":"der Kaffee","translation":"coffee","pronunciation":"dayr KAH-feh","example":"Einen Kaffee, bitte."},{"word":"der Tee","translation":"tea","pronunciation":"dayr TAY","example":"Ich möchte Tee."},{"word":"der Kuchen","translation":"cake","pronunciation":"dayr KOO-khen","example":"Der Kuchen ist süß."},{"word":"die Rechnung","translation":"bill/invoice","pronunciation":"dee REKH-noong","example":"Die Rechnung, bitte."},{"word":"die Bedienung","translation":"waiter/service","pronunciation":"dee beh-DEE-noong","example":"Die Bedienung kommt gleich."},{"word":"bezahlen","translation":"to pay","pronunciation":"beh-TSAH-len","example":"Ich möchte bezahlen."}]}',
    '{"title":"Ein vs. Einen — accusative article","pattern":"ein (nominative) → einen (accusative, masculine)","explanation":"When a masculine noun is the object of the sentence, der becomes den and ein becomes einen. Feminine and neuter stay the same in accusative.","examples":[{"sentence":"Das ist ein Kaffee. (nominative)","translation":"That is a coffee."},{"sentence":"Ich möchte einen Kaffee. (accusative)","translation":"I would like a coffee."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"How do you say ''the bill'' in German?","options":["die Rechnung","der Kaffee","der Kuchen","die Bedienung"],"correctAnswer":"die Rechnung"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I would like a tea, please.","options":["Ich möchte einen Tee, bitte.","Die Rechnung bitte.","Einen Kuchen bitte.","Ich bezahle."],"correctAnswer":"Ich möchte einen Tee, bitte."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Einen Kaffee und ___ Stück Kuchen, bitte.","options":["ein","einen","eine","der"],"correctAnswer":"ein"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The bill please","wordBankItems":["Die","Rechnung",",","bitte","."],"correctAnswer":"Die Rechnung , bitte ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Bezahlen'' means?","options":["to pay","to eat","to drink","to order"],"correctAnswer":"to pay"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 8: Die Wohnung
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000008', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name rooms in a home","Describe where things are","Use es gibt to say something exists"],"explanation":{"intro":"Being able to describe your home is a key everyday skill. Learn room names and basic location expressions.","culturalNote":"German apartments often do not include a kitchen — it is common to bring your own kitchen when you move!"},"examples":[{"german":"Das Schlafzimmer ist groß.","english":"The bedroom is large."},{"german":"Es gibt ein Bad im Flur.","english":"There is a bathroom in the hallway."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can name the rooms in a home and say where things are."}}',
    '{"items":[{"word":"das Schlafzimmer","translation":"bedroom","pronunciation":"dahs SHLAHF-tsim-er","example":"Ich schlafe im Schlafzimmer."},{"word":"die Küche","translation":"kitchen","pronunciation":"dee KÜ-kheh","example":"Die Küche ist klein."},{"word":"das Wohnzimmer","translation":"living room","pronunciation":"dahs VOHN-tsim-er","example":"Wir sitzen im Wohnzimmer."},{"word":"das Bad","translation":"bathroom","pronunciation":"dahs BAHT","example":"Das Bad ist links."},{"word":"der Flur","translation":"hallway","pronunciation":"dayr FLOOR","example":"Der Flur ist lang."},{"word":"der Balkon","translation":"balcony","pronunciation":"dayr bal-KOHN","example":"Ich stehe auf dem Balkon."}]}',
    '{"title":"Es gibt — there is/there are","pattern":"Es gibt + accusative noun","explanation":"Use es gibt to say something exists or is available. It is always es gibt — it never changes form.","examples":[{"sentence":"Es gibt ein Wohnzimmer.","translation":"There is a living room."},{"sentence":"Es gibt keine Küche.","translation":"There is no kitchen."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Schlafzimmer'' means?","options":["bedroom","kitchen","bathroom","hallway"],"correctAnswer":"bedroom"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The kitchen is small.","options":["Die Küche ist klein.","Das Bad ist groß.","Es gibt ein Zimmer.","Der Flur ist lang."],"correctAnswer":"Die Küche ist klein."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ gibt ein Bad im Flur.","options":["Es","Er","Sie","Das"],"correctAnswer":"Es"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: There is a balcony","wordBankItems":["Es","gibt","einen","Balkon","."],"correctAnswer":"Es gibt einen Balkon ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which room is ''die Küche''?","options":["kitchen","bedroom","living room","balcony"],"correctAnswer":"kitchen"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 9: Das Wetter
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000009', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Describe the weather","Ask what the weather is like","Use es ist and es wird"],"explanation":{"intro":"Weather is a universal conversation starter. Germans love talking about the weather — learn to join in!","culturalNote":"Germany has four distinct seasons. Winters in the north are grey and rainy; summers in Bavaria can be warm and sunny."},"examples":[{"german":"Wie ist das Wetter heute?","english":"What is the weather like today?"},{"german":"Es ist sonnig und warm.","english":"It is sunny and warm."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can describe the weather and ask what it is like."}}',
    '{"items":[{"word":"sonnig","translation":"sunny","pronunciation":"ZON-ikh","example":"Es ist sonnig heute."},{"word":"regnerisch","translation":"rainy","pronunciation":"RAYG-ner-ish","example":"Es ist regnerisch."},{"word":"kalt","translation":"cold","pronunciation":"KALT","example":"Es ist sehr kalt."},{"word":"warm","translation":"warm","pronunciation":"VARM","example":"Das Wetter ist warm."},{"word":"der Schnee","translation":"snow","pronunciation":"dayr SHNAY","example":"Es gibt Schnee."},{"word":"der Wind","translation":"wind","pronunciation":"dayr VINT","example":"Der Wind ist stark."}]}',
    '{"title":"Es ist — describing the weather","pattern":"Es ist + adjective / Es gibt + noun","explanation":"For weather descriptions use es ist + adjective (es ist kalt) or es gibt + noun (es gibt Regen). Both patterns are common.","examples":[{"sentence":"Es ist bewölkt.","translation":"It is cloudy."},{"sentence":"Es gibt Regen.","translation":"There is rain."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"How do you say ''it is cold''?","options":["Es ist kalt.","Es ist warm.","Es gibt Schnee.","Der Wind ist stark."],"correctAnswer":"Es ist kalt."},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"What is the weather like today?","options":["Wie ist das Wetter heute?","Es ist sonnig.","Es gibt Wind.","Wie viel kostet das?"],"correctAnswer":"Wie ist das Wetter heute?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Es ist ___ und warm.","options":["sonnig","kalt","regnerisch","schnell"],"correctAnswer":"sonnig"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: It is rainy today","wordBankItems":["Es","ist","regnerisch","heute","."],"correctAnswer":"Es ist regnerisch heute ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Schnee'' means?","options":["snow","wind","rain","sun"],"correctAnswer":"snow"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 10: Kleidung
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000010', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name common clothing items","Say what you are wearing","Use tragen (to wear)"],"explanation":{"intro":"Clothing vocabulary is essential for shopping and describing people. Learn the most common German clothing words.","culturalNote":"Germans tend to dress practically and layer up in autumn and winter."},"examples":[{"german":"Ich trage eine Jacke.","english":"I am wearing a jacket."},{"german":"Die Hose ist blau.","english":"The trousers are blue."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can name clothing items and say what I am wearing."}}',
    '{"items":[{"word":"die Jacke","translation":"jacket","pronunciation":"dee YAH-keh","example":"Ich trage eine Jacke."},{"word":"die Hose","translation":"trousers/pants","pronunciation":"dee HOH-zeh","example":"Die Hose ist schwarz."},{"word":"das Hemd","translation":"shirt","pronunciation":"dahs HEMT","example":"Das Hemd ist weiß."},{"word":"die Schuhe","translation":"shoes (pl.)","pronunciation":"dee SHOO-eh","example":"Die Schuhe sind neu."},{"word":"der Mantel","translation":"coat","pronunciation":"dayr MAN-tel","example":"Der Mantel ist warm."},{"word":"die Mütze","translation":"hat/beanie","pronunciation":"dee MÜT-seh","example":"Ich trage eine Mütze."}]}',
    '{"title":"Tragen — to wear/carry","pattern":"ich trage / du trägst / er trägt","explanation":"Tragen is an irregular verb. In the du and er/sie/es forms the vowel changes from a to ä (umlaut). Ich trage but du trägst.","examples":[{"sentence":"Ich trage ein Hemd.","translation":"I wear a shirt."},{"sentence":"Sie trägt eine Jacke.","translation":"She wears a jacket."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Schuhe'' means?","options":["shoes","jacket","shirt","coat"],"correctAnswer":"shoes"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I am wearing a coat.","options":["Ich trage einen Mantel.","Die Hose ist blau.","Das Hemd ist weiß.","Er trägt Schuhe."],"correctAnswer":"Ich trage einen Mantel."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Sie ___ eine Mütze.","options":["trägt","trage","trägst","tragen"],"correctAnswer":"trägt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The trousers are black","wordBankItems":["Die","Hose","ist","schwarz","."],"correctAnswer":"Die Hose ist schwarz ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which is ''das Hemd''?","options":["shirt","jacket","trousers","shoes"],"correctAnswer":"shirt"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 11: Die Stadt
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000011', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name places in a city","Ask and give directions","Use links, rechts, geradeaus"],"explanation":{"intro":"Getting around a German city is much easier when you know key place names and direction words.","culturalNote":"Germany has excellent public transport. Most cities have a Hauptbahnhof (main train station) as the central hub."},"examples":[{"german":"Wo ist die Apotheke?","english":"Where is the pharmacy?"},{"german":"Gehen Sie geradeaus bis zur Ampel.","english":"Go straight ahead to the traffic light."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can name places in a city and give basic directions."}}',
    '{"items":[{"word":"die Apotheke","translation":"pharmacy","pronunciation":"dee ah-poh-TAY-keh","example":"Die Apotheke ist links."},{"word":"der Bahnhof","translation":"train station","pronunciation":"dayr BAHN-hohf","example":"Wo ist der Bahnhof?"},{"word":"das Krankenhaus","translation":"hospital","pronunciation":"dahs KRAN-ken-howss","example":"Das Krankenhaus ist groß."},{"word":"die Schule","translation":"school","pronunciation":"dee SHOO-leh","example":"Die Schule ist um die Ecke."},{"word":"links","translation":"left","pronunciation":"LINKS","example":"Biegen Sie links ab."},{"word":"rechts","translation":"right","pronunciation":"REKHTS","example":"Das Café ist rechts."}]}',
    '{"title":"Direction imperatives","pattern":"Gehen Sie + direction / Biegen Sie + direction + ab","explanation":"To give directions in formal German use Sie-form imperatives: Gehen Sie (go), Biegen Sie ab (turn). For casual speech drop Sie: Geh links.","examples":[{"sentence":"Gehen Sie geradeaus.","translation":"Go straight ahead."},{"sentence":"Biegen Sie rechts ab.","translation":"Turn right."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Bahnhof'' means?","options":["train station","pharmacy","hospital","school"],"correctAnswer":"train station"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Where is the pharmacy?","options":["Wo ist die Apotheke?","Wo ist der Bahnhof?","Gehen Sie links.","Die Schule ist groß."],"correctAnswer":"Wo ist die Apotheke?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Gehen Sie ___ bis zur Ampel.","options":["geradeaus","links","rechts","oben"],"correctAnswer":"geradeaus"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Turn left","wordBankItems":["Biegen","Sie","links","ab","."],"correctAnswer":"Biegen Sie links ab ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Rechts'' means?","options":["right","left","straight","behind"],"correctAnswer":"right"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 12: Verkehrsmittel
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000012', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name means of transport","Buy a ticket","Use fahren and nehmen"],"explanation":{"intro":"Germany has one of Europe''s best public transport networks. Knowing how to navigate buses, trams and trains is very useful.","culturalNote":"The U-Bahn is the underground/metro. S-Bahn trains run above and below ground connecting suburbs to the city."},"examples":[{"german":"Ich fahre mit der U-Bahn.","english":"I travel by underground."},{"german":"Eine Fahrkarte nach Berlin, bitte.","english":"A ticket to Berlin, please."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can name transport options and buy a simple ticket."}}',
    '{"items":[{"word":"die U-Bahn","translation":"underground/metro","pronunciation":"dee OO-bahn","example":"Ich nehme die U-Bahn."},{"word":"der Bus","translation":"bus","pronunciation":"dayr BOOS","example":"Der Bus kommt um 8 Uhr."},{"word":"das Fahrrad","translation":"bicycle","pronunciation":"dahs FAR-raht","example":"Ich fahre Fahrrad."},{"word":"die Fahrkarte","translation":"ticket","pronunciation":"dee FAR-kar-teh","example":"Wo kaufe ich eine Fahrkarte?"},{"word":"fahren","translation":"to drive/travel","pronunciation":"FAR-en","example":"Ich fahre mit dem Bus."},{"word":"der Zug","translation":"train","pronunciation":"dayr TSOOK","example":"Der Zug fährt pünktlich."}]}',
    '{"title":"Mit + dative for transport","pattern":"fahren mit + dem/der (dative)","explanation":"To say how you travel use fahren/fahren mit + dative. Der Bus → mit dem Bus; die U-Bahn → mit der U-Bahn; das Fahrrad → mit dem Fahrrad.","examples":[{"sentence":"Ich fahre mit dem Zug.","translation":"I travel by train."},{"sentence":"Sie fährt mit der U-Bahn.","translation":"She travels by underground."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Fahrkarte'' means?","options":["ticket","train","bicycle","bus"],"correctAnswer":"ticket"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I travel by bus.","options":["Ich fahre mit dem Bus.","Ich nehme die U-Bahn.","Der Zug fährt ab.","Eine Fahrkarte bitte."],"correctAnswer":"Ich fahre mit dem Bus."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich fahre mit ___ U-Bahn.","options":["der","dem","die","den"],"correctAnswer":"der"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: A ticket to Berlin please","wordBankItems":["Eine","Fahrkarte","nach","Berlin",",","bitte","."],"correctAnswer":"Eine Fahrkarte nach Berlin , bitte ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Zug'' means?","options":["train","bus","bicycle","underground"],"correctAnswer":"train"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 13: Zeit und Uhrzeit
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000013', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Tell the time in German","Ask what time it is","Use Uhr and half/quarter expressions"],"explanation":{"intro":"Knowing how to tell the time is essential for making appointments and catching transport on time.","culturalNote":"Germans use the 24-hour clock in formal contexts. Es ist 15 Uhr = It is 3 pm."},"examples":[{"german":"Wie viel Uhr ist es?","english":"What time is it?"},{"german":"Es ist halb drei.","english":"It is half past two (2:30)."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can ask for and tell the time in German."}}',
    '{"items":[{"word":"die Uhr","translation":"clock/watch/o''clock","pronunciation":"dee OOR","example":"Es ist drei Uhr."},{"word":"halb","translation":"half (past the previous hour)","pronunciation":"HALP","example":"Es ist halb vier."},{"word":"Viertel nach","translation":"quarter past","pronunciation":"FEER-tel NAKH","example":"Es ist Viertel nach zwei."},{"word":"Viertel vor","translation":"quarter to","pronunciation":"FEER-tel FOR","example":"Es ist Viertel vor fünf."},{"word":"die Stunde","translation":"hour","pronunciation":"dee SHTOON-deh","example":"In einer Stunde."},{"word":"die Minute","translation":"minute","pronunciation":"dee mee-NOO-teh","example":"Fünf Minuten."}]}',
    '{"title":"Telling time with halb","pattern":"halb + next hour = half past current hour","explanation":"In German halb drei means half to three = 2:30. This is the opposite of English! Halb vier = 3:30, halb zehn = 9:30.","examples":[{"sentence":"Es ist halb fünf.","translation":"It is 4:30."},{"sentence":"Es ist Viertel nach drei.","translation":"It is 3:15."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"What does ''halb drei'' mean?","options":["2:30","3:30","3:00","2:00"],"correctAnswer":"2:30"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"What time is it?","options":["Wie viel Uhr ist es?","Wo ist die Uhr?","Es ist drei Uhr.","Wie lange dauert es?"],"correctAnswer":"Wie viel Uhr ist es?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Es ist ___ nach vier. (quarter past four)","options":["Viertel","halb","drei","zwölf"],"correctAnswer":"Viertel"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: It is 5 o''clock","wordBankItems":["Es","ist","fünf","Uhr","."],"correctAnswer":"Es ist fünf Uhr ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Minute'' means?","options":["minute","hour","clock","time"],"correctAnswer":"minute"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 14: Wochentage und Monate
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000014', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name days of the week","Name the months","Say what day or month something is"],"explanation":{"intro":"Days and months are used constantly in daily life — for appointments, birthdays and planning.","culturalNote":"German days come from Norse gods: Dienstag (Tyr), Mittwoch (mid-week), Donnerstag (Thor), Freitag (Frigg)."},"examples":[{"german":"Heute ist Montag.","english":"Today is Monday."},{"german":"Mein Geburtstag ist im Juli.","english":"My birthday is in July."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can name the days of the week and months of the year."}}',
    '{"items":[{"word":"Montag","translation":"Monday","pronunciation":"MOHN-tahk","example":"Ich arbeite am Montag."},{"word":"Mittwoch","translation":"Wednesday","pronunciation":"MIT-vokh","example":"Am Mittwoch habe ich frei."},{"word":"Freitag","translation":"Friday","pronunciation":"FRY-tahk","example":"Freitag ist mein Lieblingstag."},{"word":"Januar","translation":"January","pronunciation":"YAH-noo-ar","example":"Im Januar ist es kalt."},{"word":"Juli","translation":"July","pronunciation":"YOO-lee","example":"Im Juli fahre ich in Urlaub."},{"word":"Dezember","translation":"December","pronunciation":"deh-TSEM-ber","example":"Dezember ist der letzte Monat."}]}',
    '{"title":"Am + day / Im + month","pattern":"am + weekday (dative), im + month (dative)","explanation":"Use am with days of the week (am Montag = on Monday) and im with months (im Juli = in July). These are fixed dative contractions.","examples":[{"sentence":"Am Freitag gehe ich ins Kino.","translation":"On Friday I go to the cinema."},{"sentence":"Im Dezember schneit es.","translation":"In December it snows."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Mittwoch'' means?","options":["Wednesday","Monday","Friday","Thursday"],"correctAnswer":"Wednesday"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Today is Friday.","options":["Heute ist Freitag.","Heute ist Montag.","Im Juli ist Sommer.","Am Freitag arbeite ich."],"correctAnswer":"Heute ist Freitag."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ Juli fahre ich in Urlaub.","options":["Im","Am","In","An"],"correctAnswer":"Im"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: On Monday I work","wordBankItems":["Am","Montag","arbeite","ich","."],"correctAnswer":"Am Montag arbeite ich ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which month is ''Juli''?","options":["July","January","June","December"],"correctAnswer":"July"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 15: Hobbys und Freizeit
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000015', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Talk about hobbies","Say what you like doing","Use gern and mögen"],"explanation":{"intro":"Talking about hobbies helps you connect with people. German uses gern after a verb to show you enjoy something.","culturalNote":"Football (Fußball) is by far the most popular sport in Germany. Hiking (Wandern) and cycling are also very common."},"examples":[{"german":"Ich spiele gern Fußball.","english":"I like playing football."},{"german":"Was machst du in deiner Freizeit?","english":"What do you do in your free time?"}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about hobbies and say what I enjoy doing."}}',
    '{"items":[{"word":"das Hobby","translation":"hobby","pronunciation":"dahs HOB-ee","example":"Was ist dein Hobby?"},{"word":"Fußball spielen","translation":"to play football","pronunciation":"FOOS-bal SHPEE-len","example":"Ich spiele Fußball."},{"word":"lesen","translation":"to read","pronunciation":"LAY-zen","example":"Ich lese gern Bücher."},{"word":"Musik hören","translation":"to listen to music","pronunciation":"moo-ZEEK HÖ-ren","example":"Sie hört gern Musik."},{"word":"kochen","translation":"to cook","pronunciation":"KOKH-en","example":"Er kocht sehr gut."},{"word":"die Freizeit","translation":"free time/leisure","pronunciation":"dee FRY-tsyt","example":"In meiner Freizeit lese ich."}]}',
    '{"title":"Gern — expressing enjoyment","pattern":"verb + gern = to like doing something","explanation":"Place gern directly after the conjugated verb to say you enjoy doing something. Ich lese gern = I like reading. To say you dislike something, use nicht gern.","examples":[{"sentence":"Ich koche gern.","translation":"I like cooking."},{"sentence":"Er spielt nicht gern Tennis.","translation":"He does not like playing tennis."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"How do you say ''I like reading''?","options":["Ich lese gern.","Ich lese nicht.","Lesen macht Spaß.","Ich mag Bücher."],"correctAnswer":"Ich lese gern."},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"What do you do in your free time?","options":["Was machst du in deiner Freizeit?","Was ist dein Hobby?","Ich spiele Fußball.","Hast du Zeit?"],"correctAnswer":"Was machst du in deiner Freizeit?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Sie hört ___ Musik.","options":["gern","gut","nicht","sehr"],"correctAnswer":"gern"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I like playing football","wordBankItems":["Ich","spiele","gern","Fußball","."],"correctAnswer":"Ich spiele gern Fußball ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Kochen'' means?","options":["to cook","to read","to play","to swim"],"correctAnswer":"to cook"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 16: Körper und Gesundheit
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000016', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name body parts","Say what hurts","Use Ich habe Schmerzen / Mir tut weh"],"explanation":{"intro":"Knowing body vocabulary is essential for any medical situation or describing how you feel.","culturalNote":"In Germany you need a Krankenversicherung (health insurance) to see a doctor. EU citizens can use their EHIC card."},"examples":[{"german":"Mir tut der Kopf weh.","english":"My head hurts."},{"german":"Ich habe Bauchschmerzen.","english":"I have stomach ache."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can name body parts and say what is hurting."}}',
    '{"items":[{"word":"der Kopf","translation":"head","pronunciation":"dayr KOPF","example":"Mir tut der Kopf weh."},{"word":"der Bauch","translation":"stomach/belly","pronunciation":"dayr BOWKH","example":"Ich habe Bauchschmerzen."},{"word":"der Arm","translation":"arm","pronunciation":"dayr ARM","example":"Mein Arm tut weh."},{"word":"das Bein","translation":"leg","pronunciation":"dahs BYN","example":"Mein Bein ist gebrochen."},{"word":"der Rücken","translation":"back","pronunciation":"dayr RÜ-ken","example":"Ich habe Rückenschmerzen."},{"word":"die Hand","translation":"hand","pronunciation":"dee HANT","example":"Meine Hand tut weh."}]}',
    '{"title":"Mir tut ... weh — something hurts me","pattern":"Mir tut + body part (nominative) + weh","explanation":"Use mir tut ... weh to say a body part hurts. The body part is the subject (nominative). Mir tut der Kopf weh = My head hurts (lit. The head aches to me).","examples":[{"sentence":"Mir tut der Rücken weh.","translation":"My back hurts."},{"sentence":"Mir tun die Beine weh.","translation":"My legs hurt."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Rücken'' means?","options":["back","arm","leg","head"],"correctAnswer":"back"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"My head hurts.","options":["Mir tut der Kopf weh.","Ich habe Bauchschmerzen.","Mein Arm tut weh.","Der Arzt kommt."],"correctAnswer":"Mir tut der Kopf weh."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Mir tut der Bauch ___.","options":["weh","gut","kalt","groß"],"correctAnswer":"weh"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I have back pain","wordBankItems":["Ich","habe","Rückenschmerzen","."],"correctAnswer":"Ich habe Rückenschmerzen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Bein'' means?","options":["leg","arm","hand","foot"],"correctAnswer":"leg"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 17: Einkaufen
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000017', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Shop for items in German","Ask for prices","Use Wie viel kostet das?"],"explanation":{"intro":"Shopping vocabulary lets you navigate markets, supermarkets and stores confidently.","culturalNote":"Many German shops are closed on Sundays. Farmers markets (Wochenmarkt) are popular on Saturday mornings."},"examples":[{"german":"Wie viel kostet das?","english":"How much does this cost?"},{"german":"Das kostet fünf Euro.","english":"That costs five euros."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can ask for prices and buy items in a shop."}}',
    '{"items":[{"word":"kosten","translation":"to cost","pronunciation":"KOS-ten","example":"Was kostet das?"},{"word":"der Preis","translation":"price","pronunciation":"dayr PRYS","example":"Der Preis ist gut."},{"word":"teuer","translation":"expensive","pronunciation":"TOY-er","example":"Das ist zu teuer."},{"word":"billig","translation":"cheap","pronunciation":"BIL-ikh","example":"Das Hemd ist billig."},{"word":"der Supermarkt","translation":"supermarket","pronunciation":"dayr ZOO-per-markt","example":"Ich gehe in den Supermarkt."},{"word":"die Kasse","translation":"cash register/checkout","pronunciation":"dee KAS-eh","example":"Wo ist die Kasse?"}]}',
    '{"title":"Wie viel / Wie viele — how much/many","pattern":"Wie viel kostet + noun (singular) / Wie viele kosten + noun (plural)","explanation":"Use wie viel for uncountable or singular items and wie viele for countable plurals. Wie viel kostet das? / Wie viele kosten die Äpfel?","examples":[{"sentence":"Wie viel kostet der Mantel?","translation":"How much does the coat cost?"},{"sentence":"Wie viele kosten die Schuhe?","translation":"How much do the shoes cost?"}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"How do you ask ''how much does this cost''?","options":["Wie viel kostet das?","Was ist das?","Wo ist die Kasse?","Haben Sie das?"],"correctAnswer":"Wie viel kostet das?"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"That is too expensive.","options":["Das ist zu teuer.","Das ist billig.","Der Preis ist gut.","Ich kaufe das."],"correctAnswer":"Das ist zu teuer."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das ___ zehn Euro.","options":["kostet","kauft","gibt","macht"],"correctAnswer":"kostet"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Where is the checkout?","wordBankItems":["Wo","ist","die","Kasse","?"],"correctAnswer":"Wo ist die Kasse ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Billig'' means?","options":["cheap","expensive","free","good"],"correctAnswer":"cheap"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 18: Im Restaurant
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000018', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Order a meal at a restaurant","Ask about dishes","Handle the bill"],"explanation":{"intro":"Dining out in Germany is a pleasure. Knowing restaurant vocabulary helps you order confidently and enjoy the experience.","culturalNote":"In Germany it is normal to sit with strangers at a shared table (Stammtisch). Always say Guten Appetit before eating."},"examples":[{"german":"Ich hätte gern das Schnitzel.","english":"I would like the schnitzel."},{"german":"Kann ich bitte die Speisekarte haben?","english":"Can I have the menu please?"}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can order food at a restaurant and ask for the menu."}}',
    '{"items":[{"word":"die Speisekarte","translation":"menu","pronunciation":"dee SHPY-zeh-kar-teh","example":"Kann ich die Speisekarte sehen?"},{"word":"die Vorspeise","translation":"starter","pronunciation":"dee FOR-shpy-zeh","example":"Als Vorspeise nehme ich die Suppe."},{"word":"das Hauptgericht","translation":"main course","pronunciation":"dahs HOWPT-geh-rikht","example":"Was ist das Hauptgericht?"},{"word":"die Nachspeise","translation":"dessert","pronunciation":"dee NAKH-shpy-zeh","example":"Ich möchte eine Nachspeise."},{"word":"der Kellner","translation":"waiter","pronunciation":"dayr KEL-ner","example":"Der Kellner kommt gleich."},{"word":"bestellen","translation":"to order","pronunciation":"beh-SHTEL-en","example":"Ich möchte bestellen."}]}',
    '{"title":"Ich hätte gern — I would like (polite)","pattern":"Ich hätte gern + accusative noun","explanation":"Ich hätte gern is a very polite way to order food or ask for something. It is the Konjunktiv II form of haben and sounds more refined than ich möchte in restaurant settings.","examples":[{"sentence":"Ich hätte gern den Salat.","translation":"I would like the salad."},{"sentence":"Wir hätten gern die Rechnung.","translation":"We would like the bill."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Speisekarte'' means?","options":["menu","bill","starter","dessert"],"correctAnswer":"menu"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I would like the main course.","options":["Ich hätte gern das Hauptgericht.","Ich möchte die Vorspeise.","Die Rechnung bitte.","Was ist das Tagesgericht?"],"correctAnswer":"Ich hätte gern das Hauptgericht."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Kann ich bitte ___ Speisekarte haben?","options":["die","der","das","den"],"correctAnswer":"die"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I would like to order","wordBankItems":["Ich","möchte","bestellen","."],"correctAnswer":"Ich möchte bestellen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Bestellen'' means?","options":["to order","to pay","to eat","to cook"],"correctAnswer":"to order"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 19: Reisen und Länder
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000019', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name countries in German","Say where you are from","Use aus and in for origin and location"],"explanation":{"intro":"Germany shares borders with nine countries. Travel vocabulary and country names are essential for conversations about origins and destinations.","culturalNote":"Germany is called Deutschland. Germans may say Ich komme aus Deutschland or Ich bin Deutscher/Deutsche."},"examples":[{"german":"Ich komme aus Indien.","english":"I come from India."},{"german":"Ich reise nach Frankreich.","english":"I am travelling to France."}],"rewards":{"xp":110,"coins":55},"metadata":{"estimatedMinutes":15,"canDo":"I can name countries, say where I am from, and talk about travel destinations."}}',
    '{"items":[{"word":"Deutschland","translation":"Germany","pronunciation":"DOYCH-lant","example":"Ich wohne in Deutschland."},{"word":"Frankreich","translation":"France","pronunciation":"FRANK-rysh","example":"Paris ist in Frankreich."},{"word":"Indien","translation":"India","pronunciation":"IN-dee-en","example":"Ich komme aus Indien."},{"word":"reisen","translation":"to travel","pronunciation":"RY-zen","example":"Ich reise gern."},{"word":"das Ausland","translation":"abroad/foreign country","pronunciation":"dahs OWSS-lant","example":"Ich fahre ins Ausland."},{"word":"der Pass","translation":"passport","pronunciation":"dayr PASS","example":"Wo ist mein Pass?"}]}',
    '{"title":"Aus vs. nach — from vs. to","pattern":"kommen aus + country, fahren/reisen nach + country","explanation":"Use aus with the verb kommen to say where you are from. Use nach with fahren/reisen for destinations (countries without article). Exception: in die Schweiz, in die Türkei (feminine countries use in + accusative).","examples":[{"sentence":"Ich komme aus Spanien.","translation":"I come from Spain."},{"sentence":"Ich reise nach Japan.","translation":"I am travelling to Japan."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"How do you say ''I come from India''?","options":["Ich komme aus Indien.","Ich fahre nach Indien.","Ich bin in Indien.","Ich reise nach Indien."],"correctAnswer":"Ich komme aus Indien."},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I am travelling to France.","options":["Ich reise nach Frankreich.","Ich komme aus Frankreich.","Frankreich ist schön.","Ich fahre ins Ausland."],"correctAnswer":"Ich reise nach Frankreich."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Wo ist mein ___?","options":["Pass","Zug","Koffer","Ticket"],"correctAnswer":"Pass"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I like travelling abroad","wordBankItems":["Ich","reise","gern","ins","Ausland","."],"correctAnswer":"Ich reise gern ins Ausland ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Deutschland'' means?","options":["Germany","France","Austria","Switzerland"],"correctAnswer":"Germany"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- LESSON 20: Arbeit und Berufe
INSERT INTO cf_lesson_versions (lesson_id, version, content_status, publication_status, content, vocabulary, grammar, exercises, frozen, published_at)
VALUES (
    'aa000000-0000-0000-0000-000000000020', 1, 'APPROVED', 'PUBLISHED',
    '{"objectives":["Name common professions","Say what job you do","Ask what someone does for work"],"explanation":{"intro":"Talking about your job is one of the first things that comes up when meeting new people. Learn common profession names and how to say what you do.","culturalNote":"In German, professions have masculine and feminine forms: Lehrer (male teacher) / Lehrerin (female teacher). Add -in for the feminine form."},"examples":[{"german":"Was bist du von Beruf?","english":"What do you do for a living?"},{"german":"Ich bin Ingenieur.","english":"I am an engineer."}],"rewards":{"xp":120,"coins":60},"metadata":{"estimatedMinutes":15,"canDo":"I can say what job I do and ask others about their profession."}}',
    '{"items":[{"word":"der Lehrer / die Lehrerin","translation":"teacher (m/f)","pronunciation":"dayr LAY-rer / dee LAY-rer-in","example":"Sie ist Lehrerin."},{"word":"der Arzt / die Ärztin","translation":"doctor (m/f)","pronunciation":"dayr ARTST / dee AIRTS-tin","example":"Er ist Arzt."},{"word":"der Ingenieur","translation":"engineer","pronunciation":"dayr in-zheh-NYÖR","example":"Ich bin Ingenieur."},{"word":"der Koch / die Köchin","translation":"cook/chef (m/f)","pronunciation":"dayr KOKH / dee KÖ-khin","example":"Der Koch ist sehr gut."},{"word":"der Beruf","translation":"profession/job","pronunciation":"dayr beh-ROOF","example":"Was ist dein Beruf?"},{"word":"arbeiten","translation":"to work","pronunciation":"AR-by-ten","example":"Ich arbeite bei Siemens."}]}',
    '{"title":"Professions without article","pattern":"Ich bin + profession (no article)","explanation":"In German, when stating your profession after sein (to be), you do not use an article. Ich bin Lehrer (not ein Lehrer). This is different from English and a common mistake to avoid.","examples":[{"sentence":"Ich bin Ärztin.","translation":"I am a doctor. (female)"},{"sentence":"Er ist Ingenieur.","translation":"He is an engineer."}]}',
    '{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"How do you ask ''What do you do for work''?","options":["Was bist du von Beruf?","Wo arbeitest du?","Was machst du gern?","Wie heißt du?"],"correctAnswer":"Was bist du von Beruf?"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"She is a teacher.","options":["Sie ist Lehrerin.","Er ist Lehrer.","Ich bin Ärztin.","Sie arbeitet."],"correctAnswer":"Sie ist Lehrerin."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich ___ bei einer Firma.","options":["arbeite","bin","habe","gehe"],"correctAnswer":"arbeite"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I am an engineer","wordBankItems":["Ich","bin","Ingenieur","."],"correctAnswer":"Ich bin Ingenieur ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Arzt'' means?","options":["doctor","teacher","engineer","chef"],"correctAnswer":"doctor"}]}'::jsonb,
    true, NOW()
) ON CONFLICT (lesson_id, version) DO NOTHING;

-- ─── cf_curriculum_lesson_plans (positions 6-20) ─────────────────────────────

INSERT INTO cf_curriculum_lesson_plans (
    id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status
) VALUES
    ('dd000000-0000-0000-0000-000000000006','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l006',6,'Essen und Trinken - Food and Drink','Food vocabulary and möchten for polite requests','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000007','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l007',7,'Im Café - Ordering at a Café','Café vocabulary and accusative article','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000008','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l008',8,'Die Wohnung - Rooms and Home','Home rooms and es gibt construction','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000009','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l009',9,'Das Wetter - Weather Expressions','Weather adjectives and es ist/es gibt','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000010','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l010',10,'Kleidung - Clothing Vocabulary','Clothing and tragen verb umlaut','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000011','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l011',11,'Die Stadt - Places in the City','City places and direction imperatives','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000012','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l012',12,'Verkehrsmittel - Getting Around','Transport and mit + dative','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000013','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l013',13,'Zeit und Uhrzeit - Time and the Clock','Telling time including halb construction','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000014','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l014',14,'Wochentage und Monate - Days and Months','Days, months, am + day, im + month','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000015','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l015',15,'Hobbys und Freizeit - Hobbies','Hobbies and gern for enjoyment','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000016','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l016',16,'Körper und Gesundheit - Body and Health','Body parts and mir tut weh','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000017','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l017',17,'Einkaufen - Shopping','Shopping vocabulary and wie viel kostet','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000018','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l018',18,'Im Restaurant - At the Restaurant','Restaurant ordering and ich hätte gern','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000019','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l019',19,'Reisen und Länder - Travel and Countries','Countries and aus vs nach','PUBLISHED'),
    ('dd000000-0000-0000-0000-000000000020','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001',NULL,'de-a1-u01-l020',20,'Arbeit und Berufe - Work and Jobs','Professions and no-article rule','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

-- ─── Link lesson plans → lessons ─────────────────────────────────────────────

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000006' WHERE stable_ref = 'de-a1-u01-l006' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000007' WHERE stable_ref = 'de-a1-u01-l007' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000008' WHERE stable_ref = 'de-a1-u01-l008' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000009' WHERE stable_ref = 'de-a1-u01-l009' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000010' WHERE stable_ref = 'de-a1-u01-l010' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000011' WHERE stable_ref = 'de-a1-u01-l011' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000012' WHERE stable_ref = 'de-a1-u01-l012' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000013' WHERE stable_ref = 'de-a1-u01-l013' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000014' WHERE stable_ref = 'de-a1-u01-l014' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000015' WHERE stable_ref = 'de-a1-u01-l015' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000016' WHERE stable_ref = 'de-a1-u01-l016' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000017' WHERE stable_ref = 'de-a1-u01-l017' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000018' WHERE stable_ref = 'de-a1-u01-l018' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000019' WHERE stable_ref = 'de-a1-u01-l019' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000020' WHERE stable_ref = 'de-a1-u01-l020' AND lesson_id IS NULL;
