-- V58: German A2 lessons 121-140

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-000000000079','de-a2-l121','Relativsätze - Relative Clauses','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000007a','de-a2-l122','Das Passiv - Passive Voice Intro','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000007b','de-a2-l123','Modalverben im Perfekt - Modal Verbs in Past','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000007c','de-a2-l124','Reflexive Verben 2 - Reflexive Verbs 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000007d','de-a2-l125','Trennbare Verben 2 - Separable Verbs 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000007e','de-a2-l126','Dativergänzungen - Dative Objects','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000007f','de-a2-l127','Präpositionen mit Dativ - Dative Prepositions','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000080','de-a2-l128','Präpositionen mit Akkusativ - Acc Prepositions','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000081','de-a2-l129','Wechselpräpositionen - Two-way Prepositions','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000082','de-a2-l130','Adjektivendungen 1 - Adjective Endings 1','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000083','de-a2-l131','Adjektivendungen 2 - Adjective Endings 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000084','de-a2-l132','Genitivkasus - Genitive Case','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000085','de-a2-l133','Indirekte Fragen - Indirect Questions','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000086','de-a2-l134','Infinitivkonstruktionen - Infinitive Constructions','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000087','de-a2-l135','Temporalangaben - Time Expressions 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000088','de-a2-l136','Wohnen und Leben - Living Arrangements','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000089','de-a2-l137','Umwelt und Natur - Environment','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000008a','de-a2-l138','Politik und Gesellschaft - Politics Society','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000008b','de-a2-l139','Medien und Nachrichten - Media and News','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000008c','de-a2-l140','Technologie im Alltag - Everyday Technology','language','de','A2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000079',1,'APPROVED','PUBLISHED',
'{"objectives":["Use relative clauses","Use der/die/das as relative pronouns","Describe nouns with relative clauses"],"explanation":{"intro":"Relative clauses allow you to add information about a noun within a sentence. German relative pronouns look like definite articles but behave as subordinating conjunctions.","culturalNote":"Relative clauses are common in all levels of German, from simple descriptions to complex journalism. They allow much richer description than simple sentences."},"examples":[{"german":"Das ist der Mann, der mir geholfen hat.","english":"That is the man who helped me."},{"german":"Ich kaufe das Buch, das du empfohlen hast.","english":"I am buying the book that you recommended."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use relative clauses to describe nouns."}}',
'{"items":[{"word":"der/die/das","translation":"who/which/that (rel. pronoun)","pronunciation":"dayr/dee/dahs","example":"Der Mann, der..."},{"word":"empfehlen","translation":"to recommend","pronunciation":"emp-FEY-len","example":"Ich empfehle es."},{"word":"welcher/welche/welches","translation":"which (rel. pronoun alt.)","pronunciation":"VEL-kher/VEL-kheh/VEL-khes","example":"Das Buch, welches..."},{"word":"den/die/das","translation":"whom/which (acc. rel.)","pronunciation":"DEN/DEE/DAHS","example":"Den Mann, den ich sehe."},{"word":"dem/der/dem","translation":"to whom/which (dat. rel.)","pronunciation":"DEM/DAYR/DEM","example":"Der Mann, dem ich half."},{"word":"beschreiben","translation":"to describe","pronunciation":"beh-SHRY-ben","example":"Beschreibe ihn."}]}',
'{"title":"Relativsatz — relative clause structure","pattern":"Noun + [comma] + relative pronoun + [subordinate clause, verb last]","explanation":"Relative pronoun agrees in gender and number with the noun it refers to. Case depends on its role in the relative clause. Der Mann, der mir geholfen hat (der = nominative, subject of helped). Das Buch, das ich lese (das = accusative, object of lese). Verb goes to end.","examples":[{"sentence":"Die Frau, die hier arbeitet, ist meine Schwester.","translation":"The woman who works here is my sister."},{"sentence":"Das Haus, das ich gekauft habe, ist groß.","translation":"The house that I bought is large."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Relative pronoun for ''der Mann'' (nominative) is?","options":["der","den","dem","des"],"correctAnswer":"der"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"That is the man who helped me.","options":["Das ist der Mann, der mir geholfen hat.","Das ist ein Mann.","Der Mann hilft mir.","Ich sehe den Mann."],"correctAnswer":"Das ist der Mann, der mir geholfen hat."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Buch, ___ du empfohlen hast, ist toll.","options":["das","die","der","den"],"correctAnswer":"das"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The woman who works here","wordBankItems":["Die","Frau",",","die","hier","arbeitet"],"correctAnswer":"Die Frau , die hier arbeitet"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"In a relative clause, where does the verb go?","options":["to the end","to the start","second position","after the pronoun"],"correctAnswer":"to the end"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000007a',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand the passive voice","Form present passive with wird","Describe processes"],"explanation":{"intro":"The passive voice describes what happens to something rather than who does it. German uses werden + past participle.","culturalNote":"Passive is very common in German official language, instructions, and news reports: Das Gebäude wird renoviert (The building is being renovated). It distances the speaker from the action."},"examples":[{"german":"Das Auto wird repariert.","english":"The car is being repaired."},{"german":"Die Tür wurde geschlossen.","english":"The door was closed."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can form and understand the present and past passive."}}',
'{"items":[{"word":"wird...gemacht","translation":"is being done (passive)","pronunciation":"VIRT...geh-MAKHT","example":"Das wird gemacht."},{"word":"wurde...gemacht","translation":"was done (passive)","pronunciation":"VOOR-deh...geh-MAKHT","example":"Das wurde gemacht."},{"word":"renovieren","translation":"to renovate","pronunciation":"reh-noh-VEER-en","example":"Das Haus wird renoviert."},{"word":"reparieren","translation":"to repair","pronunciation":"reh-pah-REER-en","example":"Das Auto wird repariert."},{"word":"von","translation":"by (agent in passive)","pronunciation":"FON","example":"Von ihm gemacht."},{"word":"das Gebäude","translation":"building","pronunciation":"dahs geh-BOY-deh","example":"Das Gebäude ist neu."}]}',
'{"title":"Passiv Präsens — wird + Partizip II","pattern":"wird (sing.) / werden (pl.) + past participle at end","explanation":"Present passive: wird/werden + participle. Das Auto wird repariert. Past passive (Präteritum): wurde/wurden + participle. Die Tür wurde geschlossen. Agent (by whom): von + dative. Das Auto wurde von dem Mechaniker repariert.","examples":[{"sentence":"Die Straße wird gebaut.","translation":"The road is being built."},{"sentence":"Das Fenster wurde repariert.","translation":"The window was repaired."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Gebäude'' means?","options":["building","structure","facility","complex"],"correctAnswer":"building"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The car is being repaired.","options":["Das Auto wird repariert.","Das Auto wurde repariert.","Ich repariere das Auto.","Das Auto ist kaputt."],"correctAnswer":"Das Auto wird repariert."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Tür ___ geschlossen.","options":["wurde","wird","worden","ist"],"correctAnswer":"wurde"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The road is being built","wordBankItems":["Die","Straße","wird","gebaut","."],"correctAnswer":"Die Straße wird gebaut ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"In passive, who/what did the action is marked with?","options":["von + dative","durch + accusative","mit + dative","für + accusative"],"correctAnswer":"von + dative"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000007b',1,'APPROVED','PUBLISHED',
'{"objectives":["Use modal verbs in the past","Form Perfekt of modal verbs","Avoid the double infinitive mistake"],"explanation":{"intro":"Modal verbs have special behaviour in the Perfekt. With a dependent infinitive, they use a double infinitive construction, not the past participle.","culturalNote":"The double infinitive (Doppelinfintiv) appears when a modal verb has a dependent verb. Ich habe kommen müssen = I had to come. This construction can be striking when first encountered."},"examples":[{"german":"Ich habe das tun müssen.","english":"I had to do that."},{"german":"Sie hat kommen können.","english":"She was able to come."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use modal verbs in the Perfekt with double infinitive."}}',
'{"items":[{"word":"müssen (Perfekt)","translation":"had to","pronunciation":"MÜS-en","example":"Ich habe müssen."},{"word":"können (Perfekt)","translation":"was able to","pronunciation":"KÖN-en","example":"Ich habe können."},{"word":"wollen (Perfekt)","translation":"wanted to","pronunciation":"VOL-en","example":"Ich habe wollen."},{"word":"dürfen (Perfekt)","translation":"was allowed to","pronunciation":"DÜR-fen","example":"Ich habe dürfen."},{"word":"der Doppelinfintiv","translation":"double infinitive","pronunciation":"dayr DOP-el-in-fin-ee-TEEF","example":"Kommen müssen."},{"word":"gemusst","translation":"had to (no dependent verb)","pronunciation":"geh-MOOST","example":"Ich habe gemusst."}]}',
'{"title":"Doppelinfintiv — modal Perfekt with dependent verb","pattern":"haben + infinitive + modal infinitive (word order: other verb before modal)","explanation":"With a dependent verb: modal uses infinitive form (müssen not gemusst). Word order: habe...kommen müssen (modal goes last). Without dependent verb: use normal past participle: Ich habe gemusst = I had to (implies it without saying what). Important distinction.","examples":[{"sentence":"Er hat nicht kommen können.","translation":"He was not able to come."},{"sentence":"Wir haben lange warten müssen.","translation":"We had to wait a long time."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Perfekt of ''können'' with dependent verb is?","options":["habe können","habe gekonnt","bin können","habe gekonnte"],"correctAnswer":"habe können"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I had to do that.","options":["Ich habe das tun müssen.","Ich musste das.","Ich habe gemusst.","Das muss ich tun."],"correctAnswer":"Ich habe das tun müssen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er hat nicht kommen ___.","options":["können","gekonnt","kann","könnte"],"correctAnswer":"können"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We had to wait a long time","wordBankItems":["Wir","haben","lange","warten","müssen","."],"correctAnswer":"Wir haben lange warten müssen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"In the double infinitive, what goes last?","options":["the modal infinitive","the main verb","haben","the participle"],"correctAnswer":"the modal infinitive"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000007c',1,'APPROVED','PUBLISHED',
'{"objectives":["Use more reflexive verbs","Know dative vs accusative reflexive","Use sich freuen, sich ärgern"],"explanation":{"intro":"Reflexive verbs with emotional meanings are common in German. They express how you feel about things. Learn a set of key emotional reflexive verbs.","culturalNote":"Emotional reflexive verbs are very natural in German. Sie ärgert mich (she annoys me) vs. Ich ärgere mich über sie (I am annoyed about/with her) show how German distinguishes active vs passive emotional responses."},"examples":[{"german":"Ich freue mich auf das Wochenende.","english":"I am looking forward to the weekend."},{"german":"Er ärgert sich über den Stau.","english":"He is annoyed about the traffic jam."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use key emotional reflexive verbs in German."}}',
'{"items":[{"word":"sich freuen auf","translation":"to look forward to","pronunciation":"zikh FROY-en owf","example":"Ich freue mich auf."},{"word":"sich ärgern über","translation":"to be annoyed about","pronunciation":"zikh ÄR-gern ü-ber","example":"Ich ärgere mich über."},{"word":"sich kümmern um","translation":"to take care of","pronunciation":"zikh KÜM-mern oom","example":"Ich kümmere mich um."},{"word":"sich irren","translation":"to be mistaken","pronunciation":"zikh EER-en","example":"Ich habe mich geirrt."},{"word":"sich beschweren","translation":"to complain","pronunciation":"zikh beh-SHVEY-ren","example":"Ich beschwere mich."},{"word":"sich erholen","translation":"to recover/recuperate","pronunciation":"zikh er-HOH-len","example":"Ich erhole mich."}]}',
'{"title":"Sich freuen auf vs. sich freuen über","pattern":"freuen auf (future anticipation) / freuen über (past/present pleasure)","explanation":"Sich freuen auf = looking forward to (future). Ich freue mich auf Weihnachten = I''m looking forward to Christmas. Sich freuen über = pleased about (present/past). Ich freue mich über dein Geschenk = I''m pleased about your gift. Auf + accusative (future), über + accusative (event).","examples":[{"sentence":"Ich freue mich über die gute Note.","translation":"I am pleased about the good grade."},{"sentence":"Wir freuen uns auf die Reise.","translation":"We are looking forward to the trip."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Sich ärgern über'' means?","options":["to be annoyed about","to be angry at","to complain about","to worry about"],"correctAnswer":"to be annoyed about"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I am looking forward to the weekend.","options":["Ich freue mich auf das Wochenende.","Ich freue mich über das Wochenende.","Das Wochenende macht mich froh.","Ich freue mich!"],"correctAnswer":"Ich freue mich auf das Wochenende."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich ärgere mich ___ den Stau.","options":["über","auf","bei","wegen"],"correctAnswer":"über"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We are looking forward to the trip","wordBankItems":["Wir","freuen","uns","auf","die","Reise","."],"correctAnswer":"Wir freuen uns auf die Reise ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Sich irren'' means?","options":["to be mistaken","to be confused","to wonder","to doubt"],"correctAnswer":"to be mistaken"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000007d',1,'APPROVED','PUBLISHED',
'{"objectives":["Learn more separable verbs","Use them in sentences and Perfekt","Know common prefix meanings"],"explanation":{"intro":"German has hundreds of separable verbs. Knowing the meanings of common prefixes helps you guess new verbs.","culturalNote":"Separable verbs are a fundamental feature of German. German learners often miss the separated prefix, which can completely change meaning: stellen vs. aufstellen vs. vorstellen vs. herstellen."},"examples":[{"german":"Ich stelle das Gerät auf.","english":"I am setting up the device."},{"german":"Wir fangen um 9 Uhr an.","english":"We start at 9 o''clock."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use a wider range of separable verbs correctly."}}',
'{"items":[{"word":"aufstellen","translation":"to set up","pronunciation":"OWF-shtel-en","example":"Das Zelt aufstellen."},{"word":"anfangen","translation":"to start/begin","pronunciation":"AN-fang-en","example":"Wir fangen an."},{"word":"aufhören","translation":"to stop/cease","pronunciation":"OWF-hö-ren","example":"Hör auf!"},{"word":"vorstellen","translation":"to introduce/imagine","pronunciation":"FOR-shtel-en","example":"Ich stelle mich vor."},{"word":"zurückkommen","translation":"to come back","pronunciation":"tsoo-RÜK-kom-en","example":"Ich komme zurück."},{"word":"weitermachen","translation":"to continue","pronunciation":"VY-ter-makh-en","example":"Machen wir weiter!"}]}',
'{"title":"Separable prefix meanings","pattern":"auf- (up/open), an- (on/start), ab- (off/away), aus- (out), vor- (before/in front), zurück- (back)","explanation":"Prefix meanings help predict verb meanings. Auf- = upward or open: aufmachen (open), aufstehen (get up). An- = beginning or attachment: anfangen (start), anrufen (call). Ab- = separation: abfahren (depart), abgeben (hand in). Aus- = out/off: ausgehen (go out), ausschalten (turn off).","examples":[{"sentence":"Mach die Tür auf!","translation":"Open the door!"},{"sentence":"Die Vorstellung fängt bald an.","translation":"The show starts soon."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Aufhören'' means?","options":["to stop","to start","to continue","to pause"],"correctAnswer":"to stop"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"We start at 9 o''clock.","options":["Wir fangen um 9 Uhr an.","Wir beginnen 9 Uhr.","Um 9 Uhr starten wir.","Wir machen weiter."],"correctAnswer":"Wir fangen um 9 Uhr an."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich stelle mich ___.","options":["vor","nach","auf","ein"],"correctAnswer":"vor"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I am coming back","wordBankItems":["Ich","komme","zurück","."],"correctAnswer":"Ich komme zurück ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Prefix ''aus-'' generally means?","options":["out/off","up","away","back"],"correctAnswer":"out/off"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000007e',1,'APPROVED','PUBLISHED',
'{"objectives":["Use verbs that take dative objects","Know common dative verbs","Use helfen, danken, gefallen correctly"],"explanation":{"intro":"Some German verbs always take dative objects, not accusative. These verbs express helping, pleasing, belonging and relating to others.","culturalNote":"Dative verbs are a common source of errors for learners. The pattern is idiomatic: Das gefällt mir (I like that — literally: that pleases to me). This person-orientation is a feature of German politeness."},"examples":[{"german":"Das Lied gefällt mir sehr gut.","english":"I like the song very much."},{"german":"Ich danke dir für deine Hilfe.","english":"I thank you for your help."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use common dative verbs correctly."}}',
'{"items":[{"word":"gefallen","translation":"to please/to like (dative verb)","pronunciation":"geh-FAL-en","example":"Das gefällt mir."},{"word":"helfen","translation":"to help (dative)","pronunciation":"HEL-fen","example":"Ich helfe dir."},{"word":"danken","translation":"to thank (dative)","pronunciation":"DANG-ken","example":"Ich danke Ihnen."},{"word":"gehören","translation":"to belong to (dative)","pronunciation":"geh-HÖ-ren","example":"Das gehört mir."},{"word":"passen","translation":"to suit/fit (dative)","pronunciation":"PAS-en","example":"Das passt mir."},{"word":"glauben","translation":"to believe (dative for person)","pronunciation":"GLOW-ben","example":"Ich glaube dir."}]}',
'{"title":"Dativverben — verbs that take dative person objects","pattern":"verb + dative person (mir/dir/ihm/ihr/uns/euch/ihnen)","explanation":"Dative verbs take a dative (not accusative) for the person involved. Das gefällt mir = That pleases me (mir = dative). Ich helfe dir = I help you (dir = dative). Common list: helfen, danken, gefallen, gehören, passen, glauben, fehlen, schmecken.","examples":[{"sentence":"Schmeckt dir das Essen?","translation":"Do you like the food? (Does the food taste good to you?)"},{"sentence":"Dieses Buch gehört meiner Mutter.","translation":"This book belongs to my mother."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das gefällt mir'' means?","options":["I like that","That is mine","That suits me","I want that"],"correctAnswer":"I like that"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I thank you for your help.","options":["Ich danke dir für deine Hilfe.","Ich helfe dir.","Vielen Dank!","Das gehört mir."],"correctAnswer":"Ich danke dir für deine Hilfe."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Buch gehört ___.","options":["mir","mich","ich","meinen"],"correctAnswer":"mir"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Does the food taste good to you?","wordBankItems":["Schmeckt","dir","das","Essen","?"],"correctAnswer":"Schmeckt dir das Essen ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Passen'' as a dative verb means?","options":["to suit/fit","to match","to work","to agree"],"correctAnswer":"to suit/fit"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000007f',1,'APPROVED','PUBLISHED',
'{"objectives":["Master dative prepositions","Use aus, bei, mit, nach, seit, von, zu, gegenüber","Practice dative case endings"],"explanation":{"intro":"Certain prepositions always take the dative case. These seven are the most common dative-only prepositions.","culturalNote":"Seit (since/for) is particularly important: Seit + dative + present tense describes an ongoing situation. Ich wohne seit zwei Jahren in Berlin = I have been living in Berlin for two years."},"examples":[{"german":"Ich komme aus Deutschland.","english":"I come from Germany."},{"german":"Ich lerne seit einem Jahr Deutsch.","english":"I have been learning German for a year."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use all seven common dative prepositions correctly."}}',
'{"items":[{"word":"seit","translation":"since/for (ongoing)","pronunciation":"TSYT","example":"Seit einem Jahr."},{"word":"gegenüber","translation":"opposite/across from","pronunciation":"GAY-gen-ü-ber","example":"Gegenüber dem Bahnhof."},{"word":"außer","translation":"except/apart from","pronunciation":"OW-ser","example":"Außer mir."},{"word":"bei","translation":"at/near/with (person''s home)","pronunciation":"BY","example":"Bei meiner Mutter."},{"word":"nach","translation":"to (cities/countries)/after","pronunciation":"NAKH","example":"Nach Deutschland."},{"word":"von","translation":"from/of/by","pronunciation":"FON","example":"Von mir."}]}',
'{"title":"Seit + present tense — ongoing situations","pattern":"seit + dative + present tense (not perfect as in English)","explanation":"Seit + present tense in German = have been doing for X time. Ich lerne seit einem Jahr Deutsch = I have been learning German for a year (still learning NOW). English uses perfect; German uses present. This is a common false friend.","examples":[{"sentence":"Er wohnt seit drei Jahren hier.","translation":"He has been living here for three years."},{"sentence":"Seit wann lernst du Deutsch?","translation":"How long have you been learning German?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Außer'' means?","options":["except/apart from","outside","beyond","other than"],"correctAnswer":"except/apart from"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have been learning German for a year.","options":["Ich lerne seit einem Jahr Deutsch.","Ich habe Deutsch gelernt.","Vor einem Jahr habe ich angefangen.","Ich lerne Deutsch seit langem."],"correctAnswer":"Ich lerne seit einem Jahr Deutsch."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich komme ___ Deutschland.","options":["aus","von","nach","bei"],"correctAnswer":"aus"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Opposite the station","wordBankItems":["Gegenüber","dem","Bahnhof","."],"correctAnswer":"Gegenüber dem Bahnhof ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Seit'' + present tense expresses?","options":["ongoing action started in the past","completed past action","future plan","current state only"],"correctAnswer":"ongoing action started in the past"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000080',1,'APPROVED','PUBLISHED',
'{"objectives":["Use accusative prepositions","Know durch, für, gegen, ohne, um","Use accusative after these prepositions"],"explanation":{"intro":"Accusative-only prepositions always take the accusative case. They are fewer in number than dative prepositions but very common.","culturalNote":"Durch (through) is used both literally and figuratively: durch den Wald (through the forest), durch Übung (through practice). Für (for) is one of the most common German prepositions."},"examples":[{"german":"Ich gehe durch den Park.","english":"I walk through the park."},{"german":"Das Geschenk ist für dich.","english":"The gift is for you."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use all five accusative prepositions correctly."}}',
'{"items":[{"word":"durch","translation":"through","pronunciation":"DOORKH","example":"Durch den Wald."},{"word":"für","translation":"for","pronunciation":"FÜR","example":"Für mich."},{"word":"gegen","translation":"against/around (time)","pronunciation":"GAY-gen","example":"Gegen 10 Uhr."},{"word":"ohne","translation":"without","pronunciation":"OH-neh","example":"Ohne mich."},{"word":"um","translation":"around/at (exact time)","pronunciation":"OOM","example":"Um 8 Uhr."},{"word":"entlang","translation":"along (follows noun)","pronunciation":"ent-LANG","example":"Den Fluss entlang."}]}',
'{"title":"Akkusativpräpositionen — the five + entlang","pattern":"durch / für / gegen / ohne / um + accusative","explanation":"These five always take accusative. Durch den Wald (not: dem). Für mich (accusative personal pronoun). Gegen + accusative: gegen den Wind (against the wind). Um + accusative: um den See (around the lake), um 8 Uhr (at 8 o''clock). Entlang follows its noun: den Fluss entlang.","examples":[{"sentence":"Ohne dich ist es langweilig.","translation":"Without you it is boring."},{"sentence":"Für wen ist das?","translation":"For whom is that?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Ohne'' means?","options":["without","except","apart from","outside"],"correctAnswer":"without"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I walk through the park.","options":["Ich gehe durch den Park.","Ich gehe im Park.","Ich laufe durch dem Park.","Der Park ist schön."],"correctAnswer":"Ich gehe durch den Park."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Geschenk ist ___ dich.","options":["für","von","mit","zu"],"correctAnswer":"für"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Without you it is boring","wordBankItems":["Ohne","dich","ist","es","langweilig","."],"correctAnswer":"Ohne dich ist es langweilig ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Gegen'' with time means?","options":["around/approximately","against","opposite","near"],"correctAnswer":"around/approximately"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000081',1,'APPROVED','PUBLISHED',
'{"objectives":["Use two-way prepositions","Know dative (location) vs accusative (movement)","Apply the Wo?/Wohin? test"],"explanation":{"intro":"Nine German prepositions can take either dative or accusative. Dative answers Wo? (where?) and accusative answers Wohin? (where to?).","culturalNote":"This dative/accusative distinction is unique to German among major European languages and is one of its most characteristic features. Native speakers absorb it naturally; learners must consciously apply the rule."},"examples":[{"german":"Das Buch liegt auf dem Tisch.","english":"The book is on the table. (Wo?)"},{"german":"Ich lege das Buch auf den Tisch.","english":"I put the book on the table. (Wohin?)"}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can correctly choose dative or accusative with two-way prepositions."}}',
'{"items":[{"word":"auf dem (dative)","translation":"on the (location)","pronunciation":"owf dem","example":"Auf dem Tisch liegen."},{"word":"auf den (accusative)","translation":"onto the (movement)","pronunciation":"owf den","example":"Auf den Tisch legen."},{"word":"liegen","translation":"to lie/be located","pronunciation":"LEE-gen","example":"Das liegt hier."},{"word":"legen","translation":"to lay/put (horizontal)","pronunciation":"LAY-gen","example":"Ich lege es hin."},{"word":"stehen","translation":"to stand/be upright","pronunciation":"SHTAY-en","example":"Das steht hier."},{"word":"stellen","translation":"to place/put (upright)","pronunciation":"SHTEL-en","example":"Ich stelle es dahin."}]}',
'{"title":"Wo? Dativ / Wohin? Akkusativ — position vs. movement","pattern":"location (wo?) → dative / direction (wohin?) → accusative","explanation":"Wo? (where/location) → dative. Das Buch liegt auf dem Tisch. Wohin? (where to/direction) → accusative. Ich lege das Buch auf den Tisch. Nine prepositions: an, auf, hinter, in, neben, über, unter, vor, zwischen. Matching pairs: liegen/legen, stehen/stellen, hängen/hängen.","examples":[{"sentence":"Das Bild hängt an der Wand.","translation":"The picture hangs on the wall. (location)"},{"sentence":"Ich hänge das Bild an die Wand.","translation":"I hang the picture on the wall. (movement)"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Wohin?'' triggers which case?","options":["accusative","dative","genitive","nominative"],"correctAnswer":"accusative"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The book is on the table.","options":["Das Buch liegt auf dem Tisch.","Das Buch liegt auf den Tisch.","Das Buch lege ich auf den Tisch.","Auf dem Tisch ist ein Buch."],"correctAnswer":"Das Buch liegt auf dem Tisch."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich lege das Buch auf ___ Tisch.","options":["den","dem","der","des"],"correctAnswer":"den"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I put it there (upright)","wordBankItems":["Ich","stelle","es","dahin","."],"correctAnswer":"Ich stelle es dahin ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Stellen'' vs ''stehen'' — which involves movement?","options":["stellen","stehen","both","neither"],"correctAnswer":"stellen"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000082',1,'APPROVED','PUBLISHED',
'{"objectives":["Use adjective endings after definite articles","Apply the weak declension","Build noun phrases correctly"],"explanation":{"intro":"Adjective endings are one of the most complex parts of German grammar. Start with adjectives after the definite article (the) — this is the weak declension.","culturalNote":"German adjective endings encode a lot of grammatical information. While complex, they are acquired gradually through exposure. Reading German texts is the best way to absorb them naturally."},"examples":[{"german":"Der alte Mann ist freundlich.","english":"The old man is friendly."},{"german":"Die rote Tasche ist teuer.","english":"The red bag is expensive."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use adjective endings after definite articles correctly."}}',
'{"items":[{"word":"der alte Mann","translation":"the old man","pronunciation":"dayr AL-teh MAN","example":"Der alte Mann."},{"word":"die rote Tasche","translation":"the red bag","pronunciation":"dee ROH-teh TAH-sheh","example":"Die rote Tasche."},{"word":"das neue Auto","translation":"the new car","pronunciation":"dahs NOY-eh OW-toh","example":"Das neue Auto."},{"word":"den alten Mann","translation":"the old man (acc.)","pronunciation":"den AL-ten MAN","example":"Ich sehe den alten Mann."},{"word":"der roten Tasche","translation":"of/with the red bag (gen/dat)","pronunciation":"dayr ROH-ten TAH-sheh","example":"Mit der roten Tasche."},{"word":"stark","translation":"strong","pronunciation":"SHTARK","example":"Ein starker Mann."}]}',
'{"title":"Schwache Adjektivdeklination — after der/die/das","pattern":"-e in nominative (all genders) / -en everywhere else","explanation":"After definite articles: nominative singular = -e (der alte, die rote, das neue). Accusative masculine = -en (den alten). All dative = -en. All genitive = -en. Plural all cases = -en. Simplify: -e in nominative (singular), -en everywhere else.","examples":[{"sentence":"Ich sehe die alte Kirche.","translation":"I see the old church. (acc. feminine = -e)"},{"sentence":"Mit dem alten Mann.","translation":"With the old man. (dative = -en)"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Adjective ending after ''die'' (nominative feminine) is?","options":["-e","-en","-er","-es"],"correctAnswer":"-e"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The red bag is expensive.","options":["Die rote Tasche ist teuer.","Die roten Tasche ist teuer.","Das rote Tasche ist teuer.","Der rote Tasche ist teuer."],"correctAnswer":"Die rote Tasche ist teuer."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich sehe den alt___ Mann.","options":["en","e","er","em"],"correctAnswer":"en"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The new car is fast","wordBankItems":["Das","neue","Auto","ist","schnell","."],"correctAnswer":"Das neue Auto ist schnell ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"After definite article, adjective ending in dative is?","options":["-en","-e","-er","-es"],"correctAnswer":"-en"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000083',1,'APPROVED','PUBLISHED',
'{"objectives":["Use adjective endings after indefinite articles","Apply the mixed declension","Compare weak vs mixed endings"],"explanation":{"intro":"After indefinite articles (ein/eine/ein) and possessives (mein/dein/sein), adjectives use the mixed declension. This adds gender information where ein alone is ambiguous."},"examples":[{"german":"Ein großer Mann steht dort.","english":"A tall man stands there."},{"german":"Meine kleine Schwester kommt.","english":"My little sister is coming."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use adjective endings after indefinite articles and possessives."}}',
'{"items":[{"word":"ein großer Mann","translation":"a tall man","pronunciation":"yn GROS-er MAN","example":"Ein großer Mann."},{"word":"eine kleine Schwester","translation":"a little sister","pronunciation":"EY-neh KLY-neh SHVES-ter","example":"Eine kleine Schwester."},{"word":"ein neues Buch","translation":"a new book","pronunciation":"yn NOY-es BOOKH","example":"Ein neues Buch."},{"word":"einen großen Mann","translation":"a tall man (acc.)","pronunciation":"EY-nen GROS-en MAN","example":"Ich sehe einen großen Mann."},{"word":"stark/starke/starker","translation":"strong (various endings)","pronunciation":"SHTARK/SHTAR-keh/SHTAR-ker","example":"Stark und klar."},{"word":"jung","translation":"young","pronunciation":"YOONG","example":"Ein junger Mann."}]}',
'{"title":"Gemischte Deklination — after ein/kein/mein","pattern":"strong endings (-er/-e/-es) in nominative where ein gives no gender info","explanation":"After ein/kein/mein: where ein has no ending (ein Mann, ein Kind), the adjective must carry the gender signal. Ein großer Mann (-er = masculine). Ein neues Buch (-es = neuter). Eine kleine Schwester (-e = feminine). In accusative masculine: einen + adjective -en. Dative always -en.","examples":[{"sentence":"Ich habe einen neuen Job.","translation":"I have a new job."},{"sentence":"Mit einem kleinen Kind.","translation":"With a small child."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Adjective after ''ein'' + masculine nom. ends in?","options":["-er","-e","-es","-en"],"correctAnswer":"-er"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"A tall man stands there.","options":["Ein großer Mann steht dort.","Der große Mann steht dort.","Ein große Mann steht dort.","Ein großen Mann."],"correctAnswer":"Ein großer Mann steht dort."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich habe einen neu___ Job.","options":["en","er","e","es"],"correctAnswer":"en"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: My little sister is coming","wordBankItems":["Meine","kleine","Schwester","kommt","."],"correctAnswer":"Meine kleine Schwester kommt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"After ''ein'' neuter nom., adjective ends in?","options":["-es","-e","-er","-en"],"correctAnswer":"-es"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000084',1,'APPROVED','PUBLISHED',
'{"objectives":["Use the genitive case","Form genitive of nouns","Use von as genitive alternative"],"explanation":{"intro":"The genitive case shows possession. In formal German, it replaces von + noun. In spoken German, von is often used instead.","culturalNote":"The genitive is in decline in spoken German — vons (von dem) is increasingly used colloquially. However, written German, formal speech and place names still use genitive freely."},"examples":[{"german":"Das Haus meines Vaters ist groß.","english":"My father''s house is big."},{"german":"Das Ende des Films war überraschend.","english":"The end of the film was surprising."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can form and use the genitive case for possession."}}',
'{"items":[{"word":"des Vaters","translation":"of the father (genitive)","pronunciation":"des FAH-ters","example":"Das Haus des Vaters."},{"word":"der Mutter","translation":"of the mother (genitive)","pronunciation":"dayr MOO-ter","example":"Das Buch der Mutter."},{"word":"überraschend","translation":"surprising","pronunciation":"ü-ber-RA-shend","example":"Sehr überraschend."},{"word":"wegen + gen.","translation":"because of (+ genitive)","pronunciation":"VAY-gen","example":"Wegen des Wetters."},{"word":"trotz + gen.","translation":"despite (+ genitive)","pronunciation":"TROTS","example":"Trotz des Regens."},{"word":"während + gen.","translation":"during (+ genitive)","pronunciation":"VÄH-rend","example":"Während des Films."}]}',
'{"title":"Genitiv — des/der/des (m/f/n)","pattern":"des + noun + -(e)s (m/n) / der + noun (f/pl) — no change needed for noun","explanation":"Masculine and neuter nouns add -s or -es in genitive: des Vaters, des Endes. Feminine and plural: no change to noun, article becomes der: der Mutter, der Kinder. Adjectives after des/der add -en. Genitive prepositions: wegen, trotz, während, statt.","examples":[{"sentence":"Trotz des Regens gehen wir spazieren.","translation":"Despite the rain we are going for a walk."},{"sentence":"Das Ende des Sommers ist traurig.","translation":"The end of summer is sad."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Genitive article for masculine nouns is?","options":["des","der","dem","den"],"correctAnswer":"des"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The end of the film was surprising.","options":["Das Ende des Films war überraschend.","Das Ende von dem Film.","Der Film hatte ein Ende.","Films Ende war toll."],"correctAnswer":"Das Ende des Films war überraschend."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Trotz ___ Regens gehen wir.","options":["des","der","dem","den"],"correctAnswer":"des"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: During the film","wordBankItems":["Während","des","Films","."],"correctAnswer":"Während des Films ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Während'' takes which case?","options":["genitive","dative","accusative","nominative"],"correctAnswer":"genitive"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000085',1,'APPROVED','PUBLISHED',
'{"objectives":["Form indirect questions","Use ob for yes/no questions","Use question words in indirect questions"],"explanation":{"intro":"Indirect questions embed a question within a sentence. They are softer and more polite than direct questions.","culturalNote":"Indirect questions are extremely polite in German: Könnten Sie mir sagen, wo der Bahnhof ist? (Could you tell me where the station is?) is much more polite than Wo ist der Bahnhof?"},"examples":[{"german":"Ich weiß nicht, wo er wohnt.","english":"I don''t know where he lives."},{"german":"Können Sie mir sagen, ob der Zug pünktlich ist?","english":"Can you tell me whether the train is on time?"}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can form and use indirect questions with ob and W-words."}}',
'{"items":[{"word":"ob","translation":"whether/if (indirect yes/no)","pronunciation":"OP","example":"Ich weiß nicht, ob..."},{"word":"Ich weiß nicht, ob...","translation":"I don''t know whether...","pronunciation":"ikh VYS nikht, OP","example":"Ich weiß nicht, ob er kommt."},{"word":"Ich frage mich, ob...","translation":"I wonder whether...","pronunciation":"ikh FRAH-geh mikh, OP","example":"Ich frage mich, ob das stimmt."},{"word":"Könnten Sie mir sagen","translation":"Could you tell me","pronunciation":"KÖN-ten zee meer ZAH-gen","example":"Könnten Sie mir sagen, wo..."},{"word":"ich bin neugierig","translation":"I am curious","pronunciation":"ikh bin NOY-geer-ikh","example":"Ich bin neugierig, ob..."},{"word":"herausfinden","translation":"to find out","pronunciation":"her-OWS-fin-den","example":"Ich möchte herausfinden."}]}',
'{"title":"Indirekte Frage — verb to the end","pattern":"W-word / ob + [subordinate clause, verb final]","explanation":"Indirect questions: W-word or ob + verb-final order. Wo wohnt er? (direct) → Ich weiß nicht, wo er wohnt (indirect — verb wohnt goes to end). Yes/no questions use ob: Ist der Zug pünktlich? → ob der Zug pünktlich ist. Ob replaces the direct question inversion.","examples":[{"sentence":"Ich frage mich, wann er kommt.","translation":"I wonder when he is coming."},{"sentence":"Wissen Sie, wo die Post ist?","translation":"Do you know where the post office is?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Ob'' introduces what type of indirect question?","options":["yes/no question","W-question","both","neither"],"correctAnswer":"yes/no question"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I don''t know where he lives.","options":["Ich weiß nicht, wo er wohnt.","Wo wohnt er?","Ich kenne ihn nicht.","Wo er wohnt, weiß ich."],"correctAnswer":"Ich weiß nicht, wo er wohnt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich frage mich, ___ das stimmt.","options":["ob","wenn","weil","das"],"correctAnswer":"ob"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Do you know where the post office is?","wordBankItems":["Wissen","Sie",",","wo","die","Post","ist","?"],"correctAnswer":"Wissen Sie , wo die Post ist ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"In indirect questions, where does the verb go?","options":["to the end","second position","unchanged","before ob/W-word"],"correctAnswer":"to the end"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000086',1,'APPROVED','PUBLISHED',
'{"objectives":["Use zu + infinitive","Form um...zu constructions","Express purpose"],"explanation":{"intro":"Infinitive constructions with zu allow you to express purpose, intentions and descriptions without a full subordinate clause.","culturalNote":"Um...zu (in order to) is very efficient — much shorter than damit + full clause. It is preferred in speaking when the subject is the same in both clauses."},"examples":[{"german":"Ich lerne Deutsch, um in Deutschland zu arbeiten.","english":"I am learning German in order to work in Germany."},{"german":"Es ist wichtig, pünktlich zu sein.","english":"It is important to be punctual."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use zu + infinitive and um...zu purpose clauses."}}',
'{"items":[{"word":"um...zu","translation":"in order to","pronunciation":"OOM...TSOO","example":"Um zu lernen."},{"word":"es ist wichtig zu","translation":"it is important to","pronunciation":"es ist VIKHT-ikh tsoo","example":"Es ist wichtig zu üben."},{"word":"versuchen zu","translation":"to try to","pronunciation":"fer-ZOOH-khen tsoo","example":"Ich versuche zu schlafen."},{"word":"vorhaben zu","translation":"to plan/intend to","pronunciation":"FOR-hah-ben tsoo","example":"Ich habe vor zu reisen."},{"word":"anfangen zu","translation":"to start to","pronunciation":"AN-fang-en tsoo","example":"Ich fange an zu laufen."},{"word":"aufhören zu","translation":"to stop doing","pronunciation":"OWF-hö-ren tsoo","example":"Hör auf zu rauchen!"}]}',
'{"title":"Um...zu — purpose infinitive","pattern":"um + [infinitive clause with zu before verb]","explanation":"Um...zu expresses purpose (in order to). The subject must be the same in both clauses. Ich lerne, um zu arbeiten. For separable verbs: zu goes between prefix and verb: um mitzukommen (in order to come along). Without um: direct infinitive after many verbs: Ich versuche zu schlafen.","examples":[{"sentence":"Er spart Geld, um ein Auto zu kaufen.","translation":"He is saving money in order to buy a car."},{"sentence":"Sie ruft an, um Bescheid zu sagen.","translation":"She is calling to let him know."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Um...zu'' expresses?","options":["purpose","condition","time","manner"],"correctAnswer":"purpose"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I am learning German in order to work in Germany.","options":["Ich lerne Deutsch, um in Deutschland zu arbeiten.","Ich lerne Deutsch, damit ich arbeite.","Ich lerne Deutsch wegen Arbeit.","Ich arbeite in Deutschland."],"correctAnswer":"Ich lerne Deutsch, um in Deutschland zu arbeiten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Es ist wichtig, pünktlich ___ sein.","options":["zu","um zu","als","wie"],"correctAnswer":"zu"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Stop smoking!","wordBankItems":["Hör","auf","zu","rauchen","!"],"correctAnswer":"Hör auf zu rauchen !"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Um...zu'' can only be used when?","options":["both clauses have the same subject","subjects differ","any time","only in formal German"],"correctAnswer":"both clauses have the same subject"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000087',1,'APPROVED','PUBLISHED',
'{"objectives":["Use advanced time expressions","Distinguish vor/nach/seit/während/als/wenn","Use als for single past events"],"explanation":{"intro":"Temporal conjunctions and prepositions are essential for storytelling and describing sequences. The distinction between als and wenn is a key A2/B1 skill.","culturalNote":"Als is used for single events in the past. Wenn for repeated or habitual events (past or present/future). Confusion between these two is a typical learner error."},"examples":[{"german":"Als ich klein war, liebte ich Süßigkeiten.","english":"When I was small, I loved sweets."},{"german":"Immer wenn es regnet, bleibe ich zu Hause.","english":"Whenever it rains, I stay at home."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can use als and wenn correctly and other temporal expressions."}}',
'{"items":[{"word":"als","translation":"when (single past event)","pronunciation":"AHLS","example":"Als ich jung war."},{"word":"immer wenn","translation":"whenever (repeated)","pronunciation":"IM-er VEN","example":"Immer wenn es regnet."},{"word":"bevor","translation":"before","pronunciation":"beh-FOR","example":"Bevor ich schlafe."},{"word":"nachdem","translation":"after","pronunciation":"NAKH-dem","example":"Nachdem ich gegessen habe."},{"word":"seitdem","translation":"since then","pronunciation":"ZYT-dem","example":"Seitdem ist alles besser."},{"word":"sobald","translation":"as soon as","pronunciation":"zo-BALT","example":"Sobald er ankommt."}]}',
'{"title":"Als vs. wenn — when in the past","pattern":"als = single past event / wenn = repeated/habitual/present/future","explanation":"Als: Ich war glücklich, als ich das erfuhr = I was happy when I found that out (once). Wenn: Wenn ich Heimweh habe, rufe ich meine Mutter an = When I feel homesick, I call my mother (always/repeated). If you can say whenever, use wenn. If it was one specific time in the past, use als.","examples":[{"sentence":"Als wir ankamen, war es schon dunkel.","translation":"When we arrived, it was already dark."},{"sentence":"Wenn ich müde bin, trinke ich Kaffee.","translation":"When I''m tired, I drink coffee."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Als'' is used for?","options":["single past event","repeated events","present","future"],"correctAnswer":"single past event"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"When I was small I loved sweets.","options":["Als ich klein war, liebte ich Süßigkeiten.","Wenn ich klein war, liebte ich Süßigkeiten.","Als Kind esse ich Süßigkeiten.","Immer wenn ich klein war."],"correctAnswer":"Als ich klein war, liebte ich Süßigkeiten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Immer ___ es regnet, bleibe ich zu Hause.","options":["wenn","als","seit","ob"],"correctAnswer":"wenn"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: As soon as he arrives","wordBankItems":["Sobald","er","ankommt","."],"correctAnswer":"Sobald er ankommt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Seitdem'' means?","options":["since then","afterwards","before that","at that time"],"correctAnswer":"since then"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000088',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss living arrangements","Talk about flatsharing","Use Wohngemeinschaft vocabulary"],"explanation":{"intro":"Housing is a major life topic. Flatsharing (WG) is extremely common among German students and young professionals.","culturalNote":"WG (Wohngemeinschaft) culture is central to German city life. Finding a WG room requires applying to the existing residents (Mitbewohner) who choose their new flatmate. WG-Gesucht.de is the main platform."},"examples":[{"german":"Ich lebe in einer WG mit drei Mitbewohnern.","english":"I live in a shared flat with three flatmates."},{"german":"Die Miete teilen wir uns zu gleichen Teilen.","english":"We split the rent equally."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss living arrangements and flatsharing in German."}}',
'{"items":[{"word":"die WG","translation":"shared flat","pronunciation":"dee VAY-GEY","example":"In einer WG wohnen."},{"word":"der Mitbewohner","translation":"flatmate","pronunciation":"dayr MIT-beh-voh-ner","example":"Meine Mitbewohner."},{"word":"teilen","translation":"to share/split","pronunciation":"TY-len","example":"Die Miete teilen."},{"word":"die Hausordnung","translation":"house rules","pronunciation":"dee HOWS-ord-noong","example":"Die Hausordnung beachten."},{"word":"das Gemeinschaftszimmer","translation":"common room","pronunciation":"dahs geh-MYNSHAFTS-tsim-mer","example":"Im Gemeinschaftszimmer."},{"word":"das Konto","translation":"bank account","pronunciation":"dahs KON-toh","example":"Ein gemeinsames Konto."}]}',
'{"title":"Zu gleichen Teilen — equal sharing expressions","pattern":"zu gleichen Teilen / halbhalb / zu dritt","explanation":"Sharing expressions: zu gleichen Teilen = in equal parts. Halbhalb (50/50). Zu zweit = the two of us. Zu dritt = the three of us. Zu viert, zu fünft etc. These are common when organising shared expenses: Wir teilen das zu gleichen Teilen = We split it equally.","examples":[{"sentence":"Wir zahlen zu dritt.","translation":"The three of us are paying."},{"sentence":"Wir teilen die Rechnung halbhalb.","translation":"We split the bill 50/50."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die WG'' stands for?","options":["Wohngemeinschaft","Wohngruppe","Wohnung","Wohnhaus"],"correctAnswer":"Wohngemeinschaft"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I live in a shared flat with three flatmates.","options":["Ich lebe in einer WG mit drei Mitbewohnern.","Ich habe drei Zimmer.","Meine Wohnung ist groß.","Ich wohne allein."],"correctAnswer":"Ich lebe in einer WG mit drei Mitbewohnern."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Wir teilen die Miete zu ___ Teilen.","options":["gleichen","gleichem","gleiche","gleiches"],"correctAnswer":"gleichen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We split the bill 50/50","wordBankItems":["Wir","teilen","die","Rechnung","halbhalb","."],"correctAnswer":"Wir teilen die Rechnung halbhalb ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Mitbewohner'' means?","options":["flatmate","neighbour","housemate","lodger"],"correctAnswer":"flatmate"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000089',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss environmental issues","Use Umwelt vocabulary","Express concern for the environment"],"explanation":{"intro":"Environmental topics are important in Germany and A2 conversation. Learn to discuss climate, recycling and sustainability.","culturalNote":"Germany is one of the world leaders in recycling (Mülltrennung) and renewable energy (Energiewende). The Green Party (die Grünen) is a major political force. Umweltbewusstsein (environmental awareness) is high."},"examples":[{"german":"Der Klimawandel ist ein großes Problem.","english":"Climate change is a big problem."},{"german":"Wir sollten mehr Energie sparen.","english":"We should save more energy."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss environmental issues in German."}}',
'{"items":[{"word":"der Klimawandel","translation":"climate change","pronunciation":"dayr KLEE-mah-van-del","example":"Gegen den Klimawandel."},{"word":"die Umwelt","translation":"environment","pronunciation":"dee OOM-velt","example":"Umwelt schützen."},{"word":"recyceln","translation":"to recycle","pronunciation":"reh-TSYK-eln","example":"Ich recycele Papier."},{"word":"der Müll","translation":"rubbish/waste","pronunciation":"dayr MÜL","example":"Müll trennen."},{"word":"die Nachhaltigkeit","translation":"sustainability","pronunciation":"dee NAKH-hal-tikh-kyt","example":"Nachhaltigkeit ist wichtig."},{"word":"schützen","translation":"to protect","pronunciation":"SHÜT-tsen","example":"Die Natur schützen."}]}',
'{"title":"Sollten — should (moral obligation)","pattern":"sollten + infinitive (should — advice/recommendation)","explanation":"Sollten is Konjunktiv II of sollen and expresses what should be done. Wir sollten mehr recyceln = We should recycle more. Man sollte die Umwelt schützen = One should protect the environment. Sollten is softer than müssen (must) and very common for advice.","examples":[{"sentence":"Man sollte weniger Plastik verwenden.","translation":"One should use less plastic."},{"sentence":"Wir sollten umweltfreundlicher leben.","translation":"We should live more environmentally friendly."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Nachhaltigkeit'' means?","options":["sustainability","conservation","ecology","recycling"],"correctAnswer":"sustainability"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"We should save more energy.","options":["Wir sollten mehr Energie sparen.","Wir müssen Energie sparen.","Wir sparen Energie.","Energie ist wichtig."],"correctAnswer":"Wir sollten mehr Energie sparen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Man ___ die Natur schützen.","options":["sollte","soll","sollten","müsste"],"correctAnswer":"sollte"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Climate change is a big problem","wordBankItems":["Der","Klimawandel","ist","ein","großes","Problem","."],"correctAnswer":"Der Klimawandel ist ein großes Problem ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Schützen'' means?","options":["to protect","to recycle","to save","to conserve"],"correctAnswer":"to protect"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000008a',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand basic political vocabulary","Talk about German political system","Use wählen and abstimmen"],"explanation":{"intro":"Basic political vocabulary helps you follow the news, vote in local elections and understand German society.","culturalNote":"Germany is a federal republic with 16 states (Bundesländer). The Bundestag is the federal parliament. Elections use a mixed proportional system. Voting is civic duty — turnout is typically 70-80%."},"examples":[{"german":"Ich gehe wählen.","english":"I am going to vote."},{"german":"Die Bundestagswahl findet alle vier Jahre statt.","english":"The federal election takes place every four years."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss basic German politics and civic topics."}}',
'{"items":[{"word":"wählen","translation":"to vote/elect","pronunciation":"VÄ-len","example":"Ich gehe wählen."},{"word":"die Wahl","translation":"election/choice","pronunciation":"dee VAHL","example":"Die Wahl ist morgen."},{"word":"die Partei","translation":"political party","pronunciation":"dee par-TY","example":"Welche Partei?"},{"word":"der Bundestag","translation":"German parliament","pronunciation":"dayr BOON-des-tahk","example":"Im Bundestag abstimmen."},{"word":"die Regierung","translation":"government","pronunciation":"dee reh-GEER-oong","example":"Die neue Regierung."},{"word":"abstimmen","translation":"to vote/cast a vote","pronunciation":"AP-shtim-en","example":"Wir stimmen ab."}]}',
'{"title":"Alle + time — every X years/months","pattern":"alle vier Jahre / alle zwei Wochen","explanation":"Alle + plural time = every X (period). Alle vier Jahre = every four years. Alle zwei Wochen = every two weeks. Alle with time expressions is very common: Die Wahl findet alle vier Jahre statt. Note: alle takes the same form regardless of gender of time noun.","examples":[{"sentence":"Der Zug fährt alle 30 Minuten.","translation":"The train runs every 30 minutes."},{"sentence":"Alle zwei Jahre gibt es einen Kongress.","translation":"Every two years there is a conference."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Regierung'' means?","options":["government","parliament","party","minister"],"correctAnswer":"government"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The federal election takes place every four years.","options":["Die Bundestagswahl findet alle vier Jahre statt.","Wir wählen alle Jahre.","Die Wahl ist bald.","Ich gehe wählen."],"correctAnswer":"Die Bundestagswahl findet alle vier Jahre statt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Zug fährt ___ 30 Minuten.","options":["alle","jedes","jeden","jeder"],"correctAnswer":"alle"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I am going to vote","wordBankItems":["Ich","gehe","wählen","."],"correctAnswer":"Ich gehe wählen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Abstimmen'' means?","options":["to vote/cast a vote","to decide","to agree","to discuss"],"correctAnswer":"to vote/cast a vote"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000008b',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand media vocabulary","Talk about news","Use berichten and melden"],"explanation":{"intro":"Media vocabulary is important for following German news and discussing current events.","culturalNote":"Germany has public broadcasters ARD and ZDF, and major private channels RTL and ProSieben. Newspapers include Süddeutsche Zeitung, Frankfurter Allgemeine Zeitung, and Die Zeit. Tagesschau is the leading TV news programme."},"examples":[{"german":"Ich lese täglich die Zeitung.","english":"I read the newspaper daily."},{"german":"Laut Nachrichten ist das Wetter schlecht.","english":"According to the news, the weather is bad."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss media and follow German news in German."}}',
'{"items":[{"word":"die Nachrichten","translation":"news (always plural)","pronunciation":"dee NAKH-rikh-ten","example":"Ich schaue Nachrichten."},{"word":"berichten","translation":"to report","pronunciation":"beh-RIKH-ten","example":"Der Reporter berichtet."},{"word":"laut","translation":"according to","pronunciation":"LOWT","example":"Laut Medien..."},{"word":"der Bericht","translation":"report","pronunciation":"dayr beh-RIKHT","example":"Ein Bericht im Fernsehen."},{"word":"die Schlagzeile","translation":"headline","pronunciation":"dee SHLAHK-tsy-leh","example":"Die Schlagzeile lesen."},{"word":"das Fernsehen","translation":"television","pronunciation":"dahs FERN-zey-en","example":"Im Fernsehen schauen."}]}',
'{"title":"Laut + noun/dative — according to","pattern":"laut + noun (no article needed): laut Medien, laut Bericht","explanation":"Laut (according to) + noun. In formal/journalism: laut Medien, laut Bericht, laut einer Studie. After laut, the noun can appear without an article (especially in headlines). Laut is used like nach in this meaning: nach Angaben der Polizei (according to police reports).","examples":[{"sentence":"Laut Prognose wird es morgen regnen.","translation":"According to forecast it will rain tomorrow."},{"sentence":"Laut Bericht ist die Situation besser.","translation":"According to the report the situation is better."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Schlagzeile'' means?","options":["headline","article","report","broadcast"],"correctAnswer":"headline"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I read the newspaper daily.","options":["Ich lese täglich die Zeitung.","Ich schaue Nachrichten.","Ich lese Berichte.","Die Zeitung ist gut."],"correctAnswer":"Ich lese täglich die Zeitung."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ Nachrichten ist das Wetter schlecht.","options":["Laut","Nach","Durch","Per"],"correctAnswer":"Laut"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: According to forecast it will rain","wordBankItems":["Laut","Prognose","wird","es","regnen","."],"correctAnswer":"Laut Prognose wird es regnen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Berichten'' means?","options":["to report","to broadcast","to announce","to read"],"correctAnswer":"to report"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000008c',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about everyday technology","Describe digital tools","Use funktionieren and einrichten"],"explanation":{"intro":"Technology vocabulary is essential in modern life. A2 builds on A1 basics to discuss more complex tech topics.","culturalNote":"Germany has high smartphone and internet penetration but is notably more cash-oriented than many countries. Kartenzahlung (card payment) is less universal than in the UK or Nordics, though improving."},"examples":[{"german":"Ich richte das Gerät ein.","english":"I am setting up the device."},{"german":"Das System ist abgestürzt.","english":"The system has crashed."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe everyday technology tasks in German."}}',
'{"items":[{"word":"einrichten","translation":"to set up/configure","pronunciation":"YN-rikh-ten","example":"Das Gerät einrichten."},{"word":"abstürzen","translation":"to crash (system)","pronunciation":"AP-shtür-tsen","example":"Das System stürzt ab."},{"word":"aktualisieren","translation":"to update","pronunciation":"ak-too-ah-lee-ZEER-en","example":"Das System aktualisieren."},{"word":"das Update","translation":"update","pronunciation":"dahs OOP-deyt","example":"Ein Update installieren."},{"word":"synchronisieren","translation":"to synchronise","pronunciation":"ZÜNH-ro-nee-ZEER-en","example":"Die Daten synchronisieren."},{"word":"der Cloud-Speicher","translation":"cloud storage","pronunciation":"dayr KLOWD-shpy-kher","example":"Im Cloud-Speicher."}]}',
'{"title":"Einrichten — separable tech verbs","pattern":"einrichten / abstürzen / ausschalten — separable tech verbs","explanation":"Many tech verbs are separable. Einrichten (set up): Ich richte das Gerät ein. Abstürzen (crash): Das System stürzt ab. Ausschalten (turn off): Ich schalte es aus. Anschalten (turn on): Ich schalte an. The prefixes ein-, ab-, aus-, an- are all separable.","examples":[{"sentence":"Ich richte das neue Handy ein.","translation":"I am setting up the new phone."},{"sentence":"Schalten Sie das Gerät aus und wieder ein.","translation":"Turn the device off and on again."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Abstürzen'' means?","options":["to crash","to fall","to fail","to stop"],"correctAnswer":"to crash"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The system has crashed.","options":["Das System ist abgestürzt.","Das System ist kaputt.","Das Gerät funktioniert nicht.","Das System stürzt ab."],"correctAnswer":"Das System ist abgestürzt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich richte das Gerät ___.","options":["ein","auf","an","ab"],"correctAnswer":"ein"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Turn the device off and on again","wordBankItems":["Schalten","Sie","das","Gerät","aus","und","wieder","ein","."],"correctAnswer":"Schalten Sie das Gerät aus und wieder ein ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Aktualisieren'' means?","options":["to update","to synchronise","to install","to restart"],"correctAnswer":"to update"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-000000000079','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l121',121,'Relativsätze - Relative Clauses','Relative clauses and pronouns','PUBLISHED'),
('dd000000-0000-0000-0000-00000000007a','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l122',122,'Passiv - Passive Voice','Present and past passive with werden','PUBLISHED'),
('dd000000-0000-0000-0000-00000000007b','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l123',123,'Modalverben Perfekt - Modal Past','Double infinitive in Perfekt','PUBLISHED'),
('dd000000-0000-0000-0000-00000000007c','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l124',124,'Reflexive Verben 2 - Reflexive 2','Emotional reflexive verbs','PUBLISHED'),
('dd000000-0000-0000-0000-00000000007d','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l125',125,'Trennbare Verben 2 - Separable 2','More separable verbs and prefix meanings','PUBLISHED'),
('dd000000-0000-0000-0000-00000000007e','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l126',126,'Dativverben - Dative Verbs','Verbs that take dative objects','PUBLISHED'),
('dd000000-0000-0000-0000-00000000007f','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l127',127,'Dativpräpositionen - Dative Prepositions','Seven dative prepositions and seit','PUBLISHED'),
('dd000000-0000-0000-0000-000000000080','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l128',128,'Akkusativpräpositionen - Acc Prepositions','Five accusative prepositions','PUBLISHED'),
('dd000000-0000-0000-0000-000000000081','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l129',129,'Wechselpräpositionen - Two-way Preps','Two-way prepositions wo vs wohin','PUBLISHED'),
('dd000000-0000-0000-0000-000000000082','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l130',130,'Adjektivendungen 1 - Adj Endings 1','Weak adjective declension after der/die/das','PUBLISHED'),
('dd000000-0000-0000-0000-000000000083','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l131',131,'Adjektivendungen 2 - Adj Endings 2','Mixed declension after ein/kein','PUBLISHED'),
('dd000000-0000-0000-0000-000000000084','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l132',132,'Genitiv - Genitive Case','Genitive possession and prepositions','PUBLISHED'),
('dd000000-0000-0000-0000-000000000085','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l133',133,'Indirekte Fragen - Indirect Questions','Ob and W-words in indirect questions','PUBLISHED'),
('dd000000-0000-0000-0000-000000000086','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l134',134,'Infinitivkonstruktionen - Infinitives','Um...zu purpose and zu-infinitive','PUBLISHED'),
('dd000000-0000-0000-0000-000000000087','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l135',135,'Temporalangaben 2 - Time Expressions 2','Als vs wenn and temporal conjunctions','PUBLISHED'),
('dd000000-0000-0000-0000-000000000088','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l136',136,'Wohnen - Living Arrangements','WG and flatsharing vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000089','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l137',137,'Umwelt - Environment','Environmental vocabulary and sollten','PUBLISHED'),
('dd000000-0000-0000-0000-00000000008a','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l138',138,'Politik - Politics','Political vocabulary and German system','PUBLISHED'),
('dd000000-0000-0000-0000-00000000008b','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l139',139,'Medien - Media','News and media vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000008c','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l140',140,'Technologie - Technology','Everyday technology and separable tech verbs','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000079' WHERE stable_ref = 'de-a2-u02-l121' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000007a' WHERE stable_ref = 'de-a2-u02-l122' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000007b' WHERE stable_ref = 'de-a2-u02-l123' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000007c' WHERE stable_ref = 'de-a2-u02-l124' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000007d' WHERE stable_ref = 'de-a2-u02-l125' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000007e' WHERE stable_ref = 'de-a2-u02-l126' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000007f' WHERE stable_ref = 'de-a2-u02-l127' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000080' WHERE stable_ref = 'de-a2-u02-l128' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000081' WHERE stable_ref = 'de-a2-u02-l129' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000082' WHERE stable_ref = 'de-a2-u02-l130' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000083' WHERE stable_ref = 'de-a2-u02-l131' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000084' WHERE stable_ref = 'de-a2-u02-l132' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000085' WHERE stable_ref = 'de-a2-u02-l133' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000086' WHERE stable_ref = 'de-a2-u02-l134' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000087' WHERE stable_ref = 'de-a2-u02-l135' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000088' WHERE stable_ref = 'de-a2-u02-l136' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000089' WHERE stable_ref = 'de-a2-u02-l137' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000008a' WHERE stable_ref = 'de-a2-u02-l138' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000008b' WHERE stable_ref = 'de-a2-u02-l139' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000008c' WHERE stable_ref = 'de-a2-u02-l140' AND lesson_id IS NULL;
