-- V59: German A2 lessons 141-160

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-00000000008d','de-a2-l141','Gesundheit 2 - Health 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000008e','de-a2-l142','Ernährung - Nutrition','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000008f','de-a2-l143','Fitness und Sport 2 - Fitness 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000090','de-a2-l144','Reisen planen - Travel Planning','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000091','de-a2-l145','Am Flughafen - At the Airport','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000092','de-a2-l146','Hotel und Unterkunft - Hotel','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000093','de-a2-l147','Restaurant 2 - Restaurant 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000094','de-a2-l148','Einkaufen 2 - Shopping 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000095','de-a2-l149','Mode und Kleidung - Fashion','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000096','de-a2-l150','Farben und Muster - Colours Patterns','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000097','de-a2-l151','Berufe 2 - Jobs 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000098','de-a2-l152','Bewerbung - Job Application','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000099','de-a2-l153','Am Arbeitsplatz - At Work','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000009a','de-a2-l154','Kollegen - Colleagues','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000009b','de-a2-l155','Besprechungen - Meetings','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000009c','de-a2-l156','Ausbildung - Vocational Training','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000009d','de-a2-l157','Universität - University','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000009e','de-a2-l158','Prüfungen - Exams','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000009f','de-a2-l159','Lernen und Studieren - Study Skills','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a0','de-a2-l160','Deutschkurs - German Class','language','de','A2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000008d',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe symptoms in detail","Use bei + dative for conditions","Talk to a doctor in German"],"explanation":{"intro":"Advanced health conversations require more specific vocabulary. A2 health language covers detailed symptom descriptions, understanding diagnoses and following medical advice.","culturalNote":"Germany has a universal healthcare system (Krankenversicherung). Most Germans have both public (gesetzlich) and sometimes private (privat) insurance. The Hausarzt (GP) is the first point of contact."},"examples":[{"german":"Ich habe Schmerzen beim Schlucken.","english":"I have pain when swallowing."},{"german":"Seit wann haben Sie diese Beschwerden?","english":"Since when have you had these complaints?"}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe health symptoms in detail and interact with a doctor."}}',
'{"items":[{"word":"die Beschwerden","translation":"complaints/symptoms (plural)","pronunciation":"dee beh-SHVEHR-den","example":"Welche Beschwerden?"},{"word":"beim Schlucken","translation":"when swallowing (bei + dem)","pronunciation":"bym SHLOOK-en","example":"Schmerzen beim Schlucken."},{"word":"verschreiben","translation":"to prescribe","pronunciation":"fer-SHRY-ben","example":"Der Arzt verschreibt."},{"word":"die Überweisung","translation":"referral","pronunciation":"dee ü-ber-VY-zoong","example":"Eine Überweisung bekommen."},{"word":"nüchtern","translation":"fasting/sober","pronunciation":"NÜK-tern","example":"Nüchtern erscheinen."},{"word":"sich bessern","translation":"to improve (health)","pronunciation":"zikh BES-ern","example":"Es bessert sich."}]}',
'{"title":"Beim + Verb-Nomen — when doing","pattern":"bei + dem → beim + gerund-noun (Schlucken, Gehen, Essen)","explanation":"Beim (bei + dem) with a nominalized verb describes a circumstance. Beim Schlucken = when swallowing / while swallowing. Beim Essen = when eating. Beim Gehen = when walking. The infinitive is capitalized as a noun. Diese Schmerzen beim Gehen = these pains when walking.","examples":[{"sentence":"Schmerzt es beim Atmen?","translation":"Does it hurt when you breathe?"},{"sentence":"Ich habe Schwindel beim Aufstehen.","translation":"I have dizziness when standing up."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Überweisung'' means?","options":["referral","prescription","receipt","diagnosis"],"correctAnswer":"referral"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have pain when swallowing.","options":["Ich habe Schmerzen beim Schlucken.","Ich schlucke schlecht.","Mein Hals tut weh.","Beim Essen habe ich Schmerzen."],"correctAnswer":"Ich habe Schmerzen beim Schlucken."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Schmerzt es ___ Atmen?","options":["beim","bei","am","im"],"correctAnswer":"beim"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I have dizziness when standing up","wordBankItems":["Ich","habe","Schwindel","beim","Aufstehen","."],"correctAnswer":"Ich habe Schwindel beim Aufstehen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Sich bessern'' means?","options":["to improve","to recover","to worsen","to stabilise"],"correctAnswer":"to improve"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000008e',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss nutrition and diet","Use gesund/ungesund vocabulary","Talk about eating habits"],"explanation":{"intro":"Nutrition vocabulary is useful for everyday conversations about food and health.","culturalNote":"Germany has strong health consciousness around Vollwertkost (wholefood eating) and organic produce (Bio). Germans spend a relatively high share of income on food and value quality over speed — fast food exists but is not the norm."},"examples":[{"german":"Ich achte auf eine gesunde Ernährung.","english":"I pay attention to a healthy diet."},{"german":"Zucker sollte man in Maßen genießen.","english":"Sugar should be enjoyed in moderation."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss nutrition and healthy eating in German."}}',
'{"items":[{"word":"die Ernährung","translation":"nutrition/diet","pronunciation":"dee er-NÄ-roong","example":"Gesunde Ernährung."},{"word":"in Maßen","translation":"in moderation","pronunciation":"in MAH-sen","example":"In Maßen genießen."},{"word":"achten auf","translation":"to pay attention to","pronunciation":"AKH-ten owf","example":"Ich achte auf..."},{"word":"das Vollkorn","translation":"wholegrain","pronunciation":"dahs FOL-korn","example":"Vollkornbrot."},{"word":"ausgewogen","translation":"balanced","pronunciation":"OWS-geh-voh-gen","example":"Ausgewogene Kost."},{"word":"das Eiweiß","translation":"protein","pronunciation":"dahs EY-vys","example":"Viel Eiweiß."}]}',
'{"title":"Man sollte — impersonal advice","pattern":"Man sollte + infinitive (one should — general advice)","explanation":"Man (one/you/people in general) + sollte gives impersonal advice. Man sollte genug schlafen = One should sleep enough. This is less direct than Sie sollten (you should) and very common in health/lifestyle advice texts. Often combined with in Maßen, regelmäßig, ausreichend.","examples":[{"sentence":"Man sollte täglich Obst essen.","translation":"One should eat fruit daily."},{"sentence":"Man sollte ausreichend Wasser trinken.","translation":"One should drink sufficient water."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Ausgewogen'' means?","options":["balanced","healthy","organic","wholesome"],"correctAnswer":"balanced"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I pay attention to a healthy diet.","options":["Ich achte auf eine gesunde Ernährung.","Ich esse gesund.","Meine Ernährung ist gut.","Ich ernähre mich gesund."],"correctAnswer":"Ich achte auf eine gesunde Ernährung."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Man ___ täglich Obst essen.","options":["sollte","soll","sollten","müsste"],"correctAnswer":"sollte"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: One should drink sufficient water","wordBankItems":["Man","sollte","ausreichend","Wasser","trinken","."],"correctAnswer":"Man sollte ausreichend Wasser trinken ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''In Maßen'' means?","options":["in moderation","in portions","in small amounts","in large quantities"],"correctAnswer":"in moderation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000008f',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about fitness goals","Use regelmäßig and workout vocabulary","Discuss exercise routines"],"explanation":{"intro":"Sport and fitness vocabulary is useful for A2 social conversation. Germans are active with cycling, hiking and football being very popular.","culturalNote":"Vereine (clubs) are central to German sports culture. Most Germans belong to at least one Verein — whether for football, gymnastics (Turnen), or hiking. Mitglied werden im Verein (becoming a member of a club) is a social institution."},"examples":[{"german":"Ich trainiere dreimal pro Woche.","english":"I train three times a week."},{"german":"Ich möchte abnehmen und fitter werden.","english":"I want to lose weight and get fitter."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss fitness goals and training routines in German."}}',
'{"items":[{"word":"trainieren","translation":"to train/work out","pronunciation":"trah-NEE-ren","example":"Ich trainiere täglich."},{"word":"abnehmen","translation":"to lose weight","pronunciation":"AP-neh-men","example":"Ich möchte abnehmen."},{"word":"zunehmen","translation":"to gain weight","pronunciation":"TSOO-neh-men","example":"Nicht zunehmen."},{"word":"der Muskel","translation":"muscle","pronunciation":"dayr MOOS-kel","example":"Muskeln aufbauen."},{"word":"die Ausdauer","translation":"endurance","pronunciation":"dee OWS-dow-er","example":"Ausdauer trainieren."},{"word":"das Ziel","translation":"goal","pronunciation":"dahs TSEEL","example":"Mein Fitnessziel."}]}',
'{"title":"Dreimal pro Woche — frequency expressions","pattern":"number + -mal + pro + time period","explanation":"Dreimal pro Woche (three times a week). Einmal täglich (once daily). Zweimal im Monat (twice a month). Pro (per) + time period is the most common structure. Mal (time/instance) combines with numbers: einmal, zweimal, dreimal, viermal, fünfmal, etc.","examples":[{"sentence":"Ich jogge viermal die Woche.","translation":"I jog four times a week."},{"sentence":"Wir schwimmen einmal pro Monat.","translation":"We swim once a month."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Ausdauer'' means?","options":["endurance","stamina","flexibility","strength"],"correctAnswer":"endurance"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I train three times a week.","options":["Ich trainiere dreimal pro Woche.","Ich trainiere viel.","Dreimal in der Woche trainiere ich.","Ich gehe dreimal ins Gym."],"correctAnswer":"Ich trainiere dreimal pro Woche."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich möchte ___ und fitter werden.","options":["abnehmen","zunehmen","trainieren","laufen"],"correctAnswer":"abnehmen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We swim once a month","wordBankItems":["Wir","schwimmen","einmal","pro","Monat","."],"correctAnswer":"Wir schwimmen einmal pro Monat ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Zunehmen'' means?","options":["to gain weight","to lose weight","to maintain weight","to exercise"],"correctAnswer":"to gain weight"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000090',1,'APPROVED','PUBLISHED',
'{"objectives":["Plan a trip in German","Book accommodation and transport","Discuss travel preferences"],"explanation":{"intro":"Travel planning vocabulary is a practical A2 topic. Germany has excellent public transport and many popular destinations.","culturalNote":"Germans are enthusiastic travellers. Urlaub (holiday) is very valued — Germans get 20-30+ days annual leave. Reiserücktrittsversicherung (travel cancellation insurance) shows how serious they take trip planning."},"examples":[{"german":"Ich möchte eine Reise nach München buchen.","english":"I would like to book a trip to Munich."},{"german":"Wir reisen mit dem Zug.","english":"We are travelling by train."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can plan and discuss a trip in German."}}',
'{"items":[{"word":"buchen","translation":"to book","pronunciation":"BOO-khen","example":"Einen Flug buchen."},{"word":"die Unterkunft","translation":"accommodation","pronunciation":"dee OON-ter-koonft","example":"Unterkunft suchen."},{"word":"der Reiseführer","translation":"travel guide/guidebook","pronunciation":"dayr RY-zeh-FÜ-rer","example":"Im Reiseführer lesen."},{"word":"die Sehenswürdigkeit","translation":"sight/tourist attraction","pronunciation":"dee ZEY-ens-vür-dikh-kyt","example":"Sehenswürdigkeiten besuchen."},{"word":"der Urlaub","translation":"holiday/vacation","pronunciation":"dayr OOR-lowp","example":"Urlaub machen."},{"word":"die Reiserücktrittsversicherung","translation":"travel cancellation insurance","pronunciation":"dee RY-zeh-RÜK-trits-fer-zikh-roong","example":"Eine Versicherung abschließen."}]}',
'{"title":"Mit dem / mit der — transport prepositions","pattern":"mit + dem/der + transport: mit dem Zug, mit dem Flugzeug, mit der U-Bahn","explanation":"Mit + dative for mode of transport. Mit dem Zug (train), mit dem Bus (bus), mit dem Auto (car), mit dem Fahrrad (bike), mit dem Flugzeug (plane), mit der U-Bahn (underground), mit der Straßenbahn (tram). All transport nouns are masculine or feminine — Zug/Bus/Flugzeug (neuter!) = dem. U-Bahn/Straßenbahn (feminine) = der.","examples":[{"sentence":"Ich fahre mit dem Fahrrad zur Arbeit.","translation":"I cycle to work."},{"sentence":"Sie fliegen mit dem Flugzeug nach Berlin.","translation":"They are flying to Berlin."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Sehenswürdigkeit'' means?","options":["tourist attraction","landmark","monument","sightseeing"],"correctAnswer":"tourist attraction"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"We are travelling by train.","options":["Wir reisen mit dem Zug.","Wir fahren Zug.","Mit dem Zug fahren wir.","Wir nehmen den Zug."],"correctAnswer":"Wir reisen mit dem Zug."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Sie fliegen ___ dem Flugzeug nach Berlin.","options":["mit","auf","in","per"],"correctAnswer":"mit"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I would like to book a trip to Munich","wordBankItems":["Ich","möchte","eine","Reise","nach","München","buchen","."],"correctAnswer":"Ich möchte eine Reise nach München buchen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"U-Bahn is which gender?","options":["feminine","masculine","neuter","variable"],"correctAnswer":"feminine"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000091',1,'APPROVED','PUBLISHED',
'{"objectives":["Navigate an airport in German","Understand flight announcements","Handle check-in and boarding"],"explanation":{"intro":"Airport vocabulary is practical for travel. Key phrases for check-in, security and boarding are useful to know.","culturalNote":"Frankfurt Airport (FRA) is Germany''s largest and Europe''s fourth-busiest hub. Munich (MUC) is second. Note: German airports use Terminal and Gate just like English; Abflug = departures, Ankunft = arrivals."},"examples":[{"german":"Mein Flug geht um 14:30 Uhr ab.","english":"My flight departs at 14:30."},{"german":"Wo ist das Abfertigungsschalter?","english":"Where is the check-in desk?"}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can navigate an airport in German."}}',
'{"items":[{"word":"der Abflug","translation":"departure","pronunciation":"dayr AP-flook","example":"Abflug um 14:30."},{"word":"die Ankunft","translation":"arrival","pronunciation":"dee AN-koonft","example":"Ankunft pünktlich."},{"word":"das Handgepäck","translation":"hand luggage","pronunciation":"dahs HAND-geh-päk","example":"Handgepäck aufgeben."},{"word":"das Gepäck aufgeben","translation":"to check in luggage","pronunciation":"dahs geh-PÄK OWF-gey-ben","example":"Koffer aufgeben."},{"word":"die Sicherheitskontrolle","translation":"security check","pronunciation":"dee ZIK-her-hyts-kon-tro-leh","example":"Durch die Sicherheitskontrolle."},{"word":"das Boarding","translation":"boarding","pronunciation":"dahs BOR-ding","example":"Boarding beginnt."}]}',
'{"title":"Abgehen / ankommen — departure/arrival verbs","pattern":"Der Flug geht um ... ab / kommt um ... an","explanation":"Abgehen / abfliegen = depart. Der Flug geht um 14:30 ab. Ankommen = arrive. Das Flugzeug kommt um 17:00 an. Both are separable: geht...ab, kommt...an. Pünktlich (on time). Verspätet (delayed). Gate X: Boarding am Gate X.","examples":[{"sentence":"Das Flugzeug landet um 18:00.","translation":"The plane lands at 18:00."},{"sentence":"Mein Flug hat eine Stunde Verspätung.","translation":"My flight has a one-hour delay."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Handgepäck'' means?","options":["hand luggage","checked luggage","carry-on bag","suitcase"],"correctAnswer":"hand luggage"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"My flight departs at 14:30.","options":["Mein Flug geht um 14:30 Uhr ab.","Mein Flug fährt um 14:30.","Um 14:30 Uhr fliege ich.","Der Flug ist um 14:30."],"correctAnswer":"Mein Flug geht um 14:30 Uhr ab."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Flugzeug kommt um 17:00 ___.","options":["an","ab","auf","ein"],"correctAnswer":"an"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: My flight has a one-hour delay","wordBankItems":["Mein","Flug","hat","eine","Stunde","Verspätung","."],"correctAnswer":"Mein Flug hat eine Stunde Verspätung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Verspätet'' means?","options":["delayed","cancelled","rescheduled","early"],"correctAnswer":"delayed"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000092',1,'APPROVED','PUBLISHED',
'{"objectives":["Book a hotel","Handle hotel check-in","Discuss room preferences"],"explanation":{"intro":"Hotel vocabulary is essential for travel. A2 covers booking, check-in and dealing with problems.","culturalNote":"German hotels often ask for Ausweis (ID) at check-in. Frühstücksbuffet (breakfast buffet) is very common and often included. Zimmerservice (room service) is less common in smaller German hotels than in international chains."},"examples":[{"german":"Ich habe ein Zimmer für zwei Nächte reserviert.","english":"I have reserved a room for two nights."},{"german":"Könnte ich bitte einen ruhigeren Raum haben?","english":"Could I please have a quieter room?"}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can book and check in to a hotel in German."}}',
'{"items":[{"word":"reservieren","translation":"to reserve/book","pronunciation":"reh-zer-VEER-en","example":"Ein Zimmer reservieren."},{"word":"die Reservierung","translation":"reservation","pronunciation":"dee reh-zer-VEER-oong","example":"Meine Reservierung."},{"word":"das Einzelzimmer","translation":"single room","pronunciation":"dahs EYN-tsel-tsim-mer","example":"Ein Einzelzimmer."},{"word":"das Doppelzimmer","translation":"double room","pronunciation":"dahs DOP-el-tsim-mer","example":"Ein Doppelzimmer."},{"word":"das Frühstück inklusive","translation":"breakfast included","pronunciation":"dahs FRÜ-shtük in-kloo-ZEE-veh","example":"Mit Frühstück."},{"word":"die Rezeption","translation":"reception/front desk","pronunciation":"dee reh-tsep-TSYON","example":"An der Rezeption."}]}',
'{"title":"Könnte ich bitte — polite requests at hotel","pattern":"Könnte ich bitte + accusative object + haben?","explanation":"Könnte ich bitte... (could I please...) is the polite hotel request form. Könnte ich bitte ein ruhiges Zimmer haben? Could I please have a quiet room? Compare with Ich hätte gern... (I would like...). Both are Konjunktiv II and both are appropriate. Bitte positioned after the verb adds politeness.","examples":[{"sentence":"Könnte ich bitte die Rechnung haben?","translation":"Could I please have the bill?"},{"sentence":"Ich hätte gern ein Zimmer mit Meerblick.","translation":"I would like a room with a sea view."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Einzelzimmer'' means?","options":["single room","double room","suite","twin room"],"correctAnswer":"single room"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have reserved a room for two nights.","options":["Ich habe ein Zimmer für zwei Nächte reserviert.","Ich buche zwei Nächte.","Das Zimmer ist für zwei.","Meine Reservierung ist zwei Nächte."],"correctAnswer":"Ich habe ein Zimmer für zwei Nächte reserviert."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Könnte ich bitte die Rechnung ___?","options":["haben","bekommen","holen","nehmen"],"correctAnswer":"haben"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I would like a room with a sea view","wordBankItems":["Ich","hätte","gern","ein","Zimmer","mit","Meerblick","."],"correctAnswer":"Ich hätte gern ein Zimmer mit Meerblick ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Rezeption'' means?","options":["reception/front desk","lobby","entrance","service desk"],"correctAnswer":"reception/front desk"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000093',1,'APPROVED','PUBLISHED',
'{"objectives":["Handle complex restaurant situations","Complain politely about food","Understand a wine/drinks menu"],"explanation":{"intro":"Advanced restaurant German covers complaints, special requests and more complex ordering situations.","culturalNote":"In German restaurants, it is acceptable to send food back if it is not right — but done calmly and politely. Reklamation (complaint) is a formal right. Trinkgeld (tip) is usually 10% — left in cash, not added to card."},"examples":[{"german":"Entschuldigung, das Fleisch ist leider nicht durch.","english":"Excuse me, the meat is unfortunately not cooked through."},{"german":"Könnte ich bitte stattdessen etwas anderes bestellen?","english":"Could I please order something else instead?"}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can handle more complex restaurant situations in German."}}',
'{"items":[{"word":"nicht durch","translation":"not cooked through","pronunciation":"nikht DOORKH","example":"Das Fleisch ist nicht durch."},{"word":"stattdessen","translation":"instead","pronunciation":"SHTAT-des-en","example":"Stattdessen nehme ich."},{"word":"reklamieren","translation":"to complain (formally)","pronunciation":"reh-klah-MEER-en","example":"Ich möchte reklamieren."},{"word":"das Trinkgeld","translation":"tip","pronunciation":"dahs TRINK-gelt","example":"Trinkgeld geben."},{"word":"die Rechnung teilen","translation":"to split the bill","pronunciation":"dee REKH-noong TY-len","example":"Können wir teilen?"},{"word":"das Tagesgericht","translation":"daily special","pronunciation":"dahs TAH-ges-geh-rikht","example":"Das Tagesgericht bitte."}]}',
'{"title":"Leider — unfortunately (softening complaints)","pattern":"leider + statement (softens the complaint, shows regret)","explanation":"Leider (unfortunately) is a key politeness tool when complaining. Das Fleisch ist leider nicht durch = The meat is unfortunately not done. It signals you are not happy but are not blaming aggressively. Combine with the subjunctive: Das hätte ich mir leider anders vorgestellt = I had unfortunately imagined it differently.","examples":[{"sentence":"Das Essen ist leider kalt.","translation":"The food is unfortunately cold."},{"sentence":"Ich muss leider etwas reklamieren.","translation":"I unfortunately have to make a complaint."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Tagesgericht'' means?","options":["daily special","today''s menu","lunch dish","main course"],"correctAnswer":"daily special"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The meat is unfortunately not cooked through.","options":["Das Fleisch ist leider nicht durch.","Das Fleisch ist nicht gut.","Das Fleisch ist kalt.","Leider schmeckt es nicht."],"correctAnswer":"Das Fleisch ist leider nicht durch."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich muss leider etwas ___.","options":["reklamieren","bestellen","bezahlen","zurückgeben"],"correctAnswer":"reklamieren"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Could I please order something else instead?","wordBankItems":["Könnte","ich","bitte","stattdessen","etwas","anderes","bestellen","?"],"correctAnswer":"Könnte ich bitte stattdessen etwas anderes bestellen ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Stattdessen'' means?","options":["instead","otherwise","although","nevertheless"],"correctAnswer":"instead"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000094',1,'APPROVED','PUBLISHED',
'{"objectives":["Handle shopping complaints and returns","Compare products","Use zu + adjective constructions"],"explanation":{"intro":"Advanced shopping vocabulary covers returns, comparisons and descriptions. A2 expands on basic A1 shopping to handle real-life situations.","culturalNote":"In Germany, the right to return goods (Rückgaberecht) is strong. Within 14 days of online purchase, you can return anything without giving a reason. In-store returns require a receipt (Kassenbon/Quittung)."},"examples":[{"german":"Ich möchte diesen Pullover umtauschen.","english":"I would like to exchange this sweater."},{"german":"Das ist mir zu teuer — gibt es etwas Günstigeres?","english":"That is too expensive for me — is there something cheaper?"}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can handle returns and comparisons when shopping in German."}}',
'{"items":[{"word":"umtauschen","translation":"to exchange/swap","pronunciation":"OOM-tow-shen","example":"Ich möchte umtauschen."},{"word":"zurückgeben","translation":"to return (a purchase)","pronunciation":"tsoo-RÜK-gey-ben","example":"Ich gebe es zurück."},{"word":"die Quittung","translation":"receipt","pronunciation":"dee KVIT-oong","example":"Die Quittung bitte."},{"word":"zu teuer","translation":"too expensive","pronunciation":"tsoo TOY-er","example":"Das ist zu teuer."},{"word":"günstig","translation":"cheap/reasonable","pronunciation":"GÜN-stikh","example":"Günstiger bitte."},{"word":"der Kassenbon","translation":"till receipt","pronunciation":"dayr KAS-en-bon","example":"Den Kassenbon haben."}]}',
'{"title":"Zu + adjective — too + adjective","pattern":"Das ist mir zu + adj. (that is too...for me)","explanation":"Zu + adjective = too + adjective. Das ist zu teuer = that is too expensive. Das ist zu groß = that is too big. With dative for person: Das ist mir zu teuer = that is too expensive FOR ME (zu teuer für mich also works). Zu can also negate: Das ist nicht zu weit = that is not too far.","examples":[{"sentence":"Das Hemd ist mir zu klein.","translation":"The shirt is too small for me."},{"sentence":"Das ist nicht zu weit — wir können laufen.","translation":"That is not too far — we can walk."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Umtauschen'' means?","options":["to exchange","to return","to refund","to complain"],"correctAnswer":"to exchange"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I would like to exchange this sweater.","options":["Ich möchte diesen Pullover umtauschen.","Ich gebe den Pullover zurück.","Der Pullover passt mir nicht.","Ich möchte etwas anderes."],"correctAnswer":"Ich möchte diesen Pullover umtauschen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das ist mir zu ___.","options":["teuer","teure","teueres","teurem"],"correctAnswer":"teuer"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The shirt is too small for me","wordBankItems":["Das","Hemd","ist","mir","zu","klein","."],"correctAnswer":"Das Hemd ist mir zu klein ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Quittung'' means?","options":["receipt","invoice","refund","exchange note"],"correctAnswer":"receipt"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000095',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe clothing items","Use fashion adjectives","Talk about what to wear"],"explanation":{"intro":"Fashion vocabulary allows you to describe what people are wearing and discuss clothing preferences.","culturalNote":"German fashion terminology mixes German and English — many items keep English names (Jeans, T-Shirt, Sneaker). Kleidung is everyday vocabulary; Mode implies fashion as a concept."},"examples":[{"german":"Er trägt eine enge Jeans und ein gestreiftes Hemd.","english":"He is wearing tight jeans and a striped shirt."},{"german":"Zu welchem Anlass trägst du das?","english":"For what occasion do you wear that?"}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe clothing and discuss fashion in German."}}',
'{"items":[{"word":"eng","translation":"tight/narrow","pronunciation":"ENG","example":"Eine enge Jeans."},{"word":"gestreift","translation":"striped","pronunciation":"geh-SHTRYFT","example":"Ein gestreiftes Hemd."},{"word":"kariert","translation":"checked/plaid","pronunciation":"kah-REERT","example":"Ein kariertes Muster."},{"word":"der Anlass","translation":"occasion","pronunciation":"dayr AN-las","example":"Für welchen Anlass?"},{"word":"die Größe","translation":"size","pronunciation":"dee GRÖ-seh","example":"Welche Größe?"},{"word":"anprobieren","translation":"to try on","pronunciation":"AN-proh-beer-en","example":"Darf ich es anprobieren?"}]}',
'{"title":"Tragen — wearing vs carrying","pattern":"tragen (to wear / to carry) — context-dependent","explanation":"Tragen means both to wear (Er trägt eine Jacke = he is wearing a jacket) and to carry (Er trägt eine Tasche = he is carrying a bag). Context determines meaning. Anziehen = to put on (action). Ausziehen = to take off. Anziehen + sich (reflexive) = to get dressed.","examples":[{"sentence":"Sie trägt immer Rot — das ist ihre Lieblingsfarbe.","translation":"She always wears red — that is her favourite colour."},{"sentence":"Zieh dir die Jacke an, es ist kalt!","translation":"Put your jacket on, it''s cold!"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Gestreift'' means?","options":["striped","checked","plain","patterned"],"correctAnswer":"striped"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"He is wearing tight jeans and a striped shirt.","options":["Er trägt eine enge Jeans und ein gestreiftes Hemd.","Er hat Jeans und ein Hemd.","Sein Hemd ist gestreift.","Er zieht sich an."],"correctAnswer":"Er trägt eine enge Jeans und ein gestreiftes Hemd."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Darf ich es ___?","options":["anprobieren","tragen","anziehen","probieren"],"correctAnswer":"anprobieren"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Put your jacket on, it''s cold","wordBankItems":["Zieh","dir","die","Jacke","an",",","es","ist","kalt","!"],"correctAnswer":"Zieh dir die Jacke an , es ist kalt !"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Anziehen'' means?","options":["to put on (clothing)","to wear","to carry","to try on"],"correctAnswer":"to put on (clothing)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000096',1,'APPROVED','PUBLISHED',
'{"objectives":["Name colours and patterns","Use colour adjectives","Describe combinations"],"explanation":{"intro":"Colour vocabulary is useful everywhere — describing clothes, interiors, art and nature. Combining colours uses compound adjectives.","culturalNote":"Colours in German are sometimes compound words: dunkelblau (dark blue), hellgrün (light green). Mixing colours: Orange is both an adjective and the fruit name. Lila (purple/lilac) is indeclinable — it never adds endings."},"examples":[{"german":"Das Kleid ist dunkelblau mit weißen Punkten.","english":"The dress is dark blue with white polka dots."},{"german":"Mir gefällt Lila sehr gut.","english":"I like purple very much."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe colours and patterns precisely in German."}}',
'{"items":[{"word":"dunkelblau","translation":"dark blue","pronunciation":"DOON-kel-blau","example":"Dunkelblau ist modern."},{"word":"hellgrün","translation":"light green","pronunciation":"HEL-grün","example":"Hellgrüne Farbe."},{"word":"die Punkte","translation":"polka dots","pronunciation":"dee POONK-teh","example":"Mit weißen Punkten."},{"word":"lila","translation":"purple/lilac (indeclinable)","pronunciation":"LEE-lah","example":"Das lila Kleid."},{"word":"bunt","translation":"colourful/multi-coloured","pronunciation":"BOONT","example":"Ein buntes Muster."},{"word":"einfarbig","translation":"plain/one-coloured","pronunciation":"EYN-far-bikh","example":"Ein einfarbiges Hemd."}]}',
'{"title":"Dunkel-/hell- prefix — dark/light colours","pattern":"dunkel + colour (solid compound) / hell + colour (solid compound)","explanation":"Dunkelblau = one word. Hellgrün = one word. These are compound adjectives and inflect normally. Das dunkelblau-e Kleid → correct: das dunkelblaue Kleid. Exception: lila, rosa, orange, beige are indeclinable — they never change. Das lila Kleid, die lila Hose, ein lila Hemd (always lila, no ending).","examples":[{"sentence":"Ich mag das rosafarbene Kleid.","translation":"I like the pink dress."},{"sentence":"Die dunkelrote Wand passt gut.","translation":"The dark red wall suits well."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Bunt'' means?","options":["colourful","patterned","bright","mixed"],"correctAnswer":"colourful"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The dress is dark blue with white polka dots.","options":["Das Kleid ist dunkelblau mit weißen Punkten.","Das Kleid hat blaue Punkte.","Das dunkle Kleid ist blau.","Das Kleid gefällt mir."],"correctAnswer":"Das Kleid ist dunkelblau mit weißen Punkten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das ___ Kleid (purple — indeclinable)","options":["lila","lilane","lilas","lilaes"],"correctAnswer":"lila"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I like the dark red wall","wordBankItems":["Die","dunkelrote","Wand","gefällt","mir","."],"correctAnswer":"Die dunkelrote Wand gefällt mir ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which colour adjective is indeclinable?","options":["lila","blau","rot","grün"],"correctAnswer":"lila"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000097',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe professions in more detail","Talk about job duties","Use als + job title"],"explanation":{"intro":"A2 jobs vocabulary covers more professions and how to describe job duties and responsibilities.","culturalNote":"Germany has a dual Ausbildung (vocational training) system where apprentices split time between the workplace and Berufsschule. About 50% of young Germans go through Ausbildung, making it more respected than in many countries."},"examples":[{"german":"Ich arbeite als Ingenieur bei einer Autofirma.","english":"I work as an engineer at a car company."},{"german":"Meine Aufgaben umfassen Planung und Kontrolle.","english":"My duties include planning and control."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my profession and job duties in German."}}',
'{"items":[{"word":"als + Berufsbezeichnung","translation":"as + job title (no article!)","pronunciation":"AHLS","example":"Als Arzt arbeiten."},{"word":"umfassen","translation":"to include/encompass","pronunciation":"OOM-fas-en","example":"Meine Aufgaben umfassen."},{"word":"die Aufgabe","translation":"task/duty","pronunciation":"dee OWF-gah-beh","example":"Meine Aufgaben."},{"word":"verantwortlich für","translation":"responsible for","pronunciation":"fer-ANT-vort-likh FÜR","example":"Ich bin verantwortlich für."},{"word":"zuständig für","translation":"responsible for (in charge)","pronunciation":"TSOO-shtän-dikh FÜR","example":"Ich bin zuständig für."},{"word":"der Ingenieur","translation":"engineer","pronunciation":"dayr in-sheh-ni-ÖR","example":"Als Ingenieur tätig."}]}',
'{"title":"Als + job title — no article","pattern":"Ich arbeite als Arzt / als Lehrerin (no article before profession)","explanation":"Als (as) + profession WITHOUT article in German. Ich bin Arzt (I am a doctor). Ich arbeite als Arzt. NOT: als ein Arzt. This zero-article rule applies to professions after sein, werden, and als. Exception: with adjective = article needed: Er ist ein guter Arzt.","examples":[{"sentence":"Sie arbeitet als Programmiererin.","translation":"She works as a (computer) programmer."},{"sentence":"Er will Arzt werden.","translation":"He wants to become a doctor."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"In ''Ich arbeite als Arzt'', which article is used?","options":["no article","ein","der","einen"],"correctAnswer":"no article"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I work as an engineer at a car company.","options":["Ich arbeite als Ingenieur bei einer Autofirma.","Ich bin ein Ingenieur.","Als Ingenieur bin ich.","Ich arbeite für eine Autofirma."],"correctAnswer":"Ich arbeite als Ingenieur bei einer Autofirma."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Meine Aufgaben ___ Planung und Kontrolle.","options":["umfassen","beinhalten","haben","sind"],"correctAnswer":"umfassen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She works as a programmer","wordBankItems":["Sie","arbeitet","als","Programmiererin","."],"correctAnswer":"Sie arbeitet als Programmiererin ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Zuständig für'' means?","options":["responsible for/in charge of","involved in","working on","connected to"],"correctAnswer":"responsible for/in charge of"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000098',1,'APPROVED','PUBLISHED',
'{"objectives":["Write and understand a job application","Use formal language","Know Bewerbung vocabulary"],"explanation":{"intro":"Job application German is formal and structured. Key phrases from cover letters and CVs are useful to know.","culturalNote":"German job applications (Bewerbungen) are very formal and thorough. A Lebenslauf (CV) includes a photo, personal details and a chronological career history. A Anschreiben (cover letter) must address the specific job. Applications can run 20+ pages."},"examples":[{"german":"Ich bewerbe mich auf die ausgeschriebene Stelle als Marketingleiter.","english":"I am applying for the advertised position as Marketing Manager."},{"german":"Für Rückfragen stehe ich gerne zur Verfügung.","english":"I am available for any queries."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can read and write a basic job application in German."}}',
'{"items":[{"word":"sich bewerben auf","translation":"to apply for","pronunciation":"zikh beh-VEHR-ben owf","example":"Ich bewerbe mich auf."},{"word":"die Stelle","translation":"position/post","pronunciation":"dee SHTEL-eh","example":"Eine offene Stelle."},{"word":"der Lebenslauf","translation":"CV/résumé","pronunciation":"dayr LAY-bens-lowf","example":"Lebenslauf beifügen."},{"word":"das Anschreiben","translation":"cover letter","pronunciation":"dahs AN-shry-ben","example":"Das Anschreiben."},{"word":"zur Verfügung stehen","translation":"to be available","pronunciation":"tsoor fer-FÜ-goong SHTAY-en","example":"Ich stehe zur Verfügung."},{"word":"ausgeschrieben","translation":"advertised (for a job)","pronunciation":"OWS-geh-shree-ben","example":"Ausgeschriebene Stelle."}]}',
'{"title":"Ich bewerbe mich — reflexive application verb","pattern":"sich bewerben auf + accusative (apply for)","explanation":"Bewerben is reflexive: Ich bewerbe mich. Apply for: auf + accusative: auf die Stelle. Full: Ich bewerbe mich auf die Stelle als Lehrer. Wir möchten uns bewerben = We would like to apply. In formal context: Ich erlaube mir, mich auf... zu bewerben = I take the liberty of applying for...","examples":[{"sentence":"Sie hat sich auf mehrere Stellen beworben.","translation":"She applied for several positions."},{"sentence":"Ich bewerbe mich schriftlich.","translation":"I am applying in writing."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Anschreiben'' means?","options":["cover letter","CV","application form","reference letter"],"correctAnswer":"cover letter"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I am applying for the advertised position as Marketing Manager.","options":["Ich bewerbe mich auf die ausgeschriebene Stelle als Marketingleiter.","Ich suche eine Stelle als Marketingleiter.","Ich habe mich beworben.","Die Stelle ist ausgeschrieben."],"correctAnswer":"Ich bewerbe mich auf die ausgeschriebene Stelle als Marketingleiter."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Für Rückfragen stehe ich gerne zur ___.","options":["Verfügung","Bereitschaft","Hand","Hilfe"],"correctAnswer":"Verfügung"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She applied for several positions","wordBankItems":["Sie","hat","sich","auf","mehrere","Stellen","beworben","."],"correctAnswer":"Sie hat sich auf mehrere Stellen beworben ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Ausgeschrieben'' means in the context of jobs?","options":["advertised","available","open","posted"],"correctAnswer":"advertised"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000099',1,'APPROVED','PUBLISHED',
'{"objectives":["Use workplace vocabulary","Navigate office situations","Use bei + company"],"explanation":{"intro":"Workplace vocabulary is important for everyday professional conversations.","culturalNote":"German work culture values Pünktlichkeit (punctuality) and Zuverlässigkeit (reliability) very highly. Titles are used more formally than in English — Herr/Frau + surname is standard in many workplaces. Du vs. Sie varies by company culture."},"examples":[{"german":"Ich arbeite bei einer kleinen Firma in Hamburg.","english":"I work at a small company in Hamburg."},{"german":"Das Meeting wurde verschoben.","english":"The meeting has been postponed."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my workplace and navigate office situations in German."}}',
'{"items":[{"word":"bei einer Firma","translation":"at a company","pronunciation":"by EY-ner FIR-mah","example":"Ich arbeite bei."},{"word":"verschieben","translation":"to postpone/reschedule","pronunciation":"fer-SHEE-ben","example":"Das Meeting verschieben."},{"word":"die Abteilung","translation":"department","pronunciation":"dee AP-ty-loong","example":"In meiner Abteilung."},{"word":"das Büro","translation":"office","pronunciation":"dahs BÜ-roh","example":"Im Büro arbeiten."},{"word":"der Vorgesetzte","translation":"superior/boss","pronunciation":"dayr FOR-geh-sets-teh","example":"Mein Vorgesetzter."},{"word":"die Überstunden","translation":"overtime","pronunciation":"dee Ü-ber-shtoon-den","example":"Überstunden machen."}]}',
'{"title":"Bei + dative — at/with (employer/location)","pattern":"bei + company name or dative noun phrase","explanation":"Bei (at) is used for employers and professional locations. Ich arbeite bei BMW / bei einer Bank / bei einem kleinen Unternehmen. Different from in: in der Firma (inside the building), bei der Firma (employed by the company). Bei einem Arzt (at a doctor''s practice). Bei meiner Mutter (at my mother''s place).","examples":[{"sentence":"Er arbeitet bei einem Startup in Berlin.","translation":"He works at a startup in Berlin."},{"sentence":"Sie ist beim Bäcker in der Schlange.","translation":"She is in the queue at the baker''s."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Abteilung'' means?","options":["department","division","section","team"],"correctAnswer":"department"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I work at a small company in Hamburg.","options":["Ich arbeite bei einer kleinen Firma in Hamburg.","Ich arbeite in einer kleinen Firma.","Eine kleine Firma in Hamburg ist mein Arbeitgeber.","Ich bin bei Hamburg tätig."],"correctAnswer":"Ich arbeite bei einer kleinen Firma in Hamburg."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Meeting wurde ___.","options":["verschoben","abgesagt","vergessen","beendet"],"correctAnswer":"verschoben"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: He works at a startup in Berlin","wordBankItems":["Er","arbeitet","bei","einem","Startup","in","Berlin","."],"correctAnswer":"Er arbeitet bei einem Startup in Berlin ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Überstunden machen'' means?","options":["to work overtime","to work extra shifts","to do overtime pay","to skip work"],"correctAnswer":"to work overtime"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000009a',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about colleagues","Discuss workplace relationships","Use mit + dative for relationships"],"explanation":{"intro":"Colleague vocabulary helps you discuss your professional relationships and office dynamics.","culturalNote":"German work culture distinguishes between Arbeitskollegen (work colleagues, formal) and Freunde (friends). It is common to maintain a professional distance — many German workplace relationships only become friendships after years. Betriebsfeier (company party) is an important bonding event."},"examples":[{"german":"Ich verstehe mich gut mit meinen Kollegen.","english":"I get on well with my colleagues."},{"german":"Mein Kollege ist sehr hilfsbereit.","english":"My colleague is very helpful."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss workplace relationships and colleagues in German."}}',
'{"items":[{"word":"sich verstehen mit","translation":"to get on with","pronunciation":"zikh fer-SHTEY-en mit","example":"Ich verstehe mich gut mit."},{"word":"hilfsbereit","translation":"helpful/helpful-minded","pronunciation":"HILFS-beh-ryt","example":"Sehr hilfsbereit."},{"word":"der Kollege / die Kollegin","translation":"colleague (m/f)","pronunciation":"dayr kol-EY-geh/dee kol-EY-gin","example":"Mein Kollege."},{"word":"das Betriebsklima","translation":"work atmosphere","pronunciation":"dahs beh-TREEPS-klee-mah","example":"Gutes Betriebsklima."},{"word":"zusammenarbeiten","translation":"to work together","pronunciation":"tsoo-ZAM-en-ar-by-ten","example":"Wir arbeiten zusammen."},{"word":"die Teamarbeit","translation":"teamwork","pronunciation":"dee TEEM-ar-byt","example":"Teamarbeit schätzen."}]}',
'{"title":"Sich verstehen mit — getting along","pattern":"sich verstehen mit + dative (to get on with)","explanation":"Sich verstehen mit = to get on/along with. Ich verstehe mich gut mit ihr = I get on well with her. Gut/schlecht/prima qualifiers are common. Other relationship verbs: sich mögen (to like each other), sich streiten mit (to argue with), sich einigen mit (to agree with).","examples":[{"sentence":"Wir verstehen uns prima.","translation":"We get on brilliantly."},{"sentence":"Sie streitet sich oft mit dem Chef.","translation":"She often argues with the boss."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Hilfsbereit'' means?","options":["helpful","cooperative","friendly","reliable"],"correctAnswer":"helpful"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I get on well with my colleagues.","options":["Ich verstehe mich gut mit meinen Kollegen.","Meine Kollegen sind nett.","Ich mag meine Kollegen.","Wir arbeiten gut zusammen."],"correctAnswer":"Ich verstehe mich gut mit meinen Kollegen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Wir verstehen uns ___.","options":["prima","gut","nett","freundlich"],"correctAnswer":"prima"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She often argues with the boss","wordBankItems":["Sie","streitet","sich","oft","mit","dem","Chef","."],"correctAnswer":"Sie streitet sich oft mit dem Chef ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Betriebsklima'' means?","options":["work atmosphere","company culture","team spirit","office environment"],"correctAnswer":"work atmosphere"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000009b',1,'APPROVED','PUBLISHED',
'{"objectives":["Participate in a meeting","Use meeting phrases","Understand agenda vocabulary"],"explanation":{"intro":"Meeting vocabulary is essential for professional German. A2 level covers basic meeting participation phrases.","culturalNote":"German meetings are known for their thoroughness and structured agenda (Tagesordnung). Minutes (Protokoll) are always kept. Meetings run on time — arriving late without notice is considered very disrespectful."},"examples":[{"german":"Das Thema heute ist die neue Marketingstrategie.","english":"Today''s topic is the new marketing strategy."},{"german":"Ich hätte dazu eine Frage.","english":"I have a question about that."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can participate in a basic meeting in German."}}',
'{"items":[{"word":"die Tagesordnung","translation":"agenda","pronunciation":"dee TAH-ges-ord-noong","example":"Auf der Tagesordnung."},{"word":"das Protokoll","translation":"minutes","pronunciation":"dahs proh-toh-KOL","example":"Das Protokoll führen."},{"word":"der Tagesordnungspunkt","translation":"agenda item","pronunciation":"dayr TAH-ges-ord-noonks-poonkt","example":"Tagesordnungspunkt 3."},{"word":"das Wort ergreifen","translation":"to take the floor/speak","pronunciation":"dahs VORT er-GRY-fen","example":"Das Wort ergreifen."},{"word":"vertagen","translation":"to adjourn/postpone","pronunciation":"fer-TAH-gen","example":"Die Sitzung vertagen."},{"word":"der Beschluss","translation":"decision/resolution","pronunciation":"dayr beh-SHLOOS","example":"Einen Beschluss fassen."}]}',
'{"title":"Dazu — in relation to that","pattern":"dazu (to that/about that) — combines da + zu","explanation":"Dazu (= zu + da-pronoun) means ''in relation to/about that''. Ich hätte dazu eine Frage = I have a question about that. Dazu sage ich nichts = I have nothing to say about that. Dazu-compounds are used for abstract reference: daran (at it), davon (from it), damit (with it), dafür (for it).","examples":[{"sentence":"Dazu möchte ich etwas sagen.","translation":"I would like to say something about that."},{"sentence":"Dafür haben wir kein Budget.","translation":"We have no budget for that."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Tagesordnung'' means?","options":["agenda","schedule","programme","plan"],"correctAnswer":"agenda"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have a question about that.","options":["Ich hätte dazu eine Frage.","Ich habe eine Frage.","Was ist die Frage?","Darf ich fragen?"],"correctAnswer":"Ich hätte dazu eine Frage."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ möchte ich etwas sagen.","options":["Dazu","Dafür","Daran","Davon"],"correctAnswer":"Dazu"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We have no budget for that","wordBankItems":["Dafür","haben","wir","kein","Budget","."],"correctAnswer":"Dafür haben wir kein Budget ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Protokoll führen'' means?","options":["to take the minutes","to lead the meeting","to write the agenda","to chair the discussion"],"correctAnswer":"to take the minutes"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000009c',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand the Ausbildung system","Describe apprenticeship training","Use German vocational vocabulary"],"explanation":{"intro":"The German dual vocational training system (duales Ausbildungssystem) is unique and important to understand as a language learner.","culturalNote":"Ausbildung is highly respected in Germany — not a second-best to university. Apprentices receive a salary while training (Ausbildungsvergütung). Germany''s economic strength is largely attributed to its skilled workers (Fachkräfte) trained this way."},"examples":[{"german":"Ich mache eine Ausbildung zum Elektriker.","english":"I am doing an apprenticeship as an electrician."},{"german":"Die Ausbildung dauert drei Jahre.","english":"The apprenticeship lasts three years."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss vocational training and apprenticeships in German."}}',
'{"items":[{"word":"die Ausbildung","translation":"apprenticeship/vocational training","pronunciation":"dee OWS-bil-doong","example":"Eine Ausbildung machen."},{"word":"der Ausbildungsbetrieb","translation":"training company","pronunciation":"dayr OWS-bil-doonks-beh-treep","example":"Im Ausbildungsbetrieb."},{"word":"die Berufsschule","translation":"vocational school","pronunciation":"dee beh-ROOTS-shoo-leh","example":"In der Berufsschule."},{"word":"der Azubi","translation":"apprentice (informal)","pronunciation":"dayr AH-tsoo-bee","example":"Als Azubi arbeiten."},{"word":"die Fachkraft","translation":"skilled worker","pronunciation":"dee FAKH-kraft","example":"Eine qualifizierte Fachkraft."},{"word":"das Gesellenstück","translation":"journeyman piece","pronunciation":"dahs geh-ZEL-en-shtük","example":"Das Gesellenstück fertigen."}]}',
'{"title":"Zum/zur Ausbildung — training to become","pattern":"eine Ausbildung zum (m/n) / zur (f) + job noun","explanation":"Ich mache eine Ausbildung zum Elektriker (masculine). Zur Köchin (feminine). Note: zum = zu dem, zur = zu der. After Ausbildung, the job title is in dative. Ich lerne als Elektriker/Köchin (alternative). Duration: dauert + time: Die Ausbildung dauert zwei Jahre.","examples":[{"sentence":"Sie macht eine Ausbildung zur Bankkauffrau.","translation":"She is doing an apprenticeship as a bank clerk."},{"sentence":"Nach der Ausbildung wurde er Geselle.","translation":"After the apprenticeship he became a journeyman."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Azubi'' means?","options":["apprentice (informal)","intern","trainee","student"],"correctAnswer":"apprentice (informal)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I am doing an apprenticeship as an electrician.","options":["Ich mache eine Ausbildung zum Elektriker.","Ich lerne Elektriker.","Ich bin Elektrikerlehrling.","Ich studiere Elektrotechnik."],"correctAnswer":"Ich mache eine Ausbildung zum Elektriker."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Sie macht eine Ausbildung ___ Bankkauffrau.","options":["zur","zum","zu einer","zu"],"correctAnswer":"zur"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The apprenticeship lasts three years","wordBankItems":["Die","Ausbildung","dauert","drei","Jahre","."],"correctAnswer":"Die Ausbildung dauert drei Jahre ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Berufsschule'' means?","options":["vocational school","trade school","technical college","work school"],"correctAnswer":"vocational school"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000009d',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about university life","Use Uni vocabulary","Discuss academic subjects"],"explanation":{"intro":"University vocabulary covers enrollment, studies and campus life. Germany has many excellent universities and a strong academic tradition.","culturalNote":"German universities (Uni/Hochschulen) are mostly public and tuition-free (no fees in most states). Students pay a semester contribution (Semesterbeitrag) of €200-350. The Bologna Process brought Bachelor/Master degrees."},"examples":[{"german":"Ich studiere Informatik im dritten Semester.","english":"I am studying computer science in my third semester."},{"german":"Die Vorlesung beginnt um 8 Uhr.","english":"The lecture starts at 8 o''clock."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about university life and academic subjects in German."}}',
'{"items":[{"word":"studieren","translation":"to study (at uni)","pronunciation":"shtoo-DEER-en","example":"Ich studiere Jura."},{"word":"die Vorlesung","translation":"lecture","pronunciation":"dee FOR-lay-zoong","example":"Die Vorlesung besuchen."},{"word":"das Seminar","translation":"seminar","pronunciation":"dahs zeh-mee-NAHR","example":"Am Seminar teilnehmen."},{"word":"der Hörsaal","translation":"lecture theatre","pronunciation":"dayr HÖR-zahl","example":"Im Hörsaal sitzen."},{"word":"die Sprechstunde","translation":"office hours","pronunciation":"dee SHPREKH-shtoon-deh","example":"Sprechstunde beim Prof."},{"word":"einschreiben","translation":"to enrol","pronunciation":"YN-shry-ben","example":"An der Uni einschreiben."}]}',
'{"title":"Im + Ordinalzahl + Semester — semester number","pattern":"im ersten/zweiten/dritten/vierten... Semester","explanation":"Im dritten Semester = in the third semester. Ordinal numbers: ersten (1st), zweiten (2nd), dritten (3rd), vierten (4th), fünften (5th), sechsten (6th). Im (in + dem) + dative. Adjective in dative weak form: -en. Im siebten Semester = in the 7th semester.","examples":[{"sentence":"Er ist im vierten Semester Medizin.","translation":"He is in his fourth semester of medicine."},{"sentence":"Im ersten Semester ist alles neu.","translation":"In the first semester everything is new."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Vorlesung'' means?","options":["lecture","seminar","tutorial","class"],"correctAnswer":"lecture"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I am studying computer science in my third semester.","options":["Ich studiere Informatik im dritten Semester.","Ich lerne Informatik.","Das dritte Semester ist Informatik.","Ich studiere im Semester Informatik."],"correctAnswer":"Ich studiere Informatik im dritten Semester."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er ist im ___ Semester Medizin.","options":["vierten","vierte","vier","viertes"],"correctAnswer":"vierten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I would like to enrol at the university","wordBankItems":["Ich","möchte","mich","an","der","Uni","einschreiben","."],"correctAnswer":"Ich möchte mich an der Uni einschreiben ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Sprechstunde'' means?","options":["office hours","speaking lesson","oral exam","class time"],"correctAnswer":"office hours"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000009e',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss exams and tests","Express worry about exams","Use Prüfung vocabulary"],"explanation":{"intro":"Exam vocabulary is important for students and anyone in educational settings.","culturalNote":"German Prüfungsangst (exam anxiety) is taken seriously. The Abitur (final school exam) is very high-stakes. University exams (Klausur = written, mündliche Prüfung = oral) must be registered for in advance. Second attempts (Nachschreibetermin) are available."},"examples":[{"german":"Ich habe morgen eine schwierige Klausur.","english":"I have a difficult written exam tomorrow."},{"german":"Ich muss für die Prüfung intensiv lernen.","english":"I have to study intensively for the exam."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss exams and preparation in German."}}',
'{"items":[{"word":"die Klausur","translation":"written exam","pronunciation":"dee klow-ZOOR","example":"Die Klausur schreiben."},{"word":"die mündliche Prüfung","translation":"oral exam","pronunciation":"dee MÜND-likh-eh PRÜF-oong","example":"Mündliche Prüfung ablegen."},{"word":"durchfallen","translation":"to fail (exam)","pronunciation":"DOORKH-fal-en","example":"Die Prüfung durchfallen."},{"word":"bestehen","translation":"to pass (exam)","pronunciation":"beh-SHTEY-en","example":"Die Prüfung bestehen."},{"word":"die Prüfungsangst","translation":"exam anxiety","pronunciation":"dee PRÜF-oonks-angst","example":"Prüfungsangst haben."},{"word":"das Ergebnis","translation":"result","pronunciation":"dahs er-GAYP-nis","example":"Das Ergebnis abwarten."}]}',
'{"title":"Bestehen vs. durchfallen — pass or fail","pattern":"eine Prüfung bestehen (pass) / bei einer Prüfung durchfallen (fail)","explanation":"Bestehen = to pass: Ich habe die Prüfung bestanden. Durchfallen = to fail: Ich bin bei der Prüfung durchgefallen. Note durchfallen takes sein. Bestehen takes haben. Durch-: through-fallen = fall through (fail). Also: nicht bestehen = fail. Die Prüfung ablegen = to take an exam.","examples":[{"sentence":"Zum Glück habe ich die Klausur bestanden.","translation":"Fortunately I passed the written exam."},{"sentence":"Wenn du durchfällst, darfst du noch einmal.","translation":"If you fail, you may try once more."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Klausur'' means?","options":["written exam","oral exam","test","assessment"],"correctAnswer":"written exam"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have to study intensively for the exam.","options":["Ich muss für die Prüfung intensiv lernen.","Die Prüfung ist schwer.","Ich lerne für die Prüfung.","Die Prüfung ist morgen."],"correctAnswer":"Ich muss für die Prüfung intensiv lernen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich bin bei der Prüfung ___.","options":["durchgefallen","durchgefallen sein","nicht bestanden","gefallen"],"correctAnswer":"durchgefallen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Fortunately I passed the written exam","wordBankItems":["Zum","Glück","habe","ich","die","Klausur","bestanden","."],"correctAnswer":"Zum Glück habe ich die Klausur bestanden ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Durchfallen'' uses which auxiliary?","options":["sein","haben","werden","both"],"correctAnswer":"sein"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000009f',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe study habits","Use Lernstrategien vocabulary","Discuss what helps you learn"],"explanation":{"intro":"Study skills vocabulary is useful for language learners and students. Discussing how you learn is a natural A2 conversational topic.","culturalNote":"Germany values Lernmethodik (learning methodology). Lernkarten (flashcards), Karteikarten (index cards), and Lerngruppen (study groups) are widespread tools. Lernen lernen (learning to learn) is an actual school subject."},"examples":[{"german":"Am besten lerne ich mit Karteikarten.","english":"I learn best with flashcards."},{"german":"Ich wiederhol den Stoff vor dem Schlafen.","english":"I review the material before sleeping."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my learning habits and study methods in German."}}',
'{"items":[{"word":"die Karteikarte","translation":"flashcard/index card","pronunciation":"dee KAR-ty-kar-teh","example":"Mit Karteikarten lernen."},{"word":"wiederholen","translation":"to review/repeat","pronunciation":"vee-der-HOH-len","example":"Den Stoff wiederholen."},{"word":"der Stoff","translation":"material/content (academic)","pronunciation":"dayr SHTOF","example":"Den Stoff lernen."},{"word":"sich konzentrieren","translation":"to concentrate","pronunciation":"zikh kon-tsen-TREER-en","example":"Ich kann mich konzentrieren."},{"word":"die Lerngruppe","translation":"study group","pronunciation":"dee LERN-groo-peh","example":"In einer Lerngruppe."},{"word":"unterstreichen","translation":"to underline","pronunciation":"OON-ter-shry-khen","example":"Wichtiges unterstreichen."}]}',
'{"title":"Am besten... — best (superlative)","pattern":"Am besten / am liebsten / am schnellsten + verb phrase","explanation":"Am besten (best), am liebsten (most preferably), am schnellsten (fastest) are adverbial superlatives. Am besten lerne ich mit Musik = I learn best with music. Am liebsten esse ich Pizza = I like eating pizza most. Always: am + adjective + -sten. Exception: am liebsten uses lieb- as the base.","examples":[{"sentence":"Am schnellsten lerne ich durch Immersion.","translation":"I learn fastest through immersion."},{"sentence":"Am liebsten lerne ich morgens.","translation":"I most prefer to study in the morning."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Stoff'' in academic context means?","options":["material/content","stuff","fabric","subject"],"correctAnswer":"material/content"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I learn best with flashcards.","options":["Am besten lerne ich mit Karteikarten.","Ich lerne am besten.","Mit Karteikarten ist es gut.","Ich benutze Karteikarten."],"correctAnswer":"Am besten lerne ich mit Karteikarten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Am ___ lerne ich morgens.","options":["liebsten","liebste","lieben","am liebsten"],"correctAnswer":"liebsten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I review the material before sleeping","wordBankItems":["Ich","wiederhol","den","Stoff","vor","dem","Schlafen","."],"correctAnswer":"Ich wiederhol den Stoff vor dem Schlafen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Unterstreichen'' means?","options":["to underline","to highlight","to annotate","to mark"],"correctAnswer":"to underline"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a0',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss language learning","Talk about German class","Use Kurs vocabulary"],"explanation":{"intro":"Language learning vocabulary is meta and useful — discussing how you learn German IN German.","culturalNote":"Goethe-Institut offers A1–C2 German courses worldwide and runs official exams. Volkshochschulen (community colleges) offer affordable courses across Germany. Tandempartner (language exchange partners) are popular for practice."},"examples":[{"german":"Ich besuche einen Deutschkurs an der Volkshochschule.","english":"I attend a German class at the community college."},{"german":"Mein Kurs hat fünfzehn Teilnehmer.","english":"My class has fifteen participants."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss my language learning experience and German class in German."}}',
'{"items":[{"word":"die Volkshochschule (VHS)","translation":"community college","pronunciation":"dee FOLKS-hokh-shoo-leh","example":"An der VHS lernen."},{"word":"der Teilnehmer","translation":"participant","pronunciation":"dayr TYL-neh-mer","example":"Fünfzehn Teilnehmer."},{"word":"der Tandempartner","translation":"language exchange partner","pronunciation":"dayr TAN-dem-part-ner","example":"Mit Tandempartner sprechen."},{"word":"das Sprachniveau","translation":"language level","pronunciation":"dahs SHPRAHKH-nee-voh","example":"Mein Sprachniveau."},{"word":"Hausaufgaben machen","translation":"to do homework","pronunciation":"HOWS-owf-gah-ben MAH-khen","example":"Ich mache Hausaufgaben."},{"word":"die Aussprache","translation":"pronunciation","pronunciation":"dee OWS-shprah-kheh","example":"Aussprache üben."}]}',
'{"title":"Besuchen — to attend (a class)","pattern":"einen Kurs / eine Veranstaltung besuchen (to attend)","explanation":"Besuchen means both visit (Ich besuche meine Eltern) and attend (Ich besuche einen Kurs). Context distinguishes. Ich besuche einen Deutschkurs = I attend/go to a German class. Einen Vortrag besuchen = to attend a lecture. Difference from teilnehmen an (dative): Ich nehme an einem Kurs teil = I participate in a course.","examples":[{"sentence":"Sie besucht jeden Dienstag die Sprachschule.","translation":"She attends the language school every Tuesday."},{"sentence":"Ich nehme an einem Intensivkurs teil.","translation":"I am participating in an intensive course."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Volkshochschule'' is commonly abbreviated as?","options":["VHS","VH","VKS","VHK"],"correctAnswer":"VHS"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I attend a German class at the community college.","options":["Ich besuche einen Deutschkurs an der Volkshochschule.","Ich lerne Deutsch an der VHS.","Ich gehe zur Volkshochschule.","An der VHS ist ein Deutschkurs."],"correctAnswer":"Ich besuche einen Deutschkurs an der Volkshochschule."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich nehme an einem Intensivkurs ___.","options":["teil","an","mit","auf"],"correctAnswer":"teil"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She attends the language school every Tuesday","wordBankItems":["Sie","besucht","jeden","Dienstag","die","Sprachschule","."],"correctAnswer":"Sie besucht jeden Dienstag die Sprachschule ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Aussprache'' means?","options":["pronunciation","speaking","language","accent"],"correctAnswer":"pronunciation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-00000000008d','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l141',141,'Gesundheit 2 - Health 2','Detailed symptoms and doctor visits','PUBLISHED'),
('dd000000-0000-0000-0000-00000000008e','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l142',142,'Ernährung - Nutrition','Nutrition and healthy eating','PUBLISHED'),
('dd000000-0000-0000-0000-00000000008f','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l143',143,'Fitness 2 - Fitness 2','Fitness goals and training frequency','PUBLISHED'),
('dd000000-0000-0000-0000-000000000090','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l144',144,'Reisen - Travel Planning','Planning trips and transport','PUBLISHED'),
('dd000000-0000-0000-0000-000000000091','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l145',145,'Flughafen - Airport','Airport vocabulary and delays','PUBLISHED'),
('dd000000-0000-0000-0000-000000000092','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l146',146,'Hotel - Hotel','Hotel booking and check-in','PUBLISHED'),
('dd000000-0000-0000-0000-000000000093','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l147',147,'Restaurant 2 - Restaurant 2','Complaints and complex ordering','PUBLISHED'),
('dd000000-0000-0000-0000-000000000094','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l148',148,'Einkaufen 2 - Shopping 2','Returns and shopping complaints','PUBLISHED'),
('dd000000-0000-0000-0000-000000000095','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l149',149,'Mode - Fashion','Clothing description and fashion','PUBLISHED'),
('dd000000-0000-0000-0000-000000000096','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l150',150,'Farben - Colours','Colours patterns and descriptions','PUBLISHED'),
('dd000000-0000-0000-0000-000000000097','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l151',151,'Berufe 2 - Jobs 2','Professions and duties','PUBLISHED'),
('dd000000-0000-0000-0000-000000000098','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l152',152,'Bewerbung - Job Application','Job application vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000099','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l153',153,'Am Arbeitsplatz - At Work','Workplace vocabulary and office','PUBLISHED'),
('dd000000-0000-0000-0000-00000000009a','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l154',154,'Kollegen - Colleagues','Workplace relationships','PUBLISHED'),
('dd000000-0000-0000-0000-00000000009b','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l155',155,'Besprechungen - Meetings','Meeting participation phrases','PUBLISHED'),
('dd000000-0000-0000-0000-00000000009c','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l156',156,'Ausbildung - Vocational Training','German dual training system','PUBLISHED'),
('dd000000-0000-0000-0000-00000000009d','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l157',157,'Universität - University','University life and academic vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000009e','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l158',158,'Prüfungen - Exams','Exam vocabulary pass and fail','PUBLISHED'),
('dd000000-0000-0000-0000-00000000009f','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l159',159,'Lernen - Study Skills','Study habits and learning methods','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a0','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l160',160,'Deutschkurs - German Class','Language learning and class vocabulary','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000008d' WHERE stable_ref = 'de-a2-u02-l141' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000008e' WHERE stable_ref = 'de-a2-u02-l142' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000008f' WHERE stable_ref = 'de-a2-u02-l143' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000090' WHERE stable_ref = 'de-a2-u02-l144' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000091' WHERE stable_ref = 'de-a2-u02-l145' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000092' WHERE stable_ref = 'de-a2-u02-l146' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000093' WHERE stable_ref = 'de-a2-u02-l147' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000094' WHERE stable_ref = 'de-a2-u02-l148' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000095' WHERE stable_ref = 'de-a2-u02-l149' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000096' WHERE stable_ref = 'de-a2-u02-l150' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000097' WHERE stable_ref = 'de-a2-u02-l151' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000098' WHERE stable_ref = 'de-a2-u02-l152' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000099' WHERE stable_ref = 'de-a2-u02-l153' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000009a' WHERE stable_ref = 'de-a2-u02-l154' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000009b' WHERE stable_ref = 'de-a2-u02-l155' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000009c' WHERE stable_ref = 'de-a2-u02-l156' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000009d' WHERE stable_ref = 'de-a2-u02-l157' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000009e' WHERE stable_ref = 'de-a2-u02-l158' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000009f' WHERE stable_ref = 'de-a2-u02-l159' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a0' WHERE stable_ref = 'de-a2-u02-l160' AND lesson_id IS NULL;
