-- V60: German A2 lessons 161-180

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-0000000000a1','de-a2-l161','Freizeit - Leisure Time','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a2','de-a2-l162','Hobbys 2 - Hobbies 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a3','de-a2-l163','Musik - Music','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a4','de-a2-l164','Kino und Filme - Cinema Films','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a5','de-a2-l165','Bücher lesen - Reading Books','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a6','de-a2-l166','Feste und Feiertage - Festivals','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a7','de-a2-l167','Geburtstag - Birthday','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a8','de-a2-l168','Weihnachten - Christmas','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000a9','de-a2-l169','Silvester und Neujahr - New Year','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000aa','de-a2-l170','Ostern und Frühling - Easter Spring','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000ab','de-a2-l171','Familie 2 - Family 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000ac','de-a2-l172','Haustiere - Pets','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000ad','de-a2-l173','In der Stadt - In the City','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000ae','de-a2-l174','Auf dem Land - In the Country','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000af','de-a2-l175','Wetter 2 - Weather 2','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000b0','de-a2-l176','Jahreszeiten - Seasons','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000b1','de-a2-l177','Tiere und Natur - Animals Nature','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000b2','de-a2-l178','Deutsche Kultur - German Culture','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000b3','de-a2-l179','Stereotype und Realität - Stereotypes','language','de','A2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000b4','de-a2-l180','A2 Abschluss - A2 Completion','language','de','A2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a1',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe leisure activities","Use Freizeit vocabulary","Say what you do in your free time"],"explanation":{"intro":"Leisure time vocabulary allows you to describe hobbies, weekend activities and how you relax.","culturalNote":"Germans value their Freizeit (free time) highly and protect it carefully. Feierabend (end of the working day) is sacred — calling colleagues after hours for non-urgent work is considered intrusive."},"examples":[{"german":"In meiner Freizeit lese ich gern oder mache Sport.","english":"In my free time I like reading or doing sport."},{"german":"Am Wochenende erhole ich mich von der Arbeit.","english":"At the weekend I recover from work."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my leisure activities in German."}}',
'{"items":[{"word":"die Freizeit","translation":"free time/leisure","pronunciation":"dee FRY-tsyt","example":"In meiner Freizeit."},{"word":"der Feierabend","translation":"end of working day","pronunciation":"dayr FY-er-ah-bend","example":"Nach Feierabend."},{"word":"sich erholen","translation":"to recuperate/relax","pronunciation":"zikh er-HOH-len","example":"Ich erhole mich."},{"word":"entspannen","translation":"to relax","pronunciation":"ent-SHPAN-en","example":"Ich entspanne mich."},{"word":"der Ausgleich","translation":"balance/compensation","pronunciation":"dayr OWS-glykh","example":"Als Ausgleich zur Arbeit."},{"word":"abschalten","translation":"to switch off/unwind","pronunciation":"AP-shalt-en","example":"Nach der Arbeit abschalten."}]}',
'{"title":"In meiner Freizeit — leisure time frame","pattern":"In meiner Freizeit + verb phrase (in my free time, I...)","explanation":"In meiner Freizeit (in my free time) is the standard frame. Alternatives: Am Wochenende (at the weekend), nach der Arbeit (after work), abends (in the evenings), in den Ferien (on holiday). All can combine with gern: In meiner Freizeit lese ich gern = I like reading in my free time.","examples":[{"sentence":"Am Abend schaue ich gern Serien.","translation":"In the evenings I like watching series."},{"sentence":"In den Ferien fahren wir ans Meer.","translation":"On holiday we go to the sea."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Feierabend'' means?","options":["end of working day","evening party","free evening","holiday eve"],"correctAnswer":"end of working day"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In my free time I like reading or doing sport.","options":["In meiner Freizeit lese ich gern oder mache Sport.","Ich lese und mache Sport.","Meine Freizeit ist lang.","Ich habe viel Freizeit."],"correctAnswer":"In meiner Freizeit lese ich gern oder mache Sport."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Am Abend ___ ich gern Serien.","options":["schaue","sehe","gucke","kucke"],"correctAnswer":"schaue"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: On holiday we go to the sea","wordBankItems":["In","den","Ferien","fahren","wir","ans","Meer","."],"correctAnswer":"In den Ferien fahren wir ans Meer ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Abschalten'' figuratively means?","options":["to unwind/switch off","to turn off a device","to disconnect","to stop working"],"correctAnswer":"to unwind/switch off"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a2',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe complex hobbies","Explain why you enjoy them","Use seit with hobbies"],"explanation":{"intro":"Hobby descriptions at A2 level involve more detail — how long, how often, and why you enjoy the activity.","culturalNote":"Vereinsmitgliedschaft (club membership) is a uniquely German feature. There are ~600,000 registered clubs in Germany covering every imaginable hobby. Becoming Mitglied im Verein is a cornerstone of community life."},"examples":[{"german":"Ich spiele seit zehn Jahren Gitarre.","english":"I have been playing guitar for ten years."},{"german":"Was ich daran liebe ist, dass es entspannend ist.","english":"What I love about it is that it is relaxing."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe my hobbies in more detail in German."}}',
'{"items":[{"word":"Was ich daran liebe","translation":"What I love about it","pronunciation":"vahs ikh DAH-ran LEE-beh","example":"Was ich daran liebe ist."},{"word":"entspannend","translation":"relaxing","pronunciation":"ent-SHPAN-end","example":"Das ist entspannend."},{"word":"begeistert sein von","translation":"to be enthusiastic about","pronunciation":"beh-GYS-tert syn fon","example":"Ich bin begeistert."},{"word":"leidenschaftlich","translation":"passionately","pronunciation":"LY-den-shafft-likh","example":"Leidenschaftlich spielen."},{"word":"der Verein","translation":"club/association","pronunciation":"dayr fer-YN","example":"Im Verein mitspielen."},{"word":"beitreten","translation":"to join (a club)","pronunciation":"BY-trey-ten","example":"Einem Verein beitreten."}]}',
'{"title":"Was ich daran liebe, ist dass — embedded clause","pattern":"Was ich daran liebe, ist, dass + [subordinate clause, verb final]","explanation":"Was ich daran liebe, ist, dass... = What I love about it is that... This is a cleft sentence. Was = what (relative pronoun heading the clause). Daran = about it / at it (da-compound). That-clause follows with verb-final: dass es entspannend ist. Useful for giving reasons and expressing enthusiasm.","examples":[{"sentence":"Was mich daran reizt, ist die Kreativität.","translation":"What attracts me about it is the creativity."},{"sentence":"Das Beste daran ist, dass ich neue Leute kennenlerne.","translation":"The best thing about it is that I meet new people."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Beitreten'' means?","options":["to join","to enter","to start","to participate"],"correctAnswer":"to join"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have been playing guitar for ten years.","options":["Ich spiele seit zehn Jahren Gitarre.","Ich spielte Gitarre zehn Jahre lang.","Seit zehn Jahren lerne ich Gitarre.","Ich habe zehn Jahre Gitarre gespielt."],"correctAnswer":"Ich spiele seit zehn Jahren Gitarre."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Was ich daran liebe, ist, ___ es entspannend ist.","options":["dass","weil","ob","als"],"correctAnswer":"dass"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The best thing about it is that I meet new people","wordBankItems":["Das","Beste","daran","ist",",","dass","ich","neue","Leute","kennenlerne","."],"correctAnswer":"Das Beste daran ist , dass ich neue Leute kennenlerne ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Leidenschaftlich'' means?","options":["passionately","enthusiastically","deeply","seriously"],"correctAnswer":"passionately"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a3',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe musical tastes","Discuss instruments","Use Musikgenre vocabulary"],"explanation":{"intro":"Music is a universal topic. A2 music vocabulary covers genres, instruments and talking about concerts and favourites.","culturalNote":"Germany has a rich musical heritage — from Bach and Beethoven to Kraftwerk and Rammstein. Die Oper (opera) remains popular among all ages. Open-air music festivals like Rock am Ring draw huge crowds."},"examples":[{"german":"Ich höre am liebsten Jazz und Klassik.","english":"I like listening to jazz and classical music most."},{"german":"Ich spiele Klavier seit ich ein Kind war.","english":"I have been playing piano since I was a child."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss music preferences and instruments in German."}}',
'{"items":[{"word":"das Instrument","translation":"instrument","pronunciation":"dahs in-stroo-MENT","example":"Ein Instrument spielen."},{"word":"das Klavier","translation":"piano","pronunciation":"dahs klah-VEER","example":"Klavier spielen."},{"word":"die Geige","translation":"violin","pronunciation":"dee GY-geh","example":"Geige spielen."},{"word":"der Chor","translation":"choir","pronunciation":"dayr KOR","example":"Im Chor singen."},{"word":"das Konzert","translation":"concert/concerto","pronunciation":"dahs kon-TSERT","example":"Ins Konzert gehen."},{"word":"die Lautstärke","translation":"volume","pronunciation":"dee LOWT-shtär-keh","example":"Die Lautstärke regulieren."}]}',
'{"title":"Seit ich ein Kind war — since I was a child","pattern":"seit + ich/er/sie... + war/waren (since + past state)","explanation":"Seit + past tense: Seit ich ein Kind war = since I was a child. Seit wir in Berlin wohnen = since we have been living in Berlin (present + ongoing). When the seit-clause is in present tense, main clause also present. When seit-clause uses war/hatte (past state), the situation ended. Both forms are common.","examples":[{"sentence":"Seit er in der Band spielt, ist er glücklicher.","translation":"Since he has been playing in the band, he is happier."},{"sentence":"Seit ich klein war, liebe ich Musik.","translation":"Since I was small, I have loved music."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Geige'' means?","options":["violin","guitar","cello","fiddle"],"correctAnswer":"violin"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I like listening to jazz and classical music most.","options":["Ich höre am liebsten Jazz und Klassik.","Ich mag Jazz und Klassik.","Am liebsten ist Jazz.","Ich höre viel Musik."],"correctAnswer":"Ich höre am liebsten Jazz und Klassik."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Seit ich ein Kind ___, spiele ich Klavier.","options":["war","bin","wurde","wäre"],"correctAnswer":"war"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Since he has been in the band he is happier","wordBankItems":["Seit","er","in","der","Band","spielt",",","ist","er","glücklicher","."],"correctAnswer":"Seit er in der Band spielt , ist er glücklicher ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Chor'' means?","options":["choir","chorus","band","orchestra"],"correctAnswer":"choir"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a4',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about cinema and films","Describe film genres","Use gefällt mir / hat mir gefallen"],"explanation":{"intro":"Cinema and film vocabulary is a popular A2 conversation topic.","culturalNote":"German cinema (Kino) is popular and affordable. Deutsche Filmpreise (German Film Prizes) are prestigious. German films range from commercial comedies (Komödien) to internationally acclaimed art films. Originalfassung (OV) = original version with subtitles."},"examples":[{"german":"Der Film hat mir sehr gut gefallen.","english":"I really liked the film."},{"german":"Ich bevorzuge Dramen vor Actionfilmen.","english":"I prefer dramas to action films."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss films and cinema preferences in German."}}',
'{"items":[{"word":"das Genre","translation":"genre","pronunciation":"dahs ZHON-reh","example":"Mein Lieblingsgenre."},{"word":"das Drama","translation":"drama","pronunciation":"dahs DRAH-mah","example":"Ein gutes Drama."},{"word":"bevorzugen","translation":"to prefer","pronunciation":"beh-for-TSOO-gen","example":"Ich bevorzuge."},{"word":"der Actionfilm","translation":"action film","pronunciation":"dayr AK-tsyon-film","example":"Actionfilme schauen."},{"word":"der Regisseur","translation":"director","pronunciation":"dayr reh-zhee-SÖR","example":"Der Regisseur des Films."},{"word":"die Originalfassung","translation":"original version","pronunciation":"dee or-ee-gee-NAHL-fas-soong","example":"Im Original schauen."}]}',
'{"title":"Hat mir gefallen — past of gefallen","pattern":"hat mir gefallen (I liked it) / hat mir nicht gefallen (I didn''t like it)","explanation":"Gefallen in past: Der Film hat mir gut gefallen = I really liked the film. Uses haben + gefallen (past participle). Gefallen stays at end; mir = dative. To describe intensity: sehr gut (very much), weniger (less), überhaupt nicht (not at all). Compare: Hat dir der Film gefallen? (Did you like the film?) = Wie hat dir der Film gefallen?","examples":[{"sentence":"Das Theaterstück hat uns allen gefallen.","translation":"We all liked the play."},{"sentence":"Die Musik hat mir gar nicht gefallen.","translation":"I didn''t like the music at all."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Regisseur'' means?","options":["director","actor","producer","screenwriter"],"correctAnswer":"director"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I really liked the film.","options":["Der Film hat mir sehr gut gefallen.","Mir gefällt der Film.","Ich mochte den Film.","Der Film war gut."],"correctAnswer":"Der Film hat mir sehr gut gefallen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Musik hat mir gar nicht ___.","options":["gefallen","gefallt","gefiel","gern"],"correctAnswer":"gefallen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We all liked the play","wordBankItems":["Das","Theaterstück","hat","uns","allen","gefallen","."],"correctAnswer":"Das Theaterstück hat uns allen gefallen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Bevorzugen'' means?","options":["to prefer","to favour","to choose","to like more"],"correctAnswer":"to prefer"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a5',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss books and reading","Name literary genres","Use handeln von to describe plots"],"explanation":{"intro":"Book vocabulary is a rich topic for A2 learners. Discussing what you read and recommending books uses key grammar patterns.","culturalNote":"Germany has one of the world''s highest per-capita book-reading rates. The Frankfurt Book Fair (Frankfurter Buchmesse) is the world''s largest book fair. Libraries (Bibliotheken) are well-funded and free to join."},"examples":[{"german":"Das Buch handelt von einer Detektivin in Berlin.","english":"The book is about a female detective in Berlin."},{"german":"Ich kann dir diesen Roman wärmstens empfehlen.","english":"I can warmly recommend this novel to you."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss books and reading preferences in German."}}',
'{"items":[{"word":"handeln von","translation":"to be about","pronunciation":"HAN-deln fon","example":"Das Buch handelt von."},{"word":"der Roman","translation":"novel","pronunciation":"dayr roh-MAHN","example":"Ein spannender Roman."},{"word":"der Krimi","translation":"crime novel/thriller","pronunciation":"dayr KREE-mee","example":"Krimis lesen."},{"word":"wärmstens empfehlen","translation":"to warmly recommend","pronunciation":"VÄRM-stens emp-FEY-len","example":"Ich empfehle wärmstens."},{"word":"spannend","translation":"exciting/gripping","pronunciation":"SHPAN-end","example":"Sehr spannend."},{"word":"das Sachbuch","translation":"non-fiction book","pronunciation":"dahs ZAKH-bookh","example":"Ein interessantes Sachbuch."}]}',
'{"title":"Handeln von — to be about (plot description)","pattern":"Der Roman handelt von + dative noun","explanation":"Handeln von (to be about/deal with) + dative. Der Film handelt von einem Detektiv = The film is about a detective (einem = dative). Das Buch handelt von der Liebe = The book is about love. Alternative: Es geht um + accusative: Es geht um einen Detektiv (accusative). Both are common.","examples":[{"sentence":"Der Krimi handelt von einem Mordfall in Wien.","translation":"The crime novel is about a murder case in Vienna."},{"sentence":"Es geht um die Freundschaft zwischen zwei Kindern.","translation":"It is about the friendship between two children."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Krimi'' means?","options":["crime novel","thriller","mystery","detective story"],"correctAnswer":"crime novel"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The book is about a female detective in Berlin.","options":["Das Buch handelt von einer Detektivin in Berlin.","Das Buch ist über eine Detektivin.","Eine Detektivin in Berlin — das Buch.","Das Buch ist spannend."],"correctAnswer":"Das Buch handelt von einer Detektivin in Berlin."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Es geht ___ die Freundschaft.","options":["um","von","über","von der"],"correctAnswer":"um"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The crime novel is about a murder case in Vienna","wordBankItems":["Der","Krimi","handelt","von","einem","Mordfall","in","Wien","."],"correctAnswer":"Der Krimi handelt von einem Mordfall in Wien ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Wärmstens empfehlen'' means?","options":["to warmly recommend","to strongly advise","to highly praise","to enthusiastically promote"],"correctAnswer":"to warmly recommend"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a6',1,'APPROVED','PUBLISHED',
'{"objectives":["Name German festivals and public holidays","Describe how they are celebrated","Use stattfinden for events"],"explanation":{"intro":"German festivals and public holidays are an important cultural topic. Germany has many regional celebrations.","culturalNote":"Germany has 9-13 public holidays (Feiertage) depending on state. Catholic states like Bavaria have more. Karneval/Fasching (before Lent), Oktoberfest, and Weihnachtsmarkt (Christmas market) are internationally known."},"examples":[{"german":"Das Oktoberfest findet jedes Jahr in München statt.","english":"Oktoberfest takes place in Munich every year."},{"german":"An Weihnachten besuchen wir die Familie.","english":"At Christmas we visit the family."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss German festivals and how they are celebrated."}}',
'{"items":[{"word":"stattfinden","translation":"to take place","pronunciation":"SHTAT-fin-den","example":"Das Fest findet statt."},{"word":"der Feiertag","translation":"public holiday","pronunciation":"dayr FY-er-tahk","example":"Gesetzlicher Feiertag."},{"word":"der Weihnachtsmarkt","translation":"Christmas market","pronunciation":"dayr VY-nakhts-markt","example":"Auf dem Weihnachtsmarkt."},{"word":"das Oktoberfest","translation":"Oktoberfest","pronunciation":"dahs ok-TOH-ber-fest","example":"Zum Oktoberfest fahren."},{"word":"feiern","translation":"to celebrate","pronunciation":"FY-ern","example":"Wir feiern zusammen."},{"word":"die Tradition","translation":"tradition","pronunciation":"dee trah-deets-YOHN","example":"Eine alte Tradition."}]}',
'{"title":"Stattfinden — to take place (separable)","pattern":"findet...statt (present) / hat stattgefunden (past)","explanation":"Stattfinden = to take place. Separable: Das Konzert findet morgen statt. Past participle: hat stattgefunden. Das Festival hat letzten Sommer stattgefunden. Used for events and occurrences. Also: Die Veranstaltung findet in der Stadthalle statt = The event takes place in the town hall.","examples":[{"sentence":"Die Feier hat gestern Abend stattgefunden.","translation":"The celebration took place yesterday evening."},{"sentence":"Wann findet der Karneval statt?","translation":"When does the carnival take place?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Stattfinden'' means?","options":["to take place","to happen","to occur","to be held"],"correctAnswer":"to take place"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Oktoberfest takes place in Munich every year.","options":["Das Oktoberfest findet jedes Jahr in München statt.","Das Oktoberfest ist in München.","Jedes Jahr gibt es Oktoberfest.","In München findet es statt."],"correctAnswer":"Das Oktoberfest findet jedes Jahr in München statt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Feier hat gestern Abend ___.","options":["stattgefunden","stattgefunden hat","stattfindet","stattfindet"],"correctAnswer":"stattgefunden"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: When does the carnival take place?","wordBankItems":["Wann","findet","der","Karneval","statt","?"],"correctAnswer":"Wann findet der Karneval statt ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Feiern'' means?","options":["to celebrate","to feast","to party","to honour"],"correctAnswer":"to celebrate"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a7',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about birthday celebrations","Use birthday wishes","Plan a party in German"],"explanation":{"intro":"Birthday vocabulary is practical and social. Germans take birthdays seriously — the birthday person usually organises and pays for the celebration (unlike in many cultures).","culturalNote":"In Germany, you bring cake to YOUR workplace on YOUR birthday — not the other way round. Herzlichen Glückwunsch zum Geburtstag is the standard wish. Wishing someone happy birthday BEFORE their birthday is considered bad luck in some regions."},"examples":[{"german":"Herzlichen Glückwunsch zum Geburtstag!","english":"Happy Birthday!"},{"german":"Ich feiere meinen Geburtstag am Samstag.","english":"I am celebrating my birthday on Saturday."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss birthday celebrations and give birthday wishes in German."}}',
'{"items":[{"word":"Herzlichen Glückwunsch!","translation":"Congratulations / Happy Birthday!","pronunciation":"HERTS-likh-en GLÜK-voonsh","example":"Herzlichen Glückwunsch!"},{"word":"der Kuchen","translation":"cake","pronunciation":"dayr KOO-khen","example":"Einen Kuchen backen."},{"word":"die Kerze","translation":"candle","pronunciation":"dee KER-tseh","example":"Kerzen ausblasen."},{"word":"die Einladung","translation":"invitation","pronunciation":"dee YN-lah-doong","example":"Eine Einladung schicken."},{"word":"überraschen","translation":"to surprise","pronunciation":"ü-ber-RASH-en","example":"Jemanden überraschen."},{"word":"schenken","translation":"to give as a gift","pronunciation":"SHENK-en","example":"Ich schenke dir."}]}',
'{"title":"Zum Geburtstag — birthday dative","pattern":"Herzlichen Glückwunsch zum Geburtstag (zum = zu + dem, dative)","explanation":"Zum (zu + dem) Geburtstag. Ich wünsche dir alles Gute zum Geburtstag = I wish you all the best for your birthday. For other occasions: zum Jubiläum, zur Hochzeit (zur = zu + der), zum Jahrestag. Schenkverb: Ich schenke dir [accusative object] = I am giving you [gift].","examples":[{"sentence":"Was schenkst du ihr zum Geburtstag?","translation":"What are you giving her for her birthday?"},{"sentence":"Ich wünsche dir alles Gute!","translation":"I wish you all the best!"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Überraschen'' means?","options":["to surprise","to delight","to celebrate","to astonish"],"correctAnswer":"to surprise"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Happy Birthday!","options":["Herzlichen Glückwunsch zum Geburtstag!","Alles Gute!","Frohes Fest!","Schönen Geburtstag!"],"correctAnswer":"Herzlichen Glückwunsch zum Geburtstag!"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Was schenkst du ihr ___ Geburtstag?","options":["zum","zur","zu dem","an"],"correctAnswer":"zum"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I am celebrating my birthday on Saturday","wordBankItems":["Ich","feiere","meinen","Geburtstag","am","Samstag","."],"correctAnswer":"Ich feiere meinen Geburtstag am Samstag ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Einladung'' means?","options":["invitation","party","event","announcement"],"correctAnswer":"invitation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a8',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about Christmas traditions","Use Christmas vocabulary","Discuss gift-giving"],"explanation":{"intro":"Christmas is Germany''s most celebrated festival. Many Christmas traditions originate in Germany — Christmas trees, Advent calendars, and markets.","culturalNote":"The Weihnachtsmarkt tradition goes back to the Middle Ages. The Christkind (Christ child, not Santa) brings gifts in many parts of Germany — especially Bavaria and the South. In Northern Germany, Nikolaus (December 6th) and Weihnachtsmann (Christmas Eve) are more common."},"examples":[{"german":"Frohe Weihnachten und ein glückliches neues Jahr!","english":"Merry Christmas and a Happy New Year!"},{"german":"Am Heiligabend öffnen wir die Geschenke.","english":"On Christmas Eve we open the presents."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss Christmas traditions and wishes in German."}}',
'{"items":[{"word":"Frohe Weihnachten!","translation":"Merry Christmas!","pronunciation":"FROH-eh VY-nakh-ten","example":"Frohe Weihnachten!"},{"word":"der Heiligabend","translation":"Christmas Eve","pronunciation":"dayr HY-likh-ah-bend","example":"Am Heiligabend."},{"word":"das Geschenk","translation":"gift/present","pronunciation":"dahs geh-SHENK","example":"Geschenke auspacken."},{"word":"der Adventskranz","translation":"Advent wreath","pronunciation":"dayr ad-VENTS-krants","example":"Den Adventskranz anzünden."},{"word":"die Bescherung","translation":"gift-giving ceremony","pronunciation":"dee beh-SHEH-roong","example":"Die Bescherung beginnt."},{"word":"das Christkind","translation":"Christ child (gift-giver)","pronunciation":"dahs KRIST-kint","example":"Das Christkind kommt."}]}',
'{"title":"Frohe / frohes / frohes — adjective for wishes","pattern":"Froh- + noun with matching ending: Frohe Weihnachten / Frohes Fest","explanation":"Wish phrases use inflected frohe/frohes. Frohe Weihnachten (plural, accusative-like). Frohes Fest (neuter accusative). Frohes neues Jahr (neuter accusative). These are elliptical: Ich wünsche Ihnen/euch [frohe Weihnachten] is the implied full form. In practice they stand alone.","examples":[{"sentence":"Frohes neues Jahr!","translation":"Happy New Year!"},{"sentence":"Ich wünsche Ihnen frohe Weihnachten.","translation":"I wish you a Merry Christmas."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Heiligabend'' means?","options":["Christmas Eve","Christmas Day","Holy Day","Advent Sunday"],"correctAnswer":"Christmas Eve"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"On Christmas Eve we open the presents.","options":["Am Heiligabend öffnen wir die Geschenke.","Wir öffnen Geschenke an Weihnachten.","Die Geschenke werden geöffnet.","Am 24. Dezember ist Bescherung."],"correctAnswer":"Am Heiligabend öffnen wir die Geschenke."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich wünsche Ihnen ___ Weihnachten.","options":["frohe","frohes","froh","frohem"],"correctAnswer":"frohe"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Happy New Year!","wordBankItems":["Frohes","neues","Jahr","!"],"correctAnswer":"Frohes neues Jahr !"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Bescherung'' means?","options":["gift-giving ceremony","Christmas party","unwrapping time","holiday dinner"],"correctAnswer":"gift-giving ceremony"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000a9',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss New Year celebrations","Make resolutions","Use werden for future plans"],"explanation":{"intro":"New Year vocabulary covers celebrations and the German tradition of Silvester (New Year''s Eve).","culturalNote":"Silvester (December 31) is named after Saint Sylvester. Germans traditionally watch the British sketch ''Dinner for One'' on TV — a unique tradition unmatched elsewhere. Fireworks are set off at midnight by private individuals."},"examples":[{"german":"Zu Silvester schaue ich Feuerwerk.","english":"At New Year I watch fireworks."},{"german":"Mein Vorsatz für das neue Jahr ist, mehr Sport zu treiben.","english":"My resolution for the new year is to do more sport."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss New Year celebrations and resolutions in German."}}',
'{"items":[{"word":"Silvester","translation":"New Year''s Eve","pronunciation":"zil-VES-ter","example":"Zu Silvester feiern."},{"word":"das Feuerwerk","translation":"fireworks","pronunciation":"dahs FOY-er-verk","example":"Feuerwerk zünden."},{"word":"der Vorsatz","translation":"resolution/intention","pronunciation":"dayr FOR-zats","example":"Einen Vorsatz fassen."},{"word":"anstoßen auf","translation":"to toast (with a drink)","pronunciation":"AN-shto-sen owf","example":"Auf das neue Jahr anstoßen."},{"word":"der Sekt","translation":"sparkling wine","pronunciation":"dayr ZEKT","example":"Sekt trinken."},{"word":"das neue Jahr begrüßen","translation":"to ring in the new year","pronunciation":"dahs NOY-eh YAHR beh-GRÜ-sen","example":"Das neue Jahr begrüßen."}]}',
'{"title":"Mein Vorsatz ist, zu + infinitive","pattern":"Mein Vorsatz ist, + [zu-infinitive phrase]","explanation":"New Year''s resolutions: Mein Vorsatz ist, mehr Sport zu machen. Uses zu + infinitive. The infinitive phrase is at the end. More complex: Ich habe mir vorgenommen, ab Januar täglich zu laufen = I have decided to run daily from January. Vornehmen (to decide/resolve) is also common: Ich nehme mir vor, zu + infinitive.","examples":[{"sentence":"Ich nehme mir vor, weniger zu streiten.","translation":"I resolve to argue less."},{"sentence":"Mein Ziel ist, im März eine Prüfung abzulegen.","translation":"My goal is to take an exam in March."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Vorsatz'' means?","options":["resolution/intention","decision","goal","plan"],"correctAnswer":"resolution/intention"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"At New Year I watch fireworks.","options":["Zu Silvester schaue ich Feuerwerk.","An Silvester sehe ich Feuerwerk.","Ich schaue Feuerwerk.","Das Feuerwerk ist schön."],"correctAnswer":"Zu Silvester schaue ich Feuerwerk."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Mein Vorsatz ist, mehr Sport zu ___.","options":["treiben","machen","tun","spielen"],"correctAnswer":"treiben"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I resolve to argue less","wordBankItems":["Ich","nehme","mir","vor",",","weniger","zu","streiten","."],"correctAnswer":"Ich nehme mir vor , weniger zu streiten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Anstoßen auf'' means?","options":["to toast","to knock against","to hit","to celebrate"],"correctAnswer":"to toast"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000aa',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe Easter and spring","Use seasonal vocabulary","Discuss spring activities"],"explanation":{"intro":"Easter and spring vocabulary introduces seasonal language and cultural traditions.","culturalNote":"Ostern (Easter) is a major German holiday with 4 days off. Osterhasen (Easter bunnies) hide Ostereier (Easter eggs) for children. Easter markets (Ostermärkte) are held. Frühjahrsmüdigkeit (spring fatigue) is a recognised phenomenon."},"examples":[{"german":"Zu Ostern suchen die Kinder Ostereier im Garten.","english":"At Easter the children hunt for Easter eggs in the garden."},{"german":"Im Frühling blühen die Blumen überall.","english":"In spring flowers bloom everywhere."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss Easter traditions and spring in German."}}',
'{"items":[{"word":"der Osterhase","translation":"Easter bunny","pronunciation":"dayr OS-ter-hah-zeh","example":"Der Osterhase kommt."},{"word":"das Osterei","translation":"Easter egg","pronunciation":"dahs OS-ter-eye","example":"Ostereier suchen."},{"word":"blühen","translation":"to blossom/bloom","pronunciation":"BLÜ-en","example":"Die Blumen blühen."},{"word":"der Frühling","translation":"spring","pronunciation":"dayr FRÜ-ling","example":"Im Frühling."},{"word":"aufwachen","translation":"to wake up","pronunciation":"OWF-vakh-en","example":"Die Natur wacht auf."},{"word":"die Auferstehung","translation":"resurrection","pronunciation":"dee OWF-er-shtey-oong","example":"Auferstehung Jesu."}]}',
'{"title":"Überall — everywhere","pattern":"überall (everywhere) — used as free adverb","explanation":"Überall means everywhere: Blumen blühen überall = Flowers bloom everywhere. Überall in Deutschland = throughout Germany. Nirgendwo = nowhere (antonym). Überall can precede or follow the verb phrase. Überall wo ich bin = wherever I am. Irgendwo = somewhere.","examples":[{"sentence":"Überall in der Stadt hört man Vogelgezwitscher.","translation":"Everywhere in the city you can hear birdsong."},{"sentence":"Im Frühling ist es überall grün.","translation":"In spring it is green everywhere."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Blühen'' means?","options":["to bloom","to grow","to sprout","to blossom out"],"correctAnswer":"to bloom"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In spring flowers bloom everywhere.","options":["Im Frühling blühen die Blumen überall.","Im Frühling sind Blumen überall.","Die Blumen blühen im Frühling.","Überall ist Frühling."],"correctAnswer":"Im Frühling blühen die Blumen überall."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ in der Stadt hört man Vogelgezwitscher.","options":["Überall","Irgendwo","Nirgendwo","Hier"],"correctAnswer":"Überall"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: At Easter the children hunt for Easter eggs in the garden","wordBankItems":["Zu","Ostern","suchen","die","Kinder","Ostereier","im","Garten","."],"correctAnswer":"Zu Ostern suchen die Kinder Ostereier im Garten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Nirgendwo'' means?","options":["nowhere","somewhere","anywhere","everywhere"],"correctAnswer":"nowhere"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000ab',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe extended family relationships","Use Schwager, Schwägerin, Schwiegermutter etc.","Discuss family dynamics"],"explanation":{"intro":"Extended family vocabulary is important for social conversations. German has specific words for all in-law relationships.","culturalNote":"German family relationships have precise vocabulary where English often uses in-law. Schwiegervater/Schwiegermutter (father/mother-in-law), Schwager/Schwägerin (brother/sister-in-law), Neffe/Nichte (nephew/niece)."},"examples":[{"german":"Mein Schwager arbeitet bei einer Bank.","english":"My brother-in-law works at a bank."},{"german":"Meine Schwiegermutter besucht uns nächste Woche.","english":"My mother-in-law is visiting us next week."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can name and discuss extended family relationships in German."}}',
'{"items":[{"word":"der Schwager","translation":"brother-in-law","pronunciation":"dayr SHVAH-ger","example":"Mein Schwager."},{"word":"die Schwägerin","translation":"sister-in-law","pronunciation":"dee SHVÄ-ger-in","example":"Meine Schwägerin."},{"word":"der Schwiegervater","translation":"father-in-law","pronunciation":"dayr SHVEE-ger-fah-ter","example":"Mein Schwiegervater."},{"word":"die Schwiegermutter","translation":"mother-in-law","pronunciation":"dee SHVEE-ger-moo-ter","example":"Meine Schwiegermutter."},{"word":"der Neffe","translation":"nephew","pronunciation":"dayr NEF-eh","example":"Mein Neffe."},{"word":"die Nichte","translation":"niece","pronunciation":"dee NIKH-teh","example":"Meine Nichte."}]}',
'{"title":"Mein/meine — possessive adjectives with family","pattern":"mein (m/n) / meine (f/pl) + family member (nominative)","explanation":"Possessive adjectives with family: mein Vater, meine Mutter, mein Kind (neuter), meine Eltern (plural). For extended family: mein Schwager, meine Schwägerin. In dative: meinem Vater, meiner Mutter, meinem Kind, meinen Eltern. Common family phrase: Wie geht es Ihrer Familie? = How is your family?","examples":[{"sentence":"Meine Nichte ist erst zwei Jahre alt.","translation":"My niece is only two years old."},{"sentence":"Mein Neffe spielt gut Fußball.","translation":"My nephew plays football well."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Schwägerin'' means?","options":["sister-in-law","sister","stepsister","cousin"],"correctAnswer":"sister-in-law"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"My brother-in-law works at a bank.","options":["Mein Schwager arbeitet bei einer Bank.","Mein Bruder arbeitet bei einer Bank.","Mein Schwager ist Banker.","Er arbeitet bei einer Bank."],"correctAnswer":"Mein Schwager arbeitet bei einer Bank."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Meine Nichte ist erst zwei Jahre ___.","options":["alt","jung","klein","groß"],"correctAnswer":"alt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: My mother-in-law is visiting us next week","wordBankItems":["Meine","Schwiegermutter","besucht","uns","nächste","Woche","."],"correctAnswer":"Meine Schwiegermutter besucht uns nächste Woche ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Schwiegervater'' means?","options":["father-in-law","stepfather","godfather","uncle by marriage"],"correctAnswer":"father-in-law"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000ac',1,'APPROVED','PUBLISHED',
'{"objectives":["Talk about pets","Describe pet care","Use sich kümmern um"],"explanation":{"intro":"Pet vocabulary is popular in everyday conversation. Germany is a nation of pet lovers.","culturalNote":"Germany has around 34 million pets. Dogs are especially popular — Hunde are allowed in many shops and restaurants. Hundesteuer (dog tax) is charged by most municipalities and must be registered. The Tierheim (animal shelter) system is well-organised."},"examples":[{"german":"Ich habe einen Hund, der jeden Tag spazieren muss.","english":"I have a dog that needs a walk every day."},{"german":"Meine Katze läuft frei in der Wohnung.","english":"My cat roams freely around the flat."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about pets and their care in German."}}',
'{"items":[{"word":"der Tierarzt","translation":"vet","pronunciation":"dayr TEER-artst","example":"Zum Tierarzt gehen."},{"word":"das Futter","translation":"animal food/feed","pronunciation":"dahs FOO-ter","example":"Das Futter kaufen."},{"word":"spazieren gehen","translation":"to go for a walk","pronunciation":"shpah-TSEER-en GAY-en","example":"Mit dem Hund spazieren."},{"word":"das Tierheim","translation":"animal shelter","pronunciation":"dahs TEER-hyme","example":"Im Tierheim adoptieren."},{"word":"kastrieren","translation":"to neuter","pronunciation":"kas-TREER-en","example":"Den Hund kastrieren."},{"word":"die Pfote","translation":"paw","pronunciation":"dee PFOH-teh","example":"Die Pfoten lecken."}]}',
'{"title":"Der...der — relative clause with pet","pattern":"Ich habe einen Hund, der jeden Tag spazieren muss","explanation":"Relative clause identifying a pet: Ich habe einen Hund, der... The relative pronoun der agrees with der Hund (masculine). Ich habe eine Katze, die... (feminine). Ich habe ein Kaninchen, das... (neuter). In accusative: Ich habe einen Hund, den ich täglich füttere = I have a dog that I feed daily.","examples":[{"sentence":"Ich habe eine Katze, die sehr schüchtern ist.","translation":"I have a cat that is very shy."},{"sentence":"Das Kaninchen, das ich habe, ist sehr zahm.","translation":"The rabbit I have is very tame."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Tierheim'' means?","options":["animal shelter","pet shop","vet clinic","zoo"],"correctAnswer":"animal shelter"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have a dog that needs a walk every day.","options":["Ich habe einen Hund, der jeden Tag spazieren muss.","Mein Hund geht täglich spazieren.","Ich gehe mit dem Hund spazieren.","Ein Hund braucht Bewegung."],"correctAnswer":"Ich habe einen Hund, der jeden Tag spazieren muss."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich habe eine Katze, ___ sehr schüchtern ist.","options":["die","der","das","den"],"correctAnswer":"die"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: My cat roams freely around the flat","wordBankItems":["Meine","Katze","läuft","frei","in","der","Wohnung","."],"correctAnswer":"Meine Katze läuft frei in der Wohnung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Pfote'' means?","options":["paw","claw","tail","fur"],"correctAnswer":"paw"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000ad',1,'APPROVED','PUBLISHED',
'{"objectives":["Navigate city life","Describe urban features","Use in der Innenstadt vocabulary"],"explanation":{"intro":"City vocabulary builds on A1 directions to describe urban living and city features.","culturalNote":"German cities are famous for their Altstadt (old town) areas with cobblestone streets and historic buildings. Many cities were heavily bombed in WWII but rebuilt. The Fussgängerzone (pedestrian zone) is common in city centres."},"examples":[{"german":"Die Innenstadt ist gut mit dem ÖPNV erreichbar.","english":"The city centre is easily reachable by public transport."},{"german":"Ich wohne in der Nähe des Stadtparks.","english":"I live near the city park."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe city features and urban living in German."}}',
'{"items":[{"word":"die Innenstadt","translation":"city centre","pronunciation":"dee IN-en-shtat","example":"In die Innenstadt fahren."},{"word":"der ÖPNV","translation":"public transport","pronunciation":"dayr Ö-PEE-EN-FOW","example":"Mit dem ÖPNV."},{"word":"die Fussgängerzone","translation":"pedestrian zone","pronunciation":"dee FOOS-gäng-er-tso-neh","example":"In der Fußgängerzone."},{"word":"die Altstadt","translation":"old town","pronunciation":"dee ALT-shtat","example":"Durch die Altstadt bummeln."},{"word":"in der Nähe","translation":"near/nearby","pronunciation":"in dayr NÄ-eh","example":"In der Nähe des Bahnhofs."},{"word":"der Stadtpark","translation":"city park","pronunciation":"dayr SHTAT-park","example":"Im Stadtpark spazieren."}]}',
'{"title":"Erreichbar — reachable (adjective)","pattern":"gut/leicht/schlecht erreichbar (easily/poorly reachable)","explanation":"Erreichbar (reachable) is used with modifiers. Gut erreichbar = easily accessible. Schlecht erreichbar = hard to reach. Used in transport and location descriptions: Das Haus ist mit dem Auto gut erreichbar = The house is easily reachable by car. Mit dem Bus erreichbar sein = to be reachable by bus.","examples":[{"sentence":"Das Hotel ist mit dem Zug leicht erreichbar.","translation":"The hotel is easily reachable by train."},{"sentence":"Die Insel ist nur mit der Fähre erreichbar.","translation":"The island is only reachable by ferry."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Fussgängerzone'' means?","options":["pedestrian zone","shopping street","market square","high street"],"correctAnswer":"pedestrian zone"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The city centre is easily reachable by public transport.","options":["Die Innenstadt ist gut mit dem ÖPNV erreichbar.","Man kommt mit dem ÖPNV in die Innenstadt.","Mit dem Bus fährt man in die Innenstadt.","Die Innenstadt ist nah."],"correctAnswer":"Die Innenstadt ist gut mit dem ÖPNV erreichbar."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Hotel ist mit dem Zug leicht ___.","options":["erreichbar","erreichbar sein","erreichbar ist","zu erreichen"],"correctAnswer":"erreichbar"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I live near the city park","wordBankItems":["Ich","wohne","in","der","Nähe","des","Stadtparks","."],"correctAnswer":"Ich wohne in der Nähe des Stadtparks ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Altstadt'' means?","options":["old town","historic district","city centre","medieval quarter"],"correctAnswer":"old town"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000ae',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe rural life","Compare city and country living","Use auf dem Land vocabulary"],"explanation":{"intro":"Rural Germany has a distinct character — small villages, forests, farms and a slower pace of life.","culturalNote":"About 22% of Germans live in rural areas (Landgebiete). Dörfer (villages) are common and many Germans prefer the Landleben (country life) to city life. Schwarzwald (Black Forest), Bavarian Alps and Lüneburger Heide are famous rural areas."},"examples":[{"german":"Auf dem Land ist die Luft viel frischer als in der Stadt.","english":"In the country the air is much fresher than in the city."},{"german":"Ich könnte mir vorstellen, aufs Land zu ziehen.","english":"I could imagine moving to the country."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe rural life and compare it to city living in German."}}',
'{"items":[{"word":"auf dem Land","translation":"in the country","pronunciation":"owf dem LANT","example":"Auf dem Land leben."},{"word":"das Dorf","translation":"village","pronunciation":"dahs DORF","example":"Im Dorf wohnen."},{"word":"der Bauernhof","translation":"farm","pronunciation":"dayr BOW-ern-hof","example":"Auf dem Bauernhof."},{"word":"die Ruhe","translation":"quiet/peace","pronunciation":"dee ROO-eh","example":"Die ländliche Ruhe."},{"word":"sich vorstellen","translation":"to imagine","pronunciation":"zikh FOR-shtel-en","example":"Ich kann mir vorstellen."},{"word":"das Landleben","translation":"country life","pronunciation":"dahs LANT-lay-ben","example":"Das Landleben genießen."}]}',
'{"title":"Sich (etwas) vorstellen — to imagine","pattern":"Ich kann mir vorstellen, [zu-infinitive / dass-clause]","explanation":"Sich vorstellen (reflexive) = to imagine. Ich kann mir vorstellen, dort zu leben = I can imagine living there. The dative reflexive mir is required (not mich). After vorstellen: zu-infinitive (same subject) or dass-clause (different subject): Ich kann mir vorstellen, dass du das magst.","examples":[{"sentence":"Kannst du dir vorstellen, ohne Internet zu leben?","translation":"Can you imagine living without internet?"},{"sentence":"Ich kann mir gut vorstellen, auf dem Land zu wohnen.","translation":"I can well imagine living in the country."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Bauernhof'' means?","options":["farm","countryside","village","rural area"],"correctAnswer":"farm"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In the country the air is much fresher than in the city.","options":["Auf dem Land ist die Luft viel frischer als in der Stadt.","Das Land hat frische Luft.","Die Stadtluft ist schlechter.","Auf dem Land ist es schöner."],"correctAnswer":"Auf dem Land ist die Luft viel frischer als in der Stadt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Kannst du ___ vorstellen, ohne Internet zu leben?","options":["dir","dich","du","deinen"],"correctAnswer":"dir"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I can well imagine living in the country","wordBankItems":["Ich","kann","mir","gut","vorstellen",",","auf","dem","Land","zu","wohnen","."],"correctAnswer":"Ich kann mir gut vorstellen , auf dem Land zu wohnen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Ruhe'' means?","options":["quiet/peace","rest","silence","calm"],"correctAnswer":"quiet/peace"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000af',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe weather in more detail","Use weather verbs and expressions","Predict weather with wird"],"explanation":{"intro":"Advanced weather vocabulary goes beyond basic A1 sunny/rainy to describe conditions more precisely and forecast weather.","culturalNote":"Germany has a temperate climate with no weather extremes — but it is famously variable! Aprilwetter (April weather) describes unpredictable rapid changes. Hundstage (dog days, hot August weather) and Schmuddelwetter (grey drizzly weather) are evocative terms."},"examples":[{"german":"Heute wird es bewölkt mit vereinzelten Schauern.","english":"Today it will be cloudy with isolated showers."},{"german":"Bei dem Schmuddelwetter bleibe ich lieber zu Hause.","english":"In this miserable drizzly weather I''d rather stay at home."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe and predict the weather in detail in German."}}',
'{"items":[{"word":"bewölkt","translation":"cloudy","pronunciation":"beh-VÖLKT","example":"Heute bewölkt."},{"word":"der Schauer","translation":"shower (of rain)","pronunciation":"dayr SHOW-er","example":"Vereinzelte Schauer."},{"word":"das Schmuddelwetter","translation":"miserable drizzly weather","pronunciation":"dahs SHMOODEL-vet-er","example":"Schmuddelwetter heute."},{"word":"die Vorhersage","translation":"forecast","pronunciation":"dee FOR-her-zah-geh","example":"Die Wettervorhersage."},{"word":"der Sturm","translation":"storm","pronunciation":"dayr SHTOORM","example":"Ein Sturm zieht auf."},{"word":"vereinzelt","translation":"scattered/isolated","pronunciation":"fer-EYN-tselt","example":"Vereinzelte Wolken."}]}',
'{"title":"Wird es + adjective/noun — weather future","pattern":"Heute wird es [weather adjective] / Es wird [verb] (future)","explanation":"Werden for weather predictions: Es wird regnen = it will rain. Heute wird es sonnig = today it will be sunny. Es wird kälter werden = it will get colder (double werden). Forecast language: laut Vorhersage wird es... (according to the forecast it will...). Wind: Es wird windiger.","examples":[{"sentence":"Morgen wird es frischer und windig.","translation":"Tomorrow it will be fresher and windy."},{"sentence":"Laut Vorhersage gibt es ab Mittag Regen.","translation":"According to the forecast there will be rain from midday."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Bewölkt'' means?","options":["cloudy","overcast","rainy","foggy"],"correctAnswer":"cloudy"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Today it will be cloudy with isolated showers.","options":["Heute wird es bewölkt mit vereinzelten Schauern.","Heute regnet es und ist bewölkt.","Es ist heute bewölkt.","Vereinzelte Schauer heute."],"correctAnswer":"Heute wird es bewölkt mit vereinzelten Schauern."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Morgen ___ es frischer und windig.","options":["wird","ist","wird sein","wäre"],"correctAnswer":"wird"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: According to the forecast there will be rain from midday","wordBankItems":["Laut","Vorhersage","gibt","es","ab","Mittag","Regen","."],"correctAnswer":"Laut Vorhersage gibt es ab Mittag Regen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Vereinzelt'' means?","options":["scattered/isolated","occasional","heavy","light"],"correctAnswer":"scattered/isolated"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000b0',1,'APPROVED','PUBLISHED',
'{"objectives":["Describe all four seasons","Compare seasonal activities","Use im + season"],"explanation":{"intro":"Seasons vocabulary builds on weather to describe seasonal activities, moods and transitions.","culturalNote":"Germans are very season-oriented. Herbst (autumn) is especially beloved — walking through colourful forests (Herbstwandern), Erntedankfest (harvest festival), and Federweißer (young wine) drinking mark the season."},"examples":[{"german":"Im Herbst leuchten die Blätter in leuchtenden Farben.","english":"In autumn the leaves glow in bright colours."},{"german":"Der Sommer ist meine Lieblingsjahreszeit.","english":"Summer is my favourite season."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can describe the four seasons and seasonal activities in German."}}',
'{"items":[{"word":"der Herbst","translation":"autumn","pronunciation":"dayr HERBST","example":"Im Herbst."},{"word":"das Laub","translation":"foliage/fallen leaves","pronunciation":"dahs LOWP","example":"Das bunte Laub."},{"word":"leuchten","translation":"to glow/shine","pronunciation":"LOY-khen","example":"Die Farben leuchten."},{"word":"die Jahreszeit","translation":"season","pronunciation":"dee YAH-res-tsyt","example":"Welche Jahreszeit?"},{"word":"der Frühjahrsmüdigkeit","translation":"spring fatigue","pronunciation":"dayr FRÜ-yahrs-mü-dikh-kyt","example":"Frühjahrsmüdigkeit spüren."},{"word":"überwintern","translation":"to overwinter/hibernate","pronunciation":"ü-ber-VIN-tern","example":"Vögel überwintern im Süden."}]}',
'{"title":"Im + season — seasonal time frame","pattern":"im Frühling / im Sommer / im Herbst / im Winter","explanation":"Im (in + dem) + season: im Frühling (in spring), im Sommer (in summer), im Herbst (in autumn), im Winter (in winter). All seasons are masculine: der Frühling, der Sommer, der Herbst, der Winter → im (not in der or in das). Seasonal activities: im Winter Ski fahren, im Sommer schwimmen gehen.","examples":[{"sentence":"Im Winter schlafe ich mehr als im Sommer.","translation":"In winter I sleep more than in summer."},{"sentence":"Im Frühling beginnt die Gartensaison.","translation":"In spring the garden season begins."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Laub'' means?","options":["foliage/fallen leaves","tree","forest","branches"],"correctAnswer":"foliage/fallen leaves"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In autumn the leaves glow in bright colours.","options":["Im Herbst leuchten die Blätter in leuchtenden Farben.","Die Blätter sind im Herbst bunt.","Im Herbst fallen die Blätter.","Herbst ist schön."],"correctAnswer":"Im Herbst leuchten die Blätter in leuchtenden Farben."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Im ___ schlafe ich mehr als im Sommer.","options":["Winter","Herbst","Frühling","Jahr"],"correctAnswer":"Winter"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Summer is my favourite season","wordBankItems":["Der","Sommer","ist","meine","Lieblingsjahreszeit","."],"correctAnswer":"Der Sommer ist meine Lieblingsjahreszeit ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"All seasons in German are which gender?","options":["masculine","feminine","neuter","mixed"],"correctAnswer":"masculine"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000b1',1,'APPROVED','PUBLISHED',
'{"objectives":["Name animals and their traits","Use animal vocabulary","Describe nature"],"explanation":{"intro":"Animal and nature vocabulary is useful for trips, nature documentaries and everyday conversations.","culturalNote":"Germany''s forests (Wälder) cover about 32% of the country. They are home to deer (Rehe), wild boar (Wildschweine) and fox (Fuchs). Bienen (bees) are a major concern — Germany has strong Bienensterben (bee death) awareness campaigns."},"examples":[{"german":"Im Schwarzwald leben viele Wildtiere.","english":"Many wild animals live in the Black Forest."},{"german":"Der Fuchs ist ein schlauer Jäger.","english":"The fox is a clever hunter."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can talk about animals and nature in German."}}',
'{"items":[{"word":"das Wildtier","translation":"wild animal","pronunciation":"dahs VILT-teer","example":"Wildtiere beobachten."},{"word":"der Fuchs","translation":"fox","pronunciation":"dayr FOOKS","example":"Ein Fuchs im Garten."},{"word":"das Reh","translation":"deer (roe)","pronunciation":"dahs RAY","example":"Ein Reh im Wald."},{"word":"die Biene","translation":"bee","pronunciation":"dee BEE-neh","example":"Bienen sind wichtig."},{"word":"die Eule","translation":"owl","pronunciation":"dee OY-leh","example":"Eine Eule nachts."},{"word":"das Wildschwein","translation":"wild boar","pronunciation":"dahs VILT-shvyn","example":"Wildschweine im Wald."}]}',
'{"title":"Schlau, clever, listig — clever animals","pattern":"schlau (clever), listig (cunning), gefährlich (dangerous) — animal traits","explanation":"Animal characteristics use regular adjectives. Der Fuchs ist schlau (the fox is clever). Schlau = clever/smart. Listig = cunning/wily. Zahm = tame. Wild = wild. Gefährlich = dangerous. These follow normal adjective patterns when used attributively: Ein schlaues Tier (neuter), ein schlauer Fuchs (masculine).","examples":[{"sentence":"Der Wolf gilt als gefährlich, aber er meidet Menschen.","translation":"The wolf is considered dangerous, but it avoids people."},{"sentence":"Krähen sind sehr kluge Vögel.","translation":"Crows are very intelligent birds."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Wildschwein'' means?","options":["wild boar","wild pig","forest pig","black pig"],"correctAnswer":"wild boar"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Many wild animals live in the Black Forest.","options":["Im Schwarzwald leben viele Wildtiere.","Der Schwarzwald hat viele Tiere.","Wildtiere sind im Schwarzwald.","Im Wald gibt es Tiere."],"correctAnswer":"Im Schwarzwald leben viele Wildtiere."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Fuchs ist ein ___ Jäger.","options":["schlaues","schlauen","schlauer","schlau"],"correctAnswer":"schlauer"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Crows are very intelligent birds","wordBankItems":["Krähen","sind","sehr","kluge","Vögel","."],"correctAnswer":"Krähen sind sehr kluge Vögel ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Zahm'' means?","options":["tame","calm","gentle","safe"],"correctAnswer":"tame"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000b2',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss German cultural values","Use typisch deutsch vocabulary","Describe cultural characteristics"],"explanation":{"intro":"Understanding cultural values helps you connect more authentically with German speakers.","culturalNote":"Typisch deutsch characteristics often cited include: Pünktlichkeit (punctuality), Gründlichkeit (thoroughness), Direktheit (directness), Ordnung (order). These are cultural tendencies, not universal rules — modern Germany is very diverse."},"examples":[{"german":"Pünktlichkeit wird in Deutschland sehr geschätzt.","english":"Punctuality is very valued in Germany."},{"german":"Deutsche sind oft direkt und meinen es nicht unhöflich.","english":"Germans are often direct and do not mean it rudely."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss German cultural values and characteristics in German."}}',
'{"items":[{"word":"die Pünktlichkeit","translation":"punctuality","pronunciation":"dee PÜNKT-likh-kyt","example":"Pünktlichkeit schätzen."},{"word":"die Gründlichkeit","translation":"thoroughness","pronunciation":"dee GRÜNT-likh-kyt","example":"Mit Gründlichkeit."},{"word":"die Direktheit","translation":"directness","pronunciation":"dee dee-REKT-hyt","example":"Deutsche Direktheit."},{"word":"schätzen","translation":"to value/appreciate","pronunciation":"SHET-tsen","example":"Ich schätze das."},{"word":"gelten als","translation":"to be considered as","pronunciation":"GEL-ten ahls","example":"Das gilt als unhöflich."},{"word":"typisch","translation":"typical","pronunciation":"TÜ-pish","example":"Typisch deutsch!"}]}',
'{"title":"Gelten als — to be considered as","pattern":"gilt als + adjective / als + noun (is regarded as)","explanation":"Gelten als (to be considered/regarded as). Er gilt als Experte = He is considered an expert. Das gilt als grob = That is considered rude. Gilt als + adjective (no article): Das gilt als unhöflich. Gilt als + noun: Das Land gilt als sicher. Useful for describing cultural perceptions.","examples":[{"sentence":"Deutschland gilt als eines der pünktlichsten Länder.","translation":"Germany is considered one of the most punctual countries."},{"sentence":"Das Schweigen gilt manchmal als Zustimmung.","translation":"Silence is sometimes considered consent."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Gründlichkeit'' means?","options":["thoroughness","precision","detail","accuracy"],"correctAnswer":"thoroughness"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Punctuality is very valued in Germany.","options":["Pünktlichkeit wird in Deutschland sehr geschätzt.","Deutschland schätzt Pünktlichkeit.","Pünktlichkeit ist in Deutschland wichtig.","In Deutschland ist Pünktlichkeit normal."],"correctAnswer":"Pünktlichkeit wird in Deutschland sehr geschätzt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Deutschland gilt als eines der ___ Länder.","options":["pünktlichsten","pünktlichste","pünktlich","pünktlichem"],"correctAnswer":"pünktlichsten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Silence is sometimes considered consent","wordBankItems":["Das","Schweigen","gilt","manchmal","als","Zustimmung","."],"correctAnswer":"Das Schweigen gilt manchmal als Zustimmung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Schätzen'' means?","options":["to value/appreciate","to estimate","to assess","to guess"],"correctAnswer":"to value/appreciate"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000b3',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss stereotypes critically","Distinguish stereotype from reality","Use man sagt vocabulary"],"explanation":{"intro":"Critical thinking about stereotypes is an important topic at A2+. Language learners often encounter stereotypes about their own culture.","culturalNote":"Germans themselves are aware of German stereotypes and often discuss them with self-irony (Selbstironie). Not all Germans like football or drink beer. Regional differences within Germany are enormous — Bavarians and North Germans see themselves as very different."},"examples":[{"german":"Nicht alle Deutschen trinken gern Bier.","english":"Not all Germans like drinking beer."},{"german":"Man sagt, Deutsche sind humorlos, aber das stimmt nicht immer.","english":"They say Germans are humourless, but that''s not always true."}],"rewards":{"xp":130,"coins":65},"metadata":{"estimatedMinutes":15,"canDo":"I can discuss stereotypes and cultural generalisations critically in German."}}',
'{"items":[{"word":"das Klischee","translation":"cliché/stereotype","pronunciation":"dahs klee-SHEY","example":"Ein altes Klischee."},{"word":"man sagt","translation":"they say/it is said","pronunciation":"man ZAHKT","example":"Man sagt, dass..."},{"word":"stimmen","translation":"to be right/correct","pronunciation":"SHTIM-en","example":"Das stimmt nicht."},{"word":"verallgemeinern","translation":"to generalise","pronunciation":"fer-AL-geh-my-nern","example":"Man sollte nicht verallgemeinern."},{"word":"die Ausnahme","translation":"exception","pronunciation":"dee OWS-nah-meh","example":"Jede Regel hat Ausnahmen."},{"word":"die Selbstironie","translation":"self-irony","pronunciation":"dee ZELP-sti-roh-nee","example":"Mit Selbstironie."}]}',
'{"title":"Nicht alle — not all (quantifier negation)","pattern":"nicht alle (not all) / nicht jeder (not everyone)","explanation":"Nicht alle Deutschen... (not all Germans...). Nicht jeder/jede/jedes (not every). Manche (some). Viele (many). These quantifiers allow nuanced generalisations. Nicht jeder Deutsche mag Sauerkraut = Not every German likes sauerkraut. Comparing: Manche mögen, manche mögen nicht.","examples":[{"sentence":"Nicht alle Stereotypen stimmen.","translation":"Not all stereotypes are true."},{"sentence":"Manche Deutsche mögen Fußball, andere lieber Handball.","translation":"Some Germans like football, others prefer handball."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Verallgemeinern'' means?","options":["to generalise","to exaggerate","to stereotype","to simplify"],"correctAnswer":"to generalise"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Not all Germans like drinking beer.","options":["Nicht alle Deutschen trinken gern Bier.","Deutsche trinken Bier.","Viele Deutsche mögen kein Bier.","Es stimmt, dass Deutsche Bier mögen."],"correctAnswer":"Nicht alle Deutschen trinken gern Bier."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Man sagt, Deutsche sind humorlos, aber das ___ nicht immer.","options":["stimmt","ist","hat","klingt"],"correctAnswer":"stimmt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Not all stereotypes are true","wordBankItems":["Nicht","alle","Stereotypen","stimmen","."],"correctAnswer":"Nicht alle Stereotypen stimmen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Ausnahme'' means?","options":["exception","example","rule","case"],"correctAnswer":"exception"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000b4',1,'APPROVED','PUBLISHED',
'{"objectives":["Review all A2 topics","Celebrate completing A2","Reflect on language progress"],"explanation":{"intro":"Congratulations on completing German A2! You have covered all key A2 grammar and vocabulary topics.","culturalNote":"Reaching A2 means you can handle everyday tasks, describe your background and experiences, and communicate in familiar situations. The Goethe-Institut''s official A2 exam (Goethe-Zertifikat A2) validates this level. B1 opens the door to full independence."},"examples":[{"german":"Ich habe das A2-Niveau in Deutsch erreicht!","english":"I have reached the A2 level in German!"},{"german":"Ich freue mich darauf, mit B1 weiterzumachen.","english":"I am looking forward to continuing with B1."}],"rewards":{"xp":200,"coins":100},"metadata":{"estimatedMinutes":20,"canDo":"I have completed German A2 and am ready for B1."}}',
'{"items":[{"word":"erreichen","translation":"to reach/achieve","pronunciation":"er-RY-khen","example":"Das Ziel erreichen."},{"word":"das Niveau","translation":"level/standard","pronunciation":"dahs nee-VOH","example":"Mein Sprachniveau."},{"word":"weitermachen","translation":"to continue","pronunciation":"VY-ter-makh-en","example":"Weitermachen mit B1."},{"word":"stolz sein auf","translation":"to be proud of","pronunciation":"SHTOLTS syn owf","example":"Ich bin stolz auf mich."},{"word":"der Fortschritt","translation":"progress","pronunciation":"dayr FORT-shrit","example":"Guter Fortschritt!"},{"word":"es lohnt sich","translation":"it is worth it","pronunciation":"es LOHNT zikh","example":"Es lohnt sich zu lernen."}]}',
'{"title":"Es lohnt sich — it is worth it","pattern":"es lohnt sich + zu-infinitive (it is worth doing)","explanation":"Es lohnt sich (it is worth it/worthwhile). Es lohnt sich, Deutsch zu lernen = It is worth learning German. Reflexive: lohnen + sich. Past: Es hat sich gelohnt = It was worth it. Negative: Es lohnt sich nicht = It is not worth it. This phrase is very useful for motivational statements.","examples":[{"sentence":"Der Aufwand lohnt sich definitiv.","translation":"The effort is definitely worth it."},{"sentence":"Es hat sich gelohnt, jeden Tag zu üben.","translation":"It was worth it to practise every day."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Fortschritt'' means?","options":["progress","success","improvement","development"],"correctAnswer":"progress"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I have reached the A2 level in German!","options":["Ich habe das A2-Niveau in Deutsch erreicht!","Ich bin auf A2-Niveau.","Mein Deutschniveau ist A2.","Ich habe A2 gelernt!"],"correctAnswer":"Ich habe das A2-Niveau in Deutsch erreicht!"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Es hat sich ___, jeden Tag zu üben.","options":["gelohnt","lohnt","lohnte","lohnen"],"correctAnswer":"gelohnt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I am looking forward to continuing with B1","wordBankItems":["Ich","freue","mich","darauf",",","mit","B1","weiterzumachen","."],"correctAnswer":"Ich freue mich darauf , mit B1 weiterzumachen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"What does completing A2 mean practically?","options":["Handle everyday tasks and familiar situations","Read newspapers fluently","Understand complex arguments","Discuss abstract topics freely"],"correctAnswer":"Handle everyday tasks and familiar situations"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-0000000000a1','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l161',161,'Freizeit - Leisure','Leisure activities and Feierabend','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a2','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l162',162,'Hobbys 2 - Hobbies 2','Detailed hobby descriptions','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a3','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l163',163,'Musik - Music','Music genres and instruments','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a4','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l164',164,'Kino - Cinema','Films and cinema preferences','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a5','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l165',165,'Bücher - Books','Books genres and plot descriptions','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a6','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l166',166,'Feste - Festivals','German festivals and celebrations','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a7','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l167',167,'Geburtstag - Birthday','Birthday vocabulary and wishes','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a8','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l168',168,'Weihnachten - Christmas','Christmas vocabulary and traditions','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000a9','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l169',169,'Silvester - New Year','New Year celebrations and resolutions','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000aa','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l170',170,'Ostern - Easter','Easter and spring vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000ab','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l171',171,'Familie 2 - Family 2','Extended family and in-laws','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000ac','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l172',172,'Haustiere - Pets','Pets and animal care','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000ad','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l173',173,'In der Stadt - City','City features and urban life','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000ae','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l174',174,'Auf dem Land - Country','Rural life and comparisons','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000af','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l175',175,'Wetter 2 - Weather 2','Detailed weather and forecasts','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000b0','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l176',176,'Jahreszeiten - Seasons','All four seasons and activities','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000b1','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l177',177,'Tiere - Animals','Wildlife and nature vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000b2','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l178',178,'Deutsche Kultur - German Culture','Cultural values and characteristics','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000b3','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l179',179,'Stereotype - Stereotypes','Critical discussion of stereotypes','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000b4','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000002',NULL,'de-a2-u02-l180',180,'A2 Abschluss - A2 Complete','A2 completion milestone','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a1' WHERE stable_ref = 'de-a2-u02-l161' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a2' WHERE stable_ref = 'de-a2-u02-l162' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a3' WHERE stable_ref = 'de-a2-u02-l163' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a4' WHERE stable_ref = 'de-a2-u02-l164' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a5' WHERE stable_ref = 'de-a2-u02-l165' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a6' WHERE stable_ref = 'de-a2-u02-l166' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a7' WHERE stable_ref = 'de-a2-u02-l167' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a8' WHERE stable_ref = 'de-a2-u02-l168' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000a9' WHERE stable_ref = 'de-a2-u02-l169' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000aa' WHERE stable_ref = 'de-a2-u02-l170' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000ab' WHERE stable_ref = 'de-a2-u02-l171' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000ac' WHERE stable_ref = 'de-a2-u02-l172' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000ad' WHERE stable_ref = 'de-a2-u02-l173' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000ae' WHERE stable_ref = 'de-a2-u02-l174' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000af' WHERE stable_ref = 'de-a2-u02-l175' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000b0' WHERE stable_ref = 'de-a2-u02-l176' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000b1' WHERE stable_ref = 'de-a2-u02-l177' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000b2' WHERE stable_ref = 'de-a2-u02-l178' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000b3' WHERE stable_ref = 'de-a2-u02-l179' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000b4' WHERE stable_ref = 'de-a2-u02-l180' AND lesson_id IS NULL;
