-- V62: German B1 lessons 201-220 (B1 batch 1)
-- Level: B1 (10000000-0000-0000-0000-000000000003), unit de-b1-u03
-- Hex: 201=0xc9, 220=0xdc

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-0000000000c9','de-b1-l201','Konjunktiv II - Subjunctive Mood','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000ca','de-b1-l202','Irreale Bedingungen - Unreal Conditions','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000cb','de-b1-l203','Wunschsätze - Wish Sentences','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000cc','de-b1-l204','Konzessivsätze - Concessive Clauses','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000cd','de-b1-l205','Kausalsätze - Causal Clauses','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000ce','de-b1-l206','Konsekutivsätze - Consecutive Clauses','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000cf','de-b1-l207','Finalsätze - Purpose Clauses','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d0','de-b1-l208','Modalsätze - Modal Clauses','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d1','de-b1-l209','Partizipialkonstruktionen - Participle Clauses','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d2','de-b1-l210','Erweiterte Adjektive - Extended Adjective','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d3','de-b1-l211','Nominalisierung - Nominalisation','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d4','de-b1-l212','Funktionsverbgefüge - Function Verb Phrases','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d5','de-b1-l213','Passiv mit Modalverben - Passive+Modal','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d6','de-b1-l214','Zustandspassiv - Stative Passive','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d7','de-b1-l215','Doppelter Infinitiv - Double Infinitive','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d8','de-b1-l216','Genitiv in Texten - Written Genitive','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000d9','de-b1-l217','Konjunktionaladverbien - Connective Adverbs','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000da','de-b1-l218','Textkohärenz - Text Cohesion','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000db','de-b1-l219','Schriftlicher Ausdruck - Written Expression','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000000dc','de-b1-l220','Mündlicher Ausdruck - Spoken Expression','language','de','B1','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000c9',1,'APPROVED','PUBLISHED',
'{"objectives":["Use Konjunktiv II for politeness and hypotheticals","Form würde + infinitive","Use könnte, müsste, dürfte"],"explanation":{"intro":"Konjunktiv II (subjunctive mood) is essential for B1. It expresses hypotheticals, polite requests, and unreal situations. Unlike A2 where you just learned würde, B1 requires fluent use.","culturalNote":"Konjunktiv II makes German sound educated and polished. Würden Sie bitte... is the standard polite register in professional settings. Native speakers mix würde with synthetic forms like könnte, müsste naturally."},"examples":[{"german":"Würden Sie mir bitte helfen?","english":"Would you please help me?"},{"german":"Das könnte ich mir vorstellen.","english":"I could imagine that."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can use Konjunktiv II fluently for politeness and hypotheticals."}}',
'{"items":[{"word":"würden Sie","translation":"would you (polite)","pronunciation":"VÜR-den zee","example":"Würden Sie helfen?"},{"word":"sich vorstellen","translation":"to imagine","pronunciation":"zikh FOR-shtel-en","example":"Ich kann mir vorstellen."},{"word":"müsste","translation":"would have to/should","pronunciation":"MÜS-teh","example":"Das müsste klappen."},{"word":"dürfte","translation":"might/would be allowed to","pronunciation":"DÜR-fteh","example":"Das dürfte schwierig sein."},{"word":"sollte","translation":"should (Konj II)","pronunciation":"ZOL-teh","example":"Er sollte kommen."},{"word":"eigentlich","translation":"actually/really","pronunciation":"EY-gent-likh","example":"Das wäre eigentlich gut."}]}',
'{"title":"Synthetic Konjunktiv II forms","pattern":"könnte, müsste, dürfte, sollte, wäre, hätte (no würde needed)","explanation":"B1 uses synthetic forms directly — no würde wrapper needed. Könnte = could (Konj II of können). Müsste = should/would have to. Dürfte = might (polite). Wäre = would be. Hätte = would have. These are more natural than würde+können etc. Pattern: umlaut stem + -te endings. Können → könnte.","examples":[{"sentence":"Das könnte ein Problem sein.","translation":"That could be a problem."},{"sentence":"Ohne den Regen wäre es perfekt.","translation":"Without the rain it would be perfect."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Dürfte'' means in Konjunktiv II?","options":["might/would be allowed to","must","should","could"],"correctAnswer":"might/would be allowed to"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Would you please help me?","options":["Würden Sie mir bitte helfen?","Können Sie mir helfen?","Helfen Sie mir bitte.","Ich bitte um Hilfe."],"correctAnswer":"Würden Sie mir bitte helfen?"},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das ___ ein Problem sein.","options":["könnte","kann","konnte","wäre"],"correctAnswer":"könnte"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Without the rain it would be perfect","wordBankItems":["Ohne","den","Regen","wäre","es","perfekt","."],"correctAnswer":"Ohne den Regen wäre es perfekt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which is the Konjunktiv II of ''haben''?","options":["hätte","hatte","hat","habe"],"correctAnswer":"hätte"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000ca',1,'APPROVED','PUBLISHED',
'{"objectives":["Build unreal conditional sentences","Use wenn...würde/wäre/hätte","Understand Typ II conditions"],"explanation":{"intro":"Irreale Bedingungssätze (Type II conditionals) describe hypothetical situations that are not true now. Key to B1 level discussions.","culturalNote":"Type II conditionals are common in German discussions about policy, personal decisions, and hypothetical scenarios. If I were chancellor... What would you do if..."},"examples":[{"german":"Wenn ich mehr Zeit hätte, würde ich Klavier lernen.","english":"If I had more time, I would learn piano."},{"german":"Wenn es nicht so teuer wäre, würde ich das kaufen.","english":"If it weren''t so expensive, I would buy it."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can build and understand unreal conditional sentences in German."}}',
'{"items":[{"word":"wenn...hätte","translation":"if...had (unreal)","pronunciation":"VEN...HÄT-teh","example":"Wenn ich Zeit hätte."},{"word":"wenn...wäre","translation":"if...were (unreal)","pronunciation":"VEN...VÄ-reh","example":"Wenn es anders wäre."},{"word":"hätte...gemacht","translation":"would have done","pronunciation":"HÄT-teh...geh-MAKHТ","example":"Ich hätte das gemacht."},{"word":"wäre...gegangen","translation":"would have gone","pronunciation":"VÄ-reh...geh-GAN-gen","example":"Ich wäre gegangen."},{"word":"falls","translation":"in case/if (conditional)","pronunciation":"FALS","example":"Falls es regnet."},{"word":"vorausgesetzt","translation":"provided that","pronunciation":"for-OWS-geh-zetst","example":"Vorausgesetzt, dass."}]}',
'{"title":"Type II conditionals — wenn + Konjunktiv II","pattern":"Wenn [Konj II clause], würde/wäre/hätte [Konj II main clause]","explanation":"Type II: both clauses in Konjunktiv II. Wenn ich Zeit hätte, würde ich kommen. Word order: wenn-clause = verb last; main clause = verb second (würde/wäre/hätte in position 1 or 2). Inversion variant: Wenn-clause first → main clause begins with würde: Würde ich Zeit haben, (dann) käme ich. Advanced: replace würde+infinitive with synthetic Konj II: dann käme ich.","examples":[{"sentence":"Wenn du mich fragtest, würde ich dir helfen.","translation":"If you asked me, I would help you."},{"sentence":"Wenn sie mehr verdiente, wäre sie zufriedener.","translation":"If she earned more, she would be more satisfied."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Vorausgesetzt, dass'' means?","options":["provided that","assuming that","given that","on condition that"],"correctAnswer":"provided that"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"If I had more time, I would learn piano.","options":["Wenn ich mehr Zeit hätte, würde ich Klavier lernen.","Wenn ich Zeit habe, lerne ich Klavier.","Ich würde Klavier lernen.","Mit mehr Zeit Klavier lernen."],"correctAnswer":"Wenn ich mehr Zeit hätte, würde ich Klavier lernen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Wenn es nicht so teuer ___, würde ich das kaufen.","options":["wäre","ist","war","wird"],"correctAnswer":"wäre"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: If you asked me I would help you","wordBankItems":["Wenn","du","mich","fragtest",",","würde","ich","dir","helfen","."],"correctAnswer":"Wenn du mich fragtest , würde ich dir helfen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"In a Type II conditional, both verbs are in which mood?","options":["Konjunktiv II","Konjunktiv I","Indikativ","Imperativ"],"correctAnswer":"Konjunktiv II"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000cb',1,'APPROVED','PUBLISHED',
'{"objectives":["Express wishes in German","Use Wenn doch/nur...!","Know Wunschsätze patterns"],"explanation":{"intro":"German wish sentences have their own structure — Wenn ich doch nur... (If only...). These express unfulfilled desires and are common in authentic speech.","culturalNote":"Wish sentences in German often carry an emotional weight. Wenn ich doch nur mehr Zeit hätte! is a heartfelt wish. Hätte ich nur... (If only I had...) is common in reflections on past regrets."},"examples":[{"german":"Wenn ich doch nur mehr Geld hätte!","english":"If only I had more money!"},{"german":"Hätte ich doch nur besser aufgepasst!","english":"If only I had paid more attention!"}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can express wishes and desires using German subjunctive structures."}}',
'{"items":[{"word":"wenn doch nur","translation":"if only (wish)","pronunciation":"VEN dokh noor","example":"Wenn doch nur..."},{"word":"hätte...doch","translation":"if only...had","pronunciation":"HÄT-teh...dokh","example":"Hätte ich doch."},{"word":"der Wunsch","translation":"wish/desire","pronunciation":"dayr VOONSH","example":"Ein Wunsch bleibt."},{"word":"sich wünschen","translation":"to wish for","pronunciation":"zikh VÜN-shen","example":"Ich wünsche mir."},{"word":"leider Gottes","translation":"unfortunately (emphatic)","pronunciation":"LY-der GOT-es","example":"Leider Gottes nicht."},{"word":"bedauern","translation":"to regret","pronunciation":"beh-DOW-ern","example":"Ich bedauere das."}]}',
'{"title":"Wunschsätze — wish sentences (Konjunktiv II)","pattern":"Wenn [subject] doch [nur/bloß] [Konj II]! / Hätte [subject] doch [nur/bloß]...!","explanation":"Two patterns: 1) Wenn ich doch nur... (present wish): wenn-clause, Konj II, no main clause — exclamation. 2) Hätte/Wäre + doch + [nur/bloß] + Partizip: past regret. Hätte ich das doch nicht getan! Particle doch adds emotional force. Nur or bloß add emphasis: Wenn sie doch bloß käme!","examples":[{"sentence":"Wenn das Wetter doch nur besser wäre!","translation":"If only the weather were better!"},{"sentence":"Wäre ich doch dageblieben!","translation":"If only I had stayed there!"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Bedauern'' means?","options":["to regret","to be sorry","to apologise","to feel sad"],"correctAnswer":"to regret"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"If only I had more money!","options":["Wenn ich doch nur mehr Geld hätte!","Ich wünsche mir mehr Geld.","Hätte ich mehr Geld!","Wenn ich mehr Geld habe."],"correctAnswer":"Wenn ich doch nur mehr Geld hätte!"},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ ich doch dageblieben!","options":["Wäre","Hätte","Würde","Wenn"],"correctAnswer":"Wäre"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: If only the weather were better!","wordBankItems":["Wenn","das","Wetter","doch","nur","besser","wäre","!"],"correctAnswer":"Wenn das Wetter doch nur besser wäre !"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which particle adds emotional force to wish sentences?","options":["doch","auch","ja","mal"],"correctAnswer":"doch"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000cc',1,'APPROVED','PUBLISHED',
'{"objectives":["Use obwohl and trotzdem","Build concessive clauses","Express contrast and concession"],"explanation":{"intro":"Concessive clauses express that something happens despite a contradicting circumstance. Essential for argumentation at B1.","culturalNote":"Obwohl (although) and trotzdem (nevertheless) are high-frequency in German essays, discussions, and formal writing. German academic writing values acknowledging counterarguments (das Einräumen) — concessive clauses are the tool."},"examples":[{"german":"Obwohl es regnete, sind wir spazieren gegangen.","english":"Although it was raining, we went for a walk."},{"german":"Er ist krank, trotzdem geht er zur Arbeit.","english":"He is sick, nevertheless he goes to work."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can use concessive structures to acknowledge counterarguments in German."}}',
'{"items":[{"word":"obwohl","translation":"although/even though","pronunciation":"op-VOHL","example":"Obwohl es regnet."},{"word":"trotzdem","translation":"nevertheless/still","pronunciation":"TROTS-dem","example":"Trotzdem mache ich es."},{"word":"obgleich","translation":"although (formal)","pronunciation":"op-GLYKH","example":"Obgleich es schwer ist."},{"word":"dennoch","translation":"nevertheless (formal)","pronunciation":"DEN-nokh","example":"Dennoch versuche ich."},{"word":"wenngleich","translation":"even though (literary)","pronunciation":"VEN-glykh","example":"Wenngleich es stimmt."},{"word":"ungeachtet","translation":"regardless of","pronunciation":"OON-geh-akh-tet","example":"Ungeachtet der Kosten."}]}',
'{"title":"Obwohl vs. trotzdem — concession","pattern":"obwohl + verb-final clause / trotzdem + verb position 2","explanation":"Obwohl (subordinating conjunction) → verb goes to end: Obwohl es regnete, gingen wir. Trotzdem (adverb) → inverts subject and verb: trotzdem + verb + subject OR main clause position 1: Es regnete, trotzdem gingen wir. Key: obwohl starts a dependent clause; trotzdem is an adverb in the main clause. Never *trotzdem dass.","examples":[{"sentence":"Obwohl er müde ist, arbeitet er weiter.","translation":"Although he is tired, he keeps working."},{"sentence":"Er ist müde, trotzdem arbeitet er weiter.","translation":"He is tired, nevertheless he keeps working."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Dennoch'' means?","options":["nevertheless (formal)","although","despite","however"],"correctAnswer":"nevertheless (formal)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Although it was raining, we went for a walk.","options":["Obwohl es regnete, sind wir spazieren gegangen.","Trotzdem sind wir spazieren gegangen.","Es regnete, aber wir gingen spazieren.","Wir gingen spazieren, obwohl es regnete."],"correctAnswer":"Obwohl es regnete, sind wir spazieren gegangen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er ist krank, ___ geht er zur Arbeit.","options":["trotzdem","obwohl","dennoch","wenngleich"],"correctAnswer":"trotzdem"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Although he is tired he keeps working","wordBankItems":["Obwohl","er","müde","ist",",","arbeitet","er","weiter","."],"correctAnswer":"Obwohl er müde ist , arbeitet er weiter ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"After ''trotzdem'' the verb is in what position?","options":["position 2 (inverted)","position 1","at the end","after subject"],"correctAnswer":"position 2 (inverted)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000cd',1,'APPROVED','PUBLISHED',
'{"objectives":["Use weil, da, denn for causes","Distinguish weil vs. denn","Build causal chains"],"explanation":{"intro":"Causal clauses explain reasons. German has three ways to express because — each with different syntax.","culturalNote":"Weil (because) is the most common. Da (since/as) implies the reason is known to both speakers. Denn (for/because) is a coordinating conjunction used in writing. The Weil am Satzende debate: spoken German sometimes places weil with main clause order (controversial but common)."},"examples":[{"german":"Ich bleibe zu Hause, weil ich krank bin.","english":"I stay at home because I am sick."},{"german":"Da es schon spät ist, gehen wir jetzt.","english":"Since it is already late, we are leaving now."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can express reasons using weil, da, and denn correctly."}}',
'{"items":[{"word":"weil","translation":"because (verb-final)","pronunciation":"VYL","example":"Weil ich müde bin."},{"word":"da","translation":"since/as (known reason)","pronunciation":"DAH","example":"Da es schon spät ist."},{"word":"denn","translation":"for/because (coord.)","pronunciation":"DEN","example":"Ich gehe, denn es ist spät."},{"word":"aus diesem Grund","translation":"for this reason","pronunciation":"ows DEE-zem GROOND","example":"Aus diesem Grund."},{"word":"daher","translation":"therefore/hence","pronunciation":"DAH-hayr","example":"Daher bin ich hier."},{"word":"nämlich","translation":"namely/you see (explains)","pronunciation":"NEM-likh","example":"Es ist nämlich so."}]}',
'{"title":"Weil vs. da vs. denn — three ways to say because","pattern":"weil + verb-final / da + verb-final / denn + normal order","explanation":"Weil and da both send verb to the end (subordinating). Denn is coordinating — verb stays in position 2 after denn: Ich gehe, denn es ist spät. Da implies the listener knows the reason: Da du das weißt... (Since you know this...). Weil is neutral. Key error: never put verb in position 2 after weil (*weil ich bin krank).","examples":[{"sentence":"Da du schon hier bist, können wir anfangen.","translation":"Since you are already here, we can start."},{"sentence":"Er ist spät, denn er hat den Bus verpasst.","translation":"He is late, for he missed the bus."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"After ''denn'', the verb is in what position?","options":["position 2 (normal order)","at the end","position 1","inverted"],"correctAnswer":"position 2 (normal order)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I stay at home because I am sick.","options":["Ich bleibe zu Hause, weil ich krank bin.","Ich bin krank, deshalb bleibe ich zu Hause.","Weil ich krank bin, gehe ich nicht raus.","Ich bleibe, denn ich bin krank."],"correctAnswer":"Ich bleibe zu Hause, weil ich krank bin."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ du schon hier bist, können wir anfangen.","options":["Da","Weil","Denn","Als"],"correctAnswer":"Da"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Since you are already here we can start","wordBankItems":["Da","du","schon","hier","bist",",","können","wir","anfangen","."],"correctAnswer":"Da du schon hier bist , können wir anfangen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Nämlich'' is used to?","options":["explain/clarify (you see)","list examples","contrast","emphasise"],"correctAnswer":"explain/clarify (you see)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000ce',1,'APPROVED','PUBLISHED',
'{"objectives":["Build result clauses with sodass","Use so...dass","Express consequences"],"explanation":{"intro":"Consecutive clauses express results or consequences. So...dass is the key structure at B1.","culturalNote":"Result clauses are common in German news writing and essays. Expressing consequences logically and clearly is a sign of B1+ competence."},"examples":[{"german":"Er sprach so schnell, dass ich nichts verstanden habe.","english":"He spoke so fast that I understood nothing."},{"german":"Es war so kalt, dass das Wasser gefror.","english":"It was so cold that the water froze."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can express results and consequences using so...dass in German."}}',
'{"items":[{"word":"so...dass","translation":"so...that (result)","pronunciation":"zo...dahs","example":"So schnell, dass."},{"word":"sodass","translation":"so that (result, written)","pronunciation":"ZO-dahs","example":"Sodass ich nichts verstand."},{"word":"infolgedessen","translation":"as a result","pronunciation":"in-FOL-geh-des-en","example":"Infolgedessen passierte."},{"word":"somit","translation":"thus/therefore","pronunciation":"ZO-mit","example":"Somit ist es klar."},{"word":"folglich","translation":"consequently","pronunciation":"FOL-klikh","example":"Folglich musste ich."},{"word":"als Folge davon","translation":"as a consequence of that","pronunciation":"als FOL-geh dah-fon","example":"Als Folge davon."}]}',
'{"title":"So + adjective + dass — result clauses","pattern":"so + adjective/adverb + dass + verb-final clause","explanation":"So + adjective + dass expresses result: Er war so müde, dass er einschlief = He was so tired that he fell asleep. Dass introduces the result clause (verb-final). Note: adjective stays in base form after so (not comparative). Sodass (one word) = so that (consequential): Er rief an, sodass ich Bescheid wusste = He called so that I knew.","examples":[{"sentence":"Die Prüfung war so schwer, dass viele durchfielen.","translation":"The exam was so hard that many failed."},{"sentence":"Er lernte hart, sodass er bestand.","translation":"He studied hard so that he passed."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Folglich'' means?","options":["consequently","therefore","as a result","thus"],"correctAnswer":"consequently"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"He spoke so fast that I understood nothing.","options":["Er sprach so schnell, dass ich nichts verstanden habe.","Er sprach schnell, deshalb verstand ich nichts.","So schnell sprach er.","Ich verstand nichts, weil er schnell sprach."],"correctAnswer":"Er sprach so schnell, dass ich nichts verstanden habe."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Prüfung war so schwer, ___ viele durchfielen.","options":["dass","sodass","weil","damit"],"correctAnswer":"dass"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: He studied hard so that he passed","wordBankItems":["Er","lernte","hart",",","sodass","er","bestand","."],"correctAnswer":"Er lernte hart , sodass er bestand ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"After ''so + adjective'', the adjective is in what form?","options":["base form (not comparative)","comparative","superlative","inflected form"],"correctAnswer":"base form (not comparative)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000cf',1,'APPROVED','PUBLISHED',
'{"objectives":["Express purpose with damit and um...zu","Distinguish damit vs um...zu","Use purpose clauses naturally"],"explanation":{"intro":"Purpose clauses answer the question why or for what purpose. B1 requires fluent use of both damit and um...zu.","culturalNote":"Damit (so that) when subjects differ; um...zu when subjects are the same. This distinction signals B1 competence. Mistakenly using damit for same-subject sentences is a common learner error."},"examples":[{"german":"Er lernt Deutsch, damit er in Deutschland arbeiten kann.","english":"He learns German so that he can work in Germany."},{"german":"Sie geht früh ins Bett, um ausgeschlafen zu sein.","english":"She goes to bed early in order to be well-rested."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can express purpose using damit and um...zu correctly in German."}}',
'{"items":[{"word":"damit","translation":"so that (different subjects)","pronunciation":"dah-MIT","example":"Damit er kann."},{"word":"um...zu","translation":"in order to (same subject)","pronunciation":"OOM...TSOO","example":"Um zu lernen."},{"word":"zu dem Zweck","translation":"for the purpose of","pronunciation":"tsoo dem TSVEK","example":"Zu dem Zweck, dass."},{"word":"absichtlich","translation":"on purpose/intentionally","pronunciation":"AP-zikht-likh","example":"Absichtlich gemacht."},{"word":"das Ziel","translation":"goal/aim","pronunciation":"dahs TSEEL","example":"Das Ziel erreichen."},{"word":"beabsichtigt","translation":"intended/deliberate","pronunciation":"beh-AP-zikh-tikht","example":"Beabsichtigt handeln."}]}',
'{"title":"Damit vs. um...zu — purpose distinction","pattern":"damit + different subject / um + same subject + zu + infinitive","explanation":"Same subject → um...zu: Ich lerne, um besser zu werden (I learn in order to improve — same person). Different subjects → damit: Ich lerne, damit meine Kinder stolz sind (I learn so that my children are proud — different subjects). Um...zu: infinitive goes to the end, zu before it. Damit clause: verb-final, new subject after damit.","examples":[{"sentence":"Sie spart, um eine Reise machen zu können.","translation":"She saves up in order to be able to take a trip."},{"sentence":"Er kocht, damit seine Familie gut isst.","translation":"He cooks so that his family eats well."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Which conjunction requires SAME subject?","options":["um...zu","damit","sodass","weil"],"correctAnswer":"um...zu"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"He learns German so that he can work in Germany.","options":["Er lernt Deutsch, damit er in Deutschland arbeiten kann.","Er lernt Deutsch, um in Deutschland zu arbeiten.","Damit er arbeitet, lernt er Deutsch.","Er möchte in Deutschland arbeiten."],"correctAnswer":"Er lernt Deutsch, damit er in Deutschland arbeiten kann."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Sie spart, ___ eine Reise machen zu können.","options":["um","damit","sodass","weil"],"correctAnswer":"um"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: He cooks so that his family eats well","wordBankItems":["Er","kocht",",","damit","seine","Familie","gut","isst","."],"correctAnswer":"Er kocht , damit seine Familie gut isst ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Absichtlich'' means?","options":["on purpose/intentionally","accidentally","deliberately","by chance"],"correctAnswer":"on purpose/intentionally"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d0',1,'APPROVED','PUBLISHED',
'{"objectives":["Use indem and dadurch dass","Express means and manner","Build modal clauses"],"explanation":{"intro":"Modal clauses express how or by what means something is done. Indem (by -ing) is the key B1 structure.","culturalNote":"Indem (by doing) is very common in instructions, advice, and explanations. It shows causal mechanism. Dadurch, dass is a more formal alternative. Both are high-frequency in German texts."},"examples":[{"german":"Indem man täglich übt, verbessert man seine Aussprache.","english":"By practising daily, one improves one''s pronunciation."},{"german":"Er hat Geld gespart, indem er öfter zu Hause gegessen hat.","english":"He saved money by eating at home more often."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can use indem to express means and manner in German."}}',
'{"items":[{"word":"indem","translation":"by (doing)/by means of","pronunciation":"in-DEM","example":"Indem man übt."},{"word":"dadurch, dass","translation":"by the fact that","pronunciation":"DAH-doorkh dahs","example":"Dadurch, dass er."},{"word":"auf diese Weise","translation":"in this way/thus","pronunciation":"owf DEE-zeh VY-zeh","example":"Auf diese Weise."},{"word":"die Methode","translation":"method","pronunciation":"dee meh-TOH-deh","example":"Eine gute Methode."},{"word":"verbessern","translation":"to improve","pronunciation":"fer-BES-ern","example":"Verbessern durch Üben."},{"word":"die Aussprache","translation":"pronunciation","pronunciation":"dee OWS-sprakh-eh","example":"Gute Aussprache."}]}',
'{"title":"Indem — by doing (modal clause)","pattern":"indem + verb-final clause (by doing — simultaneous action as means)","explanation":"Indem (by -ing) shows the means. The indem-clause and main clause share the same time frame (simultaneous). Indem man täglich übt, verbessert man sich = By practising daily, one improves. Verb final after indem. Note: indem ≠ purpose (not um...zu); it''s HOW, not WHY. Dadurch, dass + verb-final is a formal alternative: Dadurch, dass er täglich übt...","examples":[{"sentence":"Indem sie freundlich ist, gewinnt sie Vertrauen.","translation":"By being friendly, she gains trust."},{"sentence":"Man lernt, indem man Fehler macht.","translation":"One learns by making mistakes."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Indem'' expresses?","options":["means/how","purpose/why","cause/because","time/when"],"correctAnswer":"means/how"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"By practising daily one improves one''s pronunciation.","options":["Indem man täglich übt, verbessert man seine Aussprache.","Man übt täglich und verbessert sich.","Um die Aussprache zu verbessern, übt man täglich.","Täglich üben verbessert die Aussprache."],"correctAnswer":"Indem man täglich übt, verbessert man seine Aussprache."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Man lernt, ___ man Fehler macht.","options":["indem","damit","sodass","wenn"],"correctAnswer":"indem"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: By being friendly she gains trust","wordBankItems":["Indem","sie","freundlich","ist",",","gewinnt","sie","Vertrauen","."],"correctAnswer":"Indem sie freundlich ist , gewinnt sie Vertrauen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Aussprache'' means?","options":["pronunciation","expression","articulation","speech"],"correctAnswer":"pronunciation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d1',1,'APPROVED','PUBLISHED',
'{"objectives":["Use participial constructions","Convert relative clauses to participles","Read formal German texts"],"explanation":{"intro":"Participial constructions (Partizipialkonstruktionen) replace relative clauses in formal/written German. They are compact and common in news and academic writing.","culturalNote":"Partizipialkonstruktionen are a hallmark of written German. Newspaper headlines and academic texts use them extensively. Understanding them is key for B1 reading comprehension."},"examples":[{"german":"Der in Berlin geborene Komponist wurde weltberühmt.","english":"The composer born in Berlin became world-famous."},{"german":"Die auf dem Tisch liegenden Dokumente gehören dem Chef.","english":"The documents lying on the table belong to the boss."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can understand and build participial constructions in German."}}',
'{"items":[{"word":"das Partizip I","translation":"present participle (-end)","pronunciation":"dahs par-TEE-tseep ershter","example":"laufend, lesend."},{"word":"das Partizip II","translation":"past participle (-t/-en)","pronunciation":"dahs par-TEE-tseep tsvyter","example":"gelesen, gemacht."},{"word":"der in Berlin geborene","translation":"the one born in Berlin","pronunciation":"dayr in ber-LEEN geh-BOH-reh-neh","example":"Der Geborene."},{"word":"die liegenden","translation":"the lying/resting ones","pronunciation":"dee LEE-gen-den","example":"Die liegenden Bücher."},{"word":"das verwendete","translation":"the used one","pronunciation":"dahs fer-VEN-deh-teh","example":"Das verwendete Material."},{"word":"ausführlich","translation":"detailed/at length","pronunciation":"OWS-für-likh","example":"Ausführlich erklären."}]}',
'{"title":"Extended participial attribute","pattern":"[participial phrase with adjective ending] + noun","explanation":"German participles act as adjectives: der liegende Mann = the lying man. Extended: der auf dem Sofa liegende Mann = the man lying on the sofa. Partizip I (present, active): liegend → der liegende. Partizip II (past, passive): geboren → der geborene. The entire participial phrase (with all modifiers) comes between article and noun. Adjective ending matches gender/case.","examples":[{"sentence":"Das von vielen gelesene Buch ist ein Bestseller.","translation":"The book read by many is a bestseller."},{"sentence":"Der im Regen stehende Mann ist mein Vater.","translation":"The man standing in the rain is my father."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Partizip I is formed with which suffix?","options":["-end","-t","-en","-lich"],"correctAnswer":"-end"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The composer born in Berlin became world-famous.","options":["Der in Berlin geborene Komponist wurde weltberühmt.","Der Komponist, der in Berlin geboren wurde, ist berühmt.","Ein Berliner Komponist wurde berühmt.","Der berühmte Berliner Komponist."],"correctAnswer":"Der in Berlin geborene Komponist wurde weltberühmt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das von vielen ___ Buch ist ein Bestseller.","options":["gelesene","lesende","gelesen","liest"],"correctAnswer":"gelesene"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The man standing in the rain is my father","wordBankItems":["Der","im","Regen","stehende","Mann","ist","mein","Vater","."],"correctAnswer":"Der im Regen stehende Mann ist mein Vater ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"In an extended participial attribute, the participle+modifiers go?","options":["between article and noun","after the noun","before the article","at the end"],"correctAnswer":"between article and noun"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d2',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand extended adjective attributes","Decode complex noun phrases","Read formal German structures"],"explanation":{"intro":"Extended adjective attributes (erweiterte Adjektivattribute) stack multiple modifiers before a noun — a key feature of written German.","culturalNote":"This structure is so characteristic of German that it is sometimes called the Nominalklammer (noun bracket). News headlines and legal texts pile up modifiers: die heute in Berlin stattgefundene außerordentliche Sitzung des Bundestages (today''s extraordinary session of the Bundestag held in Berlin)."},"examples":[{"german":"Die von der Regierung geplante neue Steuerreform ist umstritten.","english":"The new tax reform planned by the government is controversial."},{"german":"Das schnell wachsende Unternehmen sucht Mitarbeiter.","english":"The rapidly growing company is looking for employees."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can decode and construct extended adjective attributes in German."}}',
'{"items":[{"word":"das Attribut","translation":"attribute/modifier","pronunciation":"dahs at-ree-BOOT","example":"Ein erweitertes Attribut."},{"word":"umstritten","translation":"controversial/disputed","pronunciation":"OOM-shtrit-en","example":"Umstritten sein."},{"word":"wachsend","translation":"growing/expanding","pronunciation":"VAK-send","example":"Ein wachsendes Unternehmen."},{"word":"die Steuerreform","translation":"tax reform","pronunciation":"dee SHTOY-er-reh-form","example":"Die Steuerreform."},{"word":"geplant","translation":"planned","pronunciation":"geh-PLANT","example":"Der geplante Termin."},{"word":"stattfindend","translation":"taking place","pronunciation":"SHTАT-fin-dend","example":"Die stattfindende Veranstaltung."}]}',
'{"title":"Stacking modifiers before a noun","pattern":"article + [adverb + Partizip I/II + other adjectives] + noun","explanation":"Multiple modifiers stack before the noun, between article and noun. Order: adverb → partizip/adjective → noun. Das schnell wachsende Unternehmen = The rapidly growing company. Das von der Regierung geplante neue Gesetz = The new law planned by the government. Strategy for reading: find the article, find the noun (end of cluster), then parse the modifiers inside. All modifiers agree in gender/case with the noun.","examples":[{"sentence":"Die kürzlich veröffentlichte Studie zeigt interessante Ergebnisse.","translation":"The recently published study shows interesting results."},{"sentence":"Das neu eröffnete Restaurant ist sehr beliebt.","translation":"The newly opened restaurant is very popular."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Umstritten'' means?","options":["controversial/disputed","uncertain","debated","questioned"],"correctAnswer":"controversial/disputed"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The rapidly growing company is looking for employees.","options":["Das schnell wachsende Unternehmen sucht Mitarbeiter.","Das wachsende Unternehmen.","Das Unternehmen wächst schnell.","Schnell wachsendes Unternehmen."],"correctAnswer":"Das schnell wachsende Unternehmen sucht Mitarbeiter."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die kürzlich ___ Studie zeigt interessante Ergebnisse.","options":["veröffentlichte","veröffentlicht","veröffentlichende","veröffentlichen"],"correctAnswer":"veröffentlichte"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The newly opened restaurant is very popular","wordBankItems":["Das","neu","eröffnete","Restaurant","ist","sehr","beliebt","."],"correctAnswer":"Das neu eröffnete Restaurant ist sehr beliebt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"When reading extended attributes, the strategy is?","options":["find article, find noun, parse inside","read left to right","find the verb first","find adjective first"],"correctAnswer":"find article, find noun, parse inside"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d3',1,'APPROVED','PUBLISHED',
'{"objectives":["Convert verbs to nouns","Use nominalisation in writing","Understand die Nominalisierung"],"explanation":{"intro":"Nominalisation (converting verbs and adjectives into nouns) is a key feature of formal German. B1 requires recognising and producing nominalisations.","culturalNote":"German Nominalstil (nominal style) is prevalent in official documents, academic writing, and journalism. Das Fahren (driving), die Verbesserung (improvement), das Scheitern (failure) — nouns derived from verbs are everywhere."},"examples":[{"german":"Das Lernen einer Fremdsprache erfordert Geduld.","english":"Learning a foreign language requires patience."},{"german":"Die Verbesserung der Infrastruktur ist notwendig.","english":"The improvement of the infrastructure is necessary."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can recognise and use nominalisations in formal German writing."}}',
'{"items":[{"word":"das Lernen","translation":"(the) learning","pronunciation":"dahs LERN-en","example":"Das Lernen ist wichtig."},{"word":"die Verbesserung","translation":"improvement","pronunciation":"dee fer-BES-er-oong","example":"Die Verbesserung."},{"word":"das Scheitern","translation":"failure/failing","pronunciation":"dahs SHY-tern","example":"Das Scheitern ist normal."},{"word":"die Notwendigkeit","translation":"necessity","pronunciation":"dee NOT-ven-dikh-kyt","example":"Eine Notwendigkeit."},{"word":"die Anforderung","translation":"requirement/demand","pronunciation":"dee AN-for-der-oong","example":"Hohe Anforderungen."},{"word":"nominalisieren","translation":"to nominalise","pronunciation":"no-mee-nah-lee-ZEER-en","example":"Ein Verb nominalisieren."}]}',
'{"title":"Nominalisation — infinitive as noun","pattern":"infinitive → das [Infinitive] (neuter noun): das Lernen, das Fahren, das Schreiben","explanation":"Any German infinitive can become a neuter noun by capitalising and adding das: fahren → das Fahren = driving. These nouns take genitive, dative etc.: beim Lernen (while learning), zum Schreiben (for writing). Verb nominalisations with -ung suffix: verbessern → die Verbesserung. Adjective nominalisations: notwendig → die Notwendigkeit (-keit suffix). Very productive in formal register.","examples":[{"sentence":"Das Rauchen ist im Gebäude verboten.","translation":"Smoking is forbidden in the building."},{"sentence":"Beim Kochen höre ich gerne Musik.","translation":"While cooking I like to listen to music."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Nominalised infinitives in German are?","options":["neuter (das)","masculine (der)","feminine (die)","varies by verb"],"correctAnswer":"neuter (das)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Learning a foreign language requires patience.","options":["Das Lernen einer Fremdsprache erfordert Geduld.","Man muss Geduld haben beim Sprachenlernen.","Fremdsprachen lernen ist schwer.","Ich brauche Geduld beim Lernen."],"correctAnswer":"Das Lernen einer Fremdsprache erfordert Geduld."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ Kochen höre ich gerne Musik.","options":["Beim","Im","Am","Mit"],"correctAnswer":"Beim"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Smoking is forbidden in the building","wordBankItems":["Das","Rauchen","ist","im","Gebäude","verboten","."],"correctAnswer":"Das Rauchen ist im Gebäude verboten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which suffix forms nouns from verbs meaning a process/result?","options":["-ung","-heit","-keit","-schaft"],"correctAnswer":"-ung"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d4',1,'APPROVED','PUBLISHED',
'{"objectives":["Recognise function verb phrases","Use Bescheid geben, in Betracht ziehen","Decode bureaucratic language"],"explanation":{"intro":"Funktionsverbgefüge (function verb phrases) are fixed phrases combining a content noun with a light verb. Common in formal and official German.","culturalNote":"German official language is full of Funktionsverbgefüge. Administrative documents, laws, and business correspondence prefer them over simple verbs. Knowing them is key for navigating official life in Germany."},"examples":[{"german":"In Betracht ziehen bedeutet dasselbe wie berücksichtigen.","english":"To take into consideration means the same as to consider."},{"german":"Der Chef hat Bescheid gegeben, dass die Sitzung ausfällt.","english":"The boss gave notice that the meeting is cancelled."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can recognise and use common function verb phrases in German."}}',
'{"items":[{"word":"in Betracht ziehen","translation":"to consider/take into account","pronunciation":"in beh-TRAKHT TSEE-en","example":"In Betracht ziehen."},{"word":"Bescheid geben","translation":"to notify/let know","pronunciation":"beh-SHYD GAY-ben","example":"Bescheid geben."},{"word":"in Frage kommen","translation":"to come into question/be possible","pronunciation":"in FRAH-geh KOM-en","example":"Das kommt in Frage."},{"word":"zur Verfügung stellen","translation":"to make available","pronunciation":"tsoor fer-FÜ-goong SHTEL-en","example":"Ressourcen bereitstellen."},{"word":"Kritik üben an","translation":"to criticise","pronunciation":"kree-TEEK Ü-ben an","example":"Kritik üben an."},{"word":"in Anspruch nehmen","translation":"to make use of/claim","pronunciation":"in AN-sproohk NEY-men","example":"Zeit in Anspruch nehmen."}]}',
'{"title":"Funktionsverbgefüge — function verb phrases","pattern":"noun + light verb (stellen, ziehen, nehmen, üben, geben, kommen)","explanation":"Funktionsverbgefüge = content noun + light verb. The verb is semantically empty; meaning is in the noun. In Betracht ziehen ≈ berücksichtigen. Zur Verfügung stellen ≈ bereitstellen. These are frozen phrases — don''t try to modify the noun. In Betracht nehmen is wrong (*in die Betracht ziehen). Recognise them as units. Very frequent in formal writing, administration, and job contexts.","examples":[{"sentence":"Diese Option kommt für uns nicht in Frage.","translation":"This option is not possible for us."},{"sentence":"Bitte stellen Sie uns die Unterlagen zur Verfügung.","translation":"Please make the documents available to us."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Zur Verfügung stellen'' means?","options":["to make available","to provide","to supply","to offer"],"correctAnswer":"to make available"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The boss gave notice that the meeting is cancelled.","options":["Der Chef hat Bescheid gegeben, dass die Sitzung ausfällt.","Der Chef sagte, dass die Sitzung ausfällt.","Die Sitzung fällt aus.","Der Chef informierte uns."],"correctAnswer":"Der Chef hat Bescheid gegeben, dass die Sitzung ausfällt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Diese Option kommt für uns nicht in ___.","options":["Frage","Betracht","Anspruch","Frage kommen"],"correctAnswer":"Frage"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Please make the documents available to us","wordBankItems":["Bitte","stellen","Sie","uns","die","Unterlagen","zur","Verfügung","."],"correctAnswer":"Bitte stellen Sie uns die Unterlagen zur Verfügung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"In Funktionsverbgefüge, the meaning is carried by?","options":["the noun","the verb","both equally","the preposition"],"correctAnswer":"the noun"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d5',1,'APPROVED','PUBLISHED',
'{"objectives":["Combine passive with modal verbs","Use müssen/können/dürfen + Passiv","Express obligation and permission passively"],"explanation":{"intro":"Passive with modals combines two key B1 structures. Very common in official notices, instructions, and regulations.","culturalNote":"Passiv + Modal is the standard voice for regulations and rules in Germany. Hier darf nicht geraucht werden = Smoking is not allowed here. Es muss etwas getan werden = Something must be done. Signs, laws, and official documents use this structure heavily."},"examples":[{"german":"Das Formular muss vollständig ausgefüllt werden.","english":"The form must be filled in completely."},{"german":"Hier darf nicht geparkt werden.","english":"Parking is not permitted here."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can combine passive voice with modal verbs in German."}}',
'{"items":[{"word":"muss...werden","translation":"must be (done)","pronunciation":"moos...VER-den","example":"Es muss gemacht werden."},{"word":"darf nicht...werden","translation":"must not be (done)","pronunciation":"darf nikht...VER-den","example":"Darf nicht betreten werden."},{"word":"kann...werden","translation":"can be (done)","pronunciation":"kan...VER-den","example":"Es kann geändert werden."},{"word":"soll...werden","translation":"is supposed to be (done)","pronunciation":"zol...VER-den","example":"Soll abgeschlossen werden."},{"word":"die Vorschrift","translation":"regulation/rule","pronunciation":"dee FOR-shrift","example":"Eine Vorschrift einhalten."},{"word":"einhalten","translation":"to comply with/observe","pronunciation":"YN-hal-ten","example":"Vorschriften einhalten."}]}',
'{"title":"Passiv + Modalverb","pattern":"subject + modal verb + [object] + Partizip II + werden (infinitive)","explanation":"Passiv + Modal: modal verb conjugated + Partizip II + werden at end. Das muss gemacht werden = That must be done. Word order: modal in position 2, werden at end (as in all passive sentences with modals). Note: werden stays as infinitive (not wird) because modal already carries the finite form. Es kann nicht ausgeschlossen werden = It cannot be ruled out.","examples":[{"sentence":"Die Steuern müssen bis Ende April gezahlt werden.","translation":"Taxes must be paid by the end of April."},{"sentence":"Dieser Fehler kann leicht korrigiert werden.","translation":"This error can easily be corrected."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"In Passiv + Modal, ''werden'' is in what form?","options":["infinitive","present tense","past tense","Konjunktiv"],"correctAnswer":"infinitive"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The form must be filled in completely.","options":["Das Formular muss vollständig ausgefüllt werden.","Das Formular wird ausgefüllt.","Man muss das Formular ausfüllen.","Das Formular ausfüllen."],"correctAnswer":"Das Formular muss vollständig ausgefüllt werden."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Hier darf nicht geparkt ___.","options":["werden","worden","werde","wird"],"correctAnswer":"werden"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Taxes must be paid by the end of April","wordBankItems":["Die","Steuern","müssen","bis","Ende","April","gezahlt","werden","."],"correctAnswer":"Die Steuern müssen bis Ende April gezahlt werden ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Einhalten'' means?","options":["to comply with/observe","to hold in","to maintain","to keep"],"correctAnswer":"to comply with/observe"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d6',1,'APPROVED','PUBLISHED',
'{"objectives":["Use Zustandspassiv (stative passive)","Distinguish sein-Passiv from werden-Passiv","Describe resulting states"],"explanation":{"intro":"Zustandspassiv (sein-passive) describes the result of an action, not the action itself. Essential for describing states at B1.","culturalNote":"Zustandspassiv is common in everyday German for describing results. Das Fenster ist geöffnet (the window is open — describes state). Vs. Das Fenster wird geöffnet (the window is being opened — describes the action)."},"examples":[{"german":"Das Geschäft ist geschlossen — der Besitzer ist im Urlaub.","english":"The shop is closed — the owner is on holiday."},{"german":"Die Aufgabe ist erledigt.","english":"The task is done."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can distinguish and use Zustandspassiv and Vorgangspassiv correctly."}}',
'{"items":[{"word":"ist geschlossen","translation":"is closed (state)","pronunciation":"ist geh-SHLOS-en","example":"Das Fenster ist geschlossen."},{"word":"ist erledigt","translation":"is done/finished","pronunciation":"ist er-LEY-dikht","example":"Die Aufgabe ist erledigt."},{"word":"ist geöffnet","translation":"is open (state)","pronunciation":"ist geh-ÖF-net","example":"Die Tür ist geöffnet."},{"word":"der Zustand","translation":"state/condition","pronunciation":"dayr TSOO-shtant","example":"Einen Zustand beschreiben."},{"word":"der Vorgang","translation":"process/action","pronunciation":"dayr FOR-gang","example":"Ein Vorgang."},{"word":"abgeschlossen","translation":"completed/locked","pronunciation":"AP-geh-shlos-en","example":"Abgeschlossen sein."}]}',
'{"title":"Zustandspassiv vs. Vorgangspassiv","pattern":"Zustandspassiv: sein + Partizip II (state) / Vorgangspassiv: werden + Partizip II (action)","explanation":"Vorgangspassiv (werden): Das Fenster wird geöffnet = The window is being opened (ongoing action). Zustandspassiv (sein): Das Fenster ist geöffnet = The window is open (resulting state). Test: can you say ''right now''? → werden. Can you say ''currently in that condition''? → sein. Past Zustandspassiv: Das Fenster war geöffnet.","examples":[{"sentence":"Der Brief ist unterschrieben.","translation":"The letter is signed (state — has been signed)."},{"sentence":"Der Brief wird unterschrieben.","translation":"The letter is being signed (action in progress)."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Brief ist unterschrieben'' describes a?","options":["resulting state","ongoing action","completed action","future action"],"correctAnswer":"resulting state"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The task is done.","options":["Die Aufgabe ist erledigt.","Die Aufgabe wird erledigt.","Die Aufgabe war erledigt.","Ich habe die Aufgabe erledigt."],"correctAnswer":"Die Aufgabe ist erledigt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Fenster ___ gerade geöffnet. (action in progress)","options":["wird","ist","war","wäre"],"correctAnswer":"wird"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The letter is signed (state)","wordBankItems":["Der","Brief","ist","unterschrieben","."],"correctAnswer":"Der Brief ist unterschrieben ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Abgeschlossen'' means?","options":["completed/locked","finished","concluded","terminated"],"correctAnswer":"completed/locked"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d7',1,'APPROVED','PUBLISHED',
'{"objectives":["Form double infinitive constructions","Use with lassen, helfen, sehen, hören","Understand Ersatzinfinitiv"],"explanation":{"intro":"Double infinitive constructions occur with certain verbs in perfect tenses. The Ersatzinfinitiv (substitute infinitive) replaces the past participle.","culturalNote":"Double infinitives are a distinctive German structure. In Perfekt with modal+infinitive, two infinitives appear: Ich habe kommen müssen = I had to come. Word order in main clauses: double infinitive cluster at the end."},"examples":[{"german":"Ich habe gestern nicht schlafen können.","english":"I was not able to sleep yesterday."},{"german":"Sie hat das Kind weinen lassen.","english":"She let the child cry."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can form and understand double infinitive (Ersatzinfinitiv) constructions."}}',
'{"items":[{"word":"habe...können","translation":"was able to (Perfekt)","pronunciation":"HAH-beh...KÖN-en","example":"Habe schlafen können."},{"word":"habe...lassen","translation":"let/had done (Perfekt)","pronunciation":"HAH-beh...LAS-en","example":"Hat machen lassen."},{"word":"der Ersatzinfinitiv","translation":"substitute infinitive","pronunciation":"dayr er-ZATS-in-fee-nee-teef","example":"Ersatzinfinitiv bilden."},{"word":"habe...müssen","translation":"had to (Perfekt)","pronunciation":"HAH-beh...MÜS-en","example":"Habe warten müssen."},{"word":"habe...sehen","translation":"saw (Perfekt perception)","pronunciation":"HAH-beh...ZAY-en","example":"Habe kommen sehen."},{"word":"der Nebensatz","translation":"subordinate clause","pronunciation":"dayr NAY-ben-zats","example":"Ein Nebensatz."}]}',
'{"title":"Ersatzinfinitiv — infinitive instead of Partizip II","pattern":"With modals/lassen/perception verbs in Perfekt: [haben + infinitive + infinitive] NOT [haben + Partizip II]","explanation":"Normally Perfekt = haben + Partizip II. But with modals (können/müssen/dürfen/wollen/sollen/mögen), lassen, sehen, hören, helfen — use infinitive not Partizip II in Perfekt: Ich habe kommen müssen (NOT *gemusst). Ich habe das Auto reparieren lassen (NOT *gelassen). In subordinate clauses: double infinitive at the very end: ...weil ich habe kommen müssen.","examples":[{"sentence":"Er hat ihr helfen wollen.","translation":"He wanted to help her."},{"sentence":"Wir haben das Konzert kommen hören.","translation":"We heard the concert coming."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Ersatzinfinitiv'' means?","options":["substitute infinitive","double infinitive","modal infinitive","auxiliary infinitive"],"correctAnswer":"substitute infinitive"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I was not able to sleep yesterday.","options":["Ich habe gestern nicht schlafen können.","Ich konnte gestern nicht schlafen.","Ich habe nicht geschlafen können.","Gestern konnte ich schlafen nicht."],"correctAnswer":"Ich habe gestern nicht schlafen können."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er hat ihr helfen ___.","options":["wollen","gewollt","will","wollte"],"correctAnswer":"wollen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She let the child cry","wordBankItems":["Sie","hat","das","Kind","weinen","lassen","."],"correctAnswer":"Sie hat das Kind weinen lassen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Which of these correctly uses Ersatzinfinitiv?","options":["ich habe kommen müssen","ich habe gemusst zu kommen","ich habe müssen kommen","ich bin kommen müssen"],"correctAnswer":"ich habe kommen müssen"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d8',1,'APPROVED','PUBLISHED',
'{"objectives":["Use genitive in formal writing","Know von as genitive substitute","Read genitive in texts"],"explanation":{"intro":"The genitive case appears in formal writing, literature, and legal texts. B1 requires reading it fluently and beginning to use it actively.","culturalNote":"While spoken German increasingly replaces genitive with von+dative (wegen dem Regen instead of wegen des Regens), written German and formal contexts preserve genitive. Academic texts, journalism, and official documents use genitive extensively."},"examples":[{"german":"Die Ergebnisse des Berichts wurden veröffentlicht.","english":"The results of the report were published."},{"german":"Wegen des schlechten Wetters wurde das Fest abgesagt.","english":"Because of the bad weather the festival was cancelled."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can use and read genitive in formal German writing contexts."}}',
'{"items":[{"word":"des Berichts","translation":"of the report (gen.)","pronunciation":"des beh-RIKHTS","example":"Ergebnisse des Berichts."},{"word":"wegen des Wetters","translation":"because of the weather","pronunciation":"VAY-gen des VET-ers","example":"Wegen des Wetters."},{"word":"aufgrund des","translation":"on account of the","pronunciation":"OWF-groond des","example":"Aufgrund des Mangels."},{"word":"trotz des","translation":"despite the (gen.)","pronunciation":"TROTS des","example":"Trotz des Regens."},{"word":"statt des","translation":"instead of the","pronunciation":"shtat des","example":"Statt des Chefs."},{"word":"innerhalb des","translation":"within the","pronunciation":"IN-er-halp des","example":"Innerhalb des Jahres."}]}',
'{"title":"Genitive prepositions — wegen, aufgrund, trotz, statt","pattern":"wegen/aufgrund/trotz/statt + genitive noun","explanation":"Key genitive prepositions: wegen (because of), aufgrund (on account of), trotz (despite), statt (instead of), während (during), innerhalb (within), außerhalb (outside of). Masculine/neuter: des + noun + -(e)s. Feminine: der. Plural: der. Wegen des Regens = because of the rain. Trotz des Wetters = despite the weather. Colloquial: wegen dem (dative) is accepted in speech but avoid in formal writing.","examples":[{"sentence":"Aufgrund des Streiks fährt kein Bus.","translation":"Due to the strike no bus is running."},{"sentence":"Innerhalb des nächsten Monats wird gebaut.","translation":"Within the next month construction will take place."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Aufgrund des'' means?","options":["on account of/due to","because of","as a result of","owing to"],"correctAnswer":"on account of/due to"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Because of the bad weather the festival was cancelled.","options":["Wegen des schlechten Wetters wurde das Fest abgesagt.","Das Fest wurde abgesagt wegen dem Wetter.","Das schlechte Wetter hat das Fest abgesagt.","Das Fest fiel wegen Regen aus."],"correctAnswer":"Wegen des schlechten Wetters wurde das Fest abgesagt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Aufgrund ___ Streiks fährt kein Bus.","options":["des","dem","den","der"],"correctAnswer":"des"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Within the next month construction will take place","wordBankItems":["Innerhalb","des","nächsten","Monats","wird","gebaut","."],"correctAnswer":"Innerhalb des nächsten Monats wird gebaut ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Genitive of masculine nouns adds which ending?","options":["-(e)s to the noun","none","-en","-em"],"correctAnswer":"-(e)s to the noun"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000d9',1,'APPROVED','PUBLISHED',
'{"objectives":["Use connective adverbs for text cohesion","Know deshalb, daher, deswegen, jedoch, allerdings","Understand function in text"],"explanation":{"intro":"Konjunktionaladverbien (connective adverbs) are essential for creating coherent texts. They show logical relationships between sentences.","culturalNote":"German academic and journalistic writing values clear logical connectors. Allerdings (however/admittedly), jedoch (however), deshalb (therefore), daher (hence) are all high-frequency in formal written German. Using them correctly signals B1+ competence."},"examples":[{"german":"Das Projekt ist teuer. Deshalb brauchen wir mehr Budget.","english":"The project is expensive. Therefore we need more budget."},{"german":"Er arbeitet viel. Allerdings verdient er nicht viel.","english":"He works a lot. However, he does not earn much."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can use connective adverbs to build cohesive texts in German."}}',
'{"items":[{"word":"deshalb/daher/deswegen","translation":"therefore/hence/that is why","pronunciation":"DES-halp/DAH-hayr/DES-vay-gen","example":"Deshalb gehe ich."},{"word":"allerdings","translation":"however/admittedly","pronunciation":"AL-er-dings","example":"Allerdings ist es schwer."},{"word":"jedoch","translation":"however/yet","pronunciation":"yeh-DOKH","example":"Jedoch ist es möglich."},{"word":"außerdem","translation":"moreover/besides","pronunciation":"OW-ser-dem","example":"Außerdem ist es günstig."},{"word":"im Gegenteil","translation":"on the contrary","pronunciation":"im GAY-gen-tyl","example":"Im Gegenteil."},{"word":"infolgedessen","translation":"as a result/consequently","pronunciation":"in-FOL-geh-DES-en","example":"Infolgedessen entschied."}]}',
'{"title":"Connective adverbs — position 1 or after comma","pattern":"[Sentence]. Connective adverb + [inverted verb]... OR [clause], [connective adverb] + [inverted clause]","explanation":"Connective adverbs cause subject-verb inversion: deshalb + verb + subject. Es ist teuer. Deshalb brauchen wir mehr Geld. Note: allerdings/jedoch typically in position 1 or after a comma mid-sentence. Jedoch also used within a clause: Er ist jung, jedoch sehr erfahren. Distinction: deshalb/daher/deswegen = result (because of this, therefore); allerdings/jedoch = concession (however).","examples":[{"sentence":"Die Kosten sind hoch. Allerdings ist die Qualität gut.","translation":"The costs are high. However, the quality is good."},{"sentence":"Er ist sehr beschäftigt. Außerdem hat er keine Erfahrung.","translation":"He is very busy. Moreover he has no experience."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Im Gegenteil'' means?","options":["on the contrary","on the other hand","by contrast","in opposition"],"correctAnswer":"on the contrary"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The project is expensive. Therefore we need more budget.","options":["Das Projekt ist teuer. Deshalb brauchen wir mehr Budget.","Das Projekt ist teuer und wir brauchen Budget.","Wegen des teuren Projekts brauchen wir Budget.","Das Projekt braucht mehr Budget."],"correctAnswer":"Das Projekt ist teuer. Deshalb brauchen wir mehr Budget."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er ist jung, ___ sehr erfahren.","options":["jedoch","deshalb","allerdings","daher"],"correctAnswer":"jedoch"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The costs are high however the quality is good","wordBankItems":["Die","Kosten","sind","hoch",".",  "Allerdings","ist","die","Qualität","gut","."],"correctAnswer":"Die Kosten sind hoch . Allerdings ist die Qualität gut ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"After a connective adverb in position 1, the word order is?","options":["inverted (verb before subject)","normal (subject before verb)","verb-final","no change"],"correctAnswer":"inverted (verb before subject)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000da',1,'APPROVED','PUBLISHED',
'{"objectives":["Build cohesive texts in German","Use reference words and pronouns","Understand Textzusammenhang"],"explanation":{"intro":"Text cohesion is about linking sentences and ideas smoothly. B1 requires understanding and creating well-connected German texts.","culturalNote":"German texts are valued for their logical structure (roter Faden = red thread — the logical thread running through a text). Essays, presentations, and formal letters should follow a clear structure with visible connections between ideas."},"examples":[{"german":"Zuerst betrachten wir das Problem. Anschließend suchen wir nach Lösungen.","english":"First we look at the problem. Subsequently we look for solutions."},{"german":"Einerseits gibt es Vorteile, andererseits überwiegen die Nachteile.","english":"On one hand there are advantages, on the other the disadvantages outweigh them."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can create cohesive, well-connected German texts using discourse markers."}}',
'{"items":[{"word":"zuerst/zunächst","translation":"first/firstly","pronunciation":"TSOO-eyrst/TSOO-nekhst","example":"Zunächst muss man."},{"word":"anschließend","translation":"subsequently/then","pronunciation":"AN-shlee-send","example":"Anschließend folgt."},{"word":"abschließend","translation":"finally/in conclusion","pronunciation":"AP-shlee-send","example":"Abschließend lässt sich sagen."},{"word":"im Folgenden","translation":"in the following","pronunciation":"im FOL-gen-den","example":"Im Folgenden wird."},{"word":"zusammenfassend","translation":"to summarise","pronunciation":"TSOO-zam-en-fas-end","example":"Zusammenfassend kann man sagen."},{"word":"der rote Faden","translation":"red thread/logical thread","pronunciation":"dayr ROH-teh FAH-den","example":"Den roten Faden behalten."}]}',
'{"title":"Discourse sequencing markers","pattern":"Sequence: zunächst → dann/anschließend/darauf → abschließend/zuletzt","explanation":"German texts use sequencing markers to create structure. Zunächst (initially/first), dann (then), anschließend (subsequently), daraufhin (thereupon), abschließend (finally). For essays: Erstens/zweitens/drittens (firstly/secondly/thirdly). Conclusion markers: Zusammenfassend lässt sich sagen, dass... (To summarise, it can be said that...). Zum Schluss (in conclusion).","examples":[{"sentence":"Zunächst definieren wir den Begriff, dann analysieren wir Beispiele.","translation":"First we define the term, then we analyse examples."},{"sentence":"Abschließend lässt sich festhalten, dass das Experiment erfolgreich war.","translation":"In conclusion it can be noted that the experiment was successful."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Abschließend lässt sich sagen'' means?","options":["in conclusion it can be said","finally we say","to summarise","in the end"],"correctAnswer":"in conclusion it can be said"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"First we look at the problem. Subsequently we look for solutions.","options":["Zuerst betrachten wir das Problem. Anschließend suchen wir nach Lösungen.","Wir betrachten das Problem und suchen Lösungen.","Zunächst das Problem, dann die Lösungen.","Problem erst, Lösungen später."],"correctAnswer":"Zuerst betrachten wir das Problem. Anschließend suchen wir nach Lösungen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ lässt sich festhalten, dass das Experiment erfolgreich war.","options":["Abschließend","Zunächst","Anschließend","Zuletzt"],"correctAnswer":"Abschließend"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: First we define the term then we analyse examples","wordBankItems":["Zunächst","definieren","wir","den","Begriff",",","dann","analysieren","wir","Beispiele","."],"correctAnswer":"Zunächst definieren wir den Begriff , dann analysieren wir Beispiele ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der rote Faden'' means in text terms?","options":["logical thread through a text","conclusion","main argument","introduction"],"correctAnswer":"logical thread through a text"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000db',1,'APPROVED','PUBLISHED',
'{"objectives":["Write structured German texts","Use formal written registers","Build paragraphs with topic sentence"],"explanation":{"intro":"Written expression at B1 requires structuring ideas clearly with an introduction, main body, and conclusion. This lesson focuses on essay and formal letter structure.","culturalNote":"German school writing teaches Aufsatz (essay) structure: Einleitung (introduction), Hauptteil (main body), Schluss (conclusion). The Erörterung (argumentative essay) is a classic school genre. B1 exam writing tasks test this structure directly."},"examples":[{"german":"In meinem Aufsatz möchte ich zunächst das Thema vorstellen.","english":"In my essay I would first like to introduce the topic."},{"german":"Im Folgenden werde ich die Vor- und Nachteile abwägen.","english":"In the following I will weigh the advantages and disadvantages."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can write structured formal texts in German at B1 level."}}',
'{"items":[{"word":"die Einleitung","translation":"introduction","pronunciation":"dee YN-ly-toong","example":"Eine gute Einleitung."},{"word":"der Hauptteil","translation":"main body","pronunciation":"dayr HOWPT-tyl","example":"Im Hauptteil."},{"word":"der Schluss","translation":"conclusion","pronunciation":"dayr SHLOOS","example":"Ein guter Schluss."},{"word":"abwägen","translation":"to weigh up","pronunciation":"AP-vey-gen","example":"Argumente abwägen."},{"word":"die Erörterung","translation":"argumentative essay","pronunciation":"dee er-ÖR-ter-oong","example":"Eine Erörterung schreiben."},{"word":"vorstellen","translation":"to introduce/present","pronunciation":"FOR-shtel-en","example":"Das Thema vorstellen."}]}',
'{"title":"Essay structure — German Erörterung","pattern":"Einleitung (hook+thesis) → Hauptteil (arguments+examples) → Schluss (summary+position)","explanation":"Standard German essay structure: Einleitung — present topic, state position. Hauptteil — each paragraph: Behauptung (claim) + Begründung (reason) + Beispiel (example) = B-B-B method. Schluss — summarise, restate position, outlook. Useful phrases: Im Folgenden werde ich..., Erstens/zweitens..., Zusammenfassend lässt sich sagen..., Aus meiner Sicht...","examples":[{"sentence":"Aus meiner Sicht überwiegen die Vorteile.","translation":"In my view the advantages outweigh the disadvantages."},{"sentence":"Abschließend möchte ich betonen, dass...","translation":"In conclusion I would like to emphasise that..."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"The B-B-B method in German essay writing stands for?","options":["Behauptung-Begründung-Beispiel","Basis-Beweis-Beleg","Begriff-Beschreibung-Beweis","Beobachtung-Beweis-Beurteilung"],"correctAnswer":"Behauptung-Begründung-Beispiel"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In the following I will weigh the advantages and disadvantages.","options":["Im Folgenden werde ich die Vor- und Nachteile abwägen.","Ich werde Vor- und Nachteile nennen.","Die Vorteile sind größer als die Nachteile.","Im Folgenden die Vor- und Nachteile."],"correctAnswer":"Im Folgenden werde ich die Vor- und Nachteile abwägen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ möchte ich betonen, dass es viele Lösungen gibt.","options":["Abschließend","Zunächst","Erstens","Zuerst"],"correctAnswer":"Abschließend"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: In my view the advantages outweigh the disadvantages","wordBankItems":["Aus","meiner","Sicht","überwiegen","die","Vorteile","."],"correctAnswer":"Aus meiner Sicht überwiegen die Vorteile ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Erörterung'' is?","options":["argumentative essay","analysis","description","report"],"correctAnswer":"argumentative essay"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000000dc',1,'APPROVED','PUBLISHED',
'{"objectives":["Present ideas orally in German","Structure a short presentation","Use filler expressions and discourse markers"],"explanation":{"intro":"Oral expression at B1 involves presenting ideas clearly, managing pauses, and structuring speech. This lesson covers key spoken presentation skills.","culturalNote":"German presentations (Präsentation) in academic and professional contexts follow a structured format. Impromptu speaking (Stegreifrede) is less common — preparation is valued. Discourse markers help manage the flow of spoken German."},"examples":[{"german":"Ich möchte kurz über das Thema sprechen und dabei auf drei Punkte eingehen.","english":"I would like to briefly speak about the topic and address three points."},{"german":"Wie ich bereits erwähnt habe, ist die Situation komplex.","english":"As I have already mentioned, the situation is complex."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can give a short structured oral presentation in German at B1 level."}}',
'{"items":[{"word":"eingehen auf","translation":"to address/go into","pronunciation":"YN-gay-en owf","example":"Auf drei Punkte eingehen."},{"word":"wie ich bereits erwähnt habe","translation":"as I have already mentioned","pronunciation":"vee ikh beh-RYTS er-VEHNT HAH-beh","example":"Wie ich erwähnt habe."},{"word":"das Stichwort","translation":"key word/cue","pronunciation":"dahs SHTIKH-vort","example":"Stichwort: Nachhaltigkeit."},{"word":"sozusagen","translation":"so to speak/as it were","pronunciation":"ZO-tsoo-zah-gen","example":"Sozusagen ein Beweis."},{"word":"mit anderen Worten","translation":"in other words","pronunciation":"mit AN-der-en VOR-ten","example":"Mit anderen Worten."},{"word":"zu guter Letzt","translation":"last but not least","pronunciation":"tsoo GOO-ter LETST","example":"Zu guter Letzt."}]}',
'{"title":"Oral presentation structure — spoken discourse markers","pattern":"Einstieg (opening) → Hauptpunkte (main points) → Fazit (conclusion/takeaway)","explanation":"Spoken presentation markers: Ich möchte heute über...sprechen (I''d like to talk about...). Ich gehe dabei auf drei Punkte ein (I will address three points). First point: Zunächst möchte ich... Transition: Kommen wir zum nächsten Punkt (Let us come to the next point). Conclusion: Zum Schluss / Zusammenfassend... Filler expressions: Also... Ähm... Ich würde sagen...","examples":[{"sentence":"Kommen wir zum nächsten Punkt: der Finanzierung.","translation":"Let us come to the next point: financing."},{"sentence":"Zum Abschluss möchte ich festhalten, dass wir alle profitieren.","translation":"In conclusion I would like to note that we all benefit."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Eingehen auf'' means?","options":["to address/go into detail","to enter","to agree","to focus on"],"correctAnswer":"to address/go into detail"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"As I have already mentioned, the situation is complex.","options":["Wie ich bereits erwähnt habe, ist die Situation komplex.","Die Situation ist komplex, wie bekannt.","Ich habe schon erklärt, es ist komplex.","Die Situation ist schon erwähnt worden."],"correctAnswer":"Wie ich bereits erwähnt habe, ist die Situation komplex."},{"id":"ex3","type":"FILL_IN_BLANK","question":"___ wir zum nächsten Punkt: der Finanzierung.","options":["Kommen","Gehen","Kommen Sie","Wir kommen"],"correctAnswer":"Kommen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: In conclusion I would like to note that we all benefit","wordBankItems":["Zum","Abschluss","möchte","ich","festhalten",",","dass","wir","alle","profitieren","."],"correctAnswer":"Zum Abschluss möchte ich festhalten , dass wir alle profitieren ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Mit anderen Worten'' means?","options":["in other words","with different words","that is to say","put differently"],"correctAnswer":"in other words"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-0000000000c9','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l201',201,'Konjunktiv II','Subjunctive mood — würde, könnte, müsste','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000ca','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l202',202,'Irreale Bedingungen','Unreal Type II conditionals','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000cb','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l203',203,'Wunschsätze','Wish sentences with Konjunktiv II','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000cc','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l204',204,'Konzessivsätze','Obwohl vs trotzdem concessive clauses','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000cd','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l205',205,'Kausalsätze','Weil vs da vs denn causal clauses','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000ce','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l206',206,'Konsekutivsätze','So...dass result clauses','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000cf','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l207',207,'Finalsätze','Damit vs um...zu purpose clauses','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l208',208,'Modalsätze','Indem modal clauses by means of','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d1','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l209',209,'Partizipialkonstruktionen','Participial clause constructions','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d2','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l210',210,'Erweiterte Adjektive','Extended adjective attributes','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d3','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l211',211,'Nominalisierung','Nominalisation of verbs and adjectives','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d4','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l212',212,'Funktionsverbgefüge','Function verb phrases in formal German','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d5','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l213',213,'Passiv mit Modalverben','Passive voice combined with modals','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d6','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l214',214,'Zustandspassiv','Stative passive — sein+Partizip II','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d7','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l215',215,'Doppelter Infinitiv','Double infinitive Ersatzinfinitiv','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d8','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l216',216,'Genitiv in Texten','Written genitive — wegen/aufgrund/trotz','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000d9','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l217',217,'Konjunktionaladverbien','Connective adverbs — deshalb jedoch allerdings','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000da','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l218',218,'Textkohärenz','Building cohesive German texts','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000db','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l219',219,'Schriftlicher Ausdruck','Written expression and essay structure','PUBLISHED'),
('dd000000-0000-0000-0000-0000000000dc','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l220',220,'Mündlicher Ausdruck','Oral presentation and spoken discourse','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000c9' WHERE stable_ref = 'de-b1-u03-l201' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000ca' WHERE stable_ref = 'de-b1-u03-l202' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000cb' WHERE stable_ref = 'de-b1-u03-l203' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000cc' WHERE stable_ref = 'de-b1-u03-l204' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000cd' WHERE stable_ref = 'de-b1-u03-l205' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000ce' WHERE stable_ref = 'de-b1-u03-l206' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000cf' WHERE stable_ref = 'de-b1-u03-l207' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d0' WHERE stable_ref = 'de-b1-u03-l208' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d1' WHERE stable_ref = 'de-b1-u03-l209' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d2' WHERE stable_ref = 'de-b1-u03-l210' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d3' WHERE stable_ref = 'de-b1-u03-l211' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d4' WHERE stable_ref = 'de-b1-u03-l212' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d5' WHERE stable_ref = 'de-b1-u03-l213' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d6' WHERE stable_ref = 'de-b1-u03-l214' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d7' WHERE stable_ref = 'de-b1-u03-l215' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d8' WHERE stable_ref = 'de-b1-u03-l216' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000d9' WHERE stable_ref = 'de-b1-u03-l217' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000da' WHERE stable_ref = 'de-b1-u03-l218' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000db' WHERE stable_ref = 'de-b1-u03-l219' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000000dc' WHERE stable_ref = 'de-b1-u03-l220' AND lesson_id IS NULL;
