-- V65: German B1 lessons 261-280 (B1 batch 4)
-- Level: B1 (10000000-0000-0000-0000-000000000003), unit de-b1-u03
-- Hex: 261=0x105, 280=0x118

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-000000000105','de-b1-l261','Kino und Film - Cinema Film','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000106','de-b1-l262','Theater und Oper - Theatre Opera','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000107','de-b1-l263','Architektur - Architecture','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000108','de-b1-l264','Seniorenalltag - Senior Life','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000109','de-b1-l265','Jugend und Generation Z - Youth','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000010a','de-b1-l266','Gleichberechtigung - Gender Equality','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000010b','de-b1-l267','Familienpolitik - Family Policy','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000010c','de-b1-l268','Digitale Gesellschaft - Digital Society','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000010d','de-b1-l269','Humor und Komödie - Humour Comedy','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000010e','de-b1-l270','Deutsches Kabarett - German Cabaret','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000010f','de-b1-l271','Bewerbungsschreiben - Job Applications','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000110','de-b1-l272','Vorstellungsgespräch - Job Interview','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000111','de-b1-l273','Am Arbeitsplatz - At the Workplace','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000112','de-b1-l274','Arbeitskonflikte - Workplace Conflicts','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000113','de-b1-l275','Gewerkschaft - Trade Union','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000114','de-b1-l276','Selbstständigkeit - Self-employment','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000115','de-b1-l277','Weiterbildung - Continuing Education','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000116','de-b1-l278','Deutsche Dialekte - German Dialects','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000117','de-b1-l279','Sprachregister - Language Register','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000118','de-b1-l280','Fremdsprachen lernen - Learning Languages','language','de','B1','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000105',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss cinema and film","Use Kino vocabulary","Talk about German film industry"],"explanation":{"intro":"Cinema vocabulary at B1 covers film genres, criticism, and the film-going experience.","culturalNote":"Germany has a rich film tradition — Fritz Lang, Fassbinder, Werner Herzog, Wim Wenders, Florian Henckel von Donnersmarck (The Lives of Others). The Berlinale is one of the world''s top film festivals. The Deutsche Filmpreis (German Film Prize) is the top national award."},"examples":[{"german":"Der Film basiert auf einem preisgekrönten Roman und wurde in der Kritik gelobt.","english":"The film is based on a prize-winning novel and was praised in the reviews."},{"german":"Die Berlinale findet jedes Jahr im Februar in Berlin statt.","english":"The Berlinale takes place every year in February in Berlin."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss cinema, film genres, and German film culture."}}',
'{"items":[{"word":"preisgekrönt","translation":"prize-winning/award-winning","pronunciation":"PRYS-geh-krünt","example":"Ein preisgekrönter Film."},{"word":"loben","translation":"to praise","pronunciation":"LOH-ben","example":"In der Kritik gelobt."},{"word":"die Kritik","translation":"review/criticism","pronunciation":"dee kree-TIK","example":"Eine gute Kritik."},{"word":"basieren auf","translation":"to be based on","pronunciation":"bah-ZEER-en owf","example":"Auf einem Roman basieren."},{"word":"die Handlung","translation":"plot/action","pronunciation":"dee HAND-loong","example":"Die Handlung des Films."},{"word":"der Regisseur","translation":"director","pronunciation":"dayr reh-zhee-SÖR","example":"Der Regisseur."}]}',
'{"title":"Basieren auf — to be based on","pattern":"etwas basiert auf + dative (something is based on)","explanation":"Basieren auf + dative = to be based on. Der Film basiert auf einem Buch = The film is based on a book (dative: einem Buch). Der Artikel basiert auf Forschung = The article is based on research. Also: beruhen auf + dative (same meaning — more academic). Die Theorie beruht auf Fakten = The theory is based on facts. Basieren is the more common, modern variant.","examples":[{"sentence":"Das Spiel basiert auf historischen Ereignissen.","translation":"The game is based on historical events."},{"sentence":"Seine Methode basiert auf langjähriger Erfahrung.","translation":"His method is based on years of experience."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Preisgekrönt'' means?","options":["prize-winning","award-winning","celebrated","acclaimed"],"correctAnswer":"prize-winning"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The film is based on a prize-winning novel and was praised in the reviews.","options":["Der Film basiert auf einem preisgekrönten Roman und wurde in der Kritik gelobt.","Der Film ist toll.","Der Roman hat einen Preis gewonnen.","In der Kritik ist der Film gut."],"correctAnswer":"Der Film basiert auf einem preisgekrönten Roman und wurde in der Kritik gelobt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Spiel basiert auf historischen ___.","options":["Ereignissen","Ereignisse","Ereignis","dem Ereignis"],"correctAnswer":"Ereignissen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: His method is based on years of experience","wordBankItems":["Seine","Methode","basiert","auf","langjähriger","Erfahrung","."],"correctAnswer":"Seine Methode basiert auf langjähriger Erfahrung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Handlung'' in film context means?","options":["plot/action","scene","story","narrative"],"correctAnswer":"plot/action"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000106',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss theatre and opera","Use Bühne vocabulary","Talk about German performing arts"],"explanation":{"intro":"Theatre and opera vocabulary at B1 covers the performing arts scene in Germany.","culturalNote":"Germany has the highest density of opera houses and theatres in the world. Public theatre is heavily subsidised — tickets are affordable for all. The Volksbühne (People''s Stage) and Schaubühne in Berlin are famous. Bertolt Brecht (Mutter Courage, Der kaukasische Kreidekreis) is the most influential German playwright."},"examples":[{"german":"Das Stück wird vom Staatstheater in einer modernen Inszenierung aufgeführt.","english":"The play is being performed by the state theatre in a modern staging."},{"german":"In Deutschland gibt es mehr Opernhäuser als in jedem anderen Land der Welt.","english":"In Germany there are more opera houses than in any other country in the world."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss theatre, opera, and German performing arts."}}',
'{"items":[{"word":"aufführen","translation":"to perform/stage","pronunciation":"OWF-fü-ren","example":"Ein Stück aufführen."},{"word":"die Inszenierung","translation":"staging/production","pronunciation":"dee in-TSAY-neer-oong","example":"Eine moderne Inszenierung."},{"word":"das Stück","translation":"play/piece","pronunciation":"dahs SHTÜK","example":"Ein Theaterstück."},{"word":"die Vorstellung","translation":"performance/show","pronunciation":"dee FOR-shtel-oong","example":"Die Abendvorstellung."},{"word":"das Ensemble","translation":"ensemble/company","pronunciation":"dahs on-SOM-bleh","example":"Das Ensemble."},{"word":"der Vorhang","translation":"curtain","pronunciation":"dayr FOR-hang","example":"Der Vorhang fällt."}]}',
'{"title":"Aufführen — to perform/stage (separable)","pattern":"etwas aufführen (separable) — to perform, stage (a play, concert, production)","explanation":"Aufführen (separable) = to perform, stage, put on. Das Theater führt ein neues Stück auf = The theatre is staging a new play. Passive: Das Stück wird aufgeführt = The play is being performed. Die Aufführung (noun) = the performance. Note: Vorführen = to demonstrate, show (a film/procedure); Aufführen is specifically for live performance.","examples":[{"sentence":"Das Stück wurde zum ersten Mal 1949 aufgeführt.","translation":"The play was performed for the first time in 1949."},{"sentence":"Das Orchester führt heute Beethoven auf.","translation":"The orchestra is performing Beethoven today."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Inszenierung'' means?","options":["staging/production","performance","direction","mise-en-scène"],"correctAnswer":"staging/production"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The play is being performed by the state theatre in a modern staging.","options":["Das Stück wird vom Staatstheater in einer modernen Inszenierung aufgeführt.","Das Theater spielt ein neues Stück.","Das Stück ist modern.","Das Staatstheater hat eine Inszenierung."],"correctAnswer":"Das Stück wird vom Staatstheater in einer modernen Inszenierung aufgeführt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Stück wurde zum ersten Mal 1949 ___.","options":["aufgeführt","aufgeführen","aufzuführen","aufzuführen"],"correctAnswer":"aufgeführt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The orchestra is performing Beethoven today","wordBankItems":["Das","Orchester","führt","heute","Beethoven","auf","."],"correctAnswer":"Das Orchester führt heute Beethoven auf ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Vorhang'' means?","options":["curtain","backdrop","stage","scene"],"correctAnswer":"curtain"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000107',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss architecture","Use Baustil vocabulary","Talk about German architectural heritage"],"explanation":{"intro":"Architecture vocabulary at B1 covers building styles, design principles, and architectural history.","culturalNote":"Germany has major architectural movements: the Bauhaus (Dessau, 1919-1933), Expressionism, and contemporary sustainable design. Famous architects include Ludwig Mies van der Rohe, Walter Gropius. Cologne Cathedral (Kölner Dom), Neuschwanstein, and the Berlin Philharmonie are iconic structures."},"examples":[{"german":"Das Bauhaus beeinflusste die moderne Architektur und das Design weltweit.","english":"The Bauhaus influenced modern architecture and design worldwide."},{"german":"Der Kölner Dom ist ein Meisterwerk der gotischen Baukunst.","english":"Cologne Cathedral is a masterpiece of Gothic architecture."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss architecture, building styles, and German architectural heritage."}}',
'{"items":[{"word":"die Baukunst","translation":"architecture (elevated)","pronunciation":"dee BOW-koonst","example":"Gotische Baukunst."},{"word":"das Meisterwerk","translation":"masterpiece","pronunciation":"dahs MYS-ter-verk","example":"Ein Meisterwerk."},{"word":"gotisch","translation":"Gothic","pronunciation":"GOH-tish","example":"Gotische Architektur."},{"word":"der Baustil","translation":"architectural style","pronunciation":"dayr BOW-shteel","example":"Ein moderner Baustil."},{"word":"das Wahrzeichen","translation":"landmark/symbol","pronunciation":"dahs VAR-tsy-khen","example":"Das Wahrzeichen der Stadt."},{"word":"entwerfen","translation":"to design/draft","pronunciation":"ent-VER-fen","example":"Ein Gebäude entwerfen."}]}',
'{"title":"Entwerfen — to design/draft (strong verb)","pattern":"etwas entwerfen — strong verb: entwarf, entworfen (to design, draft, conceive)","explanation":"Entwerfen (strong) = to design, draft, conceive. Present: er entwirft (vowel change e→i). Past: entwarf. Participle: entworfen. Der Entwurf (noun) = the design/draft. Who designed this building? = Wer hat dieses Gebäude entworfen? Related: planen (to plan — more about schedule), gestalten (to shape/design — broader creative sense), konzipieren (to conceive/conceptualise).","examples":[{"sentence":"Mies van der Rohe entwarf das Barcelona-Pavillon.","translation":"Mies van der Rohe designed the Barcelona Pavilion."},{"sentence":"Sie entwirft gerade ein neues Bürogebäude.","translation":"She is currently designing a new office building."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Wahrzeichen'' means?","options":["landmark/symbol","monument","attraction","icon"],"correctAnswer":"landmark/symbol"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The Bauhaus influenced modern architecture and design worldwide.","options":["Das Bauhaus beeinflusste die moderne Architektur und das Design weltweit.","Das Bauhaus ist ein Stil.","Bauhaus Design ist bekannt.","Moderne Architektur hat Bauhaus beeinflusst."],"correctAnswer":"Das Bauhaus beeinflusste die moderne Architektur und das Design weltweit."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Mies van der Rohe ___ das Barcelona-Pavillon.","options":["entwarf","entworfen","entwirft","hat entworfen"],"correctAnswer":"entwarf"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She is currently designing a new office building","wordBankItems":["Sie","entwirft","gerade","ein","neues","Bürogebäude","."],"correctAnswer":"Sie entwirft gerade ein neues Bürogebäude ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Past participle of ''entwerfen'' is?","options":["entworfen","entwürfen","entwerfet","entworfen worden"],"correctAnswer":"entworfen"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000108',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss life of senior citizens","Use Rente vocabulary","Talk about aging in Germany"],"explanation":{"intro":"Senior life vocabulary covers retirement, aging, and social support systems for the elderly.","culturalNote":"Germany has an aging population — by 2030, 30% will be over 65. Rente (pension) and Pflegeversicherung (long-term care insurance) are major social topics. Seniorenheime (care homes) and ambulante Pflege (outpatient care) are common. The Rentenalter (retirement age) was raised to 67 amid protests."},"examples":[{"german":"In Deutschland geht man offiziell mit 67 Jahren in Rente.","english":"In Germany one officially goes into retirement at 67 years of age."},{"german":"Viele Senioren engagieren sich ehrenamtlich und bleiben aktiv.","english":"Many senior citizens volunteer and remain active."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss senior life, retirement, and aging-related topics in German."}}',
'{"items":[{"word":"die Rente","translation":"pension/retirement","pronunciation":"dee REN-teh","example":"In Rente gehen."},{"word":"das Rentenalter","translation":"retirement age","pronunciation":"dahs REN-ten-al-ter","example":"Das Rentenalter."},{"word":"die Pflegeversicherung","translation":"long-term care insurance","pronunciation":"dee PFLAY-geh-fer-zikh-er-oong","example":"Die Pflegeversicherung."},{"word":"ambulant","translation":"outpatient/mobile","pronunciation":"am-boo-LANT","example":"Ambulante Pflege."},{"word":"das Seniorenheim","translation":"care home","pronunciation":"dahs zen-YOH-ren-hym","example":"Im Seniorenheim."},{"word":"rüstig","translation":"sprightly/active (elderly)","pronunciation":"RÜS-tikh","example":"Ein rüstiger Rentner."}]}',
'{"title":"In + accusative — movement into a state","pattern":"in + accusative time phrase expressing going into a state or starting something","explanation":"In Rente gehen = to go into retirement (accusative: Rente here functions as a state you enter, not a literal location). Similarly: in Urlaub fahren (to go on holiday), in Pension gehen (to retire — public service), in Rente sein (to be retired — dative: location/state). The distinction: movement into → accusative; static state → dative.","examples":[{"sentence":"Er geht nächstes Jahr in Rente.","translation":"He is retiring next year."},{"sentence":"Sie ist seit drei Jahren in Rente.","translation":"She has been retired for three years."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Rüstig'' describes an elderly person who is?","options":["sprightly/active","content","healthy","social"],"correctAnswer":"sprightly/active"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In Germany one officially goes into retirement at 67 years of age.","options":["In Deutschland geht man offiziell mit 67 Jahren in Rente.","In Deutschland ist das Rentenalter 67.","Man geht mit 67 in Rente.","67 Jahre — Rente in Deutschland."],"correctAnswer":"In Deutschland geht man offiziell mit 67 Jahren in Rente."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er geht nächstes Jahr ___ Rente.","options":["in","zu","zur","an die"],"correctAnswer":"in"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She has been retired for three years","wordBankItems":["Sie","ist","seit","drei","Jahren","in","Rente","."],"correctAnswer":"Sie ist seit drei Jahren in Rente ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Ambulant'' in care context means?","options":["outpatient/mobile","home-based","social","community"],"correctAnswer":"outpatient/mobile"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000109',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss youth culture and Generation Z","Use Jugendsprache vocabulary","Talk about generational differences"],"explanation":{"intro":"Youth vocabulary at B1 covers generational differences, youth culture, and slang in German.","culturalNote":"Generation Z in Germany (born 1995-2012) is characterised by digital nativity, climate anxiety (Klimaangst), and work-life balance focus. Jugendsprache (youth language) evolves rapidly — cringe, krass, Alter, digga are common terms. The Greta Thunberg effect shaped German youth politics via Fridays for Future."},"examples":[{"german":"Die Generation Z legt großen Wert auf eine gute Work-Life-Balance.","english":"Generation Z places great importance on a good work-life balance."},{"german":"Jugendsprache verändert sich sehr schnell und bleibt für Ältere oft unverständlich.","english":"Youth language changes very quickly and often remains incomprehensible to older people."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss youth culture, generational differences, and youth language in German."}}',
'{"items":[{"word":"Wert legen auf","translation":"to place importance on","pronunciation":"VERT LAY-gen owf","example":"Wert auf Qualität legen."},{"word":"die Work-Life-Balance","translation":"work-life balance","pronunciation":"vork-lyf-bah-LONTS","example":"Work-Life-Balance."},{"word":"unverständlich","translation":"incomprehensible","pronunciation":"OON-fer-shtend-likh","example":"Unverständlich sprechen."},{"word":"die Jugendsprache","translation":"youth language","pronunciation":"dee YOO-gent-shpra-kheh","example":"Jugendsprache lernen."},{"word":"generationsübergreifend","translation":"cross-generational","pronunciation":"geh-neh-rah-TSYOHNS-ü-ber-gry-fend","example":"Generationsübergreifend."},{"word":"prägen","translation":"to shape/coin","pronunciation":"PRAY-gen","example":"Eine Generation prägen."}]}',
'{"title":"Großen Wert legen auf — to place great importance on","pattern":"(großen) Wert legen auf + accusative — to place (great) importance on","explanation":"Wert legen auf + accusative = to place importance on, to value. Ich lege großen Wert auf Pünktlichkeit = I place great importance on punctuality. Adjective modifies Wert: großen (great), keinen (no), besonderen (special). Also: etwas schätzen (to appreciate). The noun: der Wert (value, worth). Compare: auf etwas Wert legen (deliberate emphasis) vs. etwas wichtig finden (general finding something important).","examples":[{"sentence":"Das Unternehmen legt besonderen Wert auf Teamarbeit.","translation":"The company places particular importance on teamwork."},{"sentence":"Sie legt keinen Wert auf Statussymbole.","translation":"She places no importance on status symbols."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Unverständlich'' means?","options":["incomprehensible","misunderstood","unclear","confusing"],"correctAnswer":"incomprehensible"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Generation Z places great importance on a good work-life balance.","options":["Die Generation Z legt großen Wert auf eine gute Work-Life-Balance.","Generation Z findet Work-Life-Balance wichtig.","Junge Menschen wollen Balance.","Work-Life-Balance ist für Junge wichtig."],"correctAnswer":"Die Generation Z legt großen Wert auf eine gute Work-Life-Balance."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Unternehmen legt besonderen Wert auf ___.","options":["Teamarbeit","die Teamarbeit","Teamarbeiten","der Teamarbeit"],"correctAnswer":"Teamarbeit"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She places no importance on status symbols","wordBankItems":["Sie","legt","keinen","Wert","auf","Statussymbole","."],"correctAnswer":"Sie legt keinen Wert auf Statussymbole ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Prägen'' means?","options":["to shape/coin","to press","to stamp","to form"],"correctAnswer":"to shape/coin"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000010a',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss gender equality","Use Gleichberechtigung vocabulary","Talk about gender roles and policy"],"explanation":{"intro":"Gender equality vocabulary at B1 covers contemporary debates on gender roles, policy, and language.","culturalNote":"Germany introduced gender-neutral language reforms (Genderstern: Lehrer*innen, Lehrerinnen und Lehrer). The Elterngeld (parental leave allowance) incentivises fathers to take paternity leave (Vätermonate). The pay gap persists despite Gleichstellungsgesetze (equal opportunity laws)."},"examples":[{"german":"Das Elterngeld soll Väter dazu ermutigen, mehr Zeit mit ihren Kindern zu verbringen.","english":"The parental allowance is meant to encourage fathers to spend more time with their children."},{"german":"In der deutschen Sprache gibt es immer mehr gendergerechte Formulierungen.","english":"In the German language there are more and more gender-equitable formulations."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss gender equality, roles, and language in German."}}',
'{"items":[{"word":"ermutigen","translation":"to encourage","pronunciation":"er-MOO-tee-gen","example":"Väter ermutigen."},{"word":"gendergerecht","translation":"gender-equitable","pronunciation":"GEN-der-geh-rekht","example":"Gendergerechte Sprache."},{"word":"die Formulierung","translation":"formulation/wording","pronunciation":"dee for-moo-LEER-oong","example":"Eine Formulierung."},{"word":"das Elterngeld","translation":"parental allowance","pronunciation":"dahs EL-tern-gelt","example":"Elterngeld beantragen."},{"word":"der Vätermonate","translation":"fathers'' months (paternity leave)","pronunciation":"dayr FÄY-ter-moh-nah-teh","example":"Vätermonate nehmen."},{"word":"die Gleichstellung","translation":"equality/equal status","pronunciation":"dee GLYKH-shtel-oong","example":"Geschlechtergleichstellung."}]}',
'{"title":"Sollen — obligation/purpose (institutional)","pattern":"etwas soll + infinitive (institutional/designed purpose — is meant to / is supposed to)","explanation":"Sollen = designed purpose, institutional intention: Das Gesetz soll Arbeitnehmer schützen = The law is meant to protect workers. Different from müssen (must/have to — pressure) and wollen (want to — subject''s desire). Sollen implies external design: Das Elterngeld soll Väter ermutigen = The allowance is designed to encourage fathers. Very common in policy language. Also for hearsay: Er soll krank sein = He is said to be ill.","examples":[{"sentence":"Die Reform soll die Situation verbessern.","translation":"The reform is meant to improve the situation."},{"sentence":"Das System soll einfacher werden.","translation":"The system is supposed to become simpler."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Formulierung'' means?","options":["formulation/wording","formula","description","phrasing"],"correctAnswer":"formulation/wording"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The parental allowance is meant to encourage fathers to spend more time with their children.","options":["Das Elterngeld soll Väter dazu ermutigen, mehr Zeit mit ihren Kindern zu verbringen.","Väter sollen mehr Zeit haben.","Das Elterngeld hilft Vätern.","Väter werden ermutigt."],"correctAnswer":"Das Elterngeld soll Väter dazu ermutigen, mehr Zeit mit ihren Kindern zu verbringen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Reform ___ die Situation verbessern.","options":["soll","will","muss","kann"],"correctAnswer":"soll"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The system is supposed to become simpler","wordBankItems":["Das","System","soll","einfacher","werden","."],"correctAnswer":"Das System soll einfacher werden ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Ermutigen'' means?","options":["to encourage","to motivate","to inspire","to support"],"correctAnswer":"to encourage"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000010b',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss family policy in Germany","Use Familienpolitik vocabulary","Talk about childcare and parental leave"],"explanation":{"intro":"Family policy vocabulary covers German government support for families — childcare, leave, and benefits.","culturalNote":"Germany has transformed family policy significantly. Kita (Kindergarten/Kindertagesstätte) places are a legal right from age 1. Mutterschutz (maternity protection) starts 6 weeks before birth. Elternzeit (parental leave) can be taken by either parent up to 3 years. The Kindergeld (child benefit) is paid for every child."},"examples":[{"german":"In Deutschland hat jedes Kind ab einem Jahr einen gesetzlichen Anspruch auf einen Kitaplatz.","english":"In Germany every child from one year of age has a statutory right to a nursery place."},{"german":"Elternzeit kann von Müttern und Vätern gleichermaßen in Anspruch genommen werden.","english":"Parental leave can be taken equally by mothers and fathers."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss family policy, childcare, and parental leave in German."}}',
'{"items":[{"word":"der Anspruch auf","translation":"entitlement to/right to","pronunciation":"dayr AN-shproosh owf","example":"Anspruch auf Kitaplatz."},{"word":"gesetzlich","translation":"statutory/legal","pronunciation":"geh-ZETS-likh","example":"Gesetzlicher Anspruch."},{"word":"in Anspruch nehmen","translation":"to take up/claim/make use of","pronunciation":"in AN-shproosh NAY-men","example":"Elternzeit in Anspruch."},{"word":"gleichermaßen","translation":"equally/in equal measure","pronunciation":"GLY-kher-mah-sen","example":"Gleichermaßen profitieren."},{"word":"der Kitaplatz","translation":"nursery place","pronunciation":"dayr KEE-tah-plats","example":"Einen Kitaplatz bekommen."},{"word":"das Kindergeld","translation":"child benefit","pronunciation":"dahs KIN-der-gelt","example":"Kindergeld beantragen."}]}',
'{"title":"In Anspruch nehmen — to claim/make use of","pattern":"etwas in Anspruch nehmen (accusative) — to make use of, claim, avail oneself of","explanation":"In Anspruch nehmen = to claim, use, avail oneself of. Elternzeit in Anspruch nehmen = to take parental leave. Hilfe in Anspruch nehmen = to make use of help. This is a Funktionsverbgefüge (fixed verb phrase). Passive: wird in Anspruch genommen. Common in formal/official contexts: Die Möglichkeit wird von vielen in Anspruch genommen = The opportunity is used by many.","examples":[{"sentence":"Er nimmt die Möglichkeit in Anspruch, von zu Hause zu arbeiten.","translation":"He makes use of the possibility of working from home."},{"sentence":"Das Angebot kann kostenlos in Anspruch genommen werden.","translation":"The offer can be used free of charge."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Anspruch auf'' means?","options":["entitlement to/right to","claim for","demand for","access to"],"correctAnswer":"entitlement to/right to"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Parental leave can be taken equally by mothers and fathers.","options":["Elternzeit kann von Müttern und Vätern gleichermaßen in Anspruch genommen werden.","Eltern dürfen Elternzeit nehmen.","Elternzeit ist für alle gleich.","Mütter und Väter haben Elternzeit."],"correctAnswer":"Elternzeit kann von Müttern und Vätern gleichermaßen in Anspruch genommen werden."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er nimmt die Möglichkeit in ___, von zu Hause zu arbeiten.","options":["Anspruch","Ansprüchen","Ansprüche","Anspruchs"],"correctAnswer":"Anspruch"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The offer can be used free of charge","wordBankItems":["Das","Angebot","kann","kostenlos","in","Anspruch","genommen","werden","."],"correctAnswer":"Das Angebot kann kostenlos in Anspruch genommen werden ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Gleichermaßen'' means?","options":["equally/in equal measure","similarly","likewise","equally well"],"correctAnswer":"equally/in equal measure"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000010c',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss digital society","Use Digitalisierung vocabulary","Talk about data protection and privacy"],"explanation":{"intro":"Digital society vocabulary at B1 covers data protection, online behaviour, and the digital economy.","culturalNote":"Germany is known for strict data protection — the DSGVO (GDPR) was shaped significantly by German input. Datenschutz (data protection) is taken very seriously. The BSI (Bundesamt für Sicherheit in der Informationstechnik) advises on cybersecurity. Germans are more privacy-cautious online than many EU neighbours."},"examples":[{"german":"Die DSGVO stärkt die Datenschutzrechte der Bürgerinnen und Bürger in der EU.","english":"The GDPR strengthens the data protection rights of citizens in the EU."},{"german":"Digitale Kompetenz ist in der modernen Arbeitswelt unverzichtbar geworden.","english":"Digital competence has become indispensable in the modern world of work."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss digital society, data protection, and digital competence in German."}}',
'{"items":[{"word":"der Datenschutz","translation":"data protection","pronunciation":"dayr DAH-ten-shoots","example":"Datenschutz gewährleisten."},{"word":"die DSGVO","translation":"GDPR (data protection regulation)","pronunciation":"dee des-gay-fow","example":"Die DSGVO."},{"word":"unverzichtbar","translation":"indispensable","pronunciation":"OON-fer-tsikhт-bar","example":"Unverzichtbar werden."},{"word":"die digitale Kompetenz","translation":"digital competence","pronunciation":"dee dee-gee-TAH-leh kom-peh-TENTS","example":"Digitale Kompetenz."},{"word":"stärken","translation":"to strengthen","pronunciation":"SHTAYR-ken","example":"Rechte stärken."},{"word":"die Privatsphäre","translation":"privacy","pronunciation":"dee pree-VAHT-sfäy-reh","example":"Die Privatsphäre schützen."}]}',
'{"title":"Unverzichtbar — indispensable/essential","pattern":"etwas ist unverzichtbar (für + accusative) — is indispensable (for)","explanation":"Unverzichtbar = indispensable (from verzichten = to do without + un- negative prefix). Das ist unverzichtbar = That is indispensable. Für eine gute Kommunikation ist Vertrauen unverzichtbar = For good communication, trust is indispensable. Also: unentbehrlich (more formal synonym). Related: verzichtbar (dispensable), unverzichtbar für (indispensable for).","examples":[{"sentence":"Englischkenntnisse sind für viele Berufe unverzichtbar.","translation":"English skills are indispensable for many professions."},{"sentence":"Das Telefon ist heute ein unverzichtbares Werkzeug.","translation":"The phone is an indispensable tool today."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Privatsphäre'' means?","options":["privacy","private life","personal space","private sphere"],"correctAnswer":"privacy"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Digital competence has become indispensable in the modern world of work.","options":["Digitale Kompetenz ist in der modernen Arbeitswelt unverzichtbar geworden.","Digitale Kompetenz ist wichtig.","In der Arbeit braucht man digitale Fähigkeiten.","Digital sein ist wichtig."],"correctAnswer":"Digitale Kompetenz ist in der modernen Arbeitswelt unverzichtbar geworden."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Englischkenntnisse sind für viele Berufe ___.","options":["unverzichtbar","unentbehrlich","notwendig","wichtig"],"correctAnswer":"unverzichtbar"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The phone is an indispensable tool today","wordBankItems":["Das","Telefon","ist","heute","ein","unverzichtbares","Werkzeug","."],"correctAnswer":"Das Telefon ist heute ein unverzichtbares Werkzeug ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Stärken'' means?","options":["to strengthen","to support","to reinforce","to boost"],"correctAnswer":"to strengthen"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000010d',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand German humour","Use Witz vocabulary","Talk about comedy styles"],"explanation":{"intro":"Humour vocabulary at B1 covers comedy, jokes, and the cultural dimensions of what Germans find funny.","culturalNote":"German humour stereotypes are often unfair — Germany does have humour, but it''s often dry, satirical, and ironic (trocken, sarkastisch). Kabarett (political cabaret) is very popular. Witz (jokes) often use wordplay (Wortspiel) and puns (Kalauer). Loriot is the most famous German comedian/humorist."},"examples":[{"german":"Deutschen Humor versteht man oft erst, wenn man die Sprache und Kultur kennt.","english":"German humour is often only understood when you know the language and culture."},{"german":"Kalaue sind Witze mit einem schlechten Wortspiel — aber manche finden sie trotzdem lustig.","english":"Kalaue are jokes with a bad pun — but some people find them funny anyway."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss humour, jokes, and comedy in German."}}',
'{"items":[{"word":"trocken","translation":"dry (humour)","pronunciation":"TROK-en","example":"Trockener Humor."},{"word":"sarkastisch","translation":"sarcastic","pronunciation":"zar-KAS-tish","example":"Sarkastischer Witz."},{"word":"der Wortspiel","translation":"pun/wordplay","pronunciation":"dayr VORT-shpeel","example":"Ein Wortspiel."},{"word":"der Kalauer","translation":"bad pun/groan-worthy joke","pronunciation":"dayr KAH-low-er","example":"Ein Kalauer."},{"word":"lustig","translation":"funny/amusing","pronunciation":"LUS-tikh","example":"Lustig finden."},{"word":"die Pointe","translation":"punchline","pronunciation":"dee PWAN-teh","example":"Die Pointe des Witzes."}]}',
'{"title":"Erst wenn — only when (temporal condition)","pattern":"erst wenn + verb-final clause (only when — something happens first, then result)","explanation":"Erst wenn = only when, not until. Man versteht es erst, wenn man die Sprache kennt = One understands it only when one knows the language. Erst when expresses that the result doesn''t happen until a condition is met. Compare: erst als (only when — past, one-time), erst wenn (only when — future/hypothetical, or repeated). Erst also as adverb: Ich komme erst um 8 = I won''t come until 8.","examples":[{"sentence":"Der Witz ist erst lustig, wenn man die Pointe versteht.","translation":"The joke is only funny when you understand the punchline."},{"sentence":"Erst wenn alle bereit sind, können wir anfangen.","translation":"Only when everyone is ready can we start."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Pointe'' means?","options":["punchline","point","peak","highlight"],"correctAnswer":"punchline"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"German humour is often only understood when you know the language and culture.","options":["Deutschen Humor versteht man oft erst, wenn man die Sprache und Kultur kennt.","Deutsch ist schwer zu verstehen.","Humor ist kulturell.","Deutschen Humor kennt man mit Zeit."],"correctAnswer":"Deutschen Humor versteht man oft erst, wenn man die Sprache und Kultur kennt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Witz ist erst lustig, wenn man die Pointe ___.","options":["versteht","verstand","zu verstehen","verstanden"],"correctAnswer":"versteht"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Only when everyone is ready can we start","wordBankItems":["Erst","wenn","alle","bereit","sind",",","können","wir","anfangen","."],"correctAnswer":"Erst wenn alle bereit sind , können wir anfangen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Trocken'' describing humour means?","options":["dry","deadpan","cold","understated"],"correctAnswer":"dry"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000010e',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand Kabarett","Use satirical vocabulary","Talk about political satire"],"explanation":{"intro":"German Kabarett (political cabaret) vocabulary covers satire, political commentary, and irony.","culturalNote":"Kabarett has a long German tradition as political commentary and social criticism — from the Weimar Republic (1919-1933) to today. Famous Kabarettisten include Dieter Nuhr, Georg Schramm, and Die Anstalt on ZDF. Unlike stand-up comedy, Kabarett is issue-driven and often directly political."},"examples":[{"german":"Kabarettisten nehmen sich kein Blatt vor den Mund und kritisieren die Politik direkt.","english":"Cabaret artists don''t mince their words and directly criticise politics."},{"german":"Das Kabarett ist eine wichtige Form der demokratischen Meinungsfreiheit.","english":"Cabaret is an important form of democratic freedom of expression."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss political satire, Kabarett, and freedom of expression in German."}}',
'{"items":[{"word":"sich kein Blatt vor den Mund nehmen","translation":"not to mince words","pronunciation":"zikh kyn blat for den moond NAY-men","example":"Kein Blatt vor den Mund nehmen."},{"word":"die Satire","translation":"satire","pronunciation":"dee zah-TEE-reh","example":"Politische Satire."},{"word":"der Kabarettist","translation":"cabaret artist","pronunciation":"dayr ka-bah-ret-IST","example":"Ein Kabarettist."},{"word":"die Meinungsfreiheit","translation":"freedom of expression","pronunciation":"dee MY-noongs-fry-hyt","example":"Meinungsfreiheit."},{"word":"kritisieren","translation":"to criticise","pronunciation":"kree-tee-ZEER-en","example":"Die Politik kritisieren."},{"word":"der Sarkasmus","translation":"sarcasm","pronunciation":"dayr zar-KAS-moos","example":"Voller Sarkasmus."}]}',
'{"title":"Kein Blatt vor den Mund nehmen — not to mince words","pattern":"sich kein Blatt vor den Mund nehmen (idiom) — to not mince one''s words, speak one''s mind","explanation":"Sich kein Blatt vor den Mund nehmen = literally not to put a leaf/sheet in front of one''s mouth = to speak frankly, not mince words. Er nimmt kein Blatt vor den Mund = He doesn''t mince words. Reflexive: sich (dative). Very common idiom in journalism and speech descriptions. Opposite: die Wahrheit verschweigen (to conceal the truth), um den heißen Brei herumreden (to beat around the bush).","examples":[{"sentence":"Die Journalistin nimmt kein Blatt vor den Mund.","translation":"The journalist doesn''t mince her words."},{"sentence":"Er hat kein Blatt vor den Mund genommen und alles gesagt.","translation":"He didn''t mince his words and said everything."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Satire'' means?","options":["satire","parody","critique","comedy"],"correctAnswer":"satire"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Cabaret artists don''t mince their words and directly criticise politics.","options":["Kabarettisten nehmen sich kein Blatt vor den Mund und kritisieren die Politik direkt.","Kabarettisten sind ehrlich.","Kabarettisten kritisieren Politik.","Kabarett ist politisch."],"correctAnswer":"Kabarettisten nehmen sich kein Blatt vor den Mund und kritisieren die Politik direkt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Journalistin nimmt kein Blatt vor den ___.","options":["Mund","Mund nehmen","Munde","Mundes"],"correctAnswer":"Mund"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: He didn''t mince his words and said everything","wordBankItems":["Er","hat","kein","Blatt","vor","den","Mund","genommen","und","alles","gesagt","."],"correctAnswer":"Er hat kein Blatt vor den Mund genommen und alles gesagt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Kritisieren'' means?","options":["to criticise","to review","to judge","to condemn"],"correctAnswer":"to criticise"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000010f',1,'APPROVED','PUBLISHED',
'{"objectives":["Write job application letters","Use Bewerbung vocabulary","Discuss cover letter structure"],"explanation":{"intro":"Job application vocabulary at B1 is essential — writing a Bewerbungsschreiben (cover letter) is a key B1 skill.","culturalNote":"German job applications traditionally include: Bewerbungsschreiben (cover letter), Lebenslauf (CV/résumé), Zeugnisse (certificates). Photo on CV was traditional (now optional). The salutation ''Sehr geehrte Damen und Herren'' is standard, or ''Sehr geehrter Herr X/geehrte Frau Y'' if addressing someone specific."},"examples":[{"german":"Sehr geehrte Damen und Herren, mit großem Interesse habe ich Ihre Stellenanzeige gelesen.","english":"Dear Sir or Madam, I read your job advertisement with great interest."},{"german":"Ich bewerbe mich um die ausgeschriebene Stelle als Softwareentwickler.","english":"I am applying for the advertised position as software developer."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can write a formal job application letter in German."}}',
'{"items":[{"word":"die Stellenanzeige","translation":"job advertisement","pronunciation":"dee SHTEL-en-an-tsy-geh","example":"Eine Stellenanzeige."},{"word":"ausgeschrieben","translation":"advertised (position)","pronunciation":"OWS-geh-shree-ben","example":"Die ausgeschriebene Stelle."},{"word":"sich bewerben um","translation":"to apply for","pronunciation":"zikh beh-VER-ben oom","example":"Um eine Stelle bewerben."},{"word":"der Lebenslauf","translation":"CV/résumé","pronunciation":"dayr LAY-bens-lowf","example":"Lebenslauf beifügen."},{"word":"das Zeugnis","translation":"certificate/reference","pronunciation":"dahs TSOYG-nis","example":"Arbeitszeugnisse vorlegen."},{"word":"beifügen","translation":"to enclose/attach","pronunciation":"BY-fü-gen","example":"Unterlagen beifügen."}]}',
'{"title":"Sich bewerben um — to apply for","pattern":"sich bewerben um + accusative (to apply for a position)","explanation":"Sich bewerben um = to apply for (a job). Ich bewerbe mich um die Stelle = I am applying for the position. Present: ich bewerbe mich, du bewirbst dich (vowel change e→i in 2nd/3rd person). Darf ich mich bei Ihnen bewerben? = May I apply to your company? Die Bewerbung = the application. Sich um etwas bewerben = apply for something; sich bei jemandem bewerben = apply to a company/person.","examples":[{"sentence":"Ich möchte mich um die Stelle als Buchhalter bewerben.","translation":"I would like to apply for the position of accountant."},{"sentence":"Wie viele Personen haben sich auf die Stelle beworben?","translation":"How many people applied for the position?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Stellenanzeige'' means?","options":["job advertisement","job listing","career posting","work notice"],"correctAnswer":"job advertisement"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"I am applying for the advertised position as software developer.","options":["Ich bewerbe mich um die ausgeschriebene Stelle als Softwareentwickler.","Ich will Softwareentwickler werden.","Ich habe mich um die Stelle beworben.","Meine Bewerbung ist als Softwareentwickler."],"correctAnswer":"Ich bewerbe mich um die ausgeschriebene Stelle als Softwareentwickler."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich möchte mich um die Stelle als Buchhalter ___.","options":["bewerben","beworben","bewerbend","bewirbt"],"correctAnswer":"bewerben"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: How many people applied for the position?","wordBankItems":["Wie","viele","Personen","haben","sich","auf","die","Stelle","beworben","?"],"correctAnswer":"Wie viele Personen haben sich auf die Stelle beworben ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Beifügen'' means?","options":["to enclose/attach","to add","to include","to append"],"correctAnswer":"to enclose/attach"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000110',1,'APPROVED','PUBLISHED',
'{"objectives":["Prepare for a job interview in German","Use Vorstellungsgespräch vocabulary","Handle common interview questions"],"explanation":{"intro":"Job interview vocabulary at B1 covers how to present yourself professionally and handle common questions.","culturalNote":"German job interviews tend to be formal and competency-focused. Common questions: Warum bewerben Sie sich bei uns? (Why are you applying to us?), Was sind Ihre Stärken/Schwächen? (What are your strengths/weaknesses?), Wo sehen Sie sich in fünf Jahren? (Where do you see yourself in five years?). Small talk before the interview is expected."},"examples":[{"german":"Bei einem Vorstellungsgespräch sollte man sich über das Unternehmen gut informieren.","english":"For a job interview one should inform oneself well about the company."},{"german":"Auf die Frage nach den Schwächen antwortet man am besten ehrlich, aber positiv.","english":"The question about weaknesses is best answered honestly but positively."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can participate in a German job interview and answer common questions."}}',
'{"items":[{"word":"das Vorstellungsgespräch","translation":"job interview","pronunciation":"dahs for-SHTEL-oongs-geh-shpräkh","example":"Ein Vorstellungsgespräch."},{"word":"die Stärke","translation":"strength","pronunciation":"dee SHTAYR-keh","example":"Stärken nennen."},{"word":"die Schwäche","translation":"weakness","pronunciation":"dee SHVÄ-kheh","example":"Schwächen nennen."},{"word":"sich informieren über","translation":"to find out about/inform oneself about","pronunciation":"zikh in-for-MEER-en ü-ber","example":"Über das Unternehmen informieren."},{"word":"die Gehaltsvorstellung","translation":"salary expectation","pronunciation":"dee geh-HALTS-for-shtel-oong","example":"Gehaltsvorstellung nennen."},{"word":"überzeugend","translation":"convincingly/persuasively","pronunciation":"ü-ber-TSOY-gend","example":"Überzeugend auftreten."}]}',
'{"title":"Sich informieren über — to find out about/research","pattern":"sich informieren über + accusative (to find out about, research, inform oneself about)","explanation":"Sich informieren über + accusative = to find out about, research. Ich informiere mich über das Unternehmen = I am finding out about the company. Can also use bei: sich informieren bei + dative (to inquire at a source). Die Information = the information. Gut informiert sein = to be well-informed. Related: recherchieren (to research), nachschlagen (to look up).","examples":[{"sentence":"Vor dem Interview habe ich mich ausführlich über die Firma informiert.","translation":"Before the interview I thoroughly informed myself about the company."},{"sentence":"Ich informiere mich regelmäßig über aktuelle Nachrichten.","translation":"I regularly inform myself about current news."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Überzeugend'' means?","options":["convincingly/persuasively","impressively","competently","professionally"],"correctAnswer":"convincingly/persuasively"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"For a job interview one should inform oneself well about the company.","options":["Bei einem Vorstellungsgespräch sollte man sich über das Unternehmen gut informieren.","Man soll das Unternehmen kennen.","Informiere dich vor dem Interview.","Das Unternehmen kennt man durch Recherche."],"correctAnswer":"Bei einem Vorstellungsgespräch sollte man sich über das Unternehmen gut informieren."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Vor dem Interview habe ich mich ausführlich über die Firma ___.","options":["informiert","informieren","informierend","zu informieren"],"correctAnswer":"informiert"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: I regularly inform myself about current news","wordBankItems":["Ich","informiere","mich","regelmäßig","über","aktuelle","Nachrichten","."],"correctAnswer":"Ich informiere mich regelmäßig über aktuelle Nachrichten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Gehaltsvorstellung'' means?","options":["salary expectation","wage demand","pay request","compensation expectation"],"correctAnswer":"salary expectation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000111',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss workplace communication","Use Arbeitsplatz vocabulary","Talk about meetings and colleagues"],"explanation":{"intro":"Workplace vocabulary at B1 covers meetings, professional relationships, and office communication.","culturalNote":"German workplace culture values Pünktlichkeit (punctuality), Direktheit (directness), and clear hierarchy. Meetings (Besprechungen) have clear agendas. Colleagues are addressed as Herr/Frau + Nachname until explicitly invited to use first names (per du). Work emails begin with Sehr geehrte(r) or Guten Morgen/Tag."},"examples":[{"german":"Die Besprechung findet jeden Montag um 9 Uhr im Konferenzraum statt.","english":"The meeting takes place every Monday at 9 o''clock in the conference room."},{"german":"In vielen deutschen Firmen per''zen'' Kollegen erst nach einer Einladung.","english":"In many German companies colleagues use first-name terms only after an invitation."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can communicate professionally in a German workplace."}}',
'{"items":[{"word":"die Besprechung","translation":"meeting","pronunciation":"dee beh-SHPREH-khoong","example":"Eine Besprechung."},{"word":"die Tagesordnung","translation":"agenda","pronunciation":"dee TAH-ges-ord-noong","example":"Die Tagesordnung."},{"word":"das Protokoll","translation":"minutes/protocol","pronunciation":"dahs proh-toh-KOL","example":"Protokoll führen."},{"word":"der Kollege","translation":"colleague (m)","pronunciation":"dayr kol-EY-geh","example":"Mein Kollege."},{"word":"die Direktheit","translation":"directness","pronunciation":"dee dee-REKT-hyt","example":"Direktheit schätzen."},{"word":"pünktlich","translation":"punctual","pronunciation":"PÜNKT-likh","example":"Pünktlich sein."}]}',
'{"title":"Stattfinden — to take place (separable)","pattern":"etwas findet statt (separable) — to take place, to be held (event)","explanation":"Stattfinden (separable) = to take place, to be held. Present: Die Besprechung findet statt. Past: Die Besprechung fand statt. Perfect: Die Besprechung hat stattgefunden. Common in event/schedule contexts. Also: Die Veranstaltung findet nicht statt = The event is not taking place. Future: Die Konferenz wird nächste Woche stattfinden = The conference will take place next week.","examples":[{"sentence":"Das Festival findet jedes Jahr im Sommer statt.","translation":"The festival takes place every year in summer."},{"sentence":"Die Prüfung hat gestern stattgefunden.","translation":"The exam took place yesterday."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Protokoll'' in meeting context means?","options":["minutes/records","protocol","proceedings","report"],"correctAnswer":"minutes/records"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The meeting takes place every Monday at 9 o''clock in the conference room.","options":["Die Besprechung findet jeden Montag um 9 Uhr im Konferenzraum statt.","Jeden Montag gibt es eine Besprechung.","Wir treffen uns jeden Montag.","Die Besprechung ist um 9 Uhr."],"correctAnswer":"Die Besprechung findet jeden Montag um 9 Uhr im Konferenzraum statt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Prüfung hat gestern ___.","options":["stattgefunden","stattfinden","stattfand","gefunden statt"],"correctAnswer":"stattgefunden"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The festival takes place every year in summer","wordBankItems":["Das","Festival","findet","jedes","Jahr","im","Sommer","statt","."],"correctAnswer":"Das Festival findet jedes Jahr im Sommer statt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Pünktlich'' means?","options":["punctual","precise","on time","timely"],"correctAnswer":"punctual"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000112',1,'APPROVED','PUBLISHED',
'{"objectives":["Handle workplace conflicts professionally","Use Konflikt vocabulary","Discuss mediation and resolution"],"explanation":{"intro":"Workplace conflict vocabulary at B1 covers disagreements, mediation, and resolution strategies.","culturalNote":"German labour law strongly protects employees against unfair dismissal (Kündigungsschutz). Conflicts can be escalated to the Betriebsrat (works council), which has co-determination rights. Mediation (Mediation) and Schlichtung (conciliation) are preferred over litigation."},"examples":[{"german":"Bei Konflikten am Arbeitsplatz sollte man das Gespräch suchen und sachlich bleiben.","english":"With conflicts at the workplace one should seek dialogue and remain objective."},{"german":"Der Betriebsrat vertritt die Interessen der Arbeitnehmer gegenüber der Geschäftsführung.","english":"The works council represents the interests of employees vis-à-vis management."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss and handle workplace conflicts in German."}}',
'{"items":[{"word":"sachlich bleiben","translation":"to remain objective","pronunciation":"ZAKH-likh BLY-ben","example":"Sachlich bleiben."},{"word":"das Gespräch suchen","translation":"to seek dialogue","pronunciation":"dahs geh-SHPRÄKH ZOO-khen","example":"Das Gespräch suchen."},{"word":"der Betriebsrat","translation":"works council","pronunciation":"dayr beh-TREEPS-raht","example":"Der Betriebsrat."},{"word":"vertreten","translation":"to represent","pronunciation":"fer-TRAY-ten","example":"Interessen vertreten."},{"word":"gegenüber","translation":"vis-à-vis/towards","pronunciation":"GAY-gen-ü-ber","example":"Gegenüber der Firma."},{"word":"die Mediation","translation":"mediation","pronunciation":"dee meh-dee-ah-TSYOHN","example":"Eine Mediation anbieten."}]}',
'{"title":"Gegenüber — vis-à-vis/towards (preposition + postposition)","pattern":"gegenüber + dative OR dative + gegenüber (can go before or after)","explanation":"Gegenüber = opposite, across from, towards, vis-à-vis. Can precede or follow dative noun: gegenüber dem Bahnhof = opposite the station / dem Bahnhof gegenüber (same meaning). When expressing attitude/position: gegenüber dem Chef offen sein = to be open towards the boss (dative). Opposite (location): Das Haus liegt dem Park gegenüber = The house is opposite the park.","examples":[{"sentence":"Ich bin dieser Idee gegenüber aufgeschlossen.","translation":"I am open-minded towards this idea."},{"sentence":"Das Büro liegt dem Rathaus gegenüber.","translation":"The office is opposite the town hall."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Sachlich bleiben'' means?","options":["to remain objective","to stay calm","to be rational","to keep professional"],"correctAnswer":"to remain objective"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The works council represents the interests of employees vis-à-vis management.","options":["Der Betriebsrat vertritt die Interessen der Arbeitnehmer gegenüber der Geschäftsführung.","Der Betriebsrat hilft Arbeitnehmern.","Die Interessen werden vertreten.","Arbeitnehmer haben den Betriebsrat."],"correctAnswer":"Der Betriebsrat vertritt die Interessen der Arbeitnehmer gegenüber der Geschäftsführung."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich bin dieser Idee ___ aufgeschlossen.","options":["gegenüber","gegenübers","gegenüberhalb","gegenüberstehend"],"correctAnswer":"gegenüber"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The office is opposite the town hall","wordBankItems":["Das","Büro","liegt","dem","Rathaus","gegenüber","."],"correctAnswer":"Das Büro liegt dem Rathaus gegenüber ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Mediation'' means?","options":["mediation","arbitration","conciliation","intervention"],"correctAnswer":"mediation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000113',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss trade unions","Use Gewerkschaft vocabulary","Talk about worker rights and collective bargaining"],"explanation":{"intro":"Trade union vocabulary at B1 covers worker representation, collective bargaining, and industrial action.","culturalNote":"Germany has powerful trade unions: IG Metall (metalworkers), ver.di (service), IG BCE (chemicals). Collective agreements (Tarifverträge) cover around 55% of workers. Mitbestimmung (co-determination) gives workers board seats in large companies — a uniquely German model of social partnership."},"examples":[{"german":"Die Gewerkschaft hat für eine Lohnerhöhung von 5 Prozent verhandelt.","english":"The trade union negotiated for a 5 percent pay rise."},{"german":"In Deutschland haben Arbeitnehmer in großen Unternehmen Mitbestimmungsrechte.","english":"In Germany employees in large companies have co-determination rights."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss trade unions, collective bargaining, and worker rights in German."}}',
'{"items":[{"word":"die Gewerkschaft","translation":"trade union","pronunciation":"dee geh-VERK-shaft","example":"Die Gewerkschaft."},{"word":"verhandeln","translation":"to negotiate","pronunciation":"fer-HAN-deln","example":"Über Gehalt verhandeln."},{"word":"die Lohnerhöhung","translation":"pay rise","pronunciation":"dee LOHN-er-hö-oong","example":"Eine Lohnerhöhung."},{"word":"die Mitbestimmung","translation":"co-determination","pronunciation":"dee MIT-beh-shtim-oong","example":"Mitbestimmungsrecht."},{"word":"der Streik","translation":"strike","pronunciation":"dayr SHTRYK","example":"In den Streik treten."},{"word":"der Tarifvertrag","translation":"collective agreement","pronunciation":"dayr tah-REEF-fer-trahk","example":"Ein Tarifvertrag."}]}',
'{"title":"In den Streik treten — to go on strike","pattern":"in den Streik treten (to go on strike) / streiken (to strike)","explanation":"In den Streik treten = to go on strike (formal, idiomatic). Also: streiken (simpler verb — to be on strike, to strike). Die Arbeiter streiken = The workers are on strike. In den Streik treten = entering strike action. Der Streik = the strike. Streikbrecher = scab/strikebreaker. Related Funktionsverb: in Kraft treten (to come into force), in Kontakt treten (to make contact).","examples":[{"sentence":"Die Lokführer sind in den Streik getreten.","translation":"The train drivers have gone on strike."},{"sentence":"Über 30.000 Beschäftigte streiken für höhere Löhne.","translation":"Over 30,000 employees are striking for higher wages."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Mitbestimmung'' means?","options":["co-determination","participation","co-decision","representation"],"correctAnswer":"co-determination"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The trade union negotiated for a 5 percent pay rise.","options":["Die Gewerkschaft hat für eine Lohnerhöhung von 5 Prozent verhandelt.","Die Gewerkschaft will mehr Lohn.","Löhne steigen um 5 Prozent.","Verhandlungen für 5 Prozent."],"correctAnswer":"Die Gewerkschaft hat für eine Lohnerhöhung von 5 Prozent verhandelt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Lokführer sind in den Streik ___.","options":["getreten","getreten worden","treten","getreten haben"],"correctAnswer":"getreten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Over 30,000 employees are striking for higher wages","wordBankItems":["Über","30.000","Beschäftigte","streiken","für","höhere","Löhne","."],"correctAnswer":"Über 30.000 Beschäftigte streiken für höhere Löhne ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Tarifvertrag'' means?","options":["collective agreement","tariff","pay scale","labour contract"],"correctAnswer":"collective agreement"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000114',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss self-employment in Germany","Use Selbstständigkeit vocabulary","Talk about starting a business"],"explanation":{"intro":"Self-employment vocabulary at B1 covers freelancing, business registration, and entrepreneurship in Germany.","culturalNote":"Germany has about 4 million Selbstständige (self-employed). Registration at the Gewerbeamt (trade office) is required. Freiberufler (freelancers — doctors, lawyers, artists, journalists) register differently than Gewerbetreibende (traders). The Finanzamt (tax office) is key for the Umsatzsteuer (VAT)."},"examples":[{"german":"Als Freiberufler muss man die Einkommensteuer selbst abführen.","english":"As a freelancer one must pay income tax oneself."},{"german":"Die Gründung eines Unternehmens erfordert eine Anmeldung beim Gewerbeamt.","english":"The founding of a business requires registration at the trade office."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss self-employment, freelancing, and starting a business in German."}}',
'{"items":[{"word":"selbstständig","translation":"self-employed/independent","pronunciation":"ZELPST-shten-dikh","example":"Selbstständig arbeiten."},{"word":"der Freiberufler","translation":"freelancer","pronunciation":"dayr FRY-beh-roof-ler","example":"Als Freiberufler."},{"word":"abführen","translation":"to pay/remit (tax)","pronunciation":"AP-fü-ren","example":"Steuern abführen."},{"word":"die Gründung","translation":"founding/establishment","pronunciation":"dee GRÜN-doong","example":"Die Firmengründung."},{"word":"erfordern","translation":"to require","pronunciation":"er-FOR-dern","example":"Eine Anmeldung erfordern."},{"word":"das Gewerbeamt","translation":"trade office","pronunciation":"dahs geh-VER-beh-amt","example":"Beim Gewerbeamt anmelden."}]}',
'{"title":"Erfordern — to require (formal)","pattern":"etwas erfordert etwas (something requires something — formal, for rules/processes)","explanation":"Erfordern = to require, demand, necessitate (formal register). Die Situation erfordert eine schnelle Reaktion = The situation requires a quick response. Very common in legal and administrative language. Compare: benötigen (to need/require — more everyday), verlangen (to demand — from a person), brauchen (to need — most everyday). Erfordern is used when something inherently necessitates something else — structural requirement.","examples":[{"sentence":"Der Beruf erfordert viel Geduld und Ausdauer.","translation":"The profession requires a lot of patience and endurance."},{"sentence":"Diese Aufgabe erfordert besondere Sorgfalt.","translation":"This task requires particular care."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Freiberufler'' means?","options":["freelancer","free agent","independent worker","contractor"],"correctAnswer":"freelancer"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"As a freelancer one must pay income tax oneself.","options":["Als Freiberufler muss man die Einkommensteuer selbst abführen.","Freiberufler zahlen Steuern.","Selbstständige haben Steuerpflichten.","Die Einkommensteuer muss man abführen."],"correctAnswer":"Als Freiberufler muss man die Einkommensteuer selbst abführen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Beruf erfordert viel Geduld und ___.","options":["Ausdauer","Ausdauern","der Ausdauer","Ausdauerung"],"correctAnswer":"Ausdauer"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: This task requires particular care","wordBankItems":["Diese","Aufgabe","erfordert","besondere","Sorgfalt","."],"correctAnswer":"Diese Aufgabe erfordert besondere Sorgfalt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Abführen'' in tax context means?","options":["to pay/remit","to deduct","to pay off","to settle"],"correctAnswer":"to pay/remit"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000115',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss continuing education","Use Weiterbildung vocabulary","Talk about professional development"],"explanation":{"intro":"Continuing education vocabulary covers professional development, upskilling, and lifelong learning in Germany.","culturalNote":"Germany has a strong Weiterbildungskultur (continuing education culture). The Bundesagentur für Arbeit (Federal Employment Agency) funds retraining (Umschulung). MOOC providers, VHS (Volkshochschule — adult education centres), and company training programs are widely used."},"examples":[{"german":"Die Volkshochschule bietet Kurse für alle Altersgruppen zu erschwinglichen Preisen an.","english":"The adult education centre offers courses for all age groups at affordable prices."},{"german":"Lebenslanges Lernen ist in der heutigen Arbeitswelt unerlässlich.","english":"Lifelong learning is essential in today''s world of work."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss continuing education and professional development in German."}}',
'{"items":[{"word":"erschwingklich","translation":"affordable","pronunciation":"er-SHVING-likh","example":"Erschwingliche Preise."},{"word":"unerlässlich","translation":"essential/indispensable","pronunciation":"OON-er-les-likh","example":"Unerlässlich sein."},{"word":"die Umschulung","translation":"retraining","pronunciation":"dee OOM-shoo-loong","example":"Eine Umschulung machen."},{"word":"die Volkshochschule","translation":"adult education centre","pronunciation":"dee FOLKS-hokh-shoo-leh","example":"Die VHS."},{"word":"lebenslanges Lernen","translation":"lifelong learning","pronunciation":"LAY-bens-lang-es LER-nen","example":"Lebenslanges Lernen."},{"word":"die Förderung","translation":"funding/promotion/support","pronunciation":"dee FÖR-der-oong","example":"Förderung beantragen."}]}',
'{"title":"Anbieten — to offer (separable)","pattern":"etwas anbieten (separable) — to offer something (services, courses, products)","explanation":"Anbieten (separable) = to offer. Die VHS bietet Kurse an = The VHS offers courses (present, separable). Perfect: hat angeboten. Passive: Kurse werden angeboten = Courses are offered. Jemandem etwas anbieten = to offer something to someone: Ich biete Ihnen Hilfe an = I offer you help. Das Angebot (noun) = the offer.","examples":[{"sentence":"Das Unternehmen bietet flexible Arbeitszeiten an.","translation":"The company offers flexible working hours."},{"sentence":"Der Kurs wird zweimal im Jahr angeboten.","translation":"The course is offered twice a year."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Unerlässlich'' means?","options":["essential/indispensable","necessary","important","required"],"correctAnswer":"essential/indispensable"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The adult education centre offers courses for all age groups at affordable prices.","options":["Die Volkshochschule bietet Kurse für alle Altersgruppen zu erschwinglichen Preisen an.","Die VHS hat Kurse für alle.","Kurse bei der VHS sind günstig.","Alle Altersgruppen lernen bei der VHS."],"correctAnswer":"Die Volkshochschule bietet Kurse für alle Altersgruppen zu erschwinglichen Preisen an."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Kurs wird zweimal im Jahr ___.","options":["angeboten","anbieten","angeboten worden","anzubieten"],"correctAnswer":"angeboten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The company offers flexible working hours","wordBankItems":["Das","Unternehmen","bietet","flexible","Arbeitszeiten","an","."],"correctAnswer":"Das Unternehmen bietet flexible Arbeitszeiten an ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Förderung'' means?","options":["funding/promotion/support","encouragement","development","subsidy"],"correctAnswer":"funding/promotion/support"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000116',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand German dialects","Use Dialekt vocabulary","Discuss regional language variation"],"explanation":{"intro":"Dialect vocabulary at B1 covers regional variations in German and how to navigate them.","culturalNote":"German dialects are highly varied: Bayerisch (Bavaria), Sächsisch (Saxony — often mocked), Schwäbisch (Swabia), Kölsch (Cologne), Plattdeutsch/Niederdeutsch (North Germany), Alemannisch (southwest), Berlinerisch (Berlin). Standard German (Hochdeutsch/Standarddeutsch) is the common register, especially in media."},"examples":[{"german":"In Bayern spricht man einen ganz anderen Dialekt als im Norden Deutschlands.","english":"In Bavaria people speak a completely different dialect than in the north of Germany."},{"german":"Im Fernsehen und Radio wird hauptsächlich Hochdeutsch gesprochen.","english":"On television and radio Standard German is mainly spoken."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss German dialects and regional language variation."}}',
'{"items":[{"word":"der Dialekt","translation":"dialect","pronunciation":"dayr dee-ah-LEKT","example":"Ein regionaler Dialekt."},{"word":"das Hochdeutsch","translation":"Standard German","pronunciation":"dahs HOKH-doytsh","example":"Hochdeutsch sprechen."},{"word":"hauptsächlich","translation":"mainly/primarily","pronunciation":"HOWPT-zäkh-likh","example":"Hauptsächlich Hochdeutsch."},{"word":"der Akzent","translation":"accent","pronunciation":"dayr ak-TSENT","example":"Einen starken Akzent."},{"word":"mundartlich","translation":"dialectal","pronunciation":"MOON-dahr-likh","example":"Mundartliche Ausdrücke."},{"word":"verstehen","translation":"to understand","pronunciation":"fer-SHTAY-en","example":"Den Dialekt verstehen."}]}',
'{"title":"Hauptsächlich — mainly/primarily (adverb)","pattern":"hauptsächlich + verb or adjective (mainly, primarily, for the most part)","explanation":"Hauptsächlich (mainly, primarily, chiefly) — adverb from Hauptsache (main thing) + -lich. Der Film ist hauptsächlich auf Englisch = The film is mainly in English. Hauptsächlich besteht das Problem aus... = The problem mainly consists of... Compare: vor allem (above all — first in priority), überwiegend (predominantly — by proportion), meistens (mostly — frequency).","examples":[{"sentence":"Der Bericht basiert hauptsächlich auf internen Dokumenten.","translation":"The report is based mainly on internal documents."},{"sentence":"Sie arbeitet hauptsächlich mit Kunden aus dem Ausland.","translation":"She mainly works with customers from abroad."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Mundartlich'' means?","options":["dialectal","regional","local","vernacular"],"correctAnswer":"dialectal"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"On television and radio Standard German is mainly spoken.","options":["Im Fernsehen und Radio wird hauptsächlich Hochdeutsch gesprochen.","Fernsehen hat Hochdeutsch.","Deutsche sprechen im TV Hochdeutsch.","Hochdeutsch ist die Standardsprache."],"correctAnswer":"Im Fernsehen und Radio wird hauptsächlich Hochdeutsch gesprochen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Bericht basiert ___ auf internen Dokumenten.","options":["hauptsächlich","hauptsätzlich","hauptsächlicherweise","hauptsätzlicherweise"],"correctAnswer":"hauptsächlich"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She mainly works with customers from abroad","wordBankItems":["Sie","arbeitet","hauptsächlich","mit","Kunden","aus","dem","Ausland","."],"correctAnswer":"Sie arbeitet hauptsächlich mit Kunden aus dem Ausland ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Hochdeutsch'' means?","options":["Standard German","High German","Upper German","Literary German"],"correctAnswer":"Standard German"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000117',1,'APPROVED','PUBLISHED',
'{"objectives":["Understand language registers","Use formal and informal register","Switch appropriately between registers"],"explanation":{"intro":"Language register vocabulary at B1 covers formal vs. informal language, technical language, and appropriate register choice.","culturalNote":"German has strong register distinctions: Amtssprache (official language), Fachsprache (technical language), Umgangssprache (colloquial), Jugendsprache (youth language), Standardsprache (standard). The Sie/du distinction is the most visible register marker. Written German is more formal than spoken."},"examples":[{"german":"In der Behördenkorrespondenz verwendet man die Amtssprache mit bestimmten Formulierungen.","english":"In official correspondence one uses the administrative language with specific formulations."},{"german":"Das Register der Sprache muss zur Situation passen.","english":"The register of the language must match the situation."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can identify and use appropriate language registers in German."}}',
'{"items":[{"word":"das Register","translation":"register (language)","pronunciation":"dahs reh-GIS-ter","example":"Das sprachliche Register."},{"word":"die Amtssprache","translation":"official/administrative language","pronunciation":"dee AMTS-shpra-kheh","example":"Die Amtssprache."},{"word":"umgangssprachlich","translation":"colloquial","pronunciation":"oom-GANGS-shpra-khlikh","example":"Umgangssprachlich sagen."},{"word":"angemessen","translation":"appropriate/suitable","pronunciation":"AN-geh-mes-en","example":"Angemessen reagieren."},{"word":"die Fachsprache","translation":"technical language","pronunciation":"dee FAKH-shpra-kheh","example":"Medizinische Fachsprache."},{"word":"gehobene Sprache","translation":"elevated/formal language","pronunciation":"geh-HOH-beh-neh SHPRA-kheh","example":"Gehobene Sprache verwenden."}]}',
'{"title":"Passen zu/zu etw passen — to match/be appropriate for","pattern":"etwas passt zu + dative / etwas passt für + accusative (to match, suit, be appropriate)","explanation":"Passen zu + dative = to suit, match, be appropriate for (style/register matching). Das Register muss zur Situation passen = The register must match the situation. Also: Das passt nicht zusammen = That doesn''t go together. Distinguish: passen zu (to match/suit — qualitative fit), passen für (to be suitable for — functional fit). Both dative after zu, accusative after für.","examples":[{"sentence":"Dieser Ton passt nicht zur Situation.","translation":"This tone doesn''t suit the situation."},{"sentence":"Ein förmliches Register passt besser für offizielle Schreiben.","translation":"A formal register is more suitable for official correspondence."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Angemessen'' means?","options":["appropriate/suitable","adequate","proper","fitting"],"correctAnswer":"appropriate/suitable"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The register of the language must match the situation.","options":["Das Register der Sprache muss zur Situation passen.","Sprache passt sich an.","Man muss die richtige Sprache wählen.","Register ist wichtig."],"correctAnswer":"Das Register der Sprache muss zur Situation passen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Dieser Ton passt nicht zur ___.","options":["Situation","der Situation","Situationen","Situationsbeurteilung"],"correctAnswer":"Situation"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: A formal register is more suitable for official correspondence","wordBankItems":["Ein","förmliches","Register","passt","besser","für","offizielle","Schreiben","."],"correctAnswer":"Ein förmliches Register passt besser für offizielle Schreiben ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Umgangssprachlich'' means?","options":["colloquial","informal","everyday","casual"],"correctAnswer":"colloquial"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000118',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss language learning strategies","Use Sprachlernstrategie vocabulary","Reflect on learning German"],"explanation":{"intro":"Language learning vocabulary at B1 covers strategies, methods, and reflection on language acquisition.","culturalNote":"Germany has a strong tradition of language learning — Fremdsprachenkenntnisse (foreign language skills) are expected in business. English proficiency is high in Germany. The CEFR (Gemeinsamer Europäischer Referenzrahmen) sets the standard for language levels. Tandem learning (language exchange) is popular."},"examples":[{"german":"Das Tandem-Lernen verbindet Muttersprachler verschiedener Sprachen zum gegenseitigen Lernen.","english":"Tandem learning connects native speakers of different languages for mutual learning."},{"german":"Durch Immersion lernt man eine Sprache am schnellsten.","english":"Through immersion one learns a language most quickly."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss language learning strategies and reflect on my German learning journey."}}',
'{"items":[{"word":"die Immersion","translation":"immersion","pronunciation":"dee ih-MER-zyohn","example":"Sprachliche Immersion."},{"word":"der Muttersprachler","translation":"native speaker","pronunciation":"dayr MOO-ter-shpra-khler","example":"Ein Muttersprachler."},{"word":"gegenseitig","translation":"mutual/reciprocal","pronunciation":"GAY-gen-zy-tikh","example":"Gegenseitiges Lernen."},{"word":"die Strategie","translation":"strategy","pronunciation":"dee shtrah-teh-GEE","example":"Eine Lernstrategie."},{"word":"der Spracherwerb","translation":"language acquisition","pronunciation":"dayr SHPRA-kher-vairp","example":"Der Spracherwerb."},{"word":"am schnellsten","translation":"most quickly","pronunciation":"am SHNEL-sten","example":"Am schnellsten lernen."}]}',
'{"title":"Durch + accusative — through/by means of","pattern":"durch + accusative = through, by means of, via (cause or method)","explanation":"Durch + accusative = through, by means of, as a result of. Durch Immersion lernt man schnell = One learns quickly through immersion. Durch has two meanings: physical (durch den Wald = through the forest) and causal/instrumental (durch Übung = through practice). Very common with verbs: durch etwas erreichen (to achieve through), durch etwas lösen (to solve through/via).","examples":[{"sentence":"Durch regelmäßiges Üben verbessert man seine Kenntnisse.","translation":"Through regular practice one improves one''s knowledge."},{"sentence":"Das Problem wurde durch Dialog gelöst.","translation":"The problem was solved through dialogue."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Muttersprachler'' means?","options":["native speaker","mother tongue speaker","first language speaker","primary speaker"],"correctAnswer":"native speaker"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Through immersion one learns a language most quickly.","options":["Durch Immersion lernt man eine Sprache am schnellsten.","Immersion hilft beim Lernen.","Mit Immersion lernt man gut.","Sprachen lernt man durch Kontakt."],"correctAnswer":"Durch Immersion lernt man eine Sprache am schnellsten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Durch regelmäßiges Üben verbessert man seine ___.","options":["Kenntnisse","Kenntnis","Kenntnissen","die Kenntnisse"],"correctAnswer":"Kenntnisse"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The problem was solved through dialogue","wordBankItems":["Das","Problem","wurde","durch","Dialog","gelöst","."],"correctAnswer":"Das Problem wurde durch Dialog gelöst ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Gegenseitig'' means?","options":["mutual/reciprocal","bilateral","shared","collective"],"correctAnswer":"mutual/reciprocal"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-000000000105','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l261',261,'Kino und Film','Cinema and film vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000106','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l262',262,'Theater und Oper','Theatre and opera vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000107','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l263',263,'Architektur','Architecture vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000108','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l264',264,'Seniorenalltag','Senior life vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000109','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l265',265,'Jugend und Generation Z','Youth and Gen Z vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000010a','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l266',266,'Gleichberechtigung','Gender equality vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000010b','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l267',267,'Familienpolitik','Family policy vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000010c','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l268',268,'Digitale Gesellschaft','Digital society and data protection','PUBLISHED'),
('dd000000-0000-0000-0000-00000000010d','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l269',269,'Humor','Humour and comedy','PUBLISHED'),
('dd000000-0000-0000-0000-00000000010e','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l270',270,'Kabarett','German political cabaret','PUBLISHED'),
('dd000000-0000-0000-0000-00000000010f','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l271',271,'Bewerbungsschreiben','Job application letters','PUBLISHED'),
('dd000000-0000-0000-0000-000000000110','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l272',272,'Vorstellungsgespräch','Job interview vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000111','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l273',273,'Am Arbeitsplatz','Workplace communication','PUBLISHED'),
('dd000000-0000-0000-0000-000000000112','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l274',274,'Arbeitskonflikte','Workplace conflict vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000113','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l275',275,'Gewerkschaft','Trade union vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000114','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l276',276,'Selbstständigkeit','Self-employment vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000115','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l277',277,'Weiterbildung','Continuing education vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000116','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l278',278,'Deutsche Dialekte','German dialects vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000117','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l279',279,'Sprachregister','Language register vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000118','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l280',280,'Fremdsprachen lernen','Language learning strategies','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000105' WHERE stable_ref = 'de-b1-u03-l261' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000106' WHERE stable_ref = 'de-b1-u03-l262' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000107' WHERE stable_ref = 'de-b1-u03-l263' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000108' WHERE stable_ref = 'de-b1-u03-l264' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000109' WHERE stable_ref = 'de-b1-u03-l265' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000010a' WHERE stable_ref = 'de-b1-u03-l266' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000010b' WHERE stable_ref = 'de-b1-u03-l267' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000010c' WHERE stable_ref = 'de-b1-u03-l268' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000010d' WHERE stable_ref = 'de-b1-u03-l269' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000010e' WHERE stable_ref = 'de-b1-u03-l270' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000010f' WHERE stable_ref = 'de-b1-u03-l271' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000110' WHERE stable_ref = 'de-b1-u03-l272' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000111' WHERE stable_ref = 'de-b1-u03-l273' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000112' WHERE stable_ref = 'de-b1-u03-l274' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000113' WHERE stable_ref = 'de-b1-u03-l275' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000114' WHERE stable_ref = 'de-b1-u03-l276' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000115' WHERE stable_ref = 'de-b1-u03-l277' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000116' WHERE stable_ref = 'de-b1-u03-l278' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000117' WHERE stable_ref = 'de-b1-u03-l279' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000118' WHERE stable_ref = 'de-b1-u03-l280' AND lesson_id IS NULL;
