-- V68: German B1 lessons 321-340 (B1 batch 7)
-- Level: B1 (10000000-0000-0000-0000-000000000003), unit de-b1-u03
-- Hex: 321=0x141, 340=0x154

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-000000000141','de-b1-l321','Digitalisierung - Digitalisation','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000142','de-b1-l322','Künstliche Intelligenz - AI','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000143','de-b1-l323','Datenschutz 2 - Data Protection 2','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000144','de-b1-l324','Soziale Medien 2 - Social Media 2','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000145','de-b1-l325','Fake News - Fake News','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000146','de-b1-l326','Gaming - Gaming Culture','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000147','de-b1-l327','E-Commerce - Online Shopping','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000148','de-b1-l328','Homeoffice - Remote Work','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000149','de-b1-l329','Bildung digital - Digital Education','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000014a','de-b1-l330','Demokratie - Democracy','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000014b','de-b1-l331','Wahlen - Elections','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000014c','de-b1-l332','Parteien - Political Parties','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000014d','de-b1-l333','Bundesregierung - Federal Government','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000014e','de-b1-l334','Föderalismus - Federalism','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000014f','de-b1-l335','Europäische Union - EU','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000150','de-b1-l336','Außenpolitik - Foreign Policy','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000151','de-b1-l337','Internationale Beziehungen - Intl Relations','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000152','de-b1-l338','Frieden und Sicherheit - Peace Security','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000153','de-b1-l339','Meinungsfreiheit - Freedom of Speech','language','de','B1','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000154','de-b1-l340','Pressefreiheit - Press Freedom','language','de','B1','APPROVED','PUBLISHED',1,1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000141',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss digitalisation in Germany","Use Digitalisierung vocabulary","Talk about digital transformation"],"explanation":{"intro":"Digitalisation vocabulary at B1 covers the transformation of society through digital technology.","culturalNote":"Germany is known for its strong traditional industry (Mittelstand, Automobilindustrie) but faces significant challenges in digital transformation. Concepts like Digitalisierung, Industrie 4.0, and smarte Infrastruktur are central in political and business discourse. Germany ranks mid-range in EU digital economy indices."},"examples":[{"german":"Die Digitalisierung verändert nahezu alle Branchen der Wirtschaft.","english":"Digitalisation is changing almost all sectors of the economy."},{"german":"Viele Behörden kämpfen noch damit, ihre Dienste online anzubieten.","english":"Many authorities are still struggling to offer their services online."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss digital transformation, digitalisation, and the digital economy in German."}}',
'{"items":[{"word":"nahezu","translation":"almost/nearly","pronunciation":"NAH-hey-tsoo","example":"Nahezu alle."},{"word":"die Branche","translation":"sector/industry","pronunciation":"dee BRAN-sheh","example":"Alle Branchen."},{"word":"die Behörde","translation":"authority/office","pronunciation":"dee beh-HÖR-deh","example":"Staatliche Behörden."},{"word":"kämpfen damit, zu","translation":"to struggle to","pronunciation":"KEMP-fen dah-mit tsoo","example":"Damit kämpfen."},{"word":"die Industrie 4.0","translation":"Industry 4.0","pronunciation":"dee in-doos-TREE feer-komma-nool","example":"Industrie 4.0."},{"word":"smarte Infrastruktur","translation":"smart infrastructure","pronunciation":"SMART-eh in-fra-shtrooc-TOOR","example":"Smarte Infrastruktur."}]}',
'{"title":"Damit kämpfen, etwas zu tun — to struggle to do something","pattern":"mit etwas kämpfen OR damit kämpfen, etwas zu tun (to struggle with / to do)","explanation":"Kämpfen = to fight/struggle. Kämpfen mit + dative = to struggle with a noun: Ich kämpfe mit dem Problem = I struggle with the problem. Kämpfen damit, zu + infinitive = to struggle to do: Sie kämpfen damit, ihre Dienste anzubieten = They struggle to offer their services. Damit is an anticipatory da-compound for the zu-infinitive clause. Note: ringen (to wrestle/struggle — more dramatic), sich abmühen (to toil).","examples":[{"sentence":"Er kämpft damit, die Sprache zu lernen.","translation":"He struggles to learn the language."},{"sentence":"Das Unternehmen kämpft mit sinkenden Gewinnen.","translation":"The company is struggling with declining profits."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Behörde'' means?","options":["authority/office","department","ministry","agency"],"correctAnswer":"authority/office"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Digitalisation is changing almost all sectors of the economy.","options":["Die Digitalisierung verändert nahezu alle Branchen der Wirtschaft.","Digital ist alles anders.","Digitalisierung ändert die Wirtschaft.","Alle Branchen werden digital."],"correctAnswer":"Die Digitalisierung verändert nahezu alle Branchen der Wirtschaft."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er kämpft damit, die Sprache zu ___.","options":["lernen","lernend","gelernten","gelernt"],"correctAnswer":"lernen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The company is struggling with declining profits","wordBankItems":["Das","Unternehmen","kämpft","mit","sinkenden","Gewinnen","."],"correctAnswer":"Das Unternehmen kämpft mit sinkenden Gewinnen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Nahezu'' means?","options":["almost/nearly","approximately","about","roughly"],"correctAnswer":"almost/nearly"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000142',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss artificial intelligence","Use KI vocabulary","Talk about AI applications and risks"],"explanation":{"intro":"AI vocabulary at B1 covers machine learning, automation, and the societal impacts of artificial intelligence.","culturalNote":"Künstliche Intelligenz (KI) is a major topic in German politics and industry. Germany has invested in AI through its Nationale KI-Strategie (2018, updated 2023). Concerns about Arbeitsplatzverlust (job loss), Datenschutz (data protection), and Algorithmenethik (algorithmic ethics) dominate the debate."},"examples":[{"german":"Künstliche Intelligenz kann repetitive Aufgaben automatisieren und Menschen entlasten.","english":"Artificial intelligence can automate repetitive tasks and relieve people of the burden."},{"german":"Gleichzeitig wirft KI ethische Fragen auf, die noch nicht vollständig beantwortet sind.","english":"At the same time AI raises ethical questions that have not yet been fully answered."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss artificial intelligence, automation, and AI ethics in German."}}',
'{"items":[{"word":"künstliche Intelligenz","translation":"artificial intelligence","pronunciation":"KÜNST-li-kheh in-tel-ee-GENTS","example":"Künstliche Intelligenz."},{"word":"automatisieren","translation":"to automate","pronunciation":"ow-toh-mah-tee-ZEER-en","example":"Aufgaben automatisieren."},{"word":"entlasten","translation":"to relieve/unburden","pronunciation":"ent-LAS-ten","example":"Menschen entlasten."},{"word":"gleichzeitig","translation":"at the same time","pronunciation":"GLYKH-tsy-tikh","example":"Gleichzeitig auch."},{"word":"aufwerfen","translation":"to raise (a question)","pronunciation":"OWF-ver-fen","example":"Fragen aufwerfen."},{"word":"vollständig","translation":"fully/completely","pronunciation":"FOL-shten-dikh","example":"Vollständig beantwortet."}]}',
'{"title":"Aufwerfen — to raise (a question/problem)","pattern":"etwas wirft etwas auf (separable) — to raise, to throw up (a question, issue, problem)","explanation":"Aufwerfen (separable) = to raise, throw up (questions, issues, problems). Das wirft Fragen auf = That raises questions. Strong verb: wirft auf / warf auf / hat aufgeworfen. Commonly used with: Fragen (questions), Probleme (problems), Zweifel (doubts), Bedenken (concerns). Compare: stellen (to pose — deliberate action by a person: eine Frage stellen = to ask a question); aufwerfen (a situation/event raises a question spontaneously).","examples":[{"sentence":"Der Fall wirft schwierige ethische Fragen auf.","translation":"The case raises difficult ethical questions."},{"sentence":"Das Experiment hat neue Zweifel an der Theorie aufgeworfen.","translation":"The experiment has raised new doubts about the theory."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Gleichzeitig'' means?","options":["at the same time","simultaneously","equally","meanwhile"],"correctAnswer":"at the same time"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Artificial intelligence can automate repetitive tasks and relieve people of the burden.","options":["Künstliche Intelligenz kann repetitive Aufgaben automatisieren und Menschen entlasten.","KI hilft Menschen.","Aufgaben werden automatisch erledigt.","KI ersetzt Menschen."],"correctAnswer":"Künstliche Intelligenz kann repetitive Aufgaben automatisieren und Menschen entlasten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Fall wirft schwierige ethische Fragen ___.","options":["auf","hoch","aus","vor"],"correctAnswer":"auf"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The experiment has raised new doubts about the theory","wordBankItems":["Das","Experiment","hat","neue","Zweifel","an","der","Theorie","aufgeworfen","."],"correctAnswer":"Das Experiment hat neue Zweifel an der Theorie aufgeworfen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Aufwerfen'' is best used when?","options":["a situation spontaneously raises questions","a person deliberately asks","an issue is discussed","a problem is solved"],"correctAnswer":"a situation spontaneously raises questions"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000143',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss data protection at B1","Use advanced DSGVO vocabulary","Talk about digital privacy rights"],"explanation":{"intro":"Advanced data protection vocabulary covers GDPR, digital rights, and online privacy at B1.","culturalNote":"Germany''s Datenschutz culture is one of the strictest in the world. The DSGVO (Datenschutzgrundverordnung — EU GDPR) is widely discussed. Concepts like Einwilligung (consent), Auskunftsrecht (right of access), Recht auf Vergessenwerden (right to be forgotten) are known. Germans are historically privacy-conscious due to Stasi history."},"examples":[{"german":"Nach der DSGVO hat jede Person das Recht, Auskunft über ihre gespeicherten Daten zu verlangen.","english":"According to GDPR, every person has the right to demand information about their stored data."},{"german":"Die Einwilligung zur Datenverarbeitung muss freiwillig und ausdrücklich erteilt werden.","english":"Consent to data processing must be given voluntarily and explicitly."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss GDPR, data protection rights, and digital privacy in German."}}',
'{"items":[{"word":"die Einwilligung","translation":"consent","pronunciation":"dee yn-VIL-ee-goong","example":"Einwilligung geben."},{"word":"ausdrücklich","translation":"explicit/expressly","pronunciation":"OWS-drük-likh","example":"Ausdrücklich erteilen."},{"word":"die Datenverarbeitung","translation":"data processing","pronunciation":"dee DAH-ten-fer-ar-by-toong","example":"Datenverarbeitung."},{"word":"erteilen","translation":"to grant/issue","pronunciation":"er-TY-len","example":"Genehmigung erteilen."},{"word":"das Auskunftsrecht","translation":"right of access","pronunciation":"dahs OWS-koonfs-rekht","example":"Auskunftsrecht nutzen."},{"word":"freiwillig","translation":"voluntary","pronunciation":"FRY-vil-ikh","example":"Freiwillig zustimmen."}]}',
'{"title":"Das Recht, etwas zu tun / das Recht auf — right to do / right to","pattern":"das Recht, etwas zu tun (right to do) OR das Recht auf + accusative (right to/of)","explanation":"Two patterns for rights: 1) Das Recht, zu + infinitive: Jeder hat das Recht, seine Meinung zu äußern = Everyone has the right to express their opinion. 2) Das Recht auf + accusative: das Recht auf Bildung = the right to education. In legal/political language both are common. Einfordern = to claim/enforce (a right). Verletzen = to violate. Note: bei etw bleiben = to stick with — unrelated, don''t confuse.","examples":[{"sentence":"Jeder hat das Recht, seine Daten einsehen zu lassen.","translation":"Everyone has the right to have their data viewed."},{"sentence":"Das Recht auf Wohnen ist in manchen Verfassungen verankert.","translation":"The right to housing is enshrined in some constitutions."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Freiwillig'' means?","options":["voluntary","freely","willingly","optional"],"correctAnswer":"voluntary"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Consent to data processing must be given voluntarily and explicitly.","options":["Die Einwilligung zur Datenverarbeitung muss freiwillig und ausdrücklich erteilt werden.","Man muss zustimmen.","Daten brauchen eine Genehmigung.","Ausdrückliche Zustimmung ist nötig."],"correctAnswer":"Die Einwilligung zur Datenverarbeitung muss freiwillig und ausdrücklich erteilt werden."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Recht auf Wohnen ist in manchen Verfassungen ___.","options":["verankert","eingebaut","enthalten","festgelegt"],"correctAnswer":"verankert"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Everyone has the right to have their data viewed","wordBankItems":["Jeder","hat","das","Recht",",","seine","Daten","einsehen","zu","lassen","."],"correctAnswer":"Jeder hat das Recht , seine Daten einsehen zu lassen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Erteilen'' means?","options":["to grant/issue","to give","to allow","to permit"],"correctAnswer":"to grant/issue"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000144',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss social media at B1","Use Plattform vocabulary","Talk about algorithms and influence"],"explanation":{"intro":"Advanced social media vocabulary at B1 covers platforms, algorithms, content creation, and societal influence.","culturalNote":"Social media use is high in Germany — Instagram, TikTok, YouTube, and Twitter/X are most popular. Influencer (das Influencertum) is now a recognised career. Hassrede (hate speech), Trolling, and Algorithmenblase (filter bubble) are widely debated. The NetzDG (Netzwerkdurchsetzungsgesetz) requires platforms to remove illegal content quickly."},"examples":[{"german":"Algorithmen bestimmen, welche Inhalte Nutzer in ihrem Feed sehen.","english":"Algorithms determine which content users see in their feed."},{"german":"Die Filterbubble verstärkt bestehende Meinungen und erschwert den offenen Diskurs.","english":"The filter bubble reinforces existing opinions and makes open discourse more difficult."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss social media algorithms, filter bubbles, and online influence in German."}}',
'{"items":[{"word":"der Algorithmus","translation":"algorithm","pronunciation":"dayr al-go-RIT-moos","example":"Der Algorithmus."},{"word":"der Inhalt","translation":"content/contents","pronunciation":"dayr IN-halt","example":"Digitale Inhalte."},{"word":"der Nutzer","translation":"user","pronunciation":"dayr NOOTS-er","example":"Nutzer der Plattform."},{"word":"verstärken","translation":"to reinforce/intensify","pronunciation":"fer-SHTÄR-ken","example":"Meinungen verstärken."},{"word":"erschweren","translation":"to make difficult/hinder","pronunciation":"er-SHVAY-ren","example":"Den Diskurs erschweren."},{"word":"die Filterbubble","translation":"filter bubble","pronunciation":"dee FIL-ter-bub-ble","example":"Filterbubble durchbrechen."}]}',
'{"title":"Bestimmen, welche — to determine which (indirect question)","pattern":"etwas bestimmt, welche/wer/was/wie + clause (determines which/who/what/how)","explanation":"Bestimmen + indirect question clause = to determine, decide which/who/what. Der Algorithmus bestimmt, welche Inhalte Nutzer sehen = The algorithm determines which content users see. The indirect question uses verb-final word order. Other reporting verbs: festlegen (to set/specify), entscheiden (to decide), regeln (to regulate). Welche + noun: welche Inhalte (which content — plural). Wer (who), was (what), wie (how), wo (where) are also common.","examples":[{"sentence":"Der Arzt bestimmt, welche Behandlung am besten ist.","translation":"The doctor determines which treatment is best."},{"sentence":"Sie hat noch nicht entschieden, welchen Kurs sie wählen soll.","translation":"She has not yet decided which course she should choose."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Erschweren'' means?","options":["to make difficult/hinder","to complicate","to obstruct","to prevent"],"correctAnswer":"to make difficult/hinder"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Algorithms determine which content users see in their feed.","options":["Algorithmen bestimmen, welche Inhalte Nutzer in ihrem Feed sehen.","Algorithmen zeigen Inhalte.","Nutzer sehen was Algorithmen wählen.","Feed-Inhalte werden von Algorithmen kontrolliert."],"correctAnswer":"Algorithmen bestimmen, welche Inhalte Nutzer in ihrem Feed sehen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Arzt bestimmt, ___ Behandlung am besten ist.","options":["welche","welchen","welchem","was für eine"],"correctAnswer":"welche"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She has not yet decided which course she should choose","wordBankItems":["Sie","hat","noch","nicht","entschieden",",","welchen","Kurs","sie","wählen","soll","."],"correctAnswer":"Sie hat noch nicht entschieden , welchen Kurs sie wählen soll ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Verstärken'' means?","options":["to reinforce/intensify","to strengthen","to amplify","to increase"],"correctAnswer":"to reinforce/intensify"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000145',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss fake news and misinformation","Use Desinformation vocabulary","Talk about media literacy"],"explanation":{"intro":"Fake news vocabulary at B1 covers misinformation, media literacy, and the challenges of distinguishing truth from falsehood online.","culturalNote":"Fake News and Desinformation are serious concerns in Germany. The Begriff (term) ''Lügenpresse'' (lying press) has been weaponised by far-right populists. Media literacy (Medienkompetenz) is now taught in schools. Fact-checking organisations like Correctiv.org are important correctives."},"examples":[{"german":"Desinformation verbreitet sich in sozialen Medien oft schneller als wahre Informationen.","english":"Misinformation often spreads faster in social media than true information."},{"german":"Medienkompetenz hilft dabei, Falschmeldungen von seriösen Nachrichten zu unterscheiden.","english":"Media literacy helps to distinguish fake news from reputable news."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss fake news, misinformation, and media literacy in German."}}',
'{"items":[{"word":"die Desinformation","translation":"misinformation/disinformation","pronunciation":"dee des-in-for-mah-tsee-OHN","example":"Desinformation verbreiten."},{"word":"sich verbreiten","translation":"to spread","pronunciation":"zikh fer-BRY-ten","example":"Sich schnell verbreiten."},{"word":"seriös","translation":"reputable/reliable","pronunciation":"zeh-ree-ÖS","example":"Seriöse Quelle."},{"word":"die Falschmeldung","translation":"false report/fake news","pronunciation":"dee FALSH-mel-doong","example":"Eine Falschmeldung."},{"word":"die Medienkompetenz","translation":"media literacy","pronunciation":"dee meh-dee-en-kom-peh-TENTS","example":"Medienkompetenz fördern."},{"word":"überprüfen","translation":"to check/verify","pronunciation":"ü-ber-PRÜF-en","example":"Quellen überprüfen."}]}',
'{"title":"Helfen dabei, etwas zu tun — to help to do","pattern":"etwas/jemand hilft (dabei), etwas zu tun (to help [to do something])","explanation":"Helfen + zu-infinitive = to help to do. Medienkompetenz hilft dabei, Falschmeldungen zu erkennen = Media literacy helps to recognise fake news. Dabei is optional but common as an anticipatory pronoun before the zu-clause. Helfen + dative person + zu-infinitive: Er hilft mir, das zu verstehen = He helps me understand that. Also: jemandem bei etwas helfen (to help someone with something — dative + bei + dative noun).","examples":[{"sentence":"Das Tool hilft dabei, Plagiate zu erkennen.","translation":"The tool helps to detect plagiarism."},{"sentence":"Er hat mir geholfen, das Problem zu lösen.","translation":"He helped me solve the problem."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Seriös'' means?","options":["reputable/reliable","serious","trustworthy","credible"],"correctAnswer":"reputable/reliable"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Misinformation often spreads faster in social media than true information.","options":["Desinformation verbreitet sich in sozialen Medien oft schneller als wahre Informationen.","Fake News sind in sozialen Medien.","In sozialen Medien gibt es viele Falschmeldungen.","Falsche Infos verbreiten sich schnell."],"correctAnswer":"Desinformation verbreitet sich in sozialen Medien oft schneller als wahre Informationen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Tool hilft dabei, Plagiate zu ___.","options":["erkennen","erkennend","erkannt","erkenntnis"],"correctAnswer":"erkennen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: He helped me solve the problem","wordBankItems":["Er","hat","mir","geholfen",",","das","Problem","zu","lösen","."],"correctAnswer":"Er hat mir geholfen , das Problem zu lösen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Falschmeldung'' means?","options":["false report/fake news","false message","wrong news","misinformation"],"correctAnswer":"false report/fake news"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000146',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss gaming culture","Use Gaming vocabulary","Talk about esports and video games"],"explanation":{"intro":"Gaming vocabulary at B1 covers video games, esports, and the cultural impact of gaming.","culturalNote":"Germany is Europe''s largest video games market. The USK (Unterhaltungssoftware Selbstkontrolle) rates games. Deutsche Behörden (German authorities) have historically been cautious about violent games (Killerspiele debate). Esports is increasingly professionalised. The GamesCom trade fair in Cologne is the world''s largest gaming event."},"examples":[{"german":"E-Sport hat sich in Deutschland zu einem ernsthaften Berufsbild entwickelt.","english":"Esports has developed in Germany into a serious profession."},{"german":"Die GamesCom in Köln zieht jedes Jahr Hunderttausende von Spielbegeisterten an.","english":"GamesCom in Cologne attracts hundreds of thousands of gaming enthusiasts every year."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss gaming culture, esports, and the video games industry in German."}}',
'{"items":[{"word":"das Berufsbild","translation":"professional profile/occupation","pronunciation":"dahs beh-ROOFS-bilt","example":"Ein neues Berufsbild."},{"word":"anziehen","translation":"to attract","pronunciation":"AN-tsee-en","example":"Besucher anziehen."},{"word":"spielbegeistert","translation":"enthusiastic about games","pronunciation":"SHPEEL-beh-gys-tert","example":"Spielbegeisterte."},{"word":"ernsthaft","translation":"serious/earnest","pronunciation":"ERNST-haft","example":"Ernsthaft betreiben."},{"word":"das Turnier","translation":"tournament","pronunciation":"dahs toor-NEER","example":"Ein Gaming-Turnier."},{"word":"der Profi-Gamer","translation":"professional gamer","pronunciation":"dayr PRO-fee GAY-mer","example":"Profi-Gamer werden."}]}',
'{"title":"Sich zu etwas entwickeln — to develop into","pattern":"jemand/etwas entwickelt sich zu + dative (to develop into/become)","explanation":"Entwickeln (separable in some uses) with sich + zu + dative = to develop into. Der E-Sport hat sich zu einem Beruf entwickelt = Esports has developed into a profession. Also: sich weiterentwickeln (to further develop, evolve — no zu). Die Entwicklung (development). Note dative after zu: zu einem + noun (masculine/neuter), zu einer (feminine). Compare: werden + nominative (to become — simpler copula): Er wird Arzt = He becomes a doctor.","examples":[{"sentence":"Die Stadt hat sich zu einem wichtigen Wirtschaftsstandort entwickelt.","translation":"The city has developed into an important business location."},{"sentence":"Er hat sich zu einem ausgezeichneten Musiker entwickelt.","translation":"He has developed into an excellent musician."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Ernsthaft'' means?","options":["serious/earnest","sincere","genuine","professional"],"correctAnswer":"serious/earnest"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Esports has developed in Germany into a serious profession.","options":["E-Sport hat sich in Deutschland zu einem ernsthaften Berufsbild entwickelt.","E-Sport ist in Deutschland bekannt.","Profis spielen jetzt Videospiele.","E-Sport wird ernst genommen."],"correctAnswer":"E-Sport hat sich in Deutschland zu einem ernsthaften Berufsbild entwickelt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Stadt hat sich zu einem wichtigen Wirtschaftsstandort ___.","options":["entwickelt","entwickelte","entwickeln","weiterentwickelt"],"correctAnswer":"entwickelt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: He has developed into an excellent musician","wordBankItems":["Er","hat","sich","zu","einem","ausgezeichneten","Musiker","entwickelt","."],"correctAnswer":"Er hat sich zu einem ausgezeichneten Musiker entwickelt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Anziehen'' means?","options":["to attract","to draw","to pull","to lure"],"correctAnswer":"to attract"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000147',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss online shopping","Use E-Commerce vocabulary","Talk about consumer rights online"],"explanation":{"intro":"E-commerce vocabulary at B1 covers online shopping, logistics, returns, and consumer protection.","culturalNote":"Germany has one of Europe''s largest e-commerce markets. Amazon and Otto are dominant. Das Widerrufsrecht (right of withdrawal — 14 days, no questions asked) is a strong consumer protection. Paketboten (parcel delivery workers) are a visible part of modern life. Verbraucherschutzzentrale (consumer advice centres) help with disputes."},"examples":[{"german":"In Deutschland hat man beim Online-Kauf ein 14-tägiges Widerrufsrecht.","english":"In Germany one has a 14-day right of withdrawal for online purchases."},{"german":"Die Lieferkette von der Bestellung bis zur Haustür ist ein komplexes System.","english":"The supply chain from order to door is a complex system."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss online shopping, e-commerce, and consumer rights in German."}}',
'{"items":[{"word":"das Widerrufsrecht","translation":"right of withdrawal","pronunciation":"dahs VEE-der-roofs-rekht","example":"Widerrufsrecht nutzen."},{"word":"die Lieferkette","translation":"supply chain","pronunciation":"dee LEE-fer-ket-eh","example":"Die Lieferkette."},{"word":"die Bestellung","translation":"order","pronunciation":"dee beh-SHTEL-oong","example":"Eine Bestellung aufgeben."},{"word":"die Haustür","translation":"front door","pronunciation":"dee HOWS-tür","example":"An die Haustür liefern."},{"word":"das Rückgaberecht","translation":"right of return","pronunciation":"dahs RÜK-gah-beh-rekht","example":"Rückgaberecht ausüben."},{"word":"der Verbraucherschutz","translation":"consumer protection","pronunciation":"dayr fer-BROW-kher-shoots","example":"Verbraucherschutz."}]}',
'{"title":"Von...bis — from...to (spatial and temporal range)","pattern":"von + dative ... bis + accusative/nominative (from X to Y — spatial and temporal)","explanation":"Von...bis = from...to. Temporal: von Montag bis Freitag (from Monday to Friday). Spatial: von Berlin bis München (from Berlin to Munich). Von der Bestellung bis zur Haustür = from the order to the front door. Note: bis + article requires the correct case for the following preposition or no article after bis (bis Berlin — no article needed). Von...bis zu: when followed by a dative article — von der Stadt bis zum Bahnhof = from the city to the station.","examples":[{"sentence":"Die Lieferung dauert von zwei bis fünf Werktage.","translation":"Delivery takes from two to five working days."},{"sentence":"Von der Produktion bis zum Verkauf vergehen mehrere Wochen.","translation":"Several weeks pass from production to sale."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Widerrufsrecht'' means?","options":["right of withdrawal","cancellation right","return policy","refund right"],"correctAnswer":"right of withdrawal"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In Germany one has a 14-day right of withdrawal for online purchases.","options":["In Deutschland hat man beim Online-Kauf ein 14-tägiges Widerrufsrecht.","Online-Käufer haben Rechte.","Man kann 14 Tage zurückgeben.","Deutschland schützt Online-Käufer."],"correctAnswer":"In Deutschland hat man beim Online-Kauf ein 14-tägiges Widerrufsrecht."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Lieferung dauert von zwei bis fünf ___.","options":["Werktage","Werktagen","Werktags","Arbeitstage"],"correctAnswer":"Werktage"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Several weeks pass from production to sale","wordBankItems":["Von","der","Produktion","bis","zum","Verkauf","vergehen","mehrere","Wochen","."],"correctAnswer":"Von der Produktion bis zum Verkauf vergehen mehrere Wochen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Verbraucherschutz'' means?","options":["consumer protection","buyer protection","customer service","consumer rights"],"correctAnswer":"consumer protection"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000148',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss remote work","Use Homeoffice vocabulary","Talk about work-life balance"],"explanation":{"intro":"Remote work vocabulary at B1 covers home office culture, digital workplace tools, and work-life balance.","culturalNote":"Homeoffice became widespread during COVID-19 and remains common in Germany. The Recht auf Homeoffice (right to work from home) is debated but not universal. Schreibtischarbeit (desk work) and Präsenzkultur (presence culture — expectation to be in the office) are terms in this debate. German labour law (Arbeitsrecht) strictly regulates working hours even at home."},"examples":[{"german":"Im Homeoffice verschwimmt die Grenze zwischen Arbeit und Privatleben.","english":"Working from home, the boundary between work and private life blurs."},{"german":"Viele Unternehmen bieten flexible Arbeitsmodelle an, bei denen Mitarbeiter selbst entscheiden können.","english":"Many companies offer flexible working models in which employees can decide for themselves."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss remote work, flexible working, and work-life balance in German."}}',
'{"items":[{"word":"verschwimmen","translation":"to blur/become blurred","pronunciation":"fer-SHVIM-en","example":"Die Grenzen verschwimmen."},{"word":"die Grenze","translation":"boundary/border","pronunciation":"dee GREN-tseh","example":"Grenzen setzen."},{"word":"das Privatleben","translation":"private life","pronunciation":"dahs pree-VAHT-lay-ben","example":"Das Privatleben schützen."},{"word":"selbst entscheiden","translation":"to decide for oneself","pronunciation":"ZELPST ent-SHY-den","example":"Selbst entscheiden."},{"word":"die Präsenzkultur","translation":"presence culture","pronunciation":"dee prä-ZENTS-kool-toor","example":"Präsenzkultur."},{"word":"die Überstunden","translation":"overtime","pronunciation":"dee Ü-ber-shtoon-den","example":"Überstunden machen."}]}',
'{"title":"Verschwimmen — to blur, become unclear","pattern":"etwas verschwimmt (something blurs, becomes indistinct — intransitive, sein)","explanation":"Verschwimmen (strong, sein) = to blur, become blurred, merge indistinctly. Die Grenzen verschwimmen = The boundaries blur. Perfect: ist verschwommen. Also: verschwimmt vor den Augen = blurs before one''s eyes (optically). Metaphorically very common: Grenzen zwischen X und Y verschwimmen = the line between X and Y blurs. Compare: undeutlich werden (to become unclear — general), sich verwischen (to be smeared/erased — physical), sich auflösen (to dissolve/disappear).","examples":[{"sentence":"Im modernen Leben verschwimmen die Grenzen zwischen Öffentlichem und Privatem.","translation":"In modern life the boundaries between public and private blur."},{"sentence":"Beim langen Lesen verschwimmen manchmal die Zeilen.","translation":"When reading for a long time, the lines sometimes blur."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Präsenzkultur'' means?","options":["presence culture","office culture","attendance requirement","in-person culture"],"correctAnswer":"presence culture"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Working from home, the boundary between work and private life blurs.","options":["Im Homeoffice verschwimmt die Grenze zwischen Arbeit und Privatleben.","Homeoffice macht es schwer, abzuschalten.","Arbeit und Privatleben trennen ist schwer.","Im Homeoffice gibt es keine Grenzen."],"correctAnswer":"Im Homeoffice verschwimmt die Grenze zwischen Arbeit und Privatleben."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Im modernen Leben verschwimmen die Grenzen zwischen Öffentlichem und ___.","options":["Privatem","Privaten","Privat","dem Privaten"],"correctAnswer":"Privatem"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: When reading for a long time, the lines sometimes blur","wordBankItems":["Beim","langen","Lesen","verschwimmen","manchmal","die","Zeilen","."],"correctAnswer":"Beim langen Lesen verschwimmen manchmal die Zeilen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Überstunden'' means?","options":["overtime","extra hours","additional work","working late"],"correctAnswer":"overtime"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000149',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss digital education","Use Bildungsdigitalisierung vocabulary","Talk about edtech and online learning"],"explanation":{"intro":"Digital education vocabulary at B1 covers e-learning, educational technology, and the digitisation of schools.","culturalNote":"Germany has been slower to digitise schools than other European countries. The DigitalPakt Schule (2019) allocated €5 billion for school digitisation. Tablets, interactive whiteboards, and learning management systems are being introduced. During COVID-19, homeschooling exposed gaps in digital infrastructure. University MOOCs (Massive Open Online Courses) are growing."},"examples":[{"german":"Digitale Lernplattformen können individuelles Lernen fördern.","english":"Digital learning platforms can promote individual learning."},{"german":"Nicht alle Schüler haben gleichermaßen Zugang zu digitalen Lernmitteln.","english":"Not all pupils have equal access to digital learning materials."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss digital education, e-learning, and educational technology in German."}}',
'{"items":[{"word":"die Lernplattform","translation":"learning platform","pronunciation":"dee LERN-plat-form","example":"Digitale Lernplattform."},{"word":"individuell","translation":"individual","pronunciation":"in-dee-vee-doo-EL","example":"Individuelles Lernen."},{"word":"gleichermaßen","translation":"equally","pronunciation":"GLY-kher-MAH-sen","example":"Gleichermaßen Zugang."},{"word":"das Lernmittel","translation":"learning material","pronunciation":"dahs LERN-mit-el","example":"Digitale Lernmittel."},{"word":"die Ausstattung","translation":"equipment/provision","pronunciation":"dee OWS-shtah-toong","example":"Digitale Ausstattung."},{"word":"fördern","translation":"to promote/support","pronunciation":"FÖR-dern","example":"Digitales Lernen fördern."}]}',
'{"title":"Gleichermaßen — equally, in equal measure","pattern":"gleichermaßen + adjective/verb OR nicht gleichermaßen (not equally — unequal access)","explanation":"Gleichermaßen = equally, in the same measure, alike (formal). Nicht alle Schüler haben gleichermaßen Zugang = Not all pupils have equal access. Gleichermaßen can modify a verb or adjective: Das gilt gleichermaßen für alle = That applies equally to everyone. Synonyms: gleichmäßig (evenly distributed — more physical), in gleichem Maße (to the same extent — formal), genauso (equally informal — just as), ebenso (likewise).","examples":[{"sentence":"Das Problem betrifft Reiche und Arme gleichermaßen.","translation":"The problem affects rich and poor equally."},{"sentence":"Das gilt gleichermaßen für alle Mitglieder.","translation":"That applies equally to all members."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Ausstattung'' means?","options":["equipment/provision","furnishing","setup","resources"],"correctAnswer":"equipment/provision"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Not all pupils have equal access to digital learning materials.","options":["Nicht alle Schüler haben gleichermaßen Zugang zu digitalen Lernmitteln.","Digitale Bildung ist ungleich.","Nicht alle Kinder haben Tablets.","Der Zugang zu Bildung ist ungleich."],"correctAnswer":"Nicht alle Schüler haben gleichermaßen Zugang zu digitalen Lernmitteln."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Problem betrifft Reiche und Arme ___.","options":["gleichermaßen","gleichmäßig","gleichzeitig","genauso"],"correctAnswer":"gleichermaßen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That applies equally to all members","wordBankItems":["Das","gilt","gleichermaßen","für","alle","Mitglieder","."],"correctAnswer":"Das gilt gleichermaßen für alle Mitglieder ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Fördern'' means?","options":["to promote/support","to fund","to advance","to encourage"],"correctAnswer":"to promote/support"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000014a',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss democracy","Use Demokratie vocabulary","Talk about democratic values and institutions"],"explanation":{"intro":"Democracy vocabulary at B1 covers democratic principles, institutions, and values — especially in the German context.","culturalNote":"Germany is a parlamentarische Demokratie (parliamentary democracy) governed by the Grundgesetz (Basic Law, 1949). The Bundesverfassungsgericht (Federal Constitutional Court) in Karlsruhe is the guardian of the constitution. Wehrhafte Demokratie (militant democracy) — the idea that democracy must actively defend itself — is a key concept born from Weimar Republic failure."},"examples":[{"german":"Die Demokratie lebt von der aktiven Beteiligung der Bürgerinnen und Bürger.","english":"Democracy thrives on the active participation of citizens."},{"german":"Das Grundgesetz garantiert jedem Menschen in Deutschland grundlegende Rechte.","english":"The Basic Law guarantees every person in Germany fundamental rights."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss democracy, democratic institutions, and civic participation in German."}}',
'{"items":[{"word":"die Beteiligung","translation":"participation","pronunciation":"dee beh-TY-lee-goong","example":"Aktive Beteiligung."},{"word":"das Grundgesetz","translation":"Basic Law/constitution","pronunciation":"dahs GROOND-geh-zets","example":"Das Grundgesetz."},{"word":"garantieren","translation":"to guarantee","pronunciation":"gah-ran-TEER-en","example":"Rechte garantieren."},{"word":"grundlegend","translation":"fundamental/basic","pronunciation":"GROOND-lay-gend","example":"Grundlegende Rechte."},{"word":"die parlamentarische Demokratie","translation":"parliamentary democracy","pronunciation":"dee par-lah-men-TAH-ree-sheh deh-mo-krah-TEE","example":"Parlamentarische Demokratie."},{"word":"die Verfassung","translation":"constitution","pronunciation":"dee fer-FAS-oong","example":"Die Verfassung."}]}',
'{"title":"Von etwas leben — to thrive on/depend on","pattern":"etwas lebt von + dative (something thrives on, depends on, is sustained by)","explanation":"Leben von + dative = to live on, depend on, be sustained by, thrive on. Die Demokratie lebt von der Beteiligung = Democracy thrives on participation. Er lebt von seiner Rente = He lives on his pension (financial meaning). Die Stadt lebt vom Tourismus = The city thrives on tourism. Idiomatic and versatile. Compare: abhängen von (to depend on — more technical dependency), florieren durch (to flourish through — more external cause).","examples":[{"sentence":"Das Restaurant lebt von Stammkunden.","translation":"The restaurant thrives on regular customers."},{"sentence":"Er lebt von der Musik — das ist sein Beruf.","translation":"He lives from music — it is his profession."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Beteiligung'' means?","options":["participation","involvement","contribution","engagement"],"correctAnswer":"participation"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Democracy thrives on the active participation of citizens.","options":["Die Demokratie lebt von der aktiven Beteiligung der Bürgerinnen und Bürger.","Demokratie braucht Bürger.","Bürger sollen mitmachen.","Aktive Bürger stärken die Demokratie."],"correctAnswer":"Die Demokratie lebt von der aktiven Beteiligung der Bürgerinnen und Bürger."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Stadt lebt vom ___.","options":["Tourismus","Touristen","Tourismusbranche","Urlauber"],"correctAnswer":"Tourismus"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The restaurant thrives on regular customers","wordBankItems":["Das","Restaurant","lebt","von","Stammkunden","."],"correctAnswer":"Das Restaurant lebt von Stammkunden ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Grundgesetz'' means?","options":["Basic Law/constitution","fundamental law","basic rule","constitutional law"],"correctAnswer":"Basic Law/constitution"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000014b',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss elections in Germany","Use Wahlen vocabulary","Talk about the voting process"],"explanation":{"intro":"Elections vocabulary at B1 covers the German electoral system, voting rights, and election processes.","culturalNote":"Germany has a complex Verhältniswahlrecht mit Direktmandaten (proportional representation with direct mandates — mixed-member system). Bundestag elections happen every 4 years. The Wahlpflicht (compulsory voting) does not exist in Germany. Die Briefwahl (postal vote) is widely used. The 5%-Hürde (5% threshold) prevents small parties from entering parliament."},"examples":[{"german":"In Deutschland kann ab 18 Jahren jeder an der Bundestagswahl teilnehmen.","english":"In Germany everyone from age 18 can take part in the federal election."},{"german":"Die 5-Prozent-Hürde soll eine Zersplitterung des Parlaments verhindern.","english":"The 5-percent threshold is intended to prevent fragmentation of parliament."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss German elections, the voting system, and electoral politics."}}',
'{"items":[{"word":"die Bundestagswahl","translation":"federal election","pronunciation":"dee BOON-des-tahg-svahl","example":"Bei der Bundestagswahl."},{"word":"teilnehmen an","translation":"to take part in","pronunciation":"TYL-nay-men an","example":"Teilnehmen an der Wahl."},{"word":"die Hürde","translation":"hurdle/threshold","pronunciation":"dee HÜR-deh","example":"Die 5%-Hürde."},{"word":"die Zersplitterung","translation":"fragmentation","pronunciation":"dee tser-SHPLIT-er-oong","example":"Zersplitterung verhindern."},{"word":"das Direktmandat","translation":"direct mandate","pronunciation":"dahs dee-REKT-man-daht","example":"Ein Direktmandat gewinnen."},{"word":"die Briefwahl","translation":"postal vote","pronunciation":"dee BREEF-vahl","example":"Briefwahl beantragen."}]}',
'{"title":"Soll etwas verhindern — is intended to prevent","pattern":"etwas soll etwas verhindern (something is intended/designed to prevent something)","explanation":"Sollen with third person = is supposed to, is intended to (external obligation/design purpose). Die Regelung soll Betrug verhindern = The regulation is intended to prevent fraud. Die Hürde soll eine Zersplitterung verhindern = The threshold is intended to prevent fragmentation. Sollen here expresses the institutional purpose or design intent — very common in explaining laws and regulations. Compare: müssen (must — necessity), dürfen (may — permission).","examples":[{"sentence":"Das Gesetz soll Diskriminierung am Arbeitsplatz verhindern.","translation":"The law is intended to prevent discrimination in the workplace."},{"sentence":"Die Maßnahmen sollen die Ausbreitung der Krankheit eindämmen.","translation":"The measures are intended to contain the spread of the disease."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Briefwahl'' means?","options":["postal vote","mail-in ballot","absentee voting","written vote"],"correctAnswer":"postal vote"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The 5-percent threshold is intended to prevent fragmentation of parliament.","options":["Die 5-Prozent-Hürde soll eine Zersplitterung des Parlaments verhindern.","Die 5-Prozent-Hürde ist eine Grenze.","Kleine Parteien kommen nicht ins Parlament.","5% müssen Parteien erreichen."],"correctAnswer":"Die 5-Prozent-Hürde soll eine Zersplitterung des Parlaments verhindern."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Gesetz soll Diskriminierung am Arbeitsplatz ___.","options":["verhindern","verhindert","zu verhindern","verhindernd"],"correctAnswer":"verhindern"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The measures are intended to contain the spread of the disease","wordBankItems":["Die","Maßnahmen","sollen","die","Ausbreitung","der","Krankheit","eindämmen","."],"correctAnswer":"Die Maßnahmen sollen die Ausbreitung der Krankheit eindämmen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Zersplitterung'' means?","options":["fragmentation","splitting","division","breakdown"],"correctAnswer":"fragmentation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000014c',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss German political parties","Use Partei vocabulary","Talk about the party landscape"],"explanation":{"intro":"Political parties vocabulary at B1 covers the German multi-party system and the Volksparteien.","culturalNote":"Germany has six major parties in the Bundestag: CDU/CSU (Christian conservative), SPD (Social Democrats), Grüne (Greens), FDP (Liberals), Linke (Left), AfD (Alternative). Coalition government (Koalition) is the norm since no single party usually gets a majority. The Große Koalition (GroKo — Grand Coalition) was common in recent decades. Volksparteien (catch-all parties) have been losing support."},"examples":[{"german":"In Deutschland regiert meistens eine Koalition aus zwei oder mehr Parteien.","english":"In Germany a coalition of two or more parties usually governs."},{"german":"Die traditionellen Volksparteien haben in den letzten Jahrzehnten an Zustimmung verloren.","english":"The traditional catch-all parties have lost approval in recent decades."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss German political parties, coalitions, and the party landscape."}}',
'{"items":[{"word":"die Koalition","translation":"coalition","pronunciation":"dee koh-ah-leet-see-OHN","example":"Eine Koalition bilden."},{"word":"die Volkspartei","translation":"catch-all/people''s party","pronunciation":"dee FOLKS-par-ty","example":"Die Volkspartei."},{"word":"an Zustimmung verlieren","translation":"to lose approval/support","pronunciation":"an TSOO-shtim-oong fer-LEER-en","example":"An Zustimmung verlieren."},{"word":"das Jahrzehnt","translation":"decade","pronunciation":"dahs YAHR-tseynt","example":"In den letzten Jahrzehnten."},{"word":"das Programm","translation":"platform/programme","pronunciation":"dahs pro-GRAM","example":"Das Parteiprogramm."},{"word":"die Mehrheit","translation":"majority","pronunciation":"dee MAYR-hyt","example":"Eine Mehrheit erreichen."}]}',
'{"title":"An etwas verlieren — to lose (in measure/degree)","pattern":"an + dative + verlieren (to lose in terms of, to decline in)","explanation":"Verlieren an + dative = to lose in terms of, decline in (measure/attribute). An Bedeutung verlieren = to lose significance. An Zustimmung verlieren = to lose approval. An Wert verlieren = to lose value. Note: verlieren + accusative (object) = to lose (a thing): Ich habe meinen Schlüssel verloren = I lost my key. Verlieren an + dative = gradual decline in an attribute. Die Volksparteien verlieren an Zustimmung = The parties are declining in support.","examples":[{"sentence":"Das Euro hat in letzter Zeit an Wert verloren.","translation":"The euro has lost value recently."},{"sentence":"Das Thema hat an Relevanz verloren.","translation":"The topic has lost relevance."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Mehrheit'' means?","options":["majority","most","plurality","greater part"],"correctAnswer":"majority"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The traditional catch-all parties have lost approval in recent decades.","options":["Die traditionellen Volksparteien haben in den letzten Jahrzehnten an Zustimmung verloren.","Volksparteien sind nicht mehr beliebt.","Die Parteien haben weniger Stimmen.","Große Parteien verlieren Wähler."],"correctAnswer":"Die traditionellen Volksparteien haben in den letzten Jahrzehnten an Zustimmung verloren."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Thema hat an Relevanz ___.","options":["verloren","verliert","verloren gegangen","verlorengeht"],"correctAnswer":"verloren"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The euro has lost value recently","wordBankItems":["Das","Euro","hat","in","letzter","Zeit","an","Wert","verloren","."],"correctAnswer":"Das Euro hat in letzter Zeit an Wert verloren ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Koalition'' means?","options":["coalition","alliance","partnership","government"],"correctAnswer":"coalition"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000014d',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss the German federal government","Use Bundesregierung vocabulary","Talk about German government structure"],"explanation":{"intro":"Federal government vocabulary covers the structure of German government — Bundestag, Bundesrat, and executive.","culturalNote":"Germany''s Bundesregierung (federal government) consists of Bundeskanzler (Federal Chancellor) and Bundesminister (Federal Ministers). The Kanzlerin or Kanzler heads the government. The Bundesrat represents the 16 Länder (states). The Bundespräsident (Federal President) is the ceremonial head of state. Weißes Haus = White House; Kanzleramt = Chancellery (in Berlin)."},"examples":[{"german":"Der Bundeskanzler wird vom Bundestag gewählt und leitet die Bundesregierung.","english":"The Federal Chancellor is elected by the Bundestag and leads the federal government."},{"german":"Der Bundesrat hat bei bestimmten Gesetzen ein Vetorecht.","english":"The Federal Council has a veto right on certain laws."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss the structure of the German federal government and its institutions."}}',
'{"items":[{"word":"der Bundeskanzler","translation":"Federal Chancellor","pronunciation":"dayr BOON-des-kant-sler","example":"Der Bundeskanzler."},{"word":"leiten","translation":"to lead/head/manage","pronunciation":"LY-ten","example":"Die Regierung leiten."},{"word":"das Vetorecht","translation":"veto right","pronunciation":"dahs VAY-toh-rekht","example":"Ein Vetorecht haben."},{"word":"bestimmt","translation":"certain/specific","pronunciation":"beh-SHTIMMT","example":"Bestimmte Gesetze."},{"word":"das Kanzleramt","translation":"Chancellery","pronunciation":"dahs KANT-sler-amt","example":"Das Kanzleramt Berlin."},{"word":"der Bundesrat","translation":"Federal Council","pronunciation":"dayr BOON-des-raht","example":"Der Bundesrat."}]}',
'{"title":"Leiten — to lead/manage/head","pattern":"etwas leiten (to lead, head, manage — an organisation, meeting, department)","explanation":"Leiten = to lead, head, manage (an organisation or process). Er leitet das Unternehmen = He heads the company. Die Sitzung leiten = to chair/run the meeting. Sich leiten lassen von = to be guided by (abstract). Related: die Leitung (management, direction), der Leiter/die Leiterin (head/director), leitend (executive, managerial — leitende Angestellte = executive employees). Compare: führen (to lead — more person-focused leadership), managen (to manage — anglicism used colloquially).","examples":[{"sentence":"Sie leitet seit fünf Jahren die Abteilung.","translation":"She has been heading the department for five years."},{"sentence":"Wer leitet die Konferenz?","translation":"Who is chairing the conference?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Vetorecht'' means?","options":["veto right","right of refusal","blocking right","rejection right"],"correctAnswer":"veto right"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The Federal Chancellor is elected by the Bundestag and leads the federal government.","options":["Der Bundeskanzler wird vom Bundestag gewählt und leitet die Bundesregierung.","Der Kanzler ist der Chef der Regierung.","Der Bundestag wählt die Regierung.","Bundeskanzler und Bundesregierung."],"correctAnswer":"Der Bundeskanzler wird vom Bundestag gewählt und leitet die Bundesregierung."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Sie leitet seit fünf Jahren die ___.","options":["Abteilung","Abteilungen","Abteilungsleitung","Leitung"],"correctAnswer":"Abteilung"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Who is chairing the conference?","wordBankItems":["Wer","leitet","die","Konferenz","?"],"correctAnswer":"Wer leitet die Konferenz ?"},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Bundesrat'' means?","options":["Federal Council","Federal Chamber","State Council","Upper House"],"correctAnswer":"Federal Council"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000014e',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss German federalism","Use Föderalismus vocabulary","Talk about the 16 Länder"],"explanation":{"intro":"Federalism vocabulary at B1 covers Germany''s 16-state federal system and division of powers.","culturalNote":"Germany''s Föderalismus (federalism) divides power between Bund (federal) and Länder (states). Each Land has its own Landtag (parliament) and Landesregierung (state government). Zuständigkeiten (competencies) are split: foreign policy is Bundessache, education is Ländersache. The Länderfinanzausgleich (fiscal equalisation between states) is politically controversial."},"examples":[{"german":"In Deutschland ist Bildungspolitik Ländersache — jedes Bundesland entscheidet selbst.","english":"In Germany education policy is a state matter — each federal state decides for itself."},{"german":"Der Föderalismus stärkt die regionale Selbstverwaltung und Vielfalt.","english":"Federalism strengthens regional self-governance and diversity."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss German federalism, the division of powers, and the 16 Länder."}}',
'{"items":[{"word":"der Föderalismus","translation":"federalism","pronunciation":"dayr fö-deh-rah-LIS-moos","example":"Föderalismus."},{"word":"die Zuständigkeit","translation":"competency/jurisdiction","pronunciation":"dee TSOO-shten-dikh-kyt","example":"Zuständigkeit klären."},{"word":"die Selbstverwaltung","translation":"self-governance","pronunciation":"dee ZELPST-fer-val-toong","example":"Regionale Selbstverwaltung."},{"word":"die Vielfalt","translation":"diversity/variety","pronunciation":"dee FEEL-falt","example":"Kulturelle Vielfalt."},{"word":"das Bundesland","translation":"federal state","pronunciation":"dahs BOON-des-lant","example":"Ein Bundesland."},{"word":"die Landesregierung","translation":"state government","pronunciation":"dee LAN-des-reh-gee-roong","example":"Die Landesregierung."}]}',
'{"title":"Ländersache vs. Bundessache — state vs. federal matter","pattern":"etwas ist Ländersache / Bundessache / Privatsache (X is a matter for the states / federal / private)","explanation":"The -sache suffix creates compound nouns meaning ''a matter of X''. Ländersache = a matter for the states (Länder), Bundessache = a federal matter, Privatsache = a private matter, Chefsache = a matter for the boss. Das ist Privatsache = That is a private matter. Das ist Chefsache = That is the boss''s call. Very productive suffix in German — common in political, legal, and everyday language.","examples":[{"sentence":"Ob ich das tue, ist Privatsache.","translation":"Whether I do that is a private matter."},{"sentence":"Außenpolitik ist in Deutschland Bundessache.","translation":"Foreign policy in Germany is a federal matter."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Selbstverwaltung'' means?","options":["self-governance","self-administration","autonomy","independent management"],"correctAnswer":"self-governance"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In Germany education policy is a state matter — each federal state decides for itself.","options":["In Deutschland ist Bildungspolitik Ländersache — jedes Bundesland entscheidet selbst.","Bildung ist in jedem Bundesland anders.","Die Länder entscheiden über Bildung.","Jedes Land hat sein eigenes Schulsystem."],"correctAnswer":"In Deutschland ist Bildungspolitik Ländersache — jedes Bundesland entscheidet selbst."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Außenpolitik ist in Deutschland ___.","options":["Bundessache","Ländersache","Staatssache","Regierungssache"],"correctAnswer":"Bundessache"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Whether I do that is a private matter","wordBankItems":["Ob","ich","das","tue",",","ist","Privatsache","."],"correctAnswer":"Ob ich das tue , ist Privatsache ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Vielfalt'' means?","options":["diversity/variety","plurality","richness","breadth"],"correctAnswer":"diversity/variety"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000014f',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss the European Union","Use EU vocabulary","Talk about European integration"],"explanation":{"intro":"EU vocabulary at B1 covers European institutions, integration, and Germany''s role in the EU.","culturalNote":"Germany is one of the founding members and the largest economy of the EU. The Europäisches Parlament (European Parliament) sits in Strasbourg and Brussels. Key EU institutions: Europäische Kommission (Commission), Rat der EU (Council), EuGH (European Court of Justice). The Euro is Germany''s currency. Brexit (UK exit from EU in 2020) was widely covered in German media."},"examples":[{"german":"Deutschland und Frankreich gelten als Motor der europäischen Integration.","english":"Germany and France are regarded as the engine of European integration."},{"german":"Das Europäische Parlament wird direkt von den Bürgerinnen und Bürgern der EU gewählt.","english":"The European Parliament is elected directly by the citizens of the EU."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss the EU, European integration, and Germany''s role in Europe."}}',
'{"items":[{"word":"gelten als","translation":"to be regarded as","pronunciation":"GEL-ten als","example":"Als Experte gelten."},{"word":"der Motor","translation":"engine/driving force","pronunciation":"dayr MOH-tor","example":"Motor der Integration."},{"word":"die Integration","translation":"integration","pronunciation":"dee in-teh-grah-tsee-OHN","example":"Europäische Integration."},{"word":"direkt gewählt","translation":"directly elected","pronunciation":"dee-REKT geh-VÄYLT","example":"Direkt gewählt werden."},{"word":"die Kommission","translation":"commission","pronunciation":"dee ko-mis-see-OHN","example":"Europäische Kommission."},{"word":"das Mitgliedsland","translation":"member state","pronunciation":"dahs MIT-gleets-lant","example":"Mitgliedsländer der EU."}]}',
'{"title":"Gelten als — to be regarded/considered as","pattern":"jemand/etwas gilt als + nominative (to be regarded as, be considered — no article needed)","explanation":"Gelten als + nominative = to be regarded as, be considered to be. Deutschland gilt als wirtschaftliche Führungsmacht = Germany is regarded as an economic leader. Note: no article after als when the identity is non-specific (als Motor, als Experte). Gelten für + accusative = to apply to: Das gilt für alle = That applies to everyone. Related: als...angesehen werden (to be seen as), als...betrachtet werden (formal passive).","examples":[{"sentence":"Er gilt als einer der besten Ärzte in der Region.","translation":"He is regarded as one of the best doctors in the region."},{"sentence":"Das gilt als grobe Unhöflichkeit.","translation":"That is regarded as gross rudeness."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Mitgliedsland'' means?","options":["member state","member country","partner state","affiliated country"],"correctAnswer":"member state"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Germany and France are regarded as the engine of European integration.","options":["Deutschland und Frankreich gelten als Motor der europäischen Integration.","Deutschland und Frankreich führen Europa.","Europa integriert sich dank Deutschland und Frankreich.","Der Motor der EU sind große Länder."],"correctAnswer":"Deutschland und Frankreich gelten als Motor der europäischen Integration."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er gilt als einer der besten Ärzte in der ___.","options":["Region","Regionen","Gegend","Stadtregion"],"correctAnswer":"Region"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That is regarded as gross rudeness","wordBankItems":["Das","gilt","als","grobe","Unhöflichkeit","."],"correctAnswer":"Das gilt als grobe Unhöflichkeit ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Gelten als'' is followed by which case?","options":["nominative","accusative","dative","genitive"],"correctAnswer":"nominative"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000150',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss foreign policy","Use Außenpolitik vocabulary","Talk about diplomacy and international relations"],"explanation":{"intro":"Foreign policy vocabulary at B1 covers diplomacy, international relations, and Germany''s foreign policy role.","culturalNote":"Germany''s Außenpolitik is shaped by its post-WWII commitment to multilateralism and restraint — Nie wieder Krieg (never again war). Germany is a NATO member and committed to the UN. The concept of Bündnissolidarität (alliance solidarity) is important. Wirtschaftsdiplomatie (economic diplomacy) is a major tool. The Auswärtiges Amt (Foreign Office) is in Berlin."},"examples":[{"german":"Deutschland setzt in der Außenpolitik auf Multilateralismus und Diplomatie.","english":"Germany relies on multilateralism and diplomacy in foreign policy."},{"german":"Die Außenministerin vertritt die Interessen Deutschlands auf internationalem Parkett.","english":"The Foreign Minister represents Germany''s interests on the international stage."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss foreign policy, diplomacy, and Germany''s international role in German."}}',
'{"items":[{"word":"setzen auf","translation":"to rely on/bet on","pronunciation":"ZET-sen owf","example":"Auf Diplomatie setzen."},{"word":"der Multilateralismus","translation":"multilateralism","pronunciation":"dayr mool-tee-lah-teh-rah-LIS-moos","example":"Multilateralismus."},{"word":"vertreten","translation":"to represent","pronunciation":"fer-TRAY-ten","example":"Interessen vertreten."},{"word":"das Parkett","translation":"stage/parquet (fig: arena)","pronunciation":"dahs par-KET","example":"Auf internationalem Parkett."},{"word":"die Diplomatie","translation":"diplomacy","pronunciation":"dee dee-ploh-mah-TEE","example":"Diplomatie einsetzen."},{"word":"das Bündnis","translation":"alliance/pact","pronunciation":"dahs BÜND-nis","example":"Ein Bündnis eingehen."}]}',
'{"title":"Auf etwas setzen — to rely on, bank on","pattern":"auf etwas setzen (to rely on, bet on, bank on — commit to a strategy)","explanation":"Setzen auf + accusative = to rely on, bank on, put one''s faith in (a strategy or approach). Deutschland setzt auf Diplomatie = Germany banks on diplomacy. Also common: auf Qualität setzen (to focus on quality — corporate strategy), auf Erneuerbare Energien setzen (to commit to renewables). Compare: sich verlassen auf (to depend on — personal reliance), vertrauen auf (to trust in), sich stützen auf (to be based on — analysis).","examples":[{"sentence":"Das Unternehmen setzt auf Innovation als Wachstumsstrategie.","translation":"The company banks on innovation as its growth strategy."},{"sentence":"Sie setzt auf Dialog statt auf Konfrontation.","translation":"She banks on dialogue rather than confrontation."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Parkett'' in political context means?","options":["international stage/arena","floor","stage","platform"],"correctAnswer":"international stage/arena"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Germany relies on multilateralism and diplomacy in foreign policy.","options":["Deutschland setzt in der Außenpolitik auf Multilateralismus und Diplomatie.","Deutschland ist multilateral.","Außenpolitik braucht Diplomatie.","Deutschland bevorzugt Dialog."],"correctAnswer":"Deutschland setzt in der Außenpolitik auf Multilateralismus und Diplomatie."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Unternehmen setzt auf Innovation als ___.","options":["Wachstumsstrategie","Wachstum","Strategie","Innovationsstrategie"],"correctAnswer":"Wachstumsstrategie"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She banks on dialogue rather than confrontation","wordBankItems":["Sie","setzt","auf","Dialog","statt","auf","Konfrontation","."],"correctAnswer":"Sie setzt auf Dialog statt auf Konfrontation ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Bündnis'' means?","options":["alliance/pact","union","coalition","federation"],"correctAnswer":"alliance/pact"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000151',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss international relations","Use Außenpolitik 2 vocabulary","Talk about global politics"],"explanation":{"intro":"Advanced international relations vocabulary at B1 covers global governance, treaties, and political conflicts.","culturalNote":"Germany participates in key international bodies: UN, NATO, G7, G20, OSCE. The Außenpolitik is based on the Grundgesetz principle of peacekeeping. Germany''s role in the Ukraine conflict (Zeitenwende speech by Scholz in 2022 — announcing a turning point in German foreign policy) marked a historic shift."},"examples":[{"german":"Die Zeitenwende in der deutschen Außenpolitik bedeutet mehr Investitionen in die Verteidigung.","english":"The turning point in German foreign policy means more investment in defence."},{"german":"Deutschland unterstützt internationales Recht und die Charta der Vereinten Nationen.","english":"Germany supports international law and the Charter of the United Nations."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss international relations, global governance, and German foreign policy shifts in German."}}',
'{"items":[{"word":"die Zeitenwende","translation":"turning point in time","pronunciation":"dee TSY-ten-ven-deh","example":"Die Zeitenwende."},{"word":"die Verteidigung","translation":"defence","pronunciation":"dee fer-TY-dee-goong","example":"In die Verteidigung investieren."},{"word":"unterstützen","translation":"to support","pronunciation":"OON-ter-shtüt-sen","example":"International unterstützen."},{"word":"die Charta","translation":"charter","pronunciation":"dee KHAR-tah","example":"UN-Charta."},{"word":"die Vereinten Nationen","translation":"United Nations","pronunciation":"dee fer-YNT-en nah-TSYOH-nen","example":"Vereinte Nationen."},{"word":"multilateral","translation":"multilateral","pronunciation":"mool-tee-lah-teh-RAHL","example":"Multilateral handeln."}]}',
'{"title":"Bedeuten — to mean/signify","pattern":"etwas bedeutet etwas (something means/signifies something — consequence or meaning)","explanation":"Bedeuten = to mean, signify, entail. Die Zeitenwende bedeutet mehr Investitionen = The turning point means more investment. Common in political/analytical language to explain consequences. Nichts bedeuten = to mean nothing. Das hat nichts zu bedeuten = That doesn''t mean anything. Das bedeutet, dass + clause: Das bedeutet, dass sich viel ändert = That means that much will change. Die Bedeutung (meaning, significance). Bedeutend (significant, notable).","examples":[{"sentence":"Das bedeutet nicht, dass wir aufgeben.","translation":"That does not mean that we give up."},{"sentence":"Die Einigung bedeutet einen Durchbruch.","translation":"The agreement means a breakthrough."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Zeitenwende'' means?","options":["turning point in time","era change","political shift","historic moment"],"correctAnswer":"turning point in time"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Germany supports international law and the Charter of the United Nations.","options":["Deutschland unterstützt internationales Recht und die Charta der Vereinten Nationen.","Deutschland respektiert die UN.","Internationales Recht gilt für Deutschland.","Deutschland folgt den UN-Regeln."],"correctAnswer":"Deutschland unterstützt internationales Recht und die Charta der Vereinten Nationen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Einigung bedeutet einen ___.","options":["Durchbruch","Fortschritt","Erfolg","Meilenstein"],"correctAnswer":"Durchbruch"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That does not mean that we give up","wordBankItems":["Das","bedeutet","nicht",",","dass","wir","aufgeben","."],"correctAnswer":"Das bedeutet nicht , dass wir aufgeben ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Verteidigung'' means?","options":["defence","protection","security","armed forces"],"correctAnswer":"defence"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000152',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss peace and security","Use Sicherheitspolitik vocabulary","Talk about conflict and peace-building"],"explanation":{"intro":"Peace and security vocabulary at B1 covers conflict, peace-building, and Germany''s security policy.","culturalNote":"After WWII, Germany''s Sicherheitspolitik (security policy) emphasised diplomacy over military power — Wandel durch Handel (change through trade) was the guiding principle. The Bundeswehr (German armed forces) is parliament-controlled (Parlamentsheer). Germany only joined NATO military operations gradually. The Russia-Ukraine war (2022) triggered the Zeitenwende and increased Bundeswehr funding."},"examples":[{"german":"Sicherheit und Frieden sind keine Selbstverständlichkeiten, sondern müssen täglich bewahrt werden.","english":"Security and peace are not foregone conclusions, but must be preserved daily."},{"german":"Die Bundeswehr kann nur mit Zustimmung des Bundestages ins Ausland entsandt werden.","english":"The Bundeswehr can only be deployed abroad with the approval of the Bundestag."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss peace, security policy, and the Bundeswehr in German."}}',
'{"items":[{"word":"die Selbstverständlichkeit","translation":"foregone conclusion/taken-for-granted thing","pronunciation":"dee ZELPST-fer-shtent-likh-kyt","example":"Keine Selbstverständlichkeit."},{"word":"bewahren","translation":"to preserve/safeguard","pronunciation":"beh-VAH-ren","example":"Frieden bewahren."},{"word":"entsenden","translation":"to deploy/dispatch","pronunciation":"ent-ZEN-den","example":"Truppen entsenden."},{"word":"die Zustimmung","translation":"approval/consent","pronunciation":"dee TSOO-shtim-oong","example":"Zustimmung einholen."},{"word":"die Bundeswehr","translation":"German armed forces","pronunciation":"dee BOON-des-vair","example":"Die Bundeswehr."},{"word":"das Abkommen","translation":"agreement/treaty","pronunciation":"dahs AP-kom-en","example":"Ein Friedensabkommen."}]}',
'{"title":"Keine Selbstverständlichkeit — not taken for granted","pattern":"kein + abstract noun + -keit/-heit (negating a taken-for-granted abstract quality)","explanation":"Selbstverständlichkeit = something taken for granted (abstract noun from selbstverständlich). Keine Selbstverständlichkeit = not a foregone conclusion, not to be taken for granted. German forms many abstract nouns with -keit/-heit: Selbstverständlichkeit, Möglichkeit, Fähigkeit, Gelegenheit. Keine modifies these nouns in predicate: Das ist keine Kleinigkeit = That is not a trivial matter. These abstractions are common in formal/political register.","examples":[{"sentence":"Demokratie ist keine Selbstverständlichkeit.","translation":"Democracy is not to be taken for granted."},{"sentence":"Das war keine Kleinigkeit — es hat uns viel Arbeit gekostet.","translation":"That was no small matter — it cost us a lot of work."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Bewahren'' means?","options":["to preserve/safeguard","to protect","to maintain","to keep"],"correctAnswer":"to preserve/safeguard"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Security and peace are not foregone conclusions, but must be preserved daily.","options":["Sicherheit und Frieden sind keine Selbstverständlichkeiten, sondern müssen täglich bewahrt werden.","Frieden ist wichtig.","Sicherheit muss man immer im Auge behalten.","Man darf Frieden nicht vergessen."],"correctAnswer":"Sicherheit und Frieden sind keine Selbstverständlichkeiten, sondern müssen täglich bewahrt werden."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Demokratie ist keine ___.","options":["Selbstverständlichkeit","Selbstverständliches","Selbstverständnis","Selbstverständlich"],"correctAnswer":"Selbstverständlichkeit"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That was no small matter — it cost us a lot of work","wordBankItems":["Das","war","keine","Kleinigkeit","—","es","hat","uns","viel","Arbeit","gekostet","."],"correctAnswer":"Das war keine Kleinigkeit — es hat uns viel Arbeit gekostet ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Entsenden'' means?","options":["to deploy/dispatch","to send out","to export","to transfer"],"correctAnswer":"to deploy/dispatch"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000153',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss freedom of expression","Use Meinungsfreiheit vocabulary","Talk about free speech and its limits"],"explanation":{"intro":"Freedom of expression vocabulary at B1 covers the right to free speech, its legal limits, and related debates.","culturalNote":"Meinungsfreiheit (freedom of opinion) is guaranteed by Article 5 of the Grundgesetz. However it has limits: Volksverhetzung (incitement to hatred), Holocaust denial, and Nazi symbols are prohibited. The Beleidigungsrecht (defamation law) is strict. Social media companies face legal obligations to remove illegal content (NetzDG). Germany balances Meinungsfreiheit with Menschenwürde (human dignity)."},"examples":[{"german":"Meinungsfreiheit ist ein Grundrecht, das jedoch nicht grenzenlos ist.","english":"Freedom of opinion is a basic right, but one that is not unlimited."},{"german":"Volksverhetzung und das Verbreiten von Hassrede sind in Deutschland strafbar.","english":"Incitement to hatred and spreading hate speech are punishable by law in Germany."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss freedom of expression, its legal limits, and related debates in German."}}',
'{"items":[{"word":"grenzenlos","translation":"unlimited/boundless","pronunciation":"GREN-tsen-lohs","example":"Nicht grenzenlos."},{"word":"das Grundrecht","translation":"basic/fundamental right","pronunciation":"dahs GROOND-rekht","example":"Ein Grundrecht."},{"word":"strafbar","translation":"punishable","pronunciation":"SHTRAHF-bar","example":"Strafbar sein."},{"word":"die Volksverhetzung","translation":"incitement to hatred","pronunciation":"dee FOLKS-fer-het-soong","example":"Volksverhetzung."},{"word":"die Hassrede","translation":"hate speech","pronunciation":"dee HAS-ray-deh","example":"Hassrede verbreiten."},{"word":"verbreiten","translation":"to spread/disseminate","pronunciation":"fer-BRY-ten","example":"Informationen verbreiten."}]}',
'{"title":"Ein Recht, das/das jedoch — a right that (relative clause qualification)","pattern":"noun + das/der/die + jedoch + negative clause (qualifying a right/principle with a limitation)","explanation":"Relative clauses after rights/principles: das Recht auf X, das jedoch begrenzt ist = the right to X, which however is limited. Jedoch (however) within a relative clause adds concession. The relative clause directly qualifies the noun. Common in legal and political German: Ein Recht, das nicht grenzenlos gilt = a right that does not apply without limit. Jedoch (however) vs. aber (but): jedoch is more formal, often mid-sentence.","examples":[{"sentence":"Es gibt eine Freiheit, die jedoch Verantwortung erfordert.","translation":"There is a freedom that, however, requires responsibility."},{"sentence":"Das Gesetz, das jedoch umstritten ist, tritt nächste Woche in Kraft.","translation":"The law, which however is contested, comes into force next week."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Strafbar'' means?","options":["punishable","criminal","illegal","forbidden"],"correctAnswer":"punishable"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Freedom of opinion is a basic right, but one that is not unlimited.","options":["Meinungsfreiheit ist ein Grundrecht, das jedoch nicht grenzenlos ist.","Meinungsfreiheit hat Grenzen.","Grundrechte sind wichtig, aber begrenzt.","Es gibt Grenzen der Meinungsfreiheit."],"correctAnswer":"Meinungsfreiheit ist ein Grundrecht, das jedoch nicht grenzenlos ist."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Es gibt eine Freiheit, die jedoch Verantwortung ___.","options":["erfordert","erfordern","erforderende","erfordert werden"],"correctAnswer":"erfordert"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The law which however is contested comes into force next week","wordBankItems":["Das","Gesetz",",","das","jedoch","umstritten","ist",",","tritt","nächste","Woche","in","Kraft","."],"correctAnswer":"Das Gesetz , das jedoch umstritten ist , tritt nächste Woche in Kraft ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Volksverhetzung'' means?","options":["incitement to hatred","hate speech","defamation","propaganda"],"correctAnswer":"incitement to hatred"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000154',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss press freedom","Use Pressefreiheit vocabulary","Talk about journalism and media independence"],"explanation":{"intro":"Press freedom vocabulary at B1 covers journalistic independence, media ownership, and freedom of the press.","culturalNote":"Germany ranks high globally on press freedom (RSF index: typically 10-15). The Pressefreiheit is guaranteed by Article 5 GG. Public broadcasting (ARD, ZDF) is structurally independent from government. Verlegerverbände (publisher associations) and Journalistenverbände (journalist associations) advocate for press freedom. Investigative journalism (Investigativjournalismus) is well-funded at outlets like Der Spiegel, Zeit, SZ."},"examples":[{"german":"Eine freie Presse ist eine Grundvoraussetzung für eine funktionierende Demokratie.","english":"A free press is a fundamental prerequisite for a functioning democracy."},{"german":"Journalisten haben das Recht, ihre Quellen zu schützen.","english":"Journalists have the right to protect their sources."}],"rewards":{"xp":140,"coins":70},"metadata":{"estimatedMinutes":18,"canDo":"I can discuss press freedom, journalism, and media independence in German."}}',
'{"items":[{"word":"die Grundvoraussetzung","translation":"fundamental prerequisite","pronunciation":"dee GROOND-for-ows-zet-soong","example":"Grundvoraussetzung."},{"word":"funktionierend","translation":"functioning","pronunciation":"foonk-tsyoh-NEER-end","example":"Funktionierende Demokratie."},{"word":"die Quelle","translation":"source","pronunciation":"dee KVEL-eh","example":"Quellen schützen."},{"word":"investigativ","translation":"investigative","pronunciation":"in-ves-tee-gah-TEEF","example":"Investigativer Journalismus."},{"word":"unabhängig","translation":"independent","pronunciation":"OON-ap-heng-ikh","example":"Unabhängige Presse."},{"word":"öffentlich-rechtlich","translation":"public-law (broadcasting)","pronunciation":"ÖF-ent-likh REKHT-likh","example":"Öffentlich-rechtliches Fernsehen."}]}',
'{"title":"Eine Grundvoraussetzung für — a fundamental prerequisite for","pattern":"eine Grundvoraussetzung für + accusative (a fundamental prerequisite/precondition for)","explanation":"Grundvoraussetzung = fundamental prerequisite (Grund + Voraussetzung = ground + requirement). Eine Grundvoraussetzung für die Demokratie = a fundamental prerequisite for democracy. Compare: Voraussetzung (precondition — less emphatic), Bedingung (condition — often contractual), Anforderung (requirement — specification). These form a register scale from formal to very formal. Die Grundvoraussetzungen erfüllen = to meet the fundamental requirements.","examples":[{"sentence":"Vertrauen ist eine Grundvoraussetzung für jede gute Zusammenarbeit.","translation":"Trust is a fundamental prerequisite for any good collaboration."},{"sentence":"Gute Sprachkenntnisse sind eine Grundvoraussetzung für diesen Job.","translation":"Good language skills are a fundamental prerequisite for this job."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Unabhängig'' means?","options":["independent","free","autonomous","sovereign"],"correctAnswer":"independent"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"A free press is a fundamental prerequisite for a functioning democracy.","options":["Eine freie Presse ist eine Grundvoraussetzung für eine funktionierende Demokratie.","Pressefreiheit ist wichtig.","Demokratie braucht freie Medien.","Eine freie Presse schützt die Demokratie."],"correctAnswer":"Eine freie Presse ist eine Grundvoraussetzung für eine funktionierende Demokratie."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Vertrauen ist eine Grundvoraussetzung für jede gute ___.","options":["Zusammenarbeit","Kooperation","Arbeit","Partnerschaft"],"correctAnswer":"Zusammenarbeit"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Good language skills are a fundamental prerequisite for this job","wordBankItems":["Gute","Sprachkenntnisse","sind","eine","Grundvoraussetzung","für","diesen","Job","."],"correctAnswer":"Gute Sprachkenntnisse sind eine Grundvoraussetzung für diesen Job ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Öffentlich-rechtlich'' describes which type of broadcaster?","options":["public-law/public service","state-owned","independent","commercial"],"correctAnswer":"public-law/public service"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-000000000141','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l321',321,'Digitalisierung','Digitalisation vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000142','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l322',322,'Künstliche Intelligenz','AI vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000143','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l323',323,'Datenschutz 2','Advanced data protection','PUBLISHED'),
('dd000000-0000-0000-0000-000000000144','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l324',324,'Soziale Medien 2','Advanced social media','PUBLISHED'),
('dd000000-0000-0000-0000-000000000145','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l325',325,'Fake News','Fake news and media literacy','PUBLISHED'),
('dd000000-0000-0000-0000-000000000146','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l326',326,'Gaming','Gaming culture vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000147','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l327',327,'E-Commerce','Online shopping vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000148','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l328',328,'Homeoffice','Remote work vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000149','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l329',329,'Bildung digital','Digital education vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000014a','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l330',330,'Demokratie','Democracy vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000014b','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l331',331,'Wahlen','Elections vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000014c','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l332',332,'Parteien','Political parties vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000014d','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l333',333,'Bundesregierung','Federal government vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000014e','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l334',334,'Föderalismus','Federalism vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000014f','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l335',335,'Europäische Union','EU vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000150','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l336',336,'Außenpolitik','Foreign policy vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000151','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l337',337,'Internationale Beziehungen','International relations vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000152','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l338',338,'Frieden und Sicherheit','Peace and security vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000153','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l339',339,'Meinungsfreiheit','Freedom of expression vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000154','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000003',NULL,'de-b1-u03-l340',340,'Pressefreiheit','Press freedom vocabulary','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000141' WHERE stable_ref = 'de-b1-u03-l321' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000142' WHERE stable_ref = 'de-b1-u03-l322' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000143' WHERE stable_ref = 'de-b1-u03-l323' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000144' WHERE stable_ref = 'de-b1-u03-l324' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000145' WHERE stable_ref = 'de-b1-u03-l325' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000146' WHERE stable_ref = 'de-b1-u03-l326' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000147' WHERE stable_ref = 'de-b1-u03-l327' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000148' WHERE stable_ref = 'de-b1-u03-l328' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000149' WHERE stable_ref = 'de-b1-u03-l329' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000014a' WHERE stable_ref = 'de-b1-u03-l330' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000014b' WHERE stable_ref = 'de-b1-u03-l331' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000014c' WHERE stable_ref = 'de-b1-u03-l332' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000014d' WHERE stable_ref = 'de-b1-u03-l333' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000014e' WHERE stable_ref = 'de-b1-u03-l334' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000014f' WHERE stable_ref = 'de-b1-u03-l335' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000150' WHERE stable_ref = 'de-b1-u03-l336' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000151' WHERE stable_ref = 'de-b1-u03-l337' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000152' WHERE stable_ref = 'de-b1-u03-l338' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000153' WHERE stable_ref = 'de-b1-u03-l339' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000154' WHERE stable_ref = 'de-b1-u03-l340' AND lesson_id IS NULL;
