-- V70: German B2 lessons 361-380 (B2 batch 1)
-- Level: B2 (10000000-0000-0000-0000-000000000004), unit de-b2-u04
-- Hex: 361=0x169, 380=0x17c

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-000000000169','de-b2-l361','Konjunktiv II Vertiefung B2 - KonjII B2','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000016a','de-b2-l362','Passivkonstruktionen B2 - Passive B2','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000016b','de-b2-l363','Nominalstil - Nominal Style','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000016c','de-b2-l364','Konzessivsätze - Concessive Clauses','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000016d','de-b2-l365','Konditionalsätze B2 - Conditionals B2','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000016e','de-b2-l366','Modalpartikeln - Modal Particles','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000016f','de-b2-l367','Präpositionen mit Genitiv - Genitive Preps','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000170','de-b2-l368','Erweiterte Partizipalkonstruktionen - Participles','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000171','de-b2-l369','Kausalsätze B2 - Causal Clauses B2','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000172','de-b2-l370','Finalsätze - Final Clauses','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000173','de-b2-l371','Konsekutivsätze - Consecutive Clauses','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000174','de-b2-l372','Adversativsätze - Adversative Clauses','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000175','de-b2-l373','Relativsätze B2 - Relative Clauses B2','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000176','de-b2-l374','Wortstellung B2 - Word Order B2','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000177','de-b2-l375','Infinitivgruppen B2 - Infinitive Groups B2','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000178','de-b2-l376','Forschung und Wissenschaft - Research','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000179','de-b2-l377','Akademisches Schreiben - Academic Writing','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000017a','de-b2-l378','Wirtschaft und Finanzen - Economics Finance','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000017b','de-b2-l379','Globalisierung - Globalisation','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000017c','de-b2-l380','Wirtschaftspolitik - Economic Policy','language','de','B2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000169',1,'APPROVED','PUBLISHED',
'{"objectives":["Master Konjunktiv II at B2","Use irrealis and polite forms confidently","Distinguish würde + Infinitiv from synthetic Konj. II"],"explanation":{"intro":"At B2, Konjunktiv II is used confidently for nuanced hypothetical, polite, and speculative discourse.","culturalNote":"B2 German speakers use Konjunktiv II naturally and fluidly — it marks speaker attitude, politeness (Könnten Sie...?), and sophisticated hypotheticals. The synthetic Konjunktiv II (wäre, hätte, könnte) is preferred in writing and formal speech; würde + Infinitiv is more colloquial. Mixing both is normal."},"examples":[{"german":"Wenn ich mehr Zeit hätte, würde ich ein Buch schreiben — aber ich habe sie nicht.","english":"If I had more time, I would write a book — but I don''t have it."},{"german":"Es wäre schön, wenn du kommen könntest — aber ich verstehe, falls es nicht klappt.","english":"It would be nice if you could come — but I understand if it doesn''t work out."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use Konjunktiv II fluently for hypotheticals, polite requests, and nuanced expression at B2."}}',
'{"items":[{"word":"der Irrealis","translation":"irrealis (unreal condition)","pronunciation":"dayr ir-reh-AH-lis","example":"Im Irrealis."},{"word":"das Hypothetische","translation":"the hypothetical","pronunciation":"dahs hü-poh-TEH-tee-sheh","example":"Hypothetisch formulieren."},{"word":"die Distanz","translation":"distance (linguistic)","pronunciation":"dee dis-TANTS","example":"Sprachliche Distanz."},{"word":"vorausgesetzt","translation":"assuming/given that","pronunciation":"for-OWS-geh-zetst","example":"Vorausgesetzt, dass."},{"word":"gelten","translation":"to apply/hold true","pronunciation":"GEL-ten","example":"Das gilt auch hier."},{"word":"nuanciert","translation":"nuanced","pronunciation":"noo-an-SEERT","example":"Nuanciert ausdrücken."}]}',
'{"title":"Synthetic vs. analytical Konjunktiv II","pattern":"Synthetic: wäre/hätte/könnte/müsste vs. analytical: würde + Infinitiv — register and naturalness","explanation":"B2 distinction: Synthetic Konjunktiv II = wäre, hätte, könnte, dürfte, müsste, sollte, wollte — preferred in formal and literary German. Analytical = würde + Infinitiv — preferred colloquially and for all other verbs. Avoid double würde: say käme statt würde kommen in formal writing, but würde kommen is fine in speech. Special note: hätte/wäre + Partizip II = past Konjunktiv II (Wenn ich gewusst hätte... = If I had known...).","examples":[{"sentence":"Wenn ich früher gewusst hätte, was ich jetzt weiß, hätte ich anders entschieden.","translation":"If I had known earlier what I know now, I would have decided differently."},{"sentence":"Es wäre sinnvoll gewesen, früher zu beginnen.","translation":"It would have been sensible to start earlier."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Which is preferred in formal writing — synthetic or analytical Konj. II?","options":["synthetic (wäre/hätte/könnte)","analytical (würde + Inf.)","both equally","neither — use indicative"],"correctAnswer":"synthetic (wäre/hätte/könnte)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"If I had more time, I would write a book — but I don''t have it.","options":["Wenn ich mehr Zeit hätte, würde ich ein Buch schreiben — aber ich habe sie nicht.","Wenn ich Zeit hätte, schreibe ich ein Buch.","Ich würde schreiben, wenn Zeit wäre.","Mit mehr Zeit könnte ich ein Buch schreiben."],"correctAnswer":"Wenn ich mehr Zeit hätte, würde ich ein Buch schreiben — aber ich habe sie nicht."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Wenn ich früher gewusst hätte, was ich jetzt weiß, ___ ich anders entschieden.","options":["hätte","würde","wäre","sollte"],"correctAnswer":"hätte"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: It would have been sensible to start earlier","wordBankItems":["Es","wäre","sinnvoll","gewesen",",","früher","zu","beginnen","."],"correctAnswer":"Es wäre sinnvoll gewesen , früher zu beginnen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Wenn ich gewusst hätte'' is which tense of Konjunktiv II?","options":["past","present","future","pluperfect"],"correctAnswer":"past"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000016a',1,'APPROVED','PUBLISHED',
'{"objectives":["Master B2 passive constructions","Use Zustandspassiv and Vorgangspassiv","Use passive with modal verbs confidently"],"explanation":{"intro":"At B2, passive constructions are used with full range of tenses, modals, and alternatives like sich lassen.","culturalNote":"German distinguishes Vorgangspassiv (process passive — werden) and Zustandspassiv (state passive — sein). Academic and official language relies heavily on passive. The passive with modal verbs (kann gemacht werden, soll verbessert werden) is especially common in regulations and formal writing."},"examples":[{"german":"Die Arbeit muss bis Freitag abgegeben werden, damit sie bewertet werden kann.","english":"The work must be submitted by Friday so that it can be assessed."},{"german":"Das Projekt ist jetzt abgeschlossen — die Ergebnisse werden nächste Woche veröffentlicht.","english":"The project is now completed — the results will be published next week."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use German passive voice confidently with modals, tenses, and Zustandspassiv at B2."}}',
'{"items":[{"word":"der Vorgangspassiv","translation":"process passive (werden)","pronunciation":"dayr FOR-gangs-pa-seev","example":"Vorgangspassiv bilden."},{"word":"der Zustandspassiv","translation":"state passive (sein)","pronunciation":"dayr TSOO-shtants-pa-seev","example":"Zustandspassiv."},{"word":"veröffentlichen","translation":"to publish","pronunciation":"fer-ÖF-ent-likh-en","example":"Ergebnisse veröffentlichen."},{"word":"bewerten","translation":"to assess/evaluate","pronunciation":"beh-VER-ten","example":"Eine Arbeit bewerten."},{"word":"abgeben","translation":"to submit/hand in","pronunciation":"AP-gay-ben","example":"Die Arbeit abgeben."},{"word":"sich lassen + Infinitiv","translation":"can be done / is doable","pronunciation":"zikh LAS-en","example":"Das lässt sich machen."}]}',
'{"title":"Sich lassen + Infinitiv — can be done (passive alternative)","pattern":"sich + lassen + Infinitiv = can be done, is possible to do (active alternative to passive)","explanation":"Sich lassen + Infinitiv = can be done, is doable (active form replacing passive). Das lässt sich erklären = That can be explained. Das lässt sich nicht vermeiden = That cannot be avoided. Active, personal subject is das/es/noun. More versatile than the passive in spoken German. Compare: Das kann erklärt werden (passive) = Das lässt sich erklären (active lassen). Lassen sich + Infinitiv takes no agent but implies feasibility.","examples":[{"sentence":"Dieses Problem lässt sich auf mehrere Weisen lösen.","translation":"This problem can be solved in several ways."},{"sentence":"Das lässt sich leider nicht ändern.","translation":"Unfortunately that cannot be changed."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Zustandspassiv'' uses which auxiliary?","options":["sein","werden","haben","lassen"],"correctAnswer":"sein"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The work must be submitted by Friday so that it can be assessed.","options":["Die Arbeit muss bis Freitag abgegeben werden, damit sie bewertet werden kann.","Die Arbeit muss Freitag fertig sein.","Bis Freitag soll die Arbeit abgegeben werden.","Die Arbeit wird Freitag abgegeben."],"correctAnswer":"Die Arbeit muss bis Freitag abgegeben werden, damit sie bewertet werden kann."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Dieses Problem lässt sich auf mehrere Weisen ___.","options":["lösen","gelöst","zu lösen","lösend"],"correctAnswer":"lösen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Unfortunately that cannot be changed","wordBankItems":["Das","lässt","sich","leider","nicht","ändern","."],"correctAnswer":"Das lässt sich leider nicht ändern ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Projekt ist abgeschlossen'' is which passive type?","options":["Zustandspassiv","Vorgangspassiv","modal passive","sein-passive"],"correctAnswer":"Zustandspassiv"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000016b',1,'APPROVED','PUBLISHED',
'{"objectives":["Master Nominalstil","Convert verbal to nominal style","Recognise nominalisation in academic German"],"explanation":{"intro":"Nominalstil (nominal style) converts verbs and adjectives into nouns for dense, formal expression — central to academic and official German.","culturalNote":"Nominalstil is characteristic of formal German — newspapers, academic texts, official documents. Verbs become nouns (analysieren → die Analyse), adjectives become nouns (wichtig → die Wichtigkeit). This makes text more compact but can be opaque. Critics call it Nominalitis (nominal disease) — a style disease."},"examples":[{"german":"Die rasche Entwicklung erneuerbarer Energien hat zur Reduzierung der CO₂-Emissionen geführt.","english":"The rapid development of renewable energies has led to a reduction in CO₂ emissions."},{"german":"Eine gründliche Analyse der Daten ermöglicht fundierte Entscheidungen.","english":"A thorough analysis of the data enables well-founded decisions."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use and recognise nominal style in formal German texts at B2."}}',
'{"items":[{"word":"die Nominalisierung","translation":"nominalisation","pronunciation":"dee no-mee-nah-lee-TSEE-roong","example":"Nominalisierung."},{"word":"fundiert","translation":"well-founded/sound","pronunciation":"foon-DEERT","example":"Fundierte Entscheidung."},{"word":"die Reduzierung","translation":"reduction","pronunciation":"dee reh-doo-TSEE-roong","example":"Reduzierung der Emissionen."},{"word":"ermöglichen","translation":"to enable/make possible","pronunciation":"er-MÖG-likh-en","example":"Fundierte Entscheidungen ermöglichen."},{"word":"die Entwicklung","translation":"development","pronunciation":"dee ent-VIK-loong","example":"Rasche Entwicklung."},{"word":"gründlich","translation":"thorough","pronunciation":"GRÜND-likh","example":"Gründliche Analyse."}]}',
'{"title":"Nominalstil — converting verbs to nouns","pattern":"Verb → Nominalisierung: analysieren → die Analyse / entwickeln → die Entwicklung","explanation":"Nominalstil converts verbal constructions to noun phrases. Common patterns: -ung (analysieren → Analyse/Analysierung, entwickeln → Entwicklung), -tion (diskutieren → Diskussion), zero-derivation (ankommen → die Ankunft), -nis (erkennen → Erkenntnis). Verbal: Wir haben die Daten analysiert und Entscheidungen getroffen = We analysed the data and made decisions. Nominal: Die Analyse der Daten ermöglichte die Entscheidungsfindung. Both are correct; nominal is more formal.","examples":[{"sentence":"Die Verbesserung der Situation erfordert eine enge Zusammenarbeit.","translation":"The improvement of the situation requires close cooperation."},{"sentence":"Nach reiflicher Überlegung haben wir uns entschieden.","translation":"After careful consideration we have decided."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Fundiert'' means?","options":["well-founded/sound","solid","based","grounded"],"correctAnswer":"well-founded/sound"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"A thorough analysis of the data enables well-founded decisions.","options":["Eine gründliche Analyse der Daten ermöglicht fundierte Entscheidungen.","Wenn man Daten analysiert, kann man Entscheidungen treffen.","Daten analysieren hilft beim Entscheiden.","Gute Analysen führen zu guten Entscheidungen."],"correctAnswer":"Eine gründliche Analyse der Daten ermöglicht fundierte Entscheidungen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die ___ der Situation erfordert eine enge Zusammenarbeit.","options":["Verbesserung","Verbesserungen","Verbessern","verbesserte"],"correctAnswer":"Verbesserung"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: After careful consideration we have decided","wordBankItems":["Nach","reiflicher","Überlegung","haben","wir","uns","entschieden","."],"correctAnswer":"Nach reiflicher Überlegung haben wir uns entschieden ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Reduzierung'' is the nominalisation of?","options":["reduzieren","reduziert","Reduktion","Reduzierheit"],"correctAnswer":"reduzieren"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000016c',1,'APPROVED','PUBLISHED',
'{"objectives":["Master concessive clauses","Use obwohl/obgleich/wenngleich/auch wenn","Express contrast and concession at B2"],"explanation":{"intro":"Concessive clauses at B2 cover the full range of concession connectors — from basic obwohl to formal wenngleich.","culturalNote":"German has a rich set of concession connectors. At B2: obwohl (although), obgleich/obzwar (formal = although), wenngleich (even though — very formal), auch wenn (even if/even though), wenn auch (although — literary), trotzdem/dennoch (nevertheless — as adverbs in main clause)."},"examples":[{"german":"Obwohl die Studie interessante Ergebnisse lieferte, werden weitere Untersuchungen benötigt.","english":"Although the study delivered interesting results, further investigations are needed."},{"german":"Wenngleich die Situation schwierig ist, sehen wir Möglichkeiten zur Verbesserung.","english":"Even though the situation is difficult, we see opportunities for improvement."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use the full range of German concessive constructions at B2."}}',
'{"items":[{"word":"obgleich","translation":"although (formal)","pronunciation":"op-GLYKH","example":"Obgleich schwierig."},{"word":"wenngleich","translation":"even though (very formal)","pronunciation":"VEN-glykh","example":"Wenngleich bekannt."},{"word":"dennoch","translation":"nevertheless/yet","pronunciation":"DEN-okh","example":"Dennoch entschied er."},{"word":"trotzdem","translation":"nevertheless/despite that","pronunciation":"TROTS-dem","example":"Trotzdem machte sie weiter."},{"word":"ungeachtet","translation":"regardless of/notwithstanding","pronunciation":"OON-geh-akh-tet","example":"Ungeachtet der Kosten."},{"word":"gleichwohl","translation":"nevertheless (very formal)","pronunciation":"GLYKH-vohl","example":"Gleichwohl bleibt die Frage."}]}',
'{"title":"Concessive scale — obwohl to wenngleich","pattern":"obwohl (neutral) < obgleich (formal) < wenngleich (very formal) < auch wenn (conditional concession)","explanation":"Register scale for concession: 1) Obwohl (neutral, everyday and formal). 2) Obgleich/obzwar (literary/elevated). 3) Wenngleich (elevated written — newspapers, official texts). 4) Auch wenn (even if/even though — conditional concession: true now or hypothetically). After these, verb goes to end. Main clause: dennoch/trotzdem/gleichwohl as adverbs at position 1 with V2. Ungeachtet + genitive = notwithstanding (preposition, not conjunction).","examples":[{"sentence":"Obgleich er müde war, arbeitete er bis Mitternacht.","translation":"Although he was tired, he worked until midnight."},{"sentence":"Auch wenn du Recht hast, ändert das nichts an der Situation.","translation":"Even if you are right, that changes nothing about the situation."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Wenngleich'' is which register?","options":["very formal/elevated","formal","neutral","colloquial"],"correctAnswer":"very formal/elevated"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Although the study delivered interesting results, further investigations are needed.","options":["Obwohl die Studie interessante Ergebnisse lieferte, werden weitere Untersuchungen benötigt.","Die Studie war interessant aber nicht vollständig.","Trotz interessanter Ergebnisse brauchen wir mehr Forschung.","Die Ergebnisse sind gut, aber man braucht mehr."],"correctAnswer":"Obwohl die Studie interessante Ergebnisse lieferte, werden weitere Untersuchungen benötigt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Obgleich er müde war, arbeitete er bis ___.","options":["Mitternacht","Mitternachts","der Mitternacht","nachts"],"correctAnswer":"Mitternacht"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Even if you are right, that changes nothing about the situation","wordBankItems":["Auch","wenn","du","Recht","hast",",","ändert","das","nichts","an","der","Situation","."],"correctAnswer":"Auch wenn du Recht hast , ändert das nichts an der Situation ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Dennoch'' and ''trotzdem'' are?","options":["adverbs in main clause","conjunctions","conjunctions triggering verb-final","prepositions"],"correctAnswer":"adverbs in main clause"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000016d',1,'APPROVED','PUBLISHED',
'{"objectives":["Master B2 conditionals","Use all conditional types including irreale Bedingungssätze","Distinguish wenn/falls/sofern"],"explanation":{"intro":"B2 conditionals cover all types — real, potential, and irrealis — plus the formal connectors sofern and falls.","culturalNote":"German has rich conditional vocabulary. At B2: wenn (when/if), falls (if — emphasises possibility), sofern (provided that — formal condition), es sei denn (unless — concessive conditional). The irrealis uses Konjunktiv II throughout. Conditional clauses can also appear without wenn: Hättest du früher gesagt... = Had you said earlier..."},"examples":[{"german":"Sofern keine neuen Erkenntnisse vorliegen, bleibt die Entscheidung bestehen.","english":"Provided no new findings are available, the decision will stand."},{"german":"Hättest du früher Bescheid gegeben, hätten wir die Situation anders handhaben können.","english":"Had you informed us earlier, we could have handled the situation differently."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use all German conditional types confidently at B2, including inverted and formal conditionals."}}',
'{"items":[{"word":"sofern","translation":"provided that/as long as","pronunciation":"zo-FERN","example":"Sofern die Bedingung gilt."},{"word":"vorliegen","translation":"to be available/at hand","pronunciation":"FOR-lee-gen","example":"Erkenntnisse vorliegen."},{"word":"bestehen bleiben","translation":"to stand/remain in place","pronunciation":"beh-SHTAY-en BLY-ben","example":"Die Entscheidung bleibt bestehen."},{"word":"handhaben","translation":"to handle/manage","pronunciation":"HANT-hah-ben","example":"Etwas handhaben."},{"word":"es sei denn","translation":"unless","pronunciation":"es zy den","example":"Es sei denn, du kommst."},{"word":"vorausgesetzt dass","translation":"provided that/assuming that","pronunciation":"for-OWS-geh-zetst das","example":"Vorausgesetzt, dass alles klappt."}]}',
'{"title":"Inverted conditional — without wenn","pattern":"Hätte/Wäre/Würde... (inversion instead of wenn-clause) — literary/formal conditional","explanation":"In formal and literary German, the wenn can be dropped from a conditional clause — the verb moves to first position (inversion). Wenn du Zeit hättest... = Hättest du Zeit... Wenn er es gewusst hätte... = Hätte er es gewusst... This inversion is common in written German and signals elevated register. The main clause is unchanged. Also possible with all types: Würdest du mir helfen, (dann) wäre ich dankbar = Would you help me, I would be grateful.","examples":[{"sentence":"Wäre ich früher gegangen, hätte ich den Zug noch erreicht.","translation":"Had I left earlier, I would have still caught the train."},{"sentence":"Käme er pünktlich, würden wir früher beginnen können.","translation":"Were he to come on time, we would be able to start earlier."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Sofern'' means?","options":["provided that/as long as","if","unless","as soon as"],"correctAnswer":"provided that/as long as"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Provided no new findings are available, the decision will stand.","options":["Sofern keine neuen Erkenntnisse vorliegen, bleibt die Entscheidung bestehen.","Die Entscheidung ist endgültig, wenn es keine neuen Erkenntnisse gibt.","Solange es keine neuen Erkenntnisse gibt, gilt die Entscheidung.","Falls keine Erkenntnisse vorliegen, bleibt es dabei."],"correctAnswer":"Sofern keine neuen Erkenntnisse vorliegen, bleibt die Entscheidung bestehen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Wäre ich früher gegangen, hätte ich den Zug noch ___.","options":["erreicht","erreichen","erreichen können","erreichend"],"correctAnswer":"erreicht"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Had I left earlier, I would have still caught the train","wordBankItems":["Wäre","ich","früher","gegangen",",","hätte","ich","den","Zug","noch","erreicht","."],"correctAnswer":"Wäre ich früher gegangen , hätte ich den Zug noch erreicht ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Es sei denn'' means?","options":["unless","except if","provided that","in case"],"correctAnswer":"unless"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000016e',1,'APPROVED','PUBLISHED',
'{"objectives":["Master German modal particles","Use doch, ja, denn, mal, eigentlich, schon naturally","Understand the pragmatic role of Modalpartikeln"],"explanation":{"intro":"Modal particles are small words that add attitude and nuance to German utterances — essential for sounding natural at B2.","culturalNote":"Modalpartikeln (modal particles) are a distinctive feature of spoken German. They are extremely common but notoriously hard to translate. Key ones: ja (shared knowledge: Das weißt du ja = You know that), doch (contradiction or reassurance: Das stimmt doch nicht = That''s not right / Komm doch rein = Do come in), mal (softening: Schau mal = Have a look), eigentlich (actually — slight contradiction), denn (curious/interested: Was ist denn los? = What''s wrong?)."},"examples":[{"german":"Du weißt ja, dass das nicht so einfach ist — aber wir versuchen es doch.","english":"You know, of course, that it''s not that simple — but we''ll try anyway."},{"german":"Was ist denn hier los? — Komm doch rein und schau dir das mal an!","english":"What on earth is going on here? — Do come in and have a look at this!"}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use German modal particles naturally to add attitude and nuance at B2."}}',
'{"items":[{"word":"ja","translation":"ja (shared knowledge/emphasis)","pronunciation":"yah","example":"Das weißt du ja."},{"word":"doch","translation":"doch (contradiction/reassurance)","pronunciation":"dokh","example":"Komm doch rein."},{"word":"mal","translation":"mal (softening imperative)","pronunciation":"mahl","example":"Schau mal."},{"word":"eigentlich","translation":"actually (slight contradiction)","pronunciation":"EY-gent-likh","example":"Eigentlich dachte ich."},{"word":"denn","translation":"denn (curiosity/emphasis in questions)","pronunciation":"den","example":"Was ist denn los?"},{"word":"schon","translation":"schon (reassurance/concession)","pronunciation":"shohn","example":"Das wird schon klappen."}]}',
'{"title":"Modalpartikeln — functions and combinations","pattern":"Multiple particles: ja + doch (shared fact + reassurance), mal + schnell (softened urgency), doch + eigentlich (soft contradiction)","explanation":"Modal particles are unstressable function words that signal speaker attitude. Common functions: ja = shared knowledge, obviousness; doch = contradiction (statements), invitation/softening (imperatives); mal = makes requests softer; schon = reassurance, concession; denn = curiosity, questions only; eigentlich = actually (soft correction). Combinations are common: Das ist doch eigentlich gut = That is actually quite good, when you think about it. They never carry sentence stress.","examples":[{"sentence":"Das ist doch eigentlich eine gute Idee.","translation":"That''s actually quite a good idea (don''t you think)."},{"sentence":"Könnten Sie mal kurz warten?","translation":"Could you perhaps wait just a moment?"}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"Which particle softens imperatives and makes requests gentler?","options":["mal","ja","doch","denn"],"correctAnswer":"mal"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"You know, of course, that it''s not that simple — but we''ll try anyway.","options":["Du weißt ja, dass das nicht so einfach ist — aber wir versuchen es doch.","Du weißt, dass das schwer ist.","Es ist nicht einfach, aber wir probieren es.","Obwohl es schwer ist, versuchen wir es."],"correctAnswer":"Du weißt ja, dass das nicht so einfach ist — aber wir versuchen es doch."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Könnten Sie ___ kurz warten?","options":["mal","ja","doch","schon"],"correctAnswer":"mal"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That''s actually quite a good idea","wordBankItems":["Das","ist","doch","eigentlich","eine","gute","Idee","."],"correctAnswer":"Das ist doch eigentlich eine gute Idee ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Denn'' as a modal particle appears only in?","options":["questions","statements","imperatives","subjunctive clauses"],"correctAnswer":"questions"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000016f',1,'APPROVED','PUBLISHED',
'{"objectives":["Master genitive prepositions","Use wegen, trotz, während, aufgrund, angesichts","Read formal German texts at B2"],"explanation":{"intro":"Genitive prepositions are essential for formal and written German at B2 — commonly found in newspapers, academic, and legal texts.","culturalNote":"German has many genitive prepositions that mark high formal register. The most important: wegen (because of), trotz (despite), während (during), aufgrund (on the basis of), angesichts (in view of), hinsichtlich (with regard to), bezüglich (regarding), im Hinblick auf (with a view to). In spoken German, wegen + dative is very common (wegen dem Wetter), but formal writing uses genitive."},"examples":[{"german":"Angesichts der aktuellen Lage müssen wir unsere Strategie überdenken.","english":"In view of the current situation, we must rethink our strategy."},{"german":"Trotz aller Schwierigkeiten hat das Team die Aufgabe erfolgreich bewältigt.","english":"Despite all the difficulties, the team successfully mastered the task."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use and recognise genitive prepositions in formal German texts at B2."}}',
'{"items":[{"word":"angesichts","translation":"in view of/faced with","pronunciation":"AN-geh-zikhts","example":"Angesichts der Lage."},{"word":"hinsichtlich","translation":"with regard to/regarding","pronunciation":"HIN-zikht-likh","example":"Hinsichtlich der Kosten."},{"word":"bezüglich","translation":"regarding/concerning","pronunciation":"beh-TSÜG-likh","example":"Bezüglich Ihrer Anfrage."},{"word":"aufgrund","translation":"due to/on the basis of","pronunciation":"OWF-groont","example":"Aufgrund der Ergebnisse."},{"word":"im Hinblick auf","translation":"with a view to/in respect of","pronunciation":"im HIN-blik owf","example":"Im Hinblick auf."},{"word":"überdenken","translation":"to rethink/reconsider","pronunciation":"ü-ber-DEN-ken","example":"Die Strategie überdenken."}]}',
'{"title":"Genitive prepositions — formal register markers","pattern":"wegen/trotz/während/aufgrund/angesichts + genitive (formal); wegen/trotz + dative (colloquial spoken)","explanation":"Genitive prepositions mark formal register. Key ones and examples: angesichts der Situation (in view of the situation), aufgrund seiner Erfahrung (based on his experience), hinsichtlich der Anforderungen (regarding the requirements), bezüglich Ihres Schreibens (regarding your letter), trotz des Regens (despite the rain — formal; trotz dem Regen = colloquial). Wegen + genitive in writing; wegen + dative in speech. Learning to recognise and produce these is a B2 milestone.","examples":[{"sentence":"Hinsichtlich Ihrer Anfrage teilen wir Ihnen mit, dass...","translation":"With regard to your enquiry we inform you that..."},{"sentence":"Aufgrund technischer Probleme kommt es zu Verzögerungen.","translation":"Due to technical problems there will be delays."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Angesichts'' means?","options":["in view of/faced with","considering","regarding","despite"],"correctAnswer":"in view of/faced with"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In view of the current situation, we must rethink our strategy.","options":["Angesichts der aktuellen Lage müssen wir unsere Strategie überdenken.","Da die Lage schwierig ist, müssen wir anders vorgehen.","Wir überdenken unsere Strategie wegen der aktuellen Lage.","Die aktuelle Situation erfordert eine neue Strategie."],"correctAnswer":"Angesichts der aktuellen Lage müssen wir unsere Strategie überdenken."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Aufgrund technischer Probleme kommt es zu ___.","options":["Verzögerungen","Verspätungen","Problemen","Fehler"],"correctAnswer":"Verzögerungen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Due to technical problems there will be delays","wordBankItems":["Aufgrund","technischer","Probleme","kommt","es","zu","Verzögerungen","."],"correctAnswer":"Aufgrund technischer Probleme kommt es zu Verzögerungen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"In formal written German, wegen + which case is preferred?","options":["genitive","dative","accusative","nominative"],"correctAnswer":"genitive"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000170',1,'APPROVED','PUBLISHED',
'{"objectives":["Master participial constructions","Use erweitertes Partizipialattribut","Read complex newspaper German at B2"],"explanation":{"intro":"Extended participial attributes (erweiterte Partizipialattribute) are common in written German — they pack information densely into a noun phrase.","culturalNote":"Erweiterte Partizipialattribute are a major feature of written German that distinguish B2+ from B1. Pattern: article + [participial phrase] + noun. In English: relative clause (who/which is...). In German: compressed into attributive phrase. Newspapers use this constantly."},"examples":[{"german":"Die in der Studie verwendeten Methoden wurden von unabhängigen Experten überprüft.","english":"The methods used in the study were checked by independent experts."},{"german":"Das von der Regierung angekündigte Maßnahmenpaket soll die Wirtschaft stärken.","english":"The package of measures announced by the government is intended to strengthen the economy."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can read and produce extended participial attributes in formal German at B2."}}',
'{"items":[{"word":"das Maßnahmenpaket","translation":"package of measures","pronunciation":"dahs MAHS-nah-men-pa-keht","example":"Ein Maßnahmenpaket."},{"word":"ankündigen","translation":"to announce","pronunciation":"AN-kün-dee-gen","example":"Maßnahmen ankündigen."},{"word":"überprüfen","translation":"to check/verify","pronunciation":"ü-ber-PRÜF-en","example":"Methoden überprüfen."},{"word":"unabhängig","translation":"independent","pronunciation":"OON-ap-heng-ikh","example":"Unabhängige Experten."},{"word":"verwenden","translation":"to use/employ","pronunciation":"fer-VEN-den","example":"Methoden verwenden."},{"word":"das Partizipialattribut","translation":"participial attribute","pronunciation":"dahs par-ti-TSIP-ee-ahl-at-ree-boot","example":"Partizipialattribut."}]}',
'{"title":"Erweitertes Partizipialattribut — extended participial attribute","pattern":"Art. + [Partizip II + Ergänzungen] + Nomen = relative clause compressed into noun phrase","explanation":"Pattern: Die [in der Studie verwendeten] Methoden = The [methods used in the study]. The participial phrase sits between article and noun. Partizip II (active process): das [von uns entwickelte] System = the system [developed by us]. Partizip I (ongoing): die [wachsende] Wirtschaft = the [growing] economy. These compress relative clauses (die Methoden, die in der Studie verwendet wurden) into shorter phrases. Recognising and parsing these is key to reading German newspapers.","examples":[{"sentence":"Die seit Jahrzehnten angewandte Methode gilt als zuverlässig.","translation":"The method applied for decades is regarded as reliable."},{"sentence":"Das für nächstes Jahr geplante Projekt braucht noch Finanzierung.","translation":"The project planned for next year still needs funding."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Maßnahmenpaket'' means?","options":["package of measures","action plan","bundle of measures","policy package"],"correctAnswer":"package of measures"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The methods used in the study were checked by independent experts.","options":["Die in der Studie verwendeten Methoden wurden von unabhängigen Experten überprüft.","Die Methoden wurden von Experten überprüft.","Die Studie verwendete Methoden, die überprüft wurden.","Experten überprüften die Methoden der Studie."],"correctAnswer":"Die in der Studie verwendeten Methoden wurden von unabhängigen Experten überprüft."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das für nächstes Jahr geplante Projekt braucht noch ___.","options":["Finanzierung","Finanzen","finanzielle Mittel","Geld"],"correctAnswer":"Finanzierung"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The method applied for decades is regarded as reliable","wordBankItems":["Die","seit","Jahrzehnten","angewandte","Methode","gilt","als","zuverlässig","."],"correctAnswer":"Die seit Jahrzehnten angewandte Methode gilt als zuverlässig ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die [wachsende] Wirtschaft'' uses which participle type?","options":["Partizip I (ongoing)","Partizip II (completed)","Infinitiv","Adjektiv"],"correctAnswer":"Partizip I (ongoing)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000171',1,'APPROVED','PUBLISHED',
'{"objectives":["Master causal clauses at B2","Use weil/da/zumal/denn and their differences","Express cause with noun phrases (aufgrund, wegen)"],"explanation":{"intro":"B2 causal clauses cover the full range of causal connectors and the stylistic differences between them.","culturalNote":"Causal in German: weil (most common — verb to end), da (because/since — often for shared or obvious reasons, clause-initial), denn (for — coordinates, V2 in dependent clause — no verb-to-end), zumal (especially as/all the more since — adds extra reason). Choosing correctly signals fluency."},"examples":[{"german":"Da alle Teilnehmer bereits informiert waren, konnte das Meeting pünktlich beginnen.","english":"Since all participants had already been informed, the meeting could begin on time."},{"german":"Er lehnte das Angebot ab, denn er hatte bereits eine andere Stelle angenommen.","english":"He turned down the offer, for he had already accepted another position."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use all German causal connectors accurately and with appropriate register at B2."}}',
'{"items":[{"word":"zumal","translation":"especially as/all the more since","pronunciation":"tsoo-MAHL","example":"Zumal es sehr kalt war."},{"word":"denn","translation":"for/because (coordinating)","pronunciation":"den","example":"Denn das war wichtig."},{"word":"teilnehmen","translation":"to participate/take part","pronunciation":"TYL-nay-men","example":"An der Konferenz teilnehmen."},{"word":"ablehnen","translation":"to turn down/refuse","pronunciation":"AP-lay-nen","example":"Ein Angebot ablehnen."},{"word":"annehmen","translation":"to accept/take on","pronunciation":"AN-nay-men","example":"Eine Stelle annehmen."},{"word":"der Teilnehmer","translation":"participant","pronunciation":"dayr TYL-nay-mer","example":"Alle Teilnehmer."}]}',
'{"title":"Weil vs. da vs. denn — causal connectors compared","pattern":"weil (subordinating, V-final) vs. da (subordinating, clause-initial, shared info) vs. denn (coordinating, V2, adding explanation)","explanation":"Three main causal connectors: 1) Weil = because (V-final subordinate, most common, new information reason). 2) Da = since/as (V-final subordinate, usually clause-INITIAL, reason already known or obvious). 3) Denn = for/because (COORDINATING conjunction — V2 in second clause, adds explanation as afterthought or supplemental reason, more formal in writing). Zumal = especially since/all the more because (adds an additional, strengthening reason).","examples":[{"sentence":"Da er krank war, blieb er zu Hause.","translation":"Since he was ill, he stayed at home."},{"sentence":"Er blieb zu Hause, denn er war krank.","translation":"He stayed at home, for he was ill."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Zumal'' means?","options":["especially as/all the more since","especially","moreover","in addition"],"correctAnswer":"especially as/all the more since"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Since all participants had already been informed, the meeting could begin on time.","options":["Da alle Teilnehmer bereits informiert waren, konnte das Meeting pünktlich beginnen.","Weil alle informiert waren, begann das Meeting pünktlich.","Das Meeting begann pünktlich, weil alle Bescheid wussten.","Alle waren informiert, also begann das Meeting pünktlich."],"correctAnswer":"Da alle Teilnehmer bereits informiert waren, konnte das Meeting pünktlich beginnen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er blieb zu Hause, ___ er war krank.","options":["denn","weil","da","zumal"],"correctAnswer":"denn"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Since he was ill, he stayed at home","wordBankItems":["Da","er","krank","war",",","blieb","er","zu","Hause","."],"correctAnswer":"Da er krank war , blieb er zu Hause ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Denn'' as a causal conjunction: the following verb is in?","options":["second position (V2)","final position","first position","subjunctive"],"correctAnswer":"second position (V2)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000172',1,'APPROVED','PUBLISHED',
'{"objectives":["Master final clauses","Use damit/um...zu/auf dass","Express purpose at B2"],"explanation":{"intro":"Final clauses express purpose — ''in order to'' — at B2 using damit, um...zu, and formal auf dass.","culturalNote":"Purpose expression in German: um...zu (infinitive — same subject), damit (finite clause — different or same subject), auf dass (archaic/formal — Biblical). At B2, the distinction between um...zu (same subject required) and damit (allows different subjects) is mastered. Zum Zweck (for the purpose of) and mit dem Ziel (with the goal of) are formal nominal alternatives."},"examples":[{"german":"Das System wurde entwickelt, damit alle Nutzer einfachen Zugang haben können.","english":"The system was developed so that all users can have easy access."},{"german":"Um dieses Ziel zu erreichen, bedarf es erheblicher Investitionen.","english":"In order to achieve this goal, considerable investment is required."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can express purpose using damit, um...zu, and formal alternatives at B2."}}',
'{"items":[{"word":"auf dass","translation":"so that (archaic/formal)","pronunciation":"owf das","example":"Auf dass es gelingt."},{"word":"bedürfen","translation":"to require (+ genitive, formal)","pronunciation":"beh-DÜR-fen","example":"Es bedarf Investitionen."},{"word":"der Zweck","translation":"purpose/aim","pronunciation":"dayr tsvek","example":"Zum Zweck der Forschung."},{"word":"der Zugang","translation":"access","pronunciation":"dayr TSOO-gang","example":"Einfachen Zugang haben."},{"word":"gelingen","translation":"to succeed/work out (impersonal)","pronunciation":"geh-LIN-gen","example":"Es gelingt uns."},{"word":"erforderlich","translation":"required/necessary","pronunciation":"er-FOR-der-likh","example":"Das ist erforderlich."}]}',
'{"title":"Um...zu vs. damit — purpose clauses","pattern":"Um + Infinitiv + zu (same subject) vs. damit + V-final clause (different subjects allowed)","explanation":"Purpose: 1) Um...zu + infinitive (same subject required): Ich spare, um ein Auto zu kaufen = I save to buy a car. 2) Damit + finite clause (same or different subjects): Ich spare, damit mein Kind studieren kann = I save so that my child can study. Key rule: if the subject of the purpose clause is different from the main clause, damit is required; um...zu cannot be used. If same subject, either works (um...zu is more concise).","examples":[{"sentence":"Er erklärt es, damit alle es verstehen können.","translation":"He explains it so that everyone can understand it."},{"sentence":"Sie ist früh aufgestanden, um den Zug zu erreichen.","translation":"She got up early to catch the train."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Bedürfen'' takes which case?","options":["genitive","dative","accusative","nominative"],"correctAnswer":"genitive"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The system was developed so that all users can have easy access.","options":["Das System wurde entwickelt, damit alle Nutzer einfachen Zugang haben können.","Das System ermöglicht einfachen Zugang für Nutzer.","Um Zugang zu haben, wurde das System entwickelt.","Das System wurde für einfachen Zugang gebaut."],"correctAnswer":"Das System wurde entwickelt, damit alle Nutzer einfachen Zugang haben können."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er erklärt es, ___ alle es verstehen können.","options":["damit","um","auf dass","so dass"],"correctAnswer":"damit"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She got up early to catch the train","wordBankItems":["Sie","ist","früh","aufgestanden",",","um","den","Zug","zu","erreichen","."],"correctAnswer":"Sie ist früh aufgestanden , um den Zug zu erreichen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"When subjects differ, which purpose connector is REQUIRED?","options":["damit","um...zu","auf dass","zum Zweck"],"correctAnswer":"damit"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000173',1,'APPROVED','PUBLISHED',
'{"objectives":["Master consecutive clauses","Use sodass/so dass/so...dass","Express consequence at B2"],"explanation":{"intro":"Consecutive clauses (Konsekutivsätze) express consequences — ''so that'' / ''with the result that''.","culturalNote":"German Konsekutivsätze use so...dass (so...that) and sodass/so dass (so that — result). The so can be placed in the main clause (so kalt, dass... = so cold that...) or omitted. Infolgedessen (as a result), daher/darum (therefore) are adverb equivalents. The difference from damit: damit = purpose (desired), sodass = consequence (actual result)."},"examples":[{"german":"Die Lautstärke war so groß, dass man sich kaum verstehen konnte.","english":"The noise level was so great that one could barely understand each other."},{"german":"Es gab erhebliche Verzögerungen, sodass das Projekt erst im Herbst abgeschlossen werden konnte.","english":"There were considerable delays, with the result that the project could only be completed in autumn."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use consecutive clauses (sodass, so...dass) and consequence adverbs at B2."}}',
'{"items":[{"word":"infolgedessen","translation":"as a result/consequently","pronunciation":"in-FOL-geh-des-en","example":"Infolgedessen wurde entschieden."},{"word":"daher","translation":"therefore/hence","pronunciation":"dah-HAYR","example":"Daher sind wir hier."},{"word":"darum","translation":"therefore/that''s why","pronunciation":"dah-ROOM","example":"Darum geht es."},{"word":"die Lautstärke","translation":"volume/noise level","pronunciation":"dee LOWT-shtär-keh","example":"Die Lautstärke."},{"word":"abschließen","translation":"to complete/conclude","pronunciation":"AP-shlee-sen","example":"Das Projekt abschließen."},{"word":"die Verzögerung","translation":"delay","pronunciation":"dee fer-TSÖG-eh-roong","example":"Erhebliche Verzögerungen."}]}',
'{"title":"So...dass vs. sodass — consecutive clause pattern","pattern":"so + adjective/adverb + dass (degree → result) OR sodass (result clause — direct consequence)","explanation":"Two patterns: 1) So [degree] + dass [result]: Es war so laut, dass ich nichts hören konnte = It was so loud that I could hear nothing. The so emphasises the degree; dass introduces the consequence clause. 2) Sodass / so dass (together or separate): ..., sodass das Projekt scheiterte = ..., so that the project failed. The sodass/so dass version adds a result directly after a statement — no degree element needed. Key difference from damit: damit = intended purpose; sodass = actual result.","examples":[{"sentence":"Sie arbeitete so hart, dass sie schließlich zusammenbrach.","translation":"She worked so hard that she finally collapsed."},{"sentence":"Der Sturm war sehr stark, sodass viele Bäume umstürzten.","translation":"The storm was very strong, so that many trees fell."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Infolgedessen'' means?","options":["as a result/consequently","therefore","hence","accordingly"],"correctAnswer":"as a result/consequently"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The noise level was so great that one could barely understand each other.","options":["Die Lautstärke war so groß, dass man sich kaum verstehen konnte.","Die Lautstärke war sehr groß.","Man konnte sich kaum verstehen wegen der Lautstärke.","Wegen des Lärms war Verstehen schwer."],"correctAnswer":"Die Lautstärke war so groß, dass man sich kaum verstehen konnte."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Sie arbeitete so hart, dass sie schließlich ___.","options":["zusammenbrach","zusammenbricht","zusammengebrochen","sich zusammenbrach"],"correctAnswer":"zusammenbrach"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The storm was very strong so that many trees fell","wordBankItems":["Der","Sturm","war","sehr","stark",",","sodass","viele","Bäume","umstürzten","."],"correctAnswer":"Der Sturm war sehr stark , sodass viele Bäume umstürzten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Sodass'' expresses which type of clause?","options":["consequence/result","purpose","concession","condition"],"correctAnswer":"consequence/result"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000174',1,'APPROVED','PUBLISHED',
'{"objectives":["Master adversative clauses","Use während/wohingegen/aber/allerdings","Express contrast and opposition at B2"],"explanation":{"intro":"Adversative clauses at B2 contrast two facts or perspectives — distinguishing German speakers from lower-level learners.","culturalNote":"Adversative connectors: während (while/whereas — temporal or adversative), wohingegen (whereas — purely adversative, V-final), allerdings (however — main clause adverb, V2 after it), hingegen (by contrast — adverb, V2), im Gegensatz zu (in contrast to — preposition + dative). The choice signals register: hingegen/wohingegen are formal."},"examples":[{"german":"Während die Produktivität gestiegen ist, sind die Löhne real gesunken.","english":"While productivity has risen, wages have fallen in real terms."},{"german":"Städter profitieren häufig von besserer Infrastruktur, wohingegen ländliche Regionen oft vernachlässigt werden.","english":"City dwellers often benefit from better infrastructure, whereas rural regions are often neglected."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use adversative connectors to express contrast and opposition at B2."}}',
'{"items":[{"word":"wohingegen","translation":"whereas (adversative)","pronunciation":"voh-hin-GAY-gen","example":"Wohingegen die anderen."},{"word":"hingegen","translation":"by contrast/on the other hand","pronunciation":"HIN-gay-gen","example":"Hingegen war er bereit."},{"word":"allerdings","translation":"however/admittedly","pronunciation":"AL-er-dings","example":"Allerdings ist das schwierig."},{"word":"im Gegensatz zu","translation":"in contrast to","pronunciation":"im GAY-gen-zats tsoo","example":"Im Gegensatz zu früher."},{"word":"vernachlässigen","translation":"to neglect","pronunciation":"fer-NAKH-läs-ee-gen","example":"Vernachlässigt werden."},{"word":"real","translation":"in real terms","pronunciation":"reh-AHL","example":"Real gesunken."}]}',
'{"title":"Während (adversative) vs. wohingegen — contrast clauses","pattern":"Während + V-final clause (adversative contrast — while/whereas) vs. wohingegen (purely adversative, very formal)","explanation":"Während has two uses: 1) Temporal (while): Während ich arbeitete, schrieb er. 2) Adversative (whereas — B2): Während die Preise stiegen, sanken die Gehälter. Wohingegen = purely adversative (whereas — always V-final, very formal in written texts). Allerdings and hingegen are adverbs (V2 in main clause) meaning however/by contrast. Im Gegensatz zu + dative is a preposition: Im Gegensatz zum Vorjahr... = In contrast to the previous year...","examples":[{"sentence":"Während die Nachfrage steigt, bleibt das Angebot konstant.","translation":"While/Whereas demand is rising, supply remains constant."},{"sentence":"Das neue Modell ist günstiger, allerdings mit weniger Funktionen.","translation":"The new model is cheaper, however with fewer features."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Wohingegen'' means?","options":["whereas (adversative)","while","although","despite"],"correctAnswer":"whereas (adversative)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"While productivity has risen, wages have fallen in real terms.","options":["Während die Produktivität gestiegen ist, sind die Löhne real gesunken.","Die Produktivität steigt, aber die Löhne sinken.","Trotz steigender Produktivität sinken die Löhne.","Löhne und Produktivität gehen in verschiedene Richtungen."],"correctAnswer":"Während die Produktivität gestiegen ist, sind die Löhne real gesunken."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das neue Modell ist günstiger, ___ mit weniger Funktionen.","options":["allerdings","jedoch","aber","wohingegen"],"correctAnswer":"allerdings"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: While/Whereas demand is rising supply remains constant","wordBankItems":["Während","die","Nachfrage","steigt",",","bleibt","das","Angebot","konstant","."],"correctAnswer":"Während die Nachfrage steigt , bleibt das Angebot konstant ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Allerdings'' as an adverb triggers which word order?","options":["V2 (verb second)","V-final","V1 (verb first)","no change"],"correctAnswer":"V2 (verb second)"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000175',1,'APPROVED','PUBLISHED',
'{"objectives":["Master B2 relative clauses","Use was/wer/wie as relative pronouns","Use genitive relative pronouns dessen/deren"],"explanation":{"intro":"B2 relative clauses cover was (what — non-specific), genitive dessen/deren, and weswegen/womit as relative adverbs.","culturalNote":"B2 relative clauses extend beyond the basic der/die/das. Was refers to a whole sentence or an indefinite/superlative noun: Das ist alles, was ich weiß = That is all that I know. Dessen/deren are genitive relative pronouns. Wer refers to people generally."},"examples":[{"german":"Das Einzige, was mich noch überrascht, ist die Geschwindigkeit der Entwicklung.","english":"The only thing that still surprises me is the speed of development."},{"german":"Der Wissenschaftler, dessen Forschung bahnbrechend ist, wurde ausgezeichnet.","english":"The scientist whose research is groundbreaking was awarded."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use was, dessen/deren, and other B2 relative pronouns correctly in German."}}',
'{"items":[{"word":"bahnbrechend","translation":"groundbreaking/pioneering","pronunciation":"BAHN-brekh-end","example":"Bahnbrechende Forschung."},{"word":"auszeichnen","translation":"to award/distinguish","pronunciation":"OWS-tsykh-nen","example":"Jemanden auszeichnen."},{"word":"die Geschwindigkeit","translation":"speed","pronunciation":"dee geh-SHVIN-dikh-kyt","example":"Die Geschwindigkeit."},{"word":"dessen","translation":"whose (m/n genitive relative)","pronunciation":"DES-en","example":"Dessen Forschung."},{"word":"deren","translation":"whose (f/pl genitive relative)","pronunciation":"DAY-ren","example":"Deren Ergebnisse."},{"word":"weswegen","translation":"which is why/for which reason","pronunciation":"ves-VAY-gen","example":"Weswegen wir."}]}',
'{"title":"Genitive relative pronouns — dessen/deren","pattern":"Nominativ: der/die/das | Genitiv Relativ: dessen (m/n) / deren (f/pl)","explanation":"Genitive relative pronouns: dessen (masculine and neuter), deren (feminine and plural). Used when the relative clause needs a genitive attribute. Der Mann, dessen Auto gestohlen wurde... = The man whose car was stolen... Die Frau, deren Kind krank ist... = The woman whose child is ill... Der Wissenschaftler, dessen Forschung bahnbrechend ist... Deren = plural or feminine. Contrast: was (neuter, non-specific or sentence-referring), wer (person general reference).","examples":[{"sentence":"Das Unternehmen, dessen Produkte weltweit bekannt sind, wurde gegründet.","translation":"The company whose products are known worldwide was founded."},{"sentence":"Das ist alles, was ich dir sagen kann.","translation":"That is all that I can tell you."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Bahnbrechend'' means?","options":["groundbreaking/pioneering","revolutionary","innovative","path-breaking"],"correctAnswer":"groundbreaking/pioneering"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The only thing that still surprises me is the speed of development.","options":["Das Einzige, was mich noch überrascht, ist die Geschwindigkeit der Entwicklung.","Ich bin überrascht von der Geschwindigkeit.","Die Entwicklungsgeschwindigkeit ist erstaunlich.","Was mich überrascht ist, wie schnell alles geht."],"correctAnswer":"Das Einzige, was mich noch überrascht, ist die Geschwindigkeit der Entwicklung."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Wissenschaftler, ___ Forschung bahnbrechend ist, wurde ausgezeichnet.","options":["dessen","deren","dem","der"],"correctAnswer":"dessen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The company whose products are known worldwide was founded","wordBankItems":["Das","Unternehmen",",","dessen","Produkte","weltweit","bekannt","sind",",","wurde","gegründet","."],"correctAnswer":"Das Unternehmen , dessen Produkte weltweit bekannt sind , wurde gegründet ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Was'' as a relative pronoun refers to?","options":["whole sentence or indefinite/superlative noun","a person","a place","an object"],"correctAnswer":"whole sentence or indefinite/superlative noun"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000176',1,'APPROVED','PUBLISHED',
'{"objectives":["Master B2 word order","Use fronting and information structure","Handle complex sentence structures confidently"],"explanation":{"intro":"Advanced word order at B2 covers information structure — what comes first, how focus shifts, and stylistic variation.","culturalNote":"German word order is freer than English because case marks relationships. The first position (Vorfeld) carries the topic (what is already known); the final position (Nachfeld) often contains new or emphasised information. Topicalization moves any element to first position. This signals what is treated as background vs. new information."},"examples":[{"german":"Dass die Lösung so einfach sein würde, hätte ich nicht erwartet.","english":"That the solution would be so simple, I had not expected."},{"german":"Aus diesem Grund haben wir beschlossen, das Projekt zu verlängern.","english":"For this reason we have decided to extend the project."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use German word order flexibly for information structure and emphasis at B2."}}',
'{"items":[{"word":"das Vorfeld","translation":"first position (topic)","pronunciation":"dahs FOR-felt","example":"Das Vorfeld besetzen."},{"word":"die Topikalisierung","translation":"topicalisation","pronunciation":"dee toh-pee-kah-lee-TSEE-roong","example":"Topikalisierung."},{"word":"betonen","translation":"to emphasise","pronunciation":"beh-TOH-nen","example":"Ein Wort betonen."},{"word":"verlängern","translation":"to extend/prolong","pronunciation":"fer-LENG-ern","example":"Das Projekt verlängern."},{"word":"der Fokus","translation":"focus","pronunciation":"dayr FOH-koos","example":"Den Fokus setzen."},{"word":"hintergründlich","translation":"background (information)","pronunciation":"HIN-ter-gründ-likh","example":"Hintergrundinfo."}]}',
'{"title":"Topicalisation — fronting for emphasis","pattern":"Any clause element can be moved to first position (Vorfeld) for topicalisation — verb remains second","explanation":"German V2 rule: verb is ALWAYS second in main clause. But the element before it (position 1 = Vorfeld) can be almost anything: subject, object, adverb, clause, prepositional phrase. Aus diesem Grund haben wir beschlossen... (prepositional phrase fronted). Dass die Lösung einfach war, hätte ich nicht gedacht (dass-clause fronted). This fronts the topic/contrast element. Subjects normally are in Vorfeld, but can yield it to express contrast or cohesion.","examples":[{"sentence":"Das Buch hat er noch nicht gelesen.","translation":"The book he has not yet read (contrast with something else he has read)."},{"sentence":"Diesen Fehler hätte ich vermeiden können.","translation":"This mistake I could have avoided (regret focus on this specific mistake)."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"In German word order, what position does the finite verb take in main clauses?","options":["second (V2)","first","last","variable"],"correctAnswer":"second (V2)"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"That the solution would be so simple, I had not expected.","options":["Dass die Lösung so einfach sein würde, hätte ich nicht erwartet.","Ich habe nicht erwartet, dass die Lösung einfach ist.","Die Lösung war einfacher als erwartet.","Die einfache Lösung hat mich überrascht."],"correctAnswer":"Dass die Lösung so einfach sein würde, hätte ich nicht erwartet."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Buch hat er noch nicht ___.","options":["gelesen","lesen","gelesen haben","zu lesen"],"correctAnswer":"gelesen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: This mistake I could have avoided","wordBankItems":["Diesen","Fehler","hätte","ich","vermeiden","können","."],"correctAnswer":"Diesen Fehler hätte ich vermeiden können ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"Moving an element to first position for contrast is called?","options":["Topikalisierung","Inversion","Voranstellung","Betonung"],"correctAnswer":"Topikalisierung"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000177',1,'APPROVED','PUBLISHED',
'{"objectives":["Master B2 infinitive groups","Use without-zu, anstatt...zu, um...zu, scheinen zu","Extend B2 sentence variety"],"explanation":{"intro":"Infinitive groups at B2 extend beyond basic um...zu to cover a full range of infinitive constructions.","culturalNote":"Extended infinitive groups in German: um...zu (purpose), ohne...zu (without doing), anstatt/statt...zu (instead of doing), scheinen zu + Infinitiv (to seem to), beabsichtigen zu (to intend to), aufhören zu (to stop doing), beginnen zu (to begin to). The zu-infinitive is the most versatile extension of B2 syntax."},"examples":[{"german":"Anstatt das Problem zu lösen, beschloss er es zu ignorieren.","english":"Instead of solving the problem, he decided to ignore it."},{"german":"Es schien schwierig zu sein, alle Parteien zu überzeugen.","english":"It seemed difficult to convince all parties."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can use the full range of German infinitive constructions at B2."}}',
'{"items":[{"word":"scheinen zu","translation":"to seem to","pronunciation":"SHYN-en tsoo","example":"Es scheint zu funktionieren."},{"word":"beabsichtigen","translation":"to intend/plan","pronunciation":"beh-AP-zikh-tee-gen","example":"Etwas beabsichtigen."},{"word":"aufhören zu","translation":"to stop doing","pronunciation":"OWF-hö-ren tsoo","example":"Aufhören zu reden."},{"word":"beschließen","translation":"to decide/resolve","pronunciation":"beh-SHLEE-sen","example":"Etwas beschließen."},{"word":"ignorieren","translation":"to ignore","pronunciation":"ig-noh-REER-en","example":"Das Problem ignorieren."},{"word":"versuchen zu","translation":"to try to","pronunciation":"fer-ZOOKH-en tsoo","example":"Versuchen zu verstehen."}]}',
'{"title":"Infinitive constructions — full B2 inventory","pattern":"um...zu (purpose) | ohne...zu (without) | anstatt...zu (instead) | scheinen zu (to seem) | aufhören zu (to stop)","explanation":"Key infinitive constructions: 1) um...zu (purpose — in order to). 2) ohne...zu (without doing). 3) anstatt/statt...zu (instead of doing). 4) scheinen + zu + Inf (to seem to): Es scheint zu funktionieren. 5) aufhören/beginnen/versuchen + zu + Inf. All require the same subject as the main clause (except some verbs like helfen, lassen). Comma before ohne/anstatt/um is optional unless separating complex clauses. Infinitive group comes LAST in the sentence.","examples":[{"sentence":"Er redete, ohne nachzudenken.","translation":"He spoke without thinking."},{"sentence":"Sie begann, das Thema zu recherchieren.","translation":"She began to research the topic."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Beabsichtigen'' means?","options":["to intend/plan","to aim","to purpose","to want"],"correctAnswer":"to intend/plan"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Instead of solving the problem, he decided to ignore it.","options":["Anstatt das Problem zu lösen, beschloss er es zu ignorieren.","Er ignorierte das Problem, anstatt es zu lösen.","Das Problem wurde ignoriert statt gelöst.","Er entschied sich, das Problem nicht zu lösen."],"correctAnswer":"Anstatt das Problem zu lösen, beschloss er es zu ignorieren."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er redete, ohne nach___.","options":["zudenken","zu denken","gedacht","zu überlegen"],"correctAnswer":"zudenken"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She began to research the topic","wordBankItems":["Sie","begann",",","das","Thema","zu","recherchieren","."],"correctAnswer":"Sie begann , das Thema zu recherchieren ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Scheinen zu'' expresses?","options":["to seem to","to appear that","to look like","apparently"],"correctAnswer":"to seem to"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000178',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss research and science","Use Wissenschaft vocabulary","Talk about academic research in German"],"explanation":{"intro":"Research vocabulary at B2 covers scientific method, academic discourse, and research terminology.","culturalNote":"Germany is a world leader in Wissenschaft (science and research). The DFG (Deutsche Forschungsgemeinschaft — German Research Foundation) funds academic research. Fraunhofer and Max-Planck institutes are globally renowned. Publish-or-perish culture, Plagiatsskandale (plagiarism scandals), and open access debate are current issues."},"examples":[{"german":"Die empirische Forschung beruht auf systematischer Beobachtung und Auswertung von Daten.","english":"Empirical research is based on systematic observation and evaluation of data."},{"german":"Die Hypothese muss durch Experimente überprüft und gegebenenfalls revidiert werden.","english":"The hypothesis must be tested by experiments and revised if necessary."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss research methodology, scientific process, and academic vocabulary at B2."}}',
'{"items":[{"word":"empirisch","translation":"empirical","pronunciation":"em-PEE-rish","example":"Empirische Methoden."},{"word":"die Hypothese","translation":"hypothesis","pronunciation":"dee hü-poh-TAY-zeh","example":"Eine Hypothese aufstellen."},{"word":"gegebenenfalls","translation":"if necessary/as applicable","pronunciation":"geh-GAY-ben-en-fals","example":"Gegebenenfalls revidieren."},{"word":"revidieren","translation":"to revise","pronunciation":"reh-vee-DEER-en","example":"Die Hypothese revidieren."},{"word":"die Auswertung","translation":"evaluation/analysis","pronunciation":"dee OWS-ver-toong","example":"Datenauswertung."},{"word":"beruhen auf","translation":"to be based on","pronunciation":"beh-ROO-en owf","example":"Auf Fakten beruhen."}]}',
'{"title":"Beruhen auf — to be based on","pattern":"etwas beruht auf + dative (something is based on, rests on)","explanation":"Beruhen auf + dative = to be based on, rest on. Die Theorie beruht auf Experimenten = The theory is based on experiments. Compare: basieren auf + dative (to be based on — more common in everyday language, slightly less elevated), sich stützen auf + accusative (to be supported by/rely on), gründen auf + dative (to found on — more deliberate).","examples":[{"sentence":"Seine Entscheidung beruht auf falschen Annahmen.","translation":"His decision is based on false assumptions."},{"sentence":"Dieses Modell beruht auf jahrzehntelanger Forschung.","translation":"This model is based on decades of research."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Gegebenenfalls'' means?","options":["if necessary/as applicable","possibly","in case","when needed"],"correctAnswer":"if necessary/as applicable"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Empirical research is based on systematic observation and evaluation of data.","options":["Die empirische Forschung beruht auf systematischer Beobachtung und Auswertung von Daten.","Empirische Forschung sammelt Daten.","Systematische Beobachtung ist empirische Forschung.","Daten werden beobachtet und ausgewertet."],"correctAnswer":"Die empirische Forschung beruht auf systematischer Beobachtung und Auswertung von Daten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Seine Entscheidung beruht auf falschen ___.","options":["Annahmen","Annahme","Voraussetzungen","Grundlagen"],"correctAnswer":"Annahmen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: This model is based on decades of research","wordBankItems":["Dieses","Modell","beruht","auf","jahrzehntelanger","Forschung","."],"correctAnswer":"Dieses Modell beruht auf jahrzehntelanger Forschung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Revidieren'' means?","options":["to revise","to review","to reconsider","to correct"],"correctAnswer":"to revise"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000179',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss academic writing","Use akademisches Schreiben vocabulary","Produce formal academic German at B2"],"explanation":{"intro":"Academic writing vocabulary at B2 covers the conventions of formal German academic style.","culturalNote":"Akademisches Deutsch has distinct features: passive voice, nominalizations, genitive prepositions, complex subordination, and avoidance of ich (use of man or passive). German academic writing is notoriously complex — long sentences, heavy nominalization, dense information. A Seminararbeit (seminar paper) or Hausarbeit (essay) is a common university task."},"examples":[{"german":"Im vorliegenden Beitrag wird untersucht, inwieweit die aktuellen Maßnahmen wirksam sind.","english":"In the present paper it is examined to what extent the current measures are effective."},{"german":"Die gewonnenen Erkenntnisse lassen den Schluss zu, dass weiterer Forschungsbedarf besteht.","english":"The findings obtained allow the conclusion that further research is needed."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can write and understand formal academic German at B2 level."}}',
'{"items":[{"word":"vorliegend","translation":"present/at hand","pronunciation":"FOR-lee-gend","example":"Im vorliegenden Fall."},{"word":"inwieweit","translation":"to what extent","pronunciation":"in-vee-VYT","example":"Inwieweit das gilt."},{"word":"den Schluss zulassen","translation":"to allow the conclusion","pronunciation":"den shloos TSOO-las-en","example":"Den Schluss zulassen."},{"word":"der Forschungsbedarf","translation":"research need/demand","pronunciation":"dayr FOR-shoongs-beh-darf","example":"Forschungsbedarf besteht."},{"word":"gewonnen","translation":"obtained/gained","pronunciation":"geh-VON-en","example":"Gewonnene Erkenntnisse."},{"word":"wirksam","translation":"effective","pronunciation":"VIRK-zahm","example":"Wirksame Maßnahmen."}]}',
'{"title":"Academic German conventions — im vorliegenden Beitrag","pattern":"Formal academic framing: Im vorliegenden... wird untersucht... (passive impersonal)","explanation":"Key conventions of academic German: 1) Impersonal passive: Es wird untersucht = It is examined (avoids ich). 2) Im vorliegenden Beitrag/Text/Artikel (in the present paper/text/article — common opener). 3) Inwieweit = to what extent (introduces indirect question). 4) Den Schluss zulassen (allows the conclusion = evidence permits inference). 5) Densely packed nominalisations. Learning these phrases is essential for reading and writing German academic texts at B2.","examples":[{"sentence":"Im Rahmen dieser Arbeit wird gezeigt, dass...","translation":"Within the framework of this paper it is shown that..."},{"sentence":"Die vorliegenden Daten lassen vermuten, dass...","translation":"The present data suggest that..."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Wirksam'' means?","options":["effective","efficient","powerful","productive"],"correctAnswer":"effective"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"In the present paper it is examined to what extent the current measures are effective.","options":["Im vorliegenden Beitrag wird untersucht, inwieweit die aktuellen Maßnahmen wirksam sind.","Dieser Beitrag untersucht, ob die Maßnahmen wirken.","Wir untersuchen die aktuellen Maßnahmen.","Die aktuellen Maßnahmen werden untersucht."],"correctAnswer":"Im vorliegenden Beitrag wird untersucht, inwieweit die aktuellen Maßnahmen wirksam sind."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Im Rahmen dieser Arbeit wird gezeigt, dass ___.","options":["[verb-final clause]","[verb-second clause]","[infinitive follows]","[dass is not needed]"],"correctAnswer":"[verb-final clause]"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The present data suggest that further research is needed","wordBankItems":["Die","vorliegenden","Daten","lassen","vermuten",",","dass","weiterer","Forschungsbedarf","besteht","."],"correctAnswer":"Die vorliegenden Daten lassen vermuten , dass weiterer Forschungsbedarf besteht ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Inwieweit'' means?","options":["to what extent","in how far","whether","how much"],"correctAnswer":"to what extent"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000017a',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss economics and finance","Use Wirtschaft vocabulary at B2","Talk about economic concepts"],"explanation":{"intro":"Economics and finance vocabulary at B2 covers macroeconomics, financial markets, and German economic culture.","culturalNote":"Germany is the world''s 3rd largest economy (GDP). The Soziale Marktwirtschaft (Social Market Economy — coined by Ludwig Erhard) combines market economy with social protection. Key concerns: Inflation, Zinspolitik (interest rate policy), Haushaltsdisziplin (fiscal discipline — Schwarze Null = black zero, no new debt). German Sparzwang (saving compulsion) is a cultural trait."},"examples":[{"german":"Die soziale Marktwirtschaft verbindet wirtschaftliche Effizienz mit sozialer Gerechtigkeit.","english":"The social market economy combines economic efficiency with social justice."},{"german":"Steigende Zinsen belasten Kreditnehmer, können aber die Inflation eindämmen.","english":"Rising interest rates burden borrowers, but can contain inflation."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss economic concepts, financial markets, and the German economic model at B2."}}',
'{"items":[{"word":"die Marktwirtschaft","translation":"market economy","pronunciation":"dee MARKT-virt-shaft","example":"Soziale Marktwirtschaft."},{"word":"die Effizienz","translation":"efficiency","pronunciation":"dee ef-fee-tsee-ENTS","example":"Wirtschaftliche Effizienz."},{"word":"eindämmen","translation":"to contain/curb","pronunciation":"YN-däm-en","example":"Inflation eindämmen."},{"word":"der Zinssatz","translation":"interest rate","pronunciation":"dayr TSINS-zats","example":"Den Zinssatz erhöhen."},{"word":"der Kreditnehmer","translation":"borrower","pronunciation":"dayr kreh-DEET-nay-mer","example":"Kreditnehmer belasten."},{"word":"die Haushaltsdisziplin","translation":"fiscal discipline","pronunciation":"dee HOWS-halts-dis-tsee-plin","example":"Haushaltsdisziplin wahren."}]}',
'{"title":"Verbinden mit — to combine/link with","pattern":"etwas verbindet etwas mit + dative (to combine/link X with Y)","explanation":"Verbinden mit + dative = to combine, connect, link X with Y. Die Marktwirtschaft verbindet Effizienz mit Gerechtigkeit = The market economy combines efficiency with justice. Sich verbinden mit = to combine/join (reflexive). Die Verbindung (connection, link). Verbunden sein mit = to be connected with. Also: etw. in Verbindung bringen mit (to link, associate — causal).","examples":[{"sentence":"Der Kurs verbindet Theorie mit Praxis.","translation":"The course combines theory with practice."},{"sentence":"Das Angebot verbindet Qualität mit erschwinglichem Preis.","translation":"The offer combines quality with an affordable price."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Effizienz'' means?","options":["efficiency","effectiveness","economy","productivity"],"correctAnswer":"efficiency"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The social market economy combines economic efficiency with social justice.","options":["Die soziale Marktwirtschaft verbindet wirtschaftliche Effizienz mit sozialer Gerechtigkeit.","Die Marktwirtschaft ist sozial und effizient.","Deutschland hat eine soziale Marktwirtschaft.","Wirtschaft und Soziales müssen verbunden sein."],"correctAnswer":"Die soziale Marktwirtschaft verbindet wirtschaftliche Effizienz mit sozialer Gerechtigkeit."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Kurs verbindet Theorie mit ___.","options":["Praxis","Praktik","Praktischem","der Praxis"],"correctAnswer":"Praxis"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The offer combines quality with an affordable price","wordBankItems":["Das","Angebot","verbindet","Qualität","mit","erschwinglichem","Preis","."],"correctAnswer":"Das Angebot verbindet Qualität mit erschwinglichem Preis ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Eindämmen'' means?","options":["to contain/curb","to dam","to limit","to reduce"],"correctAnswer":"to contain/curb"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000017b',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss globalisation","Use Globalisierung vocabulary at B2","Talk about global trade and its effects"],"explanation":{"intro":"Globalisation vocabulary at B2 covers global trade, its benefits, critics, and the concept of deglobalisation.","culturalNote":"Deutschland is a Exportweltmeister (world export champion — historically). Over 30% of GDP comes from exports. Concepts: Freihandel (free trade), Protektionismus (protectionism), Lieferkettenstörungen (supply chain disruptions — became prominent during COVID/Ukraine war). The Begriff Deglobalisierung (deglobalisation) is increasingly discussed as countries look to reshore production."},"examples":[{"german":"Die Globalisierung hat den Wohlstand in vielen Ländern erhöht, aber gleichzeitig Ungleichheiten verstärkt.","english":"Globalisation has increased prosperity in many countries, but at the same time reinforced inequalities."},{"german":"Lieferkettenstörungen haben gezeigt, wie verwundbar hoch spezialisierte globale Produktionsketten sein können.","english":"Supply chain disruptions have shown how vulnerable highly specialised global production chains can be."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss globalisation, trade policy, and supply chains at B2."}}',
'{"items":[{"word":"der Wohlstand","translation":"prosperity/wealth","pronunciation":"dayr VOHL-shtant","example":"Wohlstand steigern."},{"word":"die Ungleichheit","translation":"inequality","pronunciation":"dee OON-glykh-hyt","example":"Soziale Ungleichheit."},{"word":"verwundbar","translation":"vulnerable","pronunciation":"fer-VOOND-bar","example":"Verwundbar sein."},{"word":"die Lieferkettenstörung","translation":"supply chain disruption","pronunciation":"dee LEE-fer-ket-en-shtö-roong","example":"Lieferkettenstörung."},{"word":"der Protektionismus","translation":"protectionism","pronunciation":"dayr pro-tek-tsyoh-NIS-moos","example":"Protektionismus."},{"word":"reshoren","translation":"to reshore","pronunciation":"ree-SHORE-en","example":"Produktion reshoren."}]}',
'{"title":"Zeigen wie + adjective + clause can be — reveal how ... can be","pattern":"etwas zeigt, wie + adjective + etwas sein kann (shows how X something can be)","explanation":"Zeigen wie = to show how. Lieferkettenstörungen haben gezeigt, wie verwundbar globale Ketten sein können = Supply chain disruptions showed how vulnerable global chains can be. Structure: haben gezeigt, wie [adjective] [noun] sein kann/können. This is a common journalistic pattern for drawing conclusions from events. Compare: demonstrieren (to demonstrate), verdeutlichen (to make clear), illustrieren (to illustrate — all work similarly).","examples":[{"sentence":"Die Krise hat gezeigt, wie wichtig gute Vorbereitung sein kann.","translation":"The crisis showed how important good preparation can be."},{"sentence":"Das Experiment illustriert, wie komplex diese Prozesse sind.","translation":"The experiment illustrates how complex these processes are."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Verwundbar'' means?","options":["vulnerable","sensitive","fragile","exposed"],"correctAnswer":"vulnerable"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Globalisation has increased prosperity in many countries, but at the same time reinforced inequalities.","options":["Die Globalisierung hat den Wohlstand in vielen Ländern erhöht, aber gleichzeitig Ungleichheiten verstärkt.","Globalisierung ist gut und schlecht.","Durch Globalisierung gibt es mehr Wohlstand und mehr Ungleichheit.","Globalisierung hat Gewinner und Verlierer."],"correctAnswer":"Die Globalisierung hat den Wohlstand in vielen Ländern erhöht, aber gleichzeitig Ungleichheiten verstärkt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Krise hat gezeigt, wie wichtig gute Vorbereitung sein ___.","options":["kann","könnte","konnte","ist"],"correctAnswer":"kann"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The experiment illustrates how complex these processes are","wordBankItems":["Das","Experiment","illustriert",",","wie","komplex","diese","Prozesse","sind","."],"correctAnswer":"Das Experiment illustriert , wie komplex diese Prozesse sind ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Wohlstand'' means?","options":["prosperity/wealth","affluence","richness","well-being"],"correctAnswer":"prosperity/wealth"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000017c',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss economic policy","Use Wirtschaftspolitik vocabulary at B2","Talk about fiscal and monetary policy"],"explanation":{"intro":"Economic policy vocabulary at B2 covers fiscal policy, monetary policy, regulation, and economic debates.","culturalNote":"German Wirtschaftspolitik is shaped by ordoliberal tradition (Freiburg School — market economy + rules-based order). The ECB (EZB — Europäische Zentralbank) sets monetary policy. Konjunkturprogramme (economic stimulus programmes) are used in recessions. The Sachverständigenrat (Council of Economic Experts — Five Wise Men) advises the government. Debt brake (Schuldenbremse) in the Grundgesetz limits deficit spending."},"examples":[{"german":"Die Schuldenbremse schränkt die Möglichkeiten der Bundesregierung ein, in Krisenzeiten zu investieren.","english":"The debt brake limits the federal government''s options to invest during crisis periods."},{"german":"Angebotsseitige Wirtschaftspolitik setzt auf Steuererleichterungen, um Investitionen zu fördern.","english":"Supply-side economic policy relies on tax relief to promote investment."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss economic policy, fiscal and monetary instruments, and economic debates at B2."}}',
'{"items":[{"word":"die Schuldenbremse","translation":"debt brake","pronunciation":"dee SHOOL-den-brem-zeh","example":"Schuldenbremse."},{"word":"einschränken","translation":"to limit/restrict","pronunciation":"YN-shren-ken","example":"Möglichkeiten einschränken."},{"word":"angebotsseitig","translation":"supply-side","pronunciation":"AN-geh-bohts-zy-tikh","example":"Angebotsseitig."},{"word":"die Steuererleichterung","translation":"tax relief","pronunciation":"dee SHTOY-er-er-lykh-teh-roong","example":"Steuererleichterungen."},{"word":"das Konjunkturprogramm","translation":"economic stimulus programme","pronunciation":"dahs kon-YOONK-toor-pro-gram","example":"Ein Konjunkturprogramm auflegen."},{"word":"die Geldpolitik","translation":"monetary policy","pronunciation":"dee GELT-po-lee-tik","example":"Geldpolitik der EZB."}]}',
'{"title":"Einschränken — to limit/restrict","pattern":"etwas schränkt etwas ein (separable — to limit, restrict, curtail)","explanation":"Einschränken (separable) = to limit, restrict, curtail. Die Schuldenbremse schränkt Investitionen ein = The debt brake limits investments. Perfect: hat eingeschränkt. Die Einschränkung = restriction, limitation. Sich einschränken = to cut back (on spending). Compare: begrenzen (to limit — more physical boundary), beschränken auf (to restrict to — more specific scope), einengen (to narrow — figurative).","examples":[{"sentence":"Das Gesetz schränkt die Meinungsfreiheit ein.","translation":"The law restricts freedom of expression."},{"sentence":"Wir müssen unsere Ausgaben einschränken.","translation":"We need to cut back on our expenditure."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Schuldenbremse'' means?","options":["debt brake","debt limit","spending cap","fiscal rule"],"correctAnswer":"debt brake"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The debt brake limits the federal government''s options to invest during crisis periods.","options":["Die Schuldenbremse schränkt die Möglichkeiten der Bundesregierung ein, in Krisenzeiten zu investieren.","Die Bundesregierung kann wegen der Schuldenbremse nicht investieren.","Die Schuldenbremse verhindert staatliche Investitionen.","In Krisenzeiten ist Investieren schwierig."],"correctAnswer":"Die Schuldenbremse schränkt die Möglichkeiten der Bundesregierung ein, in Krisenzeiten zu investieren."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Gesetz schränkt die Meinungsfreiheit ___.","options":["ein","aus","ab","weg"],"correctAnswer":"ein"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We need to cut back on our expenditure","wordBankItems":["Wir","müssen","unsere","Ausgaben","einschränken","."],"correctAnswer":"Wir müssen unsere Ausgaben einschränken ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Angebotsseitig'' means?","options":["supply-side","supply-based","from the supply angle","offer-based"],"correctAnswer":"supply-side"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-000000000169','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l361',361,'Konjunktiv II B2','KonjII B2 grammar','PUBLISHED'),
('dd000000-0000-0000-0000-00000000016a','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l362',362,'Passivkonstruktionen B2','B2 passive constructions','PUBLISHED'),
('dd000000-0000-0000-0000-00000000016b','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l363',363,'Nominalstil','Nominal style grammar','PUBLISHED'),
('dd000000-0000-0000-0000-00000000016c','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l364',364,'Konzessivsätze','Concessive clauses grammar','PUBLISHED'),
('dd000000-0000-0000-0000-00000000016d','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l365',365,'Konditionalsätze B2','B2 conditionals grammar','PUBLISHED'),
('dd000000-0000-0000-0000-00000000016e','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l366',366,'Modalpartikeln','Modal particles grammar','PUBLISHED'),
('dd000000-0000-0000-0000-00000000016f','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l367',367,'Präpositionen mit Genitiv','Genitive prepositions grammar','PUBLISHED'),
('dd000000-0000-0000-0000-000000000170','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l368',368,'Partizipalkonstruktionen','Extended participial constructions','PUBLISHED'),
('dd000000-0000-0000-0000-000000000171','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l369',369,'Kausalsätze B2','B2 causal clauses','PUBLISHED'),
('dd000000-0000-0000-0000-000000000172','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l370',370,'Finalsätze','Final/purpose clauses','PUBLISHED'),
('dd000000-0000-0000-0000-000000000173','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l371',371,'Konsekutivsätze','Consecutive clauses grammar','PUBLISHED'),
('dd000000-0000-0000-0000-000000000174','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l372',372,'Adversativsätze','Adversative clauses grammar','PUBLISHED'),
('dd000000-0000-0000-0000-000000000175','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l373',373,'Relativsätze B2','B2 relative clauses grammar','PUBLISHED'),
('dd000000-0000-0000-0000-000000000176','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l374',374,'Wortstellung B2','B2 word order grammar','PUBLISHED'),
('dd000000-0000-0000-0000-000000000177','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l375',375,'Infinitivgruppen B2','B2 infinitive groups grammar','PUBLISHED'),
('dd000000-0000-0000-0000-000000000178','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l376',376,'Forschung und Wissenschaft','Research vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-000000000179','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l377',377,'Akademisches Schreiben','Academic writing vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000017a','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l378',378,'Wirtschaft und Finanzen','Economics and finance vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000017b','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l379',379,'Globalisierung','Globalisation vocabulary','PUBLISHED'),
('dd000000-0000-0000-0000-00000000017c','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l380',380,'Wirtschaftspolitik','Economic policy vocabulary','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000169' WHERE stable_ref = 'de-b2-u04-l361' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000016a' WHERE stable_ref = 'de-b2-u04-l362' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000016b' WHERE stable_ref = 'de-b2-u04-l363' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000016c' WHERE stable_ref = 'de-b2-u04-l364' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000016d' WHERE stable_ref = 'de-b2-u04-l365' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000016e' WHERE stable_ref = 'de-b2-u04-l366' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000016f' WHERE stable_ref = 'de-b2-u04-l367' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000170' WHERE stable_ref = 'de-b2-u04-l368' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000171' WHERE stable_ref = 'de-b2-u04-l369' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000172' WHERE stable_ref = 'de-b2-u04-l370' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000173' WHERE stable_ref = 'de-b2-u04-l371' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000174' WHERE stable_ref = 'de-b2-u04-l372' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000175' WHERE stable_ref = 'de-b2-u04-l373' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000176' WHERE stable_ref = 'de-b2-u04-l374' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000177' WHERE stable_ref = 'de-b2-u04-l375' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000178' WHERE stable_ref = 'de-b2-u04-l376' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000179' WHERE stable_ref = 'de-b2-u04-l377' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000017a' WHERE stable_ref = 'de-b2-u04-l378' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000017b' WHERE stable_ref = 'de-b2-u04-l379' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000017c' WHERE stable_ref = 'de-b2-u04-l380' AND lesson_id IS NULL;
