-- V76: German B2 lessons 471-480 (B2 batch 7, 10 lessons)
-- Hex: 471=0x1d7, 480=0x1e0

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-0000000001d7','de-b2-l471','Wissenschaft und Forschung B2 - Science','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001d8','de-b2-l472','Medizin und Biotechnologie - Medicine','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001d9','de-b2-l473','Raumfahrt - Space','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001da','de-b2-l474','Quantencomputing - Quantum Computing','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001db','de-b2-l475','Erneuerbare Energien B2 - Renewables','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001dc','de-b2-l476','Kreislaufwirtschaft - Circular Economy','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001dd','de-b2-l477','Biodiversität - Biodiversity','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001de','de-b2-l478','Meere und Ozeane - Oceans','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001df','de-b2-l479','Welthandel - World Trade','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e0','de-b2-l480','B2 Meilenstein 3 - Milestone 3','language','de','B2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001d7',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss science at B2","Use Forschung vocabulary","Talk about academic research"],"explanation":{"intro":"Science and research vocabulary covers academic research, methodology, and science policy at B2.","culturalNote":"Germany is a global science leader: 4 Nobel laureates on average per year, 100+ universities, Max-Planck-Gesellschaft, Fraunhofer-Gesellschaft, Helmholtz-Gemeinschaft. Key concepts: Grundlagenforschung (basic research), angewandte Forschung (applied research), Drittmittel (third-party funding), Peer-Review, Open Access. The Exzellenzinitiative (now Exzellenzstrategie) funds elite universities."},"examples":[{"german":"Grundlagenforschung zielt nicht auf unmittelbare Anwendbarkeit ab, sondern verfolgt das Ziel, fundamentales Wissen zu erweitern.","english":"Basic research does not aim for immediate applicability but rather pursues the goal of expanding fundamental knowledge."},{"german":"Wissenschaftliche Erkenntnisse gewinnen erst durch Replikation und unabhängige Überprüfung an Glaubwürdigkeit.","english":"Scientific findings gain credibility only through replication and independent verification."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss scientific research, methodology, and science policy at B2."}}',
'{"items":[{"word":"die Anwendbarkeit","translation":"applicability","pronunciation":"dee AN-vend-bar-kyt","example":"Unmittelbare Anwendbarkeit."},{"word":"verfolgen","translation":"to pursue (a goal)","pronunciation":"fer-FOL-gen","example":"Ein Ziel verfolgen."},{"word":"die Replikation","translation":"replication","pronunciation":"dee rep-li-kah-tsee-OHN","example":"Durch Replikation."},{"word":"die Glaubwürdigkeit","translation":"credibility","pronunciation":"dee GLOWP-vür-dikh-kyt","example":"Glaubwürdigkeit gewinnen."},{"word":"unmittelbar","translation":"immediate/direct","pronunciation":"oon-MIT-el-bar","example":"Unmittelbare Anwendung."},{"word":"die Grundlagenforschung","translation":"basic research","pronunciation":"dee GROONT-lah-gen-for-shoong","example":"Grundlagenforschung."}]}',
'{"title":"Ein Ziel verfolgen — to pursue a goal","pattern":"ein Ziel verfolgen = to pursue a goal (deliberate, sustained effort toward an objective)","explanation":"Ein Ziel verfolgen = to pursue a goal. Grundlagenforschung verfolgt das Ziel, Wissen zu erweitern = Basic research pursues the goal of expanding knowledge. Note: Ziel verfolgen uses a noun (das Ziel), not a verb. Also: eine Strategie verfolgen (to pursue a strategy), einen Plan verfolgen (to pursue a plan), einen Ansatz verfolgen (to pursue an approach). Compare: anstreben (to aspire to/aim for — more aspirational), beabsichtigen (to intend — weaker, not necessarily sustained effort).","examples":[{"sentence":"Das Unternehmen verfolgt das Ziel, bis 2030 klimaneutral zu werden.","translation":"The company pursues the goal of becoming climate-neutral by 2030."},{"sentence":"Sie verfolgt eine klare Karrierestrategie.","translation":"She pursues a clear career strategy."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Glaubwürdigkeit'' means?","options":["credibility","trustworthiness","reliability","plausibility"],"correctAnswer":"credibility"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Basic research does not aim for immediate applicability but rather pursues the goal of expanding fundamental knowledge.","options":["Grundlagenforschung zielt nicht auf unmittelbare Anwendbarkeit ab, sondern verfolgt das Ziel, fundamentales Wissen zu erweitern.","Grundlagenforschung hat kein praktisches Ziel.","Grundlagenforschung erweitert Wissen ohne praktische Anwendung.","Das Ziel der Grundlagenforschung ist Wissensgewinn."],"correctAnswer":"Grundlagenforschung zielt nicht auf unmittelbare Anwendbarkeit ab, sondern verfolgt das Ziel, fundamentales Wissen zu erweitern."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Unternehmen verfolgt das Ziel, bis 2030 klimaneutral zu ___.","options":["werden","sein","gelten","bleiben"],"correctAnswer":"werden"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She pursues a clear career strategy","wordBankItems":["Sie","verfolgt","eine","klare","Karrierestrategie","."],"correctAnswer":"Sie verfolgt eine klare Karrierestrategie ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Unmittelbar'' means?","options":["immediate/direct","straightforward","without intermediary","unmediated"],"correctAnswer":"immediate/direct"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001d8',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss medicine and biotechnology at B2","Use Medizin vocabulary","Talk about gene technology and ethics"],"explanation":{"intro":"Medicine and biotechnology vocabulary covers genomics, clinical trials, and bioethics at B2.","culturalNote":"Germany has strict Gentechnikgesetz (genetic engineering law) and cautious stance on GMOs. Key developments: mRNA-Technologie (mRNA technology — BioNTech developed COVID vaccine in Mainz), CRISPR-Cas9 (gene editing), klinische Studien (clinical trials), personalised medicine. Key institutions: Deutsche Krebsgesellschaft, Robert Koch Institut (RKI — public health). Germany emphasises Bioethik (bioethics) oversight."},"examples":[{"german":"Personalisierte Medizin verspricht Therapien, die auf das individuelle genetische Profil eines Patienten zugeschnitten sind.","english":"Personalised medicine promises therapies tailored to an individual patient''s genetic profile."},{"german":"Die mRNA-Technologie hat das Potenzial, die Entwicklung von Impfstoffen gegen eine Vielzahl von Krankheiten grundlegend zu beschleunigen.","english":"mRNA technology has the potential to fundamentally accelerate the development of vaccines against a wide range of diseases."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss medicine, biotechnology, and bioethics at B2."}}',
'{"items":[{"word":"personalisiert","translation":"personalised","pronunciation":"per-zo-nah-li-ZEERT","example":"Personalisierte Medizin."},{"word":"zugeschnitten auf","translation":"tailored to","pronunciation":"TSOO-geh-shnit-en owf","example":"Auf den Patienten zugeschnitten."},{"word":"das Potenzial","translation":"potential","pronunciation":"dahs po-ten-tsee-AHL","example":"Das Potenzial haben."},{"word":"beschleunigen","translation":"to accelerate","pronunciation":"beh-SHLOY-ni-gen","example":"Die Entwicklung beschleunigen."},{"word":"der Impfstoff","translation":"vaccine","pronunciation":"dayr IMPF-shtof","example":"Impfstoffe entwickeln."},{"word":"grundlegend","translation":"fundamentally","pronunciation":"GROONT-lay-gend","example":"Grundlegend verändern."}]}',
'{"title":"Zugeschnitten auf — tailored to","pattern":"auf + accusative zugeschnitten = tailored to, designed for","explanation":"Zugeschnitten auf + accusative = tailored to, custom-designed for. Eine Therapie, die auf das genetische Profil zugeschnitten ist = a therapy tailored to the genetic profile. Perfect participial form: auf X zugeschnitten. Active: auf jemanden/etwas zuschneiden (to tailor to — separable: schneidet...zu). Compare: angepasst an (adapted to — more general), maßgeschneidert (bespoke/made-to-measure — more formal tailoring metaphor), abgestimmt auf (coordinated with/tuned to — for plans and strategies).","examples":[{"sentence":"Das Programm ist auf die Bedürfnisse der Studierenden zugeschnitten.","translation":"The programme is tailored to the needs of the students."},{"sentence":"Wir bieten Lösungen, die auf Ihren Betrieb zugeschnitten sind.","translation":"We offer solutions tailored to your business."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Beschleunigen'' means?","options":["to accelerate","to speed up","to hasten","to quicken"],"correctAnswer":"to accelerate"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Personalised medicine promises therapies tailored to an individual patient''s genetic profile.","options":["Personalisierte Medizin verspricht Therapien, die auf das individuelle genetische Profil eines Patienten zugeschnitten sind.","Personalisierte Medizin passt Therapien an den Patienten an.","Jeder Patient bekommt individuelle Behandlung.","Personalisierte Therapien nutzen das genetische Profil."],"correctAnswer":"Personalisierte Medizin verspricht Therapien, die auf das individuelle genetische Profil eines Patienten zugeschnitten sind."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Programm ist auf die Bedürfnisse der Studierenden ___.","options":["zugeschnitten","angepasst","abgestimmt","ausgerichtet"],"correctAnswer":"zugeschnitten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We offer solutions tailored to your business","wordBankItems":["Wir","bieten","Lösungen",",","die","auf","Ihren","Betrieb","zugeschnitten","sind","."],"correctAnswer":"Wir bieten Lösungen , die auf Ihren Betrieb zugeschnitten sind ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Impfstoff'' means?","options":["vaccine","inoculation","serum","immunisation"],"correctAnswer":"vaccine"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001d9',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss space at B2","Use Raumfahrt vocabulary","Talk about space exploration and policy"],"explanation":{"intro":"Space vocabulary covers space exploration, satellite technology, and space policy at B2.","culturalNote":"Germany is a major partner in ESA (Europäische Weltraumorganisation). Key missions: Rosetta (comet lander), ExoMars. Germany''s Raumfahrtagentur = DLR (Deutsches Zentrum für Luft- und Raumfahrt). Key topics: New Space (private spaceflight — Rocket Factory Augsburg), Weltraumschrott (space debris), Satellitentechnologie (satellite technology — GPS, earth observation), Mondmission (moon mission)."},"examples":[{"german":"Die Erforschung des Weltalls eröffnet nicht nur wissenschaftliche Erkenntnisse, sondern hat auch handfeste wirtschaftliche und technologische Nebeneffekte.","english":"The exploration of space opens up not only scientific insights but also has tangible economic and technological spin-offs."},{"german":"Weltraumschrott stellt eine zunehmende Bedrohung für aktive Satelliten und die Internationale Raumstation dar.","english":"Space debris poses an increasing threat to active satellites and the International Space Station."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss space exploration, satellite technology, and space policy at B2."}}',
'{"items":[{"word":"handfest","translation":"tangible/concrete","pronunciation":"HANT-fest","example":"Handfeste Vorteile."},{"word":"der Nebeneffekt","translation":"spin-off/side effect","pronunciation":"dayr NAY-ben-eh-fekt","example":"Technologische Nebeneffekte."},{"word":"die Bedrohung","translation":"threat","pronunciation":"dee beh-DROH-oong","example":"Eine Bedrohung darstellen."},{"word":"zunehmend","translation":"increasing/growing","pronunciation":"TSOO-nay-mend","example":"Zunehmende Bedrohung."},{"word":"darstellen","translation":"to pose/represent","pronunciation":"DAR-shtel-en","example":"Eine Bedrohung darstellen."},{"word":"der Weltraumschrott","translation":"space debris","pronunciation":"dayr VELT-rowm-shrot","example":"Weltraumschrott."}]}',
'{"title":"Etwas darstellen — to represent, constitute, pose","pattern":"etwas stellt X dar (separable) = something represents, constitutes, poses X","explanation":"Darstellen (separable) = to represent, constitute, pose. Weltraumschrott stellt eine Bedrohung dar = Space debris poses a threat. This is a formal-register way of saying ist (is). Eine Herausforderung darstellen = to pose a challenge. Eine Chance darstellen = to constitute an opportunity. Perfect: hat dargestellt. Compare: sein (to be — simple), bedeuten (to mean/represent — more semantic content), bilden (to form/constitute — structural).","examples":[{"sentence":"Diese Entwicklung stellt einen Wendepunkt dar.","translation":"This development represents a turning point."},{"sentence":"Der Mangel an Fachkräften stellt ein ernsthaftes Problem dar.","translation":"The shortage of skilled workers poses a serious problem."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Handfest'' means?","options":["tangible/concrete","solid","real","practical"],"correctAnswer":"tangible/concrete"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Space debris poses an increasing threat to active satellites and the International Space Station.","options":["Weltraumschrott stellt eine zunehmende Bedrohung für aktive Satelliten und die Internationale Raumstation dar.","Weltraumschrott ist gefährlich für Satelliten.","Aktive Satelliten sind durch Weltraumschrott bedroht.","Weltraumschrott bedroht die ISS und Satelliten."],"correctAnswer":"Weltraumschrott stellt eine zunehmende Bedrohung für aktive Satelliten und die Internationale Raumstation dar."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Diese Entwicklung stellt einen Wendepunkt ___.","options":["dar","vor","an","hin"],"correctAnswer":"dar"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The shortage of skilled workers poses a serious problem","wordBankItems":["Der","Mangel","an","Fachkräften","stellt","ein","ernsthaftes","Problem","dar","."],"correctAnswer":"Der Mangel an Fachkräften stellt ein ernsthaftes Problem dar ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Bedrohung'' means?","options":["threat","danger","risk","menace"],"correctAnswer":"threat"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001da',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss quantum computing at B2","Use Quantencomputing vocabulary","Talk about quantum technology"],"explanation":{"intro":"Quantum computing vocabulary covers quantum bits, superposition, and applications at B2.","culturalNote":"Germany invests heavily in Quantentechnologie: €2bn+ Quantum Technologies Framework Programme. IBM, Google, and European initiatives. Key concepts: Qubit (quantum bit), Superposition (superposition), Quantenverschränkung (quantum entanglement), Dekohärenz (decoherence). Applications: Kryptographie (cryptography — quantum-resistant encryption), Materialforschung (materials research), Optimierungsprobleme (optimisation problems). Still largely experimental."},"examples":[{"german":"Quantencomputer nutzen die Eigenschaften der Quantenmechanik, um bestimmte Berechnungen exponentiell schneller durchzuführen als klassische Computer.","english":"Quantum computers exploit the properties of quantum mechanics to perform certain calculations exponentially faster than classical computers."},{"german":"Die vollständige Realisierung fehlertoleranter Quantencomputer bleibt trotz enormer Fortschritte noch eine technische Herausforderung.","english":"The full realisation of fault-tolerant quantum computers remains a technical challenge despite enormous progress."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss quantum computing, quantum mechanics, and quantum technology at B2."}}',
'{"items":[{"word":"ausnutzen","translation":"to exploit/utilise","pronunciation":"OWS-noot-tsen","example":"Eigenschaften ausnutzen."},{"word":"exponentiell","translation":"exponential","pronunciation":"ek-spo-nen-tsee-EL","example":"Exponentiell schneller."},{"word":"fehlertolerант","translation":"fault-tolerant","pronunciation":"FAY-ler-to-leh-rant","example":"Fehlertoleranter Quantencomputer."},{"word":"die Realisierung","translation":"realisation/implementation","pronunciation":"dee reh-ah-li-ZEER-oong","example":"Vollständige Realisierung."},{"word":"vollständig","translation":"full/complete","pronunciation":"FOL-shten-dikh","example":"Vollständige Realisierung."},{"word":"die Berechnung","translation":"calculation","pronunciation":"dee beh-REKH-noong","example":"Berechnungen durchführen."}]}',
'{"title":"Trotz + Genitiv — despite (concessive preposition)","pattern":"trotz + genitive = despite, in spite of (concessive — obstacle does not prevent outcome)","explanation":"Trotz + genitive = despite, in spite of. Trotz enormer Fortschritte = despite enormous progress. Trotz des Regens (despite the rain). Trotz allem (despite everything — fixed phrase). Colloquially often used with dative: trotz dem (despite the — non-standard but widespread). Academic German uses genitive. Compare: obwohl (although — conjunction + verb), ungeachtet (regardless of — more formal), dennoch (nevertheless — adverb).","examples":[{"sentence":"Trotz intensiver Bemühungen konnte keine Einigung erzielt werden.","translation":"Despite intensive efforts, no agreement could be reached."},{"sentence":"Trotz aller Schwierigkeiten hat das Projekt Erfolg gehabt.","translation":"Despite all difficulties, the project has been successful."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Exponentiell'' means?","options":["exponential","extremely fast","rapidly increasing","geometric"],"correctAnswer":"exponential"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The full realisation of fault-tolerant quantum computers remains a technical challenge despite enormous progress.","options":["Die vollständige Realisierung fehlertoleranter Quantencomputer bleibt trotz enormer Fortschritte noch eine technische Herausforderung.","Quantencomputer sind trotz Fortschritten noch nicht ausgereift.","Die Technik hinter Quantencomputern ist noch nicht vollständig.","Quantencomputer bleiben eine Herausforderung."],"correctAnswer":"Die vollständige Realisierung fehlertoleranter Quantencomputer bleibt trotz enormer Fortschritte noch eine technische Herausforderung."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Trotz intensiver Bemühungen konnte keine Einigung ___ werden.","options":["erzielt","erreicht","gefunden","getroffen"],"correctAnswer":"erzielt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Despite all difficulties the project has been successful","wordBankItems":["Trotz","aller","Schwierigkeiten","hat","das","Projekt","Erfolg","gehabt","."],"correctAnswer":"Trotz aller Schwierigkeiten hat das Projekt Erfolg gehabt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Vollständig'' means?","options":["full/complete","total","entire","comprehensive"],"correctAnswer":"full/complete"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001db',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss renewables at B2","Use erneuerbare Energien vocabulary","Talk about energy transition"],"explanation":{"intro":"Renewables vocabulary covers wind, solar, and the energy transition at B2.","culturalNote":"Germany''s Energiewende: Ausstieg from nuclear (2023) and coal (2038), massive Windkraft (wind power — offshore and onshore) and Photovoltaik (solar) expansion. Key challenges: Netzstabilität (grid stability), Speicherkapazitäten (storage capacity), Prosumer (consumers who also produce). Germany aims for 80% renewable electricity by 2030. Key law: Erneuerbare-Energien-Gesetz (EEG)."},"examples":[{"german":"Die Energiewende erfordert nicht nur den Ausbau erneuerbarer Energiequellen, sondern auch grundlegende Anpassungen der Netzinfrastruktur.","english":"The energy transition requires not only the expansion of renewable energy sources but also fundamental adjustments to the grid infrastructure."},{"german":"Offshore-Windparks können in küstennahen Gewässern konstanter und stärker wehen als Anlagen an Land.","english":"Offshore wind farms can generate more constant and stronger wind in coastal waters than onshore installations."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss renewable energy, the energy transition, and grid infrastructure at B2."}}',
'{"items":[{"word":"der Ausbau","translation":"expansion/development","pronunciation":"dayr OWS-bow","example":"Ausbau erneuerbarer Energien."},{"word":"die Anpassung","translation":"adjustment/adaptation","pronunciation":"dee AN-pas-oong","example":"Grundlegende Anpassungen."},{"word":"küstennah","translation":"coastal/near the coast","pronunciation":"KÜS-ten-nah","example":"Küstennahe Gewässer."},{"word":"konstant","translation":"constant","pronunciation":"kon-STANT","example":"Konstanter Wind."},{"word":"die Netzinfrastruktur","translation":"grid infrastructure","pronunciation":"dee NETS-in-fra-strook-toor","example":"Netzinfrastruktur."},{"word":"der Windpark","translation":"wind farm","pronunciation":"dayr VINT-park","example":"Offshore-Windparks."}]}',
'{"title":"Wehen — to blow (wind); power generation verbs at B2","pattern":"Wind weht = wind blows; Anlage erzeugt Strom = installation generates electricity","explanation":"Wehen = to blow (specifically wind). Der Wind weht stark = The wind blows strongly. In the energy context: Strom erzeugen (to generate electricity), Energie gewinnen (to obtain/harvest energy), ins Netz einspeisen (to feed into the grid). Offshore-Windparks können stärker wehen = can generate more strongly. Note: wehen is intransitive (wind blows — no object). The particle verb einspeisen (to feed in) is key for renewables discourse.","examples":[{"sentence":"An der Küste weht der Wind stärker und konstanter als im Binnenland.","translation":"On the coast, the wind blows more strongly and more constantly than inland."},{"sentence":"Die Anlage speist täglich 500 MWh ins Netz ein.","translation":"The installation feeds 500 MWh into the grid daily."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Ausbau'' means?","options":["expansion/development","construction","extension","build-out"],"correctAnswer":"expansion/development"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The energy transition requires not only the expansion of renewable energy sources but also fundamental adjustments to the grid infrastructure.","options":["Die Energiewende erfordert nicht nur den Ausbau erneuerbarer Energiequellen, sondern auch grundlegende Anpassungen der Netzinfrastruktur.","Die Energiewende bedeutet mehr erneuerbare Energien und bessere Netze.","Erneuerbare Energien brauchen neue Netzinfrastruktur.","Die Energiewende erfordert Ausbau und Anpassung."],"correctAnswer":"Die Energiewende erfordert nicht nur den Ausbau erneuerbarer Energiequellen, sondern auch grundlegende Anpassungen der Netzinfrastruktur."},{"id":"ex3","type":"FILL_IN_BLANK","question":"An der Küste weht der Wind stärker und konstanter als im ___.","options":["Binnenland","Landesinneren","Inland","Hinterland"],"correctAnswer":"Binnenland"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The installation feeds 500 MWh into the grid daily","wordBankItems":["Die","Anlage","speist","täglich","500","MWh","ins","Netz","ein","."],"correctAnswer":"Die Anlage speist täglich 500 MWh ins Netz ein ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Küstennah'' means?","options":["coastal/near the coast","near the shore","by the sea","maritime"],"correctAnswer":"coastal/near the coast"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001dc',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss circular economy at B2","Use Kreislaufwirtschaft vocabulary","Talk about recycling and waste reduction"],"explanation":{"intro":"Circular economy vocabulary covers recycling, waste reduction, and sustainable production at B2.","culturalNote":"Germany has one of the world''s best recycling systems: Grüner Punkt (Green Dot), Pfandsystem (deposit system for bottles), Wertstoffhöfe (recycling centres). Key concepts: Kreislaufwirtschaft (circular economy — close the loop on materials), Upcycling, Cradle-to-Cradle design. The EU Circular Economy Action Plan shapes German policy. Elektroschrott (e-waste) is a growing challenge."},"examples":[{"german":"Die Kreislaufwirtschaft versucht, den linearen Wirtschaftsansatz des ''Nehmen, Herstellen, Wegwerfen'' durch einen geschlossenen Materialkreislauf zu ersetzen.","english":"The circular economy seeks to replace the linear economic approach of ''take, make, dispose'' with a closed material cycle."},{"german":"Upcycling geht über herkömmliches Recycling hinaus, indem Abfallmaterialien zu Produkten höherer Qualität aufgewertet werden.","english":"Upcycling goes beyond conventional recycling by upgrading waste materials into products of higher quality."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss circular economy, recycling, and sustainable production at B2."}}',
'{"items":[{"word":"ersetzen durch","translation":"to replace with","pronunciation":"er-ZETSEN doorkh","example":"Ersetzen durch eine Alternative."},{"word":"herkömmlich","translation":"conventional/traditional","pronunciation":"her-KÖM-likh","example":"Herkömmliches Recycling."},{"word":"hinausgehen über","translation":"to go beyond","pronunciation":"hi-NOWS-gay-en ü-ber","example":"Über Recycling hinausgehen."},{"word":"aufwerten","translation":"to upgrade/enhance","pronunciation":"OWF-ver-ten","example":"Zu höherer Qualität aufwerten."},{"word":"der Materialkreislauf","translation":"material cycle","pronunciation":"dayr mah-teh-ree-AHL-krys-lowf","example":"Geschlossener Materialkreislauf."},{"word":"linear","translation":"linear","pronunciation":"lee-neh-AR","example":"Linearer Ansatz."}]}',
'{"title":"Hinausgehen über — to go beyond","pattern":"etwas geht über + accusative hinaus = something goes beyond (exceeds, surpasses)","explanation":"Über X hinausgehen = to go beyond X, exceed, surpass. Upcycling geht über Recycling hinaus = Upcycling goes beyond recycling. Separable: geht...hinaus. Perfect: ist hinausgegangen. Also: über das Ziel hinausschießen (to overshoot the target — idiom), über den Rahmen hinausgehen (to exceed the scope). Compare: übersteigen (to exceed — more about amounts/limits), überbieten (to outbid/surpass — competitive), übertreffen (to surpass — more personal achievement).","examples":[{"sentence":"Die Ergebnisse gehen über unsere Erwartungen hinaus.","translation":"The results go beyond our expectations."},{"sentence":"Das Problem geht weit über den lokalen Rahmen hinaus.","translation":"The problem goes far beyond the local scope."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Herkömmlich'' means?","options":["conventional/traditional","common","standard","usual"],"correctAnswer":"conventional/traditional"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Upcycling goes beyond conventional recycling by upgrading waste materials into products of higher quality.","options":["Upcycling geht über herkömmliches Recycling hinaus, indem Abfallmaterialien zu Produkten höherer Qualität aufgewertet werden.","Upcycling ist besser als normales Recycling.","Durch Upcycling werden Abfälle zu hochwertigen Produkten.","Upcycling verwertet Abfälle aufwendiger als Recycling."],"correctAnswer":"Upcycling geht über herkömmliches Recycling hinaus, indem Abfallmaterialien zu Produkten höherer Qualität aufgewertet werden."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Ergebnisse gehen über unsere Erwartungen ___.","options":["hinaus","hinweg","heraus","voran"],"correctAnswer":"hinaus"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The problem goes far beyond the local scope","wordBankItems":["Das","Problem","geht","weit","über","den","lokalen","Rahmen","hinaus","."],"correctAnswer":"Das Problem geht weit über den lokalen Rahmen hinaus ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Ersetzen durch'' means?","options":["to replace with","to substitute","to swap for","to exchange for"],"correctAnswer":"to replace with"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001dd',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss biodiversity at B2","Use Biodiversität vocabulary","Talk about species loss and conservation"],"explanation":{"intro":"Biodiversity vocabulary covers ecosystems, species loss, and conservation at B2.","culturalNote":"Germany''s Biodiversitätsstrategie aims to protect 30% of land and sea by 2030. Key threats: Flächenverbrauch (land use), Pestizide (pesticides), Klimawandel. The Insektensterben (insect die-off) is a major crisis in Germany — 75%+ decline in flying insects since 1990. Key concepts: Artenvielfalt (species diversity), Ökosystemdienstleistungen (ecosystem services), Natura 2000 (EU protected areas network)."},"examples":[{"german":"Der dramatische Rückgang der Insektenpopulationen gefährdet nicht nur die biologische Vielfalt, sondern auch die Bestäubung von Nutzpflanzen.","english":"The dramatic decline of insect populations endangers not only biological diversity but also the pollination of crops."},{"german":"Artenvielfalt ist die Grundlage stabiler Ökosysteme, da verschiedene Spezies unterschiedliche ökologische Nischen besetzen.","english":"Species diversity is the basis of stable ecosystems, as different species occupy different ecological niches."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss biodiversity, species loss, and conservation at B2."}}',
'{"items":[{"word":"der Rückgang","translation":"decline","pronunciation":"dayr RÜK-gang","example":"Dramatischer Rückgang."},{"word":"die Bestäubung","translation":"pollination","pronunciation":"dee beh-SHTOY-boong","example":"Bestäubung von Nutzpflanzen."},{"word":"die Nutzpflanze","translation":"crop/cultivated plant","pronunciation":"dee NOOTS-pflan-tseh","example":"Nutzpflanzen."},{"word":"besetzen","translation":"to occupy","pronunciation":"beh-ZETSEN","example":"Nischen besetzen."},{"word":"die ökologische Nische","translation":"ecological niche","pronunciation":"dee ö-ko-LOH-gi-sheh NISH-eh","example":"Ökologische Nischen."},{"word":"stabil","translation":"stable","pronunciation":"shtah-BEEL","example":"Stabile Ökosysteme."}]}',
'{"title":"Nicht nur...sondern auch — extended with compound subjects","pattern":"X gefährdet nicht nur Y, sondern auch Z = X endangers not only Y but also Z","explanation":"Nicht nur...sondern auch with compound direct objects. Der Rückgang gefährdet nicht nur die Vielfalt, sondern auch die Bestäubung = The decline endangers not only diversity but also pollination. Both objects are fully affected. This extends to compound sentences and multi-element lists in academic discourse. The pattern reinforces that the problem has multiple dimensions — a key rhetorical move in environmental writing.","examples":[{"sentence":"Die Dürre beeinträchtigt nicht nur die Landwirtschaft, sondern auch die Trinkwasserversorgung.","translation":"The drought affects not only agriculture but also the drinking water supply."},{"sentence":"Plastikmüll schadet nicht nur Meerestieren, sondern auch dem gesamten marinen Ökosystem.","translation":"Plastic waste harms not only marine animals but also the entire marine ecosystem."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Bestäubung'' means?","options":["pollination","fertilisation","dusting","seeding"],"correctAnswer":"pollination"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The dramatic decline of insect populations endangers not only biological diversity but also the pollination of crops.","options":["Der dramatische Rückgang der Insektenpopulationen gefährdet nicht nur die biologische Vielfalt, sondern auch die Bestäubung von Nutzpflanzen.","Insekten sterben aus und das schadet der Biodiversität.","Ohne Insekten gibt es keine Bestäubung.","Der Rückgang der Insekten bedroht Biodiversität und Landwirtschaft."],"correctAnswer":"Der dramatische Rückgang der Insektenpopulationen gefährdet nicht nur die biologische Vielfalt, sondern auch die Bestäubung von Nutzpflanzen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Dürre beeinträchtigt nicht nur die Landwirtschaft, sondern auch die ___.","options":["Trinkwasserversorgung","Wasserversorgung","Wasserqualität","Wasserverfügbarkeit"],"correctAnswer":"Trinkwasserversorgung"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Plastic waste harms not only marine animals but also the entire marine ecosystem","wordBankItems":["Plastikmüll","schadet","nicht","nur","Meerestieren",",","sondern","auch","dem","gesamten","marinen","Ökosystem","."],"correctAnswer":"Plastikmüll schadet nicht nur Meerestieren , sondern auch dem gesamten marinen Ökosystem ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Rückgang'' means?","options":["decline","retreat","decrease","fall"],"correctAnswer":"decline"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001de',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss oceans at B2","Use Meer vocabulary","Talk about ocean protection and climate"],"explanation":{"intro":"Oceans vocabulary covers marine ecosystems, ocean acidification, and maritime policy at B2.","culturalNote":"Germany has coastlines on the Nordsee (North Sea) and Ostsee (Baltic Sea). Key issues: Meereserwärmung (ocean warming), Ozeanversauerung (ocean acidification), Überfischung (overfishing), Plastikverschmutzung (plastic pollution). Germany''s Meeresschutzgebiet (marine protected area) covers 45% of its EEZ. Key policy: EU Marine Strategy Framework Directive, OSPAR Convention (North Sea/Atlantic)."},"examples":[{"german":"Die Versauerung der Ozeane, verursacht durch den erhöhten CO2-Gehalt der Atmosphäre, bedroht kalzifizierungsabhängige Meeresorganismen.","english":"Ocean acidification, caused by the increased CO2 content of the atmosphere, threatens calcification-dependent marine organisms."},{"german":"Nachhaltige Fischerei erfordert strikte Fangquoten und die Erholung überfischter Bestände.","english":"Sustainable fisheries require strict catch quotas and the recovery of overfished stocks."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss ocean ecosystems, acidification, and marine conservation at B2."}}',
'{"items":[{"word":"die Versauerung","translation":"acidification","pronunciation":"dee fer-ZOW-eh-roong","example":"Versauerung der Ozeane."},{"word":"verursacht durch","translation":"caused by","pronunciation":"fer-OOR-zakht doorkh","example":"Verursacht durch CO2."},{"word":"die Fangquote","translation":"catch quota","pronunciation":"dee FANG-kvoh-teh","example":"Strikte Fangquoten."},{"word":"die Erholung","translation":"recovery","pronunciation":"dee er-HOH-loong","example":"Erholung der Bestände."},{"word":"überfischt","translation":"overfished","pronunciation":"ü-ber-FISHT","example":"Überfischte Bestände."},{"word":"strikt","translation":"strict","pronunciation":"shtrikt","example":"Strikte Maßnahmen."}]}',
'{"title":"Verursacht durch — caused by (participial attribute)","pattern":"verursacht durch + accusative = caused by (past participle as attribute)","explanation":"Verursacht durch + accusative = caused by (participial phrase). Die Versauerung, verursacht durch den erhöhten CO2-Gehalt = The acidification, caused by the increased CO2 content. This is an extended participial attribute (erweitertes Partizipialattribut) — a hallmark of formal/academic German. The participial phrase modifies the noun and stands between commas. It is the equivalent of a relative clause: die durch den CO2-Gehalt verursacht wird. Participial attributes are more compact.","examples":[{"sentence":"Die Überschwemmung, verursacht durch anhaltende Regenfälle, richtete erhebliche Schäden an.","translation":"The flooding, caused by persistent rainfall, caused considerable damage."},{"sentence":"Das Virus, verursacht durch eine unbekannte Mutation, breitete sich schnell aus.","translation":"The virus, caused by an unknown mutation, spread rapidly."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Versauerung'' means?","options":["acidification","souring","acidising","acidity"],"correctAnswer":"acidification"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Sustainable fisheries require strict catch quotas and the recovery of overfished stocks.","options":["Nachhaltige Fischerei erfordert strikte Fangquoten und die Erholung überfischter Bestände.","Für nachhaltige Fischerei braucht man Quoten und Schutz.","Fangquoten und Schutzmaßnahmen sichern die Fischerei.","Überfischung muss durch Quoten gestoppt werden."],"correctAnswer":"Nachhaltige Fischerei erfordert strikte Fangquoten und die Erholung überfischter Bestände."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Überschwemmung, verursacht durch anhaltende Regenfälle, richtete erhebliche Schäden ___.","options":["an","aus","ein","auf"],"correctAnswer":"an"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The virus caused by an unknown mutation spread rapidly","wordBankItems":["Das","Virus",",","verursacht","durch","eine","unbekannte","Mutation",",","breitete","sich","schnell","aus","."],"correctAnswer":"Das Virus , verursacht durch eine unbekannte Mutation , breitete sich schnell aus ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Überfischt'' means?","options":["overfished","over-caught","depleted","harvested out"],"correctAnswer":"overfished"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001df',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss world trade at B2","Use Welthandel vocabulary","Talk about trade policy and protectionism"],"explanation":{"intro":"World trade vocabulary covers trade policy, protectionism, and global supply chains at B2.","culturalNote":"Germany is a Exportweltmeister (export world champion) — 3rd largest exporter globally. Key concepts: Freihandel (free trade), Protektionismus (protectionism), WTO (Welthandelsorganisation), Zölle (tariffs), Handelsdefizit/-überschuss (trade deficit/surplus). Germany''s export surplus is controversial in the EU/US. Key challenge: Lieferkettenresilienz (supply chain resilience — COVID and Ukraine exposed vulnerabilities)."},"examples":[{"german":"Freihandelsabkommen zielen darauf ab, Zölle und nicht-tarifäre Handelshemmnisse abzubauen und so den gegenseitigen Marktzugang zu erleichtern.","english":"Free trade agreements aim to reduce tariffs and non-tariff trade barriers and thereby facilitate mutual market access."},{"german":"Die Corona-Pandemie hat erhebliche Schwachstellen in globalen Lieferketten aufgedeckt und Forderungen nach mehr Resilienz verstärkt.","english":"The coronavirus pandemic revealed significant weaknesses in global supply chains and reinforced calls for greater resilience."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss world trade, trade agreements, and supply chain resilience at B2."}}',
'{"items":[{"word":"das Handelshemmnis","translation":"trade barrier","pronunciation":"dahs HAN-dels-hem-nis","example":"Handelshemmnisse abbauen."},{"word":"abbauen","translation":"to reduce/dismantle","pronunciation":"AP-bow-en","example":"Hemmnisse abbauen."},{"word":"erleichtern","translation":"to facilitate","pronunciation":"er-LYKH-tern","example":"Den Marktzugang erleichtern."},{"word":"aufdecken","translation":"to reveal/uncover","pronunciation":"OWF-dek-en","example":"Schwachstellen aufdecken."},{"word":"die Schwachstelle","translation":"weakness/vulnerability","pronunciation":"dee SHVAKH-shtel-eh","example":"Schwachstellen in Lieferketten."},{"word":"verstärken","translation":"to reinforce/intensify","pronunciation":"fer-SHTER-ken","example":"Forderungen verstärken."}]}',
'{"title":"Aufdecken — to reveal, uncover, expose","pattern":"etwas aufdecken = to reveal, uncover, expose (separable — bring hidden things to light)","explanation":"Aufdecken (separable) = to reveal, uncover, expose. Die Pandemie hat Schwachstellen aufgedeckt = The pandemic revealed weaknesses. Perfect: hat aufgedeckt. Die Aufdeckung = revelation, exposure. Compare: enthüllen (to reveal/unveil — more dramatic, often scandals), bloßlegen (to lay bare/expose — more structural), ans Licht bringen (to bring to light — idiom). Aufdecken is neutral-analytical; enthüllen carries more scandal connotation.","examples":[{"sentence":"Die Prüfung deckte gravierende Mängel im System auf.","translation":"The audit uncovered serious deficiencies in the system."},{"sentence":"Investigativer Journalismus deckt Korruption und Missstände auf.","translation":"Investigative journalism uncovers corruption and abuses."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Handelshemmnis'' means?","options":["trade barrier","trade obstacle","market barrier","commercial impediment"],"correctAnswer":"trade barrier"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The coronavirus pandemic revealed significant weaknesses in global supply chains and reinforced calls for greater resilience.","options":["Die Corona-Pandemie hat erhebliche Schwachstellen in globalen Lieferketten aufgedeckt und Forderungen nach mehr Resilienz verstärkt.","COVID hat gezeigt, dass globale Lieferketten anfällig sind.","Die Pandemie hat Schwachstellen in Lieferketten sichtbar gemacht.","Durch COVID wurden Lieferkettenschwächen bekannt."],"correctAnswer":"Die Corona-Pandemie hat erhebliche Schwachstellen in globalen Lieferketten aufgedeckt und Forderungen nach mehr Resilienz verstärkt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Prüfung deckte gravierende Mängel im System ___.","options":["auf","an","aus","her"],"correctAnswer":"auf"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Investigative journalism uncovers corruption and abuses","wordBankItems":["Investigativer","Journalismus","deckt","Korruption","und","Missstände","auf","."],"correctAnswer":"Investigativer Journalismus deckt Korruption und Missstände auf ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Erleichtern'' means?","options":["to facilitate","to ease","to simplify","to make easier"],"correctAnswer":"to facilitate"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

-- Lesson 480: B2 Milestone 3 (xp:200, coins:100)
INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e0',1,'APPROVED','PUBLISHED',
'{"objectives":["Review B2 grammar and vocabulary patterns","Demonstrate mastery at lesson 480","Complete B2 Milestone 3"],"explanation":{"intro":"Glückwunsch! You have completed 80 more lessons at B2 — now at lesson 480. This milestone reviews key B2 structures introduced in lessons 461-480.","culturalNote":"At this stage you command a sophisticated B2 vocabulary across science, technology, philosophy, economics, and society. You can read German newspapers, academic texts, and professional documents with confidence. Key structures mastered: Je...desto, Trotz + Genitiv, participial attributes (verursacht durch), hinausgehen über, nicht nur...sondern auch with complex objects."},"examples":[{"german":"Je komplexer die gesellschaftlichen Herausforderungen, desto dringender ist die Notwendigkeit interdisziplinärer Lösungsansätze.","english":"The more complex the societal challenges, the more urgently needed are interdisciplinary approaches to solutions."},{"german":"Trotz aller Rückschläge haben sich die Reformbemühungen als nachhaltig wirksam erwiesen.","english":"Despite all setbacks, the reform efforts have proven to be lastingly effective."}],"rewards":{"xp":200,"coins":100},"metadata":{"estimatedMinutes":25,"canDo":"I can demonstrate mastery of complex B2 German across science, philosophy, and society — Milestone 3 complete!"}}',
'{"items":[{"word":"interdisziplinär","translation":"interdisciplinary","pronunciation":"in-ter-dis-tsi-pli-NÄR","example":"Interdisziplinäre Ansätze."},{"word":"dringend","translation":"urgent","pronunciation":"DRING-end","example":"Dringend notwendig."},{"word":"sich erweisen als","translation":"to prove to be","pronunciation":"zikh er-VY-zen als","example":"Sich als wirksam erweisen."},{"word":"nachhaltig wirksam","translation":"lastingly effective","pronunciation":"NAKH-hal-tikh VIR-zahm","example":"Nachhaltig wirksam."},{"word":"der Lösungsansatz","translation":"approach to solutions","pronunciation":"dayr LÖ-zoonks-an-zats","example":"Lösungsansätze."},{"word":"die Notwendigkeit","translation":"necessity/need","pronunciation":"dee NOHT-ven-dikh-kyt","example":"Notwendigkeit."}]}',
'{"title":"Sich erweisen als — to prove to be","pattern":"sich als + adjective/noun erweisen = to prove to be, turn out to be (based on evidence)","explanation":"Sich erweisen als + adjective/noun = to prove to be, turn out to be. Die Maßnahmen haben sich als wirksam erwiesen = The measures have proven to be effective. Perfect: hat sich erwiesen. Die Maßnahme erwies sich als Fehler = The measure proved to be a mistake. This is more evidence-based than sein (to be): erweisen implies that experience or facts confirm the characterisation. Compare: sich herausstellen als (to turn out to be — often a surprising revelation), sich zeigen als (to show oneself as).","examples":[{"sentence":"Die Investition erwies sich langfristig als rentabel.","translation":"The investment proved to be profitable in the long term."},{"sentence":"Seine Vorhersage hat sich als zutreffend erwiesen.","translation":"His prediction has proved to be accurate."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Interdisziplinär'' means?","options":["interdisciplinary","multidisciplinary","cross-disciplinary","inter-subject"],"correctAnswer":"interdisciplinary"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Despite all setbacks, the reform efforts have proven to be lastingly effective.","options":["Trotz aller Rückschläge haben sich die Reformbemühungen als nachhaltig wirksam erwiesen.","Die Reformen waren trotz Problemen erfolgreich.","Trotz Rückschlägen waren die Reformen wirksam.","Die Reformbemühungen haben sich bewährt."],"correctAnswer":"Trotz aller Rückschläge haben sich die Reformbemühungen als nachhaltig wirksam erwiesen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Investition erwies sich langfristig als ___.","options":["rentabel","profitabel","lohnenswert","gewinnbringend"],"correctAnswer":"rentabel"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: His prediction has proved to be accurate","wordBankItems":["Seine","Vorhersage","hat","sich","als","zutreffend","erwiesen","."],"correctAnswer":"Seine Vorhersage hat sich als zutreffend erwiesen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Sich erweisen als'' implies?","options":["evidence-based confirmation","simple identification","subjective assessment","prediction"],"correctAnswer":"evidence-based confirmation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-0000000001d7','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l471',471,'Wissenschaft und Forschung B2','Science and research B2','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001d8','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l472',472,'Medizin und Biotechnologie','Medicine and biotechnology','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001d9','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l473',473,'Raumfahrt','Space exploration','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001da','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l474',474,'Quantencomputing','Quantum computing','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001db','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l475',475,'Erneuerbare Energien B2','Renewables B2','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001dc','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l476',476,'Kreislaufwirtschaft','Circular economy','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001dd','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l477',477,'Biodiversität','Biodiversity','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001de','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l478',478,'Meere und Ozeane','Oceans','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001df','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l479',479,'Welthandel','World trade','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e0','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l480',480,'B2 Meilenstein 3','B2 milestone 3','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001d7' WHERE stable_ref = 'de-b2-u04-l471' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001d8' WHERE stable_ref = 'de-b2-u04-l472' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001d9' WHERE stable_ref = 'de-b2-u04-l473' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001da' WHERE stable_ref = 'de-b2-u04-l474' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001db' WHERE stable_ref = 'de-b2-u04-l475' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001dc' WHERE stable_ref = 'de-b2-u04-l476' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001dd' WHERE stable_ref = 'de-b2-u04-l477' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001de' WHERE stable_ref = 'de-b2-u04-l478' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001df' WHERE stable_ref = 'de-b2-u04-l479' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e0' WHERE stable_ref = 'de-b2-u04-l480' AND lesson_id IS NULL;
