-- V77: German B2 lessons 481-490 (B2 batch 8, 10 lessons)
-- Hex: 481=0x1e1, 490=0x1ea

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-0000000001e1','de-b2-l481','Geopolitik - Geopolitics','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e2','de-b2-l482','Europäische Union B2 - EU B2','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e3','de-b2-l483','Entwicklungspolitik - Development Policy','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e4','de-b2-l484','Migration und Asyl B2 - Migration','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e5','de-b2-l485','Religionsfreiheit - Religious Freedom','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e6','de-b2-l486','Kunst und Gesellschaft - Art','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e7','de-b2-l487','Literatur B2 - Literature','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e8','de-b2-l488','Musik und Kultur - Music','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001e9','de-b2-l489','Architektur B2 - Architecture','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001ea','de-b2-l490','Film und Kino - Cinema','language','de','B2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e1',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss geopolitics at B2","Use geopolitische vocabulary","Talk about power and global order"],"explanation":{"intro":"Geopolitics vocabulary covers power, spheres of influence, and global order at B2.","culturalNote":"Key geopolitical concepts: Mächtegleichgewicht (balance of power), Einflusssphären (spheres of influence), multipolares System (multipolar system), strategische Autonomie (strategic autonomy — EU concept). Key thinkers: Mackinder (Heartland), Brzezinski. Germany''s geopolitical position: central Europe, NATO eastern flank concerns, energy dependence (Russland/Russia), China relations (Systemwettbewerb — systemic competition)."},"examples":[{"german":"Die globale Machtverschiebung hin zu einem multipolaren System stellt die auf dem Westen basierende Nachkriegsordnung grundlegend in Frage.","english":"The global power shift towards a multipolar system fundamentally calls into question the post-war order based on the West."},{"german":"Energiesicherheit ist zu einem zentralen geopolitischen Thema geworden, seit Russlands Invasion der Ukraine die europäische Versorgungsabhängigkeit offenbart hat.","english":"Energy security has become a central geopolitical issue since Russia''s invasion of Ukraine revealed Europe''s supply dependence."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss geopolitics, power shifts, and the global order at B2."}}',
'{"items":[{"word":"die Machtverschiebung","translation":"power shift","pronunciation":"dee MAKHT-fer-shee-boong","example":"Globale Machtverschiebung."},{"word":"multipolar","translation":"multipolar","pronunciation":"mool-tee-po-LAR","example":"Multipolares System."},{"word":"offenbaren","translation":"to reveal","pronunciation":"OF-fen-bah-ren","example":"Abhängigkeit offenbaren."},{"word":"die Versorgungsabhängigkeit","translation":"supply dependence","pronunciation":"dee fer-ZOR-goonks-ap-heng-ikh-kyt","example":"Versorgungsabhängigkeit."},{"word":"die Nachkriegsordnung","translation":"post-war order","pronunciation":"dee NAKH-kreeg-zord-noong","example":"Nachkriegsordnung."},{"word":"zentral","translation":"central","pronunciation":"tsen-TRAHL","example":"Zentrales Thema."}]}',
'{"title":"Zu etwas werden — to become something","pattern":"etwas ist zu X geworden = something has become X (change of state — perfect)","explanation":"Zu + noun/adjective + werden = to become. Energiesicherheit ist zu einem zentralen Thema geworden = Energy security has become a central issue. This marks a change of state. Perfect: ist geworden (sein-verb). Compare: werden (simple future/change). The zu + dative construction (zu einem Thema werden) is standard for becoming something countable. Sich entwickeln zu (to develop into) is more gradual. Werden + adjective (Es wurde wichtig = It became important) for adjectives without article.","examples":[{"sentence":"Die Stadt ist zu einem wichtigen Wirtschaftsstandort geworden.","translation":"The city has become an important economic location."},{"sentence":"Klimaschutz ist zu einer Frage der nationalen Sicherheit geworden.","translation":"Climate protection has become a matter of national security."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Machtverschiebung'' means?","options":["power shift","power change","power move","political shift"],"correctAnswer":"power shift"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Energy security has become a central geopolitical issue since Russia''s invasion of Ukraine revealed Europe''s supply dependence.","options":["Energiesicherheit ist zu einem zentralen geopolitischen Thema geworden, seit Russlands Invasion der Ukraine die europäische Versorgungsabhängigkeit offenbart hat.","Energieversorgung ist seit dem Ukraine-Krieg ein Problem.","Russland hat Europas Energieabhängigkeit aufgezeigt.","Energiesicherheit ist wichtig für Europa."],"correctAnswer":"Energiesicherheit ist zu einem zentralen geopolitischen Thema geworden, seit Russlands Invasion der Ukraine die europäische Versorgungsabhängigkeit offenbart hat."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Stadt ist zu einem wichtigen Wirtschaftsstandort ___.","options":["geworden","gemacht worden","gemacht","entwickelt"],"correctAnswer":"geworden"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Climate protection has become a matter of national security","wordBankItems":["Klimaschutz","ist","zu","einer","Frage","der","nationalen","Sicherheit","geworden","."],"correctAnswer":"Klimaschutz ist zu einer Frage der nationalen Sicherheit geworden ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Offenbaren'' means?","options":["to reveal","to uncover","to disclose","to show"],"correctAnswer":"to reveal"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e2',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss the EU at B2","Use EU vocabulary","Talk about integration and sovereignty"],"explanation":{"intro":"EU vocabulary covers integration, sovereignty, and EU institutions at B2.","culturalNote":"Germany is the EU''s largest economy and a founding member. Key EU concepts: Subsidiaritätsprinzip (subsidiarity — decisions at lowest possible level), Souveränitätsübertragung (transfer of sovereignty), Demokratiedefizit (democratic deficit — EU legitimacy debate), Erweiterungspolitik (enlargement policy). Key institutions: Europäischer Rat, Rat der EU, Europäisches Parlament, Europäische Kommission, EuGH (Court of Justice)."},"examples":[{"german":"Das Subsidiaritätsprinzip bestimmt, dass Entscheidungen auf der niedrigstmöglichen Ebene getroffen werden sollen.","english":"The subsidiarity principle stipulates that decisions should be taken at the lowest possible level."},{"german":"Die Vertiefung der europäischen Integration steht in einem Spannungsverhältnis zur Wahrung nationaler Souveränität.","english":"The deepening of European integration is in tension with the preservation of national sovereignty."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss EU integration, subsidiarity, and sovereignty at B2."}}',
'{"items":[{"word":"das Subsidiaritätsprinzip","translation":"subsidiarity principle","pronunciation":"dahs zoop-zi-dee-ah-ri-TÄTS-prin-tsip","example":"Subsidiaritätsprinzip."},{"word":"bestimmen","translation":"to stipulate/determine","pronunciation":"beh-SHTIM-en","example":"Das Prinzip bestimmt."},{"word":"die Vertiefung","translation":"deepening","pronunciation":"dee fer-TEE-foong","example":"Vertiefung der Integration."},{"word":"die Wahrung","translation":"preservation/safeguarding","pronunciation":"dee VAH-roong","example":"Wahrung der Souveränität."},{"word":"die Souveränität","translation":"sovereignty","pronunciation":"dee zo-veh-rä-ni-TÄT","example":"Nationale Souveränität."},{"word":"niedrigstmöglich","translation":"lowest possible","pronunciation":"NEE-drikh-st-mög-likh","example":"Niedrigstmögliche Ebene."}]}',
'{"title":"Bestimmen, dass — to stipulate that","pattern":"etwas bestimmt, dass + V-final = something stipulates/lays down that (normative rule-setting)","explanation":"Bestimmen dass = to stipulate, lay down, determine that. Das Gesetz bestimmt, dass... = The law stipulates that... Used for rules, laws, principles, and agreements. Also: bestimmt sein für (to be intended/destined for), bestimmt sein durch (to be determined by). Compare: vorschreiben (to prescribe/mandate — stronger obligation), festlegen (to set/establish), verlangen (to require/demand — more personal). Bestimmt as adjective = definite/certain (ein bestimmter Artikel = definite article).","examples":[{"sentence":"Der Vertrag bestimmt, dass alle Parteien monatlich Bericht erstatten.","translation":"The contract stipulates that all parties report monthly."},{"sentence":"Das Grundgesetz bestimmt, dass die Würde des Menschen unantastbar ist.","translation":"The Basic Law stipulates that human dignity is inviolable."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Vertiefung'' means?","options":["deepening","intensification","strengthening","development"],"correctAnswer":"deepening"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The subsidiarity principle stipulates that decisions should be taken at the lowest possible level.","options":["Das Subsidiaritätsprinzip bestimmt, dass Entscheidungen auf der niedrigstmöglichen Ebene getroffen werden sollen.","Subsidiarität bedeutet dezentrale Entscheidungsfindung.","Das Prinzip der Subsidiarität schützt nationale Entscheidungsrechte.","Entscheidungen sollen möglichst lokal getroffen werden."],"correctAnswer":"Das Subsidiaritätsprinzip bestimmt, dass Entscheidungen auf der niedrigstmöglichen Ebene getroffen werden sollen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Grundgesetz bestimmt, dass die Würde des Menschen ___ ist.","options":["unantastbar","unantastbar sei","unberührbar","heilig"],"correctAnswer":"unantastbar"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The contract stipulates that all parties report monthly","wordBankItems":["Der","Vertrag","bestimmt",",","dass","alle","Parteien","monatlich","Bericht","erstatten","."],"correctAnswer":"Der Vertrag bestimmt , dass alle Parteien monatlich Bericht erstatten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Wahrung'' means?","options":["preservation/safeguarding","protection","maintaining","upholding"],"correctAnswer":"preservation/safeguarding"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e3',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss development policy at B2","Use Entwicklungspolitik vocabulary","Talk about aid and sustainability"],"explanation":{"intro":"Development policy vocabulary covers aid, sustainable development, and global inequality at B2.","culturalNote":"Germany is one of the world''s largest donors of Entwicklungshilfe (development aid — ODA: official development assistance). BMZ (Bundesministerium für wirtschaftliche Zusammenarbeit und Entwicklung). Key concepts: SDGs (Nachhaltigkeitsziele — Sustainable Development Goals), Ownership-Prinzip (local ownership of development), Post-Kolonialismus debate in Entwicklungszusammenarbeit. GIZ (Deutsche Gesellschaft für Internationale Zusammenarbeit) implements projects."},"examples":[{"german":"Nachhaltige Entwicklung erfordert die gleichzeitige Berücksichtigung ökonomischer, sozialer und ökologischer Dimensionen.","english":"Sustainable development requires the simultaneous consideration of economic, social, and ecological dimensions."},{"german":"Wirksame Entwicklungszusammenarbeit setzt das Ownership-Prinzip voraus, wonach Partnerländer ihre eigene Entwicklungsagenda bestimmen.","english":"Effective development cooperation presupposes the ownership principle, according to which partner countries determine their own development agenda."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss development policy, SDGs, and international cooperation at B2."}}',
'{"items":[{"word":"gleichzeitig","translation":"simultaneous","pronunciation":"GLYKH-tsy-tikh","example":"Gleichzeitige Berücksichtigung."},{"word":"die Berücksichtigung","translation":"consideration/taking into account","pronunciation":"dee beh-RÜK-zikh-tee-goong","example":"Berücksichtigung aller Dimensionen."},{"word":"wirksam","translation":"effective","pronunciation":"VIRK-zahm","example":"Wirksame Zusammenarbeit."},{"word":"wonach","translation":"according to which","pronunciation":"vo-NAKH","example":"Wonach Partnerländer."},{"word":"die Agenda","translation":"agenda","pronunciation":"dee ah-GEN-dah","example":"Entwicklungsagenda."},{"word":"die Entwicklungszusammenarbeit","translation":"development cooperation","pronunciation":"dee ent-VIK-loonks-tsoo-ZAM-en-ar-byt","example":"Entwicklungszusammenarbeit."}]}',
'{"title":"Wonach — according to which (relative adverb)","pattern":"wonach = according to which (connects a relative clause to a preceding noun or principle)","explanation":"Wonach = according to which, after which, in accordance with which. Das Prinzip, wonach Länder ihre Agenda bestimmen = The principle according to which countries determine their agenda. Wonach is a pronominal adverb (W-word + preposition fused): wonach = nach + dem/der/denen. Similar: wobei (in the process of which), wodurch (through which), woraufhin (following which — result). These are key for B2 relative clause variety in formal writing.","examples":[{"sentence":"Das Abkommen, wonach beide Seiten auf Zölle verzichten, tritt nächsten Monat in Kraft.","translation":"The agreement, according to which both sides waive tariffs, enters into force next month."},{"sentence":"Es gibt klare Regeln, wonach solche Entscheidungen getroffen werden müssen.","translation":"There are clear rules according to which such decisions must be taken."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Gleichzeitig'' means?","options":["simultaneous","at the same time","concurrent","parallel"],"correctAnswer":"simultaneous"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Sustainable development requires the simultaneous consideration of economic, social, and ecological dimensions.","options":["Nachhaltige Entwicklung erfordert die gleichzeitige Berücksichtigung ökonomischer, sozialer und ökologischer Dimensionen.","Nachhaltige Entwicklung verbindet Wirtschaft, Soziales und Ökologie.","Alle drei Dimensionen müssen bei nachhaltiger Entwicklung beachtet werden.","Nachhaltige Entwicklung ist mehrdimensional."],"correctAnswer":"Nachhaltige Entwicklung erfordert die gleichzeitige Berücksichtigung ökonomischer, sozialer und ökologischer Dimensionen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Abkommen, wonach beide Seiten auf Zölle verzichten, tritt nächsten Monat in ___.","options":["Kraft","Wirkung","Geltung","Funktion"],"correctAnswer":"Kraft"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: There are clear rules according to which such decisions must be taken","wordBankItems":["Es","gibt","klare","Regeln",",","wonach","solche","Entscheidungen","getroffen","werden","müssen","."],"correctAnswer":"Es gibt klare Regeln , wonach solche Entscheidungen getroffen werden müssen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Wirksam'' means?","options":["effective","working","powerful","efficient"],"correctAnswer":"effective"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e4',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss migration and asylum at B2","Use Migration vocabulary","Talk about refugee law and integration"],"explanation":{"intro":"Migration and asylum vocabulary covers refugee law, integration, and policy debates at B2.","culturalNote":"Germany received ~1.2 million asylum seekers in 2015-16 (Flüchtlingskrise). Key legal concepts: Asylrecht (Art. 16a GG — right to asylum), Genfer Flüchtlingskonvention (Geneva Refugee Convention), subsidiärer Schutz (subsidiary protection), Kettenduldung (tolerated stay in chain). Key policy: Integrationsgesetz (Integration Act), Fachkräfteeinwanderungsgesetz (Skilled Workers Immigration Act 2020). Leitkultur vs. multikulturelle Gesellschaft debate ongoing."},"examples":[{"german":"Das Recht auf Asyl schützt Menschen vor politischer Verfolgung, nicht jedoch vor wirtschaftlicher Not oder allgemeiner Armut.","english":"The right to asylum protects people from political persecution, but not from economic hardship or general poverty."},{"german":"Gelungene Integration setzt sowohl Anpassungsbereitschaft der Zugewanderten als auch Aufnahmebereitschaft der Aufnahmegesellschaft voraus.","english":"Successful integration presupposes both the willingness to adapt on the part of immigrants and the willingness to receive on the part of the host society."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss migration, asylum law, and integration at B2."}}',
'{"items":[{"word":"die Verfolgung","translation":"persecution","pronunciation":"dee fer-FOL-goong","example":"Politische Verfolgung."},{"word":"die Aufnahmebereitschaft","translation":"willingness to receive","pronunciation":"dee OWF-nah-meh-beh-ryt-shaft","example":"Aufnahmebereitschaft."},{"word":"die Anpassungsbereitschaft","translation":"willingness to adapt","pronunciation":"dee AN-pas-oonks-beh-ryt-shaft","example":"Anpassungsbereitschaft."},{"word":"zugewandert","translation":"immigrant (adj.)","pronunciation":"TSOO-geh-van-dert","example":"Zugewanderte Menschen."},{"word":"gelungen","translation":"successful (past participle as adj.)","pronunciation":"geh-LOONG-en","example":"Gelungene Integration."},{"word":"sowohl...als auch","translation":"both...and","pronunciation":"zo-VOL...als owkh","example":"Sowohl X als auch Y."}]}',
'{"title":"Sowohl...als auch — both...and (comprehensive inclusion)","pattern":"sowohl X als auch Y = both X and Y (includes both elements completely)","explanation":"Sowohl...als auch = both X and Y. Setzt sowohl Anpassungsbereitschaft als auch Aufnahmebereitschaft voraus = presupposes both willingness to adapt and willingness to receive. Unlike nicht nur...sondern auch (not only...but also — additive surprise), sowohl...als auch is neutral comprehensive inclusion: both elements are equally required. Both elements get normal case based on context.","examples":[{"sentence":"Das Projekt erfordert sowohl technisches Wissen als auch soziale Kompetenzen.","translation":"The project requires both technical knowledge and social skills."},{"sentence":"Sowohl die Regierung als auch die Opposition stimmten für das Gesetz.","translation":"Both the government and the opposition voted for the law."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Verfolgung'' means?","options":["persecution","pursuit","prosecution","tracking"],"correctAnswer":"persecution"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Successful integration presupposes both the willingness to adapt on the part of immigrants and the willingness to receive on the part of the host society.","options":["Gelungene Integration setzt sowohl Anpassungsbereitschaft der Zugewanderten als auch Aufnahmebereitschaft der Aufnahmegesellschaft voraus.","Integration braucht Anpassung und Aufnahmebereitschaft.","Sowohl Zugewanderte als auch die Gesellschaft müssen beitragen.","Integration gelingt nur mit gegenseitigem Engagement."],"correctAnswer":"Gelungene Integration setzt sowohl Anpassungsbereitschaft der Zugewanderten als auch Aufnahmebereitschaft der Aufnahmegesellschaft voraus."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Projekt erfordert sowohl technisches Wissen ___ auch soziale Kompetenzen.","options":["als","wie","und","sowie"],"correctAnswer":"als"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Both the government and the opposition voted for the law","wordBankItems":["Sowohl","die","Regierung","als","auch","die","Opposition","stimmten","für","das","Gesetz","."],"correctAnswer":"Sowohl die Regierung als auch die Opposition stimmten für das Gesetz ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Gelungen'' as adjective means?","options":["successful","accomplished","achieved","completed"],"correctAnswer":"successful"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e5',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss religious freedom at B2","Use Religionsfreiheit vocabulary","Talk about secularism and religion in society"],"explanation":{"intro":"Religious freedom vocabulary covers secularism, church-state relations, and religious rights at B2.","culturalNote":"Germany has religious freedom (Art. 4 GG). Unique: Kirchensteuer (church tax — collected by state for registered churches). Key concepts: positive Religionsfreiheit (freedom to practice religion), negative Religionsfreiheit (freedom from religion), Laizismus (laicism — strict separation), Staatskirchenrecht (church-state law — Germany''s cooperative model). Größte Religionsgruppen: Catholicism, Protestantism, Islam."},"examples":[{"german":"Religionsfreiheit umfasst sowohl das Recht, eine Religion zu bekennen und auszuüben, als auch das Recht, keiner Religion anzugehören.","english":"Religious freedom encompasses both the right to profess and practise a religion and the right not to belong to any religion."},{"german":"In pluralistischen Gesellschaften steht der Staat vor der Herausforderung, religiöse Vielfalt mit einem gemeinsamen Werterahmen in Einklang zu bringen.","english":"In pluralist societies, the state faces the challenge of reconciling religious diversity with a common value framework."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss religious freedom, secularism, and church-state relations at B2."}}',
'{"items":[{"word":"umfassen","translation":"to encompass/include","pronunciation":"oom-FAS-en","example":"Religionsfreiheit umfasst."},{"word":"bekennen","translation":"to profess/confess","pronunciation":"beh-KEN-en","example":"Eine Religion bekennen."},{"word":"angehören","translation":"to belong to","pronunciation":"AN-geh-hö-ren","example":"Einer Religion angehören."},{"word":"pluralistisch","translation":"pluralist","pronunciation":"ploo-rah-LIS-tish","example":"Pluralistische Gesellschaft."},{"word":"der Werterahmen","translation":"value framework","pronunciation":"dayr VER-teh-rah-men","example":"Gemeinsamer Werterahmen."},{"word":"religiös","translation":"religious","pronunciation":"reh-li-gee-ÖS","example":"Religiöse Vielfalt."}]}',
'{"title":"Umfassen — to encompass, include, comprise","pattern":"etwas umfasst X = something encompasses/includes X (non-separable — formal scope statement)","explanation":"Umfassen (non-separable) = to encompass, include, comprise. Religionsfreiheit umfasst sowohl...als auch = Religious freedom encompasses both...and. Perfect: hat umfasst. Compare: beinhalten (to include/contain — often for documents, contracts), einschließen (to include — often lists), abdecken (to cover — more about coverage of topics). Umfassen suggests the full scope of a concept or right.","examples":[{"sentence":"Das Paket umfasst Unterkunft, Verpflegung und Transfer.","translation":"The package encompasses accommodation, meals, and transfer."},{"sentence":"Der Begriff ''Wohlbefinden'' umfasst physische, psychische und soziale Aspekte.","translation":"The term ''well-being'' encompasses physical, psychological, and social aspects."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Bekennen'' means?","options":["to profess/confess","to acknowledge","to declare","to affirm"],"correctAnswer":"to profess/confess"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Religious freedom encompasses both the right to profess and practise a religion and the right not to belong to any religion.","options":["Religionsfreiheit umfasst sowohl das Recht, eine Religion zu bekennen und auszuüben, als auch das Recht, keiner Religion anzugehören.","Religionsfreiheit bedeutet, man kann eine Religion haben oder nicht.","Man hat das Recht auf Religion und das Recht, ohne Religion zu leben.","Religionsfreiheit schützt sowohl Gläubige als auch Atheisten."],"correctAnswer":"Religionsfreiheit umfasst sowohl das Recht, eine Religion zu bekennen und auszuüben, als auch das Recht, keiner Religion anzugehören."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Paket umfasst Unterkunft, Verpflegung und ___.","options":["Transfer","Beförderung","Transport","Reise"],"correctAnswer":"Transfer"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The term well-being encompasses physical psychological and social aspects","wordBankItems":["Der","Begriff","Wohlbefinden","umfasst","physische",",","psychische","und","soziale","Aspekte","."],"correctAnswer":"Der Begriff Wohlbefinden umfasst physische , psychische und soziale Aspekte ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Pluralistisch'' means?","options":["pluralist","diverse","varied","multicultural"],"correctAnswer":"pluralist"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e6',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss art and society at B2","Use Kunst vocabulary","Talk about art funding and cultural policy"],"explanation":{"intro":"Art and society vocabulary covers cultural policy, art funding, and the social role of art at B2.","culturalNote":"Germany has generous Kulturförderung (cultural funding): Bundesministerium für Kultur, Länder and Kommunen fund theatres, museums, opera houses. Key concepts: Kulturauftrag (cultural mandate — public duty to support culture), Kunstfreiheit (freedom of art — Art. 5 GG), öffentliche Kulturfinanzierung (public cultural financing). Germany has the highest density of theatres and museums in the world (per capita). Documenta (Kassel) every 5 years."},"examples":[{"german":"Kunst hat die gesellschaftliche Funktion, herrschende Normen und Werte zu reflektieren, zu hinterfragen und gegebenenfalls in Frage zu stellen.","english":"Art has the social function of reflecting, questioning, and if necessary calling into question dominant norms and values."},{"german":"Öffentliche Kulturförderung legitimiert sich durch den gesellschaftlichen Mehrwert, den Kunst und Kultur für das soziale Miteinander erzeugen.","english":"Public cultural funding legitimises itself through the social added value that art and culture generate for social cohesion."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss art, cultural policy, and the social role of art at B2."}}',
'{"items":[{"word":"herrschend","translation":"dominant/prevailing","pronunciation":"HER-shend","example":"Herrschende Normen."},{"word":"reflektieren","translation":"to reflect","pronunciation":"reh-flek-TEER-en","example":"Normen reflektieren."},{"word":"gegebenenfalls","translation":"if necessary/where applicable","pronunciation":"geh-GAY-be-nen-fals","example":"Gegebenenfalls in Frage stellen."},{"word":"der Mehrwert","translation":"added value","pronunciation":"dayr MAYR-vert","example":"Gesellschaftlicher Mehrwert."},{"word":"legitimieren","translation":"to legitimise","pronunciation":"leh-gi-ti-MEER-en","example":"Förderung legitimieren."},{"word":"das Miteinander","translation":"social cohesion/living together","pronunciation":"dahs MIT-yn-an-der","example":"Soziales Miteinander."}]}',
'{"title":"Sich legitimieren durch — to legitimise itself through","pattern":"sich legitimieren durch + accusative = to legitimise itself/oneself through (reflexive — self-justification)","explanation":"Sich legitimieren durch = to legitimise itself through, to justify itself by. Öffentliche Förderung legitimiert sich durch den Mehrwert = Public funding legitimises itself through added value. The reflexive legitimiert sich implies self-justification — the entity itself provides its own grounds for existing. Compare: rechtfertigen (to justify — often actions/decisions), begründen mit (to justify with/ground in — reasons), sich bewähren (to prove its worth — through performance).","examples":[{"sentence":"Ein staatlicher Eingriff legitimiert sich durch den Schutz des öffentlichen Interesses.","translation":"A state intervention legitimises itself through the protection of the public interest."},{"sentence":"Das Programm hat sich durch seine nachweisbaren Ergebnisse legitimiert.","translation":"The programme has legitimised itself through its demonstrable results."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Herrschend'' means?","options":["dominant/prevailing","ruling","governing","leading"],"correctAnswer":"dominant/prevailing"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Art has the social function of reflecting, questioning, and if necessary calling into question dominant norms and values.","options":["Kunst hat die gesellschaftliche Funktion, herrschende Normen und Werte zu reflektieren, zu hinterfragen und gegebenenfalls in Frage zu stellen.","Kunst spiegelt gesellschaftliche Normen wider.","Kunst reflektiert und hinterfragt die Gesellschaft.","Die gesellschaftliche Funktion der Kunst ist Reflexion."],"correctAnswer":"Kunst hat die gesellschaftliche Funktion, herrschende Normen und Werte zu reflektieren, zu hinterfragen und gegebenenfalls in Frage zu stellen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ein staatlicher Eingriff legitimiert sich durch den Schutz des öffentlichen ___.","options":["Interesses","Wohls","Nutzens","Gutes"],"correctAnswer":"Interesses"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The programme has legitimised itself through its demonstrable results","wordBankItems":["Das","Programm","hat","sich","durch","seine","nachweisbaren","Ergebnisse","legitimiert","."],"correctAnswer":"Das Programm hat sich durch seine nachweisbaren Ergebnisse legitimiert ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Gegebenenfalls'' means?","options":["if necessary/where applicable","possibly","optionally","under certain conditions"],"correctAnswer":"if necessary/where applicable"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e7',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss literature at B2","Use Literatur vocabulary","Talk about German literary tradition"],"explanation":{"intro":"Literature vocabulary covers German literary tradition, analysis, and contemporary writing at B2.","culturalNote":"Key German literary movements: Klassik (Goethe, Schiller), Romantik (Novalis, E.T.A. Hoffmann), Naturalismus, Expressionismus, Neue Sachlichkeit, Exilliteratur (exile literature — Mann, Brecht). Nobel Prize winners: Thomas Mann, Günter Grass, Herta Müller. Key works: Faust (Goethe), Die Blechtrommel (Grass), Der Prozess (Kafka — Austrian). Contemporary: Juli Zeh, Daniel Kehlmann."},"examples":[{"german":"Literatur spiegelt die gesellschaftlichen Verhältnisse ihrer Entstehungszeit wider und bietet gleichzeitig eine überzeitliche Reflexion des Menschlichen.","english":"Literature reflects the social conditions of its time of origin and simultaneously offers a timeless reflection on the human condition."},{"german":"Die Intertextualität verbindet literarische Werke miteinander und macht Lesen zu einem Dialog zwischen Texten über Epochen hinweg.","english":"Intertextuality connects literary works to one another and makes reading into a dialogue between texts across epochs."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss literature, literary analysis, and the German literary tradition at B2."}}',
'{"items":[{"word":"widerspiegeln","translation":"to reflect/mirror","pronunciation":"VEE-der-shpee-geln","example":"Gesellschaftliche Verhältnisse widerspiegeln."},{"word":"überzeitlich","translation":"timeless","pronunciation":"ü-ber-TSYT-likh","example":"Überzeitliche Reflexion."},{"word":"die Intertextualität","translation":"intertextuality","pronunciation":"dee in-ter-teks-too-ah-li-TÄT","example":"Intertextualität."},{"word":"die Epochе","translation":"epoch/era","pronunciation":"dee eh-POH-kheh","example":"Über Epochen hinweg."},{"word":"hinweg","translation":"across/beyond (temporal/spatial)","pronunciation":"hin-VEK","example":"Über Epochen hinweg."},{"word":"die Entstehungszeit","translation":"time of origin","pronunciation":"dee ent-SHTAY-oonks-tsyt","example":"Entstehungszeit."}]}',
'{"title":"Über...hinweg — across, beyond (temporal/spatial obstacle)","pattern":"über + accusative + hinweg = across, spanning, beyond (overcoming a span or obstacle)","explanation":"Über X hinweg = across X, spanning X, beyond X. Über Epochen hinweg = across/spanning epochs. Over generations: über Generationen hinweg. Over disagreements: über Differenzen hinweg. The construction marks something that spans or overcomes a distance, period, or obstacle. Hinwegkommen über (to get over) is the verb form. Compare: durch (through — more physical passage), im Laufe (over the course of — temporal progression).","examples":[{"sentence":"Die Freundschaft hielt über Jahrzehnte und große Entfernungen hinweg.","translation":"The friendship held across decades and great distances."},{"sentence":"Über politische Differenzen hinweg gelang eine Einigung.","translation":"Despite political differences, an agreement was reached."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Überzeitlich'' means?","options":["timeless","eternal","universal","enduring"],"correctAnswer":"timeless"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Literature reflects the social conditions of its time of origin and simultaneously offers a timeless reflection on the human condition.","options":["Literatur spiegelt die gesellschaftlichen Verhältnisse ihrer Entstehungszeit wider und bietet gleichzeitig eine überzeitliche Reflexion des Menschlichen.","Literatur zeigt, wie die Gesellschaft zu ihrer Zeit aussah.","Gute Literatur ist zeitlos und gesellschaftlich relevant.","Literatur verbindet zeithistorische Dokumentation mit universellen Themen."],"correctAnswer":"Literatur spiegelt die gesellschaftlichen Verhältnisse ihrer Entstehungszeit wider und bietet gleichzeitig eine überzeitliche Reflexion des Menschlichen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Freundschaft hielt über Jahrzehnte und große Entfernungen ___.","options":["hinweg","hinaus","hinüber","voran"],"correctAnswer":"hinweg"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Despite political differences an agreement was reached","wordBankItems":["Über","politische","Differenzen","hinweg","gelang","eine","Einigung","."],"correctAnswer":"Über politische Differenzen hinweg gelang eine Einigung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Entstehungszeit'' means?","options":["time of origin","creation time","historical period","founding period"],"correctAnswer":"time of origin"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e8',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss music and culture at B2","Use Musik vocabulary","Talk about German musical tradition"],"explanation":{"intro":"Music vocabulary covers German musical tradition, genres, and the music industry at B2.","culturalNote":"Germany has an extraordinary classical music tradition: Bach, Beethoven, Brahms, Bruckner, Wagner, Strauss. Key institutions: Berliner Philharmoniker (world-leading orchestra), Bayreuther Festspiele (Wagner festival). Contemporary: Kraftwerk (pioneers of electronic music), Rammstein, German pop (Schlager). Musikerziehung (music education) is compulsory in schools. Germany has the largest music market in Europe (Musikwirtschaft)."},"examples":[{"german":"Die Berliner Philharmoniker gelten als eines der renommiertesten Orchester der Welt und sind Botschafter deutschen Kulturerbes.","english":"The Berlin Philharmonic is regarded as one of the most prestigious orchestras in the world and is an ambassador of German cultural heritage."},{"german":"Musikstreaming hat die Geschäftsmodelle der Musikindustrie grundlegend verändert und neue Fragen über Vergütung und geistiges Eigentum aufgeworfen.","english":"Music streaming has fundamentally changed the business models of the music industry and raised new questions about remuneration and intellectual property."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss music, German musical heritage, and the music industry at B2."}}',
'{"items":[{"word":"renommiert","translation":"prestigious/renowned","pronunciation":"reh-no-MEERT","example":"Renommiertes Orchester."},{"word":"das Kulturerbe","translation":"cultural heritage","pronunciation":"dahs kool-TOOR-er-beh","example":"Deutsches Kulturerbe."},{"word":"die Vergütung","translation":"remuneration","pronunciation":"dee fer-GÜ-toong","example":"Vergütung der Künstler."},{"word":"das geistige Eigentum","translation":"intellectual property","pronunciation":"dahs GYS-ti-geh EY-gen-toom","example":"Geistiges Eigentum."},{"word":"der Botschafter","translation":"ambassador","pronunciation":"dayr BOT-shaf-ter","example":"Kulturbotschafter."},{"word":"grundlegend verändern","translation":"to fundamentally change","pronunciation":"GROONT-lay-gend fer-EN-dern","example":"Grundlegend verändert."}]}',
'{"title":"Gelten als + superlative — regarded as one of the most","pattern":"als eines der/eine der/ein(s) der + superlative = as one of the most (partitive superlative)","explanation":"Als eines der renommiertesten = as one of the most prestigious (partitive superlative). Structure: als + ein(e/s) der + superlative adjective + plural noun. Die Berliner Philharmoniker gelten als eines der renommiertesten Orchester = are regarded as one of the most prestigious orchestras. Note: eines der (genitive plural) because Orchester is plural. This construction is very common in formal German for comparative ranking. Eines der wichtigsten Probleme = one of the most important problems.","examples":[{"sentence":"Berlin gilt als eine der kreativsten Städte Europas.","translation":"Berlin is regarded as one of the most creative cities in Europe."},{"sentence":"Das ist eines der größten Probleme unserer Zeit.","translation":"That is one of the greatest problems of our time."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Renommiert'' means?","options":["prestigious/renowned","famous","well-known","respected"],"correctAnswer":"prestigious/renowned"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The Berlin Philharmonic is regarded as one of the most prestigious orchestras in the world and is an ambassador of German cultural heritage.","options":["Die Berliner Philharmoniker gelten als eines der renommiertesten Orchester der Welt und sind Botschafter deutschen Kulturerbes.","Die Berliner Philharmoniker sind weltberühmt.","Das Berliner Orchester ist das beste der Welt.","Die Berliner Philharmoniker vertreten deutsches Kulturerbe."],"correctAnswer":"Die Berliner Philharmoniker gelten als eines der renommiertesten Orchester der Welt und sind Botschafter deutschen Kulturerbes."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Berlin gilt als eine der kreativsten Städte ___.","options":["Europas","von Europa","in Europa","Europas größten"],"correctAnswer":"Europas"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: That is one of the greatest problems of our time","wordBankItems":["Das","ist","eines","der","größten","Probleme","unserer","Zeit","."],"correctAnswer":"Das ist eines der größten Probleme unserer Zeit ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Kulturerbe'' means?","options":["cultural heritage","cultural legacy","cultural property","cultural tradition"],"correctAnswer":"cultural heritage"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001e9',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss architecture at B2","Use Architektur vocabulary","Talk about design and urban space"],"explanation":{"intro":"Architecture vocabulary covers design, urban planning, and architectural heritage at B2.","culturalNote":"Germany has a rich architectural heritage. Key styles: Romanik, Gotik, Barock, Klassizismus, Jugendstil, Bauhaus (Dessau/Weimar — hugely influential globally), Brutalismus, Dekon struktivismus. Key architects: Mies van der Rohe, Walter Gropius (Bauhaus founders), Norman Foster (Reichstag dome). Key concepts: Funktionalismus (form follows function), Nachhaltiges Bauen (sustainable building), Barrierefreiheit (accessibility)."},"examples":[{"german":"Das Bauhaus revolutionierte die Architektur des 20. Jahrhunderts durch die Verbindung von Kunst, Handwerk und industrieller Fertigung.","english":"The Bauhaus revolutionised 20th-century architecture through the fusion of art, craft, and industrial production."},{"german":"Zeitgenössische Architektur steht vor der Herausforderung, ästhetische Ansprüche mit Energieeffizienz und Barrierefreiheit zu vereinbaren.","english":"Contemporary architecture faces the challenge of reconciling aesthetic demands with energy efficiency and accessibility."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss architecture, design movements, and urban planning at B2."}}',
'{"items":[{"word":"revolutionieren","translation":"to revolutionise","pronunciation":"reh-vo-loo-tsyo-NEER-en","example":"Die Architektur revolutionieren."},{"word":"die Fertigung","translation":"production/manufacturing","pronunciation":"dee FER-ti-goong","example":"Industrielle Fertigung."},{"word":"zeitgenössisch","translation":"contemporary","pronunciation":"TSYT-geh-nö-sish","example":"Zeitgenössische Architektur."},{"word":"der Anspruch","translation":"demand/standard/claim","pronunciation":"dayr AN-shprookh","example":"Ästhetische Ansprüche."},{"word":"die Barrierefreiheit","translation":"accessibility","pronunciation":"dee bah-ree-EH-reh-fry-hyt","example":"Barrierefreiheit."},{"word":"vereinbaren","translation":"to reconcile/combine","pronunciation":"fer-YN-bah-ren","example":"Ästhetik und Effizienz vereinbaren."}]}',
'{"title":"Vereinbaren — to reconcile, combine (two things that may conflict)","pattern":"X mit Y vereinbaren = to reconcile X with Y, combine X and Y (when they may be in tension)","explanation":"Vereinbaren = to reconcile, combine, make compatible. Ästhetische Ansprüche mit Energieeffizienz vereinbaren = to reconcile aesthetic demands with energy efficiency. Also: einen Termin vereinbaren (to arrange/agree on an appointment — different meaning: to schedule). Sich vereinbaren lassen mit = to be compatible with. Compare: in Einklang bringen (to bring into harmony — more formal), verbinden (to combine — more neutral, less tension implied).","examples":[{"sentence":"Lässt sich Wachstum mit Nachhaltigkeit vereinbaren?","translation":"Can growth be reconciled with sustainability?"},{"sentence":"Sie versucht, Familie und Karriere miteinander zu vereinbaren.","translation":"She tries to reconcile family and career."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Zeitgenössisch'' means?","options":["contemporary","modern","current","present-day"],"correctAnswer":"contemporary"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The Bauhaus revolutionised 20th-century architecture through the fusion of art, craft, and industrial production.","options":["Das Bauhaus revolutionierte die Architektur des 20. Jahrhunderts durch die Verbindung von Kunst, Handwerk und industrieller Fertigung.","Das Bauhaus verband Kunst und Industrie.","Durch das Bauhaus wurde die moderne Architektur geprägt.","Bauhaus revolutionierte Design und Architektur."],"correctAnswer":"Das Bauhaus revolutionierte die Architektur des 20. Jahrhunderts durch die Verbindung von Kunst, Handwerk und industrieller Fertigung."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Lässt sich Wachstum mit Nachhaltigkeit ___ ?","options":["vereinbaren","verbinden","in Einklang bringen","kombinieren"],"correctAnswer":"vereinbaren"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She tries to reconcile family and career","wordBankItems":["Sie","versucht",",","Familie","und","Karriere","miteinander","zu","vereinbaren","."],"correctAnswer":"Sie versucht , Familie und Karriere miteinander zu vereinbaren ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Fertigung'' means?","options":["production/manufacturing","fabrication","assembly","making"],"correctAnswer":"production/manufacturing"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001ea',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss film and cinema at B2","Use Film vocabulary","Talk about German cinema tradition"],"explanation":{"intro":"Film vocabulary covers German cinema tradition, film analysis, and the film industry at B2.","culturalNote":"German cinema: Stummfilm era (Nosferatu, Das Cabinet des Dr. Caligari), Weimar Republic expressionism, post-war Trümmerfilme, New German Cinema (Fassbinder, Herzog, Wenders), contemporary (Lola rennt, Das Leben der Anderen — Oscar winner). Key institutions: Berlinale (Berlin International Film Festival — one of the Big Three), Filmförderungsanstalt (FFA — film funding). German film attracts 100M+ cinema admissions/year."},"examples":[{"german":"Der expressionistische Film der Weimarer Republik spiegelt die gesellschaftliche Verunsicherung und politische Instabilität der 1920er Jahre wider.","english":"The expressionist film of the Weimar Republic reflects the social uncertainty and political instability of the 1920s."},{"german":"Das Neue Deutsche Kino der 1970er Jahre brach mit konventionellen Erzählstrukturen und entwickelte eine unverwechselbare filmische Sprache.","english":"New German Cinema of the 1970s broke with conventional narrative structures and developed a distinctive cinematic language."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss German cinema, film analysis, and the film industry at B2."}}',
'{"items":[{"word":"die Verunsicherung","translation":"uncertainty/unease","pronunciation":"dee fer-OON-zi-kheh-roong","example":"Gesellschaftliche Verunsicherung."},{"word":"unverwechselbar","translation":"distinctive/unmistakable","pronunciation":"oon-fer-VEK-sel-bar","example":"Unverwechselbare Sprache."},{"word":"brechen mit","translation":"to break with","pronunciation":"BREKH-en mit","example":"Mit Konventionen brechen."},{"word":"die Erzählstruktur","translation":"narrative structure","pronunciation":"dee er-TSÄL-shtrook-toor","example":"Erzählstrukturen."},{"word":"filmisch","translation":"cinematic","pronunciation":"FIL-mish","example":"Filmische Sprache."},{"word":"konventionell","translation":"conventional","pronunciation":"kon-ven-tsyo-NEL","example":"Konventionelle Strukturen."}]}',
'{"title":"Brechen mit — to break with (tradition/convention)","pattern":"mit etwas brechen = to break with something (tradition, norm, expectation)","explanation":"Mit etwas brechen (intransitive) = to break with, depart from (tradition, norm). Das Neue Deutsche Kino brach mit konventionellen Strukturen = New German Cinema broke with conventional structures. Perfect: hat gebrochen. Der Bruch mit (noun) = the break with. Common collocations: mit der Tradition brechen (to break with tradition), mit Gewohnheiten brechen (to break habits), mit der Vergangenheit brechen (to break with the past). Compare: aufgeben (to give up — more complete abandonment), ablehnen (to reject — more active), überwinden (to overcome — more positive framing).","examples":[{"sentence":"Die Künstlerin brach bewusst mit den Erwartungen des Kunstbetriebs.","translation":"The artist deliberately broke with the expectations of the art world."},{"sentence":"Es ist schwer, mit alten Gewohnheiten zu brechen.","translation":"It is hard to break with old habits."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Unverwechselbar'' means?","options":["distinctive/unmistakable","unique","original","incomparable"],"correctAnswer":"distinctive/unmistakable"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"New German Cinema of the 1970s broke with conventional narrative structures and developed a distinctive cinematic language.","options":["Das Neue Deutsche Kino der 1970er Jahre brach mit konventionellen Erzählstrukturen und entwickelte eine unverwechselbare filmische Sprache.","Neues Deutsches Kino war anders und innovativ.","Deutsche Filmemacher der 70er prägten eine eigene Filmsprache.","Das Neue Deutsche Kino revolutionierte das Filmemachen."],"correctAnswer":"Das Neue Deutsche Kino der 1970er Jahre brach mit konventionellen Erzählstrukturen und entwickelte eine unverwechselbare filmische Sprache."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Künstlerin brach bewusst mit den Erwartungen des ___.","options":["Kunstbetriebs","Kunstmarkts","Kunstsystems","Kunstwesens"],"correctAnswer":"Kunstbetriebs"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: It is hard to break with old habits","wordBankItems":["Es","ist","schwer",",","mit","alten","Gewohnheiten","zu","brechen","."],"correctAnswer":"Es ist schwer , mit alten Gewohnheiten zu brechen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Verunsicherung'' means?","options":["uncertainty/unease","insecurity","anxiety","destabilisation"],"correctAnswer":"uncertainty/unease"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-0000000001e1','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l481',481,'Geopolitik','Geopolitics','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e2','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l482',482,'Europäische Union B2','EU B2','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e3','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l483',483,'Entwicklungspolitik','Development policy','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e4','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l484',484,'Migration und Asyl B2','Migration B2','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e5','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l485',485,'Religionsfreiheit','Religious freedom','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e6','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l486',486,'Kunst und Gesellschaft','Art and society','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e7','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l487',487,'Literatur B2','Literature B2','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e8','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l488',488,'Musik und Kultur','Music and culture','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001e9','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l489',489,'Architektur B2','Architecture B2','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001ea','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l490',490,'Film und Kino','Film and cinema','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e1' WHERE stable_ref = 'de-b2-u04-l481' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e2' WHERE stable_ref = 'de-b2-u04-l482' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e3' WHERE stable_ref = 'de-b2-u04-l483' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e4' WHERE stable_ref = 'de-b2-u04-l484' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e5' WHERE stable_ref = 'de-b2-u04-l485' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e6' WHERE stable_ref = 'de-b2-u04-l486' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e7' WHERE stable_ref = 'de-b2-u04-l487' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e8' WHERE stable_ref = 'de-b2-u04-l488' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001e9' WHERE stable_ref = 'de-b2-u04-l489' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001ea' WHERE stable_ref = 'de-b2-u04-l490' AND lesson_id IS NULL;
