-- V78: German B2 lessons 491-500 (B2 batch 9, 10 lessons)
-- Hex: 491=0x1eb, 500=0x1f4 — milestone at 500

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-0000000001eb','de-b2-l491','Theater und Oper - Theatre','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001ec','de-b2-l492','Mode und Design - Fashion','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001ed','de-b2-l493','Sport und Gesellschaft - Sport','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001ee','de-b2-l494','Tourismus - Tourism','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001ef','de-b2-l495','Gastronomie - Gastronomy','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f0','de-b2-l496','Sprache und Identität - Language Identity','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f1','de-b2-l497','Mehrsprachigkeit - Multilingualism','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f2','de-b2-l498','Dialekte und Varietäten - Dialects','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f3','de-b2-l499','Spracherwerb - Language Acquisition','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f4','de-b2-l500','B2 Meilenstein 4 - Milestone 4','language','de','B2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (stable_ref) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001eb',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss theatre at B2","Use Theater vocabulary","Talk about German theatre tradition"],"explanation":{"intro":"Theatre vocabulary covers German theatre tradition, dramatology, and contemporary performance at B2.","culturalNote":"Germany has the highest density of publicly funded theatres in the world: ~130 state-funded theatres, ~300 private theatres. Key institutions: Berliner Ensemble (Brecht), Deutsches Theater, Schaubühne. Key playwrights: Schiller, Brecht (Episches Theater — epic theatre), Heiner Müller, Elfriede Jelinek. Key concept: Regietheater (director''s theatre — reinterpreting classics with radical contemporary readings)."},"examples":[{"german":"Bertolt Brechts episches Theater zielte darauf ab, den Zuschauer zur kritischen Reflexion anzuregen, anstatt ihn in die Handlung zu versetzen.","english":"Bertolt Brecht''s epic theatre aimed to stimulate the audience to critical reflection rather than to immerse them in the action."},{"german":"Das staatlich subventionierte Theater ermöglicht es, künstlerisch anspruchsvolle Werke zu produzieren, die sich am freien Markt nicht durchsetzen könnten.","english":"State-subsidised theatre makes it possible to produce artistically demanding works that could not succeed in the free market."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss theatre, Brecht, and German theatre tradition at B2."}}',
'{"items":[{"word":"anregen","translation":"to stimulate/prompt","pronunciation":"AN-ray-gen","example":"Zur Reflexion anregen."},{"word":"versetzen in","translation":"to immerse in/transport into","pronunciation":"fer-ZETSEN in","example":"In die Handlung versetzen."},{"word":"subventioniert","translation":"subsidised","pronunciation":"zoop-ven-tsyo-NEERT","example":"Staatlich subventioniert."},{"word":"anspruchsvoll","translation":"demanding/ambitious","pronunciation":"AN-shprookhs-fol","example":"Anspruchsvolle Werke."},{"word":"sich durchsetzen","translation":"to succeed/prevail","pronunciation":"zikh DOORKH-zetsen","example":"Am Markt durchsetzen."},{"word":"die Subvention","translation":"subsidy","pronunciation":"dee zoop-ven-tsee-OHN","example":"Staatliche Subventionen."}]}',
'{"title":"Anstatt...zu — instead of (doing) — same subject","pattern":"anstatt + zu + Infinitiv = instead of doing (same subject, same time frame)","explanation":"Anstatt zu + Infinitiv (same subject) = instead of doing. Brecht zielte darauf ab, anzuregen, anstatt zu versetzen = aimed to stimulate instead of immersing. Also written: statt + zu + Infinitiv (colloquial equivalent). Different subjects: anstatt dass + V-final. Compare: statt (instead of — preposition + noun: statt des Autos = instead of the car). Anstatt signals an alternative rejected in favour of the action in the main clause.","examples":[{"sentence":"Er löste das Problem selbst, anstatt um Hilfe zu bitten.","translation":"He solved the problem himself instead of asking for help."},{"sentence":"Anstatt zu klagen, sollten wir nach Lösungen suchen.","translation":"Instead of complaining, we should look for solutions."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Anregen'' means?","options":["to stimulate/prompt","to suggest","to encourage","to inspire"],"correctAnswer":"to stimulate/prompt"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Bertolt Brecht''s epic theatre aimed to stimulate the audience to critical reflection rather than to immerse them in the action.","options":["Bertolt Brechts episches Theater zielte darauf ab, den Zuschauer zur kritischen Reflexion anzuregen, anstatt ihn in die Handlung zu versetzen.","Brecht wollte, dass das Publikum nachdenkt, nicht mitfühlt.","Episches Theater regt zur Reflexion an statt zur Einfühlung.","Brecht lehnte Einfühlung ab und förderte kritisches Denken."],"correctAnswer":"Bertolt Brechts episches Theater zielte darauf ab, den Zuschauer zur kritischen Reflexion anzuregen, anstatt ihn in die Handlung zu versetzen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er löste das Problem selbst, anstatt um Hilfe zu ___.","options":["bitten","fragen","betteln","ersuchen"],"correctAnswer":"bitten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Instead of complaining we should look for solutions","wordBankItems":["Anstatt","zu","klagen",",","sollten","wir","nach","Lösungen","suchen","."],"correctAnswer":"Anstatt zu klagen , sollten wir nach Lösungen suchen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Anspruchsvoll'' means?","options":["demanding/ambitious","high-quality","exacting","challenging"],"correctAnswer":"demanding/ambitious"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001ec',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss fashion and design at B2","Use Mode vocabulary","Talk about the fashion industry"],"explanation":{"intro":"Fashion and design vocabulary covers the fashion industry, sustainability, and cultural expression at B2.","culturalNote":"Germany is not traditionally a fashion capital but has strong design tradition: Bauhaus influence, German functionalism. Berlin Fashion Week is growing. Key brands: Hugo Boss, Adidas, Puma, Escada. Key issues: Fast Fashion (Schnellmode — environmental impact), nachhaltige Mode (sustainable fashion), Secondhand-Boom. The EU Textilstrategie aims to make fashion more sustainable. Design schools: HfG Ulm (influential industrial design)."},"examples":[{"german":"Fast Fashion hat den Textilkonsum demokratisiert, gleichzeitig jedoch zu enormen ökologischen und sozialen Problemen in der gesamten Lieferkette geführt.","english":"Fast fashion has democratised textile consumption, but at the same time led to enormous ecological and social problems throughout the entire supply chain."},{"german":"Nachhaltige Mode versucht, den gesamten Lebenszyklus eines Kleidungsstücks zu optimieren, von der Rohstoffgewinnung bis zur Entsorgung.","english":"Sustainable fashion seeks to optimise the entire life cycle of a garment, from raw material extraction to disposal."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss fashion, sustainable fashion, and the textile industry at B2."}}',
'{"items":[{"word":"demokratisieren","translation":"to democratise","pronunciation":"deh-mo-krah-ti-ZEER-en","example":"Den Konsum demokratisieren."},{"word":"der Lebenszyklus","translation":"life cycle","pronunciation":"dayr LAY-bens-tsü-kloos","example":"Lebenszyklus eines Produkts."},{"word":"die Rohstoffgewinnung","translation":"raw material extraction","pronunciation":"dee ROH-shtof-geh-vin-oong","example":"Rohstoffgewinnung."},{"word":"die Entsorgung","translation":"disposal","pronunciation":"dee ent-ZOR-goong","example":"Entsorgung von Kleidung."},{"word":"optimieren","translation":"to optimise","pronunciation":"op-ti-MEER-en","example":"Den Prozess optimieren."},{"word":"das Kleidungsstück","translation":"garment","pronunciation":"dahs KLY-doonks-shtük","example":"Kleidungsstück."}]}',
'{"title":"Gleichzeitig jedoch — but at the same time (concessive additive)","pattern":"X, gleichzeitig jedoch Y = X, but at the same time Y (acknowledges a simultaneous contradiction)","explanation":"Gleichzeitig jedoch = but at the same time, yet simultaneously (marks that something positive and something negative happen together). Fast Fashion demokratisierte den Konsum, führte gleichzeitig jedoch zu Problemen = democratised consumption but at the same time led to problems. Gleichzeitig = simultaneously; jedoch = however/yet. Together they create a concessive additive: both things are true at the same moment. Compare: zugleich aber (simultaneously but — similar), andererseits (on the other hand — different perspective).","examples":[{"sentence":"Die Reform verbesserte die Effizienz, erhöhte gleichzeitig jedoch die Kosten.","translation":"The reform improved efficiency but at the same time increased costs."},{"sentence":"Digitalisierung schafft neue Jobs, vernichtet gleichzeitig jedoch andere.","translation":"Digitalisation creates new jobs but at the same time destroys others."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Entsorgung'' means?","options":["disposal","removal","discarding","waste management"],"correctAnswer":"disposal"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Fast fashion has democratised textile consumption, but at the same time led to enormous ecological and social problems throughout the entire supply chain.","options":["Fast Fashion hat den Textilkonsum demokratisiert, gleichzeitig jedoch zu enormen ökologischen und sozialen Problemen in der gesamten Lieferkette geführt.","Fast Fashion macht Mode günstig, schadet aber der Umwelt.","Durch Fast Fashion entstand eine ökologische und soziale Krise.","Fast Fashion ist billig, aber nicht nachhaltig."],"correctAnswer":"Fast Fashion hat den Textilkonsum demokratisiert, gleichzeitig jedoch zu enormen ökologischen und sozialen Problemen in der gesamten Lieferkette geführt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Reform verbesserte die Effizienz, erhöhte gleichzeitig ___ die Kosten.","options":["jedoch","aber","doch","allerdings"],"correctAnswer":"jedoch"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Digitalisation creates new jobs but at the same time destroys others","wordBankItems":["Digitalisierung","schafft","neue","Jobs",",","vernichtet","gleichzeitig","jedoch","andere","."],"correctAnswer":"Digitalisierung schafft neue Jobs , vernichtet gleichzeitig jedoch andere ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Lebenszyklus'' means?","options":["life cycle","lifespan","lifecycle","product life"],"correctAnswer":"life cycle"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001ed',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss sport and society at B2","Use Sport vocabulary","Talk about football and sports policy"],"explanation":{"intro":"Sport and society vocabulary covers football culture, sports policy, and the social role of sport at B2.","culturalNote":"Germany is a football nation: 4x World Cup winners (1954, 1974, 1990, 2014). Bundesliga (Germany''s top football league) is the highest-attended football league in the world. Key issues: Kommerzialisierung (commercialisation), DFB (Deutscher Fußball-Bund), Fankultur (fan culture), 50+1-Regel (50+1 rule — prevents outside investor takeovers of clubs), Doping, Inklusion im Sport."},"examples":[{"german":"Sport erfüllt wichtige gesellschaftliche Funktionen: Er fördert Integration, stärkt Gemeinschaftsgefühl und trägt zur Gesundheitsprävention bei.","english":"Sport fulfils important social functions: it promotes integration, strengthens the sense of community, and contributes to health prevention."},{"german":"Die zunehmende Kommerzialisierung des Profifußballs hat eine Kluft zwischen der Unterhaltungsindustrie und der gelebten Fankultur entstehen lassen.","english":"The increasing commercialisation of professional football has allowed a gap to emerge between the entertainment industry and the lived fan culture."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss sport, football culture, and the social role of sport at B2."}}',
'{"items":[{"word":"erfüllen","translation":"to fulfil","pronunciation":"er-FÜL-en","example":"Funktionen erfüllen."},{"word":"das Gemeinschaftsgefühl","translation":"sense of community","pronunciation":"dahs geh-MYN-shafts-geh-fühl","example":"Gemeinschaftsgefühl."},{"word":"die Kluft","translation":"gap/divide","pronunciation":"dee klooft","example":"Eine Kluft entstehen lassen."},{"word":"entstehen lassen","translation":"to allow to emerge","pronunciation":"ent-SHTAY-en LAS-en","example":"Eine Kluft entstehen lassen."},{"word":"gelebt","translation":"lived (authentic)","pronunciation":"geh-LAYPT","example":"Gelebte Fankultur."},{"word":"die Kommerzialisierung","translation":"commercialisation","pronunciation":"dee ko-mer-tsya-li-ZEER-oong","example":"Kommerzialisierung."}]}',
'{"title":"Entstehen lassen — to allow to emerge, to cause to develop","pattern":"etwas entstehen lassen = to allow something to emerge/form, to cause something to develop","explanation":"Entstehen lassen = to allow/cause to emerge/develop. Die Kommerzialisierung hat eine Kluft entstehen lassen = The commercialisation has allowed a gap to emerge. This is a causative construction with lassen: hat [noun] entstehen lassen = has allowed [noun] to come into being. Compare: entstehen (to emerge — intransitive), verursachen (to cause — more direct causation), herbeiführen (to bring about — deliberate), fördern (to promote/foster — positive).","examples":[{"sentence":"Die Vernachlässigung hat große Schäden entstehen lassen.","translation":"The neglect has allowed great damage to develop."},{"sentence":"Die Politik hat eine Vertrauenskrise entstehen lassen.","translation":"Politics has allowed a crisis of trust to develop."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Kluft'' means?","options":["gap/divide","rift","distance","separation"],"correctAnswer":"gap/divide"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The increasing commercialisation of professional football has allowed a gap to emerge between the entertainment industry and the lived fan culture.","options":["Die zunehmende Kommerzialisierung des Profifußballs hat eine Kluft zwischen der Unterhaltungsindustrie und der gelebten Fankultur entstehen lassen.","Kommerzialisierung hat Fußball von den Fans entfernt.","Im Profifußball entstand eine Kluft zwischen Industrie und Fans.","Fußball ist kommerzieller geworden und hat Fans verloren."],"correctAnswer":"Die zunehmende Kommerzialisierung des Profifußballs hat eine Kluft zwischen der Unterhaltungsindustrie und der gelebten Fankultur entstehen lassen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Vernachlässigung hat große Schäden entstehen ___.","options":["lassen","gelassen","lassen haben","entstehen lassen"],"correctAnswer":"lassen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Politics has allowed a crisis of trust to develop","wordBankItems":["Die","Politik","hat","eine","Vertrauenskrise","entstehen","lassen","."],"correctAnswer":"Die Politik hat eine Vertrauenskrise entstehen lassen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Erfüllen'' means?","options":["to fulfil","to satisfy","to meet","to carry out"],"correctAnswer":"to fulfil"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001ee',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss tourism at B2","Use Tourismus vocabulary","Talk about sustainable tourism"],"explanation":{"intro":"Tourism vocabulary covers sustainable tourism, travel trends, and tourism policy at B2.","culturalNote":"Germany receives ~40 million international tourists/year (pre-COVID). Key destinations: Bavaria (Neuschwanstein, Munich, Alps), Rhine Valley, Black Forest, Berlin, Hamburg. Key issues: Overtourismus (overtourism), nachhaltiger Tourismus (sustainable tourism), Städtetourismus (city tourism), Inlandstourismus (domestic tourism — boosted by COVID). UNESCO Welterbe (World Heritage Sites) in Germany: 52 sites."},"examples":[{"german":"Nachhaltiger Tourismus versucht, das Gleichgewicht zwischen wirtschaftlichem Nutzen und dem Schutz natürlicher und kultureller Ressourcen herzustellen.","english":"Sustainable tourism seeks to establish a balance between economic benefit and the protection of natural and cultural resources."},{"german":"Overtourismus führt in beliebten Destinationen zu Überlastung der Infrastruktur, steigenden Mietpreisen und einer Beeinträchtigung der Lebensqualität der Einheimischen.","english":"Overtourism leads in popular destinations to infrastructure overload, rising rents, and an impairment of the quality of life of local residents."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss tourism, sustainable tourism, and overtourism at B2."}}',
'{"items":[{"word":"das Gleichgewicht","translation":"balance/equilibrium","pronunciation":"dahs GLYKH-geh-vikht","example":"Gleichgewicht herstellen."},{"word":"herstellen","translation":"to establish/create","pronunciation":"HER-shtel-en","example":"Gleichgewicht herstellen."},{"word":"die Überlastung","translation":"overload","pronunciation":"dee ü-ber-LAS-toong","example":"Überlastung der Infrastruktur."},{"word":"die Beeinträchtigung","translation":"impairment/impact","pronunciation":"dee beh-YN-trek-ti-goong","example":"Beeinträchtigung der Lebensqualität."},{"word":"der Einheimische","translation":"local resident","pronunciation":"dayr YN-hy-mi-sheh","example":"Einheimische."},{"word":"beliebt","translation":"popular/beloved","pronunciation":"beh-LEEPT","example":"Beliebte Destination."}]}',
'{"title":"Herstellen — to establish, create, produce (separable)","pattern":"etwas herstellen = to establish, produce, create (separable — used for abstract and concrete)","explanation":"Herstellen (separable) = to establish, create, produce. Ein Gleichgewicht herstellen = to establish a balance. Ein Produkt herstellen = to manufacture a product. Kontakt herstellen = to establish contact. Verbindung herstellen = to make a connection. Perfect: hat hergestellt. Die Herstellung = production, establishment. Compare: schaffen (to create — more about bringing into being from scratch), erzeugen (to generate/produce — often energy, goods), produzieren (to produce — industrial/media).","examples":[{"sentence":"Es gelang nicht, einen Konsens herzustellen.","translation":"It was not possible to establish a consensus."},{"sentence":"Das Unternehmen stellt hochwertige Elektronikkomponenten her.","translation":"The company produces high-quality electronic components."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Gleichgewicht'' means?","options":["balance/equilibrium","equal weight","balance point","equilibrium"],"correctAnswer":"balance/equilibrium"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Sustainable tourism seeks to establish a balance between economic benefit and the protection of natural and cultural resources.","options":["Nachhaltiger Tourismus versucht, das Gleichgewicht zwischen wirtschaftlichem Nutzen und dem Schutz natürlicher und kultureller Ressourcen herzustellen.","Nachhaltiger Tourismus schützt Natur und Kultur.","Zwischen Wirtschaft und Naturschutz muss ein Gleichgewicht bestehen.","Tourismus muss nachhaltig und ressourcenschonend sein."],"correctAnswer":"Nachhaltiger Tourismus versucht, das Gleichgewicht zwischen wirtschaftlichem Nutzen und dem Schutz natürlicher und kultureller Ressourcen herzustellen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Es gelang nicht, einen Konsens ___.","options":["herzustellen","zu schaffen","zu finden","zu erreichen"],"correctAnswer":"herzustellen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The company produces high-quality electronic components","wordBankItems":["Das","Unternehmen","stellt","hochwertige","Elektronikkomponenten","her","."],"correctAnswer":"Das Unternehmen stellt hochwertige Elektronikkomponenten her ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Beeinträchtigung'' means?","options":["impairment/impact","damage","harm","deterioration"],"correctAnswer":"impairment/impact"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001ef',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss gastronomy at B2","Use Gastronomie vocabulary","Talk about food culture and restaurants"],"explanation":{"intro":"Gastronomy vocabulary covers food culture, restaurant industry, and culinary trends at B2.","culturalNote":"German Gastronomie: Sternegastronomie (Michelin-star restaurants), Biergärten (beer gardens — Bavarian tradition, cultural institution), Streetfood-Bewegung (street food movement), Regionalküche (regional cuisine — Schweinshaxe in Bavaria, Sauerbraten in Rhine, Labskaus in Hamburg). Key issues: Fachkräftemangel in Gastgewerbe, Lebensmittelverschwendung, vegane und vegetarische Gastronomie booming."},"examples":[{"german":"Die Regionalküche erlebt eine Renaissance, da Verbraucher zunehmend Wert auf Regionalität, Saisonalität und kurze Lieferketten legen.","english":"Regional cuisine is experiencing a renaissance, as consumers increasingly place value on regional origin, seasonality, and short supply chains."},{"german":"Die Gastronomiebranche kämpft mit einem massiven Fachkräftemangel, der auf schwierige Arbeitsbedingungen und unattraktive Vergütung zurückzuführen ist.","english":"The catering industry is struggling with a massive shortage of skilled workers, which is attributable to difficult working conditions and unattractive remuneration."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss gastronomy, food culture, and culinary trends at B2."}}',
'{"items":[{"word":"die Renaissance","translation":"renaissance/revival","pronunciation":"dee reh-neh-SANS","example":"Eine Renaissance erleben."},{"word":"die Regionalität","translation":"regional origin","pronunciation":"dee reh-gyo-nah-li-TÄT","example":"Wert auf Regionalität legen."},{"word":"die Saisonalität","translation":"seasonality","pronunciation":"dee zay-zo-nah-li-TÄT","example":"Saisonalität."},{"word":"Wert legen auf","translation":"to place value on","pronunciation":"vert LAY-gen owf","example":"Wert auf Qualität legen."},{"word":"kämpfen mit","translation":"to struggle with","pronunciation":"KEMP-fen mit","example":"Mit Problemen kämpfen."},{"word":"massiv","translation":"massive","pronunciation":"mas-SEEF","example":"Massiver Fachkräftemangel."}]}',
'{"title":"Wert legen auf — to place value on, to attach importance to","pattern":"Wert legen auf + accusative = to place value on, to attach importance to","explanation":"Wert legen auf + accusative = to place value on, to attach importance to. Verbraucher legen Wert auf Regionalität = Consumers place value on regional origin. Fixed phrase: Wert is a noun (der Wert = value), legen = to lay/place. Adjective: großen Wert legen auf (to place great value on), wenig Wert legen auf (to place little value on). Compare: schätzen (to value/appreciate — more personal), Bedeutung beimessen (to attach significance to — more analytical), etw. als wichtig erachten (to consider important — formal).","examples":[{"sentence":"Ich lege großen Wert auf ehrliche Kommunikation.","translation":"I place great value on honest communication."},{"sentence":"Das Unternehmen legt Wert auf kontinuierliche Weiterbildung.","translation":"The company attaches importance to continuous professional development."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Saisonalität'' means?","options":["seasonality","seasonal nature","season-based","seasonal cycle"],"correctAnswer":"seasonality"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Regional cuisine is experiencing a renaissance, as consumers increasingly place value on regional origin, seasonality, and short supply chains.","options":["Die Regionalküche erlebt eine Renaissance, da Verbraucher zunehmend Wert auf Regionalität, Saisonalität und kurze Lieferketten legen.","Regionalküche wird immer beliebter.","Verbraucher wollen regionale und saisonale Produkte.","Kurzkettige Lieferketten und Regionalität liegen im Trend."],"correctAnswer":"Die Regionalküche erlebt eine Renaissance, da Verbraucher zunehmend Wert auf Regionalität, Saisonalität und kurze Lieferketten legen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Ich lege großen Wert auf ehrliche ___.","options":["Kommunikation","Gespräche","Aussagen","Diskussion"],"correctAnswer":"Kommunikation"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The company attaches importance to continuous professional development","wordBankItems":["Das","Unternehmen","legt","Wert","auf","kontinuierliche","Weiterbildung","."],"correctAnswer":"Das Unternehmen legt Wert auf kontinuierliche Weiterbildung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Kämpfen mit'' means?","options":["to struggle with","to fight against","to deal with","to cope with"],"correctAnswer":"to struggle with"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f0',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss language and identity at B2","Use Sprache und Identität vocabulary","Talk about language as social marker"],"explanation":{"intro":"Language and identity vocabulary covers sociolinguistics, language as power, and language policy at B2.","culturalNote":"Key concepts: Soziolinguistik (sociolinguistics), Sprachprestige (language prestige), Code-Switching, Diglossia (Diglossie — use of two varieties), Sprachpolitik (language policy). Deutsch as identity: German unification partly driven by shared language. Language hierarchy: Hochdeutsch (standard German) vs. Mundart (dialect). Language rights for minority languages (Sorbisch, Friesisch, Dänisch, Romani) protected by European Charter."},"examples":[{"german":"Sprache ist nicht nur ein Kommunikationsmittel, sondern ein konstitutives Element kultureller und kollektiver Identität.","english":"Language is not only a means of communication but a constitutive element of cultural and collective identity."},{"german":"Sprachvarietäten signalisieren soziale Zugehörigkeit und fungieren als Marker für Klasse, Region und Bildungshintergrund.","english":"Language varieties signal social belonging and function as markers of class, region, and educational background."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss language and identity, sociolinguistics, and language varieties at B2."}}',
'{"items":[{"word":"konstitutiv","translation":"constitutive","pronunciation":"kon-sti-too-TEEF","example":"Konstitutives Element."},{"word":"die Zugehörigkeit","translation":"belonging/affiliation","pronunciation":"dee TSOO-geh-hö-rikh-kyt","example":"Soziale Zugehörigkeit."},{"word":"fungieren als","translation":"to function as","pronunciation":"foon-GEER-en als","example":"Als Marker fungieren."},{"word":"der Marker","translation":"marker","pronunciation":"dayr MAR-ker","example":"Soziale Marker."},{"word":"die Sprachvarietät","translation":"language variety","pronunciation":"dee SHPRAKH-vah-ree-eh-TÄT","example":"Sprachvarietäten."},{"word":"signalisieren","translation":"to signal","pronunciation":"sig-nah-li-ZEER-en","example":"Zugehörigkeit signalisieren."}]}',
'{"title":"Fungieren als — to function as, serve as","pattern":"etwas fungiert als + noun = something functions as, serves as (formal register)","explanation":"Fungieren als + noun (no article or indefinite article) = to function as, serve as, act as. Sprachvarietäten fungieren als Marker = Language varieties function as markers. More formal than dienen als (to serve as) or wirken als (to act as). Perfect: hat fungiert. Common in academic description of roles and functions. Compare: dienen als (to serve as — more neutral), wirken als (to act/work as — often effects/impressions), gelten als (to be regarded as — perception).","examples":[{"sentence":"Der Ausschuss fungiert als Vermittler zwischen den Parteien.","translation":"The committee functions as mediator between the parties."},{"sentence":"Das Dokument fungiert als Nachweis für die Berechtigung.","translation":"The document serves as proof of eligibility."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Konstitutiv'' means?","options":["constitutive","essential","foundational","defining"],"correctAnswer":"constitutive"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Language varieties signal social belonging and function as markers of class, region, and educational background.","options":["Sprachvarietäten signalisieren soziale Zugehörigkeit und fungieren als Marker für Klasse, Region und Bildungshintergrund.","Sprache zeigt, woher jemand kommt und welche Bildung er hat.","Dialekte und Varietäten sind soziale Marker.","Durch Sprache erkennt man soziale Herkunft."],"correctAnswer":"Sprachvarietäten signalisieren soziale Zugehörigkeit und fungieren als Marker für Klasse, Region und Bildungshintergrund."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Ausschuss fungiert als Vermittler zwischen den ___.","options":["Parteien","Seiten","Gruppen","Beteiligten"],"correctAnswer":"Parteien"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The document serves as proof of eligibility","wordBankItems":["Das","Dokument","fungiert","als","Nachweis","für","die","Berechtigung","."],"correctAnswer":"Das Dokument fungiert als Nachweis für die Berechtigung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Zugehörigkeit'' means?","options":["belonging/affiliation","membership","identity","attachment"],"correctAnswer":"belonging/affiliation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f1',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss multilingualism at B2","Use Mehrsprachigkeit vocabulary","Talk about language learning and language policy"],"explanation":{"intro":"Multilingualism vocabulary covers bilingualism, language policy, and the benefits of multiple languages at B2.","culturalNote":"EU language policy: 24 official languages, Mehrsprachigkeit (multilingualism) promoted. German is the most widely spoken mother tongue in the EU. Herkunftssprachen (heritage languages) of migrants (Turkish, Arabic, Russian) are increasingly valued. CLIL (Content and Language Integrated Learning), Immersionsschulen (immersion schools). Bilinguale Bildung (bilingual education) expanding."},"examples":[{"german":"Mehrsprachigkeit gilt als kognitive Ressource, die metasprachliches Bewusstsein schärft und die Lernfähigkeit für weitere Sprachen erhöht.","english":"Multilingualism is regarded as a cognitive resource that sharpens metalinguistic awareness and increases the capacity to learn further languages."},{"german":"Sprachpolitik steht vor der Herausforderung, Minderheitensprachen zu schützen, ohne die Kommunikationsfähigkeit in der Mehrheitssprache zu untergraben.","english":"Language policy faces the challenge of protecting minority languages without undermining communicative competence in the majority language."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss multilingualism, language policy, and cognitive benefits of languages at B2."}}',
'{"items":[{"word":"metasprachlich","translation":"metalinguistic","pronunciation":"meh-tah-SHPRAKH-likh","example":"Metasprachliches Bewusstsein."},{"word":"schärfen","translation":"to sharpen","pronunciation":"SHER-fen","example":"Bewusstsein schärfen."},{"word":"die Lernfähigkeit","translation":"capacity to learn","pronunciation":"dee LERN-fä-ikh-kyt","example":"Lernfähigkeit."},{"word":"untergraben","translation":"to undermine","pronunciation":"oon-ter-GRAH-ben","example":"Kompetenz untergraben."},{"word":"die Minderheitensprache","translation":"minority language","pronunciation":"dee MIN-der-hyt-en-shprakh-eh","example":"Minderheitensprachen schützen."},{"word":"die Mehrheitssprache","translation":"majority language","pronunciation":"dee MAYR-hyts-shprakh-eh","example":"Mehrheitssprache."}]}',
'{"title":"Schärfen — to sharpen (abstract skills and awareness)","pattern":"etwas schärfen = to sharpen (abstract — skills, awareness, senses, arguments)","explanation":"Schärfen = to sharpen (both physical — a knife — and abstract). Bewusstsein schärfen = to sharpen/heighten awareness. Das Profil schärfen = to sharpen the profile. Den Blick schärfen = to sharpen one''s eye/perspective. Das Argument schärfen = to hone the argument. Perfect: hat geschärft. Compare: schärfer machen (more direct), verfeinern (to refine/hone — more about precision), vertiefen (to deepen — more about depth of understanding).","examples":[{"sentence":"Das Training schärft die analytischen Fähigkeiten.","translation":"The training sharpens analytical skills."},{"sentence":"Kritisches Lesen schärft den Blick für Manipulationsversuche.","translation":"Critical reading sharpens the eye for manipulation attempts."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Metasprachlich'' means?","options":["metalinguistic","about language","language-related","linguistic"],"correctAnswer":"metalinguistic"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Multilingualism is regarded as a cognitive resource that sharpens metalinguistic awareness and increases the capacity to learn further languages.","options":["Mehrsprachigkeit gilt als kognitive Ressource, die metasprachliches Bewusstsein schärft und die Lernfähigkeit für weitere Sprachen erhöht.","Mehrsprachige Menschen lernen leichter neue Sprachen.","Mehrsprachigkeit hat kognitive Vorteile.","Wer mehrere Sprachen spricht, denkt flexibler."],"correctAnswer":"Mehrsprachigkeit gilt als kognitive Ressource, die metasprachliches Bewusstsein schärft und die Lernfähigkeit für weitere Sprachen erhöht."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Training schärft die analytischen ___.","options":["Fähigkeiten","Kompetenzen","Kenntnisse","Fertigkeiten"],"correctAnswer":"Fähigkeiten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Critical reading sharpens the eye for manipulation attempts","wordBankItems":["Kritisches","Lesen","schärft","den","Blick","für","Manipulationsversuche","."],"correctAnswer":"Kritisches Lesen schärft den Blick für Manipulationsversuche ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Lernfähigkeit'' means?","options":["capacity to learn","learning ability","aptitude for learning","learnability"],"correctAnswer":"capacity to learn"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f2',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss dialects at B2","Use Dialekt vocabulary","Talk about regional varieties of German"],"explanation":{"intro":"Dialects vocabulary covers regional German varieties, prestige, and language change at B2.","culturalNote":"German has highly diverse dialects: Bayerisch, Sächsisch, Kölsch, Schwäbisch, Plattdeutsch (Low German — officially recognised minority language). Dialektatlas (dialect atlas) documents variation. Key concepts: Diglossia (diglossia — dialect + standard), Sprachprestige (Sächsisch has low prestige, Bayerisch higher), Dialektschwund (dialect erosion due to media/mobility), Dialektloyalität (dialect loyalty)."},"examples":[{"german":"Dialekte sind keine verderbten Formen der Standardsprache, sondern eigenständige Sprachsysteme mit eigener Geschichte und Grammatik.","english":"Dialects are not corrupt forms of the standard language but independent language systems with their own history and grammar."},{"german":"Der Rückgang regionaler Dialekte ist ein weltweites Phänomen, das mit zunehmender Mobilität und medialer Vereinheitlichung zusammenhängt.","english":"The decline of regional dialects is a worldwide phenomenon connected with increasing mobility and media standardisation."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss dialects, language prestige, and regional language varieties at B2."}}',
'{"items":[{"word":"eigenständig","translation":"independent/autonomous","pronunciation":"EY-gen-shten-dikh","example":"Eigenständiges Sprachsystem."},{"word":"verdorben","translation":"corrupt/spoilt","pronunciation":"fer-DOR-ben","example":"Verdorbene Form."},{"word":"die Vereinheitlichung","translation":"standardisation/homogenisation","pronunciation":"dee fer-YN-hyt-li-khoong","example":"Mediale Vereinheitlichung."},{"word":"zusammenhängen mit","translation":"to be connected with","pronunciation":"tsoo-ZAM-en-heng-en mit","example":"Zusammenhängen mit."},{"word":"das Phänomen","translation":"phenomenon","pronunciation":"dahs fä-no-MEN","example":"Weltweites Phänomen."},{"word":"die Mobilität","translation":"mobility","pronunciation":"dee mo-bi-li-TÄT","example":"Zunehmende Mobilität."}]}',
'{"title":"Zusammenhängen mit — to be connected with","pattern":"etwas hängt mit etwas zusammen = something is connected/linked with something (separable)","explanation":"Zusammenhängen mit (separable) = to be connected with, to be related to. Der Rückgang hängt mit Mobilität zusammen = The decline is connected with mobility. Perfect: hat zusammengehangen. Der Zusammenhang = connection, context, relation. Im Zusammenhang mit = in connection with. Aus dem Zusammenhang reißen = to take out of context. Compare: in Verbindung stehen mit (to be in connection with — more formal), verknüpft sein mit (to be linked to — more academic).","examples":[{"sentence":"Stress hängt häufig mit mangelndem Schlaf zusammen.","translation":"Stress is frequently connected with insufficient sleep."},{"sentence":"Der Anstieg der Preise hängt mit der globalen Inflation zusammen.","translation":"The rise in prices is connected with global inflation."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Eigenständig'' means?","options":["independent/autonomous","self-contained","standalone","separate"],"correctAnswer":"independent/autonomous"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Dialects are not corrupt forms of the standard language but independent language systems with their own history and grammar.","options":["Dialekte sind keine verderbten Formen der Standardsprache, sondern eigenständige Sprachsysteme mit eigener Geschichte und Grammatik.","Dialekte sind Abweichungen vom Standard.","Jeder Dialekt hat seine eigene Geschichte und Grammatik.","Dialekte und Standardsprache sind verschieden."],"correctAnswer":"Dialekte sind keine verderbten Formen der Standardsprache, sondern eigenständige Sprachsysteme mit eigener Geschichte und Grammatik."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Stress hängt häufig mit mangelndem Schlaf ___.","options":["zusammen","zusammenhängt","zusammen hängt","zusammengehangen"],"correctAnswer":"zusammen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The rise in prices is connected with global inflation","wordBankItems":["Der","Anstieg","der","Preise","hängt","mit","der","globalen","Inflation","zusammen","."],"correctAnswer":"Der Anstieg der Preise hängt mit der globalen Inflation zusammen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Vereinheitlichung'' means?","options":["standardisation/homogenisation","unification","uniformity","harmonisation"],"correctAnswer":"standardisation/homogenisation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f3',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss language acquisition at B2","Use Spracherwerb vocabulary","Talk about first and second language learning"],"explanation":{"intro":"Language acquisition vocabulary covers first language acquisition, second language learning, and theories at B2.","culturalNote":"Key concepts: Erstspracherwerb (first language acquisition — natural, unconscious), Zweitspracherwerb (second language acquisition — L2), kritische Phase (critical period hypothesis), Inputhypothese (input hypothesis — Krashen), Fossilierung (fossilisation — errors become permanent). Germany has ~5.3 million DaF/DaZ learners (Deutsch als Fremdsprache/Zweitsprache). Goethe-Institut promotes German worldwide."},"examples":[{"german":"Die Kritische-Periode-Hypothese besagt, dass Kinder bis zur Pubertät Sprachen nahezu muttersprachlich erwerben können.","english":"The critical period hypothesis states that children can acquire languages to near-native level until puberty."},{"german":"Implizites Lernen im natürlichen Sprachumfeld führt oft zu schnellerem Erwerb als explizite grammatische Instruktion im Unterricht.","english":"Implicit learning in a natural language environment often leads to faster acquisition than explicit grammar instruction in class."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss language acquisition, the critical period, and second language learning at B2."}}',
'{"items":[{"word":"besagen","translation":"to state/say","pronunciation":"beh-ZAH-gen","example":"Die Hypothese besagt."},{"word":"nahezu","translation":"nearly/almost","pronunciation":"NAH-heh-tsoo","example":"Nahezu muttersprachlich."},{"word":"implizit","translation":"implicit","pronunciation":"im-plee-TSEET","example":"Implizites Lernen."},{"word":"explizit","translation":"explicit","pronunciation":"ek-splee-TSEET","example":"Explizite Instruktion."},{"word":"die Pubertät","translation":"puberty","pronunciation":"dee poo-ber-TÄT","example":"Bis zur Pubertät."},{"word":"erwerben","translation":"to acquire","pronunciation":"er-VER-ben","example":"Eine Sprache erwerben."}]}',
'{"title":"Besagen — to state, say (of a theory, law, rule)","pattern":"etwas besagt, dass... = something states/says that (used for theories, rules, laws as subject)","explanation":"Besagen = to state, say (with a theory, law, or rule as subject — not a person). Die Hypothese besagt, dass... = The hypothesis states that... Der Vertrag besagt, dass... = The contract states that... Note: besagen has a non-personal subject — a document, rule, theory, or principle states something. Compare with sagen (person says), behaupten (person claims), postulieren (academic: to postulate). Perfect: hat besagt.","examples":[{"sentence":"Das Gesetz besagt, dass die Übergabe innerhalb von drei Tagen erfolgen muss.","translation":"The law states that the handover must take place within three days."},{"sentence":"Die Studie besagt, dass regelmäßiger Sport die Lebenserwartung erhöht.","translation":"The study states that regular exercise increases life expectancy."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Nahezu'' means?","options":["nearly/almost","approximately","about","virtually"],"correctAnswer":"nearly/almost"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The critical period hypothesis states that children can acquire languages to near-native level until puberty.","options":["Die Kritische-Periode-Hypothese besagt, dass Kinder bis zur Pubertät Sprachen nahezu muttersprachlich erwerben können.","Kinder lernen Sprachen vor der Pubertät besser.","Bis zur Pubertät kann man Sprachen wie ein Muttersprachler lernen.","Die kritische Periode endet mit der Pubertät."],"correctAnswer":"Die Kritische-Periode-Hypothese besagt, dass Kinder bis zur Pubertät Sprachen nahezu muttersprachlich erwerben können."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Gesetz besagt, dass die Übergabe innerhalb von drei Tagen erfolgen ___.","options":["muss","müsste","müssen","soll"],"correctAnswer":"muss"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The study states that regular exercise increases life expectancy","wordBankItems":["Die","Studie","besagt",",","dass","regelmäßiger","Sport","die","Lebenserwartung","erhöht","."],"correctAnswer":"Die Studie besagt , dass regelmäßiger Sport die Lebenserwartung erhöht ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Erwerben'' means?","options":["to acquire","to learn","to obtain","to gain"],"correctAnswer":"to acquire"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

-- Lesson 500: B2 Milestone 4 (xp:200, coins:100)
INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f4',1,'APPROVED','PUBLISHED',
'{"objectives":["Review B2 advanced grammar","Demonstrate mastery at lesson 500","Complete B2 Milestone 4"],"explanation":{"intro":"Herzlichen Glückwunsch! 500 lessons complete — you are now in the upper half of the German curriculum. This milestone reviews key constructions from lessons 481-500.","culturalNote":"At 500 lessons, you have covered an extraordinary range of B2 topics: philosophy, science, technology, economics, law, politics, culture, language. You command over 3,000 vocabulary items at B2 and can handle complex texts, debates, and formal writing. Key milestone: you can now engage with authentic German media (Zeit, FAZ, Spiegel) and follow academic lectures."},"examples":[{"german":"Sowohl strukturelle als auch individuelle Faktoren bestimmen sprachliche Identität, wobei die Grenzen zwischen beiden zunehmend verschwimmen.","english":"Both structural and individual factors determine linguistic identity, the boundaries between which are increasingly blurring."},{"german":"Je differenzierter das sprachliche Repertoire, desto größer die Fähigkeit, komplexe Sachverhalte präzise und nuanciert auszudrücken.","english":"The more differentiated the linguistic repertoire, the greater the ability to express complex matters precisely and with nuance."}],"rewards":{"xp":200,"coins":100},"metadata":{"estimatedMinutes":25,"canDo":"I can demonstrate mastery of advanced B2 German grammar across all domains — Milestone 4 complete!"}}',
'{"items":[{"word":"verschwimmen","translation":"to blur/become indistinct","pronunciation":"fer-SHVI-men","example":"Grenzen verschwimmen."},{"word":"das Repertoire","translation":"repertoire","pronunciation":"dahs reh-per-TVAR","example":"Sprachliches Repertoire."},{"word":"differenziert","translation":"differentiated/nuanced","pronunciation":"di-feh-ren-TSEERT","example":"Differenziertes Repertoire."},{"word":"nuanciert","translation":"nuanced","pronunciation":"noo-an-TSEERT","example":"Nuanciert ausdrücken."},{"word":"präzise","translation":"precise","pronunciation":"prä-TSEE-zeh","example":"Präzise ausdrücken."},{"word":"der Sachverhalt","translation":"matter/state of affairs","pronunciation":"dayr ZAKH-fer-halt","example":"Komplexe Sachverhalte."}]}',
'{"title":"Wobei — in the process of which / the X of which","pattern":"wobei = in which, the X of which, whereby (relative adverb — adds a sub-comment on the whole preceding clause)","explanation":"Wobei = in which/the...of which (adds a qualifying remark to the preceding clause). Faktoren bestimmen Identität, wobei die Grenzen verschwimmen = Factors determine identity, the boundaries of which are blurring. Wobei often introduces an additional nuance or complication. Compare: dabei (in the process — more consecutive), woraufhin (as a result of which — causal/consequential), wohingegen (whereas — contrasting). Wobei is very common in academic German for adding complexity.","examples":[{"sentence":"Das System funktioniert gut, wobei es gelegentlich zu Verzögerungen kommt.","translation":"The system works well, though occasional delays occur."},{"sentence":"Die Lösung ist einfach, wobei Sicherheitsbedenken berücksichtigt werden müssen.","translation":"The solution is simple, though security concerns must be taken into account."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Nuanciert'' means?","options":["nuanced","subtle","refined","detailed"],"correctAnswer":"nuanced"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The more differentiated the linguistic repertoire, the greater the ability to express complex matters precisely and with nuance.","options":["Je differenzierter das sprachliche Repertoire, desto größer die Fähigkeit, komplexe Sachverhalte präzise und nuanciert auszudrücken.","Ein reicher Wortschatz ermöglicht präzises Ausdrücken.","Je mehr Sprache man kennt, desto besser kann man sich ausdrücken.","Sprachliches Repertoire bestimmt Ausdrucksfähigkeit."],"correctAnswer":"Je differenzierter das sprachliche Repertoire, desto größer die Fähigkeit, komplexe Sachverhalte präzise und nuanciert auszudrücken."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das System funktioniert gut, wobei es gelegentlich zu Verzögerungen ___.","options":["kommt","kommen","komme","käme"],"correctAnswer":"kommt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The solution is simple though security concerns must be taken into account","wordBankItems":["Die","Lösung","ist","einfach",",","wobei","Sicherheitsbedenken","berücksichtigt","werden","müssen","."],"correctAnswer":"Die Lösung ist einfach , wobei Sicherheitsbedenken berücksichtigt werden müssen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Verschwimmen'' means?","options":["to blur/become indistinct","to fade","to dissolve","to merge"],"correctAnswer":"to blur/become indistinct"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-0000000001eb','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l491',491,'Theater und Oper','Theatre and opera','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001ec','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l492',492,'Mode und Design','Fashion and design','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001ed','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l493',493,'Sport und Gesellschaft','Sport and society','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001ee','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l494',494,'Tourismus','Tourism','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001ef','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l495',495,'Gastronomie','Gastronomy','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f0','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l496',496,'Sprache und Identität','Language and identity','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f1','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l497',497,'Mehrsprachigkeit','Multilingualism','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f2','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l498',498,'Dialekte und Varietäten','Dialects and varieties','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f3','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l499',499,'Spracherwerb','Language acquisition','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f4','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l500',500,'B2 Meilenstein 4','B2 milestone 4 — 500 lessons','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001eb' WHERE stable_ref = 'de-b2-u04-l491' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001ec' WHERE stable_ref = 'de-b2-u04-l492' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001ed' WHERE stable_ref = 'de-b2-u04-l493' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001ee' WHERE stable_ref = 'de-b2-u04-l494' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001ef' WHERE stable_ref = 'de-b2-u04-l495' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f0' WHERE stable_ref = 'de-b2-u04-l496' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f1' WHERE stable_ref = 'de-b2-u04-l497' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f2' WHERE stable_ref = 'de-b2-u04-l498' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f3' WHERE stable_ref = 'de-b2-u04-l499' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f4' WHERE stable_ref = 'de-b2-u04-l500' AND lesson_id IS NULL;
