-- V79: German B2 lessons 501-510 (B2 batch 10)
-- Hex: 501=0x1f5, 510=0x1fe

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-0000000001f5','de-b2-l501','Linguistik - Linguistics','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f6','de-b2-l502','Übersetzung - Translation','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f7','de-b2-l503','Literarische Analyse - Literary Analysis','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f8','de-b2-l504','Rhetorik - Rhetoric','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001f9','de-b2-l505','Akademisches Schreiben - Academic Writing','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001fa','de-b2-l506','Journalismus - Journalism','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001fb','de-b2-l507','Werbung und Marketing - Advertising','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001fc','de-b2-l508','Öffentlichkeitsarbeit - PR','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001fd','de-b2-l509','Kommunikationstheorie - Communication Theory','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-0000000001fe','de-b2-l510','Medienethik - Media Ethics','language','de','B2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f5',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss linguistics at B2","Use Linguistik vocabulary","Talk about language structure and meaning"],"explanation":{"intro":"Linguistics vocabulary covers phonology, morphology, syntax, semantics, and pragmatics at B2.","culturalNote":"Key subfields: Phonologie (phonology — sound systems), Morphologie (morphology — word structure), Syntax (sentence structure), Semantik (semantics — meaning), Pragmatik (pragmatics — language in context), Diskursanalyse (discourse analysis). Key German linguists: Wilhelm von Humboldt (language and thought), Ferdinand de Saussure (influential on European linguistics), Noam Chomsky''s generative grammar influential in Germany. Key journals: Zeitschrift für Sprachwissenschaft."},"examples":[{"german":"Die Pragmatik untersucht, wie Sprache in konkreten kommunikativen Situationen verwendet wird und wie Bedeutung durch Kontext und soziale Faktoren beeinflusst wird.","english":"Pragmatics studies how language is used in concrete communicative situations and how meaning is influenced by context and social factors."},{"german":"Die generative Grammatik postuliert, dass Menschen eine angeborene Sprachfähigkeit besitzen, die den Erwerb jeder natürlichen Sprache ermöglicht.","english":"Generative grammar postulates that humans possess an innate language faculty that enables the acquisition of any natural language."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss linguistics, language structure, and meaning at B2."}}',
'{"items":[{"word":"postulieren","translation":"to postulate","pronunciation":"pos-too-LEER-en","example":"Postulieren dass."},{"word":"angeboren","translation":"innate","pronunciation":"AN-geh-boh-ren","example":"Angeborene Fähigkeit."},{"word":"die Sprachfähigkeit","translation":"language faculty","pronunciation":"dee SHPRAKH-fä-ikh-kyt","example":"Sprachfähigkeit."},{"word":"ermöglichen","translation":"to enable","pronunciation":"er-MÖG-li-khen","example":"Den Erwerb ermöglichen."},{"word":"untersuchen","translation":"to study/investigate","pronunciation":"oon-ter-ZOO-khen","example":"Sprache untersuchen."},{"word":"beeinflussen","translation":"to influence","pronunciation":"beh-YN-floo-sen","example":"Bedeutung beeinflussen."}]}',
'{"title":"Postulieren — to postulate (academic assertion)","pattern":"postulieren, dass... = to postulate that (academic: assert as a theoretical premise or axiom)","explanation":"Postulieren = to postulate (academic — assert something as a theoretical premise). Die Theorie postuliert, dass... = The theory postulates that... Often used with dass-clause or an accusative object. More academic than behaupten (to claim) or annehmen (to assume). Compare: annehmen (to assume — more tentative), voraussetzten (to presuppose), unterstellen (to assume/impute — can be pejorative). Perfect: hat postuliert.","examples":[{"sentence":"Die Theorie postuliert das Vorhandensein verborgener Variablen.","translation":"The theory postulates the existence of hidden variables."},{"sentence":"Darwin postulierte, dass alle Arten einen gemeinsamen Vorfahren haben.","translation":"Darwin postulated that all species share a common ancestor."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Angeboren'' means?","options":["innate","inborn","natural","congenital"],"correctAnswer":"innate"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Generative grammar postulates that humans possess an innate language faculty that enables the acquisition of any natural language.","options":["Die generative Grammatik postuliert, dass Menschen eine angeborene Sprachfähigkeit besitzen, die den Erwerb jeder natürlichen Sprache ermöglicht.","Chomsky glaubt, dass Sprache angeboren ist.","Die Fähigkeit, Sprache zu erwerben, ist angeboren.","Jeder Mensch besitzt eine natürliche Sprachfähigkeit."],"correctAnswer":"Die generative Grammatik postuliert, dass Menschen eine angeborene Sprachfähigkeit besitzen, die den Erwerb jeder natürlichen Sprache ermöglicht."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Darwin postulierte, dass alle Arten einen gemeinsamen Vorfahren ___.","options":["haben","besitzen","teilen","hatten"],"correctAnswer":"haben"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The theory postulates the existence of hidden variables","wordBankItems":["Die","Theorie","postuliert","das","Vorhandensein","verborgener","Variablen","."],"correctAnswer":"Die Theorie postuliert das Vorhandensein verborgener Variablen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Ermöglichen'' means?","options":["to enable","to allow","to facilitate","to make possible"],"correctAnswer":"to enable"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f6',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss translation at B2","Use Übersetzung vocabulary","Talk about translation theory and practice"],"explanation":{"intro":"Translation vocabulary covers translation theory, localization, and the challenges of transferring meaning across languages at B2.","culturalNote":"Germany has a strong translation tradition: Goethe''s translation of Faust concepts influenced European translation theory. Key concepts: Äquivalenz (equivalence), Domestizierung vs. Verfremdung (domestication vs. foreignization — Schleiermacher), Lokalisierung (localisation), Fachübersetzung (technical translation), literarische Übersetzung (literary translation). Germany is the world''s 3rd largest book-publishing market; many translated books. Literary translators receive credit alongside authors."},"examples":[{"german":"Übersetzung ist nicht bloß ein linguistischer Transferprozess, sondern ein kreativer Akt der kulturellen Vermittlung, der tiefes Verständnis beider Kulturen erfordert.","english":"Translation is not merely a linguistic transfer process, but a creative act of cultural mediation that requires deep understanding of both cultures."},{"german":"Die Debatte zwischen Domestizierung und Verfremdung spiegelt unterschiedliche Auffassungen darüber wider, welchen Vorrang der Zieltext vor dem Ausgangstext haben sollte.","english":"The debate between domestication and foreignization reflects different views about what priority the target text should have over the source text."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss translation theory, cultural mediation, and translation challenges at B2."}}',
'{"items":[{"word":"die Vermittlung","translation":"mediation","pronunciation":"dee fer-MIT-loong","example":"Kulturelle Vermittlung."},{"word":"erfordern","translation":"to require","pronunciation":"er-FOR-dern","example":"Tiefes Verständnis erfordern."},{"word":"widerspiegeln","translation":"to reflect","pronunciation":"VI-der-shpee-geln","example":"Unterschiede widerspiegeln."},{"word":"die Auffassung","translation":"view/conception","pronunciation":"dee OWF-fas-oong","example":"Unterschiedliche Auffassungen."},{"word":"der Vorrang","translation":"priority/precedence","pronunciation":"dayr FOR-rang","example":"Vorrang haben."},{"word":"der Zieltext","translation":"target text","pronunciation":"dayr TSEEL-tekst","example":"Zieltext."}]}',
'{"title":"Widerspiegeln — to reflect (abstract — values, views, differences)","pattern":"etwas spiegelt etwas wider = something reflects something (separable: spiegelt...wider)","explanation":"Widerspiegeln (separable) = to reflect, mirror (for abstract things). Die Debatte spiegelt Auffassungen wider = The debate reflects views. Perfect: hat widergespiegelt. Present: spiegelt wider. Infinitive: widerzuspiegeln. NOT used for physical mirrors (there: spiegeln, reflektieren). Common in academic/intellectual contexts. Compare: zeigen (to show — direct), zum Ausdruck bringen (to express — more deliberate), verkörpern (to embody), verdeutlichen (to illustrate/clarify).","examples":[{"sentence":"Die Wahl spiegelt die Stimmung im Land wider.","translation":"The election reflects the mood in the country."},{"sentence":"Sein Werk spiegelt die gesellschaftlichen Widersprüche seiner Zeit wider.","translation":"His work reflects the social contradictions of his time."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Vermittlung'' means?","options":["mediation","communication","transfer","conveyance"],"correctAnswer":"mediation"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The debate between domestication and foreignization reflects different views about what priority the target text should have over the source text.","options":["Die Debatte zwischen Domestizierung und Verfremdung spiegelt unterschiedliche Auffassungen darüber wider, welchen Vorrang der Zieltext vor dem Ausgangstext haben sollte.","Domestizierung und Verfremdung sind gegensätzliche Übersetzungsstrategien.","Übersetzer streiten über die Priorität von Quell- und Zieltext.","Die Übersetzungsdebatte zeigt verschiedene Meinungen über Vorrang."],"correctAnswer":"Die Debatte zwischen Domestizierung und Verfremdung spiegelt unterschiedliche Auffassungen darüber wider, welchen Vorrang der Zieltext vor dem Ausgangstext haben sollte."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Wahl spiegelt die Stimmung im Land ___.","options":["wider","widerspiegelt","wieder","her"],"correctAnswer":"wider"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: His work reflects the social contradictions of his time","wordBankItems":["Sein","Werk","spiegelt","die","gesellschaftlichen","Widersprüche","seiner","Zeit","wider","."],"correctAnswer":"Sein Werk spiegelt die gesellschaftlichen Widersprüche seiner Zeit wider ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Erfordern'' means?","options":["to require","to demand","to need","to necessitate"],"correctAnswer":"to require"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f7',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss literary analysis at B2","Use Literaturwissenschaft vocabulary","Analyse themes and motifs"],"explanation":{"intro":"Literary analysis vocabulary covers narratology, motif analysis, and literary interpretation at B2.","culturalNote":"Germanistik (German studies/literary studies) is a major academic discipline. Key figures: Goethe, Schiller, Kafka, Thomas Mann, Bertolt Brecht. Key literary movements: Sturm und Drang, Klassik, Romantik, Naturalismus, Expressionismus, Neue Sachlichkeit, Trümmerliteratur (post-WWII), Gegenwartsliteratur (contemporary). Bachmannpreis (Ingeborg Bachmann Prize) is Germany''s most prestigious literary competition (Klagenfurt)."},"examples":[{"german":"Die Analyse eines literarischen Textes erschöpft sich nicht in der Inhaltsangabe, sondern zielt auf die Deutung symbolischer, struktureller und intertextueller Ebenen ab.","english":"The analysis of a literary text is not exhausted by a summary of content, but aims at the interpretation of symbolic, structural, and intertextual levels."},{"german":"Das Motiv der Heimatlosigkeit zieht sich wie ein roter Faden durch Kafkas Werk und verweist auf das existenzielle Fremdsein des modernen Subjekts.","english":"The motif of homelessness runs like a red thread through Kafka''s work and refers to the existential alienness of the modern subject."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss literary analysis, motifs, and textual interpretation at B2."}}',
'{"items":[{"word":"sich erschöpfen in","translation":"to be exhausted by/consist merely of","pronunciation":"zikh er-SHÖP-fen in","example":"Sich nicht in Inhaltsangabe erschöpfen."},{"word":"abzielen auf","translation":"to aim at","pronunciation":"AP-tsee-len owf","example":"Auf Deutung abzielen."},{"word":"intertextuell","translation":"intertextual","pronunciation":"in-ter-teks-too-EL","example":"Intertextuelle Ebene."},{"word":"das Motiv","translation":"motif","pronunciation":"dahs mo-TEEF","example":"Das Motiv der Heimatlosigkeit."},{"word":"verweisen auf","translation":"to refer to/point to","pronunciation":"fer-VY-zen owf","example":"Auf etwas verweisen."},{"word":"wie ein roter Faden","translation":"like a red thread (recurring theme)","pronunciation":"vee yn ROH-ter FAH-den","example":"Wie ein roter Faden."}]}',
'{"title":"Sich erschöpfen in — to be exhausted by, to consist merely of","pattern":"etwas erschöpft sich in D = something is exhausted by, is limited to (no more than)","explanation":"Sich erschöpfen in + dative = to be exhausted by, to consist merely of, to amount to no more than. Die Analyse erschöpft sich nicht in der Inhaltsangabe = The analysis does not consist merely of a content summary (implies there is more to it). The not-form (erschöpft sich nicht in X, sondern...) sets up a contrast: X is insufficient; what follows is the real thing. Perfect: hat sich erschöpft. Compare: beschränken auf (to limit to — deliberate constraint), bestehen aus (to consist of — neutral), reduzieren auf (to reduce to — criticises oversimplification).","examples":[{"sentence":"Seine Kompetenz erschöpft sich nicht im technischen Bereich.","translation":"His competence is not limited to the technical domain."},{"sentence":"Das Problem erschöpft sich nicht in fehlenden Ressourcen.","translation":"The problem does not consist merely of a lack of resources."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Intertextuell'' means?","options":["intertextual","between texts","cross-referencing","textual cross-reference"],"correctAnswer":"intertextual"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The analysis of a literary text is not exhausted by a summary of content, but aims at the interpretation of symbolic, structural, and intertextual levels.","options":["Die Analyse eines literarischen Textes erschöpft sich nicht in der Inhaltsangabe, sondern zielt auf die Deutung symbolischer, struktureller und intertextueller Ebenen ab.","Literarische Analyse ist mehr als eine Zusammenfassung.","Man muss Symbole und Struktur bei der Textanalyse berücksichtigen.","Texte haben symbolische und intertextuelle Bedeutungsebenen."],"correctAnswer":"Die Analyse eines literarischen Textes erschöpft sich nicht in der Inhaltsangabe, sondern zielt auf die Deutung symbolischer, struktureller und intertextueller Ebenen ab."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Seine Kompetenz erschöpft sich nicht im technischen ___.","options":["Bereich","Gebiet","Feld","Bereich"],"correctAnswer":"Bereich"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The problem does not consist merely of a lack of resources","wordBankItems":["Das","Problem","erschöpft","sich","nicht","in","fehlenden","Ressourcen","."],"correctAnswer":"Das Problem erschöpft sich nicht in fehlenden Ressourcen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Verweisen auf'' means?","options":["to refer to/point to","to indicate","to allude to","to point at"],"correctAnswer":"to refer to/point to"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f8',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss rhetoric at B2","Use Rhetorik vocabulary","Identify rhetorical devices"],"explanation":{"intro":"Rhetoric vocabulary covers argumentation, rhetorical devices, and persuasive language at B2.","culturalNote":"Classical rhetoric (from ancient Greece/Rome) was central to German Bildung (education). Key figures: Aristotle (Ethos, Pathos, Logos — the three proofs), Cicero. Modern rhetoric: political speeches, advertising, academic argumentation. Key devices in German: Metapher, Allegorie, Ironie, Hyperbel, Antithese, Anapher (anaphora — repetition at start of clauses), Klimax (climax — ascending series). Rhetorik is a university subject in Germany."},"examples":[{"german":"Rhetorische Figuren dienen nicht bloß dem Schmuck der Rede, sondern erfüllen eine argumentative Funktion, indem sie Gedanken verdichten und emotional verstärken.","english":"Rhetorical figures do not merely serve to ornament speech, but fulfil an argumentative function, by condensing thoughts and emotionally reinforcing them."},{"german":"Die Anapher verstärkt durch die Wiederholung eines Wortes oder einer Phrase am Satzbeginn die rhythmische Wirkung und betont die thematische Kohärenz.","english":"Anaphora reinforces through the repetition of a word or phrase at the start of sentences the rhythmic effect and emphasises thematic coherence."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss rhetoric, rhetorical devices, and persuasive language at B2."}}',
'{"items":[{"word":"verdichten","translation":"to condense/compress","pronunciation":"fer-DIKH-ten","example":"Gedanken verdichten."},{"word":"verstärken","translation":"to reinforce/intensify","pronunciation":"fer-SHTER-ken","example":"Emotional verstärken."},{"word":"die Anapher","translation":"anaphora","pronunciation":"dee ah-NAH-fer","example":"Die Anapher."},{"word":"die Kohärenz","translation":"coherence","pronunciation":"dee ko-hä-RENTS","example":"Thematische Kohärenz."},{"word":"betonen","translation":"to emphasise","pronunciation":"beh-TOH-nen","example":"Kohärenz betonen."},{"word":"der Schmuck","translation":"ornament/decoration","pronunciation":"dayr shmook","example":"Schmuck der Rede."}]}',
'{"title":"Indem — by (doing), in that (means/method clause)","pattern":"indem + V-final (same or different subject) = by (doing), in that — expresses how something is achieved","explanation":"Indem + V-final = by doing, in that, through the act of (expresses the MEANS by which the main clause is achieved). Figuren erfüllen eine Funktion, indem sie Gedanken verdichten = Figures fulfil a function by condensing thoughts. Indem clause has its own subject (same as main or different). Compare: dadurch dass (by the fact that — same meaning but slightly heavier), durch + noun (through + noun — simpler), wobei (adding a qualifier without specifying means), damit (in order that — purpose, not means).","examples":[{"sentence":"Er verbesserte sein Deutsch, indem er täglich Zeitung las.","translation":"He improved his German by reading the newspaper every day."},{"sentence":"Das System funktioniert, indem es alle Anfragen zentral verarbeitet.","translation":"The system works by centrally processing all requests."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Verdichten'' means?","options":["to condense/compress","to concentrate","to compress","to consolidate"],"correctAnswer":"to condense/compress"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Rhetorical figures do not merely serve to ornament speech, but fulfil an argumentative function, by condensing thoughts and emotionally reinforcing them.","options":["Rhetorische Figuren dienen nicht bloß dem Schmuck der Rede, sondern erfüllen eine argumentative Funktion, indem sie Gedanken verdichten und emotional verstärken.","Rhetorische Figuren schmücken nicht nur die Sprache, sie haben auch Argumente.","Figuren helfen dabei, Gedanken zu komprimieren und zu verstärken.","Rhetoric hat sowohl ästhetische als auch argumentative Funktionen."],"correctAnswer":"Rhetorische Figuren dienen nicht bloß dem Schmuck der Rede, sondern erfüllen eine argumentative Funktion, indem sie Gedanken verdichten und emotional verstärken."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Er verbesserte sein Deutsch, indem er täglich Zeitung ___.","options":["las","liest","lasen","gelesen"],"correctAnswer":"las"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The system works by centrally processing all requests","wordBankItems":["Das","System","funktioniert",",","indem","es","alle","Anfragen","zentral","verarbeitet","."],"correctAnswer":"Das System funktioniert , indem es alle Anfragen zentral verarbeitet ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Kohärenz'' means?","options":["coherence","consistency","cohesion","unity"],"correctAnswer":"coherence"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001f9',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss academic writing at B2","Use akademisches Schreiben vocabulary","Write at B2 academic register"],"explanation":{"intro":"Academic writing vocabulary covers text types, citation, argumentation, and academic register at B2.","culturalNote":"German academic writing style (Wissenschaftsstil): objectivity, nominalization, passive voice, hedging, complex sentences. Key concepts: Zitat (quote), Paraphrase (paraphrase), Plagiat (plagiarism — serious academic offence), Fußnote (footnote), Literaturverzeichnis (bibliography), Quellenangabe (citation), These (thesis/argument), Argumentation, Belegen (to substantiate). German universities use VG/BG citation styles (depending on discipline)."},"examples":[{"german":"Akademisches Schreiben zeichnet sich durch Objektivität, sprachliche Präzision und den systematischen Einsatz von Belegen und Zitaten aus.","english":"Academic writing is characterised by objectivity, linguistic precision, and the systematic use of substantiating evidence and citations."},{"german":"Um eine überzeugende wissenschaftliche Argumentation aufzubauen, ist es notwendig, die eigene These klar zu formulieren und durch empirische Belege oder logische Schlussfolgerungen zu stützen.","english":"In order to build a convincing academic argument, it is necessary to formulate one''s own thesis clearly and to support it with empirical evidence or logical conclusions."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss academic writing, citation, and argumentation at B2."}}',
'{"items":[{"word":"sich auszeichnen durch","translation":"to be characterised by","pronunciation":"zikh OWS-tsykh-nen doorkh","example":"Sich durch Präzision auszeichnen."},{"word":"der Einsatz","translation":"use/deployment","pronunciation":"dayr YN-zats","example":"Systematischer Einsatz."},{"word":"der Beleg","translation":"evidence/substantiation","pronunciation":"dayr beh-LAYK","example":"Belege anführen."},{"word":"die Schlussfolgerung","translation":"conclusion","pronunciation":"dee SHLOOS-fol-geh-roong","example":"Logische Schlussfolgerung."},{"word":"stützen","translation":"to support/underpin","pronunciation":"SHTÜT-sen","example":"Die These stützen."},{"word":"überzeugend","translation":"convincing","pronunciation":"ü-ber-TSOY-gend","example":"Überzeugende Argumentation."}]}',
'{"title":"Sich auszeichnen durch — to be characterised by, to distinguish oneself by","pattern":"sich auszeichnen durch + accusative = to be characterised by, to be distinguished by","explanation":"Sich auszeichnen durch + accusative = to be characterised by, to stand out through, to be distinguished by. Akademisches Schreiben zeichnet sich durch Objektivität aus = Academic writing is characterised by objectivity. Can describe people or things. The positive connotation is stronger than gekennzeichnet sein durch (more neutral/academic). Perfect: hat sich ausgezeichnet. Compare: gekennzeichnet sein durch (to be characterised by — more neutral, often negative traits too), geprägt sein durch (to be marked/shaped by — often historical), sich abheben durch (to stand out by).","examples":[{"sentence":"Das Restaurant zeichnet sich durch frische, regionale Zutaten aus.","translation":"The restaurant is characterised by fresh, regional ingredients."},{"sentence":"Sie zeichnet sich durch ihre Fähigkeit aus, komplexe Sachverhalte verständlich zu erklären.","translation":"She is distinguished by her ability to explain complex matters in an understandable way."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Einsatz'' means?","options":["use/deployment","application","effort","input"],"correctAnswer":"use/deployment"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Academic writing is characterised by objectivity, linguistic precision, and the systematic use of substantiating evidence and citations.","options":["Akademisches Schreiben zeichnet sich durch Objektivität, sprachliche Präzision und den systematischen Einsatz von Belegen und Zitaten aus.","Akademisches Schreiben muss objektiv und präzise sein.","Belege und Zitate sind wichtig beim akademischen Schreiben.","Wissenschaftliche Texte zeichnen sich durch Genauigkeit aus."],"correctAnswer":"Akademisches Schreiben zeichnet sich durch Objektivität, sprachliche Präzision und den systematischen Einsatz von Belegen und Zitaten aus."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Restaurant zeichnet sich durch frische, regionale Zutaten ___.","options":["aus","hervor","ab","auf"],"correctAnswer":"aus"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: She is distinguished by her ability to explain complex matters clearly","wordBankItems":["Sie","zeichnet","sich","durch","ihre","Fähigkeit","aus",",","komplexe","Sachverhalte","verständlich","zu","erklären","."],"correctAnswer":"Sie zeichnet sich durch ihre Fähigkeit aus , komplexe Sachverhalte verständlich zu erklären ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Stützen'' means?","options":["to support/underpin","to prop up","to sustain","to back"],"correctAnswer":"to support/underpin"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001fa',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss journalism at B2","Use Journalismus vocabulary","Talk about media and press freedom"],"explanation":{"intro":"Journalism vocabulary covers press freedom, quality journalism, and the media landscape at B2.","culturalNote":"German press landscape: Öffentlich-rechtliche Medien (public broadcasting — ARD, ZDF, Deutsche Welle), Privatfernsehen (private TV), Tageszeitungen (daily newspapers — FAZ, Süddeutsche Zeitung, Die Zeit, Die Welt, taz). Key issues: Pressefreiheit (press freedom), Fake News, Filterblasen (filter bubbles), Qualitätsjournalismus vs. Boulevardjournalismus. Axel Springer SE = large private media group. Reporters Without Borders: Germany typically ranks around 10th in press freedom."},"examples":[{"german":"Qualitätsjournalismus erfüllt eine demokratische Wächterfunktion, indem er Machtverhältnisse kontrolliert, Missstände aufdeckt und Bürger mit zuverlässigen Informationen versorgt.","english":"Quality journalism fulfils a democratic watchdog function by controlling power relations, uncovering abuses, and supplying citizens with reliable information."},{"german":"Die Konzentration von Medienbesitz in wenigen Händen gefährdet die Meinungsvielfalt und die Unabhängigkeit redaktioneller Entscheidungen.","english":"The concentration of media ownership in few hands endangers the diversity of opinion and the independence of editorial decisions."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss journalism, press freedom, and the media landscape at B2."}}',
'{"items":[{"word":"die Wächterfunktion","translation":"watchdog function","pronunciation":"dee VEKH-ter-foonk-tsyohn","example":"Demokratische Wächterfunktion."},{"word":"aufdecken","translation":"to uncover/expose","pronunciation":"OWF-dek-en","example":"Missstände aufdecken."},{"word":"der Missstand","translation":"abuse/grievance","pronunciation":"dayr MIS-shtant","example":"Missstände aufdecken."},{"word":"versorgen mit","translation":"to supply with","pronunciation":"fer-ZOR-gen mit","example":"Mit Informationen versorgen."},{"word":"gefährden","translation":"to endanger/threaten","pronunciation":"geh-FÄR-den","example":"Die Vielfalt gefährden."},{"word":"redaktionell","translation":"editorial","pronunciation":"reh-dak-tsyo-NEL","example":"Redaktionelle Entscheidungen."}]}',
'{"title":"Aufdecken — to uncover, expose (separable — abuses, crimes, secrets)","pattern":"etwas aufdecken = to uncover, expose, reveal (separable — especially scandals, wrongs, hidden truths)","explanation":"Aufdecken (separable) = to uncover, expose (separable — for hidden problems, abuses, scandals). Missstände aufdecken = to expose abuses. Einen Betrug aufdecken = to expose a fraud. Present: deckt auf. Perfect: hat aufgedeckt. Negative connotation of what is uncovered. Compare: enthüllen (to reveal/unveil — more dramatic, also positive), ans Licht bringen (to bring to light — more journalistic), herausfinden (to find out — more neutral), aufklären (to investigate/clear up — more about solving).","examples":[{"sentence":"Die Reportage deckte gravierende Mängel im Gesundheitssystem auf.","translation":"The reportage exposed serious deficiencies in the healthcare system."},{"sentence":"Investigativer Journalismus deckt auf, was die Mächtigen lieber verbergen würden.","translation":"Investigative journalism uncovers what the powerful would prefer to conceal."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Wächterfunktion'' means?","options":["watchdog function","guardian function","oversight role","monitoring function"],"correctAnswer":"watchdog function"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Quality journalism fulfils a democratic watchdog function by controlling power relations, uncovering abuses, and supplying citizens with reliable information.","options":["Qualitätsjournalismus erfüllt eine demokratische Wächterfunktion, indem er Machtverhältnisse kontrolliert, Missstände aufdeckt und Bürger mit zuverlässigen Informationen versorgt.","Guter Journalismus deckt Probleme auf und informiert die Bevölkerung.","Journalismus kontrolliert die Macht und schützt die Demokratie.","Die Presse hat eine demokratische Kontrollaufgabe."],"correctAnswer":"Qualitätsjournalismus erfüllt eine demokratische Wächterfunktion, indem er Machtverhältnisse kontrolliert, Missstände aufdeckt und Bürger mit zuverlässigen Informationen versorgt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Reportage deckte gravierende Mängel im Gesundheitssystem ___.","options":["auf","hervor","bloß","ans Licht"],"correctAnswer":"auf"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Investigative journalism uncovers what the powerful would prefer to conceal","wordBankItems":["Investigativer","Journalismus","deckt","auf",",","was","die","Mächtigen","lieber","verbergen","würden","."],"correctAnswer":"Investigativer Journalismus deckt auf , was die Mächtigen lieber verbergen würden ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Gefährden'' means?","options":["to endanger/threaten","to jeopardise","to put at risk","to harm"],"correctAnswer":"to endanger/threaten"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001fb',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss advertising at B2","Use Werbung vocabulary","Talk about marketing and consumer behaviour"],"explanation":{"intro":"Advertising and marketing vocabulary covers consumer behaviour, brand communication, and digital marketing at B2.","culturalNote":"Germany advertising law is strict: Werbung muss als solche erkennbar sein (ads must be identifiable as such). Influencer-Marketing disclosure rules. Key concepts: Marke (brand), Zielgruppe (target group), Markenkommunikation (brand communication), virales Marketing (viral marketing), Greenwashing (false eco-claims), Schleichwerbung (covert advertising). Advertising association: GWA (Gesamtverband Kommunikationsagenturen)."},"examples":[{"german":"Moderne Werbung operiert nicht mehr allein über rationale Produktargumente, sondern über emotionale Markenwelten, die Identifikation und Zugehörigkeit vermitteln.","english":"Modern advertising operates no longer through rational product arguments alone, but through emotional brand worlds that convey identification and a sense of belonging."},{"german":"Das Phänomen des Greenwashings zeigt, wie Unternehmen ökologische Sensibilität instrumentalisieren, um ihr Image zu verbessern, ohne tatsächliche Nachhaltigkeit zu erreichen.","english":"The phenomenon of greenwashing shows how companies instrumentalise ecological sensitivity in order to improve their image without achieving actual sustainability."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss advertising, brand communication, and greenwashing at B2."}}',
'{"items":[{"word":"operieren","translation":"to operate/function","pronunciation":"o-peh-REER-en","example":"Über Markenwelten operieren."},{"word":"vermitteln","translation":"to convey/mediate","pronunciation":"fer-MIT-eln","example":"Identifikation vermitteln."},{"word":"instrumentalisieren","translation":"to instrumentalise","pronunciation":"in-stroo-men-tah-li-ZEER-en","example":"Sensibilität instrumentalisieren."},{"word":"tatsächlich","translation":"actual/real/in reality","pronunciation":"TAT-zekh-likh","example":"Tatsächliche Nachhaltigkeit."},{"word":"die Markenwelt","translation":"brand world","pronunciation":"dee MAR-ken-velt","example":"Emotionale Markenwelt."},{"word":"die Sensibilität","translation":"sensitivity","pronunciation":"dee zen-si-bi-li-TÄT","example":"Ökologische Sensibilität."}]}',
'{"title":"Nicht mehr ... sondern — no longer ... but (corrective negation)","pattern":"nicht mehr X, sondern Y = no longer X, but Y (replaces an old state with a new one)","explanation":"Nicht mehr...sondern = no longer...but (replaces what was previously true with the new reality). Werbung operiert nicht mehr über rationale Argumente, sondern über emotionale Markenwelten = Advertising operates no longer through rational arguments but through emotional brand worlds. Key: nicht mehr signals a change from a prior state; sondern introduces the new/current state. Compare: nicht...sondern (simple denial + correction), nicht mehr...als (no longer...than — comparison), schon nicht mehr (already no longer — emphasises earliness of change).","examples":[{"sentence":"Das Unternehmen setzt nicht mehr auf Massenproduktion, sondern auf individuelle Fertigung.","translation":"The company no longer relies on mass production but on individual manufacturing."},{"sentence":"Kommunikation findet nicht mehr nur per Post statt, sondern überwiegend digital.","translation":"Communication no longer takes place only by post but predominantly digitally."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Instrumentalisieren'' means?","options":["to instrumentalise","to use as a tool","to exploit","to manipulate"],"correctAnswer":"to instrumentalise"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Modern advertising operates no longer through rational product arguments alone, but through emotional brand worlds that convey identification and a sense of belonging.","options":["Moderne Werbung operiert nicht mehr allein über rationale Produktargumente, sondern über emotionale Markenwelten, die Identifikation und Zugehörigkeit vermitteln.","Werbung nutzt heute Gefühle statt Argumente.","Moderne Werbung baut auf Markenidentität und Zugehörigkeit.","Produktwerbung ist nicht mehr rational, sondern emotional."],"correctAnswer":"Moderne Werbung operiert nicht mehr allein über rationale Produktargumente, sondern über emotionale Markenwelten, die Identifikation und Zugehörigkeit vermitteln."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Unternehmen setzt nicht mehr auf Massenproduktion, sondern auf individuelle ___.","options":["Fertigung","Produktion","Herstellung","Fabrikation"],"correctAnswer":"Fertigung"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Communication no longer takes place only by post but predominantly digitally","wordBankItems":["Kommunikation","findet","nicht","mehr","nur","per","Post","statt",",","sondern","überwiegend","digital","."],"correctAnswer":"Kommunikation findet nicht mehr nur per Post statt , sondern überwiegend digital ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Tatsächlich'' means?","options":["actual/real","indeed","genuinely","effectively"],"correctAnswer":"actual/real"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001fc',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss public relations at B2","Use Öffentlichkeitsarbeit vocabulary","Talk about corporate communications"],"explanation":{"intro":"Public relations vocabulary covers crisis communication, reputation management, and stakeholder relations at B2.","culturalNote":"Öffentlichkeitsarbeit (PR) and Unternehmenskommunikation (corporate communications) are important fields. Key aspects: Krisenmanagement (crisis management), Reputationsmanagement (reputation management), Stakeholder-Kommunikation, Corporate Social Responsibility (CSR), Pressemitteilung (press release), Sprecherin/Sprecher (spokesperson). Key principle: authentische Kommunikation (authentic communication) increasingly expected."},"examples":[{"german":"Krisenmanagement in der Unternehmenskommunikation erfordert schnelles, transparentes Handeln, um das Vertrauen der Öffentlichkeit und der Stakeholder nicht zu verspielen.","english":"Crisis management in corporate communications requires swift, transparent action so as not to forfeit the trust of the public and stakeholders."},{"german":"CSR geht über Philanthropie hinaus und zielt darauf ab, soziale und ökologische Verantwortung in die Geschäftsstrategie zu integrieren.","english":"CSR goes beyond philanthropy and aims to integrate social and ecological responsibility into the business strategy."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss PR, crisis communication, and CSR at B2."}}',
'{"items":[{"word":"verspielen","translation":"to forfeit/gamble away","pronunciation":"fer-SHPEE-len","example":"Vertrauen verspielen."},{"word":"transparent","translation":"transparent","pronunciation":"trans-pah-RENT","example":"Transparentes Handeln."},{"word":"die Philanthropie","translation":"philanthropy","pronunciation":"dee fi-lan-thro-PEE","example":"Über Philanthropie hinausgehen."},{"word":"hinausgehen über","translation":"to go beyond","pronunciation":"hi-NOWS-gay-en ü-ber","example":"Über etwas hinausgehen."},{"word":"integrieren","translation":"to integrate","pronunciation":"in-teh-GREER-en","example":"In die Strategie integrieren."},{"word":"das Vertrauen","translation":"trust","pronunciation":"dahs fer-TROW-en","example":"Vertrauen der Öffentlichkeit."}]}',
'{"title":"Hinausgehen über — to go beyond (separable)","pattern":"etwas geht über etwas (Akk.) hinaus = something goes beyond something","explanation":"Hinausgehen über + accusative (separable) = to go beyond. CSR geht über Philanthropie hinaus = CSR goes beyond philanthropy. Present: geht hinaus über. Perfect: ist hinausgegangen über. The verb is separable: geht...hinaus. This expresses that something exceeds/surpasses a boundary or category. Compare: überschreiten (to exceed/overstep — often a limit or boundary), übersteigen (to exceed — often quantities, numbers), überragen (to surpass/exceed — often figurative excellence).","examples":[{"sentence":"Die Bedeutung der Entscheidung geht weit über den Einzelfall hinaus.","translation":"The significance of the decision goes far beyond the individual case."},{"sentence":"Sein Einfluss ging weit über Deutschland hinaus.","translation":"His influence extended far beyond Germany."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Verspielen'' means?","options":["to forfeit/gamble away","to lose","to waste","to squander"],"correctAnswer":"to forfeit/gamble away"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"CSR goes beyond philanthropy and aims to integrate social and ecological responsibility into the business strategy.","options":["CSR geht über Philanthropie hinaus und zielt darauf ab, soziale und ökologische Verantwortung in die Geschäftsstrategie zu integrieren.","CSR bedeutet mehr als nur spenden.","Unternehmen müssen soziale und ökologische Verantwortung übernehmen.","CSR integriert Nachhaltigkeit in die Unternehmensstrategie."],"correctAnswer":"CSR geht über Philanthropie hinaus und zielt darauf ab, soziale und ökologische Verantwortung in die Geschäftsstrategie zu integrieren."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Bedeutung der Entscheidung geht weit über den Einzelfall ___.","options":["hinaus","raus","hinüber","weiter"],"correctAnswer":"hinaus"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: His influence extended far beyond Germany","wordBankItems":["Sein","Einfluss","ging","weit","über","Deutschland","hinaus","."],"correctAnswer":"Sein Einfluss ging weit über Deutschland hinaus ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Integrieren'' means?","options":["to integrate","to incorporate","to include","to embed"],"correctAnswer":"to integrate"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001fd',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss communication theory at B2","Use Kommunikationstheorie vocabulary","Talk about models of communication"],"explanation":{"intro":"Communication theory vocabulary covers communication models, sender-receiver, and discourse theory at B2.","culturalNote":"Key communication models taught in German universities: Shannon-Weaver Modell (sender, Kanal, Empfänger, Rauschen), Schulz von Thun Vier-Seiten-Modell (4-sides model — Sachebene, Beziehungsebene, Selbstoffenbarung, Appell — influential in German corporate communication), Watzlawicks Axiome (5 axioms of communication — Man kann nicht nicht kommunizieren = One cannot not communicate). Key journals: Publizistik."},"examples":[{"german":"Das Vier-Seiten-Modell veranschaulicht, dass jede Aussage gleichzeitig Sach-, Beziehungs-, Selbstoffenbarungs- und Appellebene enthält.","english":"The four-sides model illustrates that every statement simultaneously contains a factual, relational, self-disclosure, and appeal level."},{"german":"Missverstehen entsteht häufig dann, wenn Sender und Empfänger unterschiedliche Ohren für unterschiedliche Botschaftsebenen aktivieren.","english":"Misunderstanding frequently arises when sender and receiver activate different ears for different message levels."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss communication theory, communication models, and miscommunication at B2."}}',
'{"items":[{"word":"veranschaulichen","translation":"to illustrate","pronunciation":"fer-AN-show-li-khen","example":"Ein Modell veranschaulichen."},{"word":"gleichzeitig","translation":"simultaneously","pronunciation":"GLYKH-tsy-tikh","example":"Gleichzeitig enthalten."},{"word":"enthalten","translation":"to contain","pronunciation":"ent-HAL-ten","example":"Mehrere Ebenen enthalten."},{"word":"das Missverständnis","translation":"misunderstanding","pronunciation":"dahs MIS-fer-shtent-nis","example":"Missverständnis entstehen lassen."},{"word":"aktivieren","translation":"to activate","pronunciation":"ak-ti-VEER-en","example":"Unterschiedliche Ohren aktivieren."},{"word":"die Botschaft","translation":"message","pronunciation":"dee BOT-shaft","example":"Unterschiedliche Botschaften."}]}',
'{"title":"Veranschaulichen — to illustrate, make visible (abstract concepts)","pattern":"etwas veranschaulicht etwas = something illustrates/visualises something (makes abstract visible)","explanation":"Veranschaulichen = to illustrate, make tangible, visualise (for making abstract ideas concrete). Das Modell veranschaulicht, dass... = The model illustrates that... Compare: zeigen (to show — more general), darstellen (to represent/show — for diagrams/tables), verdeutlichen (to clarify — makes something clearer), demonstrieren (to demonstrate — active), erklären (to explain — broader). Veranschaulichen implies making something visual or tangible that is otherwise abstract.","examples":[{"sentence":"Das Diagramm veranschaulicht den Rückgang der Artenvielfalt.","translation":"The diagram illustrates the decline in biodiversity."},{"sentence":"Das Beispiel veranschaulicht, wie komplex das Problem ist.","translation":"The example illustrates how complex the problem is."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Botschaft'' means?","options":["message","communication","content","information"],"correctAnswer":"message"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The four-sides model illustrates that every statement simultaneously contains a factual, relational, self-disclosure, and appeal level.","options":["Das Vier-Seiten-Modell veranschaulicht, dass jede Aussage gleichzeitig Sach-, Beziehungs-, Selbstoffenbarungs- und Appellebene enthält.","Jede Aussage hat vier verschiedene Bedeutungsebenen.","Das Modell zeigt die vier Ebenen der Kommunikation.","Kommunikation hat immer mehrere Botschaftsebenen."],"correctAnswer":"Das Vier-Seiten-Modell veranschaulicht, dass jede Aussage gleichzeitig Sach-, Beziehungs-, Selbstoffenbarungs- und Appellebene enthält."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Diagramm veranschaulicht den Rückgang der ___.","options":["Artenvielfalt","Biodiversität","Tierarten","Vielfalt"],"correctAnswer":"Artenvielfalt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The example illustrates how complex the problem is","wordBankItems":["Das","Beispiel","veranschaulicht",",","wie","komplex","das","Problem","ist","."],"correctAnswer":"Das Beispiel veranschaulicht , wie komplex das Problem ist ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Aktivieren'' means?","options":["to activate","to trigger","to engage","to stimulate"],"correctAnswer":"to activate"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001fe',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss media ethics at B2","Use Medienethik vocabulary","Talk about ethical issues in journalism"],"explanation":{"intro":"Media ethics vocabulary covers journalistic ethics, privacy, and responsibility at B2.","culturalNote":"Pressekodex (Press Code) = German press self-regulation (16 guidelines from Presserat/Press Council). Key principles: Wahrhaftigkeit (truthfulness), Sorgfaltspflicht (duty of care), Persönlichkeitsschutz (protection of personal rights), Diskriminierungsverbot (anti-discrimination). Key ethical debates: Opferschutz (protection of victims), Suizidberichterstattung (suicide reporting guidelines), Bildrechte (image rights), Datenschutz in Medien."},"examples":[{"german":"Medienethik steht vor dem Spannungsverhältnis zwischen dem Informationsrecht der Öffentlichkeit und dem Schutz der Privatsphäre und Würde des Einzelnen.","english":"Media ethics faces the tension between the public''s right to information and the protection of the privacy and dignity of the individual."},{"german":"Die Sorgfaltspflicht verpflichtet Journalisten, die Richtigkeit ihrer Informationen vor der Veröffentlichung zu überprüfen und Quellen kritisch zu bewerten.","english":"The duty of care obliges journalists to verify the accuracy of their information before publication and to critically evaluate sources."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss media ethics, journalistic responsibility, and press freedom at B2."}}',
'{"items":[{"word":"das Spannungsverhältnis","translation":"tension/tension relationship","pronunciation":"dahs SHPAN-oonks-fer-hält-nis","example":"Im Spannungsverhältnis stehen."},{"word":"verpflichten","translation":"to oblige/commit","pronunciation":"fer-PFLIKHT-en","example":"Journalisten verpflichten."},{"word":"überprüfen","translation":"to verify/check","pronunciation":"ü-ber-PRÜF-en","example":"Informationen überprüfen."},{"word":"bewerten","translation":"to evaluate","pronunciation":"beh-VER-ten","example":"Quellen bewerten."},{"word":"die Würde","translation":"dignity","pronunciation":"dee VÜR-deh","example":"Würde des Einzelnen."},{"word":"die Privatsphäre","translation":"privacy","pronunciation":"dee pri-VAT-sfä-reh","example":"Privatsphäre schützen."}]}',
'{"title":"Verpflichten zu — to oblige to, commit to (someone/something)","pattern":"jemanden zu etwas verpflichten = to oblige someone to do something; sich zu etwas verpflichten = to commit oneself to","explanation":"Verpflichten = to oblige (someone) to do something. Die Sorgfaltspflicht verpflichtet Journalisten, zu überprüfen = The duty of care obliges journalists to verify. Construction: verpflichten + accusative (person) + zu + infinitive OR verpflichten + accusative (person) + Infinitiv (direct). Reflexive: sich verpflichten, etw. zu tun = to commit oneself to doing. Die Verpflichtung = obligation. Verpflichtet sein = to be obliged/committed. Compare: zwingen (to force — stronger compulsion), auffordern (to request/call upon — weaker), veranlassen (to cause/induce).","examples":[{"sentence":"Die Vereinbarung verpflichtet beide Seiten, die Ergebnisse vertraulich zu behandeln.","translation":"The agreement obliges both sides to treat the results confidentially."},{"sentence":"Wir haben uns verpflichtet, alle Mitarbeiter fair zu entlohnen.","translation":"We have committed ourselves to paying all employees fairly."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Spannungsverhältnis'' means?","options":["tension/tension relationship","conflict","contradiction","opposition"],"correctAnswer":"tension/tension relationship"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The duty of care obliges journalists to verify the accuracy of their information before publication and to critically evaluate sources.","options":["Die Sorgfaltspflicht verpflichtet Journalisten, die Richtigkeit ihrer Informationen vor der Veröffentlichung zu überprüfen und Quellen kritisch zu bewerten.","Journalisten müssen ihre Informationen überprüfen.","Sorgfalt bedeutet, Quellen zu überprüfen und Fehler zu vermeiden.","Journalisten haben die Pflicht, korrekt zu berichten."],"correctAnswer":"Die Sorgfaltspflicht verpflichtet Journalisten, die Richtigkeit ihrer Informationen vor der Veröffentlichung zu überprüfen und Quellen kritisch zu bewerten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Vereinbarung verpflichtet beide Seiten, die Ergebnisse vertraulich zu ___.","options":["behandeln","halten","handhaben","bewahren"],"correctAnswer":"behandeln"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We have committed ourselves to paying all employees fairly","wordBankItems":["Wir","haben","uns","verpflichtet",",","alle","Mitarbeiter","fair","zu","entlohnen","."],"correctAnswer":"Wir haben uns verpflichtet , alle Mitarbeiter fair zu entlohnen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Überprüfen'' means?","options":["to verify/check","to inspect","to review","to audit"],"correctAnswer":"to verify/check"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-0000000001f5','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l501',501,'Linguistik','Linguistics','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f6','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l502',502,'Übersetzung','Translation','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f7','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l503',503,'Literarische Analyse','Literary analysis','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f8','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l504',504,'Rhetorik','Rhetoric','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001f9','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l505',505,'Akademisches Schreiben','Academic writing','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001fa','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l506',506,'Journalismus','Journalism','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001fb','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l507',507,'Werbung und Marketing','Advertising and marketing','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001fc','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l508',508,'Öffentlichkeitsarbeit','Public relations','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001fd','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l509',509,'Kommunikationstheorie','Communication theory','PUBLISHED'),
('dd000000-0000-0000-0000-0000000001fe','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l510',510,'Medienethik','Media ethics','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f5' WHERE stable_ref = 'de-b2-u04-l501' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f6' WHERE stable_ref = 'de-b2-u04-l502' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f7' WHERE stable_ref = 'de-b2-u04-l503' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f8' WHERE stable_ref = 'de-b2-u04-l504' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001f9' WHERE stable_ref = 'de-b2-u04-l505' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001fa' WHERE stable_ref = 'de-b2-u04-l506' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001fb' WHERE stable_ref = 'de-b2-u04-l507' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001fc' WHERE stable_ref = 'de-b2-u04-l508' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001fd' WHERE stable_ref = 'de-b2-u04-l509' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001fe' WHERE stable_ref = 'de-b2-u04-l510' AND lesson_id IS NULL;
