-- V80: German B2 lessons 511-520 (B2 batch 11)
-- Hex: 511=0x1ff, 520=0x208

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-0000000001ff','de-b2-l511','Soziologie - Sociology','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000200','de-b2-l512','Soziale Ungleichheit - Inequality','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000201','de-b2-l513','Klasse und Milieu - Class and Milieu','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000202','de-b2-l514','Geschlechterrollen - Gender Roles','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000203','de-b2-l515','Intersektionalität - Intersectionality','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000204','de-b2-l516','Diversität - Diversity','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000205','de-b2-l517','Rassismus und Diskriminierung - Racism','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000206','de-b2-l518','Vorurteile - Prejudice','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000207','de-b2-l519','Inklusion - Inclusion','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000208','de-b2-l520','Wohlfahrtsstaat - Welfare State','language','de','B2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-0000000001ff',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss sociology at B2","Use Soziologie vocabulary","Talk about social structures and institutions"],"explanation":{"intro":"Sociology vocabulary covers social structures, institutions, norms, and sociological theory at B2.","culturalNote":"Sociology in Germany has strong theoretical tradition: Max Weber (Rationalisierung, Verstehen, Bürokratie), Karl Marx, Georg Simmel (social interaction), Émile Durkheim influential. Contemporary: Niklas Luhmann (systems theory — Soziale Systeme), Jürgen Habermas (communicative action — Theorie des kommunikativen Handelns), Pierre Bourdieu influential on social capital, habitus, field. Key journal: Kölner Zeitschrift für Soziologie."},"examples":[{"german":"Soziale Institutionen wie Familie, Bildungssystem und Kirche erfüllen integrative Funktionen, indem sie gemeinsame Normen und Werte vermitteln und reproduzieren.","english":"Social institutions such as the family, the education system, and the church fulfil integrative functions by conveying and reproducing shared norms and values."},{"german":"Max Webers Konzept der Rationalisierung beschreibt den historischen Prozess, in dem traditionelle und affektuelle Handlungsmuster durch zweckrationale ersetzt werden.","english":"Max Weber''s concept of rationalisation describes the historical process in which traditional and affective patterns of action are replaced by purposively rational ones."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss sociology, social institutions, and sociological theory at B2."}}',
'{"items":[{"word":"die Institution","translation":"institution","pronunciation":"dee in-sti-too-TSYOHN","example":"Soziale Institutionen."},{"word":"integrativ","translation":"integrative","pronunciation":"in-teh-grah-TEEF","example":"Integrative Funktionen."},{"word":"reproduzieren","translation":"to reproduce","pronunciation":"reh-pro-doo-TSEER-en","example":"Normen reproduzieren."},{"word":"die Rationalisierung","translation":"rationalisation","pronunciation":"dee rah-tsyo-nah-li-ZEER-oong","example":"Rationalisierung."},{"word":"zweckrational","translation":"purposively rational","pronunciation":"TSVEK-rah-tsyo-nahl","example":"Zweckrationale Handlung."},{"word":"das Handlungsmuster","translation":"pattern of action","pronunciation":"dahs HAND-loonks-moos-ter","example":"Handlungsmuster ersetzen."}]}',
'{"title":"Indem — by (doing), through (means clause, revisited for complex sentences)","pattern":"X, indem Y = X by means of Y / X, in that Y — medium-register means clause","explanation":"Indem introduces the means by which the main clause action is achieved. Institutionen erfüllen integrative Funktionen, indem sie Normen vermitteln = Institutions fulfil integrative functions by transmitting norms. The indem clause can have the same or a different subject from the main clause. Indem can appear at the start of a sentence too: Indem wir zuhören, zeigen wir Respekt = By listening, we show respect. Word order: V-final in the indem clause (verb at the end). Compare: dadurch, dass (by the fact that — heavier, more explicit), durch + noun (through + noun — more concise).","examples":[{"sentence":"Unternehmen schaffen Vertrauen, indem sie transparent über ihre Entscheidungen berichten.","translation":"Companies create trust by reporting transparently about their decisions."},{"sentence":"Indem wir voneinander lernen, erweitern wir unseren Horizont.","translation":"By learning from one another, we broaden our horizons."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Reproduzieren'' means?","options":["to reproduce","to replicate","to perpetuate","to copy"],"correctAnswer":"to reproduce"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Social institutions such as the family, the education system, and the church fulfil integrative functions by conveying and reproducing shared norms and values.","options":["Soziale Institutionen wie Familie, Bildungssystem und Kirche erfüllen integrative Funktionen, indem sie gemeinsame Normen und Werte vermitteln und reproduzieren.","Familie, Schule und Kirche sind soziale Institutionen.","Soziale Institutionen vermitteln Normen und Werte.","Gemeinsame Werte werden durch soziale Institutionen weitergegeben."],"correctAnswer":"Soziale Institutionen wie Familie, Bildungssystem und Kirche erfüllen integrative Funktionen, indem sie gemeinsame Normen und Werte vermitteln und reproduzieren."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Unternehmen schaffen Vertrauen, indem sie transparent über ihre Entscheidungen ___.","options":["berichten","informieren","mitteilen","kommunizieren"],"correctAnswer":"berichten"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: By learning from one another we broaden our horizons","wordBankItems":["Indem","wir","voneinander","lernen",",","erweitern","wir","unseren","Horizont","."],"correctAnswer":"Indem wir voneinander lernen , erweitern wir unseren Horizont ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Zweckrational'' means?","options":["purposively rational","goal-oriented","rational","means-end rational"],"correctAnswer":"purposively rational"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000200',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss social inequality at B2","Use Ungleichheit vocabulary","Talk about socioeconomic disparities"],"explanation":{"intro":"Social inequality vocabulary covers income inequality, social mobility, and poverty at B2.","culturalNote":"Germany has one of the highest wealth inequality rates in the Eurozone (top 10% hold ~60% of wealth). Armutsgefährdungsquote (at-risk-of-poverty rate) ~16%. Key concepts: Einkommensungleichheit (income inequality), Gini-Koeffizient (Gini coefficient — Germany around 0.31), soziale Mobilität (social mobility — declining), Chancenungleichheit (inequality of opportunity), Bildungsungleichheit (education inequality — strong link between parental education and children''s outcomes in Germany)."},"examples":[{"german":"Soziale Ungleichheit manifestiert sich nicht nur in materiellen Disparitäten, sondern auch in ungleichem Zugang zu Bildung, Gesundheit und politischer Teilhabe.","english":"Social inequality manifests itself not only in material disparities, but also in unequal access to education, health, and political participation."},{"german":"Eine zunehmende Kluft zwischen Einkommensgruppen gefährdet den sozialen Zusammenhalt und das Vertrauen in demokratische Institutionen.","english":"A widening gap between income groups endangers social cohesion and trust in democratic institutions."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss social inequality, income gaps, and social mobility at B2."}}',
'{"items":[{"word":"sich manifestieren","translation":"to manifest itself","pronunciation":"zikh man-i-fes-TEER-en","example":"Sich in Disparitäten manifestieren."},{"word":"die Disparität","translation":"disparity","pronunciation":"dee dis-pah-ri-TÄT","example":"Materielle Disparitäten."},{"word":"der Zugang","translation":"access","pronunciation":"dayr TSOO-gang","example":"Zugang zu Bildung."},{"word":"die Teilhabe","translation":"participation","pronunciation":"dee TYL-hah-beh","example":"Politische Teilhabe."},{"word":"der Zusammenhalt","translation":"cohesion","pronunciation":"dayr TSOO-zam-en-halt","example":"Sozialer Zusammenhalt."},{"word":"zunehmend","translation":"widening/increasing","pronunciation":"TSOO-nay-mend","example":"Zunehmende Kluft."}]}',
'{"title":"Sich manifestieren in — to manifest itself in","pattern":"sich manifestieren in + dative = to manifest itself in, to materialise in","explanation":"Sich manifestieren in + dative = to manifest itself in. Ungleichheit manifestiert sich in Disparitäten = Inequality manifests itself in disparities. Used for abstract phenomena that become visible through concrete forms. Perfect: hat sich manifestiert. Compare: sich zeigen in (to show itself in — more general), sich niederschlagen in (to be reflected in — especially statistics, data), sich ausdrücken in (to express itself in — more voluntary), sich auswirken auf (to have an impact on — directed at effects).","examples":[{"sentence":"Die Krise manifestiert sich in steigenden Arbeitslosenzahlen.","translation":"The crisis manifests itself in rising unemployment figures."},{"sentence":"Soziale Ausgrenzung manifestiert sich oft in räumlicher Segregation.","translation":"Social exclusion often manifests itself in spatial segregation."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Teilhabe'' means?","options":["participation","involvement","sharing","inclusion"],"correctAnswer":"participation"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Social inequality manifests itself not only in material disparities, but also in unequal access to education, health, and political participation.","options":["Soziale Ungleichheit manifestiert sich nicht nur in materiellen Disparitäten, sondern auch in ungleichem Zugang zu Bildung, Gesundheit und politischer Teilhabe.","Ungleichheit hat viele Gesichter.","Soziale Ungleichheit zeigt sich in Einkommensunterschieden und fehlenden Chancen.","Ungleicher Zugang zu Bildung ist eine Form sozialer Ungleichheit."],"correctAnswer":"Soziale Ungleichheit manifestiert sich nicht nur in materiellen Disparitäten, sondern auch in ungleichem Zugang zu Bildung, Gesundheit und politischer Teilhabe."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Krise manifestiert sich in steigenden Arbeitslosenz___.","options":["zahlen","raten","quoten","werten"],"correctAnswer":"zahlen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Social exclusion often manifests itself in spatial segregation","wordBankItems":["Soziale","Ausgrenzung","manifestiert","sich","oft","in","räumlicher","Segregation","."],"correctAnswer":"Soziale Ausgrenzung manifestiert sich oft in räumlicher Segregation ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Der Zusammenhalt'' means?","options":["cohesion","solidarity","unity","togetherness"],"correctAnswer":"cohesion"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000201',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss class and milieu at B2","Use Milieu vocabulary","Talk about social strata in Germany"],"explanation":{"intro":"Class and milieu vocabulary covers social class, Bourdieu''s theory, and social milieus in Germany at B2.","culturalNote":"Germany uses Sinus-Milieus (Sinus-Institute social milieu model) which segments society into 10 groups based on values and lifestyle (not just income). Key concepts: Habitus (Bourdieu — ingrained dispositions), soziales Kapital (social capital), kulturelles Kapital (cultural capital — education, tastes), ökonomisches Kapital (economic capital). Traditional class terms: Arbeiterklasse (working class), Mittelstand (middle class — very broad in Germany), Oberschicht (upper class). Prekarisierung (precarisation) = growing precarious employment."},"examples":[{"german":"Bourdieus Habituskonzept erklärt, wie soziale Herkunft nicht bloß durch materiellen Besitz, sondern durch inkorporierte Denk- und Verhaltensweisen reproduziert wird.","english":"Bourdieu''s concept of habitus explains how social origin is reproduced not merely through material possessions, but through internalised ways of thinking and behaving."},{"german":"Die Mittelschicht ist in Deutschland ein heterogenes Gebilde, das Gruppen mit sehr unterschiedlichem Bildungskapital und Lebensstil umfasst.","english":"The middle class in Germany is a heterogeneous formation that encompasses groups with very different educational capital and lifestyle."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss social class, Bourdieu, habitus, and social milieus at B2."}}',
'{"items":[{"word":"inkorporiert","translation":"internalised/incorporated","pronunciation":"in-kor-po-REERT","example":"Inkorporierte Verhaltensweisen."},{"word":"das Gebilde","translation":"formation/structure","pronunciation":"dahs geh-BIL-deh","example":"Heterogenes Gebilde."},{"word":"heterogen","translation":"heterogeneous","pronunciation":"heh-teh-ro-GEN","example":"Heterogeneous Gruppe."},{"word":"umfassen","translation":"to encompass","pronunciation":"oom-FAS-en","example":"Viele Gruppen umfassen."},{"word":"die Herkunft","translation":"origin","pronunciation":"dee HER-koonft","example":"Soziale Herkunft."},{"word":"der Habitus","translation":"habitus","pronunciation":"dayr HAH-bi-toos","example":"Habitus nach Bourdieu."}]}',
'{"title":"Nicht bloß ... sondern ... durch — not merely...by/through + but also through","pattern":"nicht bloß durch X, sondern durch Y = not merely through X, but through Y (dual-means contrast)","explanation":"Nicht bloß durch X, sondern durch Y = not merely through X but through Y (contrasts two different mechanisms/means). Reproduziert nicht bloß durch materiellen Besitz, sondern durch inkorporierte Verhaltensweisen = reproduced not merely through material possessions but through internalised behaviours. Bloß (merely/just) downplays X; sondern introduces the deeper mechanism. Compare: nicht nur ... sondern auch (not only but also — additive without downplaying), weder... noch (neither... nor — exclusion).","examples":[{"sentence":"Erfolg kommt nicht bloß durch Talent, sondern durch harte Arbeit.","translation":"Success comes not merely through talent but through hard work."},{"sentence":"Sprache wird nicht bloß durch Regeln erworben, sondern durch Interaktion.","translation":"Language is acquired not merely through rules but through interaction."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Umfassen'' means?","options":["to encompass","to include","to comprise","to cover"],"correctAnswer":"to encompass"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Bourdieu''s concept of habitus explains how social origin is reproduced not merely through material possessions, but through internalised ways of thinking and behaving.","options":["Bourdieus Habituskonzept erklärt, wie soziale Herkunft nicht bloß durch materiellen Besitz, sondern durch inkorporierte Denk- und Verhaltensweisen reproduziert wird.","Bourdieu zeigt, dass Klasse mehr als Geld ist.","Soziale Herkunft prägt Denk- und Verhaltensweisen.","Der Habitus zeigt, wie Klasse reproduziert wird."],"correctAnswer":"Bourdieus Habituskonzept erklärt, wie soziale Herkunft nicht bloß durch materiellen Besitz, sondern durch inkorporierte Denk- und Verhaltensweisen reproduziert wird."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Erfolg kommt nicht bloß durch Talent, sondern durch harte ___.","options":["Arbeit","Anstrengung","Mühe","Leistung"],"correctAnswer":"Arbeit"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Language is acquired not merely through rules but through interaction","wordBankItems":["Sprache","wird","nicht","bloß","durch","Regeln","erworben",",","sondern","durch","Interaktion","."],"correctAnswer":"Sprache wird nicht bloß durch Regeln erworben , sondern durch Interaktion ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Das Gebilde'' means?","options":["formation/structure","entity","construct","body"],"correctAnswer":"formation/structure"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000202',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss gender roles at B2","Use Geschlechterrollen vocabulary","Talk about gender equality in Germany"],"explanation":{"intro":"Gender roles vocabulary covers gender equality, feminist theory, and gender policy in Germany at B2.","culturalNote":"Germany has a persistent Genderlücke (gender gap): Lohnlücke (gender pay gap ~18%), Führungspositionen (few women in top management). Elterngeld (parental allowance) and Kita (daycare) policy. Key milestones: women''s suffrage 1918, Gleichberechtigungsgesetz 1957, Gleichstellungsgesetze (equality laws). Gendergerechte Sprache (gender-equitable language) debate: Binnen-I, Gender-Sternchen (*), Genderdoppelpunkt. Key figures: Alice Schwarzer (feminist), Simone de Beauvoir influential."},"examples":[{"german":"Traditionelle Geschlechterrollen werden durch Sozialisation in Familie, Schule und Medien reproduziert und normativ verfestigt.","english":"Traditional gender roles are reproduced through socialisation in the family, school, and media and normatively consolidated."},{"german":"Die Vereinbarkeit von Familie und Beruf bleibt trotz gesetzlicher Fortschritte für Frauen strukturell schwieriger als für Männer.","english":"The reconciliation of family and career remains structurally more difficult for women than for men, despite legislative advances."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss gender roles, gender equality, and gender policy at B2."}}',
'{"items":[{"word":"normativ","translation":"normative","pronunciation":"nor-mah-TEEF","example":"Normativ verfestigt."},{"word":"verfestigen","translation":"to consolidate/entrench","pronunciation":"fer-FES-ti-gen","example":"Rollen verfestigen."},{"word":"die Vereinbarkeit","translation":"reconciliation/compatibility","pronunciation":"dee fer-YN-bahr-kyt","example":"Vereinbarkeit von Beruf und Familie."},{"word":"strukturell","translation":"structural","pronunciation":"shtrook-too-REL","example":"Strukturell schwieriger."},{"word":"trotz","translation":"despite","pronunciation":"trots","example":"Trotz Fortschritten."},{"word":"die Sozialisation","translation":"socialisation","pronunciation":"dee zo-tsya-li-ZAH-tsyohn","example":"Sozialisation in der Familie."}]}',
'{"title":"Trotz + genitive — despite (formal) vs. trotz + dative (colloquial)","pattern":"trotz + genitive (formal) = despite; trotz + dative (colloquial) = despite — both in common use","explanation":"Trotz + genitive = despite (formal standard). Trotz gesetzlicher Fortschritte = despite legislative advances. Trotz + dative: trotz dem Regen (colloquial, often in speech). Standard: trotz des Regens. In formal writing, use genitive. With plural: trotz aller Bemühungen = despite all efforts. Compare: obwohl/obschon/obgleich (although — with clause, not noun phrase), ungeachtet + genitive (notwithstanding — more formal), angesichts (in view of — neutral).","examples":[{"sentence":"Trotz intensiver Bemühungen konnte keine Einigung erzielt werden.","translation":"Despite intensive efforts, no agreement could be reached."},{"sentence":"Trotz des schlechten Wetters fand die Veranstaltung statt.","translation":"Despite the bad weather, the event took place."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Verfestigen'' means?","options":["to consolidate/entrench","to solidify","to strengthen","to reinforce"],"correctAnswer":"to consolidate/entrench"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The reconciliation of family and career remains structurally more difficult for women than for men, despite legislative advances.","options":["Die Vereinbarkeit von Familie und Beruf bleibt trotz gesetzlicher Fortschritte für Frauen strukturell schwieriger als für Männer.","Frauen haben es schwerer, Familie und Beruf zu vereinbaren.","Trotz Gleichstellungsgesetzen haben Frauen im Beruf Nachteile.","Gesetzliche Fortschritte haben die strukturellen Unterschiede nicht beseitigt."],"correctAnswer":"Die Vereinbarkeit von Familie und Beruf bleibt trotz gesetzlicher Fortschritte für Frauen strukturell schwieriger als für Männer."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Trotz intensiver Bemühungen konnte keine Einigung ___ werden.","options":["erzielt","erreicht","gefunden","geschlossen"],"correctAnswer":"erzielt"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Despite the bad weather the event took place","wordBankItems":["Trotz","des","schlechten","Wetters","fand","die","Veranstaltung","statt","."],"correctAnswer":"Trotz des schlechten Wetters fand die Veranstaltung statt ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Die Sozialisation'' means?","options":["socialisation","social development","integration","upbringing"],"correctAnswer":"socialisation"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000203',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss intersectionality at B2","Use Intersektionalität vocabulary","Talk about overlapping forms of discrimination"],"explanation":{"intro":"Intersectionality vocabulary covers overlapping dimensions of inequality and discrimination at B2.","culturalNote":"Intersektionalität (intersectionality — Kimberlé Crenshaw, 1989): analysis of how categories such as race, gender, class, disability, and sexual orientation interact and produce overlapping forms of discrimination. Growing use in German sociology, anti-discrimination law (AGG — Allgemeines Gleichbehandlungsgesetz), and feminist discourse. Key concept: intersektionale Diskriminierung (intersectional discrimination) = discrimination that results from the combination of multiple identities."},"examples":[{"german":"Intersektionalität als analytisches Konzept macht sichtbar, dass Diskriminierung selten aus einer einzigen Ursache resultiert, sondern oft aus der Überschneidung mehrerer sozialer Kategorien entsteht.","english":"Intersectionality as an analytical concept makes visible that discrimination rarely results from a single cause, but often arises from the intersection of multiple social categories."},{"german":"Eine alleinerziehende Mutter mit Migrationshintergrund und niedriger formaler Bildung ist mit multiplen, sich wechselseitig verstärkenden Benachteiligungen konfrontiert.","english":"A single mother with a migration background and low formal education is confronted with multiple, mutually reinforcing disadvantages."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss intersectionality, overlapping discrimination, and social categories at B2."}}',
'{"items":[{"word":"sichtbar machen","translation":"to make visible","pronunciation":"ZIKHT-bahr MAkhen","example":"Diskriminierung sichtbar machen."},{"word":"resultieren aus","translation":"to result from","pronunciation":"reh-zool-TEER-en ows","example":"Aus einer Ursache resultieren."},{"word":"die Überschneidung","translation":"intersection","pronunciation":"dee ü-ber-SHNY-doong","example":"Überschneidung von Kategorien."},{"word":"wechselseitig","translation":"mutual/reciprocal","pronunciation":"VEK-sel-zy-tikh","example":"Wechselseitig verstärkend."},{"word":"die Benachteiligung","translation":"disadvantage/discrimination","pronunciation":"dee beh-NAKH-ty-li-goong","example":"Multiple Benachteiligungen."},{"word":"konfrontiert sein mit","translation":"to be confronted with","pronunciation":"kon-fron-TEERT zyn mit","example":"Konfrontiert mit Benachteiligungen."}]}',
'{"title":"Sich wechselseitig verstärken — mutually reinforcing (reciprocal intensification)","pattern":"sich wechselseitig verstärken = to mutually reinforce one another (reciprocal — used for overlapping effects)","explanation":"Sich wechselseitig verstärken = to mutually reinforce each other, to be mutually reinforcing. Multiple Benachteiligungen, die sich wechselseitig verstärken = multiple disadvantages that mutually reinforce each other. Wechselseitig = mutual, reciprocal (each acting on the other). Common collocates: beeinflussen (influence), bedingen (condition), ausschließen (exclude). Compare: gegenseitig (mutual/reciprocal — more general), sich gegenseitig (each other — reflexive), sich aufschaukeln (to escalate mutually — more informal).","examples":[{"sentence":"Armut und schlechte Bildung verstärken sich wechselseitig.","translation":"Poverty and poor education mutually reinforce each other."},{"sentence":"Diese Faktoren bedingen und verstärken sich wechselseitig.","translation":"These factors condition and mutually reinforce each other."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Überschneidung'' means?","options":["intersection","overlap","crossing","convergence"],"correctAnswer":"intersection"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Intersectionality as an analytical concept makes visible that discrimination rarely results from a single cause, but often arises from the intersection of multiple social categories.","options":["Intersektionalität als analytisches Konzept macht sichtbar, dass Diskriminierung selten aus einer einzigen Ursache resultiert, sondern oft aus der Überschneidung mehrerer sozialer Kategorien entsteht.","Diskriminierung hat oft mehrere Ursachen.","Intersektionalität zeigt, wie verschiedene Kategorien sich überschneiden.","Mehrere soziale Kategorien überschneiden sich und erzeugen Diskriminierung."],"correctAnswer":"Intersektionalität als analytisches Konzept macht sichtbar, dass Diskriminierung selten aus einer einzigen Ursache resultiert, sondern oft aus der Überschneidung mehrerer sozialer Kategorien entsteht."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Armut und schlechte Bildung verstärken sich ___.","options":["wechselseitig","gegenseitig","gegenseitig sich","wechselseitig sich"],"correctAnswer":"wechselseitig"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: These factors condition and mutually reinforce each other","wordBankItems":["Diese","Faktoren","bedingen","und","verstärken","sich","wechselseitig","."],"correctAnswer":"Diese Faktoren bedingen und verstärken sich wechselseitig ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Resultieren aus'' means?","options":["to result from","to arise from","to come from","to stem from"],"correctAnswer":"to result from"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000204',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss diversity at B2","Use Diversität vocabulary","Talk about diversity management"],"explanation":{"intro":"Diversity vocabulary covers workplace diversity, cultural diversity, and inclusion policy at B2.","culturalNote":"Diversity Management became prominent in German companies in the 2000s. Key concepts: Vielfalt (diversity — German term preferred in official contexts), Charta der Vielfalt (Diversity Charter — signed by 5,000+ German organisations), Diversity & Inclusion (D&I). Protected characteristics under AGG: Alter, Behinderung, ethnische Herkunft, Geschlecht, Religion, sexuelle Identität. Challenges: unconscious bias training, Quoten (quotas) debate for boards and political parties."},"examples":[{"german":"Diversität im Unternehmen gilt nicht nur als ethische Verpflichtung, sondern als Wettbewerbsvorteil, da heterogene Teams nachweislich innovativer und problemlösungsorientierter sind.","english":"Diversity in the company is regarded not only as an ethical obligation, but as a competitive advantage, since heterogeneous teams are demonstrably more innovative and problem-solving-oriented."},{"german":"Echte Inklusion erfordert mehr als die Repräsentation verschiedener Gruppen — sie setzt eine Unternehmenskultur voraus, die unterschiedliche Perspektiven wertschätzt und strukturell verankert.","english":"True inclusion requires more than the representation of different groups — it presupposes a corporate culture that values different perspectives and structurally anchors them."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss diversity, inclusion, and diversity management at B2."}}',
'{"items":[{"word":"die Verpflichtung","translation":"obligation","pronunciation":"dee fer-PFLIKHT-oong","example":"Ethische Verpflichtung."},{"word":"der Wettbewerbsvorteil","translation":"competitive advantage","pronunciation":"dayr VET-beh-verps-for-tyl","example":"Als Wettbewerbsvorteil gelten."},{"word":"nachweislich","translation":"demonstrably","pronunciation":"NAKH-vys-likh","example":"Nachweislich innovativer."},{"word":"voraussetzen","translation":"to presuppose/require","pronunciation":"for-OWS-zetsen","example":"Eine Kultur voraussetzen."},{"word":"wertschätzen","translation":"to value/appreciate","pronunciation":"VERT-shet-sen","example":"Perspektiven wertschätzen."},{"word":"verankern","translation":"to anchor/embed","pronunciation":"fer-AN-kern","example":"Strukturell verankern."}]}',
'{"title":"Voraussetzen — to presuppose, require (as precondition)","pattern":"etwas setzt etwas voraus = something presupposes something (something requires as a prior condition)","explanation":"Voraussetzen (separable) = to presuppose, to require as a precondition. Inklusion setzt eine Unternehmenskultur voraus = Inclusion presupposes a corporate culture. The subject requires the object as a necessary prior condition (the object must already exist). Die Voraussetzung = precondition, requirement. Present: setzt voraus. Perfect: hat vorausgesetzt. Compare: erfordern (to require — the thing must be done/brought about), bedingen (to necessitate/condition — more reciprocal), implizieren (to imply — logical consequence).","examples":[{"sentence":"Diese Aufgabe setzt Fachkenntnisse im Bereich Datenschutz voraus.","translation":"This task presupposes specialist knowledge in the area of data protection."},{"sentence":"Gute Kommunikation setzt gegenseitiges Vertrauen voraus.","translation":"Good communication presupposes mutual trust."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Nachweislich'' means?","options":["demonstrably","provably","evidently","verifiably"],"correctAnswer":"demonstrably"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"True inclusion requires more than the representation of different groups — it presupposes a corporate culture that values different perspectives and structurally anchors them.","options":["Echte Inklusion erfordert mehr als die Repräsentation verschiedener Gruppen — sie setzt eine Unternehmenskultur voraus, die unterschiedliche Perspektiven wertschätzt und strukturell verankert.","Inklusion bedeutet mehr als Repräsentation.","Eine Unternehmenskultur der Vielfalt schätzt verschiedene Perspektiven.","Echte Inklusion braucht eine Kultur, die Diversität lebt."],"correctAnswer":"Echte Inklusion erfordert mehr als die Repräsentation verschiedener Gruppen — sie setzt eine Unternehmenskultur voraus, die unterschiedliche Perspektiven wertschätzt und strukturell verankert."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Diese Aufgabe setzt Fachkenntnisse im Bereich Datenschutz ___.","options":["voraus","vorher","voran","vorwärts"],"correctAnswer":"voraus"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Good communication presupposes mutual trust","wordBankItems":["Gute","Kommunikation","setzt","gegenseitiges","Vertrauen","voraus","."],"correctAnswer":"Gute Kommunikation setzt gegenseitiges Vertrauen voraus ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Verankern'' means?","options":["to anchor/embed","to fix","to root","to establish"],"correctAnswer":"to anchor/embed"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000205',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss racism and discrimination at B2","Use Diskriminierung vocabulary","Talk about anti-discrimination policy"],"explanation":{"intro":"Racism and discrimination vocabulary covers structural racism, anti-discrimination law, and social exclusion at B2.","culturalNote":"Germany''s history means Rassismus (racism) and Diskriminierung (discrimination) are treated with particular seriousness. AGG (Allgemeines Gleichbehandlungsgesetz/General Equal Treatment Act) bans discrimination in workplace and services. Structural racism (struktureller Rassismus) debate has grown since Black Lives Matter. AfD-Debatte around racial politics. Key institutions: Antidiskriminierungsstelle des Bundes (Federal Anti-Discrimination Agency). NSU-Prozess (2013-2018) revealed systemic failures in dealing with right-wing terrorism."},"examples":[{"german":"Rassismus beschränkt sich nicht auf individuelle Vorurteile, sondern ist in Institutionen und gesellschaftlichen Strukturen eingebettet, die systematisch bestimmte Gruppen benachteiligen.","english":"Racism is not limited to individual prejudices, but is embedded in institutions and social structures that systematically disadvantage certain groups."},{"german":"Antidiskriminierungsgesetze sind notwendig, aber nicht hinreichend — strukturelle Benachteiligungen erfordern aktive, politisch gesteuerte Gegenmaßnahmen.","english":"Anti-discrimination laws are necessary but not sufficient — structural disadvantages require active, politically directed counter-measures."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss racism, structural discrimination, and anti-discrimination policy at B2."}}',
'{"items":[{"word":"eingebettet","translation":"embedded","pronunciation":"YN-geh-bet-et","example":"In Strukturen eingebettet."},{"word":"systematisch","translation":"systematically","pronunciation":"züs-teh-MAH-tish","example":"Systematisch benachteiligen."},{"word":"hinreichend","translation":"sufficient","pronunciation":"HIN-ry-khend","example":"Notwendig aber nicht hinreichend."},{"word":"notwendig","translation":"necessary","pronunciation":"NOT-ven-dikh","example":"Notwendig."},{"word":"die Gegenmaßnahme","translation":"counter-measure","pronunciation":"dee GAY-gen-mahs-nah-meh","example":"Gegenmaßnahmen ergreifen."},{"word":"das Vorurteil","translation":"prejudice","pronunciation":"dahs FOR-oor-tyl","example":"Individuelle Vorurteile."}]}',
'{"title":"Beschränken auf — to limit to, confine to","pattern":"sich beschränken auf + accusative = to limit itself to (subject does not go beyond X)","explanation":"Sich beschränken auf + accusative = to be limited to, to confine itself to. Rassismus beschränkt sich nicht auf individuelle Vorurteile = Racism is not limited to individual prejudices. Transitively: etwas auf X beschränken = to limit something to X. Die Beschränkung = limitation, restriction. Perfect: hat sich beschränkt / hat beschränkt. Compare: sich erschöpfen in (to be exhausted by — no more than), reduzieren auf (to reduce to — simplification), eingrenzen auf (to narrow down to — research context).","examples":[{"sentence":"Das Projekt beschränkt sich auf zwei Phasen.","translation":"The project is limited to two phases."},{"sentence":"Bitte beschränken Sie Ihre Antwort auf das Wesentliche.","translation":"Please limit your answer to the essential points."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Hinreichend'' means?","options":["sufficient","adequate","enough","satisfactory"],"correctAnswer":"sufficient"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Racism is not limited to individual prejudices, but is embedded in institutions and social structures that systematically disadvantage certain groups.","options":["Rassismus beschränkt sich nicht auf individuelle Vorurteile, sondern ist in Institutionen und gesellschaftlichen Strukturen eingebettet, die systematisch bestimmte Gruppen benachteiligen.","Rassismus zeigt sich in individuellen und strukturellen Formen.","Struktureller Rassismus ist in Institutionen verankert.","Diskriminierung geht über individuelle Vorurteile hinaus."],"correctAnswer":"Rassismus beschränkt sich nicht auf individuelle Vorurteile, sondern ist in Institutionen und gesellschaftlichen Strukturen eingebettet, die systematisch bestimmte Gruppen benachteiligen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Projekt beschränkt sich auf zwei ___.","options":["Phasen","Teile","Stufen","Abschnitte"],"correctAnswer":"Phasen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Please limit your answer to the essential points","wordBankItems":["Bitte","beschränken","Sie","Ihre","Antwort","auf","das","Wesentliche","."],"correctAnswer":"Bitte beschränken Sie Ihre Antwort auf das Wesentliche ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Eingebettet'' means?","options":["embedded","integrated","incorporated","embedded in"],"correctAnswer":"embedded"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000206',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss prejudice at B2","Use Vorurteil vocabulary","Talk about stereotypes and cognitive biases"],"explanation":{"intro":"Prejudice vocabulary covers stereotypes, implicit bias, and mechanisms of prejudice at B2.","culturalNote":"Key concepts: Stereotyp (stereotype), impliziter Bias (implicit bias), Vorurteil (prejudice — pre-judgment based on group membership), Diskriminierung (discrimination — acting on prejudice). Contact hypothesis (Gordon Allport): inter-group contact under specific conditions reduces prejudice. In-Group/Out-Group dynamics. Fundamental attribution error. Germany: Vorurteile gegenüber Ausländern, Roma, Muslims measured by Bielefelder Mitte-Studie."},"examples":[{"german":"Vorurteile entstehen häufig durch kognitive Schematisierung, bei der ein Individuum Merkmale einer Gruppe auf alle Mitglieder der Gruppe überträgt, ohne Variation zu berücksichtigen.","english":"Prejudices frequently arise through cognitive schematisation, in which an individual transfers characteristics of a group onto all members of the group, without taking variation into account."},{"german":"Implizite Biases sind unbewusste Denkmuster, die das Verhalten beeinflussen, ohne dass die betreffende Person davon weiß oder es beabsichtigt.","english":"Implicit biases are unconscious patterns of thought that influence behaviour without the person in question knowing it or intending it."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss prejudice, stereotypes, and implicit bias at B2."}}',
'{"items":[{"word":"die Schematisierung","translation":"schematisation","pronunciation":"dee sheh-mah-ti-ZEER-oong","example":"Kognitive Schematisierung."},{"word":"übertragen","translation":"to transfer/apply","pronunciation":"ü-ber-TRAH-gen","example":"Merkmale übertragen."},{"word":"berücksichtigen","translation":"to take into account","pronunciation":"beh-RÜK-zikh-ti-gen","example":"Variation berücksichtigen."},{"word":"beabsichtigen","translation":"to intend","pronunciation":"beh-AP-zikh-ti-gen","example":"Nicht beabsichtigen."},{"word":"unbewusst","translation":"unconscious","pronunciation":"OON-beh-voost","example":"Unbewusste Denkmuster."},{"word":"das Merkmal","translation":"characteristic/feature","pronunciation":"dahs MERK-mahl","example":"Merkmale einer Gruppe."}]}',
'{"title":"Ohne zu — without (doing) (same subject, non-finite)","pattern":"ohne + zu + Infinitiv (same subject) = without doing","explanation":"Ohne zu + Infinitiv = without doing (same subject required — if different subjects: ohne dass + V-final). Verhalten beeinflussen, ohne dass die Person es weiß = influence behaviour without the person knowing (different subjects → ohne dass). Ohne Variation zu berücksichtigen = without taking variation into account (same subject). Note: ohne zu is the standard gerund-equivalent; in English this is ''without -ing''. Compare: anstatt zu (instead of doing), um zu (in order to).","examples":[{"sentence":"Sie verließ das Zimmer, ohne ein Wort zu sagen.","translation":"She left the room without saying a word."},{"sentence":"Er traf die Entscheidung, ohne die Konsequenzen zu bedenken.","translation":"He made the decision without considering the consequences."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Unbewusst'' means?","options":["unconscious","subconscious","involuntary","unaware"],"correctAnswer":"unconscious"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Implicit biases are unconscious patterns of thought that influence behaviour without the person in question knowing it or intending it.","options":["Implizite Biases sind unbewusste Denkmuster, die das Verhalten beeinflussen, ohne dass die betreffende Person davon weiß oder es beabsichtigt.","Implizite Vorurteile beeinflussen das Verhalten unbewusst.","Unbewusste Biases wirken ohne das Wissen der betreffenden Person.","Implizite Biases sind unbewusst und unbeabsichtigt."],"correctAnswer":"Implizite Biases sind unbewusste Denkmuster, die das Verhalten beeinflussen, ohne dass die betreffende Person davon weiß oder es beabsichtigt."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Sie verließ das Zimmer, ohne ein Wort zu ___.","options":["sagen","sprechen","reden","äußern"],"correctAnswer":"sagen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: He made the decision without considering the consequences","wordBankItems":["Er","traf","die","Entscheidung",",","ohne","die","Konsequenzen","zu","bedenken","."],"correctAnswer":"Er traf die Entscheidung , ohne die Konsequenzen zu bedenken ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Berücksichtigen'' means?","options":["to take into account","to consider","to acknowledge","to regard"],"correctAnswer":"to take into account"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000207',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss inclusion at B2","Use Inklusion vocabulary","Talk about disability and inclusion policy"],"explanation":{"intro":"Inclusion vocabulary covers disability rights, inclusive education, and accessibility at B2.","culturalNote":"UN-Behindertenrechtskonvention (UN CRPD) ratified by Germany 2009. Key principle: inklusive Bildung (inclusive education) — disabled and non-disabled students learn together. Progress has been slow: Germany still has Förderschulen (special schools). Barrierefreiheit (accessibility) required by law in public spaces and websites. Key legislation: Bundesteilhabegesetz (BTHG 2016 — Federal Participation Act — strengthened rights for people with disabilities). Key body: Behindertenbeauftragte (Commissioner for Disabled Persons)."},"examples":[{"german":"Inklusion bedeutet nicht lediglich räumliche Integration, sondern die aktive Umgestaltung gesellschaftlicher Strukturen, um Barrieren abzubauen und gleichberechtigte Teilhabe zu ermöglichen.","english":"Inclusion means not merely spatial integration, but the active reshaping of social structures in order to remove barriers and enable equal participation."},{"german":"Barrierefreiheit ist eine rechtliche Verpflichtung und ein gesellschaftliches Gebot, das weit über die Installierung von Rollstuhlrampen hinausgeht.","english":"Accessibility is a legal obligation and a social imperative that goes far beyond the installation of wheelchair ramps."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss inclusion, disability rights, and accessibility at B2."}}',
'{"items":[{"word":"lediglich","translation":"merely/only","pronunciation":"LAY-dikh-likh","example":"Lediglich räumliche Integration."},{"word":"die Umgestaltung","translation":"reshaping/transformation","pronunciation":"dee OOM-geh-shtal-toong","example":"Aktive Umgestaltung."},{"word":"abbauen","translation":"to remove/reduce (barriers)","pronunciation":"AP-bow-en","example":"Barrieren abbauen."},{"word":"das Gebot","translation":"imperative/commandment","pronunciation":"dahs geh-BOHT","example":"Gesellschaftliches Gebot."},{"word":"die Barrierefreiheit","translation":"accessibility","pronunciation":"dee bah-ree-YER-eh-fry-hyt","example":"Barrierefreiheit gewährleisten."},{"word":"gleichberechtigt","translation":"equal/having equal rights","pronunciation":"GLYKH-beh-rekh-tigt","example":"Gleichberechtigte Teilhabe."}]}',
'{"title":"Nicht lediglich ... sondern — not merely...but (academic register)","pattern":"nicht lediglich X, sondern Y = not merely X, but Y — lediglich (merely) more formal than bloß/nur","explanation":"Nicht lediglich...sondern = not merely...but (academic register, slightly more formal than nicht nur/nicht bloß). Inklusion bedeutet nicht lediglich räumliche Integration, sondern... = Inclusion means not merely spatial integration, but... Lediglich = merely, only (formal — more distancing than bloß, less blunt than nur in this context). Compare in register: nicht nur → nicht bloß → nicht lediglich → nicht ausschließlich (ascending formality).","examples":[{"sentence":"Das Gesetz regelt nicht lediglich den Datenschutz, sondern schafft neue Rechte für Betroffene.","translation":"The law does not merely regulate data protection, but creates new rights for those affected."},{"sentence":"Die Reform zielt nicht lediglich auf Kostensenkung ab, sondern auf strukturelle Verbesserungen.","translation":"The reform does not merely aim at cost reduction, but at structural improvements."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Lediglich'' means?","options":["merely/only","just","simply","purely"],"correctAnswer":"merely/only"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Inclusion means not merely spatial integration, but the active reshaping of social structures in order to remove barriers and enable equal participation.","options":["Inklusion bedeutet nicht lediglich räumliche Integration, sondern die aktive Umgestaltung gesellschaftlicher Strukturen, um Barrieren abzubauen und gleichberechtigte Teilhabe zu ermöglichen.","Inklusion ist mehr als Integration.","Barrieren abbauen und Teilhabe ermöglichen ist das Ziel von Inklusion.","Räumliche Integration allein reicht für Inklusion nicht aus."],"correctAnswer":"Inklusion bedeutet nicht lediglich räumliche Integration, sondern die aktive Umgestaltung gesellschaftlicher Strukturen, um Barrieren abzubauen und gleichberechtigte Teilhabe zu ermöglichen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Gesetz regelt nicht lediglich den Datenschutz, sondern schafft neue Rechte für ___.","options":["Betroffene","Benutzer","Opfer","Betroffenen"],"correctAnswer":"Betroffene"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The reform does not merely aim at cost reduction but at structural improvements","wordBankItems":["Die","Reform","zielt","nicht","lediglich","auf","Kostensenkung","ab",",","sondern","auf","strukturelle","Verbesserungen","."],"correctAnswer":"Die Reform zielt nicht lediglich auf Kostensenkung ab , sondern auf strukturelle Verbesserungen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Abbauen'' means?","options":["to remove/reduce","to demolish","to dismantle","to break down"],"correctAnswer":"to remove/reduce"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000208',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss the welfare state at B2","Use Wohlfahrtsstaat vocabulary","Talk about social policy in Germany"],"explanation":{"intro":"Welfare state vocabulary covers social security, social policy, and the German social state model at B2.","culturalNote":"Germany''s Sozialstaat (social state) is enshrined in the Grundgesetz (Art. 20: Sozialstaatsprinzip). Key pillars: Rentenversicherung (pension insurance), Krankenversicherung (health insurance), Arbeitslosenversicherung (unemployment insurance), Pflegeversicherung (long-term care insurance). Bismarck''s social insurance system (1883–1889) was the first in the world. Key challenges: Demografischer Wandel (demographic change — ageing population), Finanzierbarkeit (fiscal sustainability), Generationengerechtigkeit (intergenerational equity)."},"examples":[{"german":"Das deutsche Sozialversicherungssystem gründet auf dem Solidaritätsprinzip, wonach Risiken wie Krankheit, Alter und Arbeitslosigkeit kollektiv getragen werden.","english":"The German social insurance system is founded on the solidarity principle, according to which risks such as illness, old age, and unemployment are borne collectively."},{"german":"Die Nachhaltigkeit des Wohlfahrtsstaats steht angesichts des demografischen Wandels auf dem Prüfstand, da eine schrumpfende Erwerbsbevölkerung zunehmend eine wachsende Zahl von Rentnern finanzieren muss.","english":"The sustainability of the welfare state is under scrutiny in view of demographic change, as a shrinking working-age population must increasingly finance a growing number of pensioners."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss the welfare state, social insurance, and social policy at B2."}}',
'{"items":[{"word":"gründen auf","translation":"to be founded on/based on","pronunciation":"GRÜN-den owf","example":"Auf dem Prinzip gründen."},{"word":"wonach","translation":"according to which","pronunciation":"voh-NAKH","example":"Wonach Risiken kollektiv getragen werden."},{"word":"kollektiv","translation":"collectively","pronunciation":"ko-lek-TEEF","example":"Kollektiv tragen."},{"word":"die Nachhaltigkeit","translation":"sustainability","pronunciation":"dee NAKH-hal-tikh-kyt","example":"Nachhaltigkeit des Systems."},{"word":"auf dem Prüfstand stehen","translation":"to be under scrutiny/on the test bench","pronunciation":"owf daym PRÜF-shtant SHTAY-en","example":"Auf dem Prüfstand stehen."},{"word":"schrumpfend","translation":"shrinking","pronunciation":"SHROOMPF-end","example":"Schrumpfende Bevölkerung."}]}',
'{"title":"Wonach — according to which (relative adverb for nach)","pattern":"nach + dem Prinzip = by/according to the principle; rel. clause: ...das Prinzip, wonach... = the principle according to which...","explanation":"Wonach = according to which (relative adverb replacing nach + dem/denen). Das Prinzip, wonach Risiken kollektiv getragen werden = The principle according to which risks are borne collectively. Wonach is a relative adverb used when the relative clause relates to nach (after, according to). Paradigm: worauf (on which), worüber (about which), wobei (in which), wofür (for which), wonach (after/according to which). If the antecedent is a person, use whom (dative): die Person, nach der = the person according to whom. These are preposition + relative pronoun fused into w-pronouns for non-personal antecedents.","examples":[{"sentence":"Das Gesetz legt die Regeln fest, wonach die Wahlen abgehalten werden.","translation":"The law lays down the rules according to which the elections are held."},{"sentence":"Wir suchen einen Maßstab, wonach wir unsere Entscheidungen treffen können.","translation":"We are looking for a standard according to which we can make our decisions."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Schrumpfend'' means?","options":["shrinking","declining","decreasing","contracting"],"correctAnswer":"shrinking"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The German social insurance system is founded on the solidarity principle, according to which risks such as illness, old age, and unemployment are borne collectively.","options":["Das deutsche Sozialversicherungssystem gründet auf dem Solidaritätsprinzip, wonach Risiken wie Krankheit, Alter und Arbeitslosigkeit kollektiv getragen werden.","Das Solidaritätsprinzip bedeutet, dass alle zusammen für Risiken zahlen.","Die Sozialversicherung verteilt Risiken auf alle Versicherten.","Krankheit, Alter und Arbeitslosigkeit sind kollektive Risiken."],"correctAnswer":"Das deutsche Sozialversicherungssystem gründet auf dem Solidaritätsprinzip, wonach Risiken wie Krankheit, Alter und Arbeitslosigkeit kollektiv getragen werden."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Gesetz legt die Regeln fest, wonach die Wahlen abgehalten ___.","options":["werden","sind","werden sollen","werden müssen"],"correctAnswer":"werden"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: We are looking for a standard according to which we can make our decisions","wordBankItems":["Wir","suchen","einen","Maßstab",",","wonach","wir","unsere","Entscheidungen","treffen","können","."],"correctAnswer":"Wir suchen einen Maßstab , wonach wir unsere Entscheidungen treffen können ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Auf dem Prüfstand stehen'' means?","options":["to be under scrutiny","to be tested","to be under review","to be challenged"],"correctAnswer":"to be under scrutiny"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-0000000001ff','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l511',511,'Soziologie','Sociology','PUBLISHED'),
('dd000000-0000-0000-0000-000000000200','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l512',512,'Soziale Ungleichheit','Social inequality','PUBLISHED'),
('dd000000-0000-0000-0000-000000000201','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l513',513,'Klasse und Milieu','Class and milieu','PUBLISHED'),
('dd000000-0000-0000-0000-000000000202','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l514',514,'Geschlechterrollen','Gender roles','PUBLISHED'),
('dd000000-0000-0000-0000-000000000203','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l515',515,'Intersektionalität','Intersectionality','PUBLISHED'),
('dd000000-0000-0000-0000-000000000204','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l516',516,'Diversität','Diversity','PUBLISHED'),
('dd000000-0000-0000-0000-000000000205','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l517',517,'Rassismus und Diskriminierung','Racism and discrimination','PUBLISHED'),
('dd000000-0000-0000-0000-000000000206','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l518',518,'Vorurteile','Prejudice','PUBLISHED'),
('dd000000-0000-0000-0000-000000000207','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l519',519,'Inklusion','Inclusion','PUBLISHED'),
('dd000000-0000-0000-0000-000000000208','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l520',520,'Wohlfahrtsstaat','Welfare state','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-0000000001ff' WHERE stable_ref = 'de-b2-u04-l511' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000200' WHERE stable_ref = 'de-b2-u04-l512' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000201' WHERE stable_ref = 'de-b2-u04-l513' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000202' WHERE stable_ref = 'de-b2-u04-l514' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000203' WHERE stable_ref = 'de-b2-u04-l515' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000204' WHERE stable_ref = 'de-b2-u04-l516' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000205' WHERE stable_ref = 'de-b2-u04-l517' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000206' WHERE stable_ref = 'de-b2-u04-l518' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000207' WHERE stable_ref = 'de-b2-u04-l519' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000208' WHERE stable_ref = 'de-b2-u04-l520' AND lesson_id IS NULL;
