-- V84: German B2 lessons 551-560 (B2 batch 15)
-- Hex: 551=0x227, 560=0x230

INSERT INTO cf_lessons (id, stable_ref, title, domain_code, language_code, cefr_level, content_status, publication_status, current_version, active_version) VALUES
('aa000000-0000-0000-0000-000000000227','de-b2-l551','Außenpolitik - Foreign Policy','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000228','de-b2-l552','Deutsch-Amerikanische Beziehungen - US-Germany','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000229','de-b2-l553','Deutsch-Französische Beziehungen - Franco-German','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000022a','de-b2-l554','Russland und Ukraine - Russia Ukraine','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000022b','de-b2-l555','China und Asien - China Asia','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000022c','de-b2-l556','Naher Osten - Middle East','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000022d','de-b2-l557','Vereinte Nationen - United Nations','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000022e','de-b2-l558','Menschenrechte - Human Rights','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-00000000022f','de-b2-l559','Völkerrecht - International Law','language','de','B2','APPROVED','PUBLISHED',1,1),
('aa000000-0000-0000-0000-000000000230','de-b2-l560','Globale Gerechtigkeit - Global Justice','language','de','B2','APPROVED','PUBLISHED',1,1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000227',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss German foreign policy at B2","Use Außenpolitik vocabulary","Talk about Germany''s role in the world"],"explanation":{"intro":"Foreign policy vocabulary covers Germany''s international role, strategic culture, and alliances at B2.","culturalNote":"Germany''s Außenpolitik is shaped by history: Zivilmacht (civilian power — preference for multilateralism, diplomacy, EU), Westbindung (Western orientation — NATO, transatlanticism), Ostpolitik (Willy Brandt''s détente policy towards East). Key debates: Zeitenwende (turning point — Scholz speech Feb 2022 post-Ukraine invasion, announced €100bn Bundeswehr special fund), Sonderweg (special path — Germany exceptional?), more military spending vs. diplomacy-first."},"examples":[{"german":"Die Zeitenwende markiert eine fundamentale Neuausrichtung der deutschen Sicherheitspolitik: Weg von der Vernachlässigung der Landesverteidigung hin zu einer stärkeren Übernahme von Verantwortung in der NATO.","english":"The turning point marks a fundamental reorientation of German security policy: away from neglect of national defence towards greater assumption of responsibility within NATO."},{"german":"Deutschlands außenpolitische Handlungsfähigkeit wird durch seine eingebettete Souveränität in EU und NATO sowohl ermöglicht als auch eingeschränkt.","english":"Germany''s foreign policy capacity for action is both enabled and constrained by its embedded sovereignty in the EU and NATO."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss German foreign policy, the Zeitenwende, and Germany''s international role at B2."}}',
'{"items":[{"word":"die Neuausrichtung","translation":"reorientation","pronunciation":"dee NOY-ows-rikh-toong","example":"Fundamentale Neuausrichtung."},{"word":"markieren","translation":"to mark/signal","pronunciation":"mar-KEER-en","example":"Eine Wende markieren."},{"word":"die Übernahme","translation":"assumption/takeover","pronunciation":"dee ü-ber-NAH-meh","example":"Übernahme von Verantwortung."},{"word":"eingebettet","translation":"embedded","pronunciation":"YN-geh-bet-et","example":"Eingebettete Souveränität."},{"word":"einschränken","translation":"to constrain/restrict","pronunciation":"YN-shrenk-en","example":"Handlungsfähigkeit einschränken."},{"word":"die Handlungsfähigkeit","translation":"capacity for action","pronunciation":"dee HAND-loonks-fä-ikh-kyt","example":"Außenpolitische Handlungsfähigkeit."}]}',
'{"title":"Sowohl ... als auch ... ermöglichen als auch einschränken — enable and constrain simultaneously","pattern":"sowohl X als auch Y (paired verbs/effects) = both X and Y simultaneously","explanation":"Sowohl...als auch can pair two parallel verb effects on the same subject. Deutschlands Souveränität wird sowohl ermöglicht als auch eingeschränkt = Germany''s sovereignty is both enabled and constrained. This construction is used to present dual effects without a value judgment (neither net positive nor negative — both are true). Used frequently in political analysis where the same factor has contradictory effects simultaneously. The passive voice makes both effects equally prominent.","examples":[{"sentence":"Die Globalisierung hat Deutschland sowohl gestärkt als auch verwundbar gemacht.","translation":"Globalisation has both strengthened Germany and made it vulnerable."},{"sentence":"Der Vertrag wurde sowohl als Erfolg als auch als Kompromiss bewertet.","translation":"The treaty was evaluated both as a success and as a compromise."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Neuausrichtung'' means?","options":["reorientation","realignment","repositioning","new direction"],"correctAnswer":"reorientation"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The turning point marks a fundamental reorientation of German security policy: away from neglect of national defence towards greater assumption of responsibility within NATO.","options":["Die Zeitenwende markiert eine fundamentale Neuausrichtung der deutschen Sicherheitspolitik: Weg von der Vernachlässigung der Landesverteidigung hin zu einer stärkeren Übernahme von Verantwortung in der NATO.","Deutschland investiert jetzt mehr in Verteidigung.","Die Zeitenwende bedeutet mehr Verantwortung in der NATO.","Deutschlands Sicherheitspolitik hat sich nach der Ukraine-Invasion geändert."],"correctAnswer":"Die Zeitenwende markiert eine fundamentale Neuausrichtung der deutschen Sicherheitspolitik: Weg von der Vernachlässigung der Landesverteidigung hin zu einer stärkeren Übernahme von Verantwortung in der NATO."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Globalisierung hat Deutschland sowohl gestärkt als auch verwundbar ___.","options":["gemacht","geworden","gemacht hat","gemacht"],"correctAnswer":"gemacht"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The treaty was evaluated both as a success and as a compromise","wordBankItems":["Der","Vertrag","wurde","sowohl","als","Erfolg","als","auch","als","Kompromiss","bewertet","."],"correctAnswer":"Der Vertrag wurde sowohl als Erfolg als auch als Kompromiss bewertet ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Einschränken'' means?","options":["to constrain/restrict","to limit","to reduce","to curtail"],"correctAnswer":"to constrain/restrict"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000228',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss US-Germany relations at B2","Use transatlantisch vocabulary","Talk about NATO and trade policy"],"explanation":{"intro":"US-Germany relations vocabulary covers the transatlantic alliance, trade, and geopolitical tensions at B2.","culturalNote":"Germany-US relationship: cornerstone of German foreign policy since WWII. Key milestones: Marshall Plan, Berlin Airlift 1948, NATO membership 1955, German reunification 1990 (US support crucial). Key tensions: Trumpism (America First vs. multilateralism), trade disputes (Strafzölle — tariffs), NSA-Affäre (2013 — Merkel phone surveillance), NordStream/Russia policy differences, defense spending (2% GDP NATO target). Key frame: transatlantische Partnerschaft (transatlantic partnership)."},"examples":[{"german":"Die transatlantische Partnerschaft bleibt trotz periodischer Spannungen das strukturierende Fundament der deutschen Außenpolitik, da sie Sicherheits- und Wertegemeinschaft verbindet.","english":"The transatlantic partnership remains, despite periodic tensions, the structuring foundation of German foreign policy, as it combines a security and values community."},{"german":"Die Abhängigkeit Europas von amerikanischer Sicherheitsarchitektur wirft zunehmend Fragen nach europäischer strategischer Autonomie auf.","english":"Europe''s dependence on American security architecture is increasingly raising questions about European strategic autonomy."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss US-Germany relations, NATO, and transatlantic policy at B2."}}',
'{"items":[{"word":"das Fundament","translation":"foundation","pronunciation":"dahs foon-dah-MENT","example":"Strukturierendes Fundament."},{"word":"strukturierend","translation":"structuring/organising","pronunciation":"shtroock-too-REER-end","example":"Strukturierendes Element."},{"word":"die Wertegemeinschaft","translation":"community of values","pronunciation":"dee VER-teh-geh-myn-shaft","example":"Wertegemeinschaft."},{"word":"die Sicherheitsarchitektur","translation":"security architecture","pronunciation":"dee ZI-kher-hyts-ar-ki-tek-toor","example":"Amerikanische Sicherheitsarchitektur."},{"word":"strategisch","translation":"strategic","pronunciation":"shtrah-TAY-gish","example":"Strategische Autonomie."},{"word":"die Autonomie","translation":"autonomy","pronunciation":"dee ow-to-no-MEE","example":"Strategische Autonomie."}]}',
'{"title":"Fragen aufwerfen — to raise questions (about)","pattern":"etwas wirft Fragen auf = something raises questions (about) (separable — usually: wirft Fragen...auf)","explanation":"Fragen aufwerfen (separable) = to raise questions. Die Abhängigkeit wirft Fragen nach europäischer Autonomie auf = Dependence is raising questions about European autonomy. Present: wirft auf. Perfect: hat aufgeworfen. Fragen nach + dative = questions about. This construction signals that something is prompting debate or concern (often a problem or development). Compare: Fragen stellen (to ask questions — personal act), Bedenken aufwerfen (to raise concerns — slightly stronger than Fragen), thematisieren (to raise as a topic).","examples":[{"sentence":"Der Bericht wirft grundlegende Fragen nach der Finanzierung auf.","translation":"The report raises fundamental questions about the financing."},{"sentence":"Die Entscheidung wirft ethische Fragen auf.","translation":"The decision raises ethical questions."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Das Fundament'' means?","options":["foundation","basis","base","bedrock"],"correctAnswer":"foundation"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The transatlantic partnership remains, despite periodic tensions, the structuring foundation of German foreign policy, as it combines a security and values community.","options":["Die transatlantische Partnerschaft bleibt trotz periodischer Spannungen das strukturierende Fundament der deutschen Außenpolitik, da sie Sicherheits- und Wertegemeinschaft verbindet.","Die transatlantische Partnerschaft ist wichtig für Deutschlands Sicherheit.","Trotz Spannungen bleibt die Partnerschaft mit den USA stabil.","Deutschland braucht die USA als Partner für Sicherheit und Werte."],"correctAnswer":"Die transatlantische Partnerschaft bleibt trotz periodischer Spannungen das strukturierende Fundament der deutschen Außenpolitik, da sie Sicherheits- und Wertegemeinschaft verbindet."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Bericht wirft grundlegende Fragen nach der Finanzierung ___.","options":["auf","hervor","aus","auf"],"correctAnswer":"auf"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The decision raises ethical questions","wordBankItems":["Die","Entscheidung","wirft","ethische","Fragen","auf","."],"correctAnswer":"Die Entscheidung wirft ethische Fragen auf ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Strategisch'' means?","options":["strategic","tactical","geopolitical","political"],"correctAnswer":"strategic"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000229',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss Franco-German relations at B2","Use deutsch-französisch vocabulary","Talk about the EU motor"],"explanation":{"intro":"Franco-German relations vocabulary covers the bilateral relationship, EU leadership, and historical reconciliation at B2.","culturalNote":"Deutsch-Französische Beziehungen: historically enemies (3 wars 1870-1945), now key EU partnership. Key milestones: Élysée-Vertrag 1963 (Adenauer-de Gaulle), DFJW (youth exchange office), Aachen Treaty 2019 (updated cooperation). Key tensions: economic divergence (German Ordoliberalismus vs. French dirigisme), defense integration (PESCO, FCAS joint fighter jet delays), eurobond debate. Key figure: Macron-Scholz/Macron-Merkel dynamics. Deutsch-Französische Parlamentarische Versammlung (joint parliamentary assembly)."},"examples":[{"german":"Die deutsch-französische Achse gilt traditionell als Motor der europäischen Integration, gerät aber in jüngster Zeit durch unterschiedliche wirtschafts- und sicherheitspolitische Vorstellungen unter Druck.","english":"The Franco-German axis is traditionally regarded as the motor of European integration, but has recently come under pressure through differing economic and security policy ideas."},{"german":"Die historische Versöhnung zwischen Deutschland und Frankreich gilt als Modell dafür, wie einstige Erzfeinde durch gemeinsame Institutionen und gesellschaftlichen Austausch echten Frieden schaffen können.","english":"The historical reconciliation between Germany and France is regarded as a model of how former arch-enemies can create genuine peace through shared institutions and societal exchange."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss Franco-German relations, EU leadership, and historical reconciliation at B2."}}',
'{"items":[{"word":"die Achse","translation":"axis","pronunciation":"dee AKH-seh","example":"Deutsch-französische Achse."},{"word":"die Versöhnung","translation":"reconciliation","pronunciation":"dee fer-ZÖH-noong","example":"Historische Versöhnung."},{"word":"der Erzfeind","translation":"arch-enemy","pronunciation":"dayr ERTS-fynd","example":"Einstige Erzfeinde."},{"word":"einstig","translation":"former/erstwhile","pronunciation":"YN-stikh","example":"Einstige Feinde."},{"word":"die Vorstellung","translation":"idea/conception","pronunciation":"dee FOR-shtel-oong","example":"Unterschiedliche Vorstellungen."},{"word":"unter Druck geraten","translation":"to come under pressure","pronunciation":"oon-ter drook geh-RAH-ten","example":"Unter Druck geraten."}]}',
'{"title":"Unter Druck geraten — to come under pressure (begin to experience pressure)","pattern":"unter Druck geraten = to come under pressure (begin a state of pressure — geraten signals onset of state)","explanation":"Unter Druck geraten = to come under pressure (geraten = to get into, to fall into a state — signals onset). Die Achse gerät unter Druck = The axis is coming under pressure. Geraten + unter/in + accusative (states/situations): in Vergessenheit geraten (to fall into oblivion), in Verdacht geraten (to fall under suspicion), in Schwierigkeiten geraten (to get into difficulties). Compare: unter Druck stehen (to be under pressure — ongoing state), unter Druck gesetzt werden (to be put under pressure — by external agent).","examples":[{"sentence":"Die Koalition geriet nach dem Skandal unter erheblichen Druck.","translation":"The coalition came under considerable pressure after the scandal."},{"sentence":"Das Projekt geriet in ernsthafte Schwierigkeiten.","translation":"The project got into serious difficulties."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Versöhnung'' means?","options":["reconciliation","settlement","resolution","peacemaking"],"correctAnswer":"reconciliation"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The Franco-German axis is traditionally regarded as the motor of European integration, but has recently come under pressure through differing economic and security policy ideas.","options":["Die deutsch-französische Achse gilt traditionell als Motor der europäischen Integration, gerät aber in jüngster Zeit durch unterschiedliche wirtschafts- und sicherheitspolitische Vorstellungen unter Druck.","Deutschland und Frankreich treiben die EU gemeinsam voran.","Die Beziehung zwischen Deutschland und Frankreich ist angespannt.","Unterschiedliche Ansichten belasten die deutsch-französische Partnerschaft."],"correctAnswer":"Die deutsch-französische Achse gilt traditionell als Motor der europäischen Integration, gerät aber in jüngster Zeit durch unterschiedliche wirtschafts- und sicherheitspolitische Vorstellungen unter Druck."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Koalition geriet nach dem Skandal unter erheblichen ___.","options":["Druck","Zwang","Belastung","Stress"],"correctAnswer":"Druck"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The project got into serious difficulties","wordBankItems":["Das","Projekt","geriet","in","ernsthafte","Schwierigkeiten","."],"correctAnswer":"Das Projekt geriet in ernsthafte Schwierigkeiten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Einstig'' means?","options":["former/erstwhile","previous","past","old"],"correctAnswer":"former/erstwhile"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000022a',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss Russia-Ukraine conflict at B2","Use Russland Ukraine vocabulary","Talk about the war and Germany''s response"],"explanation":{"intro":"Russia-Ukraine conflict vocabulary covers the invasion, international response, and energy dependency at B2.","culturalNote":"Russia''s invasion of Ukraine February 2022: Zeitenwende for Germany. German response: initially hesitant weapons deliveries, then €100bn Bundeswehr fund, Leopard 2 tanks decision Jan 2023. Energy dependency: Wandel durch Handel (change through trade — assumption behind Nord Stream). LNG terminals built rapidly. Sanctions (Sanktionen), Flüchtlinge aus Ukraine (~1 million in Germany). Debate: until when to support Ukraine, reconstruction, war crimes tribunal."},"examples":[{"german":"Russlands Angriffskrieg gegen die Ukraine hat die europäische Sicherheitsordnung erschüttert und die Annahme widerlegt, dass wirtschaftliche Verflechtung Konflikte verhindert.","english":"Russia''s war of aggression against Ukraine has shaken the European security order and refuted the assumption that economic interdependence prevents conflicts."},{"german":"Deutschland hat seine Energieabhängigkeit von Russland rascher abgebaut als erwartet, jedoch um den Preis erheblich gestiegener Energiekosten für Industrie und Verbraucher.","english":"Germany has reduced its energy dependence on Russia more quickly than expected, but at the price of considerably increased energy costs for industry and consumers."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss Russia''s invasion of Ukraine, Germany''s response, and energy dependency at B2."}}',
'{"items":[{"word":"erschüttern","translation":"to shake/shatter","pronunciation":"er-SHÜT-ern","example":"Die Ordnung erschüttern."},{"word":"widerlegen","translation":"to refute","pronunciation":"VI-der-lay-gen","example":"Eine Annahme widerlegen."},{"word":"die Verflechtung","translation":"interdependence/entanglement","pronunciation":"dee fer-FLEKH-toong","example":"Wirtschaftliche Verflechtung."},{"word":"abbauen","translation":"to reduce/dismantle","pronunciation":"AP-bow-en","example":"Abhängigkeit abbauen."},{"word":"der Preis","translation":"price/cost","pronunciation":"dayr prys","example":"Um den Preis gestiegener Kosten."},{"word":"der Angriffskrieg","translation":"war of aggression","pronunciation":"dayr AN-grifs-kreeg","example":"Angriffskrieg."}]}',
'{"title":"Um den Preis + genitive — at the price of, at the cost of","pattern":"um den Preis + genitive = at the price of, at the cost of (something valuable was sacrificed)","explanation":"Um den Preis + genitive = at the price of (something valuable was given up to achieve the result). Deutschland baute Abhängigkeit ab, um den Preis gestiegener Energiekosten = Germany reduced dependence at the price of increased energy costs. The phrase marks a trade-off: something was achieved, but something valuable was paid. Compare: auf Kosten (at the expense of — slightly less emphasising the trade-off), zum Preis (at the price of — same meaning, less idiomatic), unter Inkaufnahme (accepting the cost of — very formal).","examples":[{"sentence":"Der Sieg wurde errungen, um den Preis enormer Verluste.","translation":"The victory was won at the price of enormous losses."},{"sentence":"Die Reform wurde durchgesetzt, um den Preis sozialer Spannungen.","translation":"The reform was pushed through at the price of social tensions."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Verflechtung'' means?","options":["interdependence/entanglement","connection","integration","network"],"correctAnswer":"interdependence/entanglement"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Russia''s war of aggression against Ukraine has shaken the European security order and refuted the assumption that economic interdependence prevents conflicts.","options":["Russlands Angriffskrieg gegen die Ukraine hat die europäische Sicherheitsordnung erschüttert und die Annahme widerlegt, dass wirtschaftliche Verflechtung Konflikte verhindert.","Der Ukraine-Krieg hat Europa verändert.","Wirtschaftliche Verflechtung verhindert Kriege nicht immer.","Russland hat die europäische Sicherheitsordnung herausgefordert."],"correctAnswer":"Russlands Angriffskrieg gegen die Ukraine hat die europäische Sicherheitsordnung erschüttert und die Annahme widerlegt, dass wirtschaftliche Verflechtung Konflikte verhindert."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Sieg wurde errungen, um den Preis enormer ___.","options":["Verluste","Opfer","Kosten","Schäden"],"correctAnswer":"Verluste"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The reform was pushed through at the price of social tensions","wordBankItems":["Die","Reform","wurde","durchgesetzt",",","um","den","Preis","sozialer","Spannungen","."],"correctAnswer":"Die Reform wurde durchgesetzt , um den Preis sozialer Spannungen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Erschüttern'' means?","options":["to shake/shatter","to disturb","to unsettle","to destabilise"],"correctAnswer":"to shake/shatter"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000022b',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss China and Asia at B2","Use China-Politik vocabulary","Talk about Germany''s China strategy"],"explanation":{"intro":"China and Asia policy vocabulary covers trade dependency, geopolitics, and Germany''s China strategy at B2.","culturalNote":"Germany-China: key trade partner (China biggest trading partner for Germany since 2017). Key issues: Abhängigkeit (dependency — VW, BMW, BASF heavy China exposure), Entkopplung vs. De-Risking (decoupling vs. reducing risk — policy debate), China-Strategie (published 2023 — first standalone China strategy), Systemrivalität (systemic rivalry). Taiwan-Frage (Taiwan question). Key events: BRI (Belt and Road — Duisburg as main terminal), Huawei 5G debate."},"examples":[{"german":"Die wirtschaftliche Verflechtung mit China bietet einerseits erhebliche Exportchancen, schafft andererseits strategische Abhängigkeiten, die im Falle geopolitischer Spannungen zur Verwundbarkeit werden.","english":"Economic interdependence with China offers, on the one hand, considerable export opportunities, but on the other creates strategic dependencies that become a vulnerability in the event of geopolitical tensions."},{"german":"Das Konzept des De-Riskings zielt darauf ab, wirtschaftliche Beziehungen zu China aufrechtzuerhalten, gleichzeitig jedoch kritische Abhängigkeiten in strategisch sensiblen Bereichen zu reduzieren.","english":"The concept of de-risking aims to maintain economic relations with China while at the same time reducing critical dependencies in strategically sensitive areas."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss Germany''s China policy, de-risking, and trade dependency at B2."}}',
'{"items":[{"word":"aufrechterhalten","translation":"to maintain","pronunciation":"OWF-rekht-er-hal-ten","example":"Beziehungen aufrechterhalten."},{"word":"sensibel","translation":"sensitive","pronunciation":"zen-ZEE-bel","example":"Strategisch sensible Bereiche."},{"word":"die Exportchance","translation":"export opportunity","pronunciation":"dee eks-PORT-khan-seh","example":"Erhebliche Exportchancen."},{"word":"im Falle","translation":"in the event of","pronunciation":"im FAL-eh","example":"Im Falle von Spannungen."},{"word":"geopolitisch","translation":"geopolitical","pronunciation":"geh-o-po-LI-tish","example":"Geopolitische Spannungen."},{"word":"das De-Risking","translation":"de-risking","pronunciation":"dahs dee-RIS-king","example":"Konzept des De-Riskings."}]}',
'{"title":"Im Falle + genitive — in the event of, in case of","pattern":"im Falle + genitive = in the event of, in case of (formal conditional — for hypothetical or anticipated situations)","explanation":"Im Falle + genitive = in the event of, in the case of (formal). Im Falle geopolitischer Spannungen = in the event of geopolitical tensions. More formal than wenn or falls. Often used in contracts, legal language, policy documents. Compare: im Fall dass (in the case that — with clause), falls (if/in case — less formal), für den Fall, dass (in case — slightly more emphatic conditional).","examples":[{"sentence":"Im Falle eines Ausfalls ist ein Notstromaggregat verfügbar.","translation":"In the event of a power failure, a backup generator is available."},{"sentence":"Im Falle von Beschwerden wenden Sie sich bitte an den Kundenservice.","translation":"In case of complaints, please contact customer service."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Aufrechterhalten'' means?","options":["to maintain","to uphold","to preserve","to keep up"],"correctAnswer":"to maintain"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Economic interdependence with China offers, on the one hand, considerable export opportunities, but on the other creates strategic dependencies that become a vulnerability in the event of geopolitical tensions.","options":["Die wirtschaftliche Verflechtung mit China bietet einerseits erhebliche Exportchancen, schafft andererseits strategische Abhängigkeiten, die im Falle geopolitischer Spannungen zur Verwundbarkeit werden.","China ist ein wichtiger Handelspartner, aber auch ein geopolitisches Risiko.","Exportchancen und Abhängigkeiten sind zwei Seiten der China-Beziehung.","Wirtschaftliche Abhängigkeit von China kann zur Schwäche werden."],"correctAnswer":"Die wirtschaftliche Verflechtung mit China bietet einerseits erhebliche Exportchancen, schafft andererseits strategische Abhängigkeiten, die im Falle geopolitischer Spannungen zur Verwundbarkeit werden."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Im Falle eines Ausfalls ist ein Notstromaggregat ___.","options":["verfügbar","vorhanden","bereit","zugänglich"],"correctAnswer":"verfügbar"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: In case of complaints please contact customer service","wordBankItems":["Im","Falle","von","Beschwerden","wenden","Sie","sich","bitte","an","den","Kundenservice","."],"correctAnswer":"Im Falle von Beschwerden wenden Sie sich bitte an den Kundenservice ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Sensibel'' means?","options":["sensitive","delicate","fragile","careful"],"correctAnswer":"sensitive"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000022c',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss the Middle East at B2","Use Naher Osten vocabulary","Talk about Israel-Palestine and regional conflicts"],"explanation":{"intro":"Middle East vocabulary covers regional conflicts, Israel-Palestine, and Germany''s special relationship with Israel at B2.","culturalNote":"Germany''s Naher Osten policy: Staatsräson — unconditional support for Israel''s security (Merkel 2008: Israel''s existence is German Staatsräson). October 7, 2023 Hamas attack and subsequent Gaza war prompted intense German debate. Zwei-Staaten-Lösung (two-state solution) official policy. Germany is also a major donor to UNRWA and Palestinian Authority. Key tensions: balancing Israel support with humanitarian law, Palestinian civilian casualties, arms export debate."},"examples":[{"german":"Deutschlands Nahostpolitik wird von dem historisch begründeten Grundsatz geleitet, dass Israels Sicherheit zur deutschen Staatsräson gehört.","english":"Germany''s Middle East policy is guided by the historically grounded principle that Israel''s security belongs to German reasons of state."},{"german":"Die Spannungen zwischen humanitärem Völkerrecht und politischer Solidarität stellen Demokratien in Konflikten wie dem israelisch-palästinensischen vor schwer auflösbare Dilemmata.","english":"The tensions between international humanitarian law and political solidarity confront democracies with hard-to-resolve dilemmas in conflicts such as the Israeli-Palestinian one."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss the Middle East, Germany''s Israel policy, and humanitarian law at B2."}}',
'{"items":[{"word":"die Staatsräson","translation":"reasons of state","pronunciation":"dee SHTAHTS-rä-zon","example":"Deutschlands Staatsräson."},{"word":"leiten","translation":"to guide/lead","pronunciation":"LY-ten","example":"Von einem Grundsatz geleitet."},{"word":"historisch begründet","translation":"historically grounded","pronunciation":"his-TO-rish beh-GRÜN-det","example":"Historisch begründeter Grundsatz."},{"word":"auflösbar","translation":"resolvable","pronunciation":"OWF-lös-bahr","example":"Schwer auflösbare Dilemmata."},{"word":"das Dilemma","translation":"dilemma","pronunciation":"dahs di-LEM-ah","example":"Schwer auflösbares Dilemma."},{"word":"konfrontieren mit","translation":"to confront with","pronunciation":"kon-fron-TEER-en mit","example":"Mit Dilemmata konfrontieren."}]}',
'{"title":"Von etwas geleitet werden — to be guided by something","pattern":"von etwas geleitet werden = to be guided by something (passive — the policy/action has a guiding principle)","explanation":"Von X geleitet werden = to be guided by X. Deutschlands Politik wird von dem Grundsatz geleitet... = Germany''s policy is guided by the principle... Used when a principle or value directs the action (without controlling it in a mechanical way). Perfect: wurde geleitet. Compare: durch X bestimmt werden (to be determined by — stronger influence), von X getragen werden (to be carried/sustained by — more support than direction), sich von X leiten lassen (to allow oneself to be guided by — reflexive, more personal/voluntary).","examples":[{"sentence":"Die Entscheidung wurde von ethischen Grundsätzen geleitet.","translation":"The decision was guided by ethical principles."},{"sentence":"Lass dich von Vernunft, nicht von Emotionen leiten.","translation":"Let yourself be guided by reason, not emotions."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Die Staatsräson'' means?","options":["reasons of state","state interest","national security","state doctrine"],"correctAnswer":"reasons of state"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Germany''s Middle East policy is guided by the historically grounded principle that Israel''s security belongs to German reasons of state.","options":["Deutschlands Nahostpolitik wird von dem historisch begründeten Grundsatz geleitet, dass Israels Sicherheit zur deutschen Staatsräson gehört.","Deutschland unterstützt Israel unbedingt.","Israels Sicherheit ist ein fundamentales Prinzip der deutschen Außenpolitik.","Deutschlands Nahostpolitik basiert auf historischer Verantwortung gegenüber Israel."],"correctAnswer":"Deutschlands Nahostpolitik wird von dem historisch begründeten Grundsatz geleitet, dass Israels Sicherheit zur deutschen Staatsräson gehört."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Die Entscheidung wurde von ethischen Grundsätzen ___.","options":["geleitet","geführt","bestimmt","geleitet"],"correctAnswer":"geleitet"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Let yourself be guided by reason not emotions","wordBankItems":["Lass","dich","von","Vernunft",",","nicht","von","Emotionen",",","leiten","."],"correctAnswer":"Lass dich von Vernunft , nicht von Emotionen , leiten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Auflösbar'' means?","options":["resolvable","solvable","dissolvable","workable"],"correctAnswer":"resolvable"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000022d',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss the United Nations at B2","Use Vereinte Nationen vocabulary","Talk about UN reform"],"explanation":{"intro":"United Nations vocabulary covers UN structure, mandate, reform, and Germany''s role at B2.","culturalNote":"Germany and the UN: founding member of UN 1973 (both German states), second-largest financial contributor. Key bodies: Sicherheitsrat (Security Council — Germany a non-permanent member twice), Generalversammlung (General Assembly), Menschenrechtsrat, UN Organisationen (WHO, WFP, UNHCR, UNESCO). Germany pushes for UN reform: permanent UNSC seat aspiration, vetoreform debate. Responsibility to Protect (R2P) — Germany supporter. SDGs (Nachhaltigkeitsziele)."},"examples":[{"german":"Das Vetorecht der ständigen Mitglieder des Sicherheitsrats lähmt in Konflikten, in denen Großmächte beteiligt sind, die Fähigkeit der Vereinten Nationen zum kollektiven Handeln.","english":"The veto right of the permanent members of the Security Council paralyses the United Nations'' capacity for collective action in conflicts in which great powers are involved."},{"german":"Eine Reform der Vereinten Nationen ist überfällig, scheitert jedoch regelmäßig am Widerstand der Vetomächte, die eine Erosion ihrer Privilegien befürchten.","english":"A reform of the United Nations is overdue, but regularly fails due to the resistance of the veto powers, who fear an erosion of their privileges."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss the UN, Security Council, veto power, and UN reform at B2."}}',
'{"items":[{"word":"lähmen","translation":"to paralyse","pronunciation":"LÄ-men","example":"Handlungsfähigkeit lähmen."},{"word":"scheitern an","translation":"to fail due to","pronunciation":"SHYTE-ern an","example":"An Widerstand scheitern."},{"word":"überfällig","translation":"overdue","pronunciation":"ü-ber-FÄL-ikh","example":"Überfällige Reform."},{"word":"die Erosion","translation":"erosion","pronunciation":"dee eh-ro-ZYOHN","example":"Erosion von Privilegien."},{"word":"das Vetorecht","translation":"veto right","pronunciation":"dahs VAY-to-rekht","example":"Vetorecht."},{"word":"befürchten","translation":"to fear","pronunciation":"beh-FÜRKH-ten","example":"Erosion befürchten."}]}',
'{"title":"Scheitern an — to fail due to, founder on (separable/intransitive)","pattern":"etwas scheitert an + dative = something fails due to, founders on (the dative is what causes the failure)","explanation":"Scheitern an + dative = to fail due to, to founder on. Die Reform scheitert am Widerstand = The reform fails due to resistance. Scheitern is intransitive (no accusative object) — the subject fails; the dative explains why. Perfect: ist gescheitert (sein — change of state). Der Scheiterhaufen = stake/pyre (historical), das Scheitern = failure. Compare: versagen (to fail — performance failure), misslingen (to fail — not succeed), auf Ablehnung stoßen (to meet with rejection).","examples":[{"sentence":"Das Projekt scheiterte an fehlenden Finanzmitteln.","translation":"The project failed due to lack of funds."},{"sentence":"Die Verhandlungen scheiterten an gegensätzlichen Interessen.","translation":"The negotiations failed due to conflicting interests."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Überfällig'' means?","options":["overdue","late","delayed","pending"],"correctAnswer":"overdue"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"A reform of the United Nations is overdue, but regularly fails due to the resistance of the veto powers, who fear an erosion of their privileges.","options":["Eine Reform der Vereinten Nationen ist überfällig, scheitert jedoch regelmäßig am Widerstand der Vetomächte, die eine Erosion ihrer Privilegien befürchten.","Die UN braucht eine Reform, aber die Großmächte blockieren sie.","Vetomächte verhindern eine Reform des Sicherheitsrats.","Eine UN-Reform ist nötig, aber politisch schwierig durchzusetzen."],"correctAnswer":"Eine Reform der Vereinten Nationen ist überfällig, scheitert jedoch regelmäßig am Widerstand der Vetomächte, die eine Erosion ihrer Privilegien befürchten."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Das Projekt scheiterte an fehlenden ___.","options":["Finanzmitteln","Geldern","Ressourcen","Mitteln"],"correctAnswer":"Finanzmitteln"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The negotiations failed due to conflicting interests","wordBankItems":["Die","Verhandlungen","scheiterten","an","gegensätzlichen","Interessen","."],"correctAnswer":"Die Verhandlungen scheiterten an gegensätzlichen Interessen ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Lähmen'' means?","options":["to paralyse","to cripple","to immobilise","to impair"],"correctAnswer":"to paralyse"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000022e',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss human rights at B2","Use Menschenrechte vocabulary","Talk about human rights law and violations"],"explanation":{"intro":"Human rights vocabulary covers international human rights law, Germany''s human rights policy, and enforcement at B2.","culturalNote":"Germany''s human rights policy: central to foreign policy self-understanding. Key instruments: Allgemeine Erklärung der Menschenrechte (UDHR 1948), EMRK (European Convention on Human Rights — binding on Germany), Grundgesetz Art. 1 (dignity as inviolable). Germany hosts key institutions: International Criminal Court (ICC) supports. Key debates: universelle vs. kulturrelative Menschenrechte (universal vs. culturally relative), wirtschaftliche Menschenrechte (economic human rights — right to housing, food), Menschenrechte und Handelspolitik (human rights and trade)."},"examples":[{"german":"Die Universalität der Menschenrechte ist nach wie vor umstritten, da einige Staaten kulturelle Besonderheiten als Begründung für Abweichungen vom internationalen Standard geltend machen.","english":"The universality of human rights is still disputed, since some states invoke cultural particularities as justification for deviations from the international standard."},{"german":"Der Schutz der Menschenrechte setzt wirksame Durchsetzungsmechanismen voraus, an denen es auf internationaler Ebene nach wie vor mangelt.","english":"The protection of human rights presupposes effective enforcement mechanisms, which are still lacking at the international level."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss human rights, universality, and enforcement mechanisms at B2."}}',
'{"items":[{"word":"umstritten","translation":"disputed/controversial","pronunciation":"OOM-shtri-ten","example":"Nach wie vor umstritten."},{"word":"geltend machen","translation":"to invoke/assert","pronunciation":"GEL-tend MAKHen","example":"Besonderheiten geltend machen."},{"word":"die Besonderheit","translation":"particularity/characteristic","pronunciation":"dee beh-ZON-der-hyt","example":"Kulturelle Besonderheiten."},{"word":"die Abweichung","translation":"deviation","pronunciation":"dee AP-vy-khoong","example":"Abweichungen vom Standard."},{"word":"mangeln an","translation":"to lack","pronunciation":"MAN-geln an","example":"Es mangelt an Mechanismen."},{"word":"der Durchsetzungsmechanismus","translation":"enforcement mechanism","pronunciation":"dayr DOORKH-zetsoongs-meh-khan-is-moos","example":"Durchsetzungsmechanismen."}]}',
'{"title":"Es mangelt an — there is a lack of (impersonal)","pattern":"es mangelt an + dative = there is a lack of, X is lacking (impersonal construction)","explanation":"Es mangelt an + dative = there is a lack of, X is lacking. Es mangelt an Durchsetzungsmechanismen = Enforcement mechanisms are lacking. Impersonal subject es (=it/there). Perfect: es hat gemangelt an. Alternatively: X mangelt (es mangelt am Geld = money is lacking). Der Mangel = lack, deficiency, shortage. Compare: fehlen an (to be missing — more neutral: es fehlt an Zeit = time is lacking), es gibt keinen/keine (there is no), entbehren (literary: to lack).","examples":[{"sentence":"Es mangelt an politischem Willen, die notwendigen Reformen durchzusetzen.","translation":"There is a lack of political will to push through the necessary reforms."},{"sentence":"In der Region mangelt es an sauberem Trinkwasser.","translation":"The region lacks clean drinking water."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Umstritten'' means?","options":["disputed/controversial","contested","debated","questioned"],"correctAnswer":"disputed/controversial"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The universality of human rights is still disputed, since some states invoke cultural particularities as justification for deviations from the international standard.","options":["Die Universalität der Menschenrechte ist nach wie vor umstritten, da einige Staaten kulturelle Besonderheiten als Begründung für Abweichungen vom internationalen Standard geltend machen.","Manche Staaten lehnen universelle Menschenrechte ab.","Kulturelle Unterschiede werden zur Rechtfertigung von Menschenrechtsverletzungen genutzt.","Die Universalität von Menschenrechten ist politisch umkämpft."],"correctAnswer":"Die Universalität der Menschenrechte ist nach wie vor umstritten, da einige Staaten kulturelle Besonderheiten als Begründung für Abweichungen vom internationalen Standard geltend machen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Es mangelt an politischem Willen, die notwendigen Reformen ___.","options":["durchzusetzen","einzuführen","umzusetzen","zu verwirklichen"],"correctAnswer":"durchzusetzen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: The region lacks clean drinking water","wordBankItems":["In","der","Region","mangelt","es","an","sauberem","Trinkwasser","."],"correctAnswer":"In der Region mangelt es an sauberem Trinkwasser ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Geltend machen'' means?","options":["to invoke/assert","to claim","to argue","to advance"],"correctAnswer":"to invoke/assert"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-00000000022f',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss international law at B2","Use Völkerrecht vocabulary","Talk about international legal norms"],"explanation":{"intro":"International law vocabulary covers the structure of international law, state sovereignty, and enforcement at B2.","culturalNote":"Völkerrecht (international law): Germany is a strong advocate. Key principles: Souveränität (sovereignty), Gewaltverbot (prohibition of force — UN Charter Art. 2(4)), Nichteinmischung (non-interference), pacta sunt servanda (treaties must be observed). Key institutions: Internationaler Gerichtshof (ICJ — The Hague), Internationaler Strafgerichtshof (ICC — International Criminal Court, Rome Statute). Germany signed ICC. Key debates: Responsibility to Protect (Schutzverantwortung), Sanktionenrecht."},"examples":[{"german":"Das Gewaltverbot der UN-Charta ist ein Eckpfeiler des modernen Völkerrechts, dessen Verletzung — wie durch den russischen Angriff auf die Ukraine — die regelbasierte Weltordnung in ihren Grundfesten erschüttert.","english":"The prohibition of force in the UN Charter is a cornerstone of modern international law, the violation of which — as through Russia''s attack on Ukraine — shakes the rule-based world order to its foundations."},{"german":"Die effektive Durchsetzung des Völkerrechts bleibt eine fundamentale Herausforderung, da es kein internationales Polizei- oder Vollstreckungsorgan gibt.","english":"The effective enforcement of international law remains a fundamental challenge, as there is no international police or enforcement body."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss international law, the UN Charter, and enforcement challenges at B2."}}',
'{"items":[{"word":"der Eckpfeiler","translation":"cornerstone/pillar","pronunciation":"dayr EK-pfy-ler","example":"Eckpfeiler des Völkerrechts."},{"word":"in seinen Grundfesten","translation":"to its foundations","pronunciation":"in ZY-nen GROOND-fes-ten","example":"In den Grundfesten erschüttern."},{"word":"das Vollstreckungsorgan","translation":"enforcement body","pronunciation":"dahs FOL-shtreck-oonks-or-gahn","example":"Vollstreckungsorgan."},{"word":"regelbasiert","translation":"rule-based","pronunciation":"RAY-gel-bah-zeert","example":"Regelbasierte Weltordnung."},{"word":"die Weltordnung","translation":"world order","pronunciation":"dee VELT-or-dnoong","example":"Regelbasierte Weltordnung."},{"word":"das Gewaltverbot","translation":"prohibition of force","pronunciation":"dahs geh-VALT-fer-boht","example":"Gewaltverbot."}]}',
'{"title":"In seinen Grundfesten erschüttern — to shake to its foundations","pattern":"etwas in seinen Grundfesten erschüttern = to shake something to its very foundations (idiom for fundamental destabilisation)","explanation":"In seinen Grundfesten erschüttern = to shake to its foundations (idiomatic — very strong destabilisation of what was thought to be solid). Die Weltordnung in ihren Grundfesten erschüttern = to shake the world order to its foundations. Used for events that challenge the very basis of an institution, idea, or order. The Grundfesten (foundations, cornerstones) metaphor implies structural damage. Compare: erschüttern alone (to shake/shatter — milder, without ''to foundations'' adds), destabilisieren (to destabilise — more technical), infrage stellen (to call into question — less dramatic).","examples":[{"sentence":"Der Skandal hat das Vertrauen in die Institution in seinen Grundfesten erschüttert.","translation":"The scandal shook trust in the institution to its very foundations."},{"sentence":"Diese Entdeckung erschüttert das Wissenschaftssystem in seinen Grundfesten.","translation":"This discovery shakes the scientific system to its very foundations."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Der Eckpfeiler'' means?","options":["cornerstone/pillar","keystone","foundation stone","cornerpiece"],"correctAnswer":"cornerstone/pillar"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"The prohibition of force in the UN Charter is a cornerstone of modern international law, the violation of which shakes the rule-based world order to its foundations.","options":["Das Gewaltverbot der UN-Charta ist ein Eckpfeiler des modernen Völkerrechts, dessen Verletzung — wie durch den russischen Angriff auf die Ukraine — die regelbasierte Weltordnung in ihren Grundfesten erschüttert.","Das Gewaltverbot ist ein wichtiges Prinzip des Völkerrechts.","Russlands Angriff verletzt das Völkerrecht und untergräbt die Weltordnung.","Die UN-Charta verbietet Gewalt, aber Verletzungen untergraben die Weltordnung."],"correctAnswer":"Das Gewaltverbot der UN-Charta ist ein Eckpfeiler des modernen Völkerrechts, dessen Verletzung — wie durch den russischen Angriff auf die Ukraine — die regelbasierte Weltordnung in ihren Grundfesten erschüttert."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Der Skandal hat das Vertrauen in die Institution in seinen Grundfesten ___.","options":["erschüttert","zerstört","untergraben","erschüttert"],"correctAnswer":"erschüttert"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: This discovery shakes the scientific system to its very foundations","wordBankItems":["Diese","Entdeckung","erschüttert","das","Wissenschaftssystem","in","seinen","Grundfesten","."],"correctAnswer":"Diese Entdeckung erschüttert das Wissenschaftssystem in seinen Grundfesten ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Regelbasiert'' means?","options":["rule-based","regulated","standardised","norm-based"],"correctAnswer":"rule-based"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_lesson_versions (lesson_id,version,content_status,publication_status,content,vocabulary,grammar,exercises,frozen,published_at) VALUES
('aa000000-0000-0000-0000-000000000230',1,'APPROVED','PUBLISHED',
'{"objectives":["Discuss global justice at B2","Use globale Gerechtigkeit vocabulary","Talk about development, trade, and inequality"],"explanation":{"intro":"Global justice vocabulary covers development aid, trade justice, and North-South relations at B2.","culturalNote":"Deutschland und globale Gerechtigkeit: ODA (Official Development Assistance) — Germany 2nd largest donor (~€35bn/year). Key organisations: GIZ (Gesellschaft für Internationale Zusammenarbeit), KfW Entwicklungsbank. Key debates: Wirksamkeit der Entwicklungshilfe (effectiveness of aid), Abhängigkeit (dependency) vs. Partnerschaft (partnership), fairer Handel (fair trade), Handelsregeln (WTO), Schuldenentlastung (debt relief for developing countries). SDGs (17 sustainable development goals — 2030 Agenda)."},"examples":[{"german":"Globale Gerechtigkeit erfordert nicht nur Entwicklungshilfe, sondern eine grundlegende Veränderung der Welthandelsregeln, die strukturell ärmere Länder benachteiligen.","english":"Global justice requires not only development aid, but a fundamental change of world trade rules that structurally disadvantage poorer countries."},{"german":"Der Ansatz, Entwicklungszusammenarbeit als partnerschaftlich und nachfragegetrieben statt als paternalistisch und gebergetrieben zu gestalten, gewinnt zunehmend an Bedeutung.","english":"The approach of designing development cooperation as partnership-based and demand-driven rather than paternalistic and donor-driven is gaining increasing importance."}],"rewards":{"xp":150,"coins":80},"metadata":{"estimatedMinutes":20,"canDo":"I can discuss global justice, development policy, and trade equity at B2."}}',
'{"items":[{"word":"paternalistisch","translation":"paternalistic","pronunciation":"pah-ter-nah-LIS-tish","example":"Paternalistischer Ansatz."},{"word":"nachfragegetrieben","translation":"demand-driven","pronunciation":"NAKH-frah-geh-geh-tree-ben","example":"Nachfragegetriebene Hilfe."},{"word":"gebergetrieben","translation":"donor-driven","pronunciation":"GAY-ber-geh-tree-ben","example":"Gebergetriebene Entwicklungspolitik."},{"word":"an Bedeutung gewinnen","translation":"to gain in importance","pronunciation":"an beh-DOY-toong geh-VIN-en","example":"An Bedeutung gewinnen."},{"word":"partnerschaftlich","translation":"partnership-based","pronunciation":"PART-ner-shaft-likh","example":"Partnerschaftlicher Ansatz."},{"word":"strukturell benachteiligen","translation":"to structurally disadvantage","pronunciation":"shtroock-too-REL beh-NAKH-ty-li-gen","example":"Strukturell benachteiligen."}]}',
'{"title":"An Bedeutung gewinnen — to gain in importance","pattern":"etwas gewinnt an Bedeutung = something gains in importance (increases in importance over time)","explanation":"An Bedeutung gewinnen = to gain in importance, to become more important (intransitive — slow process of growing significance). An Bedeutung verlieren = to lose importance. Der Ansatz gewinnt zunehmend an Bedeutung = The approach is gaining increasing importance. Compare: wichtiger werden (to become more important — more direct), an Relevanz gewinnen (to gain in relevance — same pattern), in den Vordergrund treten (to come to the fore — more sudden prominence).","examples":[{"sentence":"Erneuerbare Energien haben in den letzten Jahren stark an Bedeutung gewonnen.","translation":"Renewable energies have gained greatly in importance in recent years."},{"sentence":"Datenschutz gewinnt in der digitalen Gesellschaft zunehmend an Bedeutung.","translation":"Data protection is gaining increasing importance in digital society."}]}',
'{"items":[{"id":"ex1","type":"MULTIPLE_CHOICE","question":"''Paternalistisch'' means?","options":["paternalistic","patronising","controlling","top-down"],"correctAnswer":"paternalistic"},{"id":"ex2","type":"TRANSLATE_TO_TARGET","question":"Global justice requires not only development aid, but a fundamental change of world trade rules that structurally disadvantage poorer countries.","options":["Globale Gerechtigkeit erfordert nicht nur Entwicklungshilfe, sondern eine grundlegende Veränderung der Welthandelsregeln, die strukturell ärmere Länder benachteiligen.","Entwicklungshilfe allein reicht für globale Gerechtigkeit nicht aus.","Welthandelsregeln müssen fairer werden.","Arme Länder werden durch Handelsregeln strukturell benachteiligt."],"correctAnswer":"Globale Gerechtigkeit erfordert nicht nur Entwicklungshilfe, sondern eine grundlegende Veränderung der Welthandelsregeln, die strukturell ärmere Länder benachteiligen."},{"id":"ex3","type":"FILL_IN_BLANK","question":"Erneuerbare Energien haben in den letzten Jahren stark an Bedeutung ___.","options":["gewonnen","zugenommen","gestiegen","gewachsen"],"correctAnswer":"gewonnen"},{"id":"ex4","type":"SENTENCE_CONSTRUCT","question":"Build: Data protection is gaining increasing importance in digital society","wordBankItems":["Datenschutz","gewinnt","in","der","digitalen","Gesellschaft","zunehmend","an","Bedeutung","."],"correctAnswer":"Datenschutz gewinnt in der digitalen Gesellschaft zunehmend an Bedeutung ."},{"id":"ex5","type":"MULTIPLE_CHOICE","question":"''Nachfragegetrieben'' means?","options":["demand-driven","demand-led","market-driven","consumer-driven"],"correctAnswer":"demand-driven"}]}'::jsonb,
true,NOW()) ON CONFLICT (lesson_id,version) DO NOTHING;

INSERT INTO cf_curriculum_lesson_plans (id, curriculum_id, level_id, unit_id, stable_ref, position, title, topic, plan_status) VALUES
('dd000000-0000-0000-0000-000000000227','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l551',551,'Außenpolitik','German foreign policy','PUBLISHED'),
('dd000000-0000-0000-0000-000000000228','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l552',552,'Deutsch-Amerikanische Beziehungen','US-Germany relations','PUBLISHED'),
('dd000000-0000-0000-0000-000000000229','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l553',553,'Deutsch-Französische Beziehungen','Franco-German relations','PUBLISHED'),
('dd000000-0000-0000-0000-00000000022a','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l554',554,'Russland und Ukraine','Russia and Ukraine','PUBLISHED'),
('dd000000-0000-0000-0000-00000000022b','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l555',555,'China und Asien','China and Asia','PUBLISHED'),
('dd000000-0000-0000-0000-00000000022c','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l556',556,'Naher Osten','Middle East','PUBLISHED'),
('dd000000-0000-0000-0000-00000000022d','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l557',557,'Vereinte Nationen','United Nations','PUBLISHED'),
('dd000000-0000-0000-0000-00000000022e','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l558',558,'Menschenrechte','Human rights','PUBLISHED'),
('dd000000-0000-0000-0000-00000000022f','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l559',559,'Völkerrecht','International law','PUBLISHED'),
('dd000000-0000-0000-0000-000000000230','00000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000004',NULL,'de-b2-u04-l560',560,'Globale Gerechtigkeit','Global justice','PUBLISHED')
ON CONFLICT (id) DO NOTHING;

UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000227' WHERE stable_ref = 'de-b2-u04-l551' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000228' WHERE stable_ref = 'de-b2-u04-l552' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000229' WHERE stable_ref = 'de-b2-u04-l553' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000022a' WHERE stable_ref = 'de-b2-u04-l554' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000022b' WHERE stable_ref = 'de-b2-u04-l555' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000022c' WHERE stable_ref = 'de-b2-u04-l556' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000022d' WHERE stable_ref = 'de-b2-u04-l557' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000022e' WHERE stable_ref = 'de-b2-u04-l558' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-00000000022f' WHERE stable_ref = 'de-b2-u04-l559' AND lesson_id IS NULL;
UPDATE cf_curriculum_lesson_plans SET lesson_id = 'aa000000-0000-0000-0000-000000000230' WHERE stable_ref = 'de-b2-u04-l560' AND lesson_id IS NULL;
